### ISSUE TITLE
failed to detect PyQt5

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1012]
`--version`
```
0.6.12.3
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\Андрей\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

Everything worked for me. But I reinstalled Windows and downloaded it all over again.

I had a python problem, it didn't see `PYQT5`. The solution was to copy the `platforms` folder from `C:\Users\Андрей\AppData\Local\Programs\Python\Python39\Lib\site-packages\PyQt5\Qt\plugins` plugins to `C:\Users\Андрей\AppData\Local\Programs\Python\Python39`
After that, the library started working for me. But when I try to compile, I get this output:

```
C:\Users\Андрей>python -m nuitka --mingw64 --standalone --windows-uac-admin --include-data-file=E:\test\test\icons\*=icons\ --include-data-file=E:\test\test\files\*=files\ --windows-company-name=test --windows-file-version=1.0.0 --windows-product-name=test --windows-file-description=testtest --windows-disable-console --windows-icon-from-ico=E:\test\Other\Media\test.ico --output-dir=E:\test\test\Current_build --plugin-enable=multiprocessing --plugin-enable=numpy --plugin-enable=qt-plugins  "E:\test\test\main.py"
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: qt-plugins: Injecting pre-module load code for module 'PyQt5':
Nuitka-Plugins:INFO: qt-plugins:     Adding binary folder to runtime 'PATH' environment variable for proper loading.
Nuitka-Plugins:INFO: qt-plugins: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: qt-plugins:     Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka-Plugins:INFO: qt-plugins:     system Qt plug-ins, which may be from another Qt version.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running 'C:\\Users\\A4F7~1\\AppData\\Local\\Nuitka\\Nuitka\\ccache\\v3.7.12\\ccache.exe "C:\\Users\\A4F7~1\\AppData\\Local\\Nuitka\\Nuitka\\gcc\\x86_64\\10.2.0-11.0.0-8.0.0-r5\\mingw64\\bin\\gcc.exe" -o "module.numpy.ma.core.o" -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_STANDALONE -D_NUITKA_WINMAIN_ENTRY_POINT -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=166 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -IC:\\Users\\Андрей\\AppData\\Local\\Programs\\Python\\Python39\\include -I. -IC:\\Users\\A4F7~1\\AppData\\Local\\Programs\\Python\\Python39\\lib\\SITE-P~1\\nuitka\\build\\include -IC:\\Users\\A4F7~1\\AppData\\Local\\Programs\\Python\\Python39\\lib\\SITE-P~1\\nuitka\\build\\static_src "module.numpy.ma.core.c"' took 69.99 seconds
Nuitka-Scons:INFO: Compiled 298 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 298
Nuitka-Postprocessing:INFO: Adding 1 icon(s) from icon 'file E:\test\Other\Media\test.ico'.
FATAL: qt-plugins: Error, failed to detect PyQt5 plugin directories.
```

This also does not work in the latest factory.

**Comment by kayhayen** [comment]
Manual copying is not supported and for good reasons.

Not detecting the PyQt5 plugin folder is bad and unusual. Can you checkout, what the code of "getPyQtPluginDirs" in  Nuitka executes, and why it fails to work for you?

**Comment by Pro100rus32** [comment]
_**qt 5.12.2**_
**My code:**
`Python 3.9.2`
```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Process returned 3221226505 (0xc0000409)        execution time : 1.277 s
```

_This used to work._


_**qt 5.12.3**_
**My code:**
`Python 3.9.2`

```
Traceback (most recent call last):
  File "E:\test\test\main.py", line 1, in <module>
    from test import *
  File "E:\test\test\test.py", line 34, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed while importing QtCore: Не найден указанный модуль.

Process returned 1 (0x1)        execution time : 0.429 s
```


Where can I find getPyQtPluginDirs?

**Comment by Pro100rus32** [comment]
**Last Factory:**
```
...
Nuitka-Scons:INFO: Compiled 299 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 299
Nuitka-Postprocessing:INFO: Adding 1 icon(s) from icon file 'E:\\test\\test\\Media\\Sp7EYBpX_hY.ico'.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: DLL load failed while importing QtCore: Не найден указанный модуль.
Traceback (most recent call last):
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 185, in <module>
    main()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 171, in main
    MainControl.main()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 754, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\Plugins.py", line 353, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 183, in considerExtraDlls
    plugin_dirs = self.getPyQtPluginDirs(qt_version)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 129, in getPyQtPluginDirs
    output = Execution.check_output([sys.executable, "-c", command])
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\utils\Execution.py", line 169, in check_output
    raise subprocess.CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Users\\Андрей\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-c', 'from __future__ import print_function\nfrom __future__ import absolute_import\n\nimport PyQt5.QtCore\nfor v in PyQt5.QtCore.QCoreApplication.libraryPaths():\n    print(v)\nimport os\n# Standard CPython has installations like this.\nguess_path = os.path.join(os.path.dirname(PyQt5.__file__), "plugins")\nif os.path.exists(guess_path):\n    print("GUESS:", guess_path)\n# Anaconda has this, but it seems not automatic.\nguess_path = os.path.join(os.path.dirname(PyQt5.__file__), "..", "..", "..", "Library", "plugins")\nif os.path.exists(guess_path):\n    print("GUESS:", guess_path)\n']' returned non-zero exit status 1.
```

**Comment by kayhayen** [comment]
Well, it seems the PyQt5 you want to compile with doesn't load, not even uncompiled. Your PyQt5 installation is invalid, I guess not working at all for anything, because the scripts Nuitka executes there is not very demanding, it basically imports in and dumps a few values.

So I would call this one invalid as a bug report. Please make sure your original program works in the environment you compile it, I guess it does not?
