### ISSUE TITLE
Trouble  running pyttsx3 text to speech converter

### ISSUE THREAD

**Issue by Python-retropie-raspberry-pi-hobby** [Nuitka/Nuitka#1016]
I'm trying to build a voice assistant and I'm using nuitka for speed improvement.
```
0.6.12.3
Python: 3.7.3 (default, Jul 25 2020, 13:03:44) 
Executable: /usr/bin/python3
OS: Linux
Arch: armv7l
```
Here is my code:
```

from fuzzywuzzy import fuzz
import sys
import pyttsx3
engine = pyttsx3.init()
text = "Hairy activated"
voices = engine.getProperty("voices")
print(voices)
engine.setProperty("rate", 135)
engine.setProperty("voice", voices[10].id)
engine.say(text)
# play the speech
engine.runAndWait()
from os import environ, path
import os
#sys.path.insert(0, '/home/pi/AIY-voice-kit-python/src/examples/voice')
#from __init__ import LiveSpeech, get_model_path
from pocketsphinx import LiveSpeech, get_model_path
model_path = get_model_path()
print("active")
speech = LiveSpeech(
    verbose=False,
    sampling_rate=16000,
    buffer_size=2048,
    no_search=False,
    full_utt=False,
    hmm=os.path.join(model_path, 'en-us'),
    lm=os.path.join(model_path, 'en-us.lm.bin'),
    dic=os.path.join(model_path, 'cmudict-en-us.dict')
)

for phrase in speech:
    p = str(phrase)
    print(p)
    r1 = (fuzz.ratio(p,"harry"))
    print(r1)
    ri = int(r1)
    if ri > 59:
        text = "Yes?"
        engine.say(text)
``` 
 here is the command:
```
python3 -m nuitka --run --follow-imports /home/pi/Desktop/AIY-projects-python/src/examples/voice/speack.py
```
and here is the log:
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running /usr/bin/ccache /usr/bin/gcc -o module.pocketsphinx.pocketsphinx.o -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.7m -I. -I/usr/local/lib/python3.7/dist-packages/nuitka/build/include -I/usr/local/lib/python3.7/dist-packages/nuitka/build/static_src module.pocketsphinx.pocketsphinx.c took 68.31 seconds
Nuitka-Scons:INFO: Compiled 26 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 26
Nuitka:INFO: Keeping build directory 'speack.build'.
Nuitka:INFO: Successfully created 'speack.bin'.
Nuitka:INFO: Launching 'speack.bin'.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/AIY-projects-python/src/examples/voice/speack.py", line 4, in <module>
    engine = pyttsx3.init()
  File "/home/pi/.local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/pi/.local/lib/python3.7/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/pi/.local/lib/python3.7/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyttsx3.drivers'
```
Is there any more information you want? Please help as soon as you can.

**Comment by Ja7adR** [comment]
> I'm trying to build a voice assistant and I'm using nuitka for speed improvement.
> 
> ```
> 0.6.12.3
> Python: 3.7.3 (default, Jul 25 2020, 13:03:44) 
> Executable: /usr/bin/python3
> OS: Linux
> Arch: armv7l
...
> 
> Is there any more information you want? Please help as soon as you can.

hi, implement this issue and I get same error and I think nuitka can't follow **importlib** .

https://github.com/Nuitka/Nuitka/issues/1016

**Comment by kayhayen** [comment]
This is not standalone mode, so it wouldn't have to follow it for compilation, however, there are issues when things are mixed, compiled or not, then the loader of Python can't load the compiled stuff, and vice versa, so far it only loads extension modules, but not sourcefiles or bytecode. This is a missing feature indeed. 

The extension modules were most pressing, but this surely is annoying too. You can fix this potentially with provisions of --include-package on the trouble makers, so no mixing occurs, unless of course it's not found at compile time.

**Comment by Ja7adR** [comment]
> This is not standalone mode, so it wouldn't have to follow it for compilation, however, there are issues when things are mixed, compiled or not, then the loader of Python can't load the compiled stuff, and vice versa, so far it only loads extension modules, but not sourcefiles or bytecode. This is a missing feature indeed.
> 
> The extension modules were most pressing, but this surely is annoying too. You can fix this potentially with provisions of --include-package on the trouble makers, so no mixing occurs, unless of course it's not found at compile time.

Thank you @kayhayen `--include-package=src.modules` for me work.

**Comment by kayhayen** [comment]
This is the kind same issue as many times reported, you need to include more packages, because mixed loading doesn' work. It will eventually work, but it requires to implement loading source code from disk in Nuitka and byte compiling it, with caching, etc. which is not in strong demand normally. But it will happen. For now I am closing this as a duplicate.

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
@kayhayen I've edited my command:
```
 python3 -m nuitka --run --follow-imports --include-package=src.modules /home/pi/Desktop/AIY-projects-python/src/examples/voice/speack.py
``` 
and I got this error:
```
Nuitka:INFO: Starting Python compilation.
FATAL: Error, failed to locate package 'src.modules' you asked to include.
```
Do you know what is wrong?

**Comment by kayhayen** [comment]
@Python-retropie-raspberry-pi-hobby you might have to do that with ´pyttsx3.drivers` of course. Read up what these options do, then it should be something you get.

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
during GIMPLE pass: evrp
module.pyttsx3.six.c: In function ‘modulecode_pyttsx3$six’:
module.pyttsx3.six.c:40908:1: internal compiler error: in fold_binary_loc, at fold-const.c:9253
 }
 ^
0x76b16717 __libc_start_main
	/build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
scons: *** [module.pyttsx3.six.o] Error 1
Nuitka-Scons:INFO: Running /usr/bin/ccache /usr/bin/gcc -o module.pocketsphinx.pocketsphinx.o -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -I/usr/include/python3.7m -I. -I/usr/local/lib/python3.7/dist-packages/nuitka/build/include -I/usr/local/lib/python3.7/dist-packages/nuitka/build/static_src module.pocketsphinx.pocketsphinx.c took 76.83 seconds
``` 
I'm getting this now with the following command
```
python3 -m nuitka --run --follow-imports --include-package=pyttsx3.drivers /home/pi/Desktop/AIY-projects-python/src/examples/voice/speack.py
```

**Comment by kayhayen** [comment]
Internal compiler errors of gcc are none of Nuitka's business. Try having more memory, or try using clang.
