### ISSUE TITLE
Windows: Standalone dependency detection doesn't work in virtualenv on unicode home directories

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1018]
In search of a solution to #1012, I tried to run in Virtualenv

```
0.6.12.3
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: E:\PYPYthon\Scripts\python.exe
OS: Windows
Arch: x86_64
```

`python -m nuitka --mingw64 --standalone --plugin-enable=qt-plugins "C:\Users\Андрей\Desktop\main.py"`

```
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: qt-plugins: Injecting pre-module load code for module 'PyQt5':
Nuitka-Plugins:INFO: qt-plugins:     Adding binary folder to runtime 'PATH' environment variable for proper loading.
Nuitka-Plugins:INFO: qt-plugins: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: qt-plugins:     Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka-Plugins:INFO: qt-plugins:     system Qt plug-ins, which may be from another Qt version.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 15 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 15
Nuitka-Plugins:INFO: qt-plugins: Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'main.dist\PyQt5\qt-plugins'.
Nuitka-Plugins:INFO: qt-plugins: Copying OpenSSL DLLs to 'main.dist'.
Traceback (most recent call last):
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "E:\PYPYthon\lib\site-packages\nuitka\MainControl.py", line 747, in main
    copyUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1376, in copyUsedDLLs
    used_dlls = detectUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1311, in detectUsedDLLs
    worker_pool.submit(
  File "E:\PYPYthon\lib\site-packages\nuitka\utils\ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1280, in addDLLInfo
    used_dlls = detectBinaryDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1255, in detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1071, in detectBinaryPathDLLsWindowsDependencyWalker
    _parseDependsExeOutput(output_filename, result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 906, in _parseDependsExeOutput
    _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"), result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 891, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\users\\\x04\x04\x04\x04\x04\x04\\appdata\\local\\programs\\python\\python39\\python39.dll', '     [  6] c:\\users\\\x04\x04\x04\x04\x04\x04\\
appdata\\local\\programs\\python\\python39\\PYTHON39.DLL')
```

I tried to delete the `C:\Users\Андрей\AppData\Local\Nuitka` folder and restart the compilation, but it doesn't work:

```
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: qt-plugins: Injecting pre-module load code for module 'PyQt5':
Nuitka-Plugins:INFO: qt-plugins:     Adding binary folder to runtime 'PATH' environment variable for proper loading.
Nuitka-Plugins:INFO: qt-plugins: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: qt-plugins:     Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka-Plugins:INFO: qt-plugins:     system Qt plug-ins, which may be from another Qt version.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
Yes
Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r5/winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-m
ingw-w64-8.0.0-r5.zip'.
Nuitka:INFO: Extracting to 'C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe'
Nuitka-Scons:INFO: Backend C compiler: C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka will make use of ccache to speed up repeated compilation.

Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\ccache\v3.7.12".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
Yes
Nuitka:INFO: Downloading 'https://github.com/ccache/ccache/releases/download/v3.7.12/ccache-3.7.12-windows-32.zip'.
Nuitka:INFO: Extracting to 'C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\ccache\v3.7.12\ccache.exe'
Nuitka-Scons:INFO: Compiled 15 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 15
Nuitka-Plugins:INFO: qt-plugins: Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'main.dist\PyQt5\qt-plugins'.
Nuitka-Plugins:INFO: qt-plugins: Copying OpenSSL DLLs to 'main.dist'.
Nuitka will make use of Dependency Walker (https://dependencywalker.com) tool
to analyze the dependencies of Python extension modules.

Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\depends\x86_64".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
Yes
Nuitka:INFO: Downloading 'https://dependencywalker.com/depends22_x64.zip'.
Nuitka:INFO: Extracting to 'C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\depends\x86_64\depends.exe'
Traceback (most recent call last):
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "E:\PYPYthon\lib\site-packages\nuitka\MainControl.py", line 747, in main
    copyUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1376, in copyUsedDLLs
    used_dlls = detectUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1311, in detectUsedDLLs
    worker_pool.submit(
  File "E:\PYPYthon\lib\site-packages\nuitka\utils\ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1280, in addDLLInfo
    used_dlls = detectBinaryDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1255, in detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1071, in detectBinaryPathDLLsWindowsDependencyWalker
    _parseDependsExeOutput(output_filename, result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 906, in _parseDependsExeOutput
    _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"), result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 891, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\users\\\x04\x04\x04\x04\x04\x04\\appdata\\local\\programs\\python\\python39\\python39.dll', '     [  6] c:\\users\\\x04\x04\x04\x04\x04\x04\\
appdata\\local\\programs\\python\\python39\\PYTHON39.DLL')
```

**Comment by Pro100rus32** [comment]
`python -m nuitka --mingw64 --standalone "C:\Users\Андрей\PycharmProjects\pythonProject\test.py"`

Code:
`print("Hello World!")`

Output:

```
Traceback (most recent call last):
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "E:\PYPYthon\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "E:\PYPYthon\lib\site-packages\nuitka\MainControl.py", line 747, in main
    copyUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1376, in copyUsedDLLs
    used_dlls = detectUsedDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1311, in detectUsedDLLs
    worker_pool.submit(
  File "E:\PYPYthon\lib\site-packages\nuitka\utils\ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1280, in addDLLInfo
    used_dlls = detectBinaryDLLs(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1255, in detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 1071, in detectBinaryPathDLLsWindowsDependencyWalker
    _parseDependsExeOutput(output_filename, result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 906, in _parseDependsExeOutput
    _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"), result)
  File "E:\PYPYthon\lib\site-packages\nuitka\freezer\Standalone.py", line 891, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\users\\\x04\x04\x04\x04\x04\x04\\appdata\\local\\programs\\python\\python39\\python39.dll', '     [  6] c:\\users\\\x04\x04\x04\x04\x04\x04\\
appdata\\local\\programs\\python\\python39\\PYTHON39.DLL')
```


**python 32-bit notVirtualenv**

```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86\10.2.0-11.0.0-8.0.0-r5".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
yes
Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r5/winlibs-i686-posix-dwarf-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r5.zip'.
Nuitka:INFO: Extracting to 'C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86\10.2.0-11.0.0-8.0.0-r5\mingw32\bin\gcc.exe'
Nuitka-Scons:INFO: Backend C compiler: C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\gcc\x86\10.2.0-11.0.0-8.0.0-r5\mingw32\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 12
Nuitka will make use of Dependency Walker (https://dependencywalker.com) tool
to analyze the dependencies of Python extension modules.

Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\depends\x86".

No installer needed, cached, one time question.

Proceed and download? [Yes]/No
yes
Nuitka:INFO: Downloading 'https://dependencywalker.com/depends22_x86.zip'.
Nuitka:INFO: Extracting to 'C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\depends\x86\depends.exe'
Traceback (most recent call last):
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\MainControl.py", line 747, in main
    copyUsedDLLs(
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 1376, in copyUsedDLLs
    used_dlls = detectUsedDLLs(
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 1311, in detectUsedDLLs
    worker_pool.submit(
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\utils\ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 1280, in addDLLInfo
    used_dlls = detectBinaryDLLs(
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 1255, in detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 1071, in detectBinaryPathDLLsWindowsDependencyWalker
    _parseDependsExeOutput(output_filename, result)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 906, in _parseDependsExeOutput
    _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"), result)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nuitka\freezer\Standalone.py", line 891, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\users\\\x04\x04\x04\x04\x04\x04\\appdata\\local\\programs\\python\\python39-32\\python39.dll', '     [   ] c:\\users\\\x04\x04\x04\x04\x04\x04\\appdata\\local\\programs\\python\\python39-32\\PYTHON39.DLL')
```

**Comment by kayhayen** [comment]
The dependency walker tool seems to hate your home directory path very much, but Nuitka, as you can see is using short paths in a couple of places, which will always work, e.g. `Is it OK to download and put it in "C:\Users\A4F7~1\AppData\Local\Nuitka\Nuitka\ccache\v3.7.12".`

Now I wonder how this can happen, as we have done similar fixes in the past for it. Also why you end up with `\x04\0x04....\` is a mystery, but I guess, it's because a unicode path confused it.

Looking at the code, I believe your %PATH% contains your home directory, but only once you use a virtualenv, otherwise you didn't trigger the bug, and a bug it clearly is. I am adding a conversion to short paths for all "user" directories, that are typically coming from `%PATH%`, but in fact if could also be Python package directory paths, which will also trigger this.

That would actually be worth a hotfix, but new release is coming soon anyway.

**Comment by Pro100rus32** [comment]
It worked, super!

Thank you so much!

**Comment by kayhayen** [comment]
This is part of the current pre-release now. Due to cleanups in the field, backporting to stable is not an option.

**Comment by kayhayen** [comment]
Part of the 0.6.13 release.
