### ISSUE TITLE
ImportError: LoadLibraryExW '_socket.pyd' failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Pernat1y** [Nuitka/Nuitka#1035]
Hello.

I am trying to build https://github.com/Pernat1y/vm-automation with Nuitka. It builds just fine but does not work due to a missing module.
If I remove 'http.client' module, everything works just fine.

```
> vm_automation_windows.exe
Traceback (most recent call last):
  File "C:\vm-automation-master\demo_cli.py", line 6, in <module>
    import http.client
  File "C:\vm-automation-master\http\client.py", line 71, in <module>
  File "C:\vm-automation-master\email\parser.py", line 12, in <module>
  File "C:\vm-automation-master\email\feedparser.py", line 27, in <module>
  File "C:\vm-automation-master\email\_policybase.py", line 9, in <module>
  File "C:\vm-automation-master\email\utils.py", line 29, in <module>
  File "C:\vm-automation-master\socket.py", line 51, in <module>
ImportError: LoadLibraryExW 'C:\vm-automation-master\_socket.pyd' failed: The specified module could not be found.
```

Versions:
```
0.6.13
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python39\python.exe
OS: Windows
Arch: x86_64
```

**Comment by czee** [comment]
I get the same:
`Traceback (most recent call last):
  File "C:\Users\me\test.py", line 11, in <module>
  File "C:\Users\me\artifactory.py", line 39, in <module artifactory>
  File "C:\Users\me\requests\__init__.py", line 43, in <module requests>
  File "C:\Users\me\urllib3\__init__.py", line 11, in <module urllib3>
  File "C:\Users\me\urllib3\exceptions.py", line 3, in <module urllib3.exceptions>
  File "C:\Users\me\urllib3\packages\six.py", line 199, in load_module
  File "C:\Users\me\urllib3\packages\six.py", line 113, in _resolve
  File "C:\Users\me\urllib3\packages\six.py", line 82, in _import_module
  File "C:\Users\me\http\client.py", line 71, in <module>
  File "C:\Users\me\email\parser.py", line 12, in <module>
  File "C:\Users\me\email\feedparser.py", line 27, in <module>
  File "C:\Users\me\email\_policybase.py", line 9, in <module>
  File "C:\Users\me\email\utils.py", line 29, in <module>
  File "C:\Users\me\socket.py", line 49, in <module>
ImportError: LoadLibraryExW 'C:\Users\me\_socket.pyd' failed: The specified module could not be found.`

**Comment by kayhayen** [comment]
I need to information from the issue template, e.g. version etc-

**Comment by czee** [comment]
Sorry

0.6.13
Python 3.7.9 [MSC v.1916 64 bit (AMD64)] on win32
OS: Windows
Arch: x86_64

**Comment by czee** [comment]
And one thing I noticed, it works OK on my own PC, but not when I downloaded this from our repository. So it seems it's an environment issue in our own setup?

**Comment by kayhayen** [comment]
@czee what is "it" in your sentence, Nuitka?

**Comment by czee** [comment]
The executable that was giving this error

**Comment by kayhayen** [comment]
I don't see the command lines used either. For me this works.

**Comment by czee** [comment]
Sorry, this is entirely a problem in our environment.

**Comment by kayhayen** [comment]
@czee no problem

**Comment by kayhayen** [comment]
The issue template wasn't filled out, specifically the command used and any details are missing. Left open this is just a trap for others to believe this actually is a valid issue, which it likely is not.
