### ISSUE TITLE
Multiprocessing problem using compiled function, has no attribute 'im_self'

### ISSUE THREAD

**Issue by EnzoRondo** [Nuitka/Nuitka#104]
OS:
`Microsoft Windows Server 2012 Standard`

nuitka --version
```
0.5.33rc7
3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe
```
I've tried build 0.5.32.7 and latest dev build

nuitka installed this way (tried both):
```
pip install nuitka
pip install https://github.com/kayhayen/Nuitka/archive/develop.zip
```
code to reproduce error (n1.py):
```python
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import freeze_support


def test():
    print("just a test")


if __name__ == '__main__':
    freeze_support()
    manager = ProcessPoolExecutor(1).submit(test,)
```

output:
```
PS C:\Users\Administrator\Desktop\wow\n1.dist> ./n1.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\queues.py", line 234, in _feed
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\reduction.py", line 51, in dumps

  File "C:\Users\Administrator\Desktop\wow\n1.dist\__init__.py-postLoad", line 11, in _reduce_compi
led_method
AttributeError: 'compiled_function' object has no attribute 'im_self'
```
and hanging here, then I'm doing Ctrl+C:
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\process.py", line 258, in _boots
trap
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\process.py", line 93, in run
  File "C:\Users\Administrator\Desktop\wow\n1.dist\concurrent\futures\process.py", line 169, in _pr
ocess_worker
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\queues.py", line 94, in get
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\connection.py", line 216, in rec
v_bytes
  File "C:\Users\Administrator\Desktop\wow\n1.dist\multiprocessing\connection.py", line 306, in _re
cv_bytes
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wow\n1.dist\concurrent\futures\process.py", line 86, in _pyt
hon_exit
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\threading.py", line 1072, in _wait_for_tstate_
lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

expected output:
```
just a test
```

**Comment by EnzoRondo** [comment]
Thanks for help dear @kayhayen, no problems in last factory version!
