### ISSUE TITLE
test_class failure on macos

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1041]
This occurred on develop branch, and locally, so I can debug this further as needed.

It looks like the difference is being hidden by the `assertEqual` logic :/

Running
> sudo python3.9 ./tests/run-tests --skip-reflection-test --no-other-python --skip-basic-tests --skip-syntax-tests --skip-program-tests --skip-package-tests --skip-plugins-tests

```py
...

Run '/usr/local/opt/python@3.9/bin/python3.9 ./tests/CPython32/run_all.py search' in '/Users/john.vandenberg/python/Nuitka'.
Using concrete python 3.9.2 on x86_64
...
Comparing output of 'test/test_class.py' using '/usr/local/opt/python@3.9/bin/python3.9' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache, plugin_disable:multiprocessing ...
--- /usr/local/opt/python@3.9/bin/python3.9 (stdout)
+++ nuitka (stdout)

@@ -17,7 +17,7 @@

 Traceback (most recent call last):
   File "/Users/john.vandenberg/python/Nuitka/tests/CPython32/test/test_class.py", line 535, in testHashComparisonOfMethods
     self.assertEqual(a1.f, A(1).f)
-AssertionError: <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
+AssertionError: <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
 
 ----------------------------------------------------------------------
 Ran 12 tests in x.xxxs
--- /usr/local/opt/python@3.9/bin/python3.9 (stderr)
+++ nuitka (stderr)

@@ -10,6 +10,6 @@

 test.support.TestFailed: Traceback (most recent call last):
   File "/Users/john.vandenberg/python/Nuitka/tests/CPython32/test/test_class.py", line 535, in testHashComparisonOfMethods
     self.assertEqual(a1.f, A(1).f)
-AssertionError: <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
+AssertionError: <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
 
 
Updating CPython cache by force due to non-matching comparison results.
--- /usr/local/opt/python@3.9/bin/python3.9 (stdout)
+++ nuitka (stdout)

@@ -17,7 +17,7 @@

 Traceback (most recent call last):
   File "/Users/john.vandenberg/python/Nuitka/tests/CPython32/test/test_class.py", line 535, in testHashComparisonOfMethods
     self.assertEqual(a1.f, A(1).f)
-AssertionError: <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
+AssertionError: <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
 
 ----------------------------------------------------------------------
 Ran 12 tests in x.xxxs
--- /usr/local/opt/python@3.9/bin/python3.9 (stderr)
+++ nuitka (stderr)

@@ -10,6 +10,6 @@

 test.support.TestFailed: Traceback (most recent call last):
   File "/Users/john.vandenberg/python/Nuitka/tests/CPython32/test/test_class.py", line 535, in testHashComparisonOfMethods
     self.assertEqual(a1.f, A(1).f)
-AssertionError: <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[84 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
+AssertionError: <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>> != <boun[93 chars].testHashComparisonOfMethods.<locals>.A object at 0xxxxxxxxx>>
 
 
Error, results differed (stdout,stderr).
Error exit! 1
```

**Comment by kayhayen** [comment]
The CPython32 test suite is nothing I run against Python3.9 so far, there would be too little to gain.

**Comment by kayhayen** [comment]
This is not going to happen.
