### ISSUE TITLE
CPython38 test_asyncore failure on macos

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1043]
```py
Run '/run/current-system/sw/bin/python3.8 ./tests/CPython38/run_all.py search' in '/Users/john.vandenberg/python/Nuitka'.
Using concrete python 3.8.8 on x86_64
...
Comparing output of 'test/test_asyncore.py' using '/run/current-system/sw/bin/python3.8' with flags silent, remove_output, binary_python_path, recurse_none, timing, original_file, cpython_cache, plugin_disable:multiprocessing ...
--- /run/current-system/sw/bin/python3.8 (stderr)
+++ nuitka (stderr)

@@ -1,6 +1,30 @@

-..........................s...........................s..................s........s..sss........s..ss
+..........................s...........................s..........E.......s........s..sss........s..ss
+======================================================================
+ERROR: test_handle_close_after_conn_broken (__main__.TestAPI_UseIPv6Select)
+----------------------------------------------------------------------
+Traceback (most recent call last):
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 650, in test_handle_close_after_conn_broken
+    self.loop_waiting_for_flag(client)
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 508, in loop_waiting_for_flag
+    asyncore.loop(timeout=0.01, count=1, use_poll=self.use_poll)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 207, in loop
+    poll_fun(timeout, map)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 156, in poll
+    write(obj)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 95, in write
+    obj.handle_error()
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 91, in write
+    obj.handle_write_event()
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 439, in handle_write_event
+    self.handle_write()
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 629, in handle_write
+    self.send(data)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 358, in send
+    result = self.socket.send(data)
+OSError: [Errno 41] Protocol wrong type for socket
+
 ----------------------------------------------------------------------
 Ran 101 tests in x.xxxs
 
-OK (skipped=10)
+FAILED (errors=1, skipped=10)
 
Updating CPython cache by force due to non-matching comparison results.
--- /run/current-system/sw/bin/python3.8 (stderr)
+++ nuitka (stderr)

@@ -1,6 +1,30 @@

-..........................s...........................s..................s........s..sss........s..ss
+..........................s...........................s..........E.......s........s..sss........s..ss
+======================================================================
+ERROR: test_handle_close_after_conn_broken (__main__.TestAPI_UseIPv6Select)
+----------------------------------------------------------------------
+Traceback (most recent call last):
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 650, in test_handle_close_after_conn_broken
+    self.loop_waiting_for_flag(client)
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 508, in loop_waiting_for_flag
+    asyncore.loop(timeout=0.01, count=1, use_poll=self.use_poll)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 207, in loop
+    poll_fun(timeout, map)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 156, in poll
+    write(obj)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 95, in write
+    obj.handle_error()
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 91, in write
+    obj.handle_write_event()
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 439, in handle_write_event
+    self.handle_write()
+  File "/Users/john.vandenberg/python/Nuitka/tests/CPython38/test/test_asyncore.py", line 629, in handle_write
+    self.send(data)
+  File "/nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/lib/python3.8/asyncore.py", line 358, in send
+    result = self.socket.send(data)
+OSError: [Errno 41] Protocol wrong type for socket
+
 ----------------------------------------------------------------------
 Ran 101 tests in x.xxxs
 
-OK (skipped=10)
+FAILED (errors=1, skipped=10)
 
Exit codes 0 (CPython) != 1 (Nuitka)
Error, results differed (stderr,exit_code).
Error exit! 1
```

**Comment by kayhayen** [comment]
This is most likely obsolete, we run the CPython test suites on macOS ourselves for a long time already.
