### ISSUE TITLE
"MATPLOTLIBDATA" non-zero exit status 1

### ISSUE THREAD

**Issue by RashiqAzhan** [Nuitka/Nuitka#1047]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
0.6.13.1
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Executable: ...\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

  Pip, pipenv, & poetry.

* Many times when you get an error from Nuitka, your setup may be special

  Hello world program works fine.

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

 ```
from PIL import Image
import numpy as np
from joblib import Memory, Parallel, delayed
from deco import concurrent, synchronized

def main():
    array = np.array(range(10))
    print(array)
    input("Press any key to exit...")

if __name__ == '__main__':
    main()
 ```

* The specific PyPI names and versions

```
Pillow==8.1.2
numpy==1.20.1
joblib==1.0.1
deco==0.6.2
```

* Command used
```
python -m nuitka --onefile --windows-onefile-tempdir --plugin-enable=numpy --plugin-enable=pylint-warnings nuitka_test.py
```

* Terminal Output

```
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\nuitka\__main__.py", line 185, in <module>
    main()
  File "...\.venv\lib\site-packages\nuitka\__main__.py", line 171, in main
    MainControl.main()
  File "...\.venv\lib\site-packages\nuitka\MainControl.py", line 689, in main
    main_module = _createNodeTree(filename=filename)
  File "...\.venv\lib\site-packages\nuitka\MainControl.py", line 161, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "...\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 371, in optimize
    finished = makeOptimizationPass()
  File "...\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 317, in makeOptimizat
ionPass
    changed = optimizeModule(current_module)
  File "...\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 214, in optimizeModul
e
    changed = optimizeCompiledPythonModule(module)
  File "...\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 120, in optimizeCompi
ledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "...\.venv\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 531, in computeModule
    trace_collection=self.trace_collection
  File "...\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSe
quence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "...\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequen
ce
    new_statement = trace_collection.onStatement(statement=statement)
  File "...\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 561, in onStateme
nt
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "...\.venv\lib\site-packages\nuitka\nodes\AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "...\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 542, in onExpress
ion
    r = expression.computeExpressionRaw(trace_collection=self)
  File "...\.venv\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1131, in computeExpression
Raw
    return self.computeExpression(trace_collection=trace_collection)
  File "...\.venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 605, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "...\.venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 477, in _attemptRecursion
    module_package=module_package,
  File "...\.venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 408, in _consider
    reason=reason,
  File "...\.venv\lib\site-packages\nuitka\importing\Recursion.py", line 128, in recurseTo
    reason=reason,
  File "...\.venv\lib\site-packages\nuitka\importing\Recursion.py", line 108, in _recurseTo
    ImportCache.addImportedModule(module)
  File "...\.venv\lib\site-packages\nuitka\importing\ImportCache.py", line 48, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "...\.venv\lib\site-packages\nuitka\plugins\Plugins.py", line 431, in onModuleDiscovered
    plugin.onModuleDiscovered(module)
  File "...\.venv\lib\site-packages\nuitka\plugins\PluginBase.py", line 341, in onModuleDiscovered
    preload_desc = self.createPreModuleLoadCode(module)
  File "...\.venv\lib\site-packages\nuitka\plugins\standard\NumpyPlugin.py", line 429, in createPreMo
duleLoadCode
    and self._getMatplotlibInfo().needs_matplotlibdata_env
  File "...\.venv\lib\site-packages\nuitka\plugins\standard\NumpyPlugin.py", line 237, in _getMatplot
libInfo
    feedback = Execution.check_output([sys.executable, "-c", cmd])
  File "...\.venv\lib\site-packages\nuitka\utils\Execution.py", line 169, in check_output
    raise subprocess.CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['...\\.venv\\Scripts\\python.exe', '-c', '\\\nfrom __fu
subprocess.CalledProcessError: Command '['...\\.venv\\Scripts\\python.exe', '-c', '\\\nfrom __future__ import print_function\nfrom matplotlib imp
ort matplotlib_fname, get_backend, _get_data_path, __version__\nfrom inspect import getsource\nprint(repr(matplotlib_fname()))\nprint(repr(get_backend()))\nprint(repr(_get_data_path()))\
nprint(repr(__version__))\nprint(repr("MATPLOTLIBDATA" in getsource(_get_data_path)))\n']' returned non-zero exit status 1.
```

**Comment by kayhayen** [comment]
Are the `...` the result of you truncating the output there? (which would be ok, but it would also explain why a command might not be executable). 

Also in your pip output, matplotlib is missing, is is a dependency of any of those, or can it be that it's corrupt.

It's pretty shitty bad that `Execution.check_output` doesn't share the output. My first line of attack would be to enhance this, and let you know once I have that.

**Comment by kayhayen** [comment]
So if there is a traceback from Python, or any stderror, that would be right before the traceback you posted. Maybe you removed that?

**Comment by kayhayen** [comment]
I pushed this to factory, please re-execute without changing anything on your side, and report the new enhanced output, i.e. the final line. It should contain the stdout and stderr, making this easy to tell what it is about.

**Comment by RashiqAzhan** [comment]
Thank you for the quick reply. Sorry for messing up the terminal outputs.
`...` the ellipses were put by me where the file path was. I can include them if that would be any help.

Matplotlib is included. I removed it since I was not using it in that particular file. I have deleted the virtual environment folder for both poetry, pipenv, and pip and started from scratch several times to rule out installation issues. I have rebooted the OS in between just in case. 
Also, matplotlib functions perform normally. Would that rule out an installation issue?

* The unabridged `python -m pip freeze` output:
```
anyio==2.2.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.3.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
colorama==0.4.4
cycler==0.10.0
Cython==0.29.22
debugpy==1.2.1
deco==0.6.2
decorator==4.4.2
defusedxml==0.7.1
entrypoints==0.3
fastcore==1.3.19
fastrelease==0.1.11
ffmpeg-python==0.2.0
future==0.18.2
ghapi==0.1.16
idna==2.10
imageio==2.9.0
importlib-metadata==3.7.3
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.17.2
Jinja2==2.11.3
joblib==1.0.1
json5==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.7.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-packaging==0.7.12
jupyter-server==1.5.1
jupyterlab==3.0.12
jupyterlab-legos-ui==0.1.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-widgets==1.0.0
jupyterthemes==0.20.0
kiwisolver==1.3.1
lesscpy==0.14.0
llvmlite==0.36.0
lxml==4.6.3
MarkupSafe==1.1.1
matplotlib==3.4.0
mistune==0.8.4
mplcursors==0.4
nbclassic==0.2.6
nbclient==0.5.3
nbconvert==5.6.1
nbdev==1.1.13
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5
notebook==6.3.0
nuitka==0.6.14rc2
numba==0.53.1
numpy==1.20.1
opencv-python==4.5.1.48
packaging==20.9
pandocfilters==1.4.3
parso==0.7.1
pickleshare==0.7.5
Pillow==8.1.2
ply==3.11
prometheus-client==0.9.0
prompt-toolkit==3.0.18
pyaes==1.6.1
pycparser==2.20
pycryptodome==3.10.1
Pygments==2.8.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-magic==0.4.22
python-magic-bin==0.4.14
pytz==2021.1
PyWavelets==1.1.1
pywin32==300
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==22.0.3
qtconsole==5.0.3
QtPy==1.9.0
requests==2.25.1
scikit-image==0.18.1
scipy==1.6.2
Send2Trash==1.5.0
six==1.15.0
sk-video==1.1.10
sniffio==1.2.0
terminado==0.9.3
testpath==0.4.4
tifffile==2021.3.17
tornado==6.1
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.26.4
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xeus-python==0.12.1
zipp==3.4.1
```

* Terminal Output (final line):
```
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\utils\Execution.py", line 186, in check_output
    raise NuitkaCalledProcessError(retcode, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['...\\.venv\\Scripts\\python.exe', '-c', '\\\nfrom __future__ import print_function\nf
rom matplotlib import matplotlib_fname, get_backend, _get_data_path, __version__\nfrom inspect import getsource\nprint(repr(matplotlib_fname()))\nprint(repr(get_backend()))\nprint(repr(_
get_data_path()))\nprint(repr(__version__))\nprint(repr("MATPLOTLIBDATA" in getsource(_get_data_path)))\n']' returned non-zero exit status 1. Error was b'Traceback (most recent call last
):\r\n  File "<string>", line 3, in <module>\r\nImportError: cannot import name \'_get_data_path\' from \'matplotlib\' (...\\.venv\\lib\\site-pac
kages\\matplotlib\\__init__.py)'.
```

* Terminal Output (with the last line before traceback):
```
PASS 1:  PASS 1:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 969/1072,
ipykernel.pylab.backend_inlineProblem with statement at ...\.venv\lib\site-packages\ipykernel\pylab\backend_inline.py:6:-> import matplotlib

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '...\\.venv\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py', 
'module_name': <ModuleName ipykernel.pylab.backend_inline>, 'code_flags': ''}>'.

Traceback (most recent call last):
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\__main__.py", line 185, in <module>
    main()
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\__main__.py", line 171, in main
    MainControl.main()
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\MainControl.py", line 689, in main
    main_module = _createNodeTree(filename=filename)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\MainControl.py", line 161, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\Optimization.py", line 373, in optimize
    finished = makeOptimizationPass()
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\Optimization.py", line 319, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\Optimization.py", line 214, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\Optimization.py", line 120, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\ModuleNodes.py", line 531, in computeModule
    trace_collection=self.trace_collection
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\TraceCollections.py", line 561, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\optimizations\TraceCollections.py", line 542, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\ExpressionBases.py", line 1131, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\ImportNodes.py", line 605, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\ImportNodes.py", line 477, in _attemptRecursion
    module_package=module_package,
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\nodes\ImportNodes.py", line 408, in _consider
    reason=reason,
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\importing\Recursion.py", line 128, in recurseTo
    reason=reason,
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\importing\Recursion.py", line 108, in _recurseTo
    ImportCache.addImportedModule(module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\importing\ImportCache.py", line 48, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\plugins\Plugins.py", line 431, in onModuleDiscovered
    plugin.onModuleDiscovered(module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\plugins\PluginBase.py", line 341, in onModuleDiscovered
    preload_desc = self.createPreModuleLoadCode(module)
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\plugins\standard\NumpyPlugin.py", line 429, in createPreModuleLoadCode
    and self._getMatplotlibInfo().needs_matplotlibdata_env
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\plugins\standard\NumpyPlugin.py", line 237, in _getMatplotlibInfo
    feedback = Execution.check_output([sys.executable, "-c", cmd])
  File "...\.venv\lib\site-packages\nuitka-0.6.14rc2-py3.7.egg\nuitka\utils\Execution.py", line 186, in check_output
    raise NuitkaCalledProcessError(retcode, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['...\\.venv\\Scripts\\python.exe', '-c', '\\\nfrom __future__ import print_function\nf
rom matplotlib import matplotlib_fname, get_backend, _get_data_path, __version__\nfrom inspect import getsource\nprint(repr(matplotlib_fname()))\nprint(repr(get_backend()))\nprint(repr(_
get_data_path()))\nprint(repr(__version__))\nprint(repr("MATPLOTLIBDATA" in getsource(_get_data_path)))\n']' returned non-zero exit status 1. Error was b'Traceback (most recent call last
):\r\n  File "<string>", line 3, in <module>\r\nImportError: cannot import name \'_get_data_path\' from \'matplotlib\' (...\\.venv\\lib\\site-pac
kages\\matplotlib\\__init__.py)'.
```

**Comment by kayhayen** [comment]
So my guess was correct about `...` but you really left me wondering what happens if somebody were to name a folder `...`.

Seems that matplotlib 3.4 is new to Nuitka. We made changes for 3.2 only recently. If you replace "_get_data_path" with "get_data_path" it will likely work for you. I will try and prepare a hotfix for this.

**Comment by kayhayen** [comment]
Fix is on factory branch: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of 0.6.13.2

**Comment by RashiqAzhan** [comment]
Never again. I had enough run-ins with spaces, dots, and whatnot in folder and file names.

I just ran the factory and WE COOKING NOW!

Thank you for solving this so quickly.
