### ISSUE TITLE
PandasUsing: write error: No space left on device

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1053]
Obviously this isnt a serious fault in Nuitka, as the build VM do not have typical amounts of disk space.  However if this is due only to Nuitka's build of PandasUsing, maybe this error indicates the disk usage is growing significantly.

This occurred on ppc64 while doing python3.8 tests after having already run the python3.6 tests on the same VM, and I am running both clang and gcc tests, so quite a bit of work has occurred at this point.  Possibly the tests are leaving behind some significant amounts of data from each run.  Under `tests/standalone/` there are some log files, which are appropriate to leave there, and I will now start deleting them manually between test runs, but that isnt like to be the cause.  I am now also pruning `/tmp` in case that has some large files left behind.

I would appreciate any suggestions on where else to look for large artifacts deposited after each test run.

```
[29582s] Consider output of standalone mode compiled program: PandasUsing.py
[29582s] Comparing output of 'PandasUsing.py' using '/usr/bin/python3.8' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, plugin_enable:numpy, plugin_disable:pylint-warnings, plugin_disable:qt-plugins, plugin_disable:pyside2, plugin_disable:pyside6 ...
[33427s] /.build/build-vm: line 447: echo: write error: No space left on device
[33513s] --- /usr/bin/python3.8 (stdout)
[33513s] +++ nuitka (stdout)
[33513s] 
[33513s] @@ -1,2 +1 @@
[33513s] 
[33513s] -1.2.3
[33513s]  
[33513s] --- /usr/bin/python3.8 (stderr)
[33513s] +++ nuitka (stderr)
[33513s] 
[33513s] @@ -1 +1,39 @@
[33513s] 
[33513s] +scons: *** [module.pandas.io.sas.o] Error 1
[33513s] +ccache: error: Failed to write to /home/abuild/rpmbuild/BUILD/Nuitka-0.6.13.2/tests/standalone/PandasUsing.build/ccache-28963.txt: No space left on device
[33513s] +scons: *** [module.pandas.io.pytables.o] Error 1
[33513s] +ccache: error: Failed to write to /home/abuild/rpmbuild/BUILD/Nuitka-0.6.13.2/tests/standalone/PandasUsing.build/ccache-28963.txt: No space left on device
[33513s] +scons: *** [module.pandas.io.parquet.o] Error 1
[33513s] +{standard input}: Assembler messages:
[33513s] +{standard input}: Fatal error: can't write 132 bytes to section .text of module.pandas.io.parsers.o: 'No space left on device'
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +/usr/lib64/gcc/powerpc64-suse-linux/10/../../../../powerpc64-suse-linux/bin/as: BFD (GNU Binutils; openSUSE Tumbleweed) 2.36.1.20210301-2 assertion fail ../../bfd/elf.c:3127
[33513s] +{standard input}: Fatal error: module.pandas.io.parsers.o: No space left on device
[33513s] +scons: *** [module.pandas.io.parsers.o] Error 1
[33513s] +OSError: [Errno 28] No space left on device:
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 1381:
[33513s] +    _exec_main(parser, values)
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 1344:
[33513s] +    _main(parser)
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 1119:
[33513s] +    nodes = _build_targets(fs, options, targets, target_top)
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 1318:
[33513s] +    jobs.run(postfunc = jobs_postfunc)
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Job.py", line 113:
[33513s] +    postfunc()
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 1315:
[33513s] +    SCons.SConsign.write()
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/SConsign.py", line 117:
[33513s] +    syncmethod()
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/dblite.py", line 148:
[33513s] +    self._pickle_dump(self._dict, f, self._pickle_protocol)
[33513s] +Traceback (most recent call last):
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/dblite.py", line 143, in __del__
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/dblite.py", line 140, in close
[33513s] +  File "/usr/lib/python3.8/site-packages/SCons/dblite.py", line 148, in sync
[33513s] +OSError: [Errno 28] No space left on device
[33513s]  
[33513s] Updating CPython cache by force due to non-matching comparison results.
```

**Comment by kayhayen** [comment]
Are you using ccache? Also I am not sure that Scons should actually have to write this database, it hopefully isn't caching build results itself too. I removed the scons caching that was done for Windows, now that we have either ccache or clcache more or less always, but maybe that enabled it for all platforms. 

That would allow Nuitka to double.

As for Pandas, it's using 1000+ modules, some of which are not very scalable, right now it's a stress test more than anything.

**Comment by jayvdb** [comment]
Yes, using ccache.  I should add `ccache --show-stats` after each test run to verify that.

I could use `ccache --evict-older-than 0s` between test runner invocations to flush the ccache, as I guess there is no re-usability between gcc/clang and debug/nodebug.

https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:python/python-Nuitka is nearly ready to ship 0.6.13.2.  Let me know if there is any other commands you would like added between test runs that might help determine where the disk space is disappearing.

I will leave the ppc builds so that they finish in a few hours, and we can see if it re-occurs.

**Comment by kayhayen** [comment]
Definitely not, change of compile or flags will break that caching anyway. The `.build` folders are normally removed, you can verify that, I think they should only live in case of errors. The `.dist` folders the same.

As for the scons thing I was looking at, it seems scons is actually using a sort of small cache for directory scan results, and then going to the trouble to write that sync, and the file was 100k for me, but it's used from memory anyway. Seems Scons won't allow to disable that, but I prevent the disk write now, saving a bit of disk churn. Testing that in my CI first.

Notice, that will only work with the inline copy of Scons, so it won't affect you, but it seems unimportant anyway, but maybe I ought to change it such that it does it via monkey patching.

**Comment by jayvdb** [comment]
Agree 100k isnt important - I wouldnt worry about monkey-patching.

I've already confirmed .build and .dist are not being left behind.

**Comment by kayhayen** [comment]
More a matter of wasted CPU cycles and IO cycles, and of course funny things that code does for Windows being unable to replace existing files. Esp. as previously there were problems with different Python versions using the same file, but incompatible pickle, so I can drop a bit of complexity for sure for repeated compilations.

**Comment by kayhayen** [comment]
I think the inclusion log, etc can be disabled, however, in case of bugs, we want them to be there, and they should be relatively small still. So I am closing this then.

**Comment by kayhayen** [comment]
For the record, changed it to monkey patching, that is better when I update the inline copies anyway, even now there are 2 to patch manually, feasible, but risky too.

**Comment by jayvdb** [comment]
The ppc builds both passed, so this was a bit intermittent, unless deleting those logs files was sufficient to squeeze the pandas build through the goal posts.
