### ISSUE TITLE
If spawning a process on windows using a class-method in case the class-method got a thread-object in its attrs, we get TypeError: cannot pickle 'cell' object for any process we try to spawn

### ISSUE THREAD

**Issue by chwba** [Nuitka/Nuitka#1056]
Compiled executable: https://nextcloud.mnwd.in/s/6sCGRtwCnKy322e
Compilation log: https://nextcloud.mnwd.in/s/Pw7jYqo2TK2Lsr6

**Exception:**
```
Starting a thread...
Starting a process...
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\app.py", line 17, in <module>
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\app.py", line 12, in main
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\example_class.py", line 30, in run_a_process
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocess\process.py", line 121, in start
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocess\context.py", line 224, in _Popen
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocess\context.py", line 327, in _Popen
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocess\popen_spawn_win32.py", line 93, in __init__
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocess\reduction.py", line 63, in dump
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\dill\_dill.py", line 454, in dump
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 487, in dump
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 603, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 717, in save_reduce
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\dill\_dill.py", line 941, in save_module_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 971, in save_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 997, in _batch_setitems
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\__init__.py-postLoad", line 8, in save_compiled_method
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 692, in save_reduce
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 886, in save_tuple
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 603, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 717, in save_reduce
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\dill\_dill.py", line 941, in save_module_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 971, in save_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 997, in _batch_setitems
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 603, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 717, in save_reduce
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\dill\_dill.py", line 941, in save_module_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 971, in save_dict
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 997, in _batch_setitems
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\dill\_dill.py", line 1444, in save_function
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 692, in save_reduce
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 901, in save_tuple
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 560, in save
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 901, in save_tuple
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\pickle.py", line 578, in save
TypeError: cannot pickle 'cell' object

(venv) C:\Users\Administrator\PycharmProjects\nuitka_glfw_not_found\app.dist>Traceback (most recent call last):
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\app.py", line 20, in <module __parents_main__>
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocessing\spawn.py", line 74, in freeze_support
  File "C:\Users\ADMINI~1\PYCHAR~1\NUITKA~1\APP~1.DIS\multiprocessing\spawn.py", line 102, in spawn_main
OSError: [WinError 87] The parameter is incorrect
```

**Snippet to reproduce:**
_app.py_
```python
from time import sleep

from example_class import Example


def main():
    e = Example()
    print("Starting a thread...")
    e.start_thread()
    sleep(1)
    print("Starting a process...")
    e.run_a_process()
    sleep(1)


if __name__ == "__main__":
    main()
```

__example_class.py__
```python
import threading
import time

from multiprocess import Process, freeze_support


class Example:
    def __init__(self):
        self.thread = threading.Thread(target=self.thread_worker, daemon=True)
        self.anything = 1

    def start_thread(self):
        self.thread.start()

    def thread_worker(self):
        self.anything = 2
        while True:
            time.sleep(2.5)
            print("THREAD IS RUNNING...")

    def process_worker(self):
        self.anything = 3
        while True:
            time.sleep(3.5)
            print("PROCESS IS RUNNING...")

    def run_a_process(self):
        freeze_support()
        p = Process(target=self.process_worker, daemon=False)
        p.start()
```

**nuitka**
```
0.6.13.2
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\Administrator\PycharmProjects\nuitka_glfw_not_found\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```

**pip freeze**
```
dill==0.3.3
multiprocess==0.70.11.1
Nuitka==0.6.13.2
```

**Comment by kayhayen** [comment]
Good report. The `multiprocessing` plugin doesn't cover `multiprocess`, and therefore no freeze support is enabled, which may or may not be when the dill code gets activated, and therefore the uncompiled type doesn't work. 

I forgot exactly how dill is normally enabled, but I believe to know that multiprocessing and dill are used with Nuitka successfully.

Adding support for `multiprocess` is a new feature that we can consider, not sure what it entails at this point. Upstream code is looking relatively confusing to me. Also seems to transfer more than multiprocessing does, i.e. more than necessary. Maybe it's not even possible, at least I am confused that it is transfering that much. The cell ob the uncompiled object would only have to be transfered with multiprocessing in case it is a nested local function, and that's owned by own on the module level that is not, so that wouldn't have to happen, unless multiprocess needs that, in which case the dill plugin will potentially not be sufficient in its current form, as it wouldn't cover these unnecessary ones.

Another minor observation, is that the `__file__` of the dill post load code looks wrong as `__init__.py-postLoad` without a dill there, probably it's missing out the package nature, something not nice, but not functionally relevant.

I managed to reproduce this and will look at the values on the call stack more closely, but this is not a small thing potentially.

**Comment by KevinRodriguez777** [comment]
still happens nowadays.

**Comment by kayhayen** [comment]
I was trying this on Linux just now, and I think I saw no error, so it would be windows specific, but that makes sense, as multiprocess is very different there.

**Comment by kayhayen** [comment]
With that regression fix, I can now reproduce it. What's strange is that it is complaining about a cell, and not a compiled cell, I don't know why that would change with Nuitka at all.

**Comment by kayhayen** [comment]
Ok, for whatever reason, it's crashing when it attempts to save a cell containing `print` built-in, which might be caused by the compiled method. It might be transferring a module dictionary contents there, something it maybe shouldn't do or at least not have to do that maybe, but I am seeing that cells are being transferred OK in pure Python, not sure how we break it.

**Comment by kayhayen** [comment]
I wonder if saving a compiled cell doesn't trigger this, one would need to make a small test to pickle only a compiled cell.
