### ISSUE TITLE
Nuitka + Django + Pipenv how to make it work?

### ISSUE THREAD

**Issue by maxwxzheng** [Nuitka/Nuitka#1058]
I'm trying to use nuitka to package our software built with Django and Pipenv. I'm struggling to make it work.
Here are the steps I followed to create the project and compile the app:
```
pipenv --python 3.6
pipenv shell
pipenv install django
# Installed django 3.1.7
pipenv install nuitka
# Installed nuitka 0.6.13.2
django-admin startproject myapp
cd myapp
python -m nuitka --standalone --follow-imports manage.py
```
Then I used this command to run the binary:
```
manage.dist/manage runserver
```
This gives me error:
ModuleNotFoundError: No module named 'myapp'
(Note that `python manage.py runserver` works)

I'm not sure if this is caused by django, pipenv, or nuitka. Any thoughts?

**Comment by maxwxzheng** [comment]
Update: I tried to compile the binary with this command:
```
python -m nuitka --standalone --follow-imports --include-plugin-directory=/home/max/.local/share/virtualenvs/nuitka-test-5P4ez-51/lib/python3.6/site-packages/django --include-package=myapp myapp/manage.py
```
Now when I run `manage.dist/manage`, I get this error:
```
Traceback (most recent call last):
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/manage.py", line 22, in <module>
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/manage.py", line 18, in main
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/core/management/__init__.py", line 401, in execute_from_command_line
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/core/management/__init__.py", line 377, in execute
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/__init__.py", line 24, in setup
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/apps/registry.py", line 114, in populate
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/apps/config.py", line 211, in import_models
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/contrib/auth/models.py", line 90, in <module django.contrib.auth.models>
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/db/models/base.py", line 161, in __new__
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/db/models/base.py", line 326, in add_to_class
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/db/models/fields/related.py", line 1637, in contribute_to_class
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/functional.py", line 176, in __mod__
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/functional.py", line 140, in __text_cast
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/translation/__init__.py", line 94, in gettext
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/translation/trans_real.py", line 355, in gettext
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/translation/trans_real.py", line 268, in translation
  File "/home/max/Desktop/unitx/nuitka-test/manage.dist/django/utils/translation/trans_real.py", line 160, in __init__
OSError: No translation files found for default language en-us.
```

**Comment by kayhayen** [comment]
Django is a bit dynamic, I believe the config can make it try to restart as Python. The plugin directory option is wrong to use, rather use `--include-package=django` if that is what you want. And there are now options to include data files of packages, it seems you need those.

But all in all, Django is not well supported in Nuitka. If you are a commercial user, please consider https://nuitka.net/pages/commercial.html as I could make a Django plugin to get it well supported out of the box, but it's not happening unless somebody were to fund it.

**Comment by maxwxzheng** [comment]
@kayhayen Thanks for the reply. I tried the following command and it made more progress:
`python -m nuitka --standalone --follow-imports --include-package=django --include-package-data=django --include-package=myapp myapp/manage.py`
Now when I try to run the binary, it doesn't error out, but it also doesn't work correctly. When I run `manage.dist/manage`, I get this:
```

Type 'manage help <subcommand>' for help on a specific subcommand.

Available subcommands:
```
Somehow the subcommands aren't showing up. And when I tried `manage.dist/manage runserver`, I got this:
```
Unknown command: 'runserver'
Type 'manage help' for usage.
```
Do you know what might caused this?

In terms of sponsorship, we are open to it. I'm happy to discuss more in detail in a private channel. What'd be the best way to connect?

**Comment by kayhayen** [comment]
@maxwxzheng there is a link to a form on the page I gave, that asks the questions I usually need answered, but otherwise my email address is kay.hayen@gmail.com

**Comment by dwividha** [comment]
Any updates to this thread? I am also stuck at the exact same point - is there any solution to this?

**Comment by kayhayen** [comment]
Since this appears to be about data files, consider this:

https://nuitka.net/doc/nuitka-package-config.html#data-files

I will welcome a PR from it for sure.

**Comment by dwividha** [comment]
So here are a couple of things that I tried, the combination of which seemed to work ( I didn't have the time to backtrack the minimal set of changes):
- removed the '--standalone' flag - in the documentation I saw that this appends the '--no-site' flag which disables other site-packages to be included as a part of the binary
- Changed the `execute()` command in django.core.management to this:
```
    def execute(self):
        """
        Given the command-line arguments, figure out which subcommand is being
        run, create a parser appropriate to that command, and run it.
        """
        try:
            subcommand = self.argv[1]
        except IndexError:
            subcommand = "help"  # Display help if no arguments were given.

        # Preprocess options to extract --settings and --pythonpath.
        # These options could affect the commands that are available, so they
        # must be processed early.
        parser = CommandParser(
            usage="%(prog)s subcommand [options] [args]",
            add_help=False,
            allow_abbrev=False,
        )
        parser.add_argument("--settings")
        parser.add_argument("--pythonpath")
        parser.add_argument("args", nargs="*")  # catch-all
        try:
            options, args = parser.parse_known_args(self.argv[2:])
            handle_default_options(options)
        except CommandError:
            pass  # Ignore any option errors at this point.

        try:
            settings.INSTALLED_APPS
        except ImproperlyConfigured as exc:
            self.settings_exception = exc
        except ImportError as exc:
            self.settings_exception = exc

        if settings.configured:
            # Start the auto-reloading dev server even if the code is broken.
            # The hardcoded condition is a code smell but we can't rely on a
            # flag on the command class because we haven't located it yet.
            if subcommand == "runserver" and "--noreload" not in self.argv:
                try:
                    autoreload.check_errors(django.setup)()
                except Exception:
                    # The exception will be raised later in the child process
                    # started by the autoreloader. Pretend it didn't happen by
                    # loading an empty list of applications.
                    apps.all_models = defaultdict(dict)
                    apps.app_configs = {}
                    apps.apps_ready = apps.models_ready = apps.ready = True

                    # Remove options not compatible with the built-in runserver
                    # (e.g. options for the contrib.staticfiles' runserver).
                    # Changes here require manually testing as described in
                    # #27522.
                    _parser = self.fetch_command("runserver").create_parser(
                        "django", "runserver"
                    )
                    _options, _args = _parser.parse_known_args(self.argv[2:])
                    for _arg in _args:
                        self.argv.remove(_arg)

            # In all other cases, django.setup() is required to succeed.
            else:
                django.setup()

        self.autocomplete()

        if subcommand == "help":
            if "--commands" in args:
                sys.stdout.write(self.main_help_text(commands_only=True) + "\n")
            elif not options.args:
                sys.stdout.write(self.main_help_text() + "\n")
            else:
                self.fetch_command(options.args[0]).print_help(
                    self.prog_name, options.args[0]
                )
        # Special-cases: We want 'django-admin --version' and
        # 'django-admin --help' to work, for backwards compatibility.
        elif subcommand == "version" or self.argv[1:] == ["--version"]:
            sys.stdout.write(django.get_version() + "\n")
        elif self.argv[1:] in (["--help"], ["-h"]):
            sys.stdout.write(self.main_help_text() + "\n")
        elif subcommand == "runserver":
            BaseRunserverCommand().run_from_argv(self.argv)
        else:
            self.fetch_command(subcommand).run_from_argv(self.argv)
```
The change here is including this:
```
        elif subcommand == "runserver":
            BaseRunserverCommand().run_from_argv(self.argv)
```
I figured maybe the BaseRunserverCommand will come under coverage of nuitka if it is explicitly referenced rather than dynamically

- Add a few flags to the nuitka command:
```
python -m nuitka --nofollow-import-to='*.tests' --nofollow-import-to='*.*.tests' --nofollow-import-to='*.*.*.tests' --follow-imports  --include-package=rest_framework  --include-package=django  manage.py ```
I also added `include-package` for all `django-apps` in my project, along with for all the critical dependencies mentioned in `requirements.txt`

- The command I used to run the runserver:
`./manage.bin runserver --noreload`

And... Profit!

Django runserver seems to be working perfectly fine now! :) 

I now need to figure out how to include gunicorn in the mix here, would love your help if possible. Let me know if I should create another ticket for that.

**Comment by kayhayen** [comment]
There are a lot better tools for data files and their analysis, check out my post series and the docs referred to in it: https://nuitka.net/posts/nuitka-package-config-kickoff.html

Data files should be easy to recognize, DLLs, etc all. For me Django is not yet on the commercial roadmap. I will be probably the end of the year before I start to look at that. I recommend Vibora which works with Nuitka and is much faster btw as customers of mine are using it.

**Comment by richardscholtens** [comment]
This thread helped me a lot to create a standalone django application. I also encountered the problem with the `runserver` command. It seems that this command cannot be found within the `django` package because the `--follow-imports` does not add the separate django apps within. Thus, to include the runserver command add the following flag option:

```shell
--include-package=django.core
```

By adding this specific package the `runserver` command will be included and the `manage.py` file will find and execute the command. 

Please note, the `collectstatic` is not included. Currently I am trying to add this command as well by adding the following flag:

```shell
--include-package=django.contrib \
--include-package=django.contrib.staticfiles
```

I'll let you guys know if these flags will add the `collectstatic` command when the compiling procedure is done.

**Comment by kayhayen** [comment]
I will want to support Django properly at one point, and that may come during this autumn. If there are low key applications, that are kind of easy to test for functionality, and still expose dynamic usage of stuff from Django, that will be extractable by a Nuitka plugin that would be great. If somebody were to produce how contents of  relatively empty `manage.py` and then a populated with extension of Django in 2 examples, I might be able to do this very much more easily.

For flask, bottle, and what not this is already done, but Django is not yet. Mostly because I cannot produce these kind of good examples myself, as that will take too much of my time. Django apps have been possible to run with Nuitka for many years already, but the out of the box experience needs polish. Esp. as many Django users are Python and Django beginner level.

**Comment by richardscholtens** [comment]
Ok, so I figured out some additional things. My previous statement/statement about adding `django.core` might not have been fully complete. When I tried out new approaches I forgot to remove all files and thus it was still adding all the imports included in the anwser of @dwividha. When I did remove all the files it did not work anymore. Because of this I discovered that something in that file was allowing me to get all the commands for the `manage.py` functionality. 

All following information is based upon a Windows 10 operating system. I assume that `nuitka` is already installed.

I got it working again by only adding the following two imports inside the `manage.py` file:

```python
from django.core.management.commands import runserver
from django.contrib.staticfiles.management.commands import collectstatic
```

These import will include all necessary commands to fully start the web application with an `DEBUG=False` environment variable. For example sake I will show my command including some 3th party apps most people probably use. So I did the following command:

```shell
#!/bin/bash
python -m nuitka \
  --standalone \
  --python-flag=no_site \
  --follow-imports \
  --nofollow-import-to='*.tests' \
  --nofollow-import-to='*.*.tests' \
  --nofollow-import-to='*.*.*.tests' \
  --prefer-source-code \
  --include-data-dir=static=static \
  --include-data-dir=templates=templates \
  --include-package=custom_app \
  --include-package-data=custom_app \
  --include-package=django \
  --include-package-data=django \  
  --include-package=django.core \
  --include-package-data=django.core \
  --include-package=project \    # this is my configuration folder with my settings
  --include-package=crispy_forms \
  --include-package-data=crispy_forms \
  --include-package=widget_tweaks \
  --include-package=axes \
  --include-package=certifi \
  --include-package=whitenoise \
  --nofollow-import-to=pytest \
  --output-dir=standalone/build \
  manage.py
```

Please note, I have created a folder in my root directory called `standalone`. To run the above command a made a shell script named `compile_webapplication_to_standalone.sh`. To run the script use:

```shell
standalone\compile_webapplication_to_standalone.sh
```

Running this script will return a `build` folder including two subfolders with `manage.build` and `manage.dist`. Now add the following information to an `.env` file and add it to the `manage.dist`.

```text
DJANGO_SECRET_KEY="hello world"
ALLOWED_HOSTS=localhost,127.0.0.1
DEBUG=False
```

Before we use the `manage.py` commands one has to make sure all Django settings are correct. Below you can find my `standalone.py` file including all additional settings.

```python
# Located in project.settings.standalone

import os

os.environ["DJANGO_READ_DOT_ENV_FILE"] = "True"

from .base import *  # pylint: disable=wildcard-import,unused-wildcard-import; # noqa: E501,F403

print(f"executing {__name__}", file=sys.stderr)

###############################
# Database declaration
###############################
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "standalone.db",  # noqa: F405
        "USER": "",
        "PASSWORD": "",
        "HOST": "",
        "PORT": "",
    }
}

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "custom_app",
    "crispy_forms",
    "widget_tweaks",
    "axes",
]
```

Please note it also imports the base.py. Besides all the normal settings for `staticfiles` and such it also includes a piece of code needed to import the `.env` file. So make sure to add the following code  to the `base.py` file:

```python
if env.bool("DJANGO_READ_DOT_ENV_FILE", default=False):
    # OS environment variables take precedence over variables from .env
    _env_path = BASE_DIR / ".env"
    print(f"reading env file [{_env_path}]", file=sys.stderr)
    env.read_env(_env_path)
```

So after you added all needed configurations and imports. You can start the compiling script. After this you add the environment variables to the `manage.dist` folder within the `build` folder. Now it is possible to start the webapplication by doing the following in a command prompt:

```cmd
  manage.dist\manage.exe migrate --settings=project.settings.standalone
  set PYTHONUTF8=1  # optional
  manage.dist\manage.exe loaddata -v3 demo-set --settings=project.settings.standalone # optional, populate the database
  set PYTHONUTF8=  # optional
  manage.exe createsuperuser  # optional
  manage.dist\manage.exe collectstatic --settings=project.settings.standalone
  manage.exe runserver --noreload
```

I hope this will give you enough information to get it working. Please let me know if you need more information.

**Comment by richardscholtens** [comment]
The `INSTALLED_APPS` list contains all apps that are used by the webapplication including the needed apps from Django framework and your own custom apps.

The python library is imported in the same file as where the `execute_from_command_line(sys.argv)` comes from. Thus the following lines in  `manage.py` do the import:

 ```python
    try:
        from django.core.management import execute_from_command_line
```

Within `django.core.management`  the following imports are used:

```
import functools
import os
import pkgutil
import sys
from argparse import (
    _AppendConstAction, _CountAction, _StoreConstAction, _SubParsersAction,
)
from collections import defaultdict
from difflib import get_close_matches
from importlib import import_module

import django
from django.apps import apps
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.management.base import (
    BaseCommand, CommandError, CommandParser, handle_default_options,
)
from django.core.management.color import color_style
from django.utils import autoreload
```

Not sure if I understand the `dump` comment. Do you mean something like this?
[Django settings](https://docs.djangoproject.com/en/4.2/topics/settings/#default-settings)
`django.conf.settings`

**Comment by kayhayen** [comment]
I guess, the using code for `import_module` introduces the dynamic imports. I was wondering if it does anything more than going over `INSTALLED_APPS` and doing an import on them, or if it expects config there, or entry points, anything really.

My goal is to know `INSTALLED_APPS` without looking at the source code. If `INSTALLED_APPS` is that kind of setting, great. If that means something else, not good. I don't really want to match source code, if there is a programmatic way. btw, do I understand it correctly, and these things live in `manage.py` because your comment `# Located in project.settings.standalone` suggests otherwise?

**Comment by kayhayen** [comment]
That module name is also peculiar :)

**Comment by richardscholtens** [comment]
The `import_module` function is only used to retrieve all command as shown in the code below:

```python

def load_command_class(app_name, name):
    """
    Given a command name and an application name, return the Command
    class instance. Allow all errors raised by the import process
    (ImportError, AttributeError) to propagate.
    """
    module = import_module('%s.management.commands.%s' % (app_name, name))
    return module.Command()
```

Reference: [django.core.management.__init__.py](https://github.com/django/django/blob/main/django/core/management/__init__.py)


When you start a django project you use the following command:

```shell
django-admin startproject mysite
```

So when I started the application I used:

```shell
django-admin startproject project
```shell

This creates a base setup for your Django project. Please check the [first Django tutorial](https://docs.djangoproject.com/en/4.2/intro/tutorial01/) step to see what is created.

As you can see you receive a `manage.py` and a folder `my_site` which includes a `settings.py`.
In my own project I received a folder `project`. In this folder I added a folder called `settings` . Then I renamed `settings.py` into `base.py` and moved `base.py` into the folder `settings`. The `base.py` file can be imported to add flexibility on the specific server you are on. For instance, you can create a `local.py`, `ota.py`, `production.py` and/or `standalone.py`. All files hold all configuration of `base.py`, but data can be overwritten/updated for specific use cases. So for creating a standalone version I used all `base.py` configuration and updated the `DATABASES` and `INSTALLED_APPS` variables.

Please note, when compiling all configuration files are added even when they are not used because of the flag:

```shell
  --include-package=project
```

If you would follow the earlier mentioned tutorial `project` would be `my_site`. So when starting the application you specify which configuration you would want to use which in my case would be `project.settings.standalone`. I hope this answers your question.

**Comment by richardscholtens** [comment]
You must also include ` django.core.management.commands`  because this is where the ` runserver` command is located. I do believe it is best to include everything from the Django framework for it also hold out of the box functionality and styling. That is why I included the following flags:

```shell
  --include-package=django
  --include-package-data=django
```

Furthermore, it seems you can get app configuration information with the sample code below.

```python

from django.apps import apps

for app in apps.get_app_configs():
    print(app.verbose_name, ":")
    for model in app.get_models():
        print("\t", model)

``` 
[Reference stackoverflow](https://stackoverflow.com/questions/4111244/get-a-list-of-all-installed-applications-in-django-and-their-attributes)
[Reference Django documentation](https://docs.djangoproject.com/en/4.2/ref/applications/#django.apps.apps.get_app_configs)
[Reference Django Github code line 150](https://github.com/django/django/blob/main/django/apps/registry.py)

**Comment by kayhayen** [comment]
Including all of a package is a surefire way to maximize bloat though. For the code you gave, I won't know what to execute before that, right? In my world, I kind of don't know the structure of things, and if you check `__main__` or not, so that's kind of ugly to me... I wonder, if we had our own "app", if it then provide a command to run, say "compile" or "deploy" and then, running from without Django, could collect all the information like what you give there, and launch Nuitka with that background. Probably we can then also see static files configuration, and what not as well.

**Comment by richardscholtens** [comment]
Yeah, that is true. However, maybe it is best to first focus on a working prototype and afterwards try to minimize bloat. 

I believe you might need something like this:

[Django setup](https://github.com/django/django/blob/main/django/__init__.py)
[Django __main__](https://github.com/django/django/blob/main/django/__main__.py)
[Reference](https://www.upgrad.com/blog/django-applications/)

**Comment by jhbuhrman** [comment]
How to programmatically list all "root" modules of your used apps:
```python
from django.apps import apps
print([app_config.name for app_config in apps.get_app_configs()])
```

**Comment by richardscholtens** [comment]
Do make sure you give a specific settings file to the `manage.py` command.

Usage:

```shell
python manage.py print_settings --settings=project.settings.standalone
```

Output:

```text
...
INSTALLED_APPS                           = ['django.contrib.auth', 'django.contrib.contenttypes", 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'custom_app', 'crispy_forms', 'widget_tweaks', 'axes']
...
```

I only gave the `INSTALLED_APPS` settings output but this command will give every setting configuration setup variable.

**Comment by jhbuhrman** [comment]
> ```python
> print([app_config.name for app_config in apps.get_app_configs()])
> ```

More precisely:
```
python manage.py shell --settings project.settings.standalone -c "from django.apps import apps; print([app_config.name for app_config in apps.get_app_configs()])"
['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', ..., 'myapp1', 'myapp2']
```
This works under the assumption that you're building a program with a predetermined Django configuration file, as specified by the `--settings` option, `project/settings/standalone.py` in our case, since that config file determines what apps will be included in the Django-based application.

Hope this can be of use :-)

**Comment by kayhayen** [comment]
So, yes, I think we can make a Django plugin that will execute the main script given with said options, and kind of requires from your to have this extension installed. We can then use that to know these hidden dependencies. I will try and get that to work. Our own plugin for Django is then unnecessary at all.

**Comment by richardscholtens** [comment]
Glad we could be of help. Please let us know if you need additional information and/or help. It would be really nice if you can make Nuitka even more Django compatible!

**Comment by kayhayen** [comment]
I will schedule a stream to make this, I will keep you posted. If you joined me there, that would be cool, but it feels like I have enough to at least get us started, and produce the Nuitka plugin, that maybe you guys can then help complete when there are things missing. The basic setup I can do, but I am sure there will always be some settings and their combinations to add support for.

**Comment by kayhayen** [comment]
Very much expected. I got a new CI machine that will also double duty as a streaming platform. I got taxes to catch up with this week, but after that, this seems like a perfect one to go into now. It appears that `python manage.py print_settings --settings=project.settings.standalone` is kind of the way to go. Not sure now, if the settings should be in `manage.py` and why the argument would be needed, but I would like to have that plugin for Django handle the details and not the Nuitka plugin.

One thing I am not aware of, and I might have used Django myself before, but I believe I didn't have a settings file then, did I have to?

**Comment by richardscholtens** [comment]
The manage.py command does not show all commands when the settings file is missing. The settings file should be set at all times. In the manage.py file a default settings is always specified. You probably had it set without even knowing.

**Comment by kojibhy** [comment]
just curios why you try add manage.py? for production you will use gunicorn/uvicorn or Daphne.

**Comment by richardscholtens** [comment]
> just curios why you try add manage.py? for production you will use gunicorn/uvicorn or Daphne with asgi.py or wsgi.py as entry to your app.

Well, to be honest. I was not thinking about this. My main goal was to even try to compile the web application as a whole. When developing I always use manage.py to start up my processes locally. So I think I used it out of convenience.

However, it is a good suggestion to take a look at you proposals as well when I'm in a further stage. Gunicorn is incompatible with Windows so I probably cannot use that in my use case. My use case proposes that the standalone version works on Windows, Linux and MacOS. So uvicorn and daphne might be a good options. 

In my use case one must assume the hardware has no internet connection, thus manage.py will do as well I guess.

@jhbuhrman , how do you think about this?

**Comment by jhbuhrman** [comment]
> @jhbuhrman , how do you think about this?

Yep, our goal is to make a standalone version available of our Django application for browsing purposes, runnable from a (Windows) Laptop (permanently) without internet connectivity, to be used by a single user. Given those circumstances, I don't see a high-priority need to pull in a distinct WSGI or ASGI server.

**Comment by tunsmm** [comment]
Any updates about this issue?

**Comment by SokolovskiR** [comment]
Also waiting for updates on this issue

**Comment by jhbuhrman** [comment]
> Any updates about this issue?

Me and our project team are still planning to work on this for our project. Other priorities forced us to focus on other stuff first, unfortunately. I hope to get back to this in the course of 2024Q2

**Comment by kayhayen** [comment]
From my side, this is not really planned for now, there is other things to do. But help is very much wanted.

**Comment by mertcankurt** [comment]
Is there any development on this, i am also waiting for updates on this issue?

**Comment by mertcankurt** [comment]
If you need help with it, i can try to help in any way i can. I am a fullstack delevoper using django as a rest api backend. I really need this to work with runserver or gunicorn. Preferably gunicorn.

**Comment by kayhayen** [comment]
So, I think basic Django apps work, with the configuration being extracted from the config used in manage.py and the empty app as created by Django works for sure. So this should be resolved. If there are other issues with this, let me know but 2.7 should work perfectly for you.

**Comment by parasiteoflife** [comment]
I tried packaging my app but nuitka crashes with
```
FATAL: implicit-imports: Error, failed to evaluate expression '["%s.management.commands.*" % x for x in get_variable("django_installed_apps")]' in this context, exception was 'SyntaxError('invalid syntax', ('<unknown>', 1, 21, 'my_app v0.1.1', 1, 23))'.
```

I'm using Python 3.13.9, Django 5.2.10 and Windows 10

**Comment by kayhayen** [comment]
@parasiteoflife Posting below closed or unrelated issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
