### ISSUE TITLE
Add support for pyenv

### ISSUE THREAD

**Issue by loretoparisi** [Nuitka/Nuitka#1079]
I'm trying to build a `standalone` project of a simple test file importing `numpy`:

```
python -m nuitka --follow-imports --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings test.py
```

I get the following error:

```
undefined symbols for architecture x86_64:████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 994/995
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.7m.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.7m.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.7m.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.7m.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.7m.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.7m.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.7m.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.7m.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
                                                                                                                                                                      scons: *** [/Users/loretoparisi/Documents/Projects/AI/nuitka-test/test.dist/test] Error 1   
```

```
python --version
Python 3.7.10
```

```
mbploreto:nuitka-test loretoparisi$  python -m nuitka --version
0.6.14.4
Python: 3.7.10 (default, Apr 29 2021, 22:08:48) 
Executable: /Users/loretoparisi/.pyenv/versions/3.7.10/bin/python
OS: Darwin
Arch: x86_64
```

The whole compilation logs
```
Nuitka-Options:INFO: Used command line options: --follow-imports --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings test.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.                                                                     
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                                                       
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.six,pkg_resources._vendor.appdirs'.                                                                                                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'brotli._brotli' added '_cffi_backend'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'requests.packages' added 'urllib3,urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,urllib.response'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'cryptography' added '_cffi_backend'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib3' added 'urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,urllib.response'.                                               
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends' added 'matplotlib.backends._backend_agg,matplotlib.backends._tkagg,matplotlib.backends.backend_tkagg,matplotlib.backends.backend_agg'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg' added 'matplotlib.backends.backend_webagg_core,tornado'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib.backends.backend_webagg_core' added 'matplotlib.backends.backend_webagg,tornado'.   
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'matplotlib' added 'matplotlib.backend_managers,matplotlib.backend_bases,mpl_toolkits'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pycparser.c_parser' added 'pycparser.yacctab,pycparser.lextab'.
Nuitka-Plugins:INFO: pyzmq: Implicit dependencies of module 'zmq.backend' added 'zmq.backend.cython'.                                                                  
Nuitka-Plugins:WARNING: Use '--plugin-enable=pkg-resources' for: Resolve pkg_resources version information.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy._lib' added 'scipy._lib.messagestream'.                                                  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.                     
                                                                                                                                                                      Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                           
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.                                                             
Nuitka-Scons:INFO: Running clang -o module.asn1crypto.core.o -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -D_XOPEN_SOURCE -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=165 -D_NUITKA_EXE -I/Users/loretoparisi/.pyenv/versions/3.7.10/include/python3.7m -I. -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/include -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/static_src module.asn1crypto.core.c took 60.24 seconds
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running clang -o module.matplotlib.axes._axes.o -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -D_XOPEN_SOURCE -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=165 -D_NUITKA_EXE -I/Users/loretoparisi/.pyenv/versions/3.7.10/include/python3.7m -I. -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/include -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/static_src module.matplotlib.axes._axes.c took 98.03 seconds
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running clang -o module.matplotlib.patches.o -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -D_XOPEN_SOURCE -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=165 -D_NUITKA_EXE -I/Users/loretoparisi/.pyenv/versions/3.7.10/include/python3.7m -I. -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/include -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/static_src module.matplotlib.patches.c took 64.55 seconds
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running clang -o module.pyparsing.o -c -std=c11 -fvisibility=hidden -fwrapv -w -fvisibility=hidden -fvisibility-inlines-hidden -O3 -pipe -D_XOPEN_SOURCE -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=165 -D_NUITKA_EXE -I/Users/loretoparisi/.pyenv/versions/3.7.10/include/python3.7m -I. -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/include -I/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/nuitka/build/static_src module.pyparsing.c took 90.84 seconds
```

**Comment by kayhayen** [comment]
The `pyenv` Python's are typically compiled in some broken fashion. I doubt you can do hello world in accelerated mode. CPython and standard included Pythons work fine. Anaconda ought to work well too.

Since I will be looking at macOS some more in the coming weeks, can you provide the config you used with `pyenv` here. I understand it's more of a toolkit to build your own configurations, is it. But since `pyenv` has not be supportive in the future of Nuitka, I cannot promise it will ever improve.

**Comment by loretoparisi** [comment]
@kayhayen thank you, exactly which configuration do you need?

I have used 
pyenv shell 3.7.10

Because now macos has 3.9 by defaults by several frameworks will break on that.

**Comment by kayhayen** [comment]
I thought with pyenv you get to also provide configuration and tweaks, you are using some sort of baseline?

**Comment by loretoparisi** [comment]
So nothing specific, just installed through `brew` and then set up that version:
```
ip-192-168-178-30:~ loretoparisi$ pyenv version
3.7.10 (set by /Users/loretoparisi/.pyenv/version)
ip-192-168-178-30:~ loretoparisi$ pyenv --version
pyenv 1.2.26
```

and in `.bash_profile`:
```
eval "$(pyenv init -)"
```

**Comment by kayhayen** [comment]
Ok, thanks for the pointers. I will look into it.

**Comment by jtran** [comment]
I had the same error, but as mentioned in [this comment](https://github.com/Nuitka/Nuitka/issues/93#issuecomment-626039857), if you reinstall Python using this, it works.

```shell
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.10
```

I always use pyenv for development.  I've been using Nuitka with it for over a year now, and it (mostly) works with pyenv, despite claiming not to 🙂

**Comment by kayhayen** [comment]
I think Homebrew is pretty bad it seems. With pyenv, I think there were issues, some of which have been fixed since, but it seems a moving target. I got the standard Pythons supported on macOS well now, maybe one day I will be able to look into those.

New Nuitka should not need the shared library though, and would like a static link library in preference. You could try that and disable the shared library, it could still work, or will in the future. Not sure now how well Debian Python3 works with this, should on newer systems.

**Comment by kayhayen** [comment]
Any idea, how pyenv can be detect as a Vendor for the Python on Nuitka factory, this information is output, but "unknown" for pyenv (and Homebrew for that matter), but I would like to change it, so I can see it clearly in reports, and give advice on configuration options needed.

**Comment by jtran** [comment]
I'm guessing you mean `_getPythonVendor()` in `OptionParsing.py`.  Below is what `sys.executable` outputs.  The latter is when using a virtual environment.

```
$ python -i
Python 3.8.6 (default, Jan 21 2021, 01:57:32)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/Users/myusername/.pyenv/versions/3.8.6/bin/python'
>>>
$ cd -
$ python -i
Python 3.9.7 (default, Nov  3 2021, 16:11:14)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/Users/myusername/.pyenv/versions/MyVirtualEnvName/bin/python'
>>>
```

So basically, it's in `~/.pyenv`.

**Comment by kayhayen** [comment]
In virtualenv's that need not be the case though, but Nuitka has a function to get at the original `sys.executable`, and I made a sort of mistake with that too when I detect Apple OS Python. Also do you have a `PYENV_ROOT` environment variable defined?

**Comment by kayhayen** [comment]
Looking at pyenv docs, it seems impossible to not have that environent variable, and therefore I settled with this kind of code:

You might try it out at this:  https://nuitka.net/doc/factory.html

```
    elif os.environ.get("PYENV_ROOT") and isPathBelow(
        path=os.environ["PYENV_ROOT"], filename=getSystemPrefixPath()
    ):
````

**Comment by jtran** [comment]
I do have `PYENV_ROOT` set; its value is `/Users/myusername/.pyenv`.  I haven't tried running the factory code, but from looking at it, I think it makes sense.

**Comment by kayhayen** [comment]
I will be adding support for pyenv, currently on factory, it's not only detected as a vendor, it is also auto enabling the static link library. You should be able to drop the `PYTHON_CONFIGURE_OPTS="--enable-shared"` as Nuitka doesn't have to use that anymore, and it's only making things slower.

Since now Debian Python 2 is better than say Fedora Python's (CentOS, etc), using pyenv on those other platforms could be an easy way out of the non-optimal nature. Obviously I will want peope to use Nuitka-Python for Linux in the future, which will be even more suitable for Nuitka optimization (of programs), but this is nice to get on the way too, since on macOS esp. everybody seems doomed to have to use pyenv or Homebrew. Not sure yet about the later, I saw that it can install pyenv, but it also its own Python, does it not?

Not sure when I want to update the docs.

**Comment by kayhayen** [comment]
This is now on the develop branch, please give it a spin, esp. on macOS and let me know how it goes with your existing setups, no need to change anything just yet.

**Comment by jtran** [comment]
On macOS 10.15 Catalina, I made a fresh install of Python 3.9.6 through pyenv without special options, got the `develop` branch by doing `pip install https://github.com/Nuitka/Nuitka/archive/develop.zip`, and I got the same error as in this issue's description.  I tried it both with and without a virutalenv.  I tried reinstalling Nuitka with `--no-cache-dir`.  Same.

When I was researching this initially, I read someone else's issue talking about how compiling Python looks in `/usr/lib`, so depending on what else you have installed, it could affect it.  But I'm just guessing.  I stopped investigating into it further once I found that `--enable-shared` worked well enough for the development I was doing.  It would be nice, though, to be able to build something statically linked that could be distributed, especially as a single file that worked with code signing.

**Comment by kayhayen** [comment]
It could well be that pyenv on macOS produces garbage `libpython.a` and is not well maintained. After all, it also used to contain `main.o` for no reason on Linux e.g. something which I was able to workaround. I will have to reproduce this. I believe I have achieved pyenv to work on Linux. But the way I am seeing it, pyenv is more relevant on macOS even, so I will have to check out what the above error means.

I think it may the case that an OS library for localization needs to be added to the linkage there. I have had similar issues with Debian Python needing a hand to do OS level library linking. Shouldn't be too hard, but I might not have the time. But what does `python-config --libs` say for you there in the non-working configuration?

**Comment by jtran** [comment]
```
$ python-config --libs
-lpython2.7 -ldl -framework CoreFoundation
$ which python-config
/Users/myusername/.pyenv/shims/python-config
$ python --version
Python 3.9.6
```

Also, maybe it's unrelated, but with the latest `develop`, I'm getting this error which I haven't seen before.  I can open a separate issue if you'd like.

```
Problem with statement at /Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py:139:
-> system_version = tuple(sys.version_info)[:3]

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py', 'module_name': <ModuleName pkg_resources._vendor.pyparsing>, 'code_flags': ''}>'.
                                                                                                                       Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████▍ | 686/697
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/__main__.py", line 142, in <module>
    main()
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/__main__.py", line 128, in main
    MainControl.main()
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/MainControl.py", line 905, in main
    main_module = _createNodeTree(filename=filename)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/MainControl.py", line 192, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/Optimization.py", line 349, in optimizeModules
    finished = makeOptimizationPass()
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/Optimization.py", line 312, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/Optimization.py", line 207, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/Optimization.py", line 103, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ModuleNodes.py", line 523, in computeModule
    result = module_body.computeStatementsSequence(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/TraceCollections.py", line 608, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/TraceCollections.py", line 589, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ExpressionBases.py", line 1168, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/TraceCollections.py", line 589, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ExpressionBases.py", line 1187, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/CallNodes.py", line 82, in computeExpression
    return called.computeExpressionCall(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ConstantRefNodes.py", line 1335, in computeExpressionCall
    new_node, tags, message = computeBuiltinCall(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/OptimizeBuiltinCalls.py", line 1488, in computeBuiltinCall
    new_node = _dispatch_dict[builtin_name](call_node)
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/optimizations/OptimizeBuiltinCalls.py", line 516, in tuple_extractor
    return BuiltinParameterSpecs.extractBuiltinArgs(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/specs/BuiltinParameterSpecs.py", line 629, in extractBuiltinArgs
    positional = args.getIterationValues()
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ConstantRefNodes.py", line 212, in getIterationValues
    return tuple(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ConstantRefNodes.py", line 213, in <genexpr>
    makeConstantRefNode(
  File "/Users/myusername/.pyenv/versions/venv-3.9.6/lib/python3.9/site-packages/nuitka/nodes/ConstantRefNodes.py", line 1586, in makeConstantRefNode
    assert False, (constant, constant_type)
AssertionError: (sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0), <class 'sys.version_info'>)
```

**Comment by kayhayen** [comment]
@jtran thanks for pointing that out, seems recent improvements in optimization have unvealed a weakness in how `sys.version_info` works as a compile time constant in compile time simulation that need  it as an argument. The develop branch was rebased, and should work with this now.

**Comment by jtran** [comment]
Yes, that works.  It's back to the error in this issue description.

**Comment by kayhayen** [comment]
The changes made so far are part of the 0.6.18 release, which means it's supported on Linux. I am hoping  to provide a hotfix for macOS later.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made, macOS will be done separately, again maybe as a hotfix when I find the time.

**Comment by james-bellamy** [comment]
@kayhayen This issue appears to have re-emerged:

Using version
```
1.7.10
Commercial: None
Python: 3.8.13 (default, Aug 21 2023, 12:01:47)
Flavor: pyenv
Executable: /Users/james.bellamy/.pyenv/versions/3.8.13/bin/python3
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

linking is failing due to 
```
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.8.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.8.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.8.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.8.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.8.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.8.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.8.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.8.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

unless I use `python3.8 -m nuitka --onefile src/cli.py --output-dir=build --output-filename=output --static-libpython=no` once I've reinstalled python3.8 specifiying `PYTHON_CONFIGURE_OPTS="--enable-shared"`

**Comment by jtran** [comment]
As far as I know, pyenv support on macOS was never added, even though this issue was closed.

**Comment by kayhayen** [comment]
I had Homebrew working at some point. I think pyenv might be used in there. But since it's a moving target, chances are it's already broken again. But what I have, still works:

```
hayen@kaymac Py2C % python3.10 ~/repos/Py2C/bin/nuitka --version
1.8rc
Commercial: 2.2.3
Python: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: Homebrew Python
Executable: /opt/homebrew/Cellar/python@3.10/3.10.11/bin/python3.10
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
hayen@kaymac Py2C % python3.10 ~/repos/Py2C/bin/nuitka tests/standalone/CtypesUsing.py 
Nuitka-Options:INFO: Used command line options: --standalone tests/standalone/CtypesUsing.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile
Nuitka:WARNING: time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.8rc' on Python '3.10' commercial grade '2.2.3'.
Nuitka:INFO: Completed Python level compilation and optimization.                
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 6 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka:INFO: Keeping build directory 'CtypesUsing.build'.                       
Nuitka:INFO: Created binary that runs on macOS 13.0 (arm64) or higher.
Nuitka:INFO: Successfully created 'CtypesUsing.dist/CtypesUsing.bin'.
hayen@kaymac Py2C % ./CtypesUsing.dist/CtypesUsing.bin     
```

Notice that Homebrew is not very back portables, so I believe it is not relevant at all for the common use case.

I think pyenv out of the box might not at all be better on pyenv. Also, I will not forget how I was treated when I first reported a bug against pyenv that blocked its use with Nuitka at the time, and that I since have worked around. If you use pyenv, then surely because you can help yourself.

**Comment by kayhayen** [comment]
Changed the title to make clear, that Homebrew can be used instead, if you want these self-compiled Pythons and environments. I am updating the User Manual, pronouncing Homebrew as supported, and pyenv not just as "likely not working," but as "known not working". If anybody cares enough to maintain support for it in Nuitka, be my guest.
