### ISSUE TITLE
Python flag -OO makes numpy compilation fail

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#1091]
Hello,

When compiling pandas with `--python-flag=-OO`, the created program fails with the following error (see the provied SSCCE):

Compile command
```
C:\GIT\PROJECT\PythonSRC>c:\Python38-64\python.exe -m nuitka --python-flag=-OO --assume-yes-for-download --standalone --plugin-enable=numpy nuitka_test.py
```

Output
```
C:\GIT\PROJECT\PythonSRC\nuitka_test.dist>nuitka_test.exe
Traceback (most recent call last):
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\nuitka_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\pandas\__init__.py", line 11, in <module pandas>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\numpy\__init__.py", line 140, in <module numpy>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\numpy\core\multiarray.py", line 75, in <module numpy.core.multiarray>
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\numpy\core\overrides.py", line 207, in decorator
  File "C:\GIT\PROJECT\PYTHON~1\NUITKA~1.DIS\numpy\core\overrides.py", line 171, in decorator
TypeError: add_docstring() argument 2 must be str, not None
```

When removing the `--python-flag=-OO` flag, everything works as expected:

Compile command
```
C:\GIT\PROJECT\PythonSRC\nuitka_test.dist>c:\Python38-64\python.exe -m nuitka --assume-yes-for-download --standalone --plugin-enable=numpy nuitka_test.py
```

Output
```
C:\GIT\PROJECT\PythonSRC\nuitka_test.dist>nuitka_test.exe
Empty DataFrame
Columns: []
Index: []
```

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
c:\Python38-64\python.exe -m nuitka --version
0.6.14.7
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Executable: c:\Python38-64\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

Via `c:\Python38-64\python.exe -m pip install nuitka`

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

SSCCE program nuitka_test.py
```
import pandas

df = pandas.DataFrame()
print(df)
```

* The specific PyPI names and versions

```
aiofiles==0.5.0
aiosqlite==0.16.1
APScheduler==3.6.3
astroid==2.4.2
atomicwrites==1.4.0
attrs==20.3.0
bleach==3.3.0
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.3
command-runner==0.6.3
configparser-crypt==0.6.2
cryptidy==1.0.5
cryptography==3.2.1
docutils==0.16
et-xmlfile==1.0.1
fastapi==0.61.1
flup==1.0.3
forbiddenfruit==0.1.3
h11==0.11.0
idna==2.10
iniconfig==1.1.1
iso8601==0.1.14
isort==5.6.4
Jinja2==2.11.2
keyring==22.0.1
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
mtuprobe==0.1.0
multiprocessing-logging==0.3.1
Nuitka==0.6.14.7
numpy==1.19.3
ofunctions==2.0.3
ofunctions.file-utils==0.7.8
openpyxl==3.0.7
packaging==20.9
pandas==1.2.4
pkginfo==1.7.0
pluggy==0.13.1
psutil==5.7.2
py==1.10.0
pycparser==2.20
pycryptodomex==3.9.9
pydantic==1.6.1
Pygments==2.7.4
pygubu==0.10.3
pylint==2.6.0
pymemcache==3.4.0
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyPika==0.44.1
pytest==6.2.2
python-dateutil==2.8.1
python-tr==0.1.2
pytz==2020.5
pyuv==1.4.0
pyvmomi==7.0
pywin32==228
pywin32-ctypes==0.2.0
readme-renderer==28.0
requests==2.24.0
requests-pkcs12==1.9
requests-toolbelt==0.9.1
rfc3986==1.4.0
six==1.15.0
SQLAlchemy==1.3.19
starlette==0.13.6
tblib==1.7.0
toml==0.10.2
tortoise-orm==0.16.21
tqdm==4.56.1
twine==3.3.0
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.25.11
uvicorn==0.12.1
webencodings==0.5.1
windows-tools==2.0.1
WMI==1.5.1
wrapt==1.12.1
```

* Note if this is a regression

Don't know if this worked before :(

**Comment by kayhayen** [comment]
That's not working with Python though, is it? 

I wonder what Nuitka should do in these cases. Making code work with different input is not easy. Maybe this is something for the "anti-bloat" plugin as well, it probably does something very unnecessary there anyway. Another consideration could be to use the empty string rather than None, but that too is incompatible.

**Comment by deajan** [comment]
Looks like it works with python.
```
C:\GIT\PROJECT>c:\Python38-64\python.exe -OO nuitka_test.py
Empty DataFrame
Columns: []
Index: []
```

**Comment by kayhayen** [comment]
I managed to reproduce this, on Python 2.7 and Linux even.

**Comment by kayhayen** [comment]
The minimal reproducer has shrunk to `import numpy.core.multiarray` and that shows it. However, I am deeply confused as to how it's possible after adding a trace where the call stack points to:

```
                if dispatcher.__doc__ is None:
                    print("NONE DOC", dispatcher, implementation, add_docstring.__module__)

                add_docstring(implementation, dispatcher.__doc__)
```

And with Python, this outputs:

``` 
('NONE DOC', <function empty_like at 0x7ff3fb3eded8>, <built-in function empty_like>, 'numpy.core._multiarray_umath')
```

And with Nuitka:

```
('NONE DOC', <compiled_function empty_like at 0x7fd9cf98add0>, <built-in function empty_like>, 'numpy.core._multiarray_umath')
```

But dispatcher being different doesn't matter, because only its `__doc__` is used, and that's both cases None. Except of course, that with CPython it doesn't complain about the None value.

The actual code is in an extension module, so i think I don't see what it does, but I also have no idea how it could be different.

**Comment by trapezoid677** [comment]
The problem is discussed in detail here:

[https://github.com/numpy/numpy/issues/13248](url)

**Comment by kayhayen** [comment]
A lot of discussion, but Nuitka doesn't use bytecode, and is still affected.

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
Note, it requires to use anti-bloat plugin to work, something you want to do anyway and it's becoming the default in a future release.

**Comment by kayhayen** [comment]
This is part of the 0.6.17 release.
