### ISSUE TITLE
Python3.9 NuitkaOptimizationError with annotated generics

### ISSUE THREAD

**Issue by bphillips-exos** [Nuitka/Nuitka#1105]
I recently upgraded a project to Python 3.9 and changed the type annotations to [PEP 585](https://www.python.org/dev/peps/pep-0585) style. My project compiles fine except for one nested function with annotated generics. 

Versions:

* nuitka-0.6.14.7
* Python 3.9.4
* ubuntu:16.04

Python installed with apt-get (deadsnakes), Nuitka installed with pip.

Run with: 
```sh
nuitka3 --no-pyi-file --module featuremine_utils --include-package featuremine_utils
```

Minimal code to cause failure:

```python3
def f():
    def inner_f() -> list[str]:
        pass
```

Failure

```
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 133/150
  File "/usr/local/lib/python3.9/dist-packages/nuitka/__main__.py", line 185, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/nuitka/__main__.py", line 171, in main
    MainControl.main()
  File "/usr/local/lib/python3.9/dist-packages/nuitka/MainControl.py", line 692, in main
    main_module = _createNodeTree(filename=filename)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/MainControl.py", line 161, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/Optimization.py", line 379, in optimize
    finished = makeOptimizationPass()
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/Optimization.py", line 325, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/Optimization.py", line 220, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/Optimization.py", line 120, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/ModuleNodes.py", line 530, in computeModule
    result = module_body.computeStatementsSequence(
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/TraceCollections.py", line 539, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/ExpressionBases.py", line 1112, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/TraceCollections.py", line 539, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/FunctionNodes.py", line 1097, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/TraceCollections.py", line 435, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/FunctionNodes.py", line 501, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/FunctionNodes.py", line 516, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/optimizations/TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/usr/local/lib/python3.9/dist-packages/nuitka/nodes/TryNodes.py", line 141, in computeStatement
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementsFrameFunction" line="41" co_name="f" co_kind="Function" co_varnames="inner_f" co_freevars="" co_argcount="0" co_posonlyargcount="0" co_kwonlyargcount="0" co_has_starlist="False" co_has_stardict="False" co_filename="featuremine_utils/common.py" co_lineno="41" co_new_locals="True" co_is_optimized="True" code_flags="">
      <role name="statements" type="list">
        <node kind="StatementAssignmentVariable" line="42" variable_name="inner_f" is_temp="False" var_type="object" owner="featuremine_utils$common$$$function__3_f">
          <role name="source">
            <node kind="ExpressionFunctionCreation" line="42">
              <role name="defaults" type="list" />
              <role name="kw_defaults" type="none" />
              <role name="annotations">
                <node kind="ExpressionMakeDict" line="42">
                  <role name="pairs" type="list">
                    <node kind="ExpressionKeyValuePair" line="42">
                      <role name="key">
                        <node kind="ExpressionConstantStrRef" line="42" constant="'return'" user_provided="True" />
                      </role>
                      <role name="value">
                        <node kind="ExpressionSubscriptLookup" line="42">
                          <role name="expression">
                            <node kind="ExpressionConstantTypeRef" line="42" constant="&lt;class 'list'&gt;" />
                          </role>
                          <role name="subscript">
                            <node kind="ExpressionConstantTypeRef" line="42" constant="&lt;class 'str'&gt;" />
                          </role>
                        </node>
                      </role>
                    </node>
                  </role>
                </node>
              </role>
              <role name="function_ref">
                <node kind="ExpressionFunctionRef" line="42" code_name="featuremine_utils$common$$$function__3_f$$$function__1_inner_f" />
              </role>
            </node>
          </role>
        </node>
      </role>
    </node>
```

**Comment by kayhayen** [comment]
Unfortunately I cannot reproduce the crash, but the information from the exception is revealing. I was working on optimizing `list[int]` to a compile time constant, which is not happening with Nuitka stable, and that may cause issues. I will look into it.

**Comment by kayhayen** [comment]
This might be better on https://nuitka.net/doc/factory.html where I added a dedicated node type for this. So far we do not optimize the constant compile time result of `list[int]`, but other code expects that to happen, and either replace it with the exception, or a new constant value, but so far just nothing is done. In `--debug` you would have gotten a warning about this.

For code generation, I still need a way to create generic alias objects, then we could know not to have them, and that no exception can happen. For now, this will generate exception checks for the annotation value, which would be nice to avoid.

**Comment by kayhayen** [comment]
I also made an optimization that does constant generic alias values like these. There is plenty of potential for optimization of memory usage, because `list[str] is not list[str]` with CPython. For now, I only added the code generation for it, to see what happens with the dedicated compile time node for `GenericAlias` classes. Unfortunately, the can be mutable, if the arguments contain a concrete list or dictionary.

But with the code, annotations are now generated without assuming they could raise, which will make that better for optimization purposes.

**Comment by bphillips-exos** [comment]
Thanks for the quick response!

> Unfortunately I cannot reproduce the crash

Perhaps other code in the file contributed to the exception. Happy to try and create a self-contained example if that would help. 

> This might be better on https://nuitka.net/doc/factory.html

Yes! The build passes with the factory version. I did test against the "develop" version yesterday before creating the ticket, but that build failed.

**Comment by kayhayen** [comment]
Part of 0.6.15 release.
