### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by Justaus3r** [Nuitka/Nuitka#1113]
Hello,first a thanks for actively maintaining a incredible project like this.
I am compiling a python script using curses module,the exe is being built inside the dist folder but when ever i run the executable i get
this error:
```
$ Anfu.exe
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\Desktop\PROGRA~1\Anfu\ANFU~1.DIS\Anfu.py", line 26, in <module>
  File "C:\Users\ADMINI~1\Desktop\PROGRA~1\Anfu\ANFU~1.DIS\curses\__init__.py", line 13, in <module>
ModuleNotFoundError: No module named '_curses'
```
the script itself is running fine whenever i run it with python interpreter.i have tried on both windows 7 and 10 but no luck.
python version(i also tried with python 3.9 but same problem):
```
$ python --version
Python 3.8.3
```
nuitka version:
```
$ python -m nuitka --version                                                    
0.6.15                                                                          
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (A
MD64)]                                                                          
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python
.exe                                                                            
OS: Windows                                                                     
Arch: x86_64                                                                    
```
command i am using to compile the file:
```
python -m nuitka  --plugin-enable=tk-inter --standalone Anfu.py
```
Link to repo i am compiling: [here](https://github.com/Justaus3r/Anfu)
i am also compiling my other projects like [this](https://github.com/Justaus3r/Penta) one,and all other projects are compiling fine.the problem seems to occur only with scripts having curses module .does nuitka support curses,is there a workout for this cuz i really want to compile my script with nuitka for its promising speed.

**Comment by kayhayen** [comment]
When I tried to reproduce this, see what happens to me:

```
$ /c/Python38_64/python Mini.py
Traceback (most recent call last):
  File "Mini.py", line 1, in <module>
    import curses
  File "C:\Python38_64\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

```

None of my Pythons import this, also not Python2.7, which conflicts with your statement that the scripts runs for you. How so?

**Comment by Justaus3r** [comment]
hey @kayhayen ,thnx for the reply 
if you are on windows then you need to install curses using ```python -m pip install windows-curses```
then run it again.i think the problem is with linux curses,when you import linux curses you get that error so for windows the package is different.

**Comment by Justaus3r** [comment]
[Here](https://pypi.org/project/windows-curses/) is the link for pypi package.the package work's for python 2.7 and python 3.4 to 3.9.[this](https://github.com/zephyrproject-rtos/windows-curses) is the link for github repo of the wheels on pypi.i personally tested this package on python 3.7,3.8 and 3.9.
Here's a screenshot:
![link for 1 screenshot](https://drive.google.com/uc?export=download&id=1pLzLBP45ST2jWYMimifw7q2-zyrQe1Qc)

and after doing ```python Anfu.py```:

![link for 2 screenshot](https://drive.google.com/uc?export=download&id=1jXk0WG65sSZw2j49MAkzIY6dB9IBlytU)

**Comment by Justaus3r** [comment]
btw code tested on both linux and windows and i perfectly works,
Linux distro:Kali linux
Windows :Windows 7 and Windows 10

**Comment by kayhayen** [comment]
Thanks for your report, a fix for this is on the factory branch and will become part of the next hotfix.

https://nuitka.net/doc/factory.html
