### ISSUE TITLE
executable built with xmlschema module does not work on window 10 64bit

### ISSUE THREAD

**Issue by zosun** [Nuitka/Nuitka#1114]
I want to compile the following python script code to binary and compiling procedure is fine, but the final binary can't be launched successfully.

if I removed xmlschema related code, the compiled binary can be launched successfully.

**Python source code:**

import wx
import xmlschema

class AppFrame(wx.Frame):
    def __init__(self):
        super(AppFrame, self).__init__(None, title='External Tool', pos=(80, 80), size=(1080, 650),
                                       style=wx.DEFAULT_FRAME_STYLE & ~(wx.RESIZE_BORDER | wx.MAXIMIZE_BOX))
        self.init_ui()

    def init_ui(self):
        self.Show(True)

    def schema_check(self):
        schema = xmlschema.XMLSchema('dkdkdkk')
        schema.validate('kdkdkdk')

if __name__ == '__main__':
    app = wx.App()
    main_frame = AppFrame()
    app.MainLoop()

Her are details of my testing environment

**Window 10 platform information**
E:\>systeminfo

Host Name:                 DESKTOP-B5UG3HA
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Build Type:             Multiprocessor Free
Original Install Date:     1/16/2021, 8:39:13 PM
System Boot Time:          5/28/2021, 12:21:13 PM
System Manufacturer:       Dell Inc.
System Model:              Inspiron 5559
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2601 Mhz
BIOS Version:              Dell Inc. 1.9.0, 9/7/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,083 MB
Available Physical Memory: 7,319 MB
Virtual Memory: Max Size:  18,515 MB
Virtual Memory: Available: 5,769 MB
Virtual Memory: In Use:    12,746 MB
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Python interpreter version. No virtual python environment.**

Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32

**Nuitka version:** 
E:\>python -m nuitka --version
0.6.14
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64

**Nuitka install command:**

python -m pip install nuitka

**command to build the script:**

E:\>python -m nuitka --windows-disable-console --plugin-enable=pylint-warnings --plugin-enable=numpy --windows-company-name=Nodoby --windows-product-version=2.1.0 --windows-product-name="External Tool"  --onefile  test_xmlschema_ui.py

**Comment by zosun** [comment]
After remove --windows-disable-console option, the executable will report following trace back.

Traceback (most recent call last):
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 1499, in open_local_file
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tester\\AppData\\Local\\Nodoby\\EXTERN~1\\210~1.0\\xmlschema\\schemas\\XSD_1.0\\XMLSchema.xsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\test_xmlschema_ui.py", line 2, in <module>
    import xmlschema
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\__init__.py", line 20, in <module xmlschema>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\dataobjects.py", line 20, in <module xmlschema.dataobjects>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\validators\__init__.py", line 38, in <module xmlschema.validators>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\validators\schema.py", line 1900, in <module xmlschema.validators.schema>
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\validators\schema.py", line 130, in __new__
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\validators\schema.py", line 718, in create_meta_schema
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\validators\schema.py", line 324, in __init__
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\resources.py", line 394, in __init__
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\xmlschema\resources.py", line 600, in parse
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 214, in urlopen
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 517, in open
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 534, in _open
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 494, in _call_chain
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 1477, in file_open
  File "C:\Users\tester\AppData\Local\Nodoby\EXTERN~1\210~1.0\urllib\request.py", line 1516, in open_local_file
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: 'C:\\Users\\tester\\AppData\\Local\\Nodoby\\EXTERN~1\\210~1.0\\xmlschema\\schemas\\XSD_1.0\\XMLSchema.xsd'>

**Comment by kayhayen** [comment]
You need to include the data files of `xmlschema` it seems. Does your example need any files as input for `xmlschema`?

**Comment by zosun** [comment]
It should be caused by the implementation of xmlschema. 

some meta data in the folder xmlschema is included by the following code.

os.path.join(SCHEMAS_DIR, 'XSD_1.0/XMLSchema.xsd')

the file is not copied the final target folder. the compiled executable can be launched successfully if I copied these files manually to the folder: C:\Users\tester\AppData\Local\Nodoby\EXTERN1\2101.0\

Per my understanding nuitka already provides method to include the metadata for some modules. Is that correct?

**Comment by zosun** [comment]
as long as I include xmlschema module and make one instance of XMLSchema class, the issue will occur. even my script does not need any file as input for xmlschema.

**Comment by zosun** [comment]
In another word, in order to create one instance of XMLSchema,  it needs input of XSD_1.0/XMLSchema.xsd which is in the folder of C:\Python39\Lib\site-packages\xmlschema\schemas\XSD_1.0, XMLSchema import this metadata by API call os.path.join(SCHEMAS_DIR, 'XSD_1.0/XMLSchema.xsd') instead of import directive.  Nuitka does not detect the existence of these metadata by missing of import directive.

**Comment by kayhayen** [comment]
Yes, there is an option to include the data files for a package entirely or specific ones, just read the help output. Once I find the time, I will look at adding it to the data files plugin so it becomes automatic.

**Comment by zosun** [comment]
You are correct. Here is my solution.
1. copy the file from xmlschema folder to my source folder
2. add option --include-data-dir=".\schemas"=".\xmlschema\schemas"
then the issue disappeared. 

thanks Kay

**Comment by kayhayen** [comment]
There is also an option that takes package names and files relative to it.

Can I enlist you to describe these options in "Missing data files in standalone" in the `README.rst` ? That seems very much missing.

**Comment by zosun** [comment]
> There is also an option that takes package names and files relative to it.
> 
> Can I enlist you to describe these options in "Missing data files in standalone" in the `README.rst` ? That seems very much missing.

Is that option --include-package=xmlschema ? I tried that and it didn't work. 
I also tried --include-package=xmlschema --include-package-data="schemas" and it didn't work.

**Comment by kayhayen** [comment]
Interesting, that should have worked. I will check it out too.

**Comment by kayhayen** [comment]
@zosun you made a mistake with the same for `--include-package-data`, that should not be the name of any of that package data, but the package you want to address, so that's `--include-package-data=xmlschema` there, and that ought to work.

**Comment by zosun** [comment]
> @zosun you made a mistake with the same for `--include-package-data`, that should not be the name of any of that package data, but the package you want to address, so that's `--include-package-data=xmlschema` there, and that ought to work.

@kayhayen you are right. It works now. How can I  describe these options in "Missing data files in standalone" in the README.rst.  Do I have the right to modify README.rst?

**Comment by kayhayen** [comment]
You have the right and moral obligation to modify it such that it best describes the tools available, such that people have an easier time that you now. I will at one point, for the spefific example at hand, make it entirely unnecessary.
