### ISSUE TITLE
Python3.9: Could crash or raise exceptions with generic aliases

### ISSUE THREAD

**Issue by bphillips-exos** [Nuitka/Nuitka#1115]
This issue stems from the same code that caused the issues in [1105](https://github.com/Nuitka/Nuitka/issues/1105).

A function with the following annotation compiles without error, but fails when imported from the compiled artifact. I get the same behavior with 0.6.15 and the factory version.

Function:
```python3
def f(arg: str) -> Callable[[dict], set[str]]:
    ...
```

If I change the function to the following, I do not get the error on import (no `set[str]`)
```python3
def f(arg: str) -> Callable[[dict], set]:
    ...
```

Error:
```
  File "/usr/lib/python3.9/_collections_abc.py", line 430, in __new__
    return cls.__create_ga(origin, args)
  File "/usr/lib/python3.9/_collections_abc.py", line 440, in __create_ga
    if not isinstance(args, tuple) or len(args) != 2:
SystemError: <built-in function isinstance> returned a result with an error set
```

Versions:
* nuitka-0.6.15
* Python 3.9.4
* ubuntu:16.04

**Comment by kayhayen** [comment]
I will need a minimal reproducer, this of course works fine for me.

**Comment by bphillips-exos** [comment]
@kayhayen here is a self-contained example which segfaults when imported, I'm not sure what determines segfault vs SystemError. Will try to create an example that raises the SystemError.

`/simple/simple.py` compiled with `nuitka3 --no-pyi-file --module simple --include-package simple`
```python3
from collections.abc import Callable


def f(a: str) -> Callable[[dict], set[str]]:
    def _f(b: dict) -> set[str]:
        return set()

    return _f
```

```
root@58a2f86b5783:/exos# python3.9 -c 'from simple.simple import f'
Segmentation fault
```

One other detail I missed from earlier, there is a TypeError which causes the SystemError.

```
TypeError: DEEP_COPY does not implement: types.GenericAlias

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
  File "/usr/lib/python3.9/_collections_abc.py", line 430, in __new__
    return cls.__create_ga(origin, args)
  File "/usr/lib/python3.9/_collections_abc.py", line 440, in __create_ga
    if not isinstance(args, tuple) or len(args) != 2:
SystemError: <built-in function isinstance> returned a result with an error set
```

**Comment by kayhayen** [comment]
Yup, that DEEP_COPY may in fact be the thing that causes this both and is a severe problem that I will have to hotfix. Some code paths expect no error from it to be possible.

**Comment by kayhayen** [comment]
Please check this out, I will make it part of a hotfix as soon as possible: https://nuitka.net/doc/factory.html

**Comment by bphillips-exos** [comment]
The factory version is working for both the example above and the original code. Thank you!

**Comment by kayhayen** [comment]
Part of 0.6.15.2 hotfix release.
