### ISSUE TITLE
TensorflowPlugin: Do not use split on ModuleName objects

### ISSUE THREAD

**Issue by Josh596** [Nuitka/Nuitka#1122]
Version - 0.6.15.1
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
OS: Windows
Arch: x86_64

**When I include --plugin-enable=tensorflow in my script, this happens:**
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.15.1' on Python '3.8' commercal None.
Traceback (most recent call last):
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka__main__.py", line 187, in <module>
    main()
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka__main__.py", line 173, in main
    MainControl.main()
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkaMainControl.py", line 706, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkaMainControl.py", line 93, in _createNodeTree
    main_module = Building.buildModuleTree(
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkatree\Building.py", line 1158, in buildModuleTree
    module, source_ref, source_code = decideModuleTree(
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkatree\Building.py", line 1005, in decideModuleTree
    mode=decideCompilationMode(False, module_name, source_ref),
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkatree\Building.py", line 932, in decideCompilationMode
    result = Plugins.decideCompilation(module_name, source_ref)
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkaplugins\Plugins.py", line 568, in decideCompilation
    value = plugin.decideCompilation(module_name, source_ref)
  File "C:\Users\JOSHUA\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitkaplugins\standard\TensorflowPlugin.py", line 89, in decideCompilation
    elements = module_name.split(".")
  File "<string>", line 3, in split
nuitka.Errors.NuitkaCodeDeficit:
Do not use split on ModuleName objects, use e.g.
.hasNamespace(),
.getBasename(),
.getTopLevelPackageName()
.hasOneOfNamespaces

Check API documentation of nuitka.utils.ModuleNames.ModuleName

**Comment by SachinGanesh** [comment]
Getting same error when using **--plugin-enable=tensorflow**

**Comment by kayhayen** [comment]
Part of 0.6.15.3 hotfix release.
