### ISSUE TITLE
ImportError: cannot import name 'ExifTags' from 'PIL'

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#1133]
`
import cv2
import torch
from PIL import Image, ImageDraw, ImageFont, ImageTk

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

for f in ['zidane.jpg', 'bus.jpg']:
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
img1 = Image.open('zidane.jpg')  # PIL image
img2 = cv2.imread('bus.jpg')[:, :, ::-1]  # OpenCV image (BGR to RGB)
imgs = [img1, img2]  # batch of images

results = model(imgs, size=640)  # includes NMS

results.print()  
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)`

-----------

python -m nuitka --standalone --output-dir=out --plugin-enable=tk-inter --plugin-enable=numpy --plugin-enable=torch  --plugin-enable=pylint-warnings --plugin-enable=pkg-resources --follow-import-to=requests --include-package=requests --include-package=yaml   ./main.py

--------------------------

Using cache found in C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master
Traceback (most recent call last):
  File "E:\yolov5\cc\out\main.dist\main.py", line 30, in <module>
  File "E:\yolov5\cc\out\main.dist\torch\hub.py", line 339, in load
  File "E:\yolov5\cc\out\main.dist\torch\hub.py", line 368, in _load_local
  File "C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 65, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 28, in _create
    from models.yolo import Model, attempt_load
  File "C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 16, in <module>
    from models.common import *
  File "C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 15, in <module>
    from utils.datasets import letterbox
  File "C:\Users\mm/.cache\torch\hub\ultralytics_yolov5_master\utils\datasets.py", line 22, in <module>
    from PIL import Image, ExifTags
ImportError: cannot import name 'ExifTags' from 'PIL' (E:\yolov5\cc\out\main.dist\PIL\__init__.py)

**Comment by kayhayen** [comment]
Just as an aside, make sure to use the anti-bloat plugin from next release, this has very bad dependency creep. I can reproduce this with only code `PIL import Image, ExifTags` which is very strange, given it's a plain import. Probably it's another plugin missing.

**Comment by kayhayen** [comment]
I wonder what `PIL_init.py` is here, Can it be something that `yolov5` has and actually copied there. It doesn't look like something lives on systems normally. I guess you have to used `--include-module` on it as well. Whatever that thing in ".cache" is doing there, Nuitka hasn't see it at compile time.

**Comment by kayhayen** [comment]
Probably this would be something the torch plugin could do, looking at that extra code. But Torch is really only a program generator there, so using Nuitka might be heavily wrong there.

**Comment by kayhayen** [comment]
I am going over old issues that escaped my attention, this seems like a good example code actually. I would hope the original issue is solved, but this seems to cover `torch.hub` which is nice and does some actual work.

**Comment by kayhayen** [comment]
So, it appears, that it downloads on the target machine, which I would assume is not desirable, and then the downloaded code, e.g. does not find `psutil`. I believe we should have a Nuitka plugin that deals with this, or some sort of hard import logic, where the node can handle this. I am not sure though what `hubconf.py` is supposed to and if we will be able to do it.

Somebody with more knowledge about these downloads should help me there.
