### ISSUE TITLE
How to include external packages as part of the Nuitka build for a Conda environment

### ISSUE THREAD

**Issue by zerovirus123** [Nuitka/Nuitka#1144]
Python: 3.7.7
Nuitka: 0.6.15.3
OS: Windows 10

I have a relatively complex computer vision project inside a Conda environment. One of the dependencies, OpenCV, is not installed with either Conda or pip. Instead, it is built using CMake and then copied inside site-packages. I built my project using this command: python -m nuitka --mingw64 --standalone --plugin-enable=numpy --plugin-enable=torch --plugin-enable=pylint-warnings --plugin-enable=tensorflow --plugin-enable=pkg-resources --plugin-enable=qt-plugins main.py.

When I tried running main.exe, the executable could not find the cv2 package. Then I copied the cv2 package inside main.dist. When the executable tried importing cv2, the program threw a import recursion error.

``
['F:\\Sliding_Windows\\main.dist', 'F:/Sliding_Windows/main.dist/cv2', 'F:\\Sliding_Windows\\main.dist']
Traceback (most recent call last):
  File "F:\Sliding_Windows\main.dist\main.py", line 1, in <module>
  File "F:\Sliding_Windows\main.dist\cv2\__init__.py", line 102, in <module cv2>
    bootstrap()
  File "F:\Sliding_Windows\main.dist\cv2\__init__.py", line 90, in bootstrap
    import cv2
  File "F:\Sliding_Windows\main.dist\cv2\__init__.py", line 102, in <module cv2>
    bootstrap()
  File "F:\Sliding_Windows\main.dist\cv2\__init__.py", line 27, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
``
I renamed the binaries path in config.py and config-3.7.py, but that changed nothing. How does Nuitka find all the packages for a target Conda environment? Is there a config or environment file that I should modify to include my cv2 package? Thanks.

**Comment by zerovirus123** [comment]
I have managed to find a workaround for this issue. For the production environment, remove the cv2 package built from source. Then, pip install opencv-python. Copy the cv2.pyd and dll files built from source into the new cv2 folder in site-packages. Build the project, and then copy the .pyd and .dll files into ${project_name}.dist/cv2.

**Comment by kayhayen** [comment]
Nuitka does nothing special when resolving imports, it just looks at the `sys.path` and that ought to work. Does it run without your self compiled thing? Or would it need the DLLs too? That's things we do in the implicit imports plugin already. If you could confirm that, I can do it.

However, your self compiled version may not be "standalone", is it? Building packages from source such that they are as good as the wheels is on Windows a task that doesn't always succeed.

Yours,
Kay

**Comment by zerovirus123** [comment]
Hi Kay,

       Since my source code requires OpenCV to function, doing a build without my self-compiled OpenCV2 would probably generate an executable with missing imports. The next best thing is probably just pip install opencv-python and build the project as it is. However, opencv-python from pip has no CUDA support, whereas my self-compiled version has CUDA in addition to other supports.

       What do you mean by standalone? Aren't CMake compiled OpenCV with output .pyds and .dlls standalones? Or do I need to add the site-packages path for OpenCV before building the project?

Thanks,
Brian

**Comment by kayhayen** [comment]
I don't know that. I know that wheels are built that way. Maybe your build is that way too, maybe not.
