### ISSUE TITLE
Shapely Support For Nuitka

### ISSUE THREAD

**Issue by zerovirus123** [Nuitka/Nuitka#1153]
I was trying to build Geopandas and I noticed that it could not resolve the shapely dependency. Shapely is a library that is a dependency for many GIS libraries (GDAL, geopandas, etc...).

```Build Command
python -m nuitka --mingw64 --standalone --include-package=shapely --jobs 12 nuitka_test.py
```

 ```
# Python code
import shapely
import shapely.geos
import ctypes
```
The executable is compiled successfully, but crashes when it tries to locate the dependencies.
```
          Traceback (most recent call last):
          File "F:\Sliding_Windows\nuitka_test.dist\nuitka_test.py", line 49, in <module>
          File "<frozen importlib._bootstrap>", line 983, in _find_and_load
          File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
          File "F:\Sliding_Windows\nuitka_test.dist\shapely\geos.py", line 149, in <module shapely.geos>
          File "F:\Sliding_Windows\nuitka_test.dist\ctypes\__init__.py", line 364, in __init__
OSError: [WinError 126] The specified module could not be found.
```
Seems like Nuitka could not locate some of the dependencies for the build. I have looked through other posts and some have expressed a similar problem. Is there something like a config.py or yaml that allows users to add hidden dependencies?

**Comment by kayhayen** [comment]
Yes, this will be a DLL missing, I will look into it.

**Comment by kayhayen** [comment]
This is fixed on the factory branch: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is currently on the develop branch and supposed to be working.

**Comment by zerovirus123** [comment]
Will check it out. Thanks.

**Comment by kayhayen** [comment]
This is part of the 0.7 release now.
