### ISSUE TITLE
Executing binary fails - pypsrp/urllib3

### ISSUE THREAD

**Issue by ghost** [Nuitka/Nuitka#1158]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
0.6.16.2
Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
Executable /usr/bin/python3
OS: Linux (Debian 10)
Arch: X86_64
```

* How did you install Nuitka and Python
```
pip3 install nuitka
```
* The specific PyPI names and versions
```
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.1
cryptography==3.4.7
decorator==5.0.9
gssapi==1.6.14
idna==3.2
pycparser==2.20
pypsrp==0.5.0
pyspnego==0.1.6
requests==2.26.0
six==1.16.0
urllib3==1.26.6
```
* Many times when you get an error from Nuitka, your setup may be special
Code:
```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan
import gssapi
from urllib3 import * #needed for nuitka
from urllib3 import exceptions

if __name__ == '__main__':
    wsman = WSMan(server="server", username="user",password="pass",ssl=False)
    print("Hi")
    # with wsman, RunspacePool(wsman) as pool:
    #    ps = PowerShell(pool)
    #    ps.add_script("whoami")
    #    output = ps.invoke()

```

* In your issue the options used
```
python3 -m nuitka main.py --standalone
python3 -m nuitka main.py --standalone --include-package=urllib3 --include-package=pypsrp
```
Error:
```
Compiling gives no errors but executing the binary on the same system does.


Traceback (most recent call last):
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/main.py", line 1, in <module>
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/pypsrp/powershell.py", line 29, in <module pypsrp.powershell>
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/pypsrp/shell.py", line 9, in <module pypsrp.shell>
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/pypsrp/wsman.py", line 9, in <module pypsrp.wsman>
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/requests/__init__.py", line 43, in <module requests>
  File "/tmp/mounta/PYTHON/nuitka_test/main.dist/urllib3/__init__.py", line 11, in <module urllib3>
ImportError: cannot import name 'exceptions' from 'urllib3' (/tmp/mounta/PYTHON/nuitka_test/main.dist/urllib3/__init__.py)
```

Is there anything I am doing wrong?

**Comment by kayhayen** [comment]
The star import is not doing what you think it does, it's not importing sub-packages, but I can't tell what's wrong from your end, should be a bug in Nuitka. However, urllib3 should be something reported already, will have to check out, if the way inclusion is forced might do anything to it.

**Comment by Reduxonowa** [comment]
Yes, Ive testet a lot combinations.
Ive found another post where sombody used "--include-module=urllib3". That leads to a "segmentation fault".
I am still not sure what should be used.. include-module or include-package?

Thank you for having a look!

**Comment by Reduxonowa** [comment]
I did compile in the past with Nuitka different things on different computers. After searching for my notes I did this(downgraded as this was the version the last project compiled):
pip3 install --force-reinstall nuitka==0.6.11.6
pip3 install --force-reinstall urllib3==1.26.3
After that I noticed there is another package called urllib3 in dist-packages folder -> apt remove python3-urllib3 
after that it compiles and shows the print with "Hi"!

After that i upgraded the packages again to see if it had anything to do with the dist package thing or if it was the packages:
pip3 install --force-reinstall urllib3==1.26.6
when I execute it (compiled with the same arguments as before) I get:
zsh: segmentation fault ./main

then I run 
pip3 install --force-reinstall nuitka==0.6.11.6
and get for execution:
"Hi"


So what can i tell. With Version 0.6.11.6 of Nuitka it works!
i will try to compile the bigger project now...

**Comment by Reduxonowa** [comment]
not urllib3 anymore but on the bigger project I get something else now:

```
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pypsrp/powershell.py", line 29, in <module pypsrp.powershell>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pypsrp/shell.py", line 9, in <module pypsrp.shell>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pypsrp/wsman.py", line 19, in <module pypsrp.wsman>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pypsrp/negotiate.py", line 7, in <module pypsrp.negotiate>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/spnego/__init__.py", line 12, in <module spnego>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/spnego/_context.py", line 31, in <module spnego._context>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/spnego/exceptions.py", line 19, in <module spnego.exceptions>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/gssapi/__init__.py", line 4, in <module gssapi>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/gssapi/bindings/__init__.py", line 230, in <module gssapi.bindings>
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/gssapi/bindings/__init__.py", line 187, in _read_header
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pkg_resources/__init__.py", line 1134, in resource_exists
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pkg_resources/__init__.py", line 1404, in has_resource
  File "/tmp/mounta/PYTHON/projectos/bin/main.dist/pkg_resources/__init__.py", line 1457, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
```

Any Ad-Hoc idea? Otherwise I will test a bit more and create a new issue.

**Comment by kayhayen** [comment]
I have some hopes that recent changes made for 0.6.18 fix the problem reported, but I have yet to try your test case, which seems might be interesting anyway.

**Comment by kayhayen** [comment]
The `urllib3.exceptions` is listed as an implicit dependency of `urllib3`, so this ought to be good already from that.

**Comment by kayhayen** [comment]
This works for me with 0.7 on Windows. I noticed you used Linux, kind of assumed this was a Linux only feature. Can you retry on what looks to be your Debian 10 system? Maybe the Debian packaging version of `urllib3` is not working with Nuitka, I would love to know that, but I think that also should not be an issue anymore.
