### ISSUE TITLE
gssapi not compatible with Nuitka

### ISSUE THREAD

**Issue by Reduxonowa** [Nuitka/Nuitka#1161]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
0.6.16.2
Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
Executable /usr/bin/python3
OS: Linux (Debian 10)
Arch: X86_64
```

* How did you install Nuitka and Python
```
pip3 install nuitka
```
* The specific PyPI names and versions
```
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.1
cryptography==3.4.7
decorator==5.0.9
gssapi==1.6.14
idna==3.2
pycparser==2.20
pypsrp==0.5.0
pyspnego==0.1.6
requests==2.26.0
six==1.16.0
urllib3==1.26.6
```
* Many times when you get an error from Nuitka, your setup may be special
Code:
```
import gssapi

if __name__ == '__main__':
    print("Hi")

```

* In your issue the options used
```
python3 -m nuitka main.py --standalone
python3 -m nuitka main.py --standalone --include-package=gssapi
```
Error:
```
 % ./main
Traceback (most recent call last):
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/gssapi/__init__.py", line 4, in <module gssapi>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/gssapi/bindings/__init__.py", line 230, in <module gssapi.bindings>
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/gssapi/bindings/__init__.py", line 187, in _read_header
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/pkg_resources/__init__.py", line 1134, in resource_exists
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/pkg_resources/__init__.py", line 1404, in has_resource
  File "/tmp/mounta/PYTHON/nuitka_test/bin/main.dist/pkg_resources/__init__.py", line 1457, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
```

Seems that gssapi is not compatible with gssapi.

Related to: https://github.com/Nuitka/Nuitka/issues/1158
Basically I am just trying to use pypsrp which requires gssapi.

**Comment by Reduxonowa** [comment]
It is working. Something is extremely messed up with my pip packages. Will clean everything from python / pip and try again. But for all others: it is working.
