### ISSUE TITLE
cc1.exe: out of memory allocating 65536 bytes 

### ISSUE THREAD

**Issue by Josh596** [Nuitka/Nuitka#1165]
Python version - 3.8.8
Nuitka version - 0.6.16.2

I ran python -m nuitka --standalone --mingw64 --windows-icon-from-ico=icons/appicon.ico --windows-company-name=company_name --windows-product-name=product_name --windows-product-version=1.1.0 --windows-disable-console --plugin-enable=pyside6 --plugin-enable=numpy --plugin-enable=pkg-resources --assume-yes-for-download --run  --windows-force-stderr-spec=%PROGRAM%.err.txt launch_app.py

I've tried this on two different PCs
**PC 1**
1. Windows 10 (64bit)
2. 8gb RAM
3. Ryzen 5200U

**PC 2**
1. Windows 10(64bit)
2. 8gb RAM
3. Intel Core i7

The script runs for about an hour and 30 minutes and stops.

**Comment by Josh596** [comment]
Okay. It compiles successfully on a 16gb RAM pc, but I get this error - 
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found

Full Error Log:
Traceback (most recent call last):
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\launch_app.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_main.py", line 12, in <module puzzle_main>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_ui.py", line 18, in <module puzzle_ui>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon_view_port.py", line 20, in <module cartoon_view_port>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon\cartoon.py", line 1, in <module cartoon.cartoon>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\__init__.py", line 55, in <module tensorflow>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\__init__.py", line 39, in <module tensorflow._api.v2.compat>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module tensorflow._api.v2.compat.v1>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 39, in <module tensorflow._api.v2.compat.v1.compat>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\compat\v1\__init__.py", line 51, in <module tensorflow._api.v2.compat.v1.compat.v1>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\__init__.py", line 11, in <module tensorflow._api.v2.compat.v1.lite>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\experimental\__init__.py", line 10, in <module tensorflow._api.v2.compat.v1.lite.experimental>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\experimental\nn\__init__.py", line 10, in <module tensorflow._api.v2.compat.v1.lite.experimental.nn>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\python\lite.py", line 38, in <module tensorflow.lite.python.lite>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\experimental\microfrontend\python\ops\audio_microfrontend_op.py", line 29, in <module tensorflow.lite.experimental.microfrontend.python.ops.audio_microfrontend_op>
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\python\framework\load_library.py", line 58, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found

**Comment by kayhayen** [comment]
Closing for lack of feedback.
