### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by Josh596** [Nuitka/Nuitka#1166]
Windows 10 (64bit)
Python 3.8.9
Tensorflow 2.5.0
Nuitka 0.6.16.2

After compiling a PySide6 app that involves tensorflow, I get this when I try to run the exe:
Traceback (most recent call last):
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\launch_app.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_main.py", line 12, in <module puzzle_main>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_ui.py", line 18, in <module puzzle_ui>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon_view_port.py", line 20, in <module cartoon_view_port>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon\cartoon.py", line 1, in <module cartoon.cartoon>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\__init__.py", line 55, in <module tensorflow>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\__init__.py", line 39, in <module tensorflow._api.v2.compat>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module tensorflow._api.v2.compat.v1>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 39, in <module tensorflow._api.v2.compat.v1.compat>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\compat\v1\__init__.py", line 51, in <module tensorflow._api.v2.compat.v1.compat.v1>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\__init__.py", line 11, in <module tensorflow._api.v2.compat.v1.lite>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\experimental\__init__.py", line 10, in <module tensorflow._api.v2.compat.v1.lite.experimental>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\_api\v2\compat\v1\lite\experimental\nn\__init__.py", line 10, in <module tensorflow._api.v2.compat.v1.lite.experimental.nn>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\python\lite.py", line 38, in <module tensorflow.lite.python.lite>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\experimental\microfrontend\python\ops\audio_microfrontend_op.py", line 29, in <module tensorflow.lite.experimental.microfrontend.python.ops.audio_microfrontend_op>
  File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\python\framework\load_library.py", line 58, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found

**Comment by nickjbenson** [comment]
I was just hitting this issue for a project as well. I'm not sure why, but it seems like Nuitka doesn't copy the tflite experimental folder from your site-packages into the `.dist` folder. It's not necessarily "wrong" on Nuitka's part, because, why would a Windows distribution require any Linux library `.so` file? Nevertheless, TensorFlow complains if it's missing. 

I was able to work around this issue by copying the `experimental` folder in my virtual environment's site-packages folder into the distribution folder, after the compilation was finished. E.g., I copied:
```
<path_to_env>/env/Lib/site-packages/tensorflow/lite/experimental
```
to:
```
<path_to_dist_folder/<your_lib>.dist/tensorflow/lite/experimental
```

After doing this, I can successfully get past this error when running the compiled executible in the `.dist` folder. For me, I hit and worked-around this issue when using TensorFlow 2.5.0.

**Comment by Josh596** [comment]
@nickjbenson 
After I did this, I now get the following error when I try to run the executable 
Traceback (most recent call last): File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\launch_

app.py

", line 1, in <module> File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_

main.py

", line 12, in <module puzzle_main> File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\puzzle_

ui.py

", line 18, in <module puzzle_ui> File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon_view_

port.py

", line 20, in <module cartoon_view_port> File "C:\Users\lflot\Desktop\PUZZLE~1\LAUNCH~1.DIS\cartoon\

cartoon.py

", line 2, in <module cartoon.cartoon> ModuleNotFoundError: No module named 'tensorflow.compat'

Any ideas?

**Comment by Josh596** [comment]
These are lines 1 and 2 of the cartoon.py file 

1 import tensorflow.compat.v1 as tf
2 from tensorflow.python.platform import gfilefrom

**Comment by nickjbenson** [comment]
Not sure, I don't hit that issue with my compilation. I do have to have the tensorflow plugin enabled when building anything with tensorflow. I believe Nuitka's output detects its presence and warns that `--plugin-enable=tensorflow` needs to be passed as an argument. Are you passing that arg when building?

**Comment by Josh596** [comment]
This is what I use to build @nickjbenson 
python -m nuitka --standalone  --mingw64 --windows-icon-from-ico=icons/tools-icon.ico --windows-company-name=company_name --windows-product-name=product_name --windows-product-version=1.1.0 --windows-disable-console --plugin-enable=pyside6 --plugin-enable=numpy --plugin-enable=pkg-resources --plugin-enable=torch --plugin-enable=tensorflow --plugin-enable=pylint-warnings --assume-yes-for-download --run  --windows-force-stderr-spec=%PROGRAM%.err.txt launch_app.py

**Comment by nickjbenson** [comment]
Sorry, I'm not sure what your issue could be. The stdout from your build might be helpful for diagnosing if there's somewhere tensorflow is not being detected or properly handled.

Fwiw, with Tensorflow 2.5.0, I don't see `tensorflow.compat` as a module. Does your code run on its own, before compiling via Nuitka? It's possible you need a different version of Tensorflow, but I can't speak to Nuitka's compatibility with older versions.

**Comment by kayhayen** [comment]
Latest Torch is supposed to work with the plugin activated on 0.8.1
