### ISSUE TITLE
importing h5py not work

### ISSUE THREAD

**Issue by ybs3910** [Nuitka/Nuitka#1169]
CentOS 7.6.1810
Python 3.6.3
Nuitka 0.6.16.2
h5py 2.5.0

My project that uses h5py is not executable with below error.
`
ModuleNotFoundError: No module named 'h5py.defs'
`

So, I wrote a simple code that uses h5py.

```
import h5py
print("A")
```

I compiled this code with below command.

> python -m nuitka --follow-imports --plugin-enable=numpy --standalone test.py

It looks successful.
```
Nuitka-Options:INFO: Used command line options: --follow-imports --plugin-enable=numpy --standalone test.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16.2' on Python '3.6' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bit_generator,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.six,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy._lib' added 'scipy._lib.messagestream'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bit_generator,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.mtrand'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: The provided gcc is too old, switching to g++ instead.
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka-Plugins:INFO: numpy: Copied 2 files from 'numpy' installation.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.6.3.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.6.3.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'orig-prefix.txt' due to package data for 'site'.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist/test'.
```

But this is not executable.

> test.dist/test

```
Traceback (most recent call last):
  File "/run/build/test.dist/test.py", line 1, in <module>
  File "/run/build/test.dist/h5py/__init__.py", line 23, in <module h5py>
  File "h5py/h5r.pxd", line 21, in init h5py._conv
  File "h5py/_objects.pxd", line 12, in init h5py.h5r
  File "h5py/_objects.pyx", line 1, in init h5py._objects
ModuleNotFoundError: No module named 'h5py.defs'
```

What am I missing?

**Comment by kayhayen** [comment]
On factory branch there is now support for h5py, make sure to use `--enable-plugin=anti-bloat` as I added configuration to avoid `h5py.tests` to be included, which includes `pytest`, which... https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now on the develop branch and will be part of the next release.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
