### ISSUE TITLE
Onefile raise FileNotFoundError on Python 3.9/3.6

### ISSUE THREAD

**Issue by Ricky-Hao** [Nuitka/Nuitka#1170]
## Code
```python
import sys

if __name__ == '__main__':
    print(sys.argv)
```

## Command Line
`python -m nuitka --onefile main.py`

## Output
```
(venv) root@c1b16b997b1b:~/test# python -m nuitka --onefile main.py
Nuitka-Options:INFO: Used command line options: --onefile main.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16.2' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 11
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Traceback (most recent call last):
  File "/root/test/venv/lib/python3.9/site-packages/nuitka/__main__.py", line 187, in <module>
    main()
  File "/root/test/venv/lib/python3.9/site-packages/nuitka/__main__.py", line 173, in main
    MainControl.main()
  File "/root/test/venv/lib/python3.9/site-packages/nuitka/MainControl.py", line 786, in main
    packDistFolderToOnefile(dist_dir, binary_filename)
  File "/root/test/venv/lib/python3.9/site-packages/nuitka/freezer/Onefile.py", line 70, in packDistFolderToOnefile
    packDistFolderToOnefileLinux(onefile_output_filename, dist_dir, binary_filename)
  File "/root/test/venv/lib/python3.9/site-packages/nuitka/freezer/Onefile.py", line 198, in packDistFolderToOnefileLinux
    os.unlink(onefile_output_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'main.bin'
```
## pip freeze
(venv) root@c1b16b997b1b:~/test# pip freeze
Nuitka==0.6.16.2

## main.dist
```
(venv) root@c1b16b997b1b:~/test/main.dist# ls
AppRun              _codecs_jp.so    _curses_panel.so  _json.so             _posixsubprocess.so  _struct.so    grp.so           libXss.so.1         libfreetype.so.6     libsqlite3.so.0  main                      readline.so
_asyncio.so         _codecs_kr.so    _datetime.so      _lsprof.so           _queue.so            _tkinter.so   lib2to3          libbsd.so.0         libgdbm.so.6         libssl.so.1.1    main.appimage.stderr.txt  select.so
_bisect.so          _codecs_tw.so    _dbm.so           _lzma.so             _random.so           _uuid.so      libX11.so.6      libbz2.so.1.0       liblzma.so.5         libtcl8.6.so     main.appimage.stdout.txt  termios.so
_blake2.so          _contextvars.so  _decimal.so       _multibytecodec.so   _sha512.so           _zoneinfo.so  libXau.so.6      libcrypto.so.1.1    libncursesw.so.6     libtinfo.so.6    main.desktop              unicodedata.so
_bz2.so             _crypt.so        _elementtree.so   _multiprocessing.so  _socket.so           array.so      libXdmcp.so.6    libdb-5.3.so        libpanelw.so.6       libtk8.6.so      main.xpm                  zlib.so
_codecs_cn.so       _csv.so          _gdbm.so          _opcode.so           _sqlite3.so          audioop.so    libXext.so.6     libexpat.so.1       libpng16.so.16       libuuid.so.1     math.so
_codecs_hk.so       _ctypes.so       _hashlib.so       _pickle.so           _ssl.so              binascii.so   libXft.so.2      libffi.so.6         libpython3.9.so.1.0  libxcb.so.1      mmap.so
_codecs_iso2022.so  _curses.so       _heapq.so         _posixshmem.so       _statistics.so       fcntl.so      libXrender.so.1  libfontconfig.so.1  libreadline.so.7     libz.so.1        pyexpat.so
```
There is not `main.bin` in `main.dist`.

**Comment by charterchap** [comment]
Are you on at VM shared folder or network drive? I get this problem unless I copy my code to the local file system first

**Comment by Ricky-Hao** [comment]
> Are you on a VM shared folder or network drive? I get this problem unless I copy my code to the local file system first

No, first I try in docker with python 3.9 and got the problem. Then try it on CentOS 7(VPS) with local file system and Python 3.6,  got the problem too.

Test on RaspberryPi 4 ArchLinux
```
(venv)  ricky@rpi4  ~/temp/nuitka  python -m nuitka --onefile main.py --linux-onefile-icon=1
Nuitka-Options:INFO: Used command line options: --onefile main.py --linux-onefile-icon=1
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16.2' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.                                                                                                                                                                                                                                                                         
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                                                                                                                                                                                                                        
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                                                                                                                                                                                                                             
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.                                                                                                                                                                                                                                                               
Nuitka-Scons:INFO: Running gcc -o static_src/CompiledCodeHelpers.o -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D_NUITKA_STANDALONE -D_NUITKA_ONEFILE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=164 -D_NUITKA_EXE -I/usr/include/python3.9 -I. -I/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/build/include -I/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/build/static_src static_src/CompiledCodeHelpers.c took 65.85 seconds                                                                                                                      
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.                                                                                                                                                                                                                                
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka will make use of AppImage (https://appimage.org/) tool
to combine Nuitka dist folder to onefile binary.

Is it OK to download and put it in '/home/ricky/.local/share/Nuitka/appimagetool-aarch64.AppImage/aarch64/12'.

No installer needed, cached, one time question.

Proceed and download? [Yes]/No 
Yes
Nuitka:INFO: Downloading 'https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-aarch64.AppImage'.
Traceback (most recent call last):
  File "/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/__main__.py", line 187, in <module>
    main()
  File "/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/__main__.py", line 173, in main
    MainControl.main()
  File "/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/MainControl.py", line 786, in main
    packDistFolderToOnefile(dist_dir, binary_filename)
  File "/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/freezer/Onefile.py", line 70, in packDistFolderToOnefile
    packDistFolderToOnefileLinux(onefile_output_filename, dist_dir, binary_filename)
  File "/home/ricky/temp/nuitka/venv/lib/python3.9/site-packages/nuitka/freezer/Onefile.py", line 198, in packDistFolderToOnefileLinux
    os.unlink(onefile_output_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'main.bin'
```

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
