### ISSUE TITLE
Gevent plugin not working because of missing .so file

### ISSUE THREAD

**Issue by Ricky-Hao** [Nuitka/Nuitka#1175]
## Code
```python
from gevent import monkey
monkey.patch_all()

import sys
from gevent.pool import Pool

if __name__ == '__main__':
    pool = Pool(size=2)
    print(sys.argv)
```

## Error
```python
(venv) root@c1b16b997b1b:~/test/main.dist# ./main
Traceback (most recent call last):
  File "/root/test/main.dist/main.py", line 1, in <module>
  File "/root/test/main.dist/gevent/__init__.py", line 86, in <module gevent>
  File "/root/test/main.dist/gevent/_hub_local.py", line 101, in <module gevent._hub_local>
  File "/root/test/main.dist/gevent/_util.py", line 148, in import_c_accel
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'
```

Found a relate issue: https://github.com/gevent/gevent/issues/1468
Maybe the problem is cause by missing some `.so` file?

```python
(venv) root@c1b16b997b1b:~/test# python -v -c 'import gevent' 2>&1 | grep hub_local
# /root/test/venv/lib/python3.9/site-packages/gevent/__pycache__/_hub_local.cpython-39.pyc matches /root/test/venv/lib/python3.9/site-packages/gevent/_hub_local.py
# code object from '/root/test/venv/lib/python3.9/site-packages/gevent/__pycache__/_hub_local.cpython-39.pyc'
# extension module 'gevent._gevent_c_hub_local' loaded from '/root/test/venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-x86_64-linux-gnu.so'
# extension module 'gevent._gevent_c_hub_local' executed from '/root/test/venv/lib/python3.9/site-packages/gevent/_gevent_c_hub_local.cpython-39-x86_64-linux-gnu.so'
import 'gevent._gevent_c_hub_local' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7f6889f3efa0>
import 'gevent._hub_local' # <_frozen_importlib_external.SourceFileLoader object at 0x7f688a3b5130>
# cleanup[2] removing gevent._gevent_c_hub_local
# cleanup[2] removing gevent._hub_local
# destroy gevent._hub_local
# cleanup[3] wiping gevent._gevent_c_hub_local
```
`gevent` need `site-packages/gevent/_gevent_c_hub_local.cpython-39-x86_64-linux-gnu.so` to run.
But it can't be included by `--plugin-enable=gevent` or `--include-package-data=gevent`.

## Build Log
```
(venv) root@c1b16b997b1b:~/test# python -m nuitka --standalone --plugin-enable=gevent --plugin-enable=pylint-warnings main.py
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=gevent --plugin-enable=pylint-warnings main.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.15.3' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.pool' added 'gevent._imap'.
Nuitka-Plugins:INFO: gevent: Greenlet tree tracking switched off
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent._ffi' added 'gevent._ffi.loop,gevent._ffi.callback,gevent._ffi.watcher'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.libuv' added 'gevent._interfaces,gevent._ffi,gevent._ffi.loop,gevent._ffi.callback,gevent._ffi.watcher,gevent.libuv.loop,gevent.libuv._corecffi,gevent.libuv.watcher'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.libuv.loop' added 'gevent.libuv._corecffi,gevent._interfaces'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent._semaphore' added 'gevent._abstract_linkable'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.greenlet' added 'gevent._hub_local'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.hub' added 'gevent._hub_primitives,gevent._greenlet_primitives,gevent._hub_local,gevent._waiter,gevent._util,gevent._ident,gevent.exceptions'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.monkey' added 'gevent.builtins,gevent.time,gevent.local,gevent.ssl,gevent.events'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent' added 'gevent._config,gevent.core,gevent.resolver_thread,gevent.resolver_ares,gevent.socket,gevent.threadpool,gevent.thread,gevent.threading,gevent.select,gevent.hub,gevent._hub_primitives,gevent._greenlet_primitives,gevent._hub_local,gevent._waiter,gevent._util,gevent._ident,gevent.exceptions,gevent.greenlet,gevent.local,gevent.event,gevent.queue,gevent.resolver,gevent.resolver.blocking,gevent.resolver.cares,gevent.resolver.thread,gevent.subprocess,gevent.libev,gevent.libev.corecext,gevent.libev.corecffi,gevent.libev.watcher'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.libev' added 'gevent.libev.corecext,gevent.libev.corecffi,gevent.libev.watcher'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'gevent.resolver' added 'gevent.resolver.blocking,gevent.resolver.cares,gevent.resolver.thread'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 110 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 110
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.dist/main'.
```

## pip freeze
```
(venv) root@c1b16b997b1b:~/test# pip freeze
gevent==21.1.2
greenlet==1.1.0
Nuitka==0.6.15.3
zope.event==4.5.0
zope.interface==5.4.0
```

**Comment by Geographs** [comment]
I also have this problem on Windows using Nuitka 0.6.16.3.

**Comment by Geographs** [comment]
I was able to solve this problem by:
1. Copying and pasting the `gevent` folder (from site-packages) into the `main.dist` folder
2. Running `main.exe`
3. Attempting to delete everything in the `gevent` folder that was just pasted.
4. Pressing skip for all the files that are being used by `main.exe`

**Comment by kayhayen** [comment]
This should be fixed on develop now.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
