### ISSUE TITLE
Issue with networkx module: Nuitka doesn't support __defaults__ size changes

### ISSUE THREAD

**Issue by theExplodeGuy** [Nuitka/Nuitka#1177]
Hello, I am trying to create an application that includes the networkx python3 module. I have ran into the issue described in the title. I am not very familiar with C++ and Nuitka's inner workings, so I would like to ask for more information about where this issue might be, and whether I could do something about this to help fix it. Here is a minimum reproducible example:

```
purple@NetworkGateway:/tmp$ mkdir networkxExample
purple@NetworkGateway:/tmp$ cd networkxExample/
purple@NetworkGateway:/tmp/networkxExample$ python3.9 -m venv nxenv
purple@NetworkGateway:/tmp/networkxExample$ cd nxenv/
bin/     include/ lib/     lib64/   share/   
purple@NetworkGateway:/tmp/networkxExample$ cd nxenv/bin/
purple@NetworkGateway:/tmp/networkxExample/nxenv/bin$ source activate
(nxenv) purple@NetworkGateway:/tmp/networkxExample/nxenv/bin$ cd ..
(nxenv) purple@NetworkGateway:/tmp/networkxExample/nxenv$ cd ..
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ vim test.py
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ which python
/tmp/networkxExample/nxenv/bin/python
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ python -m pip install networkx
Collecting networkx
  Using cached networkx-2.6.2-py3-none-any.whl (1.9 MB)
Installing collected packages: networkx
Successfully installed networkx-2.6.2
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ python -m pip install nuitka
Collecting nuitka
  Using cached Nuitka-0.6.16.2.tar.gz (3.0 MB)
Building wheels for collected packages: nuitka
  Building wheel for nuitka (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/networkxExample/nxenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6hwa2dwg/nuitka/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6hwa2dwg/nuitka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b1begngf
       cwd: /tmp/pip-install-6hwa2dwg/nuitka/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for nuitka
  Running setup.py clean for nuitka
Failed to build nuitka
Installing collected packages: nuitka
    Running setup.py install for nuitka ... done
Successfully installed nuitka-0.6.16.2
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ python -m nuitka --plugin-enable=numpy --onefile test.py
Nuitka-Options:INFO: Used command line options: --plugin-enable=numpy --onefile test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16.2' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                                                
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.                                                                          
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                               
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 288 C files using ccache.                                                                                      
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 287
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Postprocessing:INFO: Completed onefile creation.
Nuitka:INFO: Keeping dist folder 'test.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.bin'.
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ ./test.bin 
Traceback (most recent call last):
  File "/tmp/.mount_test.bpOQH5g/test.py", line 1, in <module>
    import networkx
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/.mount_test.bpOQH5g/networkx/__init__.py", line 57, in <module networkx>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/.mount_test.bpOQH5g/networkx/utils/__init__.py", line 3, in <module networkx.utils>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/.mount_test.bpOQH5g/networkx/utils/random_sequence.py", line 25, in <module networkx.utils.random_sequence>
  File "/tmp/.mount_test.bpOQH5g/networkx/utils/decorators.py", line 800, in __call__
TypeError: Nuitka doesn't support __defaults__ size changes
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(nxenv) purple@NetworkGateway:/tmp/networkxExample$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ uname -a
Linux NetworkGateway 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ python --version
Python 3.9.5
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ python -m pip freeze
networkx==2.6.2
Nuitka==0.6.16.2
(nxenv) purple@NetworkGateway:/tmp/networkxExample$ cat test.py 
import networkx

g = networkx.DiGraph()
print('hello')
```
Also reference this issue: https://github.com/Nuitka/Nuitka/issues/522
    Under Test failures: mock, with graphviz, shows the same issue.

**Comment by kayhayen** [comment]
It seems to try to do a JIT for call arguments. Nice idea, absolutely no way this could be done in a compatible fashion for Nuitka, unless you do not compile the decorated code, which I assume is the performance relevant one.

So I have to declare this as unsupported. For commercial pay I could consider getting the mechamism redone in Nuitka, so get in touch with me if you have the money to do it: https://nuitka.net/pages/commercial.html but otherwise, I don't see this working.
