### ISSUE TITLE
Error loading cudnn64_7.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by JianJingGao** [Nuitka/Nuitka#1198]
0.6.16.4
Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Executable: D:\Program Files (x86)\anaconda3\envs\yolox\python.exe
OS: Windows
Arch: x86_64
 
---------------------------------------------------------------------------------------------------------
(yolox) D:\work\demo\YOLOX-main\tools\out-1\demo.dist>demo.exe
Traceback (most recent call last):
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 19, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\torch\lib\cudnn64_7.dll" or one of its dependencies.
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
Traceback (most recent call last):
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\demo.py", line 597, in <module>
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\context.py", line 56, in Manager
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\managers.py", line 567, in start
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 250, in recv
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
KeyboardInterrupt
  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes
KeyboardInterrupt  File "D:\work\demo\YOLOX-~1\tools\out-1\DEMO~1.DIS\multiprocessing\connection.py", line 306, in _recv_bytes

 
something print caffe2_detectron_ops_gpu.dll" or one of its dependencies  error message

**Comment by kayhayen** [comment]
No minimal reproducer, no support.
