### ISSUE TITLE
Broken numpy on develop Nuitka branch

### ISSUE THREAD

**Issue by kosmonavvt** [Nuitka/Nuitka#1201]
Nuitka, develop branch, installation from source (python3 setup.py install)

```
$ nuitka3 --version
0.6.17rc4
Python: 3.9.7 (default, Sep  4 2021, 14:37:05) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

```
$ python3 -m pip freeze
numpy==1.21.2
packaging==21.0
```

Everything is working good on Nuitka 0.6.16.4 (from pypi and installed from source)
problem only on version 0.6.17rc4

Reproduce:

```
$ cat test.py
#!/usr/bin/env python3
import numpy
print("Hello numpy world!")
```

```
Nuitka-Options:INFO: Used command line options: --follow-imports test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17rc4' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.
Problem with statement at /usr/lib/python3.9/site-packages/numpy/distutils/core.py:8:
->     from setuptools.command import easy_install

Problem with statement at /usr/lib/python3.9/site-packages/numpy/distutils/core.py:4:
-> if 'setuptools' in sys.modules:

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '/usr/lib/python3.9/site-packages/numpy/distutils/core.py', 'module_name': <ModuleName numpy.distutils.core>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/__main__.py", line 187, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/__main__.py", line 173, in main
    MainControl.main()
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/MainControl.py", line 722, in main
    main_module = _createNodeTree(filename=filename)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/MainControl.py", line 175, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/Optimization.py", line 347, in optimize
    finished = makeOptimizationPass()
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/Optimization.py", line 310, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/Optimization.py", line 205, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/Optimization.py", line 103, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ModuleNodes.py", line 524, in computeModule
    result = module_body.computeStatementsSequence(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/TraceCollections.py", line 609, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ConditionalNodes.py", line 569, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/TraceCollections.py", line 903, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/TraceCollections.py", line 609, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/TraceCollections.py", line 590, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ExpressionBases.py", line 1182, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/optimizations/TraceCollections.py", line 590, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ExpressionBases.py", line 1131, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ImportNodes.py", line 602, in computeExpression
    self._attemptRecursion(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ImportNodes.py", line 507, in _attemptRecursion
    sub_imported_module = self._consider(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/nodes/ImportNodes.py", line 407, in _consider
    imported_module = recurseTo(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/importing/Recursion.py", line 65, in recurseTo
    module, added_flag = _recurseTo(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/importing/Recursion.py", line 37, in _recurseTo
    module, is_added = Building.buildModule(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/tree/Building.py", line 1293, in buildModule
    source_code = readSourceCodeFromFilename(
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/tree/SourceReading.py", line 169, in readSourceCodeFromFilename
    source_code_modified = Plugins.onModuleSourceCode(module_name, source_code)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/plugins/Plugins.py", line 593, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(module_name, source_code)
  File "/usr/lib/python3.9/site-packages/Nuitka-0.6.17rc4-py3.9.egg/nuitka/plugins/standard/PkgResourcesPlugin.py", line 86, in onModuleSourceCode
    self.pkg_resources.require(match[1])
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 728, in resolve
    requirements = list(requirements)[::-1]
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'%(name)s'": Expected W:(abcd...)
```

**Comment by kayhayen** [comment]
As a workaround, enable the anti-bloat plugin, which avoids inclusion of `numpy.distutils` or should. This plugin is supposed to become enabled by default, but isn't yet. It reduces compile time by a lot avoiding pytest and its many dependencies with numpy, however, this is a bug of the PkgResourcesPlugin, which apparently fails to properly extract a requirement definition.

**Comment by kayhayen** [comment]
There is also a fix for this on the factory branch, even if of course this is not an important issue when anti-bloat is available.

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
I have also made a nicer error exit, in case the plugin encounters an unexpected exception, that part is going into the next release, but the exception, I am putting it into a hotfix, although I am not entirely sure that stable is really affected, but it can still be done as it saves the worries.

**Comment by kosmonavvt** [comment]
> There is also a fix for this on the factory branch, even if of course this is not an important issue when anti-bloat is available.

Thanks, working good on factory branch, no error.

**Comment by kayhayen** [comment]
Also part of the hotfix and pre-release I made.
