### ISSUE TITLE
pyside6: Copying QtWebEngine components, FileNotFoundError

### ISSUE THREAD

**Issue by rainyl** [Nuitka/Nuitka#1237]
* Nuitka version： 0.6.17.2 on Windows x64

* How did you install Nuitka and Python: using pip, virtualenvironment

* Nuitka options used: nuitka --mingw64 --standalone --output-dir=build --show-progress --show-memory --plugin-enable=pylint-warnings --plugin-enable=pyside6 --windows-icon-from-ico=resources/logo.png src/webenginetest.py

The following is the main error information:

Nuitka-Plugins:INFO: pyside6: Copying OpenSSL DLLs to 'build1\\webenginetest.dist'.
Nuitka-Plugins:INFO: pyside6: Copying QtWebEngine components
Traceback (most recent call last):
  File "path\to\venv\venvwebtest\lib\site-packages\nuitka\__main__.py", line 187, in <module>
    main()
  File "path\to\venv\venvwebtest\lib\site-packages\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "path\to\venv\venvwebtest\lib\site-packages\nuitka\MainControl.py", line 776, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "path\to\venv\venvwebtest\lib\site-packages\nuitka\plugins\Plugins.py", line 358, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "path\to\venv\venvwebtest\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 683, in considerExtraDlls
    for f in os.listdir(bin_dir):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'path\to\venv/venvwebtest/lib/site-packages/PySide6\\bin'

Here is the test example:

```
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'webenginetest.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenuBar, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.webEngineView = QWebEngineView(self.centralwidget)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(180, 60, 300, 200))
        self.webEngineView.setUrl(QUrl(u"about:blank"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
    # retranslateUi


class WebEngineTest(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None) -> None:
        super(WebEngineTest, self).__init__(parent)
        self.setupUi(self)



if __name__ == "__main__":
    import sys
    app = QApplication()
    mainwindow = WebEngineTest()
    mainwindow.show()
    sys.exit(app.exec_())
```

**Comment by kayhayen** [comment]
You are correct. Installing pyqt5 via pip didn't reveal any reason to me, why this was done like this so far. I will risk breaking Qt5 which is badly supported anyway and hotfix this for PySide to work. There is no exe at all on these.

I am also noticing, that translations are copied too, not sure if for a good reason at all, but I will only enhance it such that it makes sure it's the correct one at all.

**Comment by rainyl** [comment]
> 
> 
> I pushed a fix to factory, please try it out, and while at it, can you check if the translations are working for you? I am a bit suspicious of the target folder. You might have to move it out of "Qt" subfolder, let me know if that is the case. Alternatively if you could update your example to display something that is translated would be really nice.
> 
> https://nuitka.net/doc/factory.html

I have tried the 0.6.18rc3 version, and it worked fine. i created a new venv and just installed the pyside6 and nuitka(0.6.18rc3).  there was no "Qt" folder in the "PySide6", after executing the exe file it said can't find translations locales, but translations i made by ".qm" file showed normally. I copied the translations folder from other project and it disappeared. I am new to Qt and know little about it's "Qt/translations/qtwebengine_locales"(such as en-US.pak), but in my condition, without them, the app works normally.

here is the example with translations test.
```
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect, QTranslator, Slot,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.webEngineView = QWebEngineView(self.centralwidget)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(60, 10, 581, 431))
        self.webEngineView.setUrl(QUrl(u"about:blank"))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(270, 470, 93, 28))
        self.pushButton.setFlat(False)
        self.btnRetranslate = QPushButton(self.centralwidget)
        self.btnRetranslate.setObjectName(u"btnRetranslate")
        self.btnRetranslate.setGeometry(QRect(450, 470, 93, 28))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"testButton", None))
        self.btnRetranslate.setText(QCoreApplication.translate("MainWindow", u"retranslate", None))
    # retranslateUi

class WebEngineTest(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None) -> None:
        super(WebEngineTest, self).__init__(parent)
        self.setupUi(self)
        self.trans = QTranslator(self)
        self.btnRetranslate.clicked.connect(self.translate)

    @Slot()
    def translate(self):
        if self.trans.isEmpty() or self.trans.language() == "en_US":
            self.trans.load("webenginetest_CN.qm")
        else:
            self.trans.load("webenginetest_EN.qm")
        print("Change language to {}".format(self.trans.language()))
        QApplication.instance().installTranslator(self.trans)
        self.retranslateUi(self)


if __name__ == "__main__":
    import sys
    app = QApplication()
    mainwindow = WebEngineTest()
    mainwindow.show()
    sys.exit(app.exec_())

```

and the .qm files:
[webenginetestQM.zip](https://github.com/Nuitka/Nuitka/files/7334708/webenginetestQM.zip)

**Comment by kayhayen** [comment]
Thhis is currently on develop, and will be part of 0.6.18 release.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
