### ISSUE TITLE
Error in fetching data path with matplotlib in NumpyPlugin.py

### ISSUE THREAD

**Issue by DamienHallez** [Nuitka/Nuitka#1269]
Hello Team,

Compiling in standalone mode on a Raspberry Pi, I had this error:

Nuitka-Options:INFO: Recursing all is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: cannot import name '_get_data_path' from 'matplotlib' (/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py)
Problem with statement at plot_files.py:14:
-> import matplotlib

Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'plot_files.py', 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 209, in <module>
    main()
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 195, in main
    MainControl.main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 696, in main
    main_module = _createNodeTree(filename=filename)
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 154, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/Optimization.py", line 619, in optimize
    makeOptimizationPass()
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/Optimization.py", line 552, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/Optimization.py", line 191, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/Optimization.py", line 112, in optimizeCompiledPythonModule
    module.computeModule()
  File "/usr/lib/python3/dist-packages/nuitka/nodes/ModuleNodes.py", line 504, in computeModule
    result = module_body.computeStatementsSequence(
  File "/usr/lib/python3/dist-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/usr/lib/python3/dist-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/TraceCollections.py", line 520, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/usr/lib/python3/dist-packages/nuitka/nodes/AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/usr/lib/python3/dist-packages/nuitka/optimizations/TraceCollections.py", line 501, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/usr/lib/python3/dist-packages/nuitka/nodes/ExpressionBases.py", line 1098, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/usr/lib/python3/dist-packages/nuitka/nodes/ImportNodes.py", line 538, in computeExpression
    self._attemptRecursion(
  File "/usr/lib/python3/dist-packages/nuitka/nodes/ImportNodes.py", line 408, in _attemptRecursion
    imported_module = self._consider(
  File "/usr/lib/python3/dist-packages/nuitka/nodes/ImportNodes.py", line 337, in _consider
    imported_module, added_flag = recurseTo(
  File "/usr/lib/python3/dist-packages/nuitka/importing/Recursion.py", line 123, in recurseTo
    return _recurseTo(
  File "/usr/lib/python3/dist-packages/nuitka/importing/Recursion.py", line 108, in _recurseTo
    ImportCache.addImportedModule(module)
  File "/usr/lib/python3/dist-packages/nuitka/importing/ImportCache.py", line 48, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "/usr/lib/python3/dist-packages/nuitka/plugins/Plugins.py", line 316, in onModuleDiscovered
    plugin.onModuleDiscovered(module)
  File "/usr/lib/python3/dist-packages/nuitka/plugins/PluginBase.py", line 398, in onModuleDiscovered
    pre_code, reason = self.createPreModuleLoadCode(module)
  File "/usr/lib/python3/dist-packages/nuitka/plugins/standard/NumpyPlugin.py", line 429, in createPreModuleLoadCode
    or not self._getMatplotlibInfo().needs_matplotlibdata_env
  File "/usr/lib/python3/dist-packages/nuitka/plugins/standard/NumpyPlugin.py", line 237, in _getMatplotlibInfo
    feedback = Execution.check_output([sys.executable, "-c", cmd])
  File "/usr/lib/python3/dist-packages/nuitka/utils/Execution.py", line 157, in check_output
    raise subprocess.CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', '\\\nfrom __future__ import print_function\nfrom matplotlib import matplotlib_fname, get_backend, _get_data_path, __version__\nfrom inspect import getsource\nprint(repr(matplotlib_fname()))\nprint(repr(get_backend()))\nprint(repr(_get_data_path()))\nprint(repr(__version__))\nprint(repr("MATPLOTLIBDATA" in getsource(_get_data_path)))\n']' returned non-zero exit status 1.

Effectively, I don't know from which version of matplotlib it was, but now the the function to get data path is simply "get_data_path".

I have changed in the NumpyPlugin.py file, lines 227, 231, 233 and it works well!

# ----- nuitka version
$>  python3 -m nuitka --version
0.6.11.3
Python: 3.9.2 (default, Mar 12 2021, 04:06:34) 
Executable: /usr/bin/python3
OS: Linux
Arch: armv7l

Nuitka installed with pip3

# -----pip list
$> python -m pip freeze
aenum==3.1.3
appdirs==1.4.4
astroid==2.5.1
asttokens==2.0.4
beautifulsoup4==4.9.3
bluepy==1.3.0
certifi==2020.6.20
chardet==4.0.0
colorzero==1.1
cryptography==3.3.2
cupshelpers==1.0
cycler==0.11.0
dbus-python==1.2.16
decorator==4.4.2
distro==1.5.0
docutils==0.16
galternatives==1.0.8
gpiozero==1.6.2
html5lib==1.1
idna==2.10
isort==5.6.4
jedi==0.18.0
kiwisolver==1.3.2
lazy-object-proxy==0.0.0
logilab-common==1.8.1
lxml==4.6.3
Mako==1.1.3
MarkupSafe==1.1.1
matplotlib==3.4.3
mccabe==0.6.1
mypy==0.812
mypy-extensions==0.4.3
Nuitka==0.6.11.3
numpy==1.21.4
olefile==0.46
parso==0.8.1
Pillow==8.1.2
psutil==5.8.0
pycairo==1.16.2
pycups==2.0.1
Pygments==2.7.1
PyGObject==3.38.0
pylint==2.7.2
pyparsing==3.0.4
pyserial==3.5b0
pysmbc==1.0.23
python-apt==2.2.1
python-can==3.3.4
python-dateutil==2.8.2
python-prctl==1.7
PyVISA==1.11.3
PyVISA-py==0.5.2
pyxdg==0.27
requests==2.25.1
roman==2.0.0
RPi.GPIO==0.7.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
scikit-highs==0.5.1
scipy==1.7.2
SCons==4.0.1
Send2Trash==1.6.0b1
six==1.16.0
soupsieve==2.2.1
ssh-import-id==5.10
thonny==3.3.10
toml==0.10.1
typed-ast==1.4.2
typing-extensions==3.7.4.3
urllib3==1.26.5
webencodings==0.5.1
wrapt==1.12.1
xdg==5

Best

**Comment by kayhayen** [comment]
You didn't fill out the issue template, and probably followed no steps mentioned in there.

**Comment by DamienHallez** [comment]
Hello Kay, 


Thanks for your feedback. 


I don't know what happened but it was just to mention that there is a modification to do in ' NumpyPlugin.py ' about fetching data dir for matplolib. 
Effectively, the function to do it is now " get_path_data" and not "_get_path_data" anymore. 
So I replaced "_get_path_data" by"get_path_data" in lines 227, 231, 233 and it works well now. 


Regards 


Damien 
----- Mail original -----

De: "Kay Hayen" ***@***.***> 
À: "Nuitka/Nuitka" ***@***.***> 
Cc: "DamienHallez" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 10 Novembre 2021 14:08:16 
Objet: Re: [Nuitka/Nuitka] Error in fetching data path with matplotlib in NumpyPlugin.py (Issue #1269) 



You didn't fill out the issue template, and probably followed no steps mentioned in there. 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .
