### ISSUE TITLE
How to deal with modules loaded via manual file system scans and import calls in standalone mode?

### ISSUE THREAD

**Issue by mcfreis** [Nuitka/Nuitka#1278]
I have the following code which imports all modules from the current directory:

```
__all__ = [
    import_module("." + f.split('.py')[0], __package__)
    for f in os.listdir(os.path.dirname(__file__))
    if "__" not in f
]
```
 I added the files from the directory with a plugin over `getImplicitImports`. But the exe does not run and gives the following error:

```
Traceback (most recent call last):
  File "D:\path\to\app\meterlab2.pyw", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\path\to\app\xxxx\common\devices\types\__init__.py", line 6, in <module xxxx.common.devices.types>
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'D:\\path\\to\\app\\xxxx\\common\\devices\\types'
```

What are my options to solve this?

Regards

**Comment by kayhayen** [comment]
This code should be using `pkgutil.iter_modules` which is tremendously simper to use and more correct in all cases.
