### ISSUE TITLE
ModuleNotFoundError(s) with compiled executable - quarchpy

### ISSUE THREAD

**Issue by evolving-chrism** [Nuitka/Nuitka#1279]
Hello,

I have been getting a "ModuleNotFoundError" when trying to run a nuitka-compiled executable that imports the quarchpy library. 

I have attached a small example project .zip that demonstrates this issue.
This package contains three main scripts for testing:  build.sh, pytest.py, and funcs.py.
** If you run "python3 -m pytest", it will run and output successfully.
** However, when you run "./build.sh", it can compile pytest.py into pytest with nuitka, but running the resulting executable "./pytest" fails, as it inevitably returns a ModuleNotFoundError. 

I have been working with my support contact at Quarch in trying to resolve this issue. We have found that different combinations of using sudo and/or non-sudo [for the library install commands] affect the result, as each will affect the system path locally and/or at root level, thereby affecting how the python interpreter loads and links the modules to the runtime environment. Additionally, running the nuitka compilation command with or without sudo affects the result. We have performed extensive testing on this issue, and there are a number of other scripts we have used for further debugging, but I don't want to overload this initial submission, so I'd be glad to share those separately if needed.

I should also mention that I had a coworker who was able to produce a working executable for quarchpy back in April, but when running on his branch now, there is the same missing modules issue described above. This leads me to believe that at some point around early summer this year, the mainline branch of nuitka diverged in some functionality that interacts with quarchpy (and other libraries overriding __all__), no longer allowing the subpackage modules to be resolved appropriately from the top level.?

Environment:
 -- I am using Ubuntu 20.04. When I was on 18.04, the ModuleNotFoundErrors were more extensive with other packages, e.g. prettytable.
 -- I am using Python3.8.10. The Nuitka version is 0.6.17.7, and Quarchpy is 2.1.1. They are both installed with pip3.
 -- The nuitka compilation options used/attempted include --follow-imports, --standalone, and --onefile. Unfortunately, none of these options seem to be working as expected.
 
Please let me know if there is anything else I can share, including the more extensive build scripts we have tried, that may be helpful in resolving the module not found errors. Thank you very much.
[quarchpy_example.zip](https://github.com/Nuitka/Nuitka/files/7573361/quarchpy_example.zip)

**Comment by kayhayen** [comment]
Nuitka should inform you that these options imply another, so if you cannot get `--standalone` to work, it's over. The --onefile implies it and cannot be better, and `--follow-imports` is implied in `--standalone`.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
What a mess:

```
# Adds /serial to the path.
folder2add = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]) + "//connection_specific//serial")
if folder2add not in sys.path:
    sys.path.insert(0, folder2add)

# Adds /QIS to the path.
folder2add = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]) + "//connection_specific//QIS")
if folder2add not in sys.path:
    sys.path.insert(0, folder2add)

# Adds /usb_libs to the path.
folder2add = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]) + "//connection_specific//usb_libs")
if folder2add not in sys.path:
    sys.path.insert(0, folder2add)

# Adds /usb_libs to the path.
folder2add = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]) + "//config_files")
if folder2add not in sys.path:
    sys.path.insert(0, folder2add)
```

I never saw a worse way to do this before. By setting a `PYTHONPATH` before you compile, I assume this can be worked around.

**Comment by kayhayen** [comment]
Also, this is actually what the `--include-plugin-directory` was created for originally. It forces inclusion of modules in a folder in flat form and was designed for that kind of out of package namespace plugins. The only other time I came across this were mercurial plugins which was the last time I encounted a use case for that, 11 years ago. :)

**Comment by kayhayen** [comment]
If you want to be more specific, you can use `--include-plugin-files` as well, to e.g. only add the `debug.py`` (I assume it's ont the files) of theirs.

**Comment by evolving-chrism** [comment]
Hi KayHayen, thank you for your response.~~

I am curious about your comment regarding setting the PYTHONPATH before it gets compiled; what would be a better way for the top-level init script to handle it?
 --> I see a note on the Nuitka user manual that "If you don’t do any dynamic imports, simply setting your PYTHONPATH at compilation time is what you should do." Would you recommend, then, exporting the python path with something along the lines of: `export PYTHONPATH=$(python3 -c "import sys; import quarchpy; sys.path.remove(''); print(':'.join(sys.path))")`? Or would that be too contrived?

Also, is there a preferred/best practice for installing nuitka and/or external libraries with or without sudo, before compiling?

I am trying your advice with using the two flags you mentioned; 
  -- When I edit the compile command to be: "python3 -m nuitka pytest.py --follow-imports --include-plugin-directory=~/.local/lib/python3.8/site-packages/quarchpy --standalone", the build outputs: "Nuitka-Recursion:WARNING: Failed to recurse to directory '~/.local/lib/python3.8/site-packages/quarchpy'.", then continues to run into the "ModuleNotFoundError: No module named 'debug'".. Any ideas why?
  -- When I comment out the calls to debug, and change the import statement in funcs.py, I still get similar errors, but just missing different modules.

** I mainly just want to be able to use the quarchpy functions for scanDevices() and the constructor for quarchDevice(...). 
So I tried "python3 -m nuitka pytest.py --follow-imports --include-plugin-files=~/.local/lib/python3.8/site-packages/quarchpy/device/device.py,~/.local/lib/python3.8/site-packages/quarchpy/device/scanDevices.py --standalone", but it returned "Nuitka-Recursion:WARNING: Didn't match any files against pattern '~/.local/lib/python3.8/site-packages/quarchpy/device/device.py'.
Nuitka-Recursion:WARNING: Didn't match any files against pattern '~/.local/lib/python3.8/site-packages/quarchpy/device/scanDevices.py'." in the build output.

Am I doing something wrong, syntactically or otherwise?\
Please let me know what you think. And Happy Thanksgiving!

**Comment by kayhayen** [comment]
The problem is *in* the `quarchpy` package, it extends the `sys.path` and then makes imports with names that pull into this. You would have to emulate its effects. You might be able to see what they add, by printing `sys.path` after running it with Python, since they don't clean up. Alternatively you can go to https://nuitka.net/pages/commercial.html and for a priority customer, I would add something to Nuitka that does things just automatically.

**Comment by evolving-chrism** [comment]
Hi Kay Hayen, thank you for the info. 

I am considering paying for the priority customer option.
But currently, I am still trying to resolve this issue by my own means. 

It is strange to me that when I add the --show-modules flag, I can see in the output that all of the relevant quarchpy submodules are recursed to and included in the compilation. Yet at the end when I go to execute, it will say those very same modules cannot be found. Sometimes when I fiddle with it, it suggests there may be circular imports.

But more concerning than that is that I am now receiving a permissions error during compilation:
```
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
 
Traceback (most recent call last):                                                                                                                                               
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 142, in <module>
    main()
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 128, in main
    MainControl.main()
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 906, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 193, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/optimizations/Optimization.py", line 359, in optimizeModules
    demoteCompiledModuleToBytecode(module)
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/optimizations/BytecodeDemotion.py", line 92, in demoteCompiledModuleToBytecode
    writeImportedModulesNamesToCache(
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/Caching.py", line 93, in writeImportedModulesNamesToCache
    with openTextFile(_getCacheFilename(cache_name, "txt"), "w") as modules_cache_file:
  File "/home/chris/.local/lib/python3.8/site-packages/nuitka/utils/FileOperations.py", line 484, in openTextFile
    return open(filename, mode)  # pylint: disable=unspecified-encoding
PermissionError: [Errno 13] Permission denied: '/home/chris/.cache/Nuitka/module-cache/pkg_resources@30215ca4ade72b693e951effce1ac1c2@fa400efcd0ed88e44761481c15695601.txt'
```

I am using an older version of quarchpy, and I have tried numerous versions of nuitka. The above output is from the currently released 0.6.17.1.
Do you know why this is happening?

**Comment by kayhayen** [comment]
The `PermissionError` is more in the realms of your home directory setup being broken there.

**Comment by kayhayen** [comment]
For the trick mentioned, there is now support in the Yaml configuration, if anyone wants to pick this up, this would be easy now. However, I am not convinced of the commercial relevance, so i am not doing it myself immediately.

The relevant docs are at: https://nuitka.net/doc/nuitka-package-config.html#id12 and I believe the same thing or something similar as done for `tkinterweb` might apply.
