### ISSUE TITLE
Support for PyOpenGL

### ISSUE THREAD

**Issue by Rayterex** [Nuitka/Nuitka#1282]
I'm unable to compile project that uses PyOpenGL

Error message:
```
Traceback (most recent call last):
  File "<string>", line 3, in _wrapped_function_initializeGL_21
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\pg_ui\pg_node_editor\pg_view_3d.py", line 67, in initializeGL
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\pg_gl_util\pg_texture.py", line 45, in create
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\latebind.py", line 45, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\wrapper.py", line 656, in wrapperCall
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\wrapper.py", line 459, in calculate_cArgs
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\converters.py", line 251, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\converters.py", line 196, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\arrays\arraydatatype.py", line 172, in zeros
  File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\OpenGL\arrays\arraydatatype.py", line 79, in get_output_handler
RuntimeError: ('Unable to find any output handler at all (not even ctypes/numpy ones!)', 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x0000016B6571DD40>', (1, <object object at 0x0000016B63CCAE40>), 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x0000016B657F3A80>)
```
On the:
```
File "C:\Users\neman\AppData\Local\Temp\ONC9F3~1\pg_gl_util\pg_texture.py", line 45, in create
```
I'm calling OpenGL function for the first time:
```
GL.glGenTextures(1)
```

I've tried to follow [#86](https://github.com/Nuitka/Nuitka/issues/86) but it is a bit confusing. Anyway, `--include-module=OpenGL.platform.win32` doesn't seem to help

Python version: `Python 3.8.11`
Nuitka version:
```
0.6.17.7
Commercial: None
Python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\neman\Anaconda3\envs\trivial\python.exe
OS: Windows
Arch: x86_64
```

**Comment by kayhayen** [comment]
Call me lazy or stupid, but I really would appreciate an example code, where nothing needs to be guessed or filled in. I am not an expert on all Python packages.

**Comment by Rayterex** [comment]
Sorry, no problem. Here is the minimal example. I ripped out [answer from here](https://stackoverflow.com/questions/44781223/minimalist-pyopengl-example-in-pyqt5-application)

Here it is:
```
import numpy as np
from OpenGL import GL
from PySide2.QtWidgets import QOpenGLWidget, QApplication


class OpenGLWidget(QOpenGLWidget):

    def initializeGL(self):
        vertices = np.array([0.0, 1.0, -1.0, -1.0, 1.0, -1.0], dtype=np.float32)

        bufferId = GL.glGenBuffers(1)
        GL.glBindBuffer(GL.GL_ARRAY_BUFFER, bufferId)
        GL.glBufferData(GL.GL_ARRAY_BUFFER, vertices.nbytes, vertices, GL.GL_STATIC_DRAW)

        GL.glEnableVertexAttribArray(0)
        GL.glVertexAttribPointer(0, 2, GL.GL_FLOAT, GL.GL_FALSE, 0, None)

    def paintGL(self):
        GL.glDrawArrays(GL.GL_TRIANGLES, 0, 3)


app = QApplication([])
widget = OpenGLWidget()
widget.show()
app.exec_()
```

I run Nuitka like this: `nuitka --jobs 8 --standalone --onefile --follow-imports --enable-plugin=pyside2 --enable-plugin=numpy test.py`

and error message is kinda similar:
```
Traceback (most recent call last):
  File "<string>", line 3, in _wrapped_function_initializeGL_1
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\test_delete_me.py", line 11, in initializeGL
    bufferId = GL.glGenBuffers(1)
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\latebind.py", line 45, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\wrapper.py", line 656, in wrapperCall
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\wrapper.py", line 459, in calculate_cArgs
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\converters.py", line 251, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\converters.py", line 196, in __call__
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\arrays\arraydatatype.py", line 172, in zeros
  File "C:\Users\neman\AppData\Local\Temp\ONE46F~1\OpenGL\arrays\arraydatatype.py", line 79, in get_output_handler
RuntimeError: ('Unable to find any output handler at all (not even ctypes/numpy ones!)', 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x0000019B0E7DF2C0>', (1, <object object at 0x0000019B7FDEABF0>), 1, <OpenGL.platform.baseplatform.glGenBuffers object at 0x0000019B0E7E8FC0>)
```

Hope this help.

**Comment by kayhayen** [comment]
With Nuitka, I traced this:

```
importByName OpenGL.platform.win32.Win32Platform
importByName OpenGL.arrays.numpymodule.NumpyHandler
importByName OpenGL.arrays.ctypesarrays.CtypesArrayHandler
```

And with pure CPython:

```
importByName OpenGL.platform.win32.Win32Platform
importByName OpenGL.arrays.numpymodule.NumpyHandler
importByName OpenGL.arrays.numpymodule.NumpyHandler
importByName OpenGL.arrays.nones.NoneHandler
importByName OpenGL.arrays.ctypespointers.CtypesPointerHandler
```

The difference is strange, we probably are not detecting all kinds of plugins. The platform plugin is detected just fine of course.

**Comment by Rayterex** [comment]
I've tried to compile example that doesn't use Qt (PySide2), but only PyOpenGL (glfw is used to create window) and generated .exe file does work. Qt also uses OpenGL so maybe Nuitka can't follow who owns OpenGL context, Qt or PyOpenGL. This is my assumption.

Here is the working example, [taken from here](https://github.com/totex/PyOpenGL_tutorials/blob/master/video_06_quad.py) 
I've compiled it with Nuitka like this:
```
nuitka --jobs 8 --standalone --onefile --follow-imports --enable-plugin=numpy --enable-plugin=glfw test.py
```
However, whenever I test examples that use both Qt (PySide) and PyOpenGL .exe file return errors.
Hope this helps.

**Comment by kayhayen** [comment]
So it came down to only needing this, which is on the factory branch.

```
OpenGL.arrays.arraydatatype:
  depends:
    - "OpenGL.arrays.numpymodule"
    - "OpenGL.arrays.ctypesarrays"
    - "OpenGL.arrays.ctypespointers"
    - "OpenGL.arrays.nones"
```

I didn't observe any problems with Qt, but the point with `glfw` is good. That plugin deals with OpenGL specifics like this:

```
    def getImplicitImports(self, module):
        if module.getFullName() == "OpenGL":
            opengl_infos = self.queryRuntimeInformationSingle(
                setup_codes="import OpenGL.plugins",
                value="[(f.name, f.import_path) for f in OpenGL.plugins.FormatHandler.all()]",
            )

            # TODO: Filter by name.
            for _name, import_path in opengl_infos:
                yield ModuleName(import_path).getPackageName()
```

It's probably time to create an OpenGL plugin, just enabling `glfw` and then using Qt will also work I suppose. I was more clever when I did that I see now.

**Comment by kayhayen** [comment]
I am enabling that plugin now always, it has no adverse effects unless `glfw` is actually used, so we can do that, and it's what I want to happen anyway. I hope for that to solve your issue automatically.

**Comment by kayhayen** [comment]
For the record, this is what I added to the example:

```
# nuitka-project: --standalone
# nuitka-project: --enable-plugin=anti-bloat
# nuitka-project: --noinclude-default-mode=error
# nuitka-project: --enable-plugin=numpy
# nuitka-project: --enable-plugin=pyside2
```

Anti bloat makes a huge difference again.

**Comment by Rayterex** [comment]
Yeah, `--enable-plugin=glfw` solves the problem. Hope I will make some bucks from my project so I can support You. You are doing a God's work here!

**Comment by kayhayen** [comment]
On factory the plugin `glfw` is now enabled by default, and I also moved the OpenGL platform plugin handling to there, so this should be all good now. https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
