### ISSUE TITLE
nuitka seems to do something for commented-out lines

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1293]
This bug has brought me to the brink of insanity. Check out the attached Python project. It's essientially empty, only the scaffolfing and two empty files are there (`__about__.py` and `__init__.py`).
[foobar.zip](https://github.com/Nuitka/Nuitka/files/7629103/foobar.zip)
```
.
├── justfile
├── pyproject.toml
├── setup.cfg
├── setup.py
├── src
│   └── foobar
│       ├── __about__.py
│       └── __init__.py
└── tox.ini

2 directories, 7 files
```

When running
```bash
tox
```
on it, I'm getting the error 
```
Processing ./.tox/.tmp/package/1/foobar-0.0.1.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: foobar
  Building wheel for foobar (pyproject.toml): started
  Building wheel for foobar (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/n/l/.tox/py3/bin/python /tmp/n/l/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpyfhz50ji
       cwd: /tmp/pip-req-build-xbrdinpu
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/foobar
  copying src/foobar/__about__.py -> build/lib/foobar
  copying src/foobar/__init__.py -> build/lib/foobar
  Building: PyPackage(module_name=foobar, related_packages=['foobar']) with ['/tmp/n/l/.tox/py3/bin/python', '-m', 'nuitka', '--module', '--plugin-enable=pylint-warnings', '--output-dir=/tmp/pip-req-build-xbrdinpu/build/lib', '--nofollow-import-to=*.tests', '--show-modules', '--remove-output', '--include-package=foobar', '/tmp/pip-req-build-xbrdinpu/build/lib/foobar']
  Nuitka-Options:INFO: Used command line options: --module --plugin-enable=pylint-warnings --output-dir=/tmp/pip-req-build-xbrdinpu/build/lib --nofollow-import-to=*.tests --show-modules --remove-output --include-package=foobar /tmp/pip-req-build-xbrdinpu/build/lib/foobar
  Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17.7' on Python '3.9' commercial None.
  Nuitka-Recursion:INFO: Checking top level plug-in path /tmp/pip-req-build-xbrdinpu/build/lib/foobar None
  Nuitka-Recursion:INFO: Checking detail plug-in path '/tmp/pip-req-build-xbrdinpu/build/lib/foobar' 'None':
  Nuitka-Recursion:INFO: Included 'foobar' as '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': '/tmp/pip-req-build-xbrdinpu/build/lib/foobar/__init__.py', 'module_name': <ModuleName foobar>, 'code_flags': ''}>'.
  Nuitka-Recursion:INFO: Package directory '/tmp/pip-req-build-xbrdinpu/build/lib/foobar'.
  Nuitka-Recursion:INFO: Checking detail plug-in path '/tmp/pip-req-build-xbrdinpu/build/lib/foobar/__about__.py' 'foobar':
  Traceback (most recent call last):
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/__main__.py", line 187, in <module>
      main()
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/__main__.py", line 173, in main
      MainControl.main()
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/MainControl.py", line 744, in main
      main_module = _createNodeTree(filename=filename)
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/MainControl.py", line 146, in _createNodeTree
      Recursion.checkPluginPath(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/importing/Recursion.py", line 275, in checkPluginPath
      checkPluginSinglePath(plugin_filename, module_package=module_package)
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/importing/Recursion.py", line 246, in checkPluginSinglePath
      checkPluginSinglePath(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/importing/Recursion.py", line 192, in checkPluginSinglePath
      module = recurseTo(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/importing/Recursion.py", line 65, in recurseTo
      module, added_flag = _recurseTo(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/importing/Recursion.py", line 37, in _recurseTo
      module, is_added = Building.buildModule(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/tree/Building.py", line 1291, in buildModule
      source_code = readSourceCodeFromFilename(
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/tree/SourceReading.py", line 169, in readSourceCodeFromFilename
      source_code_modified = Plugins.onModuleSourceCode(module_name, source_code)
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 593, in onModuleSourceCode
      new_source_code = plugin.onModuleSourceCode(module_name, source_code)
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/plugins/standard/PkgResourcesPlugin.py", line 129, in onModuleSourceCode
      value = self.metadata.version(match[1])
    File "/usr/lib/python3.9/importlib/metadata.py", line 551, in version
      return distribution(distribution_name).version
    File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
      return Distribution.from_name(distribution_name)
    File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
      raise PackageNotFoundError(name)
  importlib.metadata.PackageNotFoundError: foobar
  Traceback (most recent call last):
    File "/tmp/n/l/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/tmp/n/l/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/n/l/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 4, in <module>
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/distutils/DistutilCommands.py", line 94, in run
      self._build(os.path.abspath(self.build_lib))
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/distutils/DistutilCommands.py", line 228, in _build
      check_call(command, cwd=build_lib)
    File "/tmp/pip-build-env-kqv9y58f/overlay/lib/python3.9/site-packages/nuitka/utils/Execution.py", line 212, in check_call
      subprocess.check_call(*popenargs, **kwargs)
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/n/l/.tox/py3/bin/python', '-m', 'nuitka', '--module', '--plugin-enable=pylint-warnings', '--output-dir=/tmp/pip-req-build-xbrdinpu/build/lib', '--nofollow-import-to=*.tests', '--show-modules', '--remove-output', '--include-package=foobar', '/tmp/pip-req-build-xbrdinpu/build/lib/foobar']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for foobar
Failed to build foobar
ERROR: Could not build wheels for foobar, which is required to install pyproject.toml-based projects
```
Here comes the crazy part: The error disappears when removing the one line in `__about__.py`. But that line is just a comment!
```python
# metadata.version("foobar")
```

**Comment by kayhayen** [comment]
That is because, unlike for recent `importlib.import_module` optimization, this plugin works on the basis of source code search replacements. Once function level hard import tracing through module variables works, this is likely to be replaced with an approach that works during optimization. 

Exceptions duing such replacements are genuine bugs though, the code is attempting to catch them, but there are many variants, and the specific exceptions to look for are not known.

I added this one to factory, https://nuitka.net/doc/factory.html and it will be in the next release 0.6.18 which which be released any minute now.

**Comment by kayhayen** [comment]
As an aside, that very release has a `.pyproject` integration, read about in the manual, you wouldn't have to have a `setup.py` anymore. Let me know if and how well this works for you.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.

**Comment by nschloe** [comment]
Thanks!
