### ISSUE TITLE
`with suppress_known_deprecation():`   TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1316]
Follow-up on #1303.

When building with `pyproject.toml` and `nuitka.distutils.Build`, I'm getting the build error
```
[...]
       cwd: /tmp/pip-req-build-qwrt9dkw
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/nschloe/software/foobar/foobar/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/nschloe/software/foobar/foobar/.tox/py3/lib/p
ython3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/nschloe/software/foobar/foobar/.tox/py3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-_0ut264e/overlay/lib/python3.9/site-packages/nuitka/distutils/Build.py", line 39, in build_wheel
      with suppress_known_deprecation():
  TypeError: 'module' object is not callable
```

**Comment by kayhayen** [comment]
Please fill out the issue template. This was fixed in a hotfix, which I have to guess you didn't use.

**Comment by nschloe** [comment]
Sorry for not filling in the form; I got lazy.

You are right, it seems to have been fixed in https://github.com/Nuitka/Nuitka/commit/15d054cccd10ebb14190eb032b82935350586709. The corresponding 0.6.18.3 release isn't on PyPI though, so I'm having a hard time actually using it.

**Comment by kayhayen** [comment]
It actually is, I checked it, albeit there may have been overlap.

**Comment by kayhayen** [comment]
@nschloe the form exists, so I can be lazy :)

**Comment by nschloe** [comment]
Yup, it's up for 2 hours now, and the fix is in there. Thanks!
