### ISSUE TITLE
[QUESTION] I found this text in my .exe file when viewing it in a file editor. Why is it there and can I change it?

### ISSUE THREAD

**Issue by msr8** [Nuitka/Nuitka#1325]
So I complied a program and used the tag `--follow-imports` and it runs perfectly, no issue in that. However I saw this when viewing the files in a text editor (VS Code), there are like, docs for all the modules I used. Why is it there and will the program be affected if I remove them or edit the text? Also you can consider making a discord or subreddit for any future noob question
![Screenshot 2021-12-20 at 07 58 58](https://user-images.githubusercontent.com/79649185/146703714-fa2cd336-ec8e-4cea-ad84-93267ba72544.png)

**Comment by kayhayen** [comment]
You are obviously including doc strings, which can be disabled, check out the documentation. There are a couple of Python flags you ought to use. Nuitka commercial has more details on this, if your goal is obfuscucation. Constant data is not hidden in normal Nuitka, but only covered by Nuitka commercial: https://nuitka.net/doc/commercial.html#protection-against-reverse-enginneering

**Comment by kayhayen** [comment]
I am leaving this open as a remind to myself that Nuitka needs to make an output that explains what a created output is and is not, and provide links to this kind of information.

**Comment by kayhayen** [comment]
I have came back to this, and I was considering, if not I want to first make things more selective by chance. It would be nice if e.g. stdlib was not including the docstrings by default, and that per Yaml and options, this could be selected, and then we would report on the amount of docstrings included for modules and functions, and point to a mnemonic, that explains it better on the site. That will be a bit of development work, but my suspect is that at least for some packages, say numpy and stdlib, we can get this to be the default for standalone compilation at least. Maybe something for a live stream this week.

**Comment by mosol1** [comment]
how to fix this error


[2024-10-13 07:34:10] [INFO    ] discord.client: logging in using static token
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 15306, in <module>
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 952, in __init__
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 1436, in home
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 869, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\runners.py", line 194, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\runners.py", line 118, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\base_events.py", line 687, in run_until_complete
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 858, in runner
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 786, in start
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 620, in login
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\http.py", line 816, in static_login
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\http.py", line 638, in request
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\client.py", line 1355, in __aenter__
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\client.py", line 659, in _request
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 557, in connect
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1002, in _create_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1305, in _create_direct_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1061, in _wrap_create_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\impl.py", line 88, in start_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\_staggered.py", line 91, in staggered_race
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\taskgroups.py", line 145, in __aexit__
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\_staggered.py", line 88, in run_one_coro
    | aiohappyeyeballs._staggered._Done
    +------------------------------------

**Comment by kayhayen** [comment]
This state has persisted and will some more, as scalability is more important. With Nuitka commercial this is solved very nicely, and only the messaging needs real improvement, but there are nice optimization ideas in here. Currently it's possible to configure these things with Nuitka Package configuration and we ought to maybe change default for standard library doc strings now, but it's not a priority yet.
