### ISSUE TITLE
Utils - getLinuxDistribution failed

### ISSUE THREAD

**Issue by bsvedin** [Nuitka/Nuitka#1331]
Inside SLES based docker image
```
cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

Nuitka version 0.6.18.4 - This is a regression. It used to work in version 0.6.18.2

Ran the following command
```
python3 -m nuitka \
	--output-dir=bin \
	--include-package=<packageName> \
	--nofollow-import-to=<otherPackageName>  \
	--assume-yes-for-downloads \
	start_service.py
```
and it threw this error
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/nuitka/__main__.py", line 142, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/nuitka/__main__.py", line 78, in main
    from nuitka import Options  # isort:skip
  File "/usr/lib/python3.6/site-packages/nuitka/Options.py", line 30, in <module>
    from nuitka.OptionParsing import isPyenvPython, parseOptions
  File "/usr/lib/python3.6/site-packages/nuitka/OptionParsing.py", line 103, in <module>
    version="\n".join(_getVersionInformationValues()),
  File "/usr/lib/python3.6/site-packages/nuitka/OptionParsing.py", line 98, in _getVersionInformationValues
    yield "Distribution: %s %s" % getLinuxDistribution()
  File "/usr/lib/python3.6/site-packages/nuitka/utils/Utils.py", line 95, in getLinuxDistribution
    version = version.split()[0]
IndexError: list index out of range
```

Like I said, this used to work in a barely older version

**Comment by kayhayen** [comment]
Can I ask you for the following two things:

What does `lsb_release -i -s` output? Can you provide the content of `/etc/os-release` on your SLES system?

**Comment by bsvedin** [comment]
`lsb_release -i -s` command not found
```
cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

**Comment by kayhayen** [comment]
Can you retry with 0.6.18.5 and report output of `nuitka --version` ?

**Comment by bsvedin** [comment]
I no longer get the error with 0.6.18.5
