### ISSUE TITLE
Cannot get pycryptodome module with ARC4 Cipher to work

### ISSUE THREAD

**Issue by vinayinvicible** [Nuitka/Nuitka#1343]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
0.6.18.5
Commercial: None
Python: 3.10.0 (default, Oct 11 2021, 15:31:34) [GCC 9.3.0]
Flavor: pyenv
Executable: ~/.virtualenvs/nuitka-test/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu "20.04.3

* How did you install Nuitka and Python

  > Installed Python using pyenv.
     Installed Nuitka via pip. 

* The specific PyPI names and versions

  > python -m pip freeze
Nuitka==0.6.18.5
pycryptodome==3.12.0

* Many times when you get an error from Nuitka, your setup may be special

  Then even a `print("hello world")` program will not work, please try that and report
  that instead.

* Provide in your issue the Nuitka options used

  ```python
  #   test.py
  from Crypto.Cipher import ARC4
  ```
  `python -m nuitka test.py --onefile -o test`

  ```bash
  Traceback (most recent call last):
    File "/tmp/.mount_testTcayZQ/test.py", line 1, in <module>
      from Crypto.Cipher import ARC4
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "/tmp/.mount_testTcayZQ/Crypto/Cipher/ARC4.py", line 30, in <module Crypto.Cipher.ARC4>
    File "/tmp/.mount_testTcayZQ/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
  OSError: Cannot load native module 'Crypto.Cipher._ARC4': Not found '_ARC4.cpython-310-x86_64-linux-gnu.so', Not found '_ARC4.abi3.so', Not found '_ARC4.so'
  ```

**Comment by kayhayen** [comment]
I will merge the PR and consider a hotfix with it. It seems you added also a lot of hashes and ciphers beyond that, good job.
