### ISSUE TITLE
requests - Import Error

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1347]
```
0.6.19rc7
Commercial: None
Python: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\TEST\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
_p.s. win 11_

**Code:**
`import requests`

**cmd:**
`python -m nuitka --mingw64 --standalone --lto=no "D:\Test.py"`

**test.exe**
```
PS D:\TEST\Test.dist> D:\TEST\Test.dist\Test.exe
Traceback (most recent call last):
  File "D:\TEST\Test.dist\importlib\_common.py", line 89, in _tempfile
  File "D:\TEST\Test.dist\importlib\abc.py", line 371, in read_bytes
  File "D:\TEST\Test.dist\importlib\_adapters.py", line 54, in open
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEST\Test.dist\Test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\TEST\Test.dist\requests\__init__.py", line 133, in <module requests>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\TEST\Test.dist\requests\utils.py", line 41, in <module requests.utils>
  File "D:\TEST\Test.dist\certifi\core.py", line 37, in where
  File "D:\TEST\Test.dist\contextlib.py", line 135, in __enter__
  File "D:\TEST\Test.dist\importlib\_common.py", line 95, in _tempfile
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\andre\\AppData\\Local\\Temp\\tmp6vxl6lft'
```

_p.s. error only on python 3.10_

**Comment by kayhayen** [comment]
I believe this is a duplicate, and is already reported. Basically the Nuitka loader is missing an interface used by modern importlib to open package files, and therefore makes a useless copy to a temporary file, that on Windows can be locked by just about anything, Virus, Windows Defender, Search Indexer, what not.
