### ISSUE TITLE
AssertionError: ..vocab

### ISSUE THREAD

**Issue by omrivm** [Nuitka/Nuitka#1350]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):
0.6.18.6
Commercial: None
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) 
Flavor: Anaconda Python
OS: Linux
Arch: x86_64
Distribution: Debian bullseye/sid

* How did you install Nuitka and Python
installed via pip on anaconda

* Provide in your issue the Nuitka options used
python -m nuitka --follow-imports --standalone --onefile --warn-implicit-exceptions --assume-yes-for-downloads --follow-stdlib --enable-plugin=torch --enable-plugin=gevent --enable-plugin=multiprocessing --enable-plugin=numpy --enable-plugin=pkg-resources --enable-plugin=tensorflow --output-dir=~/build/Lemma/ LemmaSrv2.py

 * Error
 Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'spacy.strings' added 'pathlib'.                                                                           
PASS 1:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 4716/4753, spacy.tokens.morphanalysisTraceback (most recent call last):
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/__main__.py", line 142, in <module>
    main()
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/__main__.py", line 128, in main
    MainControl.main()
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/MainControl.py", line 906, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/MainControl.py", line 193, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 350, in optimizeModules
    finished = makeOptimizationPass()
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 312, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 204, in optimizeModule
    optimizeShlibModule(module)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 194, in optimizeShlibModule
    Plugins.considerImplicitImports(module=module, signal_change=signalChange)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 344, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 268, in _considerImplicitImports
    full_name = ModuleName(full_name)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/nuitka/utils/ModuleNames.py", line 31, in __init__
    assert ".." not in str(value), value
AssertionError: ..vocab

**Comment by kayhayen** [comment]
There is no reproducer though.

**Comment by omrivm** [comment]
Sorry, to reproduce:
`import spacy`
when spacy is installed:
```
pip install spacy
pip install -U spacy[cuda]
pip install spacy-transformers
python3 -m spacy download en_core_web_trf
```

**Comment by kayhayen** [comment]
I don't have CUDA, but it wasn't necessary. The problematic line is in a .pyi file, which makes relative imports:

`from ..vocab import Vocab`

The pyi parsing unlike the normal parsing doesn't yet consider the package name to resolve those. Apparently we have not yet come across this, but it needs to be added of course. The code has this:

` # TODO: Might want to add full relative import handling. `

**Comment by kayhayen** [comment]
So the fix is on the factory branch, I was compiling the module though, and encountering implicit imports, which I am adding to Nuitka handling for them. So you might want to wait a bit:  https://nuitka.net/doc/factory.html

**Comment by omrivm** [comment]
thank you for the quick response!
any ETA for for a full support for spacy?

**Comment by kayhayen** [comment]
@omrivm for anything not part of https://nuitka.net/doc/commercial.html the ETA thing does not exist, but rather it's done when it's done.

**Comment by kayhayen** [comment]
The pyi parsing bug is on develop now and will be in the 0.6.19 release. Spacy itself will take longer.

**Comment by omrivm** [comment]
Thank you!

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
