### ISSUE TITLE
Optmization error report with sets, failure to annotate potential exception exit, causing error compiling code using Python2 ldap3 module

### ISSUE THREAD

**Issue by tschloesser** [Nuitka/Nuitka#1371]
Dear all,

I am quite new to Pyhon and even more to Nuika. Today I started to compile a (simple) Python code utilizing the ldap3 module and run into the issue documented below.

As far as I can understand, the issue is not coming from my code, butr the (official) Python LDAP3 module.
(https://ldap3.readthedocs.io/en/latest/#)

Canb anybody help?

Kind regards 

Thorsten

ka-Options:INFO: Used command line options: --follow-imports --standalone getNMASUP#.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19' on Python '2.7' commercial None.
PASS 1:  16%|████████▎                                           | 112/705, ldap3.core.rdnsProblem with statement at /Library/Python/2.7/site-packages/ldap3/core/rdns.py:29:
-> class ReverseDnsSetting(object):

Problem with statement at /Library/Python/2.7/site-packages/ldap3/core/rdns.py:29:
-> class ReverseDnsSetting(object):

Problem with statement at /Library/Python/2.7/site-packages/ldap3/core/rdns.py:29:
-> class ReverseDnsSetting(object):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'module_name': <ModuleName ldap3.core.rdns>, 'code_flags': '', 'filename': '/Library/Python/2.7/site-packages/ldap3/core/rdns.py'}>'.
PASS 1:  16%|████████▎                                           | 112/705, ldap3.core.rdnsTraceback (most recent call last):
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/MainControl.py", line 913, in main
    main_module = _createNodeTree(filename=filename)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/MainControl.py", line 190, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 350, in optimizeModules
    finished = makeOptimizationPass()
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 312, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 207, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 103, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/ModuleNodes.py", line 537, in computeModule
    trace_collection=self.trace_collection
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/AssignNodes.py", line 274, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 594, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/OutlineNodes.py", line 246, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/Users/tschloesser/Library/Python/2.7/lib/python/site-packages/nuitka/nodes/TryNodes.py", line 154, in computeStatement
    statement,
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.

    <node co_argcount="0" co_filename="ldap3/core/rdns.py" co_freevars="" co_has_stardict="False" co_has_starlist="False" co_is_optimized="False" co_kind="Class" co_kwonlyargcount="0" co_lineno="29" co_name="ReverseDnsSetting" co_new_locals="True" co_posonlyargcount="0" co_varnames="" code_flags="" kind="StatementsFrameFunction" line="29">
      <role name="statements" type="list">
        <node kind="StatementLocalsDictOperationSet" line="35" locals_scope="&lt;LocalsDictHandle of locals_ldap3$core$rdns$$$class__1_ReverseDnsSetting_29&gt;" variable_name="SUPPORTED_VALUES">
          <role name="source">
            <node kind="ExpressionMakeSet" line="35">
              <role name="elements" type="list">
                <node kind="ExpressionLocalsVariableRef" line="35" variable_name="OFF" />
                <node kind="ExpressionLocalsVariableRef" line="35" variable_name="REQUIRE_RESOLVE_ALL_ADDRESSES" />
                <node kind="ExpressionLocalsVariableRef" line="35" variable_name="REQUIRE_RESOLVE_IP_ADDRESSES_ONLY" />
                <node kind="ExpressionLocalsVariableRef" line="36" variable_name="OPTIONAL_RESOLVE_ALL_ADDRESSES" />
                <node kind="ExpressionLocalsVariableRef" line="36" variable_name="OPTIONAL_RESOLVE_IP_ADDRESSES_ONLY" />
              </role>
            </node>
          </role>
        </node>
      </role>
    </node>

**Comment by kayhayen** [comment]
Thanks for the report, this is great. I hope to get this resolved in a hotfix coming soon.

**Comment by kayhayen** [comment]
I have pushed a tentative fix to factory: https://nuitka.net/doc/factory.html

**Comment by tschloesser** [comment]
Hy Kay,

thank you for the fast reply!

I tested the updated version with Python 2.7 under MacOS 11.6.2.
This thime the process did run for a longer time, but broke at the start of „Backend C“ - i belive this is because of MacOS security, is it:

ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.tbd for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)  

Can you provide some help on this as well ;-)

Kind regards

Thorsten

===========================
Thorsten Schlößer
***@***.***

**Comment by kayhayen** [comment]
@tschloesser create new issues for separate things please.

**Comment by kayhayen** [comment]
Part of 0.6.19.1 release
