### ISSUE TITLE
OSError: [Errno 7] Argument list too long: 'otool'

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#1382]
OS Mac os x 
latest nuitta from pypi pip install

python -m nuitka --onefile app.py

gives at the end 

OSError: [Errno 7] Argument list too long: 'otool'

**Comment by kayhayen** [comment]
Interesting, and why didn't you find out the issue template?

**Comment by MyraBaba** [comment]
Nuitka-Scons:INFO: Backend C compiler: /usr/local/bin/gcc-11 (gcc-11).
Nuitka-Scons:INFO: Compiled 1236 C files using ccache.                                                                                                                                                                     
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 1235
Traceback (most recent call last):
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/MainControl.py", line 957, in main
    copyUsedDLLs(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1182, in copyUsedDLLs
    used_dlls = detectUsedDLLs(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1116, in detectUsedDLLs
    worker_pool.submit(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/utils/ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1080, in addDLLInfo
    used_dlls = detectBinaryDLLs(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 1064, in detectBinaryDLLs
    return _detectBinaryPathDLLsMacOS(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/freezer/Standalone.py", line 779, in _detectBinaryPathDLLsMacOS
    stdout, _stderr, _exit_code = executeProcess(
  File "/Users/tulpar/Projects/Deeptt-Detection2/venv/test-REST-Nov2021/lib/python3.8/site-packages/nuitka/utils/Execution.py", line 453, in executeProcess
    process = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'otool'

**Comment by kayhayen** [comment]
Please retry with this one: https://nuitka.net/doc/factory.html

**Comment by MyraBaba** [comment]
Same error:

OSError: [Errno 7] Argument list too long: '/usr/bin/otool'

**Comment by kayhayen** [comment]
Ok, with a proper issue template filled out, you can retry, this is not usable.

**Comment by kayhayen** [comment]
Closed, because reporter didn't fill out the issue template and created doubt if the factory version was used at all successfully, this makes no sense to support, maybe somebody will encounter the same issue and be capable to make a useful report.
