### ISSUE TITLE
TypeError: replace() argument 1 must be str, not bytes

### ISSUE THREAD

**Issue by xbdr419** [Nuitka/Nuitka#1387]
nuitka  --version
0.6.19.3
Commercial: None
Python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\admin\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Nuitka-Memory:INFO: Memory usage changed loading module '__main__': 256.00 KB (262144 bytes)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\MainControl.py", line 913, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\MainControl.py", line 115, in _createNodeTree
    main_module = Building.buildMainModuleTree(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\tree\Building.py", line 1118, in buildMainModuleTree
    module.setEarlyModules(detectEarlyImports())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 589, in detectEarlyImports
    early_modules = tuple(_detectEarlyImports())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 509, in _detectEarlyImports
    result = _detectImports(command=import_code, user_provided=False, technical=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 286, in _detectImports
    for line in stderr.replace(b"\r", b"").split(b"\n"):
TypeError: replace() argument 1 must be str, not bytes

**Comment by kayhayen** [comment]
Seems very much impossible to happen, since the flavor was not detected, can you confirm this is CPython?

**Comment by kayhayen** [comment]
I am also suspecting, the locale might influence this. I see no way, that the process execution is not supposed to give bytes, where of course it wouldn't matter, but maybe you have something in environment variables, that affects Python here, such that it will produce `str` from a pipe, where bytes are normally given, but it looks very impossible, indeed.

**Comment by xbdr419** [comment]
Thanks , I tried rebuilding the environment in conda and it's working fine now. There should be some environmental influence, but not sure where the problem is.

**Comment by kayhayen** [comment]
I would appreciate if you could provide more information on what Python this originally was.  From the installation path, I would have said it might be a downloaded CPython, can you confirm? And maybe, I assume you are in Asia, correct me if I am wrong, you got something in `site` or `usersite` to make life easier or something like that. But possibly also a `.pth` file in the `site-packages` could do funny things. All of which, Nuitka ought to protect itself against well already. If it's not a CPython, I would love to know it better.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
