### ISSUE TITLE
orderedmultidict, cryptography are not included into app.dist for some reason

### ISSUE THREAD

**Issue by vsilent** [Nuitka/Nuitka#1398]
> python -m nuitka --version

* How did you install Nuitka and Python
using Docker

FROM python:3.9-slim as builder

RUN apt-get update && apt-get install -y gcc libpq5 libpq-dev git wget unzip ccache patchelf \
&& apt-get clean; apt-get autoclean; apt-get autoremove -y -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
COPY . .
RUN pip uninstall pyopenssl
RUN pip uninstall cryptography
RUN pip install -r requirements.txt
RUN pip install pyopenssl
RUN pip install cryptography
RUN pip install orderedmultidict
RUN pip install nuitka

PYTHONPATH=$PYTHONPATH:/app/tools:/app/tools/adapters/tools/:/app/tools/common:/app/tools/adapters:/app/tools/adapters/tools/common # anyway non of this is included 
RUN python3 -m nuitka --follow-imports --low-memory --include-plugin-directory=/app/tools --standalone run.py

* The specific PyPI names and versions

orderedmultidict, cryptography 

The app is compiled OK,  but when I run it in the container I get following

```
root@87440f29ed98:/app# ./run.bin 
Traceback (most recent call last):
  File "/app/run.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/app/loggingconf.py", line 4, in <module loggingconf>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/app/config.py", line 3, in <module config>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/app/tools/__init__.py", line 2, in <module tools>
    from .common.v1.http import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/app/tools/common/v1/http/__init__.py", line 7, in <module tools.common.v1.http>
    from furl import furl
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/furl/__init__.py", line 13, in <module furl>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/furl/furl.py", line 26, in <module furl.furl>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/furl/omdict1D.py", line 13, in <module furl.omdict1D>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/orderedmultidict/__init__.py", line 19, in <module orderedmultidict>
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/orderedmultidict/__version__.py'
```
After installing manually orderedmultidict in container with pip it worked fine, 
Another problem is relative import,  I have import like
```
root@87440f29ed98:/app# ./run.bin 
Traceback (most recent call last):
  File "/app/run.py", line 25, in <module>
  File "/app/run.py", line 17, in main
  File "/app/app/__init__.py", line 28, in create_app
  File "/app/app/do/__init__.py", line 2, in <module app.do>
    from .common.v1.http import (
  File "/app/tools/adapters/tools/__init__.py", line 2, in <module tools.adapters.tools>
    from .common.v1.asyncio.async_proxy import AsyncProxyMetaclass, AsyncProxy
ModuleNotFoundError: No module named 'tools.adapters.tools.common'
I tried to set paths but this did not help
root@87440f29ed98:/app# export PYTHONPATH=/app/tools:/app/tools/adapters/tools
```
Thanks

**Comment by kayhayen** [comment]
I think I was need a minimal example. It seems `orderedmultidict` is trying to open a source file to detect its own version, which is of course stupid, and probably needs some treatment in Nuitka. As for the other issue, manual copying to the dist folder is not supported at all, so lets first solve the first issue, and then look at that.

**Comment by kayhayen** [comment]
Added support for the `multiordereddict` which has indeed a manual open of source code to import values from it, how bad. It is now working on factory:  https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the 0.8 release I just made.
