### ISSUE TITLE
Reproducer for shapes.pop().getCType() KeyError: 'pop from an empty set'

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#1401]
Hi!

Here is the reproducer for #1373 

```python
docker run -it --rm ubuntu:18.04

apt update && apt install patchelf python3 python3-pip gcc make zlib1g-dev git
pip3 install nuitka zstandard tqdm
# Successfully installed nuitka-0.6.19.4 zstandard-0.17.0 tqdm-4.62.3

git clone -n https://github.com/xonsh/xonsh && cd xonsh && git checkout e761156

nuitka3 --static-libpython=yes --standalone --onefile --onefile-tempdir --include-module=tqdm xonsh
```
JFYI: 
* it works perfect if we remove `--include-module=tqdm`.
* i see the same error on Python 3.8.10 in `ubuntu:20.04` docker container

Log:
```
Nuitka-Options:INFO: Used command line options: --static-libpython=yes --standalone --onefile --onefile-tempdir --include-module=tqdm xonsh
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.4' on Python '3.6' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.six,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'curses' added '_curses'.                    
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                    
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.                
Nuitka:INFO: Completed Python level compilation and optimization.                                                   
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:WARNING: Problem creating function code '__main__$$$function__11_complex_call_helper_keywords_star_list_star_dict'.
C Source Generation:   1%|4                                                                        | 1/147, __main__Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/MainControl.py", line 923, in main
    result, options = compileTree()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/MainControl.py", line 792, in compileTree
    makeSourceDirectory()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/MainControl.py", line 389, in makeSourceDirectory
    data_filename=os.path.basename(c_filename + "onst"),  # Really .const
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/CodeGeneration.py", line 510, in generateModuleCode
    return _generateModuleCode(module=module, data_filename=data_filename)
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/CodeGeneration.py", line 471, in _generateModuleCode
    function_body=function_body, context=context
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/CodeGeneration.py", line 426, in generateFunctionBodyCode
    cross_module=function_body.isCrossModuleUsed()
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/FunctionCodes.py", line 611, in getFunctionCode
    needs_exception_exit=needs_exception_exit,
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/FunctionCodes.py", line 638, in _getFunctionCode
    temp_variables=temp_variables,
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/FunctionCodes.py", line 540, in setupFunctionLocalVariables
    context=context, variable=variable
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/VariableCodes.py", line 265, in decideLocalVariableCodeType
    c_type = getPickedCType(variable, context)
  File "/usr/local/lib/python3.6/dist-packages/nuitka/codegen/VariableCodes.py", line 227, in getPickedCType
    r = shapes.pop().getCType()
KeyError: 'pop from an empty set'

```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kayhayen** [comment]
Ok, I can work from there, thanks.

**Comment by kayhayen** [comment]
I think it should not happen with current develop version, can you try it?

**Comment by anki-code** [comment]
Yes! It works in Nuitka 0.6.20rc5 (current develop)!
