### ISSUE TITLE
CV2 cannot be imported via Nuitka properly

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1412]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

My Requirements:
MACOS Monterey
Python:3.7.3
Nuitka '0.6.19.4'

* How did you install Nuitka and Python

pip

* The specific PyPI names and versions

opencv-python==4.5.1.48
numpy==1.18.2

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

import cv2
if __name__     == "__main__":
    cap = cv2.VideoCapture(0)
    hello, img = cap.read()

* Provide in your issue the Nuitka options used

sudo python3.7 -m nuitka --standalone  --enable-plugin=numpy webcam.py

* Note if this is a regression

Not tried

Description:
CV2 cannot be imported via Nuitka properly. Following error pops up, in the first line("import cv2") during the standalone executable run. 

Note: I have already seen #1407 and #1275, but I guess my bug is something different? Even I cannot find my libswresample.3.5.100.dylib file in my laptop to copy paste it under CV2 folder as recommended here
https://github.com/Nuitka/Nuitka/issues/1275#issuecomment-983200547

Erro Message:
Traceback (most recent call last):
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/webcam.py", line 1, in <module>
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/cv2/__init__.py", line 5, in <module cv2>
ImportError: dlopen(/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/cv2/cv2.so, 0x0002): Library not loaded: @loader_path/libswresample.3.5.100.dylib
  Referenced from: /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libavcodec.58.54.100.dylib
  Reason: tried: '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libswresample.3.5.100.dylib' (no such file), '/usr/local/lib/libswresample.3.5.100.dylib' (no such file), '/usr/lib/libswresample.3.5.100.dylib' (no such file)Library not loaded: @loader_path/libswresample.3.5.100.dylib
  Referenced from: /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libavformat.58.29.100.dylib
  Reason: tried: '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libswresample.3.5.100.dylib' (no such file), '/usr/local/lib/libswresample.3.5.100.dylib' (no such file), '/usr/lib/libswresample.3.5.100.dylib' (no such file)

**Comment by emre84** [comment]
I have found libswresample file and copied all dylibs file into cv2/ folder but the same error pops up. I would be grateful for a response.

**This is my command:**
sudo python3.7 -m nuitka --standalone  --enable-plugin=numpy --python-flag=no_site --include-data-file=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cv2/.dylibs/*.dylib=cv2/ webcam.py

**This is error:**
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/webcam.py", line 1, in <module>
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/cv2/__init__.py", line 5, in <module cv2>
ImportError: dlopen(/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/cv2/cv2.so, 0x0002): Library not loaded: @loader_path/libswresample.3.5.100.dylib
  Referenced from: /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libavcodec.58.54.100.dylib
  Reason: tried: '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libswresample.3.5.100.dylib' (no such file), '/usr/local/lib/libswresample.3.5.100.dylib' (no such file), '/usr/lib/libswresample.3.5.100.dylib' (no such file)Library not loaded: @loader_path/libswresample.3.5.100.dylib
  Referenced from: /Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libavformat.58.29.100.dylib
  Reason: tried: '/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/webcam.dist/libswresample.3.5.100.dylib' (no such file), '/usr/local/lib/libswresample.3.5.100.dylib' (no such file), '/usr/lib/libswresample.3.5.100.dylib' (no such file)

**Comment by emre84** [comment]
Ok, I found the solution. In my case, I copied all my dylib file directly under webcam.dist/ folder instead of webcam.dist/CV2/ and it worked fine.
