### ISSUE TITLE
Nuitka should give better ModuleNotFoundError in case of imports asked to not follow to in standalone mode

### ISSUE THREAD

**Issue by William1Wu** [Nuitka/Nuitka#1426]
Hi Kayhayen,

My development environment is a virtualenv (python3.8) on Anaconda3 (2019.0.7). 
How do I create virtualenv and install python and nuitka
```
conda create -n nuitka python==3.8
pip install nuitka
```
Check version of Nuitka and OS
```
D:\nuitka>python -m nuitka --version
0.6.19.7
Commercial: None
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Software\Anaconda3\envs\algarch\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
The third-party dependency package I use is：
```
utils==1.0.1
matplotlib==3.1.3
numpy==1.22.2 (latest)
opencv_python==4.5.4.62
Pillow==8.4.0
scikit_image==0.18.3
scikit_learn==0.24.2
skimage==0.0
torch==1.10.0
torchvision==0.11.1
```

I use this command to execute nuitka to compile python code: 
`nuitka --standalone --show-memory --show-progress --nofollow-imports --plugin-enable=numpy,matplotlib,torch --output-dir=out/follow-import-plugin-numpy-matplotlib-torch main.py`

Then I copy all files on path `D:\Software\Anaconda3\envs\nuitka\Lib\site-packages` to path `D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist`

Finally, open a new command window to execute main.exe and then get a error message: 
```
D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\torch\package\_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._globals' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\main.py", line 3, in <module>
  File "D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\torchvision\__init__.py", line 7, in <module>
    from torchvision import datasets
  File "D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\torchvision\datasets\__init__.py", line 4, in <module>
    from .cifar import CIFAR10, CIFAR100
  File "D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\torchvision\datasets\cifar.py", line 4, in <module>
    import numpy as np
  File "D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\numpy\__init__.py", line 112, in <module numpy>
    from ._globals import (
ModuleNotFoundError: No module named 'numpy._globals'
```

1. numpy._globals exists on `D:\nuitka\out\follow-import-plugin-numpy-matplotlib-torch\main.dist\numpy\_globals.py` 
2. I try to downgrade numpy to older version, but it's also not working.

Could you help me to solve this problem? Thanks.

**Comment by kayhayen** [comment]
Ok, that's an excellent problem report. I am a bit confused as to why it is seemingly only happening with Anaconda or only when using torch, but oh wait:

Does this not trigger a warning for you: `--standalone --nofollow-imports`

Now what could be the source of an issue, where a module import is not followed?

I think what has happened, and you can correct me, is that Nuitka has told you that it doesn't follow unless you specify following options. You picked the one that silenced it on anything. Then it didn't run, and you learned, you need standalone mode. Nuitka outputs stuff, but who cares about a warning. Then it doesn't work, and you have no idea what to do, because well, how would you? 

I think you are not alone with this flow and it's Nuitka's fault. This comes down to Nuitka to track why a module was not included, and state that in the report it can create (very weak right now) and then use that list at compile time to interpret uncatched `ImportError` and stating why it was not included. That's an interesting topic for the next live stream: https://nuitka.net/pages/Streaming.html

But yes, no real issue behind this.

**Comment by William1Wu** [comment]
Hi Kayhayen,

Thanks for your response in advance.

> Ok, that's an excellent problem report. I am a bit confused as to why it is seemingly only happening with Anaconda or only when using torch, but oh wait:
> 
> Does this not trigger a warning for you: `--standalone --nofollow-imports`

Command: 
`nuitka --standalone --show-memory --show-progress --nofollow-imports --output-dir=out/follow-import main.py`
Then copy all files on path `D:\Software\Anaconda3\envs\nuitka\Lib\site-packages` and `D:\Software\Anaconda3\envs\nuitka\python3.dll` to path `D:\nuitka\out\follow-import\main.dist`
PS: Nothing happened after execute main.exe if no copy python3.dll to `D:\nuitka\out\follow-import\main.dist`

```
D:\nuitka\out\follow-import\main.dist>main.exe
Traceback (most recent call last):
  File "D:\nuitka\out\follow-import\main.dist\main.py", line 3, in <module>
  File "D:\nuitka\out\follow-import\main.dist\skimage\measure\__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes_lewiner, marching_cubes
  File "D:\nuitka\out\follow-import\main.dist\skimage\measure\_marching_cubes_lewiner.py", line 8, in <module>
    from ._marching_cubes_classic import _marching_cubes_classic
  File "D:\nuitka\out\follow-import\main.dist\skimage\measure\_marching_cubes_classic.py", line 3, in <module>
    import scipy.ndimage as ndi
  File "D:\nuitka\out\follow-import\main.dist\scipy\ndimage\__init__.py", line 153, in <module>
    from .interpolation import *
  File "D:\nuitka\out\follow-import\main.dist\scipy\ndimage\interpolation.py", line 37, in <module>
    from scipy import special
  File "D:\nuitka\out\follow-import\main.dist\scipy\special\__init__.py", line 643, in <module>
    from . import _ufuncs
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found.
```
> Now what could be the source of an issue, where a module import is not followed?
> 
> I think what has happened, and you can correct me, is that Nuitka has told you that it doesn't follow unless you specify following options. You picked the one that silenced it on anything. Then it didn't run, and you learned, you need standalone mode. Nuitka outputs stuff, but who cares about a warning. Then it doesn't work, and you have no idea what to do, because well, how would you?

Yes. Actually, it's successful to run Nuitka on other options. But still can't execute main.exe. error like:
`ImportError: DLL load failed while importing ft2font `

> 
> I think you are not alone with this flow and it's Nuitka's fault. This comes down to Nuitka to track why a module was not included, and state that in the report it can create (very weak right now) and then use that list at compile time to interpret uncatched `ImportError` and stating why it was not included. That's an interesting topic for the next live stream: https://nuitka.net/pages/Streaming.html
> 
> But yes, no real issue behind this.

**Comment by kayhayen** [comment]
Shifted the improvement to 1.0, maybe could be done in a live stream.

**Comment by norovsambuu** [comment]
I have same issue I tried to install exe file using Nuitka (version 1.1) on Python 3.8.10. 

I used following command to execute:
nuitka --mingw64 --follow-imports --onefile --enable-plugin=numpy --enable-plugin=tk-inter --include module=sqlalchemy.sql.default_comparator --enable-plugin=pyqt5 counter_for_sale\main.py

After installation, exe file is created successfully. When I run, command promt shows following error and exits silently.

Error line is shown in picture below.
![failed](https://user-images.githubusercontent.com/103095296/185064087-c54566d2-fb23-43dd-9470-90baab8373c1.png)

I tried compiling same code using PyInstaller and exe works without any problem. I want to know why nuitka is not working on my code.

Thank you very much in advance.

**Comment by kayhayen** [comment]
@norovsambuu posting in unrelated issues is a sure fire way to get ignored

**Comment by kayhayen** [comment]
I am adding the stream tag, as I believe this might be a good topic for a Nuitka live stream. I will update the issue once that is scheduled.

**Comment by kayhayen** [comment]
Streams have been delayed until march, want to get 3.11 support first.

**Comment by kayhayen** [comment]
With 3.11 support out, I figure this could be a first stream goal, putting a potential new `--deployment` option to good use.

**Comment by KevinRodriguez777** [comment]
is this still revelant?

**Comment by kayhayen** [comment]
Oh yes, it's a common user error to have a program crash because a module is not included, and the user had asked for it to not be included. I just don't take the time to do streams right now it seems. Keeping a list of modules excluded from inclusion, and checking their imports and error exit due to them, would make sense. A potential offender is also the GUI plugins, as they suppress other toolkits, but might be used in error, like you require PySide6 with the plugin, but there is a top level import of PyQt6 that is not caught elsewhere.

Arguable this kind of thing, including stream ideas, could live in the roadmap though.

**Comment by kayhayen** [comment]
I have finally an implementation of this. For a long time already, Nuitka tracks excluded modules for the purposes of the --report outputs, and it's actually pretty easy to add now, this will be coming to 4.0 and I am setting the factory tag early, but it wil go there and need to be disabled with `--no-deployment=excluded-module-usage`

**Comment by kayhayen** [comment]
This is part of the 4.0 release already.
