### ISSUE TITLE
RuntimeError: __code__ is not writable in Nuitka

### ISSUE THREAD

**Issue by penahause** [Nuitka/Nuitka#1432]
```
0.6.16.2
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Executable: C:\Users\thoma\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64

Nuitka instaled by pip. No virtualenv.

numpy==1.22.2
oauthlib==3.1.0
opencv-contrib-python==4.5.1.48
opencv-python==4.2.0.34

nuitka --standalone --follow-imports --mingw64 --enable-plugin=tk-inter --show-scons --show-progress --enable-plugin=numpy --enable-plugin=multiprocessing yolotiny.py
```

When I execute the exe the console window just pops. Tried to execut thru cmd and got:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\numpy\__init__.py", line 144, in <module numpy>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\numpy\core\__init__.py", line 23, in <module numpy.core>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\numpy\core\multiarray.py", line 80, in <module numpy.core.multiarray>
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\numpy\core\overrides.py", line 201, in decorator
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\numpy\core\overrides.py", line 183, in decorator
RuntimeError: __code__ is not writable in Nuitka
Traceback (most recent call last):
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\yolotiny.py", line 1, in <module>
  File "C:\Users\thoma\Desktop\YOLOTI~1.DIS\cv2\__init__.py", line 5, in <module cv2>
ImportError: numpy.core.multiarray failed to import
```

The code is a sample of OpenCV that detect people/objetcs/animals on screen based on "YOLO: Real-Time Object Detection" trained models.

**Comment by tfeldmann** [comment]
I've got the same error using numpy 1.22.2.

**Comment by kayhayen** [comment]
This has no reproducer. Open a new issue with the issue template filled out.
