### ISSUE TITLE
scipy.stats and "TypeError: arg 5 (closure) expected cell, found compiled_cell"

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1436]
Let's consider sample program and nuitka call for compilation:
https://github.com/belonesox/nuitka-arg5-closure-expected-cell-found-compiled-cell

* branches ``linux-python-3.9`` and ``windows-python-3.9``   for linux and windows respect.
* pipenv-based ``setup-demo.sh``/``setup-demo.bat`` for setup pipenv
* on ``demo_build.sh``/``demo_build.bat`` for build
* trivial ``test.py``

```
import numpy as np
import scipy.stats

if __name__ == "__main__":
    print(scipy.__version__)
```

for nuitka versions >=0.6.16.4 and <=0.6.19.2

we got on running compiled test.dist/test[.exe]
```
Traceback (most recent call last):
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/test.py", line 2, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/numpy/__init__.py", line 144, in <module nu
mpy>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/numpy/core/__init__.py", line 23, in <modul
e numpy.core>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/numpy/core/multiarray.py", line 80, in <mod
ule numpy.core.multiarray>
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/numpy/core/overrides.py", line 201, in deco
rator
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/numpy/core/overrides.py", line 183, in deco
rator
RuntimeError: __code__ is not writable in Nuitka
```
or 
```
Traceback (most recent call last):
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\numpy\__init__.py", line 144, in <module numpy>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\numpy\core\__init__.py", line 23, in <module numpy.core>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\numpy\core\multiarray.py", line 80, in <module numpy.core.multiarray>
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\numpy\core\overrides.py", line 201, in decorator
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\numpy\core\overrides.py", line 183, in decorator
RuntimeError: __code__ is not writable in Nuitka
```

----

for nuitka versions >0.6.19.2 and till factory branch we got
```
Traceback (most recent call last):
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/test.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/stats/__init__.py", line 453, in <module scipy.stats>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/stats/_stats_py.py", line 44, in <module scipy.stats._stats_py>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/stats/distributions.py", line 8, in <module scipy.stats.distributions>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/stats/_distn_infrastructure.py", line 27, in <module scipy.stats._distn_infrastructure>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/integrate/__init__.py", line 92, in <module scipy.integrate>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/integrate/_quadrature.py", line 31, in <module scipy.integrate._quadrature>
  File "/home/stas/projects/bugs/nuitka/nuitka-arg5-closure-expected-cell-found-compiled-cell/test.dist/scipy/integrate/_quadrature.py", line 24, in _copy_func
TypeError: arg 5 (closure) expected cell, found compiled_cell
```

```
Traceback (most recent call last):
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\test.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\stats\__init__.py", line 453, in <module scipy.stats>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\stats\_stats_py.py", line 44, in <module scipy.stats._stats_py>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\stats\distributions.py", line 8, in <module scipy.stats.distributions>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\stats\_distn_infrastructure.py", line 27, in <module scipy.stats._distn_infrastructure>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\integrate\__init__.py", line 92, in <module scipy.integrate>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\integrate\_quadrature.py", line 31, in <module scipy.integrate._quadrature>
  File "C:\projects\bugs\nuitka\NUITKA~2\TEST~1.DIS\scipy\integrate\_quadrature.py", line 24, in _copy_func
TypeError: arg 5 (closure) expected cell, found compiled_cell
```

**Comment by kayhayen** [comment]
This is fixed on factory branch. This rang a bell, but it was actually for Tensorflow that I have done a similar thing in the past. Basically, they copy functions for no good reason.

https://nuitka.net/doc/factory.html

This is going to be in the next hotfix if I don't forget it.

Yours,
Kay

**Comment by kayhayen** [comment]
This is part of 0.7.1 hotfix that I just made.
