### ISSUE TITLE
NotImplementedError: Can't perform this operation for unregistered loader type Pyfiglet

### ISSUE THREAD

**Issue by alf1e** [Nuitka/Nuitka#1437]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

0.8rc1
Commercial: None
Python: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Barlo\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

pip3 install git+https://github.com/Nuitka/Nuitka/

* The specific PyPI names and versions

git+https://github.com/Nuitka/Nuitka/
termcolor
pyfiglet

* Many times when you get an error from Nuitka, your setup may be special

  Then even a `print("hello world")` program will not work, please try that and report
  that instead.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```py
from pyfiglet import figlet_format
import pyfiglet.fonts

print(figlet_format("Sample Text"))
```

* Provide in your issue the Nuitka options used

nuitka --standalone --follow-imports main.py      

```
Traceback (most recent call last):
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\main.py", line 12, in <module>
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pyfiglet\__init__.py", line 65, in figlet_format
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pyfiglet\__init__.py", line 794, in __init__
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pyfiglet\__init__.py", line 801, in setFont
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pyfiglet\__init__.py", line 126, in __init__
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pyfiglet\__init__.py", line 136, in preloadFont
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pkg_resources\__init__.py", line 1120, in resource_exists
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pkg_resources\__init__.py", line 1391, in has_resource
  File "C:\Users\Barlo\OneDrive\Desktop\CLOUDF~1\CODE-N~1\DEBASS~1\MAIN~1.DIS\pkg_resources\__init__.py", line 1458, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
```

**Comment by kayhayen** [comment]
Seems you are aware of the duplicate, please don't do this creating duplicates.
