### ISSUE TITLE
anyio - BrokenResourceError

### ISSUE THREAD

**Issue by befedo** [Nuitka/Nuitka#1441]
Hello,

I have a [dash](https://plotly.com/dash/) application which is hosted as a [FastAPI](https://fastapi.tiangolo.com/) middleware with [uvicorn](https://www.uvicorn.org/). When I run the whole thing, with `> python app.py` everything works as expected. After building a standalone application (see below, build.bat) I get the following error:
```{text}
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\uvicorn\protocols\http\h11_impl.py", line 364, in run_asgi
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\fastapi\applications.py", line 212, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\applications.py", line 112, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\middleware\errors.py", line 159, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\exceptions.py", line 71, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\routing.py", line 656, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\routing.py", line 408, in handle
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\middleware\wsgi.py", line 64, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\middleware\wsgi.py", line 91, in __call__
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\to_thread.py", line 28, in run_sync
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\_backends\_asyncio.py", line 754, in run
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\starlette\middleware\wsgi.py", line 126, in wsgi
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\from_thread.py", line 35, in run
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\_backends\_asyncio.py", line 847, in run_async_from_thread
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\concurrent\futures\_base.py", line 446, in result
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\concurrent\futures\_base.py", line 391, in __get_result
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\streams\memory.py", line 193, in send
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\anyio\streams\memory.py", line 177, in send_nowait
anyio.BrokenResourceError
```
I've installed all in a venv, with the following version:
```{text}
> python -mnuitka --version
0.7
Commercial: None
Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\nuitka\Documents\build\app\.env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
I've invoked nuitka like below (build.bat)
```{text}
python -m nuitka^
  --mingw64^
  --standalone^
  --prefer-source-code^
  --assume-yes-for-downloads^
  --enable-plugin=numpy^
  --enable-plugin=multiprocessing^
  --enable-plugin=pylint-warnings^
  --include-package=sqlalchemy^
  --include-package=plotly^
  --include-data-dir=app/assets=app/assets^
  --include-package-data=plotly^
  --include-package-data=dash^
  --include-package-data=dash_renderer^
  --include-package-data=dash_extensions^
  --include-package-data=dash_html_components^
  --include-package-data=dash_core_components^
  --include-package-data=dash_bootstrap_components^
  app.py
```

I've found [something](https://stackoverflow.com/questions/64281002/pyinstaller-compiled-uvicorn-server-does-not-start-correctly) on stackoverflow but don't know if that helps.

If I can provide something else, please let me know.

Best regards
Befedo

**Comment by xkortex** [comment]
In all likelihood, this has nothing to do with Nuitka. This is something to do with a connection closing unexpectedly in the starlette/anyio layer. This issue might be related: https://github.com/encode/starlette/issues/1284

Are you able to reliably reproduce the error?

**Comment by kayhayen** [comment]
The report is also about ancient Nuitka.
