### ISSUE TITLE
tk-inter plugin error

### ISSUE THREAD

**Issue by Fire-Cube** [Nuitka/Nuitka#1471]
When I want to compile a program with --plugin-enable=tk-inter it gives an error.
`Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\MainControl.py", line 969, in main
    copyDataFiles(dist_dir=dist_dir)
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\freezer\Standalone.py", line 1582, in copyDataFiles
    for plugin, included_datafile in Plugins.considerDataFiles(module):
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\plugins\Plugins.py", line 547, in considerDataFiles
    for value in plugin.considerDataFiles(module):
  File "C:\Users\Ben\AppData\Roaming\Python\Python310\site-packages\nuitka\plugins\standard\TkinterPlugin.py", line 201, in considerDataFiles
    yield self.makeIncludedDataDirectory(
AttributeError: 'NuitkaPluginTkinter' object has no attribute 'makeIncludedDataDirectory'`

I use the newest nuitka version: 0.7.4

**Comment by funchan24** [comment]
I got the same error.

**Comment by madaraXor** [comment]
same error for me

**Comment by madaraXor** [comment]
I solved the problem by modifying the file \AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\standard\TkinterPlugin.py

        if isWin32Windows():
            yield self.makeIncludedDataDirectory(
                source_path=os.path.join(tcl, "..", "tcl8"),
                dest_path="tcl8",
                reason="Tcl modules needed for tkinter usage",
            )

------>

        if isWin32Windows():
            yield makeIncludedDataDirectory(
                source_path=os.path.join(tcl, "..", "tcl8"),
                dest_path="tcl8",
                reason="Tcl modules needed for tkinter usage",
            )

the self of the makeIncludedDataDirectory function
was incorrect

**Comment by kayhayen** [comment]
Ouch, regression in a hotfix, very bad. @madaraXor has the correct fix for it.

**Comment by kayhayen** [comment]
It's out on the main branch, should appear on PyPI soon, let me know if the problem persists, I was too lazy to test on Windows now, feeling under the weather.
