### ISSUE TITLE
ModuleName error trying to compile package

### ISSUE THREAD

**Issue by jcollado** [Nuitka/Nuitka#1488]
When trying to compile a python package using nuitka I got this error:
```
Nuitka-Options:INFO: Used command line options: --module company_project_name --include-package=company.project_name
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.6' on Python '3.6' commercial None.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/MainControl.py", line 919, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/MainControl.py", line 119, in _createNodeTree
    is_main=not Options.shallMakeModule(),
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/tree/Building.py", line 1144, in buildMainModuleTree
    hide_syntax_error=False,
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/tree/Building.py", line 1244, in buildModule
    logger=general,
  File "/home/user/miniconda3/envs/company.project_name/lib/python3.6/site-packages/nuitka/importing/Importing.py", line 697, in decideModuleSourceRef
    assert type(module_name) is ModuleName
AssertionError
```

This happened because I passed a package name instead of a `.py` file to the `--module` option.
If I pass a `.py` file, I get a a `.so` file back from `nuitka`. However, I'm not sure about
how a package should be compiled and used as a replacement of the original one.
What is the recommended procedure to do it?

To reproduce this scenario, please have a look a the following repository:
https://github.com/jcollado/nuitka-module-name-error-example

The `README.md` file contains full instructions about how I created the conda environment
and how I run `nuitka` to compile the code.

The relevant software versions are as follows:
- `conda`: 4.12.0
- `nuitka`: 0.7.6
- `gcc`: 11.2.0

**Comment by kayhayen** [comment]
Thanks a lot, this will help me eradicate this usability issue.

**Comment by kayhayen** [comment]
Seems I forgot about it, I have a new tag for issues that are well reported and that I will come back to now. I probably just forgot to track the solution. With current develop, and therefore likely stable, this is not happening.
