### ISSUE TITLE
Nuitka app erroring out while trying to pack with the arcade module

### ISSUE THREAD

**Issue by Hunter2807** [Nuitka/Nuitka#1492]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

0.7.6
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
(I am using Windows 11)

* How did you install Nuitka and Python

pip and https://python.org

* The specific PyPI names and versions

arcade v2.6.12

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
from arcade import Window

win = Window("Example", 500, 500)
win.run()
```

* Provide in your issue the Nuitka options used

```bash
python -m nuitka --include-data-file="C:\Users\HP\Desktop\Python Stuff\pyweek\assets.zip"=assets.zip run_game.py --standalone --follow-imports --enable-plugin=numpy --include-package=arcade
```

Whenever I try to run the exe compiled from the above options, this is the error I get:
```bash
C:\Users\HP\Desktop\Python Stuff\pyweek>run_game.dist\\run_game.exe
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\arcade\text_pyglet.py", line 27, in load_font
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\arcade\resources\__init__.py", line 39, in resolve_resource_path
FileNotFoundError: Cannot locate resource : C:\Users\HP\Desktop\Python Stuff\pyweek\run_game.dist\arcade\resources\fonts\ttf\Kenney Blocks.ttf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\run_game.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\game\views\start.py", line 1, in <module game.views.start>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\game\views\main.py", line 6, in <module game.views.main>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\arcade\__init__.py", line 573, in <module arcade>
  File "C:\Users\HP\Desktop\PYTHON~1\pyweek\RUN_GA~1.DIS\arcade\text_pyglet.py", line 29, in load_font
FileNotFoundError: Unable to find resource with the name: :resources:fonts/ttf/Kenney Blocks.ttf
```

I did some debugging and found out that nuitka is not packaging the `:resources:` directory, arcade provides with their module, when installed from PyPi. They also have a [pyinstaller hook](https://github.com/pythonarcade/arcade/blob/development/arcade/__pyinstaller/hook-arcade.py), in which they are manually adding the resources path to the data files. I understand I will also have to manually link those with the `--include-data-dir`  flag, but is this a bug with nuitka that it isn't including the resources path or the intended behaviour?

**Comment by kayhayen** [comment]
Nah, liking if it works by default. There is `data-files.yml` in Nuitka for this, and maybe you can make a PR for it.
