### ISSUE TITLE
Unable to run with Crypto & Cryptodome

### ISSUE THREAD

**Issue by Aikkko** [Nuitka/Nuitka#1501]
Hey, I can't run the code after compilation. Error:

```
Traceback (most recent call last):
  File "/tmp/.mount_enc.biYsK2tL/enc.py", line 5, in <module>
    from Cryptodome.Cipher import PKCS1_v1_5
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/.mount_enc.biYsK2tL/Cryptodome/Cipher/PKCS1_v1_5.py", line 33, in <module Cryptodome.Cipher.PKCS1_v1_5>
  File "/tmp/.mount_enc.biYsK2tL/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Cryptodome.Cipher._pkcs1_decode': Not found '_pkcs1_decode.cpython-310-x86_64-linux-gnu.so', Not found '_pkcs1_decode.abi3.so', Not found '_pkcs1_decode.so'
```

```bash
➜ $  pip list | grep crypto

crypto                        1.4.1
cryptography                  36.0.2
pycryptodome                  3.14.1
pycryptodomex                 3.12.0
```

Code:

```python
# -*- coding: utf8 -*-

import base64
from Crypto.PublicKey import RSA
from Cryptodome.Cipher import PKCS1_v1_5

mod = 22950459014405249699123127139811608263458812966021070961113300499494891383943282494730386636963905922878354481561960335213348934701708091591451235059884561345166039743786146156192538817088743718026223724124154807243679069208496820420620909496915419706516219463697951978845771140406616453876059707482118084152887113934623039840422363617971997587295709509457115082516069954750068555124344717737349788458884702890399489565239608944833307693878509677928243417850744322348038804372519631730352236487681015746653646328313452987638300990915762766439840042360705673070461861854518532159790058902205462916362709248737584997839

exp = 65537

rsa = RSA.construct((mod, exp))
cipher = PKCS1_v1_5.new(rsa)

def pkcs1v15_encrypt(key, message):
    return PKCS1_v1_5.new(key).encrypt(message)

print(base64.b64encode(pkcs1v15_encrypt(rsa, "pa$$ww0rd".encode('ascii'))))
```

0.8rc7
Commercial: None
Python: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None

Installed from pacman:
```bash
➜  ~ $ pacman -Q | grep nuitka  
nuitka 0.7.5-1
```

**Nuitka options**:
nuitka3 --standalone --onefile --follow-stdlib --linux-onefile-icon=/usr/share/pixmaps/links_32x32.xpm main.py

**Comment by kayhayen** [comment]
I managed to reproduce this with my development version, but only after updating `pycryptodomex`, so this is probably some sort of regression with them adding something we don't have yet.

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.
