### ISSUE TITLE
Error when building standalone with Nuitka-Python 

### ISSUE THREAD

**Issue by Maxwell175** [Nuitka/Nuitka#1506]
* How did you install Nuitka and Python

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually.

Run from source using Nuitka Python. 

* Provide in your issue the Nuitka options used

  Ideally use the project feature, so options and example code go alone

  [Nuitka Options in the code](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code)

test.py: `print("Hello World") `

-m nuitka --standalone test.py

Error:
```
Traceback (most recent call last):
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\MainControl.py", line 929, in main
    result, options = compileTree()
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\MainControl.py", line 852, in compileTree
    result, options = runSconsBackend(quiet=not Options.isShowScons())
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\MainControl.py", line 690, in runSconsBackend
    SconsInterface.runScons(
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\build\SconsInterface.py", line 249, in runScons
    options["result_name"] = getExternalUsePath(
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\utils\FileOperations.py", line 759, in getExternalUsePath
    dirname = getWindowsShortPathName(os.path.dirname(filename))
  File "C:\Nuitka-Python\output\lib\site-packages\nuitka\utils\FileOperations.py", line 728, in getWindowsShortPathName
    raise WindowsError(
FileNotFoundError: [Errno 2] The system cannot find the file specified.
```

git bisect led me to the following commit:

```
053c207229292b7f011937964a69cdf271d47532 is the first bad commit
commit 053c207229292b7f011937964a69cdf271d47532
Author: Kay Hayen <kay.hayen@gmail.com>
Date:   Mon Feb 7 09:57:30 2022 +0100

    macOS: Added support for mixing --onefile and --macos-create-app-bundle

    * For some software, e.g. PySide2 it will actually be the only way
      to get it working.
```

**Comment by kayhayen** [comment]
I think this is the missing `makePath` that you identified already.

**Comment by Maxwell175** [comment]
Yep. That's correct. Just opened an issue to track it.

**Comment by kayhayen** [comment]
I am adding a `resetDirectory` that first removes a directory and then creates it again, for use in these cases, that should solve the issue.

**Comment by kayhayen** [comment]
This in on https://nuitka.net/doc/factory.html right now, ought to work you.

On a side note, the `clcache` changes should make things work for you too, please try it too.

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
