### ISSUE TITLE
failed to import

### ISSUE THREAD

**Issue by stealth0414** [Nuitka/Nuitka#1508]
$ /e/yolov5_gitee2/window.dist/window.exe
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "E:\yolov5_gitee2\window.dist\window.py", line 19, in <module>
  File "E:\yolov5_gitee2\window.dist\cv2\__init__.py", line 8, in <module cv2>
    globals().update(importlib.import_module('cv2.cv2').__dict__)
ImportError: numpy.core.multiarray failed to import

Is it a version question between cv2 and numpy?How do i do to solve it when i run this exe?

**Comment by makao007** [comment]
same here , any solution ?
