### ISSUE TITLE
pyexcel: TypeError: descriptor 'iter_modules' for 'nuitka_module_loader' objects doesn't apply to a 'str' object

### ISSUE THREAD

**Issue by dagginio** [Nuitka/Nuitka#1515]
Hello,

I have a problem with pyexcel and compiling with Nuitka. Here is my bug report:
`
Traceback (most recent call last):
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\main.py", line 1, in <module>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel\__init__.py", line 12, in <module pyexcel>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel\book.py", line 11, in <module pyexcel.book>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlockedFile "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel\sheet.py", line 16, in <module pyexcel.sheet>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel\internal\__init__.py", line 13, in <module pyexcel.internal>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel\internal\source_plugin.py", line 18, in <module pyexcel.internal.source_plugin>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel_io\__init__.py", line 28, in <module pyexcel_io>
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pyexcel_io\plugins.py", line 257, in load_plugins
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\lml\loader.py", line 130, in scan_plugins_regex
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\lml\loader.py", line 115, in <genexpr>
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pkgutil.py", line 131, in iter_modules
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\functools.py", line 877, in wrapper
File "C:\Users\danie\DOCUME~1\GIT-RE~1\PYEXCE~1\MAIN~1.DIS\pkgutil.py", line 141, in iter_importer_modules
TypeError: descriptor 'iter_modules' for 'nuitka_module_loader' objects doesn't apply to a 'str' object`

I tried already including the pyexcel package. 

Nuitka version: 0.77 and 0.8RC8
Nuitka was installed by pip, and python was installed on windows by the setup files provided on python.org
More precisely I installed nuitka by pipenv

`
chardet==4.0.0
lml==0.1.0
Nuitka==0.7.7
pyexcel==0.7.0
pyexcel-io==0.6.6
texttable==1.6.4
`
Here is a short example:

`
import pyexcel
print("hello")
`

I compiled like this:
`
python -m nuitka --include-package=pyexcel --standalone --msvc=14.3 --lto=no main.py
`

Thanks for your help
Daniel

**Comment by kayhayen** [comment]
It seems that the `iter_modules` function of loader objects, may also be used in a static fashion, i.e. without a loader object., or we are storing the loader class where an object should be.

**Comment by kayhayen** [comment]
On the factory branch, this is now working. The commit has more, but basically the entry in `sys.meta_path` is used by`pkgutil`when you query without a package name, and then `iter_modules` was called with a string argument, which is not flying. The fix is to put a special object there rather than a class, that knows how to handle this in `iter_modules`.

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now on develop and will be in 0.8 release.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
