### ISSUE TITLE
No module named 'dns.rdtypes.ANY'

### ISSUE THREAD

**Issue by sudhakar-datta** [Nuitka/Nuitka#1526]
Issue - ModuleNotFoundError: No module named 'dns.rdtypes.ANY'

Skips compiling dnspython

command line usage: nuitka3 --follow-imports  --show-modules --standalone  --plugin-enable=eventlet,gevent  --include-module=dns bin/swift-proxy-server

Version and other details:
===================

~/swift-3-oxy$ nuitka3 --version
0.7.7
Commercial: None
Python: 3.6.9 (default, Mar 15 2022, 13:55:28) 
Flavor: Debian Python
Executable: /home/swift/swift-3-oxy/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6

```
=========================================
~/swift-3-oxy$ ./swift-proxy-server.dist/swift-proxy-server 
/home/swift/swift-3-oxy/swift-proxy-server.dist/distutils/__init__.py:14: UserWarning: The virtualenv distutils package at %s appears to be in the same location as the system distutils?
Traceback (most recent call last):
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/swift-proxy-server", line 18, in <module>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/swift/common/utils.py", line 48, in <module swift.common.utils>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/__init__.py", line 17, in <module eventlet>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/convenience.py", line 7, in <module eventlet.convenience>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/green/socket.py", line 21, in <module eventlet.green.socket>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/support/greendns.py", line 69, in <module eventlet.support.greendns>
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/support/greendns.py", line 61, in import_patched
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/patcher.py", line 132, in import_patched
  File "/home/swift/swift-3-oxy/swift-proxy-server.dist/eventlet/patcher.py", line 109, in inject
ModuleNotFoundError: No module named 'dns.rdtypes.ANY'

=============================================
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.query'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rcode'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdata'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdataclass'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdataset'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdatatype'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdtypes'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdtypes.IN'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rdtypes.IN.A'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.renderer'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.resolver'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.reversename'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.rrset'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.set'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.tokenizer'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.tsig'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.tsigkeyring'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.ttl'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.update'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.version'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.wiredata'.
Nuitka-Inclusion:INFO: Included uncompiled module 'dns.zone'.
```

**Comment by kayhayen** [comment]
This would need a minimal reproducer for me to see it.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
