### ISSUE TITLE
Nuitka raise SameFileError

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1528]
**Problem**
I tried to recompile a file using Nuitka. Unfortunatelly, it throw ```SameFileError```.

**Environment**
Nuitka 0.7.7
Python 3.10.4
Windows 10

**Error Output**
```
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Total memory usage before generating C code: 187.86 MB (196984832 bytes):
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 929, in main
    result, options = compileTree()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 798, in compileTree
    makeSourceDirectory()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 357, in makeSourceDirectory
    addExtensionModuleEntryPoint(module)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\IncludedEntryPoints.py", line 141, in addExtensionModuleEntryPoint
    copyDllFile(module.getFilename(), target_filename)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\SharedLibraries.py", line 581, in copyDllFile
    copyFile(source_path=source_path, dest_path=dest_path)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 638, in copyFile
    shutil.copyfile(source_path, dest_path)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:\\Users\\Home\\Desktop\\Python\\1\\Yashmak.dist\\_ctypes.pyd' and 'C:\\Users\\home\\Desktop\\Python\\1\\Yashmak.dist\\_ctypes.pyd' are the same file
```

**COMMAND**
```
nuitka --mingw64  --windows-disable-console --standalone --show-progress  --plugin-enable=pyqt6 --plugin-enable=multiprocessing --output-dir=C:\Users\home\Desktop\Python\1 C:\Users\home\PycharmProjects\QYashmak\project\Yashmak.py
```

**Comment by kayhayen** [comment]
I have had reports like this before, but I never managed to reproduce it. I wonder how this output folder relates to the source directory, and how it is located in %PATH% or something.

**Comment by kayhayen** [comment]
Closing for lack of feedback, my question was left unanswered, therefore this is without value.
