### ISSUE TITLE
Nuitka glfw plugin error for newer OpenGL

### ISSUE THREAD

**Issue by SimonasLetukas** [Nuitka/Nuitka#1531]
Hi,

I'm getting
```
Nuitka-Optimization:INFO: C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenGL\version.py:1 : new_code : Instructed by user to follow to all non-standard library modules.
FATAL: glfw: Undetected OS, please report bug for 'x11'.
```
when running
`python -m nuitka --standalone --enable-plugin=pyqt5 --verbose main.py`

Version info:
```
nuitka --version
0.7.7
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

I'm using pyforms in main.py which depends on OpenGL from what I understand. Maybe somebody has encountered a similar problem before and would be able to point me to the right direction? 

Thanks so much for your time!

**Comment by kayhayen** [comment]
I have added this for factory branch, ought to work now, let me know. https://nuitka.net/doc/factory.html

**Comment by SimonasLetukas** [comment]
Thanks for such a quick patch. I tried out the factory branch and now get a different (same?) error:
```
FATAL: glfw: Undetected OS specific glfw plugin 'wayland', please report bug for.
```

**Comment by kayhayen** [comment]
I see, it's a similar error, I have added it too.

**Comment by SimonasLetukas** [comment]
Tried it again, now get
```
PASS 1:  69%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 920/1324, OpenGLTraceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 925, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 201, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\optimizations\Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\optimizations\Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\optimizations\Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\optimizations\Optimization.py", line 149, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\importing\Recursion.py", line 448, in considerUsedModules
    Plugins.considerImplicitImports(module=module, signal_change=signal_change)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 369, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 295, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 274, in iterateModuleNames
    for v in value:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\GlfwPlugin.py", line 71, in getImplicitImports
    os_part, plugin_name_part = line[15:-1].split(",")
ValueError: too many values to unpack (expected 2)
```

**Comment by kayhayen** [comment]
This is not actually `glfw`, but `OpenGL` that changed, and it just happens to live in the plugin, but actually ought to be its own, it seems `glfw` works without it too. I managed to reproduce it after updating `PyOpenGL`.  The source code based parsing broke due to line comments after the plugin instantiation. One day we need to become better doing this inside the node tree of Nuitka.

Anyway, factory now should handle this just fine.

**Comment by SimonasLetukas** [comment]
It works now, thanks!

**Comment by kcleal** [comment]
Hi, 
Im having some issues with PyOpenGL and glfw. I tried using the factory branch but no success.

If I try `import OpenGL` it fails straight away with:

`Nuitka-Options:INFO: Used command line options: --onefile hello.py -o hello_bin
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.7' on Python '3.10' commercial None.
FATAL: glfw: Undetected OS, please report bug for 'x11'.`

If I try `import glfw`, things progress for a little while then it errors with:

`No installer needed, cached, one time question.
Proceed and download? [Yes]/No 
no
Nuitka-Scons:INFO: Backend linking program (no progress information available).                       
Nuitka-Scons:WARNING: You are not using ccache.
FATAL: Error, call to 'install_name_tool' failed: ['/opt/local/bin/install_name_tool', '-change', '/usr/local/opt/glfw/lib/libglfw.3.dylib', '@executable_path/libglfw.3.dylib', 'hello.dist/glfw/libglfw.3.3.dylib'] -> b'/opt/local/bin/install_name_tool: object: hello.dist/glfw/libglfw.3.3.dylib malformed object (unknown load command 9)'.`

Im using python3.10 in a venv

Thanks!

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
