### ISSUE TITLE
Build OpenCV standalone Error

### ISSUE THREAD

**Issue by makao007** [Nuitka/Nuitka#1535]
Hi, I try to build the opencv script, but fail. Could You Provide a mini OpenCV standalone build demo ?

python -m nuitka --version

0.8rc9
Commercial: None
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\softwares\conda\envs\deep\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

-------------  hello_cv.py
import cv2
img = cv2.imread('aa.jpg')
cv2.imshow('img', img)
cv2.waitKey(0)
----------------
python -m nuitka  hello_cv.py
Traceback (most recent call last):
  File "D:\temp\aaa\hello_cv.py", line 1, in <module>
    import cv2
  File "D:\temp\aaa\cv2\__init__.py", line 8, in <module cv2>
ModuleNotFoundError: No module named 'cv2.cv2'
----------------
nuitka --standalone  hello_cv.py
Traceback (most recent call last):
  File "D:\temp\aaa\HELLO_~1.DIS\hello_cv.py", line 1, in <module>
  File "D:\temp\aaa\HELLO_~1.DIS\cv2\__init__.py", line 8, in <module cv2>
ModuleNotFoundError: No module named 'cv2.cv2'
----------------
python -m nuitka --standalone  --nofollow-imports --mingw64 --plugin-enable=numpy,multiprocessing --output-dir=hello hello_cv.py 
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "D:\temp\aaa\hello\HELLO_~1.DIS\hello_cv.py", line 1, in <module>
  File "D:\temp\aaa\hello\HELLO_~1.DIS\cv2\__init__.py", line 8, in <module cv2>
ImportError: numpy.core.multiarray failed to import

**Comment by kayhayen** [comment]
Congratulations on using `--nofollow-imports` and reporting an `ImportError`. Read warnings.
