### ISSUE TITLE
OSError: [Errno 7] Argument list too long: 'ldd'

### ISSUE THREAD

**Issue by yanboma** [Nuitka/Nuitka#1537]
# python3 -m nuitka --version
0.8rc9
Commercial: None
Python: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
Flavor: Anaconda Python
Executable: /opt/conda/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.4

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/opt/conda/lib/python3.6/site-packages/nuitka/MainControl.py", line 976, in main
    standalone_entry_points=getStandaloneEntryPoints(),
  File "/opt/conda/lib/python3.6/site-packages/nuitka/freezer/Standalone.py", line 1366, in copyDllsUsed
    and Options.getWindowsDependencyTool() != "depends.exe",
  File "/opt/conda/lib/python3.6/site-packages/nuitka/freezer/Standalone.py", line 1140, in _detectUsedDLLs
    standalone_entry_point.package_name,
  File "/opt/conda/lib/python3.6/site-packages/nuitka/utils/ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "/opt/conda/lib/python3.6/site-packages/nuitka/freezer/Standalone.py", line 1101, in addDLLInfo
    update_cache=update_cache,
  File "/opt/conda/lib/python3.6/site-packages/nuitka/freezer/Standalone.py", line 1054, in _detectBinaryDLLs
    original_dir=os.path.dirname(original_filename),
  File "/opt/conda/lib/python3.6/site-packages/nuitka/freezer/Standalone.py", line 637, in _detectBinaryPathDLLsPosix
    stdout, stderr, _exit_code = executeProcess(command=("ldd", dll_filename))
  File "/opt/conda/lib/python3.6/site-packages/nuitka/utils/Execution.py", line 372, in executeProcess
    cwd=getExternalUsePath(os.getcwd()) if external_cwd else None,
  File "/opt/conda/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'ldd'

**Comment by kayhayen** [comment]
There is no reproducer, though.

**Comment by yanboma** [comment]
> 

I don't understand what you mean, how to fix it?

**Comment by kayhayen** [comment]
Providing a minimal reproducer is essential. Otherwise, this is useless.

**Comment by kayhayen** [comment]
This is an invalid report, but probably was fixed with 0.8 which had a better report that fits this.
