### ISSUE TITLE
Plugin for sqlalchemy or any hints?

### ISSUE THREAD

**Issue by mcfreis** [Nuitka/Nuitka#1563]
Hi, 

is there a plugin available for sqlalchemy or any hints what to include?

Thanky you

```python
Traceback (most recent call last):
  File "D:\PROGRA~1\te_tools\spaLab\receiver\receiverWidget.py", line 524, in onStartStop
  File "D:\PROGRA~1\te_tools\spaLab\receiver\receiverWidget.py", line 44, in open
  File "D:\PROGRA~1\te_tools\spaLab\dbIntf\dbIntf.py", line 23, in open
  File "<string>", line 2, in create_engine
  File "D:\PROGRA~1\te_tools\spaLab\sqlalchemy\util\deprecations.py", line 309, in warned
  File "D:\PROGRA~1\te_tools\spaLab\sqlalchemy\engine\create.py", line 534, in create_engine
  File "D:\PROGRA~1\te_tools\spaLab\sqlalchemy\engine\url.py", line 661, in _get_entrypoint
  File "D:\PROGRA~1\te_tools\spaLab\sqlalchemy\util\langhelpers.py", line 343, in load
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqlite
```

**Comment by kayhayen** [comment]
No issue template no fun.
