### ISSUE TITLE
nuitka with gridserachCV, when parameter n_jobs>1，UnboundLocalError: local variable 'pid' referenced before assignment

### ISSUE THREAD

**Issue by EWilsen** [Nuitka/Nuitka#1577]
Hi， 
 > python -m nuitka --version
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\software\python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python
* pip install nuitka

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually.
no virtualenv ， only download from https://www.python.org/

* The specific PyPI names and versions
the GridsearchCV from scikit-learn    1.0.2 which install by pip install scikit-learn

  > python -m pip freeze
cycler==0.11.0
fonttools==4.33.3
joblib==1.1.0
kiwisolver==1.4.2
lxml==4.8.0
matplotlib==3.5.2
Nuitka==0.7.7
numpy==1.22.3
packaging==21.3
pandas==1.4.2
Pillow==9.1.0
py4j==0.10.9.5
pycryptodomex==3.14.1
pyparsing==3.0.8
pypmml==0.9.16
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2022.1
pyzipper==0.3.5
scikit-learn==1.0.2
scipy==1.8.0
seaborn==0.11.2
six==1.16.0
threadpoolctl==3.1.0
xgboost==0.90
xlrd==2.0.1
xlwt==1.3.0
* Many times when you get an error from Nuitka, your setup may be special

  when without gridsearchCV everthing be okay

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

gsearch = GridSearchCV(estimator=XGBClassifier(), param_grid=param_list, 
                           scoring='roc_auc', cv=5, return_train_score=True, n_jobs=8)
gsearch.fit(X_train, y_train)

* Provide in your issue the Nuitka options used
Traceback (most recent call last):
  File "D:\grid_check\out\grid_test.dist\grid_test.py", line 80, in <module>
  File "D:\grid_check\out\grid_test.dist\grid_test.py", line 63, in __get_cv_params
  File "D:\grid_check\out\grid_test.dist\sklearn\model_selection\_search.py", line 820, in fit
    with parallel:
  File "D:\grid_check\out\grid_test.dist\joblib\parallel.py", line 725, in __enter__
    self._initialize_backend()
  File "D:\grid_check\out\grid_test.dist\joblib\parallel.py", line 735, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "D:\grid_check\out\grid_test.dist\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "D:\grid_check\out\grid_test.dist\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "D:\grid_check\out\grid_test.dist\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "D:\grid_check\out\grid_test.dist\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "D:\grid_check\out\grid_test.dist\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "D:\grid_check\out\grid_test.dist\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "D:\grid_check\out\grid_test.dist\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "D:\grid_check\out\grid_test.dist\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "D:\grid_check\out\grid_test.dist\joblib\externals\loky\backend\resource_tracker.py", line 162, in ensure_running
    pid = spawnv_passfds(exe, args, fds_to_pass)
  File "D:\grid_check\out\grid_test.dist\joblib\externals\loky\backend\resource_tracker.py", line 380, in spawnv_passfds
    print(pid)
UnboundLocalError: local variable 'pid' referenced before assignment

when i set n_jobs=1 , program do well, but is too slowly to get result.

**Comment by EWilsen** [comment]
> I think I have seen `joblib` in other issues too. It may well be something like `multiprocessing` that needs special care.

I tried to use other functions and solved the problem，XGBClassifier -->xgb.trian, 'multiprocessing'  worked

**Comment by kayhayen** [comment]
The example code is not enough to reproduce this. I used to ignore reports not actionable, but now I start to close/delete them. Will try with an example code I googled, just to know if there still any validity to the report.

**Comment by kayhayen** [comment]
The joblib is supposed to be supported well in 1.9 now, although 1.3 didn't work as expected when I checked it last, this issue seems obsolete, and I will fix joblib 1.3 for Windows in a 1.9 hotfix anyway
