### ISSUE TITLE
PyObjC assert error when running macOS app that uses pynput

### ISSUE THREAD

**Issue by madeinouweland** [Nuitka/Nuitka#1590]
I'm using Python 3.10.4 (from python.org) on macOS Monterey.
I created a virtual environment with `python -m venv env` and activated it
Then I installed:
```
pip install nuitka
pip install pynput
```

Here is what pip installed:
```
Package                              Version
------------------------------------ -------
Nuitka                               0.8.3
pip                                  22.0.4
pynput                               1.7.6
pyobjc-core                          8.5
pyobjc-framework-ApplicationServices 8.5
pyobjc-framework-Cocoa               8.5
pyobjc-framework-Quartz              8.5
setuptools                           58.1.0
six                                  1.16.0
```

I created main.py with this code:
```
import pynput

print("hello")
```

The program works and prints "hello"

Then I run this command:
```
python -m nuitka --follow-imports --standalone main.py --output-dir=publish
```

Output:
```
Nuitka-Options:INFO: Used command line options: --follow-imports --standalone main.py --output-dir=publish
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install
Nuitka:WARNING: 'ordered-set' or 'orderset' PyPI packages for best Python
Nuitka:WARNING: compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '0.8.3' on Python '3.10' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pynput.mouse' added 'pynput.mouse._darwin'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'pkg_resources' with 1 change(s) for: avoid using plistlib dependency on non-macOS.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'pydoc' with 1 change(s) for: remove module ability to display GUI with tkinter and topics data.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pynput.keyboard' added 'pynput.keyboard._darwin'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'zipfile' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.    
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka will make use of ccache to speed up repeated compilation.

Is it OK to download and put it in '/Users/hsc/Library/Application Support/Nuitka/ccache/v4.2.1'.

No installer needed, cached, one time question.

Proceed and download? [Yes]/No 
n
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Running clang -o module.AppKit._metadata.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=x86_64-apple-macos10.9 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=151 -D_NUITKA_EXE -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -I. -I/Users/hsc/dev/globalhotkeys/env/lib/python3.10/site-packages/nuitka/build/include -I/Users/hsc/dev/globalhotkeys/env/lib/python3.10/site-packages/nuitka/build/static_src module.AppKit._metadata.c took 144.08 seconds
Nuitka-Scons:INFO: Backend linking program (no progress information available). 
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka:INFO: Keeping build directory 'publish/main.build'.                      
Nuitka:INFO: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka:INFO: Successfully created 'publish/main.dist/main'.
```

The binary was created succesfully but when I run the programm, I get this error:

```
(env) globalhotkeys $ ./publish/main.dist/main 
Traceback (most recent call last):
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/pynput/__init__.py", line 40, in <module pynput>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/pynput/keyboard/__init__.py", line 31, in <module pynput.keyboard>
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/pynput/_util/__init__.py", line 70, in backend
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/pynput/keyboard/_darwin.py", line 29, in <module pynput.keyboard._darwin>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/Quartz/__init__.py", line 6, in <module Quartz>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/AppKit/__init__.py", line 10, in <module AppKit>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/Foundation/__init__.py", line 9, in <module Foundation>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/CoreFoundation/__init__.py", line 13, in <module CoreFoundation>
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/objc/_lazyimport.py", line 152, in __init__
  File "/Users/hsc/dev/globalhotkeys/publish/main.dist/objc/_lazyimport.py", line 510, in __load_cftypes
objc.internal_error: PyObjC: internal error in PyObjCClass_UnbuildClass at Modules/objc/class-builder.m:104: assertion failed: objc_class != nil
```

I have never tried this with older versions of Nuitka so I do not know if this is a regression.

**Comment by Maxwell175** [comment]
This issue can be narrowed down to just `pyobjc` and the following reproducer:

```
import objc

v = objc.registerCFSignature('CFAllocatorRef', b'^{__CFAllocator=}', 2)
print(v)
```

**Comment by kayhayen** [comment]
But other functions before and after just work. I have no idea, why it asserts about the class there.

**Comment by kayhayen** [comment]
https://github.com/ronaldoussoren/pyobjc/issues/502

**Comment by kayhayen** [comment]
So, this is in their bindings code, we need to make a change similar to the one for PySide, lets hope they carry it.

**Comment by kayhayen** [comment]
It seems that the new release has support for Nuitka 1.2 which should be released once this happens.

**Comment by kayhayen** [comment]
On factory branch it now also errors out in case too old `objc` module is used.

> FATAL: options-nanny: Using module (objc (8, 5, 1)) with no support: pyobjc is not supported before 9.0 or later

**Comment by emre84** [comment]
Hi Kay,

Thanks for your efforts. I am getting following error in runtime.(Compilation has no error)

**Nuitka Command:**
sudo python3.7 -m nuitka --run --standalone  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site test.py

**Error:**
Nuitka:INFO: Launching 'test.dist/test'
Traceback (most recent call last):
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/tests/test.dist/test.py", line 9, in <module>
AttributeError: 'NoneType' object has no attribute 'deliverNotification_'

**Script:**
import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter

notification = NSUserNotification.alloc().init()
notification.setTitle_("hallo")
notification.setInformativeText_("hallo2")
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification_(notification)
time.sleep(2)

(Note:center.deliverNotification_(notification) is line 9 and script works fine in PyCharm)

**Environment:**
I installed development 5 hours ago.

emres-Air:tests emre$ python3.7 -m nuitka --version
1.2rc8
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64

**Comment by kayhayen** [comment]
@emre84 posting below existing issues is a surefire way to get ignored

**Comment by kayhayen** [comment]
Part of the 1.2 release that was made a while ago.

**Comment by emre84** [comment]
Hallo Kay,

I installed development branch 10 min ago:
**VERSION:**
emres-Air:tests emre$ python3.7 -m nuitka --version
Nuitka-Options:INFO: Used command line options: --version
1.3rc3
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/CCompilerVersion.scons'
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/inline_copy/bin/scons.py", line 44, in <module>
**NOTE:**
Somehow I got an error for "python3.7 -m nuitka --version" command, as you see above. But my comment is not related with this warning

I used following nuitka command for below code:
**COMMAND:**
sudo python3.7 -m nuitka --run --standalone  --noinclude-pytest-mode=nofollow  --noinclude-setuptools-mode=nofollow --python-flag=no_site test5.py

**CODE:**
import os
import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter
_title = "title"
_message = "message"
notification = NSUserNotification.alloc().init()
notification.setTitle_(_title)
notification.setInformativeText_(_message)
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification_(notification)
time.sleep(2)

But if I execute my executable, I get following error:
**ERROR:**
Traceback (most recent call last):
  File "/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/tests/test5.dist/test5.py", line 16, in <module>
AttributeError: 'NoneType' object has no attribute 'deliverNotification_'

Do you know what the problem could be? Or is your bug fix not related with Foundation-NSUserNotification and Foundation-NSUserNotificationCenter libraries? I thought that #1590 would fix my problem.

Thanks a lot in advance.

**Comment by kayhayen** [comment]
@emre84 isn't is clear that posting new issues below other issues is not getting accepted?
