### ISSUE TITLE
objc.internal_error: PyObjC: internal error in PyObjCClass_UnbuildClass at Modules/objc/class-builder.m:91: assertion failed: objc_class != nil

### ISSUE THREAD

**Issue by AlvinKuruvilla** [Nuitka/Nuitka#1597]
From what I can see from the backtrace the issue revolves around pynput, but the build process works fine. This issue only occurs when running the generated executable
  > python -m nuitka --version
0.8.3
Commercial: None
Python: 3.9.13 (main, May 24 2022, 21:28:31)
Flavor: Unknown
Executable: /Users/alvinkuruvilla/Dev/kmlog/env/bin/python3
OS: Darwin
Arch: x86_64

Installed nuitka  using Pip

Build Script
```
python3 -m nuitka --follow-imports src/tui.py
```
Backtrace:
```
Traceback (most recent call last):
  File "/Users/alvinkuruvilla/Dev/kmlog/src/tui.py", line 35, in <module>
    from tools.keylogger import Keylogger
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/src/tools/keylogger.py", line 19, in <module tools.keylogger>
    from pynput.keyboard import Listener
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/pynput/__init__.py", line 40, in <module pynput>
    from . import keyboard
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/pynput/keyboard/__init__.py", line 31, in <module pynput.keyboard>
    backend = backend(__name__)
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/pynput/_util/__init__.py", line 70, in backend
    return importlib.import_module('._' + module, package)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/pynput/keyboard/_darwin.py", line 29, in <module pynput.keyboard._darwin>
    import Quartz
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/Quartz/__init__.py", line 6, in <module Quartz>
    import AppKit
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/AppKit/__init__.py", line 10, in <module AppKit>
    import Foundation
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/Foundation/__init__.py", line 9, in <module Foundation>
    import CoreFoundation
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/CoreFoundation/__init__.py", line 13, in <module CoreFoundation>
    sys.modules["CoreFoundation"] = mod = objc.ObjCLazyModule(
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/objc/_lazyimport.py", line 151, in __init__
    self.__load_cftypes(metadict.get("cftypes"))
  File "/Users/alvinkuruvilla/Dev/kmlog/env/lib/python3.9/site-packages/objc/_lazyimport.py", line 510, in __load_cftypes
    v = objc.registerCFSignature(name, typestr, func())
objc.internal_error: PyObjC: internal error in PyObjCClass_UnbuildClass at Modules/objc/class-builder.m:91: assertion failed: objc_class != nil
```

**Comment by kayhayen** [comment]
This might be a duplicate, and has no reproducer anyway.
