### ISSUE TITLE
ModuleNotFoundError: No module named 'multiprocessing', while using ProcessPoolExecutor

### ISSUE THREAD

**Issue by junbaibai0719** [Nuitka/Nuitka#1613]
I compiled these code
```
import time
from concurrent.futures import ProcessPoolExecutor

def run():
    time.sleep(1)
    print(1)

def main():
    with ProcessPoolExecutor() as pool:
        pool.submit(run())


if __name__ == '__main__':
    main()
```
with command : ```python -m nuitka --standalone --mingw64   --show-memory --show-modules --show-progress  --plugin-enable=multiprocessing  --output-dir=dist  main.py```.
Then I run it:
```
D:\Documents\processPoolExecutor\dist\main.dist>main.exe
Traceback (most recent call last):
  File "D:\DOCUME~1\PROCES~1\dist\MAIN~1.DIS\main.py", line 2, in <module>
  File "D:\DOCUME~1\PROCES~1\dist\MAIN~1.DIS\concurrent\futures\__init__.py", line 44, in __getattr__
  File "D:\DOCUME~1\PROCES~1\dist\MAIN~1.DIS\concurrent\futures\process.py", line 51, in <module>
ModuleNotFoundError: No module named 'multiprocessing'

D:\Documents\processPoolExecutor\dist\main.dist>
```

**Comment by kayhayen** [comment]
Missing stdlib dependency, https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
