### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by cool1coder** [Nuitka/Nuitka#1618]
hi, i am tryna make 1 exe and it does work but once i have the FileNotFoundError: [WinError 2] The system cannot find the file specified i do have the exe but with plenty of pyd files and folders so if u know how to fix this pls help me here is the log:

Nuitka-Options:INFO: Used command line options: --onefile --standalone --enable-plugin=numpy --windows-icon-from-ico=cool.ico --windows-company-name=Report-Bots --windows-product-version=1.0 main.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.8.4' on Python '3.10' commercial None.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'psutil' with 11 change(s) for: resolve platform specific imports at compile time.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'anyio._core._eventloop' added 'anyio._backends._asyncio'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'certifi.core' with 1 change(s) for: avoid using importlib.resources without need.
Nuitka-Plugins:INFO: anti-bloat: Updated module 'cffi.api' function 'distutils_extension'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'cffi.ffiplatform' with 1 change(s) for: disable distutils hacks.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: anti-bloat: Updated module 'lib2to3.pgen2.literals' function 'test'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pycparser.c_parser' added 'pycparser.yacctab,pycparser.lextab'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib3' added 'urllib3,urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,urllib.response'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'cryptography' added '_cffi_backend'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'zipfile' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
Nuitka-Scons:INFO: Running 'C:\\Users\\mverb\\AppData\\Local\\Nuitka\\Nuitka\\gcc\\x86_64\\11.2.0-14.0.0-9.0.0-msvcrt-r7\\mingw64\\bin\\gcc.exe -o "C:\\Users\\mverb\\DOWNLO~1\\GRABBE~1.SCR\\TIKTOK~1\\MAIN~1.DIS\\main.exe" -fuse-linker-plugin -flto=4 -fpartial-inlining -freorder-functions -Wl,--exclude-all-symbols -Wl,--out-implib,.\\import.lib -municode -O3 -s -Wl,--enable-auto-import -Wl,--stack,9863168 -static-libgcc @".\\@link_input.txt" -LC:\\Users\\mverb\\AppData\\Local\\Programs\\Python\\Python310\\libs -lm -lpython310' took 1304.89 seconds
Nuitka-Scons:INFO: Compiled 1716 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 428
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 4
Nuitka-Postprocessing:INFO: Adding 1 icon(s) from icon file 'cool.ico'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Traceback (most recent call last):
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 987, in main
    packDistFolderToOnefile(dist_dir, binary_filename)
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Onefile.py", line 69, in packDistFolderToOnefile
    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Onefile.py", line 370, in packDistFolderToOnefileBootstrap
    compressor_python = getCompressorPython()
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Onefile.py", line 291, in getCompressorPython
    compressor_python = findInstalledPython(
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\InstalledPythons.py", line 212, in findInstalledPython
    if candidate.checkUsability(
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\InstalledPythons.py", line 68, in checkUsability
    output = check_output([self.python_exe, "-c", test_code])
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\Execution.py", line 123, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mverb\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kayhayen** [comment]
Was still able to make a guess, and potentially fix the issue, the registry of yours contains Python installations that are no longer accessible, and subprocess creates an uncaught exception for those. I added a file existence check for installed Python scans. As a workaround, you can also install `zstandard` as well, then it wouldn't scan for other Pythons to have it.
