### ISSUE TITLE
Icon error: OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by SysKeyyy** [Nuitka/Nuitka#1619]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

Hi! I have seen other issues regarding icons in Nuitka, but none seemes to match my problem.

The develop version of Nuitka does not fix the problem, and updating / downgrading neither.

this is the error i recive when the compiler trys to apply the icon: 

```
Traceback (most recent call last):
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 187, in <module>
    main()
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 766, in main
    executePostProcessing()
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\PostProcessing.py", line 322, in executePostProcessing
    executePostProcessingResources(manifest=manifest, onefile=False)
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\PostProcessing.py", line 283, in executePostProcessingResources
    _addWindowsIconFromIcons(onefile=onefile)
  File "C:\Users\cudden\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\PostProcessing.py", line 177, in _addWindowsIconFromIcons
    icon_file.seek(icon.image_offset, 0)
OSError: [Errno 22] Invalid argument
```

I installed nuitka first using the executable installer, and then tryed with PIP

My Nuitka / python info:

```
0.6.17.7
Commercial: None
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Users\cudden\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

This is my command: 
```
nuitka --mingw64 .\test.py --onefile --standalone --windows-uac-admin --windows-icon-from-ico=c:\\users\\cudden\\pictures\\tool.ico
```

**Comment by kayhayen** [comment]
Very old Nuitka, please retry with recent one. Icon parsing codes have had fixes in the past.
