### ISSUE TITLE
minimal standalone pytorch program fails with linker error on macOS

### ISSUE THREAD

**Issue by victor-shepardson** [Nuitka/Nuitka#1628]
* Nuitka version, full Python version, flavor, OS, etc.

```
0.9
Commercial: None
Python: 3.9.12 (main, Jun  1 2022, 06:36:29)
Flavor: Anaconda Python
Executable: /Users/victor/anaconda3/envs/nuitka-torch10/bin/python
OS: Darwin
Arch: x86_64
```

* How did you install Nuitka and Python

installed python=3.9 and pip via conda, pytorch=1.10 from the pytorch conda channel, then nuitka from pip

* The specific PyPI names and versions

```
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2022.4.26=hecd8cb5_0
  - certifi=2022.6.15=py39hecd8cb5_0
  - intel-openmp=2022.0.0=hecd8cb5_3615
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libuv=1.40.0=haf1e3a3_0
  - mkl=2022.0.0=hecd8cb5_105
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1o=hca72f7f_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.12=hdfd78df_1
  - pytorch=1.10.2=py3.9_0
  - readline=8.1.2=hca72f7f_1
  - setuptools=61.2.0=py39hecd8cb5_0
  - sqlite=3.38.5=h707629a_0
  - tk=8.6.12=h5d9f67b_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=hca72f7f_1
  - zlib=1.2.12=h4dc903c_2
  - pip:
    - nuitka==0.9
```

* test program

```
import torch

x = torch.randn(1000)

print(x)
```

* nuitka command

`python -m nuitka test.py --standalone --plugin-enable=numpy`

* result

```
Nuitka-Options:INFO: Used command line options: test.py --standalone --plugin-enable=numpy
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' or
Nuitka:WARNING: 'orderedset' PyPI packages for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '0.9' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'torch.onnx.symbolic_registry' added 'torch.onnx.symbolic_opset7,torch.onnx.symbolic_opset12,torch.onnx.symbolic_opset14'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs,pkg_resources._vendor.jaraco,pkg_resources._vendor.importlib_resources,pkg_resources._vendor.more_itertools'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.jaraco' added 'pkg_resources._vendor.jaraco.text,pkg_resources._vendor.jaraco.functools,pkg_resources._vendor.jaraco.context'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'concurrent.futures.process' added 'multiprocessing,multiprocessing.connection'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'quopri' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Running /Users/victor/Library/Application Support/Nuitka/ccache/v4.2.1/ccache /usr/bin/clang -o module.torch.onnx.symbolic_opset9.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=x86_64-apple-macos10.9 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=152 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -I/Users/victor/anaconda3/envs/nuitka-torch10/include/python3.9 -I. -I/Users/victor/anaconda3/envs/nuitka-torch10/lib/python3.9/site-packages/nuitka/build/include -I/Users/victor/anaconda3/envs/nuitka-torch10/lib/python3.9/site-packages/nuitka/build/static_src module.torch.onnx.symbolic_opset9.c took 64.53 seconds
Nuitka-Scons:INFO: Backend linking program with 434 modules (no progress information available).
Undefined symbols for architecture x86_64:
  "_CALL_FUNCTION_WITH_ARGS1", referenced from:
      _impl_torch$nn$quantized$modules$linear$$$function__23_from_float in module.torch.nn.quantized.modules.linear.o
     (maybe you meant: _CALL_FUNCTION_WITH_ARGS11_KWSPLIT, _CALL_FUNCTION_WITH_ARGS10 , _CALL_FUNCTION_WITH_ARGS1_VECTORCALL , _CALL_FUNCTION_WITH_ARGS10_VECTORCALL , _CALL_FUNCTION_WITH_ARGS10_KWSPLIT , _CALL_FUNCTION_WITH_ARGS19_KWSPLIT , _CALL_FUNCTION_WITH_ARGS15_KWSPLIT , _CALL_FUNCTION_WITH_ARGS1_KWSPLIT , _CALL_FUNCTION_WITH_ARGS14 , _CALL_FUNCTION_WITH_ARGS13 , _CALL_FUNCTION_WITH_ARGS11 , _CALL_FUNCTION_WITH_ARGS19 , _CALL_FUNCTION_WITH_ARGS12 , _CALL_FUNCTION_WITH_ARGS13_KWSPLIT )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [/Users/victor/nuitka_test/test.dist/test] Error 1
```

similar result with pytorch=1.11

**Comment by kayhayen** [comment]
This is fixed on factory branch on for coming 0.9.1 hotfix branch, has nothing to do with torch really, for format with single positional argument, a regression of the `str.format` that I found too.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by victor-shepardson** [comment]
thanks! I tried `git clone`, `git checkout factory` and `python setup.py install`, but now I get this:

```
Nuitka-Options:INFO: Used command line options: test.py --standalone --plugin-enable=numpy
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' or
Nuitka:WARNING: 'orderedset' PyPI packages for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0rc1' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'torch.onnx.symbolic_registry' added 'torch.onnx.symbolic_opset7,torch.onnx.symbolic_opset12,torch.onnx.symbolic_opset14,torch.onnx.symbolic_opset15'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources.extern' added 'pkg_resources._vendor.packaging,pkg_resources._vendor.pyparsing,pkg_resources._vendor.appdirs,pkg_resources._vendor.jaraco,pkg_resources._vendor.importlib_resources,pkg_resources._vendor.more_itertools'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.jaraco' added 'pkg_resources._vendor.jaraco.text,pkg_resources._vendor.jaraco.functools,pkg_resources._vendor.jaraco.context'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pkg_resources._vendor.packaging' added 'pkg_resources._vendor.packaging.version,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.requirements'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'concurrent.futures.process' added 'multiprocessing,multiprocessing.connection'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'quopri' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 461 modules (no progress information available).
Nuitka-Scons:INFO: Compiled 461 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 460
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/protoc-3.13.0.0' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch/bin/torch_shm_manager' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included 7176 data files due to package data directory 'include' for 'torch'.
Nuitka-Plugins:INFO: dll-files: Found 7 files DLLs from torch installation.
Detecting used DLLs: 82.3%|████████████████████▌    | 51/62, test.dist/termios.soTraceback (most recent call last):
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/__main__.py", line 138, in <module>
    main()
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/MainControl.py", line 986, in main
    copyDllsUsed(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 1396, in copyDllsUsed
    used_dlls = _detectUsedDLLs(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 1157, in _detectUsedDLLs
    worker_pool.submit(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/utils/ThreadedExecutor.py", line 45, in submit
    self.results.append(function(*args))
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 1111, in addDLLInfo
    used_dlls = _detectBinaryDLLs(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 1087, in _detectBinaryDLLs
    return _detectBinaryPathDLLsMacOS(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 801, in _detectBinaryPathDLLsMacOS
    _, sub_result = _detectBinaryPathDLLsMacOS(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 801, in _detectBinaryPathDLLsMacOS
    _, sub_result = _detectBinaryPathDLLsMacOS(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 801, in _detectBinaryPathDLLsMacOS
    _, sub_result = _detectBinaryPathDLLsMacOS(
  [Previous line repeated 981 more times]
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/freezer/Standalone.py", line 782, in _detectBinaryPathDLLsMacOS
    stdout = getOtoolDependencyOutput(
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/utils/SharedLibraries.py", line 279, in getOtoolDependencyOutput
    with withEnvironmentPathAdded("DYLD_LIBRARY_PATH", *package_specific_dirs):
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/site-packages/Nuitka-1.0rc1-py3.9-macosx-10.9-x86_64.egg/nuitka/utils/Execution.py", line 171, in withEnvironmentPathAdded
    if env_var_name in os.environ:
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/_collections_abc.py", line 769, in __contains__
    self[key]
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/Users/victor/anaconda3/envs/nuitka91-torch11/lib/python3.9/os.py", line 755, in encode
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by LabGuy94** [comment]
try to include the torch plugin if you haven't already

**Comment by kayhayen** [comment]
No idea, what is going on there,  `[Previous line repeated 981 more times].` ... why would it recurse there this many times, something going wrong.

**Comment by kayhayen** [comment]
The fix I am talking about is now in 0.9, but it seems I need to check out, what is going on there. I assume it's about Anaconda on macOS and something causing an endless recursion in the dependency detection there.

@LabGuy94 the torch plugin is no more, it got merged into the Yaml configuration entirely.

```
class NuitkaPluginTorch(NuitkaPluginBase):
    """This plugin is now not doing anything anymore."""

    plugin_name = "torch"
    plugin_desc = "Deprecated, was once required by the torch / torchvision packages"

    @classmethod
    def isRelevant(cls):
        # Only to prevent build scripts that reference it from crashing.
        return False
```

**Comment by kayhayen** [comment]
The dependency analysis got rewritten for 1.0 and this should be solved on factory right now. https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is part of 1.0 release.
