### ISSUE TITLE
LLVMLite and XGBoost dll error

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1636]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
0.9
Commercial: None
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions
pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

  > python -m pip freeze
llvmlite==0.38.1
xgboost==1.6.0
shap==0.40.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import xgboost
import shap

print('hello world')
```

* Provide in your issue the Nuitka options used

python -m nuitka --enable-plugin=numpy --enable-plugin=tk-inter --enable-plugin=tensorflow --nofollow-import-to=IPython,dask --mingw64 --standalone main.py

### Explanation

When i run the exe i obtain this error:

```
Traceback (most recent call last):
  File "D:\MAIN~1.DIS\main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\plotter.py", line 9, in <module plotter>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D\MAIN~1.DIS\shap\__init__.py", line 12, in <module shap>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D\MAIN~1.DIS\shap\_explanation.py", line 12, in <module shap._explanation>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\shap\utils\__init__.py", line 1, in <module shap.utils>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "D:\MAIN~1.DIS\shap\utils\_clustering.py", line 4, in <module shap.utils._clustering>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\numba\__init__.py", line 19, in <module numba>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\numba\core\config.py", line 15, in <module numba.core.config>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\llvmlite\binding\__init__.py", line 4, in <module llvmlite.binding>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\llvmlite\binding\dylib.py", line 3, in <module llvmlite.binding.dylib>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\llvmlite\binding\ffi.py", line 195, in <module llvmlite.binding.ffi>
OSError: Could not load shared object file: llvmlite.dll
Errors were: [FileNotFoundError("Could not find module 'D:\\MAIN~1.DIS\\llvmlite\\binding\\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'D:\\main.dist\\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'D:\\_DEV]
```

Solved this by manually copying llvmlite directory from site-packages to the dist dir.
When i run again the exe after the fix i obtain this:

```
Traceback (most recent call last):
  File "D:\MAIN~1.DIS\main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\pmlearn\learn\trainer.py", line 17, in <module pmlearn.learn.trainer>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\xgboost\__init__.py", line 9, in <module xgboost>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\MAIN~1.DIS\xgboost\core.py", line 188, in <module xgboost.core>
  File "D:\MAIN~1.DIS\xgboost\core.py", line 141, in _load_lib
  File "D:\MAIN~1.DIS\xgboost\libpath.py", line 64, in find_lib_path
xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path.  List of candidates:
- D:\MAIN~1.DIS\xgboost\lib\xgboost.dll
- D:\MAIN~1.DIS\xgboost\..\..\lib\xgboost.dll
- D:\MAIN~1.DIS\lib\xgboost.dll
- D:\MAIN~1.DIS\xgboost\../../windows/x64/Release/xgboost.dll
- D:\MAIN~1.DIS\xgboost\./windows/x64/Release/xgboost.dll
XGBoost Python package path: D:\MAIN~1.DIS\xgboost
See: https://xgboost.readthedocs.io/en/latest/build.html for installing XGBoost.
```
Solved also this by manually copying xgboost dir from site-package to the dist dir. XGBoost need also the VERSION file to work.

**EDIT**:
With this hot fix everithings works but when the program exits i obtain this error:
```
Exception ignored in: <compiled_function Booster.__del__ at 0x0000019021E11D60>
Traceback (most recent call last):
  File "D:\MAIN~1.DIS\xgboost\core.py", line 1468, in __del__
AttributeError: 'NoneType' object has no attribute 'XGBoosterFree'
```

**Comment by interseba5** [comment]
No idea yet?

**Comment by kayhayen** [comment]
@interseba5 I do not appreciate this kind of noise only comment

I have added the required DLL dependency and the data file on factory branch, with that `import xgboost` was working.

**Comment by kayhayen** [comment]
Release as part of 0.9.3.
