### ISSUE TITLE
Networkx TypeError

### ISSUE THREAD

**Issue by paddy-r** [Nuitka/Nuitka#1649]
* Nuitka version, full Python version, flavor, OS, etc.:

```
0.9.2
Commercial: None
Python: 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\***\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

Installed ```nuitka``` via ```pip``` into a ```conda``` environment.

* The specific PyPI names and versions

```
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1655215393654/work
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

Minimal code is below.

```
import networkx as nx
g = nx.DiGraph()
print('Hiyer!')
```

Output (captured via ```nx_tester.exe > nx_tester.txt && type nx_tester.txt```) below. I've removed some file and path info.

```
Traceback (most recent call last):
  File "C:\***\nx_tester.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\***\lib\site-packages\networkx\__init__.py", line 59, in <module networkx>
    from networkx import utils
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\***\lib\site-packages\networkx\utils\__init__.py", line 3, in <module networkx.utils>
    from networkx.utils.random_sequence import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\***\lib\site-packages\networkx\utils\random_sequence.py", line 24, in <module networkx.utils.random_sequence>
    @py_random_state(2)
  File "C:\***\lib\site-packages\networkx\utils\decorators.py", line 850, in __call__
    func.__defaults__ = f.__defaults__
TypeError: Nuitka doesn't support __defaults__ size changes
```

* Provide in your issue the Nuitka options used

```
python -m nuitka --follow-imports nx_tester.py
```

**Comment by kayhayen** [comment]
This seems another case of function copying, that hopefully can be avoided with a source modification in `anti-bloat` mechanism too.

**Comment by kayhayen** [comment]
I am doing the anti-bloat work here first, seems a big compilation, that somehow pulls in `unittest` and we cannot have that happen, can we.

**Comment by kayhayen** [comment]
Part of the 1.0.1 release that is immanent.
