### ISSUE TITLE
Implicit import of _socket not working after Nuitka 0.7.7

### ISSUE THREAD

**Issue by ralienpp** [Nuitka/Nuitka#1650]
I ask for some tips in finding the root cause of a problem. Here is my environment:

```
$ /opt/devpy39/bin/python3.9 -m nuitka --version
0.9.2
Commercial: None
Python: 3.9.6 (default, Oct 26 2021, 13:46:24) 
Flavor: Unknown
Executable: /opt/devpy39/bin/python3.9
OS: Linux
Arch: x86_64
Distribution: Linuxmint (based on Ubuntu) 20.3
```

- Nuitka was installed with `pip`.
- The Python executable in that directory is compiled from source, and has some additional modules installed to it via `pip`, from a [requirements.txt](https://github.com/Nuitka/Nuitka/files/9029544/requirements.txt) file.

Here's my code:

```
import asyncio

async def main():
    print('Hello ...')
    await asyncio.sleep(1)
    print('... World!')

if __name__ == '__main__':
    asyncio.run(main())
```

I compile it with `/opt/devpy39/bin/python3.9 -m nuitka --follow-imports  nuitkasocketonly.py`, and the process is finished without errors.

However, when I run the program, I get this:

```
./nuitkasocketonly.bin
Traceback (most recent call last):
  File "nuitkasocketonly.py", line 1, in <module>
    import asyncio
  File "/opt/devpy39/lib/python3.9/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/opt/devpy39/lib/python3.9/asyncio/base_events.py", line 23, in <module>
    import socket
  File "/opt/devpy39/lib/python3.9/socket.py", line 51, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
```

The error persists even if I explicitly add `import socket` or even `import _socket` to the top of my code. I also tried it with `plugin-enable=implicit-imports` (Nuitka tells me that this plugin is always enabled, so this didn't have any effect, because `_socket` is [already imported](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/plugins/standard/ImplicitImports.py#L235) along with `socket`).

I've tried the previous versions, going back from 0.9.2, and the issue goes away at Nuitka 0.7.7. However, I didn't see anything obviously related to this between 0.7.7 and now in the changelog.

The strange part is that if I compile a clean Python 3.9.6, install it to another directory, then install the same dependencies - the produced binary works well, even with Nuitka 0.9.2. It is clear that the culprit is somewhere in my environment, but I was so far unable to identify which piece of the puzzle is responsible for the error.

I was wondering whether this issue follows some pattern, maybe something similar has occurred in the past, and I can leverage that experience to focus on some specific part of my development environment to find the cause.

**Comment by kayhayen** [comment]
What is a built-in module gets decided at compile time, various Python distributions have differences there.

Mind you however, that accelerated mode never includes extension modules, so it shouldn't matter at all.

**Comment by kayhayen** [comment]
Can you please use `--report=out.xml` in the failing Python, that could reveal something.

In my self-compiled Python, that has it external, it just works. The Debian Python has this built-in, so no problem feasible there.

**Comment by ralienpp** [comment]
This is what the output looks like:

```
<nuitka-compilation-report>
  <module name="__main__" kind="PythonMainModule" reason="Root module" />
  <module name="site" kind="UncompiledPythonModule" reason="Instructed by user to follow all modules, including non-automatic standard library modules." />
  <search_path dirs="/home/alex/projects/nuitkatest:/opt/devpy39/lib/python3.9:/opt/devpy39/lib/python3.9/lib-dynload:/opt/devpy39/lib/python3.9/site-packages" />
</nuitka-compilation-report>

```

**Comment by kayhayen** [comment]
And you do run this on the machine where it was compiled?

**Comment by ralienpp** [comment]
Yes, the action happens on the same computer.

**Comment by kayhayen** [comment]
Very interesting, the `site` module might be doing stupid stuff in our case. Can you add a `print(sys.path)` at the top of your script, and provide the output, I suspect that `site` module reacts badly somehow.

**Comment by ralienpp** [comment]
Here are the paths for the working binary:

```
['/home/alex/projects/nuitkatest', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9',
'/usr/local/lib/python3.9/lib-dynload', '/home/alex/projects/nuitkatest/venv39/lib/python3.9/site-packages']
```

And the associated report

```
<nuitka-compilation-report>
  <module name="__main__" kind="PythonMainModule" reason="Root module" />
  <module name="_virtualenv" kind="CompiledPythonModule" reason="Instructed by user to follow to all non-standard library modules." />
  <module name="site" kind="UncompiledPythonModule" reason="Instructed by user to follow all modules, including non-automatic standard library modules." />
  <search_path dirs="/home/alex/projects/nuitkatest:/usr/local/lib/python3.9:/usr/local/lib/python3.9/lib-dynload:/home/alex/projects/nuitkatest/venv39/lib/python3.9/site-packages" />
</nuitka-compilation-report>
```


Here are the paths for the failing attempt:
```
['/home/alex/projects/nuitkatest', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9',
'/usr/lib/python3.9/lib-dynload', '/home/alex/projects/nuitkatest/venv39/lib/python3.9/site-packages']
```
I was surprised to see `venv39` in the list (the last element). I thought maybe it is because nuitka is reusing the data in `nuitkasocketonly.build` - after removing this directory and compiling again, the output is:

```
['/home/alex/projects/nuitkatest', '/opt/devpy39/lib/python39.zip', '/opt/devpy39/lib/python3.9',
'/usr/lib/python3.9/lib-dynload', '/opt/devpy39/lib/python3.9/site-packages']
```

And the report

```
<nuitka-compilation-report>
  <module name="__main__" kind="PythonMainModule" reason="Root module" />
  <module name="site" kind="UncompiledPythonModule" reason="Instructed by user to follow all modules, including non-automatic standard library modules." />
  <search_path dirs="/home/alex/projects/nuitkatest:/opt/devpy39/lib/python3.9:/opt/devpy39/lib/python3.9/lib-dynload:/opt/devpy39/lib/python3.9/site-packages" />
</nuitka-compilation-report>
```

**Comment by kayhayen** [comment]
That caching bug is interesting as well, that should not happen, I will have to look into that as well.

However, the `virtualenv` must be active when the compiled binary is run, or else it will not find it. I understand however, that in your case, in the non-working environment, it's not there.

Once thing that came to my mind just now, is that you ought to use `--python-flag=-v` when compiling. I do not need traces of the working case, but only the non-working case, it's actually more confusing to me otherwise. With that, we should see traces at runtime, where it attempts to import `socket` and then `_socket` and see what Nuitka meta path based loader states about it.

**Comment by ralienpp** [comment]
> I understand however, that in your case, in the non-working environment, it's not there.

Hmm, now I get it - the environment was indeed not activated. I mistakenly thought that calling the right python interpreter directly would suffice. However, the environment I'm using is indeed requiring me to activate a virtualenv first. If I do that - it works.

This is the output you've requested: [execution-output.txt](https://github.com/Nuitka/Nuitka/files/9053257/execution-output.txt), however - I have to say this was a false alarm, I missed one of the steps in the recipe.

**Comment by kayhayen** [comment]
The accelerated binary potentially ought to check if the environment changes, or enforce the compile time environment, then this error of course would be avoided.
