### ISSUE TITLE
Match case with pipe shows duplicate node usage during code generation

### ISSUE THREAD

**Issue by black-snow** [Nuitka/Nuitka#1655]
match-case with `|` ought to be fixed with https://github.com/Nuitka/Nuitka/issues/1507 but it seems to be broken on RC4 of 1.0 again.

```
1.0rc4
Commercial: None
Python: 3.10.5 (main, Jun 23 2022, 10:42:52) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11
```

```python
match some_var:
    case 'a':
        print('x')
    case 'b':
        print('x')
```

works,

```python
match some_var:
    case 'a' | 'b':
        print('x')
```

results in something like:

```
[...]
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
C Source Generation: 0.0%|                         | 0/115, __main__Problem with <Node 'EXPRESSION_TEMP_VARIABLE_REF' with {'temp_name': 'match_statement_1__subject', 'owner': '__main__'}> at main.py:312
Problem with <Node 'EXPRESSION_COMPARISON_EQ'> at main.py:312
Problem with <Node 'EXPRESSION_CONDITIONAL_OR'> at main.py:312
Problem with <Node 'STATEMENT_CONDITIONAL'> at main.py:312
Problem with <Node 'STATEMENT_TRY' with {'aborting': False}> at main.py:312
Traceback (most recent call last):
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/__main__.py", line 138, in <module>
    main()
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/MainControl.py", line 944, in main
    result, options = compileTree()
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/MainControl.py", line 806, in compileTree
    makeSourceDirectory()
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/MainControl.py", line 402, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeGeneration.py", line 531, in generateModuleCode
    return _generateModuleCode(module=module, data_filename=data_filename)
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeGeneration.py", line 518, in _generateModuleCode
    return getModuleCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/ModuleCodes.py", line 75, in getModuleCode
    generateStatementSequenceCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 250, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 234, in _generateStatementSequenceCode
    generateStatementsFrameCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/FrameCodes.py", line 127, in generateStatementsFrameCode
    _generateStatementSequenceCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 239, in _generateStatementSequenceCode
    generateStatementCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 199, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/TryCodes.py", line 86, in generateTryCode
    generateStatementSequenceCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 250, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 239, in _generateStatementSequenceCode
    generateStatementCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 199, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/BranchCodes.py", line 43, in generateBranchCode
    generateConditionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/ConditionalCodes.py", line 39, in generateConditionCode
    generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 56, in generateExpressionCode
    _generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 103, in _generateExpressionCode
    code_generator(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/ConditionalCodes.py", line 117, in generateConditionalAndOrCode
    generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 56, in generateExpressionCode
    _generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 103, in _generateExpressionCode
    code_generator(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/ComparisonCodes.py", line 174, in generateComparisonExpressionCode
    generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 56, in generateExpressionCode
    _generateExpressionCode(
  File "/workspaces/xxx-cli/__pypackages__/3.10/lib/nuitka/codegen/CodeHelpers.py", line 84, in _generateExpressionCode
    assert not hasattr(expression, "code_generated"), expression
AssertionError: <Node 'EXPRESSION_TEMP_VARIABLE_REF' with {'temp_name': 'match_statement_1__subject', 'owner': '__main__'}>
```

Where line `312` in `main.py` is the line containing `match`.

**Comment by kayhayen** [comment]
Part of the 0.9.3 release I made a while ago.
