### ISSUE TITLE
the compatibility with opencv

### ISSUE THREAD

**Issue by statfs** [Nuitka/Nuitka#1661]
Usually we have two method to install opencv:
- pip install opencv-python (or pip install opencv-contrib)
- conda install -c conda-forge opencv

Firstly, I use pip to install opencv, and use a script to pass the test, then Nuitka it to a package. this error occur to me:
```
pip install opencv-python
python -m nuitka --standalone --show-progress --show-memory  --onefile --show-scons test.py
```

```
#test.py
import cv2
print(cv2.__version__)
```

> Nuitka-Inclusion:WARNING: Conflicting DLLs for 'libcrypto.1.1.dylib' in your installation, newest file version used, hoping for the best.
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libcrypto.1.1.dylib'.
/opt/miniconda3/envs/py37/lib/libcrypto.1.1.dylib used by:
   test.dist/_hashlib.so
   test.dist/_ssl.so
different from
Nuitka-Inclusion:WARNING: /opt/miniconda3/envs/py37/lib/python3.7/site-packages/cv2/.dylibs/libcrypto.1.1.dylib used by
   test.dist/cv2/cv2.so
Nuitka-Inclusion:WARNING: Conflicting DLLs for 'liblzma.5.dylib' in your installation, newest file version used, hoping for the best.
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'liblzma.5.dylib'.
/opt/miniconda3/envs/py37/lib/liblzma.5.dylib used by:
   test.dist/_lzma.so
different from
Nuitka-Inclusion:WARNING: /opt/miniconda3/envs/py37/lib/python3.7/site-packages/cv2/.dylibs/liblzma.5.dylib used by
   test.dist/cv2/cv2.so
Nuitka-Inclusion:WARNING: Conflicting DLLs for 'libssl.1.1.dylib' in your installation, newest file version used, hoping for the best.
Nuitka-Inclusion:WARNING: Ignoring non-identical DLLs for 'libssl.1.1.dylib'.
/opt/miniconda3/envs/py37/lib/libssl.1.1.dylib used by:
   test.dist/_ssl.so
different from
Nuitka-Inclusion:WARNING: /opt/miniconda3/envs/py37/lib/python3.7/site-packages/cv2/.dylibs/libssl.1.1.dylib used by
   test.dist/cv2/cv2.so
FATAL: Error, problem with dependency scan of 'test.dist/libavcodec.58.134.100.dylib' with '@loader_path/liblzma.5.dylib' please report the bug.

PS: It works on windows, but fail on Mac.

using factory branch (python setup.py install):
> 1.0rc4
Commercial: None
Python: 3.7.13 (default, Mar 28 2022, 07:24:34) 
Flavor: Anaconda Python
Executable: /opt/miniconda3/envs/py37/bin/python
OS: Darwin
Arch: x86_64

Secondly, I use conda to install opencv
```
conda env -n c37 python=3.7
#using same command and script like above
```

> ERROR1:
FATAL: anti-bloat: Error, cannot evaluate code 'textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')' in 'import textwrap
import pkgutil
from nuitka.utils.Importing import getSharedLibrarySuffix' due to: [Errno 2] No such file or directory: '/opt/miniconda3/envs/c37/lib/python3.7/site-packages/cv2/config-3.py'

then I manually execute command below to go on.
```
ln -s  /opt/miniconda3/envs/c37/lib/python3.7/site-packages/cv2/config-3.7.py /opt/miniconda3/envs/c37/lib/python3.7/site-packages/cv2/config-3.py
```

>ERROR2:
C Source Generation: 56.2%|██████████████           | 50/89, numpy.lib.arraysetopsProblem with <Node 'EXPRESSION_COMPARISON_LT'> at /opt/miniconda3/envs/c37/lib/python3.7/site-packages/numpy/lib/arraysetops.py:561
Problem with <Node 'EXPRESSION_CONDITIONAL_OR'> at /opt/miniconda3/envs/c37/lib/python3.7/site-packages/numpy/lib/arraysetops.py:561
Problem with <Node 'STATEMENT_CONDITIONAL'> at /opt/miniconda3/envs/c37/lib/python3.7/site-packages/numpy/lib/arraysetops.py:561
Problem with <Node 'STATEMENT_TRY' with {'aborting': True}> at /opt/miniconda3/envs/c37/lib/python3.7/site-packages/numpy/lib/arraysetops.py:484
Nuitka:WARNING: Problem creating function code 'numpy$lib$arraysetops$$$function__12_in1d'.
C Source Generation: 56.2%|██████████████           | 50/89, numpy.lib.arraysetopsTraceback (most recent call last):
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/__main__.py", line 138, in <module>
    main()
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/MainControl.py", line 944, in main
    result, options = compileTree()
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/MainControl.py", line 806, in compileTree
    makeSourceDirectory()
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/MainControl.py", line 404, in makeSourceDirectory
    data_filename=os.path.basename(c_filename[:-2] + ".const"),
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeGeneration.py", line 532, in generateModuleCode
    return _generateModuleCode(module=module, data_filename=data_filename)
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeGeneration.py", line 493, in _generateModuleCode
    function_body=function_body, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeGeneration.py", line 448, in generateFunctionBodyCode
    cross_module=function_body.isCrossModuleUsed()
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/FunctionCodes.py", line 611, in getFunctionCode
    needs_exception_exit=needs_exception_exit,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/FunctionCodes.py", line 647, in _getFunctionCode
    context=context,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 251, in generateStatementSequenceCode
    statement_sequence=statement_sequence, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 240, in _generateStatementSequenceCode
    statement=statement, emit=statement_emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 200, in generateStatementCode
    statement=statement, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/TryCodes.py", line 87, in generateTryCode
    statement_sequence=tried_block, emit=emit, allow_none=False, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 251, in generateStatementSequenceCode
    statement_sequence=statement_sequence, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 235, in _generateStatementSequenceCode
    statement_sequence=statement, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/FrameCodes.py", line 128, in generateStatementsFrameCode
    statement_sequence=statement_sequence, emit=local_emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 240, in _generateStatementSequenceCode
    statement=statement, emit=statement_emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 200, in generateStatementCode
    statement=statement, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/BranchCodes.py", line 44, in generateBranchCode
    condition=statement.subnode_condition, emit=condition_emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/ConditionalCodes.py", line 40, in generateConditionCode
    to_name=compare_name, expression=condition, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 61, in generateExpressionCode
    allow_none=allow_none,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 104, in _generateExpressionCode
    to_name=to_name, expression=expression, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/ConditionalCodes.py", line 76, in generateConditionalAndOrCode
    to_name=left_name, expression=left_value, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 61, in generateExpressionCode
    allow_none=allow_none,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelpers.py", line 104, in _generateExpressionCode
    to_name=to_name, expression=expression, emit=emit, context=context
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/ComparisonCodes.py", line 353, in generateRichComparisonExpressionCode
    context=context,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/ComparisonCodes.py", line 180, in getRichComparisonCode
    right_c_type=right_c_type,
  File "/opt/miniconda3/envs/c37/lib/python3.7/site-packages/Nuitka-1.0rc4-py3.7-macosx-10.9-x86_64.egg/nuitka/codegen/CodeHelperSelection.py", line 57, in selectCodeHelper
    if Options.is_report_missing and (
NameError: name 'Options' is not defined

It seems that missing " from nuitka import Options",  I decide to rollback to 0.9.3, then the build of the executable package success. but the execution failed. 

>ERROR3: ./test.bin
Traceback (most recent call last):
  File "/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/test.py", line 1, in <module>
    import cv2
  File "/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/cv2/__init__.py", line 188, in <module cv2>
  File "/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/cv2/__init__.py", line 160, in bootstrap
  File "/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/imp.py", line 342, in load_dynamic
ImportError: dlopen(/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/cv2/cv2.so, 0x0002): tried: '/var/folders/rx/gg7gc62j7zq0kdhs71xfrn680000gp/T//onefile_37205_1657189219_921944/cv2/cv2.so' (no such file)

then I stop here to find any help.

**Comment by Josh596** [comment]
Hey,
Have you tried the develop branch, after installing the develop branch yesterday, I was able to get past `FATAL: Error, problem with dependency scan of 'test.dist/libavcodec.58.134.100.dylib' with '@loader_path/liblzma.5.dylib' please report the bug.`

**Comment by kayhayen** [comment]
This is a report against a develop bug that has already been fixed, but no issue template no fun anyway.

**Comment by statfs** [comment]
> This is a report against a develop bug that has already been fixed, but no issue template no fun anyway.

this error happened at nuitka 0.9.3, this version cannot work properly with opencv.

**Comment by statfs** [comment]
and still appear at nuitka 0.9.4

**Comment by lchunleo** [comment]
is the fix already in for creation of standalone for application that uses opencv?

**Comment by kayhayen** [comment]
yes
