### ISSUE TITLE
Feature Request: Support `--hidden-Import` like PyInstaller implementation.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#1667]
I noticed there are many issue about using `--include-module|package` option.
the behavior of these options are not as what user expected.
`--hidden-import` should include and follow imports even if unused module.

###### _ignored issue template bcz this is not bug report._

**Comment by Maxwell175** [comment]
@byehack Please include a minimal code sample that demonstrates what you would like to happen.

**Comment by kayhayen** [comment]
It does what it is supposed to do, no (competent) issues have been reported with it.

**Comment by byehack** [comment]
@Maxwell175 @kayhayen 
https://github.com/Nuitka/Nuitka/issues/1663 https://github.com/Nuitka/Nuitka/issues/1463 https://github.com/Nuitka/Nuitka/issues/1526 https://github.com/Nuitka/Nuitka/issues/1446 https://github.com/Nuitka/Nuitka/issues/1185 https://github.com/Nuitka/Nuitka/issues/1256
https://github.com/Nuitka/Nuitka/issues/1112 https://github.com/Nuitka/Nuitka/issues/1084 https://github.com/Nuitka/Nuitka/issues/757 https://github.com/Nuitka/Nuitka/issues/1595

**Comment by byehack** [comment]
here is part of code:
```python3
import base64
x = 'aW1wb3J0IGRpc3R1dGlscy5jb21tYW5kLmJkaXN0X3JwbQ=='  # decode: import distutils.command.bdist_rpm
exec(base64.b64decode(x))
print(1)
```
try to `nuitka --standalone --mingw64 --include-module=distutils.command.bdist_rpm xwz.py` but it doesn't works:

```
C:\nuitkatest>c:\python37x86\python -m nuitka --mingw64 --standalone --include-module=distutils.command.bdist_rpm xwz.py

Nuitka-Options:INFO: Used command line options: --mingw64 --standalone --include-module=distutils.command.bdist_rpm xwz.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python
Nuitka:WARNING: compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '0.9.3' on Python '3.7' commercial grade 'not installed'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib.request' added 'http.client,http.cookiejar'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'shelve' added 'dbm.dumb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'concurrent.futures.process' added 'multiprocessing,multiprocessing.connection'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module '_asyncio' added 'asyncio'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'quopri' added 'py_compile'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:WARNING: Did not follow import to unused 'distutils.command.bdist_rpm', consider include options.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 12 modules (no progress information available).
lto-wrapper.exe: warning: using serial compilation of 4 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information

Nuitka-Scons:INFO: Compiled 28 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 10
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka:INFO: Keeping build directory 'xwz.build'.
Nuitka:INFO: Successfully created 'xwz.dist\\xwz.exe'.


C:\nuitkatest>xwz.dist\xwz.exe
Traceback (most recent call last):
  File "C:\Users\Tester\Desktop\NUITKA~1\XWZ~1.DIS\xwz.py", line 3, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'

```
