### ISSUE TITLE
Data files for pyqtgraph are not included automatically, causing ZeroDivisionError for missing icons

### ISSUE THREAD

**Issue by ljzecg** [Nuitka/Nuitka#1671]
Simplest Example Code:

```
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import sys
import pyqtgraph as pg


class W(QWidget):
    def __init__(self):
        super().__init__()

        pg.PlotWidget()


def main():
    app = QApplication(sys.argv)
    w = W()
    w.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()

```

1.First Try
nuitka scripy:
`python -m nuitka .\main.py --standalone --enable-plugin=pyqt5 --enable-plugin=numpy`

When executing main.exe, it says:
```
Traceback (most recent call last):
  File "...\MAIN~1.DIS\main.py", line 30, in <module>
  File "...\MAIN~1.DIS\main.py", line 20, in main
  File "...\MAIN~1.DIS\main.py", line 13, in __init__
  File "...\MAIN~1.DIS\pyqtgraph\widgets\PlotWidget.py", line 55, in __init__
  File "...\MAIN~1.DIS\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 121, in __init__
  File "...\MAIN~1.DIS\pyqtgraph\graphicsItems\ButtonItem.py", line 19, in __init__
ZeroDivisionError: float division by zero
```

2.Second Try
nuitka scripy:
`python -m nuitka .\main.py --standalone --enable-plugin=pyqt5 --enable-plugin=numpy --nofollow-import-to=pyqtgraph`

Then I copy the entire folder "pyqtgraph" and "numpy" into "main.dest"
It says:
```
Traceback (most recent call last):
  File "...\MAIN~1.DIS\main.py", line 6, in <module>
  File "...\main.dist\pyqtgraph\__init__.py", line 17, in <module>
    from .colors import palette
  File "...\main.dist\pyqtgraph\colors\palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "...\main.dist\pyqtgraph\Qt\__init__.py", line 167, in <module>
    from PyQt5 import uic
ImportError: cannot import name 'uic' from 'PyQt5' (...\MAIN~1.DIS\PyQt5\__init__.py)
```

How to deal with pyqtgraph?
My python env is:
```
Nuitka==0.9.4
numpy==1.21.6
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyqtgraph==0.12.4
```

**Comment by kayhayen** [comment]
Your second try is non-sense, and not supported.

First try almost looks like a datafile was missing. Not currently aware of any for pyqtgraph data files, but that might be what is happening there.

**Comment by kayhayen** [comment]
Ok, in the example I used there is this:

``# nuitka-project: --include-package-data=pyqtgraph`

The treacherous thing that Qt does is for images that fail to load, create a 0,0 dimensions image, that then leads to `ZeroDivisionError` for anything that wants to do math with it.

**Comment by ljzecg** [comment]
> Ok, in the example I used there is this:
> 
> `# nuitka-project: --include-package-data=pyqtgraph`
> 
> The treacherous thing that Qt does is for images that fail to load, create a 0,0 dimensions image, that then leads to `ZeroDivisionError` for anything that wants to do math with it.

That works! Thanks a lot.

**Comment by kayhayen** [comment]
On factory, this is now automatic. I noticed that `examples` are included, use the `--noinclude-data-files` option accordingly, these are definitely useless or use: https://nuitka.net/doc/factory.html

**Comment by ljzecg** [comment]
A follow up issue.

After adding just TWO lines of code to the example code above (the last two lines in function __init__ of class W), a new error has arisen.
```
Traceback (most recent call last):
  File "...\A0779~1.DIS\a.py", line 39, in <module>
  File "...\A0779~1.DIS\a.py", line 30, in main
  File "...\A0779~1.DIS\a.py", line 23, in __init__
  File "...\A0779~1.DIS\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 322, in setAxisItems
  File "...\A0779~1.DIS\pyqtgraph\graphicsItems\AxisItem.py", line 588, in unlinkFromView
TypeError: 'compiled_method' object is not connected
```

```
class W(QWidget):
    def __init__(self):
        super().__init__()

        pw = pg.PlotWidget()

        ax = pg.AxisItem(orientation='bottom')
        pw.plotItem.setAxisItems({"bottom": ax})
```

I was wondering if it is the "pyqtgraph" problem or the "nuitka" issue?
Thanks.

**Comment by kayhayen** [comment]
@ljzecg there is nothing like a followup issue, create new one for new issue.

**Comment by kayhayen** [comment]
This is part of 1.0 release.
