### ISSUE TITLE
Nuitka standalone build fails to run when using pathlib with nested folders

### ISSUE THREAD

**Issue by Aspect1103** [Nuitka/Nuitka#1675]
So I've got a folder structure like this:
```
Root dir\
|    venv\
|    game\
|    |    resources\
|    |    |    wall.py
|    |    __init__.py
|    |    textures.py
|    |    window.py
|    requirements.txt
```

Inside of window.py, I have this code:
```py
from game.textures import temp
```
And textures.py:
```py
import pathlib
import arcade

wall_path = pathlib.Path(__file__).resolve().parent / "resources" / "textures" / "wall.png"

arcade.load_texture(wall_path)
```
When running the program without Nuitka, it executes correctly and loads the image, however, building the game with Nuitka using this CLI command:
`nuitka game/window.py --standalone --follow-imports --enable-plugin=numpy --include-data-dir=game/resources=resources`
I envounter this traceback:
```
Traceback (most recent call last):
  File "D:\Programming\Python\Procedurally Generated Dungeon Crawler - Copy\window.dist\window.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Programming\Python\Procedurally Generated Dungeon Crawler - Copy\window.dist\game\textures.py", line 7, in <module game.textures>
  File "D:\Programming\Python\Procedurally Generated Dungeon Crawler - Copy\window.dist\arcade\texture.py", line 504, in load_texture
  File "D:\Programming\Python\Procedurally Generated Dungeon Crawler - Copy\window.dist\arcade\resources\__init__.py", line 39, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : D:\Programming\Python\Procedurally Generated Dungeon Crawler - Copy\window.dist\game\resources\textures\wall.png
```
This is due to `window.py` importing `textures.py` using the absolute path `game.textures` and then `textures.py` getting the current dir and adding the path to the `wall.png` file. Is there any way to solve this with Nuitka?

Full Python and Nuitka version. It was installed via pip inside of my virtualenv using `pip install nuitka`:
```
0.9.4
Commercial: None
Python: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]        
Flavor: Unknown
Executable: D:\Programming\Python\Procedurally Generated Dungeon Crawler\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
Python packaages:
```
arcade==2.6.15
atomicwrites==1.4.1
attrs==21.4.0      
cffi==1.15.1       
cfgv==3.3.1        
colorama==0.4.5    
distlib==0.3.5     
filelock==3.7.1    
identify==2.5.1    
iniconfig==1.1.1   
nodeenv==1.7.0     
Nuitka==0.9.6      
numpy==1.23.1      
packaging==21.3
Pillow==9.1.1
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.20.0
py==1.11.0
pycparser==2.21
pyglet==2.0.dev18
pymunk==6.2.1
pyparsing==3.0.9
pytest==7.1.2
pytiled-parser==2.0.1
PyYAML==6.0
Shapely==1.8.2
six==1.16.0
toml==0.10.2
tomli==2.0.1
typing_extensions==4.3.0
virtualenv==20.15.1
```

**Comment by kayhayen** [comment]
Seems like a user error, you specify as target folder `resources`, yet expect the file to live in `game/resources`. Adapt your datafile option.
