### ISSUE TITLE
Failed run of standalone build after succesful binary build and execution

### ISSUE THREAD

**Issue by log2A** [Nuitka/Nuitka#1681]
Hello,

I am able to use Nuitka to Program compilation with all modules embedded and run the binary just fine. 

However, as I move to build a Program Distribution from the binary, the Program Distribution builds without error but fails as I go to execute the Program Distribution build. 

Below are environment details and stdout details for the failed execution run of the Program Distribution build. Appreciate any help as to why the Program Distribution may be failing. End goal is to move to the onefile distribution once Program Distribution (standalone) is working. Thank you.

0.9.6
Commercial: None
Python: 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)]
Flavor: Unknown
Executable: /private/tmp/binary_staging/logen_nuitka_env/bin/python
OS: Darwin
Arch: x86_64
running Nuitka-0.9.6 on macos 12.4 inside python3 venv

executed: python3 -m nuitka --follow-imports app_name
results:
Nuitka-Scons:INFO: Backend linking program with 192 modules (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka:INFO: Keeping build directory 'app_name.build'.
Nuitka:INFO: Successfully created 'app_name.bin'.

executed: ./app_name.bin and binary execution of app works

then executed: python3 -m nuitka --standalone app_name
results:
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka:INFO: Keeping build directory 'app_name.build'.                                        
Nuitka:INFO: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka:INFO: Successfully created 'app_name.dist/app_name'.

then executed: ./app_name.dist/app_name and failed results, for the reference to file not found, the file does exist and was writable during the succesful binary execution above:
Traceback (most recent call last):
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/app_name", line 14, in main
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/modules/gui/app_name_gui.py", line 61, in run
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/modules/common/app_name_log_handle.py", line 16, in log_handle
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/logging/handlers.py", line 155, in __init__
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/logging/handlers.py", line 58, in __init__
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/logging/__init__.py", line 1167, in __init__
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/logging/__init__.py", line 1197, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/resources/log/app_name-v1.0.0-alpha.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/tokenize.py", line 332, in find_cookie
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/app_name", line 26, in <module>
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/app_name", line 23, in main
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/traceback.py", line 135, in format_exception
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/traceback.py", line 502, in __init__
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/traceback.py", line 383, in extract
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/traceback.py", line 306, in line
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/linecache.py", line 30, in getline
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/linecache.py", line 46, in getlines
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/linecache.py", line 136, in updatecache
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/tokenize.py", line 396, in open
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/tokenize.py", line 373, in detect_encoding
  File "/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/tokenize.py", line 337, in find_cookie
SyntaxError: invalid or missing encoding declaration for '/private/tmp/binary_staging/app_name_nuitka_env/app_name/app_name/app_name.dist/app_name'

**Comment by kayhayen** [comment]
You got some code that that attemps to execute the main binary as if it was a script. It is not. Since you carefully avoided to provide sufficient information, I think this is far as I can help here.

**Comment by log2A** [comment]
Hi @kayhayen, thank your for the response. Pardon my ignorance can you elaborate on what you mean by code attempting to execute the main binary as if it was a script? 

Also, can you please let me know what additional information I should include to be sufficient information? Thank you.

**Comment by kayhayen** [comment]
Well, like a minimal reproducer of the issue, i.e. code or even only module names. I am assuming you don't care enough to do that, or don't want to, but then it's just a waste of time. Create a new issue, if you can provide the issue template information.
