### ISSUE TITLE
Nuitka, ModuleNotFoundError: No module named 'dateutil.easter'

### ISSUE THREAD

**Issue by oondrash** [Nuitka/Nuitka#1696]
**Build**: 
python3 get-hints.py app.py
python3 nuitka-hints.py app.py
./app.dist/app

**Environment**:
CentOS Stream 8
Python 3.6.9
amqp (5.1.1)
attrs (21.4.0)
backports.zoneinfo (0.2.1)
cached-property (1.5.2)
configobj (5.0.6)
dbus-python (1.2.4)
decorator (4.2.1)
Deprecated (1.2.13)
gpg (1.13.1)
html5lib (0.999999999)
importlib-metadata (4.8.3)
importlib-resources (5.4.0)
iniconfig (1.1.1)
isc (2.0)
kombu (5.1.0)
libcomps (0.1.16)
librabbitmq (2.0.0)
lxml (4.2.3)
MarkupSafe (0.23)
nftables (0.1)
Nuitka (0.6.12.2)
numpy (1.19.1)
ordered-set (4.0.2)
packaging (21.3)
pandas (1.1.0)
patsy (0.5.2)
perf (0.1)
pexpect (4.3.1)
pip (9.0.3)
pluggy (1.0.0)
ply (3.9)
psutil (5.4.3)
ptyprocess (0.5.2)
py (1.11.0)
pyasn1 (0.3.7)
pycairo (1.16.3)
pydbus (0.6.0)
pygobject (3.28.3)
pyparsing (3.0.9)
pytest (7.0.1)
python-dateutil  #(2.8.2)
python-linux-procfs (0.6.3)
pytz (2022.1)
pytz-deprecation-shim (0.1.0.post0)
pyudev (0.21.0)
PyYAML (3.12)
rpm (4.14.3)
schedutils (0.6)
scipy (1.5.4)
selinux (2.9)
sepolicy (1.1)
setools (4.3.0)
setroubleshoot (1.1)
setuptools (39.2.0)
six (1.11.0)
slip (0.6.4)
slip.dbus (0.6.4)
sos (4.1)
SSSDConfig (2.5.1)
statsmodels (0.12.2)
syspurpose (1.28.17)
systemd-python (234)
tomli (1.2.3)
typing-extensions (4.1.1)
tzdata (2022.1)
tzlocal (4.2)
urllib3 (1.26.10)
vine (5.0.0)
WALinuxAgent (2.2.49.2)
webencodings (0.5.1)
wincertstore (0.2)
wrapt (1.14.1)
zipp (3.6.0)

**Error**:
Traceback (most recent call last):
  File "/tmp/service/app.dist/pandas/__init__.py", line 30, in <module pandas>
  File "/tmp/service/app.dist/pandas/_libs/__init__.py", line 13, in <module pandas._libs>
  File "pandas/_libs/hashtable.pxd", line 8, in init pandas._libs.interval
  File "pandas/_libs/missing.pxd", line 11, in init pandas._libs.hashtable
  File "pandas/_libs/tslibs/nattype.pxd", line 9, in init pandas._libs.missing
  File "/tmp/service/app.dist/pandas/_libs/tslibs/__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas/_libs/tslibs/conversion.pyx", line 33, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pxd", line 7, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 17, in init pandas._libs.tslibs.offsets
ModuleNotFoundError: No module named 'dateutil.easter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/service/app.dist/app.py", line 9, in <module>
  File "/tmp/service/app.dist/tools/utils.py", line 12, in <module tools.utils>
  File "/tmp/service/app.dist/pandas/__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'dateutil.easter' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**Comment by kayhayen** [comment]
No issue template, no fun.
