### ISSUE TITLE
[HELP] OpenVino + Windows, ImportError when import ie_api.pyd

### ISSUE THREAD

**Issue by pardont** [Nuitka/Nuitka#1699]
1. install openvino:
 pip install openvino
 
2. create a file 'main.py', content is:
> from openvino.inference_engine import IECore
_ie = IECore()
print(_ie.available_devices[0])

output is: CPU

3. nuitka compile:
> python -m nuitka --standalone --enable-plugin=numpy main.py

4. run main.exe, FAILED:
> Traceback (most recent call last):
  File "D:\test\TEST_N~1\TEST_O~1\MAIN~1.DIS\main.py", line 9, in <module>
  File "D:\test\TEST_N~1\TEST_O~1\MAIN~1.DIS\openvino\inference_engine\__init__.py", line 30, in <module openvino.inference_engine>
ImportError

5. copy required files  to output folder:
C:\Users\zwp\AppData\Local\Programs\Python\Python38\Lib\site-packages\openvino\inference_engine\constants.pyd
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\site-packages\openvino\libs

6. Always FAILED:
> Traceback (most recent call last):
  File "D:\test\TEST_N~1\TEST_O~1\MAIN~1.DIS\main.py", line 9, in <module>
  File "D:\test\TEST_N~1\TEST_O~1\MAIN~1.DIS\openvino\inference_engine\__init__.py", line 30, in <module openvino.inference_engine>
ImportError

Environment:  python -m nuitka --version
> 0.9.6
Commercial: None
Python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\zwp\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

**Comment by kayhayen** [comment]
Manual copying is not supported and unlikely to work correctly. These will be hidden dependencies, that we need to define.

**Comment by kayhayen** [comment]
I was working my way through the hidden dependencies and adding data files, however it fails to run in the end. Enabling the plugin back then didn't cause `numpy` to be included, only to be handled if included. That dependency would have had to be specified manually. However, now it has hit a problem, in that rather than properly error exiting, it errors from the module load, but without an error. It seems it is crashing when `IECore()` is called.

**Comment by kayhayen** [comment]
So, applying an API monitor, I noticed it searches for ``plugins.xml`` in versioned paths, and top level. Moving it to top level of the dist folder helps it find it, and then of course the DLL paths are wrong, but changing it made things run. So that's great. Now I need to figure out why the PyPI package gets away with it being inside `.libs` near the DLLs and Nuitka standalone code does not.

**Comment by kayhayen** [comment]
Ok, deleting `openvino.dll` from top level dist folder, also solves this.

I believe when adding the DLLs, dependent DLLs go to the top level and not near the DLL using it, and the duplicate DLL is not even detected as a bad thing, when it gets added later. It of course should be only added in one spot, that by itself is another bug of Nuitka.

In this particular case, the DLL has to be near its data files, as it uses its own file path, so that is very much unwanted. We might have to revise how the DLL dependencies found for DLLs in folders are handled. I think they were put top level in an attempt to use that as the form of deduplication, to put them all there. It however should be easy to see that these DLLs are found near the inserted DLL, and therefore it should not be done that way.

This may require more thinking.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.1 that I just made.
