### ISSUE TITLE
AssertionError: ()

### ISSUE THREAD

**Issue by YangZhenxun** [Nuitka/Nuitka#1730]
My nuitka version:1.0.3
Commercial: None
Python: 3.11.0b5 (main, Jul 25 2022, 22:59:14) [MSC v.1932 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\86139\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
* Command
    nuitka --standalone  --show-progress --onefile --mingw64 --windows-disable-console --follow-imports --enable-plugin=numpy --enable-plugin=pyqt6 view.py

* Error
   Nuitka-Progress:INFO: Doing module dependency considerations for 'abc':
PASS 1: 99.9%|████████████████████████▉| 1718/1719, abcTraceback (most recent call last):
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 918, in main
    main_module = _createNodeTree(filename=filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 206, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\optimizations\Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\optimizations\Optimization.py", line 319, in makeOptimizationPass
    current_module.setChild("functions", used_functions)
 File "C:\Users\86139\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\nodes\NodeBases.py", line 603, in setChild
    assert old_value is not value, value
AssertionError: ()

**Comment by kayhayen** [comment]
Python 3.11 is not officially supported at this, and this would need a reproducer, may have nothing to do with 3.11 but hard to tell now.

**Comment by YepoMax** [comment]
> Python 3.11 is not officially supported at this, and this would need a reproducer, may have nothing to do with 3.11 but hard to tell now.

I have the **exact same error**. Works perfectly with Python 3.10 but get this error with Python 3.11
I tried without --onefile and got worse results.

I cannot wait for an update of nuitka supporting Python 3.11 as for the specific code I'm working on I get significant speed improvement using Python 3.11 !

Best of luck and thank you so much for your hard work :)
