### ISSUE TITLE
win32com : ImportError: DLL load failed while importing shell: The specified procedure could not be found

### ISSUE THREAD

**Issue by arcontechnologies** [Nuitka/Nuitka#1733]
Nuitka version :

```
1.0.4
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\albel\.conda\envs\robotenv\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

My command :

I would like to mention that I added some packages that seems not beeing detected by Nuitka and causing issues even after compilation. 

`nuitka robotscheduler.py --standalone --follow-imports  --enable-plugin=numpy --include-package=win32com --include-package=pywin32_system32 --include-package=spacy --include-package=fr_core_news_sm --include-package=thinc --windows-icon-from-ico=robot.png --include-package=preshed --include-data-dir=D:\robot\data=data --include-data-dir=D:\robot\emails_traites=emails_traites --include-data-dir=D:\robot\log=log --include-data-dir=D:\robot\model=model --include-data-dir=D:\robot\templates=templates --include-data-dir=D:\robot\libraries=libraries --include-data-files=D:\robot\robot.py=robot.py`

My error :

```
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.4' on Python '3.9' commercial grade 'not installed'.
PASS 1: 1.0%|▏                        | 10/1024, thinc.utilTraceback (most recent call last):
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\MainControl.py", line 918, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\MainControl.py", line 206, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\optimizations\Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\optimizations\Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\optimizations\Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\optimizations\Optimization.py", line 149, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\importing\Recursion.py", line 430, in considerUsedModules
    _addParentPackageUsages(
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\importing\Recursion.py", line 382, in _addParentPackageUsages
    used_package_module = recurseTo(
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\importing\Recursion.py", line 73, in recurseTo
    module, added_flag = _recurseTo(
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\importing\Recursion.py", line 42, in _recurseTo
    module, is_added = Building.buildModule(
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\tree\Building.py", line 1323, in buildModule
    module = _createModule(
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\tree\Building.py", line 1072, in _createModule
    and hasCachedImportedModulesNames(module_name, source_code)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\Caching.py", line 60, in hasCachedImportedModulesNames
    result = getCachedImportedModulesNames(module_name, source_code)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\Caching.py", line 71, in getCachedImportedModulesNames
    cache_filename = _getCacheFilename(cache_name, "json")
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\Caching.py", line 44, in _getCacheFilename
    return os.path.join(_getCacheDir(), "%s.%s" % (module_name, extension))
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\Caching.py", line 38, in _getCacheDir
    module_cache_dir = os.path.join(getCacheDir(), "module-cache")
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\utils\AppDirs.py", line 50, in getCacheDir
    _cache_dir = appdirs.user_cache_dir("Nuitka", None)
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\build\inline_copy\appdirs\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Users\albel\.conda\envs\robotenv\lib\site-packages\nuitka\build\inline_copy\appdirs\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.
```

installed python packages :

```
Package               Version
--------------------- ---------
blis                  0.7.8
catalogue             2.0.8
certifi               2022.6.15
charset-normalizer    2.1.0
click                 8.1.3
colorama              0.4.5
commonmark            0.9.1
cymem                 2.0.6
en-core-web-sm        3.4.0
fr-core-news-sm       3.4.0
idna                  3.3
Jinja2                3.1.2
joblib                1.1.0
keyboard              0.13.5
langcodes             3.3.0
MarkupSafe            2.1.1
murmurhash            1.0.8
Nuitka                1.0.4
numpy                 1.23.2
opencv-contrib-python 4.5.5.64
opencv-python         4.5.5.64
orderedset            2.0.3
packaging             21.3
pandas                1.4.3
pathy                 0.6.2
Pillow                9.2.0
pip                   22.2.2
preshed               3.0.6
pydantic              1.9.2
Pygments              2.13.0
PyMuPDF               1.20.2
pyparsing             3.0.9
pytesseract           0.3.9
python-dateutil       2.8.2
pytz                  2022.2.1
pywin32               302
pywin32-ctypes        0.2.0
requests              2.28.1
rich                  12.5.1
schedule              1.1.0
scikit-learn          1.1.2
scipy                 1.9.0
setuptools            65.0.0
six                   1.16.0
sklearn               0.0
smart-open            5.2.1
spacy                 3.4.1
spacy-legacy          3.0.9
spacy-loggers         1.0.3
srsly                 2.4.4
thinc                 8.1.0
threadpoolctl         3.1.0
tqdm                  4.64.0
typeguard             2.13.3
typer                 0.4.2
typing_extensions     4.3.0
urllib3               1.26.11
wasabi                0.10.1
wheel                 0.37.1
wincertstore          0.2 
```

**Comment by arcontechnologies** [comment]
It turned out that Nuitka is incompatible with Pywin32==304. So I downgraded it to 301 which seems not to trigger an issue.

**Comment by kayhayen** [comment]
I checked and 304 is working fine with factory version at least, but Anaconda and DLLs are often different, so I would expect that, on develop there is a fix for `win32ui` module.

Oh wait, the `appdirs` inline copy is crashing for you at compile time, never saw that, and also that code catches `ImportError` and tries something else...

**Comment by kayhayen** [comment]
So I have no clue why this happened on your side, maybe a delayed `ImportError` when actually using it, I might have to update the inline copy there, to see if they have improved on their side. I am also not sure, if it ought to use pywin32 when it has a good ctypes fallback.

**Comment by kayhayen** [comment]
ok, may still have to do something with Anaconda, that your pywin32 was broken, but I just changed the inline copy of appdirs to not use pywin32, but only ctypes, that should solve it.

**Comment by arcontechnologies** [comment]
@kayhayen Thanks to take this into account. I'm facing also another issue with spacy related packages. I'm wondering if I should use anaconda virtual env or setup a new one without using anaconda.

**Comment by kayhayen** [comment]
I think spacy is something I mean to get to, but didn't yet have the time to make my way through, but I think I will get there. Generally for DLLs anaconda is similar to this one: https://nuitka.net/info/debian-dist-packages.html but I hope to get that sorted out in the coming months, but basically they or upstreams do stuff to reuse DLLs from outside locations, but e.g. with shapely.geos I fixed this kind of thing recently, but I do not have a good vision. The goal is definitely for Anaconda to work too, but I have to admit, CPython comes always first.

**Comment by arcontechnologies** [comment]
@kayhayen thanks for your feedback

**Comment by kayhayen** [comment]
The appdirs change is on develop now and will be part of the next release 1.1 as I didn't quite think it is worth the risk to put it in a hotfix. I am closing it for lack of general relevance.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.

**Comment by AlbelTec** [comment]
Thanks a lot 👍  I'll test it again
