### ISSUE TITLE
Onefile: Scan for zstandard having Python could crash with OSError

### ISSUE THREAD

**Issue by Rajjco** [Nuitka/Nuitka#1735]
1.0.4
Commercial: None
Python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Xen3\PycharmProjects\payloadDumper\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10 (I'm actually on windows 11 pro x64) but 10 was reported.

`Traceback (most recent call last):
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\MainControl.py", line 979, in main
    packDistFolderToOnefile(dist_dir)
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 46, in packDistFolderToOnefile
    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 181, in packDistFolderToOnefileBootstrap
    compressor_python = getCompressorPython()
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 103, in getCompressorPython
    compressor_python = findInstalledPython(
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\utils\InstalledPythons.py", line 219, in findInstalledPython
    if candidate.checkUsability(
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\utils\InstalledPythons.py", line 74, in checkUsability
    output = check_output([self.python_exe, "-c", test_code])
  File "C:\Users\Xen3\PycharmProjects\payloadDumper\venv\lib\site-packages\nuitka\utils\Execution.py", line 123, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "c:\users\xen3\appdata\local\programs\python\python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\xen3\appdata\local\programs\python\python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 1920] The file cannot be accessed by the system
`

Installed Nuitka in project virtual environment folder.
commands: pip install nuitka
                    pip install ordered-set
                    pip install imageio

imageio==2.21.1
Nuitka==1.0.4
numpy==1.23.2
ordered-set==4.1.0
Pillow==9.2.0
protobuf==3.20.1

Nuitka Command:
nuitka --onefile --follow-imports --enable-plugin=tk-inter --windows-icon-from-ico=Resources\android.png --disable-console main.py

Keep getting OSError: [WinError 1920] The file cannot be accessed by the system when i try to use onefile mode.
No issues with standalone mode.

**Comment by kayhayen** [comment]
Ok, thanks for the report, it seems it is attempting to use a Python, that doesn't exist anymore, maybe manually deleted. I feel like I seen this before, but probably didn't act on it, going to be part of 1.0.5 hotfix, not sure though, when that will be released.

**Comment by kayhayen** [comment]
This should be fixed on https://nuitka.net/doc/factory.html

I think I recall attempts to discover unusable Pythons during scan, but there is plenty of things that can go wrong, this now catched the failed attempt. As a workaround install `zstandard` from PyPI near nuitka, then no scan is done and it will not hit the bug. Potentially the next thing it was going to tell you that you don't have it on any installed Python.

Regarding Windows release, I have observed that Python releases, that predate Windows releases will do this. I have seen Windows 10 reported as Windows 8, very bad. Might have to replace Python stdlib query there with something that asks Windows itself. Maybe a new Python would do it for you. I will investigate that separately.

**Comment by kayhayen** [comment]
Wait, that is also not supposed to happen, user installations of Python are supposed to work, like ever since, maybe you had both, and dependency walker got confused about that being in `%PATH%`. I changed that for 1.1 versions, maybe that will also address what happened to you there. What might have happened is that dependency analysis sometimes found system wide, sometimes user python.dll, and failed to copy both, since I do not just overwrite, because that is bug hiding. Only a theory, but I guess, there being a `C:\Program Files\Python310` before seems to indicate it might be true. 

That is probably rare, and hopefully works with next release out of the box.

**Comment by kayhayen** [comment]
@LinuxUserGD posting below unrelated issues is a surefire way to get ignored

**Comment by kayhayen** [comment]
Part of the 1.0.5 release.
