### ISSUE TITLE
Standalone: FileNotFoundError (execl)

### ISSUE THREAD

**Issue by LinuxUserGD** [Nuitka/Nuitka#1746]
Description:

Compiling Nuitka works with `--standalone` and `--onefile` mode but fails at runtime.

Nuitka Version:

```bash
1.1rc6
Commercial: None
Python: 3.10.6 (main, Aug 21 2022, 19:11:22) [GCC 13.0.0 20220612 (experimental)]
Flavor: Unknown
Executable: /usr/bin/python3.10
OS: Linux
Arch: x86_64
Distribution: Gentoo None
```

Install:

```bash
sudo python3.10 -m pip install git+https://github.com/Nuitka/Nuitka/
```

Dependencies:

```bash
appdirs==1.4.4
Jinja2==3.0.3
ordered-set==4.1.0
orderedset==2.0.3
pyyaml_env_tag==0.1
tqdm==4.62.3
zstandard==0.18.0
```

Hello World:

```bash
user@user ~ $ echo 'print("Hello World!")' > temp.py && sudo python3.10 -m nuitka --linux-onefile-icon=/usr/share/pixmaps/ --static-libpython=no --clang --onefile --quiet --remove-output temp.py && ./temp.bin
Hello World! 
```

Example:

```bash
wget 'https://raw.githubusercontent.com/Nuitka/Nuitka/develop/bin/nuitka3' -q -O nuitka3.py
```
Nuitka options:

```bash
sudo python3.10 -m nuitka --linux-onefile-icon=/usr/share/pixmaps/ --static-libpython=no --clang --standalone nuitka3.py
```

Error:
```bash
user@user ~ $ ./nuitka3.dist/nuitka3
Traceback (most recent call last):
  File "/home/user/nuitka3.dist/nuitka3.py", line 36, in <module>
    nuitka.__main__.main()
  File "/home/user/nuitka3.dist/nuitka/__main__.py", line 81, in main
  File "/home/user/nuitka3.dist/nuitka/utils/ReExecute.py", line 125, in reExecuteNuitka
  File "/home/user/nuitka3.dist/nuitka/utils/ReExecute.py", line 65, in callExecProcess
  File "/home/user/nuitka3.dist/os.py", line 542, in execl
FileNotFoundError: [Errno 2] No such file or directory
```

Afaik this is not a regression.

**Comment by kayhayen** [comment]
There is a test in `tests/reflected` that shows how to run it. Nuitka will reexecute itself if not ran in the proper environment, with correct flags, but without the source it will fail. At this time I do not plan to make Nuitka work as a standalone binary, because due to its nature, it must live within the installation it is compiling for.
