### ISSUE TITLE
NuitkaOptimizationError for distribution version attribute lookup in an exception block

### ISSUE THREAD

**Issue by vinayinvicible** [Nuitka/Nuitka#1754]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.0.5
Commercial: None
Python: 3.7.3 (default, Aug 24 2022, 17:04:32) 
Flavor: pyenv
Executable: /home/vinay/code/testing/compile/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.4

  If you are not providing the full output. The issue cannot be solved and will
  be considered `invalid`. It does more than you think, and we are adding more
  all the time. We do not want to left guessing or trying things out to
  reproduce your issue.

* How did you install Nuitka and Python

  > Installed Python using pyenv.
Installed Nuitka via pip.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
# main.py
import pkg_resources
try:
    pkg_version = pkg_resources.get_distribution('Nuitka').parsed_version
except Exception:
    pkg_version = None

print(pkg_version)
```

* Provide in your issue the Nuitka options used

  > python -m nuitka main.py
Nuitka-Options:INFO: Used command line options: main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.5' on Python '3.7' commercial grade 'not installed'.
PASS 1: 0.0%|                         | 0/1, __main__Problem with statement at main.py:2:
-> try:
Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'main.py', 'module_name': <ModuleName __main__>, 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/MainControl.py", line 918, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/MainControl.py", line 206, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 98, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 892, in computeModule
    CompiledPythonModule.computeModule(self)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 537, in computeModule
    trace_collection=self.trace_collection
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/vinay/code/testing/compile/.venv/lib/python3.7/site-packages/nuitka/nodes/TryNodes.py", line 154, in computeStatement
    statement,
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.
```
    <node is_temp="False" kind="StatementAssignmentVariableGeneric" line="3" owner="__main__" var_type="object" variable_name="pkg_version">
      <role name="source">
        <node attribute_name="parsed_version" kind="ExpressionAttributeLookup" line="3">
          <role name="expression">
            <node kind="ExpressionPkgResourcesDistributionValueRef" line="3" />
          </role>
        </node>
      </role>
    </node>
```

**Comment by kayhayen** [comment]
I am not sure why, but this one escaped my attention, but I believe it got fixed, 1.1 does not reproduce the error anymore, and I recall doing something for the attributes and annotating if they raise an exception. Might have been when I added `importlib.metadata.distribution` support.

What a pity, this is actually an excellent report.

**Comment by Jackiexiao** [comment]
I think it's not fixed yet? In my case, similar program still exist (ps: if I remove `PackageNotFoundError` import, it works well)

version
```
python -m nuitka --version                                                   
1.3.3
Commercial: None
Python: 3.8.3 (default, Jul  2 2020, 16:21:59) 
Flavor: Anaconda Python
Executable: /data1/xiaojianjin/anaconda3/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
Version C compiler: /usr/bin/gcc (gcc).
```
code for reproduce
```python
# python > 3.8
from importlib.metadata import PackageNotFoundError, version  # pragma: no cover

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = "frontend"
    __version__ = version(dist_name)
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"
finally:
    del version, PackageNotFoundError

```
**error log**
```
PASS 1: 98.9%|████████████████████████▋| 86/87, frontend    Problem with statement at /tmp/build-via-sdist-k_2pf00r/frontend-2.0.0b1.dev3+g2faab02.d20221228/build/lib/frontend/__init__.py:2:
-> from importlib.metadata import PackageNotFoundError, version  # pragma: no cover

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': '/tmp/build-via-sdist-k_2pf00r/frontend-2.0.0b1.dev3+g2faab02.d20221228/build/lib/frontend/__init__.py', 'module_name': <ModuleName frontend>, 'code_flags': ''}>'.
PASS 1: 98.9%|████████████████████████▋| 86/87, frontendTraceback (most recent call last):
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/__main__.py", line 151, in <module>
    main()
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/__main__.py", line 137, in main
    MainControl.main()
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/MainControl.py", line 915, in main
    main_module = _createNodeTree(filename=filename)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/MainControl.py", line 210, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/optimizations/Optimization.py", line 341, in optimizeModules
    finished = makeOptimizationPass()
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/optimizations/Optimization.py", line 297, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/optimizations/Optimization.py", line 188, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/optimizations/Optimization.py", line 99, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/nodes/ModuleNodes.py", line 550, in computeModule
    result = module_body.computeStatementsSequence(
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/nodes/StatementNodes.py", line 172, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/nodes/FrameNodes.py", line 184, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/optimizations/TraceCollections.py", line 684, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/tmp/build-env-f3x5cw4u/lib/python3.8/site-packages/nuitka/nodes/TryNodes.py", line 152, in computeStatement
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementAssignmentVariableHardValue" line="2" variable_name="version" is_temp="False" var_type="object" owner="frontend">
      <role name="source">
        <node kind="ExpressionImportlibMetadataVersionRef" line="2" />
      </role>
    </node>
```

**Comment by kayhayen** [comment]
@Jackiexiao posting below closed issues is a surefire way to get ignored, although I will admit this is one of the better ones, with my current factory version it doesn't reproduce, but that might be because of recent changes that generate these kinds of nodes, and they might have fixed it on the side.
