### ISSUE TITLE
No module named 'reportlab.graphics.barcode.code128'

### ISSUE THREAD

**Issue by n0trace** [Nuitka/Nuitka#1758]
root@4013d10d9343:~/xhtml2pdf# python3 -v
Python 3.8.13 (default, Aug 23 2022, 09:35:56) 
[GCC 10.2.1 20210110] on linux

root@4013d10d9343:~/xhtml2pdf# nuitka3 --version
1.0.5
Commercial: None
Python: 3.8.13 (default, Aug 23 2022, 09:35:56) 
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11

Traceback (most recent call last):
  File "/tmp/onefile_5193_1661506203_134981/pisa.py", line 18, in <module>
    import xhtml2pdf.pisa as pisa
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/pisa.py", line 26, in <module xhtml2pdf.pisa>
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/document.py", line 26, in <module xhtml2pdf.document>
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/context.py", line 34, in <module xhtml2pdf.context>
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/parser.py", line 32, in <module xhtml2pdf.parser>
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/tables.py", line 21, in <module xhtml2pdf.tables>
  File "/tmp/onefile_5193_1661506203_134981/xhtml2pdf/tags.py", line 26, in <module xhtml2pdf.tags>
  File "/tmp/onefile_5193_1661506203_134981/reportlab/graphics/barcode/__init__.py", line 76, in <module reportlab.graphics.barcode>
  File "/tmp/onefile_5193_1661506203_134981/reportlab/graphics/barcode/__init__.py", line 42, in _reset
  File "/tmp/onefile_5193_1661506203_134981/reportlab/graphics/barcode/widgets.py", line 173, in <module reportlab.graphics.barcode.widgets>
  File "/tmp/onefile_5193_1661506203_134981/reportlab/graphics/barcode/widgets.py", line 100, in _BCW
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'reportlab.graphics.barcode.code128'

**Comment by kayhayen** [comment]
No reproducer given, means nothing I can do.

**Comment by n0trace** [comment]
nuitka3 --onefile --standalone --plugin-enable=numpy pisa.py

**Comment by kayhayen** [comment]
I am getting file not found for `pisa.py``  with that. ;-)

**Comment by n0trace** [comment]
pisa.py on https://github.com/xhtml2pdf/xhtml2pdf root

**Comment by kayhayen** [comment]
I wish I had the time to compile other peoples project for them. If you cannot extract a minimal reproducer, I can only help you as part of https://nuitka.net/doc/commercial.html but I wasted my time asking, which I need to stop doing.
