### ISSUE TITLE
Stuck in line 200 of __init__.py of Parrot Olympe GroundSDK

### ISSUE THREAD

**Issue by neilyoung** [Nuitka/Nuitka#1769]
Not that I care much (I was just giving this "nuitka" a try), but maybe you care.

- Parrot Olympe SDK (a drone SDK) installed following their instructions: https://developer.parrot.com/docs/olympe/installation.html

- I'm running it on a PI, but that shouldn't matter much

- Written a complete nuts test app "test.py", knowing that it will not work:

```python
import olympe
```

- Running their pyenv shell:

```bash
source ~/code/parrot-groundsdk/products/olympe/linux/env/shell
```

- Running nuitka after proper installation of modules and dependencies within pyenv:

```bash
python -m nuitka --standalone  --static-libpython=no --verbose  test.py
```

- Result after a while: It hangs here:

```bash
Nuitka-Optimization:INFO: /home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/olympe_deps/__init__.py:200 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'e,path,for_loop_1__iter_value'.
```

- CTRL C gives:

```bash

^CNuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': '/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/olympe_deps/__init__.py', 'module_name': <ModuleName olympe_deps>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/MainControl.py", line 918, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/MainControl.py", line 206, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/Optimization.py", line 98, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/ModuleNodes.py", line 536, in computeModule
    result = module_body.computeStatementsSequence(
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/TryNodes.py", line 165, in computeStatement
    result = except_handler.computeStatementsSequence(
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/nodes/VariableReleaseNodes.py", line 100, in computeStatement
    trace_collection.onControlFlowEscape(self)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/optimizations/TraceCollections.py", line 504, in onControlFlowEscape
    if variable.isModuleVariable():
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/staging/usr/lib/python/site-packages/nuitka/Variables.py", line 326, in isModuleVariable
    @staticmethod
KeyboardInterrupt

```

**Comment by neilyoung** [comment]
No, disregard please. It proceeds. But extremely slow...

**Comment by kayhayen** [comment]
Yes, scalability is a constant area of improvement, but obviously hard to be quick on your hardware there. Checkout low memory in user manual for some improvements.

**Comment by neilyoung** [comment]
I was perfectly able to compile the app to a standalone dist dir, but at runtime the app stated to miss jsonschema (which I indeed use).
