### ISSUE TITLE
Spacy is crashing at runtime

### ISSUE THREAD

**Issue by AlbelTec** [Nuitka/Nuitka#1781]
Nuitka version :
```
1.0.6
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\robot\robotenv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
My command :

`nuitka robotscheduler.py --standalone --follow-imports  --enable-plugin=numpy --include-package=win32com,spacy,fr_core_news_sm,thinc,blis --windows-icon-from-ico=D:\robot\robot.ico --include-package=preshed --include-data-dir=D:\robot\data=data --include-data-dir=D:\robot\emails_traites=emails_traites --include-data-dir=D:\robot\log=log --include-data-dir=D:\robot\model=model --include-data-dir=D:\robot\templates=templates  --include-data-files=D:\robot\robot.py=robot.py --python-flag=-O  --include-module=libraries.detectbs --include-module=libraries.nlp --include-module=libraries.ocr --include-module=libraries.outlooknew --include-module=libraries.pdf --include-module=libraries.richlib --include-module=libraries.variables --include-module=libraries.utils --windows-uac-admin`

My environment :

`Virtual environment created with Python 3.10`

I switched from anaconda to standard python because I was suspecting that anaconda do some internal stuff that can lead to package recognition issues

My error :

```
Traceback (most recent call last):
  File "D:\robot\robotscheduler.dist\robotscheduler.py", line 3, in <module>
  File "D:\robot\robotscheduler.dist\robot.py", line 3, in <module robot>
    from libraries import outlooknew
  File "D:\robot\robotscheduler.dist\libraries\outlooknew.py", line 4, in <module libraries.outlooknew>
  File "D:\robot\robotscheduler.dist\libraries\nlp.py", line 1, in <module libraries.nlp>
  File "D:\robot\robotscheduler.dist\spacy\__init__.py", line 6, in <module spacy>
  File "D:\robot\robotscheduler.dist\spacy\errors.py", line 2, in <module spacy.errors>
  File "D:\robot\robotscheduler.dist\spacy\compat.py", line 38, in <module spacy.compat>
  File "D:\robot\robotscheduler.dist\thinc\api.py", line 2, in <module thinc.api>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "D:\robot\robotscheduler.dist\thinc\initializers.py", line 4, in <module thinc.initializers>
    from .backends import Ops
  File "D:\robot\robotscheduler.dist\thinc\backends\__init__.py", line 8, in <module thinc.backends>
    from .cupy_ops import CupyOps
  File "D:\robot\robotscheduler.dist\thinc\backends\cupy_ops.py", line 4, in <module thinc.backends.cupy_ops>
    from .numpy_ops import NumpyOps
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
    # cython: cdivision=True
ModuleNotFoundError: No module named 'thinc.backends.linalg'
```
I managed to add Thinc package manually with all required modules. and "linalg" is present but Nuitka ignores it. moreover, if I uninstall thinc in the virtual environment and then copy it once again in "dist" folder, it works ! But if I quit the program and try again I end up with same error. I can't understand why I'm geeting this random error. 

Packages installed :

```
Package               Version
--------------------- ---------
blis                  0.7.8
catalogue             2.0.8
certifi               2022.6.15
charset-normalizer    2.1.1
click                 8.1.3
colorama              0.4.5
commonmark            0.9.1
cymem                 2.0.6
fr-core-news-sm       3.4.0
idna                  3.3
Jinja2                3.1.2
joblib                1.1.0
keyboard              0.13.5
langcodes             3.3.0
MarkupSafe            2.1.1
murmurhash            1.0.8
Nuitka                1.0.6
numpy                 1.23.2
opencv-contrib-python 4.6.0.66
opencv-python         4.6.0.66
packaging             21.3
pandas                1.4.4
pathy                 0.6.2
Pillow                9.2.0
pip                   22.2.2
preshed               3.0.7
pydantic              1.8.2
Pygments              2.13.0
PyMuPDF               1.20.2
pyparsing             3.0.9
pytesseract           0.3.10
python-dateutil       2.8.2
pytz                  2022.2.1
pywin32               304
requests              2.28.1
rich                  12.5.1
schedule              1.1.0
scikit-learn          1.1.2
scipy                 1.9.1
setuptools            57.4.0
six                   1.16.0
sklearn               0.0
smart-open            5.2.1
spacy                 3.4.1
spacy-legacy          3.0.10
spacy-loggers         1.0.3
srsly                 2.4.4
thinc                 8.1.0
threadpoolctl         3.1.0
tqdm                  4.64.1
typer                 0.4.2
typing_extensions     4.3.0
urllib3               1.26.12
wasabi                0.10.1
```

Related issue : [[#1732](https://github.com/Nuitka/Nuitka/issues/1732)]

**Comment by kayhayen** [comment]
Thanks for switching, spacy is indeed on the list of things i need to add support for. The backend of thinc probably needs a DLL or so. I assume you have no other reproducer there? Your includes indeed had rhe chance to make it work, albeit in a very painful, unoptimal way. Or is this happening on `import spacy` already? Me working on it ususally just takes an example that seems good without me digging one up.

**Comment by rayjharvey** [comment]
I too am receiving the same exact error. I am working on a personal AI project that I have been developing for a few years now and wanting to go public I wanted to obfuscate the core code. I been using cxFreexe and pyinstaller for the different parts of her but when I ran across Nuitka that did all what those did plus a bag of chips and a coke (the C speed increase) I was absolutely thrilled. Anywho, I have tried, everything short of the last individual of uninstalling thinc, but did copy over all of spacy, numpy and thinc from site-packages and as the previous stated it ignores the file (thinc/backends/linalg) that is mentioned at the end of the error. I manually included spacy and thinc in the command line of Nuitka.

I am using Python 3.10.7 (Cpython and standard pip, no virtual env) and Nuitka 1.0.7 and the latest of spacy. I would be happy to share any information you may request.

python -m nuitka --standalone --nofollow-import-to=config --nofollow-import-to=jedi --nofollow-import-to=ipython --include-package=jinxed --include-package=dadjokes --include-package=pyjokes --include-package=PyDictionary --include-package=wikipediaapi --include-package=spacy --include-package=blis --include-package=preshed --include-package=thinc --include-package-data=contractions --include-data-dir=kep=kep --include-data-dir=resources=resources --include-data-dir=storage=storage --include-data-files=config.py=config.py --enable-plugin=tk-inter --enable-plugin=numpy --windows-icon-from-ico=resources/adax-logo.ico adax_ctrl.py


Connecting NLP: Connected
Traceback (most recent call last):
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\adax_ctrl.py", line 58, in <module>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\net_server_interface.py", line 32, in <module net_server_interface>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\nlpmod.py", line 83, in <module nlpmod>
  File "importlib.py", line 126, in import_module
  File "C:\Hyvernion\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\kep\definition_kep.py", line 14, in <module>
    import spacy
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\spacy\__init__.py", line 6, in <module spacy>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\spacy\errors.py", line 2, in <module spacy.errors>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\spacy\compat.py", line 38, in <module spacy.compat>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\thinc\api.py", line 2, in <module thinc.api>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\thinc\initializers.py", line 4, in <module thinc.initializers>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\thinc\backends\__init__.py", line 8, in <module thinc.backends>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-1.2.2022.25\adax_ctrl.dist\thinc\backends\cupy_ops.py", line 4, in <module thinc.backends.cupy_ops>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
    # cython: cdivision=True
ModuleNotFoundError: No module named 'thinc.backends.linalg'

**Comment by kayhayen** [comment]
The dependency for `thinc` was added as part of the 1.1.1 hotfix release I just made. Not sure if this fixes `spacy` already, please open new issues if not.
