### ISSUE TITLE
Importing `requests` fails with `OSError: [Errno 22] Invalid argument:` on Windows.

### ISSUE THREAD

**Issue by loathingKernel** [Nuitka/Nuitka#1783]
Versions of software used
* Windows 8.1 x64,
* Python 3.10.7 (Installed with the Windows installer from python.org)
* Nuitka-develop ([f4d22a0](https://github.com/Nuitka/Nuitka/commit/f4d22a0a98b71ab595586959c1e33b65e82a08b5))

Sample Code
```python
import requests
```

The following command was used to compile a standalone binary in a `virtualenv`
`python -m nuitka --standalone .\nuitka_test.py`

Packages in the virtualenv at the time of user
```
Package            Version
------------------ -----------
certifi            2022.6.15.1
charset-normalizer 2.1.1
idna               3.3
Nuitka             1.1rc11
pip                22.2.2
requests           2.28.1
setuptools         65.3.0
urllib3            1.26.12
wheel              0.37.1
```

Running the resulting binary in WIndows CMD resulted in this failure.
```
C:\Users\loathingkernel\Projects\Rare\nuitka_test.dist>nuitka_test.exe
Traceback (most recent call last):
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\nuitka_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\requests\__init__.py", line 147, in <module requests>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\requests\utils.py", line 58, in <module requests.utils>
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\certifi\core.py", line 37, in where
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\contextlib.py", line 135, in __enter__
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\importlib\_common.py", line 90, in _tempfile
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\tempfile.py", line 341, in mkstemp
  File "C:\Users\LOATHI~1\Projects\Rare\NUITKA~1.DIS\tempfile.py", line 256, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\Users\\LOATHI~1\\AppData\\Local\\Temp\\tmpmyim1o1yC:\\Users\\LOATHI~1\\Projects\\Rare\\NUITKA~1.DIS\\certifi\\\\cacert.pem'
```

The issue was first encountered while trying to compile [Rare](https://github.com/Dummerle/Rare) with `nuitka` in `virtualenv` with the same versions as the above. The resulting failures in that case are below.
* nuitka 1.0.6
```
Traceback (most recent call last):
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\importlib\_common.py", line 92, in _tempfile
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\importlib\abc.py", line 371, in read_bytes
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\importlib\_adapters.py", line 54, in open
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\__main__.py", line 119, in <module>
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\__main__.py", line 104, in main
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\rare\app.py", line 10, in <module rare.app>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\requests\__init__.py", line 147, in <module requests>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\requests\utils.py", line 58, in <module requests.utils>
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\certifi\core.py", line 37, in where
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\contextlib.py", line 135, in __enter__
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\importlib\_common.py", line 98, in _tempfile
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LOATHI~1\\AppData\\Local\\Temp\\tmp08_mwr0y'
```

* nuitka from `develop`
```
C:\Users\loathingkernel\Projects\Rare\rare.dist>rare.exe
Traceback (most recent call last):
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\__main__.py", line 120, in <module>
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\__main__.py", line 104, in main
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\rare\app.py", line 10, in <module rare.app>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\requests\__init__.py", line 147, in <module requests>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\requests\utils.py", line 58, in <module requests.utils>
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\certifi\core.py", line 37, in where
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\contextlib.py", line 135, in __enter__
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\importlib\_common.py", line 90, in _tempfile
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\tempfile.py", line 341, in mkstemp
  File "C:\Users\LOATHI~1\Projects\Rare\RARE~1.DIS\tempfile.py", line 256, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\Users\\LOATHI~1\\AppData\\Local\\Temp\\tmp9nd3kh8mC:\\Users\\LOATHI~1\\Projects\\Rare\\RARE~1.DIS\\certifi\\\\cacert.pem'
```

In the meantime Rare is working correctly using Python 3.9.x on the same platform with nuitka 1.0.6

Edit:
Trying on Linux with python 3.10.7 and possibly the same library versions (sorry, I don't have that `virtualenv` any more to check), produced what looks to my untrained eye like a similar issue
```
Traceback (most recent call last):
  File "/home/loathingkernel/Projects/external/Rare/rare/__main__.py", line 128, in <module>
    main()
  File "/home/loathingkernel/Projects/external/Rare/rare/__main__.py", line 104, in main
    from rare.app import start
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/loathingkernel/Projects/external/Rare/rare/app.py", line 10, in <module rare.app>
    import requests.exceptions
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/loathingkernel/Projects/external/Rare/nuitka_venv/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module requests>
    from . import packages, utils
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/loathingkernel/Projects/external/Rare/nuitka_venv/lib/python3.10/site-packages/requests/utils.py", line 58, in <module requests.utils>
    DEFAULT_CA_BUNDLE_PATH = certs.where()
  File "/home/loathingkernel/Projects/external/Rare/nuitka_venv/lib/python3.10/site-packages/certifi/core.py", line 37, in where
    _CACERT_PATH = str(_CACERT_CTX.__enter__())
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/importlib/_common.py", line 92, in _tempfile
    os.write(fd, reader())
  File "/usr/lib/python3.10/importlib/abc.py", line 371, in read_bytes
    with self.open('rb') as strm:
  File "/usr/lib/python3.10/importlib/_adapters.py", line 54, in open
    raise ValueError()
ValueError
```
 
The culprit seems to be certifi `2022.6.15.1`, downgrading it to `2022.6.15` fixed the issue on Linux. I will try to test later on Windows.

**Comment by kayhayen** [comment]
So, actually on develop, it almost works, and wouldn't do the `tempfile`, if we register with `importlib.resources.as_file` that might help somewhat, but for now I am adding something that again forces the use of old style APIs.

**Comment by kayhayen** [comment]
This is on factory, but I am making a dedicated hotfix right now too.

**Comment by loathingKernel** [comment]
I am happy to report that with `Nuitka 1.0.7` and `Python 3.10` building Rare works as expected. Thank you very much for the quick resolution!
