### ISSUE TITLE
DependsExe - AssertionError: ('c:\\windows\\syswow64\\python36.dll', '     [ ? ] PYTHON36.DLL')

### ISSUE THREAD

**Issue by marcelomanzo** [Nuitka/Nuitka#1788]
We are evaluating Nuitka, to possible use the commercial version, and while compiling a huge python app, we are facing an error with  the DependsExe.

Any idea how to fix it?

(venv310) PS C:\Users\marce\PycharmProjects\srsapp> python -m nuitka --standalone --enable-plugin=tk-inter --enable-plugin=numpy launcher_win64.py
Nuitka-Options:INFO: Used command line options: --standalone --enable-plugin=tk-inter --enable-plugin=numpy launcher_win64.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.7' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.                                               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 945 files (no progress information available).
Nuitka-Scons:INFO: Running 'link @C:\\Users\\marce\\AppData\\Local\\Temp\\tmpzgdort4l.lnk' took 514.95 seconds
Nuitka-Scons:INFO: Compiled 945 C files using clcache with 943 cache hits and 2 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'Cryptodome\Util\.\.keep_dir.txt' due to empty dir needed for 'Cryptodome.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included 600 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk copy needed for standalone Tcl.
Nuitka-Plugins:INFO: tk-inter: Included 831 data files due to Tcl needed for tkinter usage.
Nuitka-Plugins:INFO: numpy: Found 1 file DLLs from numpy installation.
Detecting used DLLs: 76.1%|███████████████████      | 54/71, pep272_encryption\_fast_xor.pydTraceback (most recent call last):
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\MainControl.py", line 964, in main
    detectUsedDLLs(
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\Standalone.py", line 700, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\Standalone.py", line 662, in _detectUsedDLLs
    used_dlls = _detectBinaryDLLs(
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\Standalone.py", line 575, in _detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 90, in detectBinaryPathDLLsWindowsDependencyWalker
    result = detectDLLsWithDependencyWalker(
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\DependsExe.py", line 193, in detectDLLsWithDependencyWalker
    result = parseDependsExeOutput(output_filename)
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\DependsExe.py", line 137, in parseDependsExeOutput
    return _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"))
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\nuitka\freezer\DependsExe.py", line 129, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\windows\\syswow64\\python36.dll', '     [ ? ] PYTHON36.DLL')

**Comment by kayhayen** [comment]
No issue template, no fun.
