### ISSUE TITLE
Missing support for pyscf

### ISSUE THREAD

**Issue by jsjie** [Nuitka/Nuitka#1789]
This error happens when I try to write a wrapper for package pyscf using conda. A minimum case is like the following:
```
.
├── environment.yml
├── main.py
└── test
    └── 10-simple
        ├── MOLE
        └── settings.json
```
[case.zip](https://github.com/Nuitka/Nuitka/files/9562279/case.zip)
related files are in case.zip. Besides what are specified in environment.yml, there are also some packages missing in conda and I installed by pip: ```pyberny``` and ```mcfun```.

A simple ```python main.py --filename=test/10-simple/settings.json``` should work fine.
I tried two ways to compile. First is to run ```python -m nuitka --standalone --enable-plugin=numpy main.py```. This gives me an ```OSError```:
```
$ ./main.dist/main --filename=test/10-simple/settings.json > .local/b.log
pyscf plugins found in 
/not_existing
When PYTHONPATH is set, it is recommended to load these plugins through the environment variable PYSCF_EXT_PATHTraceback (most recent call last):
  File "{workspace}/main.dist/main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "{workspace}/main.dist/pyscf/__init__.py", line 113, in <module pyscf>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "{workspace}/main.dist/pyscf/lib/__init__.py", line 24, in <module pyscf.lib>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "{workspace}/main.dist/pyscf/lib/numpy_helper.py", line 39, in <module pyscf.lib.numpy_helper>
  File "{workspace}/main.dist/pyscf/lib/misc.py", line 54, in load_library
  File "{workspace}/main.dist/numpy/ctypeslib.py", line 163, in load_library
OSError: no file with expected extension
```

The second way is to run ```python -m nuitka --follow-imports --enable-plugin=numpy main.py```. ```--enable-plugin``` is of no use this time, in fact. The result is:
```
Traceback (most recent call last):
  File "{workspace}/main.py", line 5, in <module>
    from pyscf import gto, scf
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/pyscf/__init__.py", line 115, in <module pyscf>
    from pyscf import scf
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/pyscf/scf/__init__.py", line 104, in <module pyscf.scf>
    from pyscf.scf import hf
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/pyscf/scf/hf.py", line 33, in <module pyscf.scf.hf>
    from pyscf.scf import diis
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/pyscf/scf/diis.py", line 26, in <module pyscf.scf.diis>
    import scipy.optimize
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/scipy/optimize/__init__.py", line 413, in <module scipy.optimize>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/scipy/optimize/_linprog.py", line 21, in <module scipy.optimize._linprog>
    from ._linprog_highs import _linprog_highs
  File "/home/zhu/miniconda3/envs/quanchem/lib/python3.9/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module scipy.optimize._linprog_highs>
    from ._highs._highs_wrapper import _highs_wrapper
ModuleNotFoundError: No module named 'scipy.optimize._highs'
```

**Comment by kayhayen** [comment]
On factory, there a bunch of DLLs added for `pyscf` packages. I will keep compiling the example you gave until it works not sure if that will happen in time for 1.1 release, but this may easily slip into 1.2 as I am readying that release now.

**Comment by kayhayen** [comment]
I also added data files needed, and with this it runs.. This is then part of the stable release 1.1 that I just made. 

It seems though, that a lot of anti-bloat work would be necessary. It also gives a warning when run in compiled form, that should be patched away with anti-bloat, but that didn't make the cut off. I might still do those things later, but for now it works.

**Comment by kayhayen** [comment]
The warning was removed with anti-bloat configuration that will be in 1.1.1 hotfix release.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.1 that I just made.
