### ISSUE TITLE
macOS and PyQt5

### ISSUE THREAD

**Issue by katant** [Nuitka/Nuitka#179]
Python 3.7, Nuitka 0.6.0.4
While compiling standalone, Nuitka crashes on:
`Nuitka:INFO:Copying Qt plug-ins 'iconengines,imageformats,mediaservice,printsupport' to 'main.dist/PyQt5/qt-plugins'.`
Traceback:
`FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/plugins/imageformats/QtCore.framework/Versions/5/QtCore'`
Qt is installed

**Comment by kayhayen** [comment]
A more complete traceback of the FileNotFoundError would really help.

**Comment by katant** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 180, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 174, in main
    MainControl.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 844, in main
    standalone_entry_points = standalone_entry_points
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/freezer/Standalone.py", line 1153, in copyUsedDLLs
    if filecmp.cmp(dll_filename1, dll_filename2):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/filecmp.py", line 51, in cmp
    s1 = _sig(os.stat(f1))
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/plugins/imageformats/QtCore.framework/Versions/5/QtCore'

**Comment by kayhayen** [comment]
It should not happen that only in `filecmp` the non-existance of a file is found. I am not sure, but this looks like a directory anyway. I will attempt a change that aims at checking more immediately if a DLL exists when was first discovered for inclusion.

You could help by making it output `dll_filename1` and `dll_filename2` with a print statement, so we can have a better idea right now.

**Comment by katant** [comment]
I have already solved this problem by simply transferring the necessary files from the Qt5 program to the PyQt5 folder

**Comment by kayhayen** [comment]
Lets assume this was invalid then.
