### ISSUE TITLE
Extension Module compilation | ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by arnelochner** [Nuitka/Nuitka#1792]
## Description

Extension Module compilation not working properly if python file imports numpy.

I am trying to compile a .py file into a .pyd/.so via nuitka.
I followed the instruction of "Use Case 2" of the github tutorial.

However I am getting a 

```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

Error after importing the .pyd/.so file.

In https://github.com/Nuitka/Nuitka/issues/888 it is recommended to use --plugin-enable=numpy to fix this issue.
However I cannot use this argument/flag when using nuitka with --module:

```
python -m nuitka --module test.py --follow-import-to=numpy --plugin-enable=numpy
Nuitka-Options:INFO: Used command line options: --module test.py --follow-import-to=numpy --plugin-enable=numpy
Nuitka-Plugins:WARNING: numpy: Not relevant with this OS, or Nuitka arguments given, not activated.
```

Therefore I am curious if it's possible to compile a python file, which imports numpy, into a working .pyd/.so file.

I would be grateful for any feedback.

## Nuitka version, full Python version, flavor, OS
```
python -m nuitka --version
1.0.7
Commercial: None
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) 
Flavor: Anaconda Python
Executable: /home/arne/anaconda3/envs/py39_nuitka/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.4
```
 
##  How did you install Nuitka and Python

-   python via conda environment
-   nuitka via pip within conda environment

 
## The specific PyPI names and versions 

```
Nuitka==1.0.7
numpy==1.23.3
```

## Code Example to reproduce

test.py:
 ```
import numpy as np

def testing():
    l = np.array([1,2,3])
    return 1
```

nuitka command:

```
python -m nuitka --module test.py --follow-import-to=numpy
```

Use compiled test.cpython-39-x86_64-linux-gnu.so:

```
python -c "from test import tesing"
```

Results in:

```
Traceback (most recent call last):
  File "/home/arne/nuitka-showcase/tmp/numpy/core/__init__.py", line 23, in <module numpy.core>
  File "/home/arne/nuitka-showcase/tmp/numpy/core/multiarray.py", line 10, in <module numpy.core.multiarray>
  File "/home/arne/nuitka-showcase/tmp/numpy/core/overrides.py", line 6, in <module numpy.core.overrides>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arne/nuitka-showcase/tmp/test.py", line 1, in <module test>
  File "/home/arne/nuitka-showcase/tmp/numpy/__init__.py", line 140, in <module numpy>
  File "/home/arne/nuitka-showcase/tmp/numpy/core/__init__.py", line 49, in <module numpy.core>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/arne/anaconda3/envs/py39_nuitka/bin/python"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by kayhayen** [comment]
Python extension modules cannot include other extension modules. Including "numpy" is not what should you do, instead you should depend on it. Instead build a wheel and include whatever you want in that.
