### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy

### ISSUE THREAD

**Issue by uralbash** [Nuitka/Nuitka#1793]
I have error when run app if it uses sqlalchemy_utils. I tested this with Nuitka stable, develop and factory version

```
Traceback (most recent call last):
  File "/home/uralbash/test1/build/test1.dist/test1.py", line 3, in <module>
  File "/home/uralbash/test1/build/test1.dist/sqlalchemy_utils/__init__.py", line 1, in <module sqlalchemy_utils>
  File "/home/uralbash/test1/build/test1.dist/sqlalchemy_utils/aggregates.py", line 374, in <module sqlalchemy_utils.aggregates>
  File "/home/uralbash/test1/build/test1.dist/sqlalchemy_utils/compat.py", line 10, in <module sqlalchemy_utils.compat>
  File "/home/uralbash/test1/build/test1.dist/importlib/metadata/__init__.py", line 974, in metadata
  File "/home/uralbash/test1/build/test1.dist/importlib/metadata/__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for sqlalchemy
```

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.0.7
Commercial: None
Python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
Flavor: Debian Python
Executable: /home/uralbash/test1/.env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
```

* How did you install Nuitka and Python

Installed from pip

* The specific PyPI names and versions

  > python -m pip freeze

```
astroid==2.12.5
black==22.8.0
click==8.1.3
ConfigUpdater==3.1.1
dill==0.3.5.1
dodgy==0.2.1
fdb==2.0.2
flake8==5.0.4
flake8-polyfill==1.0.2
future==0.18.2
greenlet==1.1.3
imageio==2.21.2
isort==5.10.1
lazy-object-proxy==1.7.1
mccabe==0.7.0
mypy-extensions==0.4.3
Nuitka==1.0.7
numpy==1.23.2
ordered-set==4.1.0
pathspec==0.10.0
pep8-naming==0.10.0
Pillow==9.2.0
platformdirs==2.5.2
prospector==1.7.7
pycodestyle==2.9.1
pydantic==1.10.1
pydocstyle==6.1.1
pyflakes==2.5.0
pylama==8.4.1
pylint==2.15.0
pylint-celery==0.3
pylint-django==2.5.3
pylint-flask==0.6
pylint-plugin-utils==0.7
pymodbus==2.5.3
pyscard==2.0.3
pyserial==3.5
PySide6-Addons==6.3.1
PySide6-Essentials==6.3.1
PyYAML==6.0
requirements-detector==0.7
setoptconf-tmp==0.3.1
shiboken6==6.3.1
six==1.16.0
snowballstemmer==2.2.0
SQLAlchemy==1.4.41
sqlalchemy-firebird==0.7.5
SQLAlchemy-Utils==0.38.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.4
transaction==3.0.1
typing_extensions==4.3.0
websockets==10.3
wrapt==1.14.1
zipp==3.8.1
zope.interface==5.4.0
zope.sqlalchemy==1.6
zstandard==0.18.0
```

* Example

test1.py
```
import sqlalchemy
from sqlalchemy.sql import default_comparator
import sqlalchemy_utils

print("test nuitka")
```
Without ``import sqlalchemy_utils`` it works file

* Provide in your issue the Nuitka options used

```
python -m nuitka -j5 \
	--standalone \
	--follow-imports \
	--no-pyi-file \
	--output-dir=./build \
	test1.py
```
 ```
$  ls -l

_asyncio.so    _codecs_hk.so       _codecs_tw.so    _dbm.so      _json.so        libexpat.so.1  libsqlite3.so.0  _lzma.so             _opcode.so      _sqlite3.so  _uuid.so
audioop.so     _codecs_iso2022.so  _contextvars.so  _decimal.so  libbz2.so.1.0   libffi.so.8    libssl.so.3      mmap.so              _posixshmem.so  _ssl.so      _zoneinfo.so
_bz2.so        _codecs_jp.so       _crypt.so        greenlet     libcrypto.so.3  liblzma.so.5   libuuid.so.1     _multibytecodec.so   _queue.so       termios.so
_codecs_cn.so  _codecs_kr.so       _ctypes.so       _hashlib.so  libdb-5.3.so    libmpdec.so.3  libz.so.1        _multiprocessing.so  sqlalchemy      test1
```

**Comment by grgi** [comment]
This is a problem with more and more packages which determine their version via the following code:

```
import sys

if sys.version_info >= (3, 8):
    from importlib import metadata
else:
    import importlib_metadata as metadata

__version__ = metadata.version("<PACKAGE_NAME>")
```
A simpler example package without any further dependencies is `py3Dmol`. The very weird thing is that in the following example
```
from importlib import metadata

if __name__ == '__main__':
    # This works also compiled
    print(f"importlib.metadata.version('py3Dmol'): {metadata.version('py3Dmol')}")


# but this import fails for the compiled version
from py3Dmol import __version__

if __name__ == '__main__':
    print(f"py3Dmol.__version__: {__version__}")
```
the first `print` works and only the second one fails although they are basically the same:
```
importlib.metadata.version('py3Dmol'): 1.8.1
Traceback (most recent call last):
  File "/tmp/importlib_metadata/src/foo.dist/foo.py", line 7, in <module>
  File "/tmp/importlib_metadata/src/foo.dist/py3Dmol/__init__.py", line 16, in <module py3Dmol>
  File "/tmp/importlib_metadata/src/foo.dist/importlib/metadata/__init__.py", line 984, in version
  File "/tmp/importlib_metadata/src/foo.dist/importlib/metadata/__init__.py", line 957, in distribution
  File "/tmp/importlib_metadata/src/foo.dist/importlib/metadata/__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for py3Dmol
```

Note that, using `importlib_metadata` rather than `importlib.metadata` just works. However, this would require manually altering all packages before compiling with Nuitka.

**Comment by grgi** [comment]
It is related to #1745 but there Python 3.6 is used along with `importlib_metadata` because it does not have `importlib.metadata` but this PyPI package works for me, so I don't think that this a duplicate.

**Comment by uralbash** [comment]
The problem is in this code after compilation it raise error
https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/compat.py#L3-L11
```python
if sys.version_info >= (3, 8):
    from importlib.metadata import metadata
else:
    from importlib_metadata import metadata


_sqlalchemy_version = tuple(
    [int(i) for i in metadata("sqlalchemy")["Version"].split(".")[:2]]
)
```
But if change  code as @grgi  suggested, then everything works
```python
if sys.version_info >= (3, 8):
    from importlib import metadata
else:
    from importlib_metadata import metadata


_sqlalchemy_version = tuple(
    [int(i) for i in metadata.version("sqlalchemy").split(".")[:2]]
)
```

**Comment by kayhayen** [comment]
Unlike `pkg_resources` it is a bit harder to create `Distribution` objects at run time. We will need our own variation of the `Distribution` abstract type where we preserve e.g. `METADATA` file content.

**Comment by kayhayen** [comment]
So, the importlib metadat `.distribution` methods are supported in the latest pre-release, and for factory I now added a re-formulation for the `metadata` function calls, such that the code ought to work now.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by grgi** [comment]
Thanks, the factory version works for me now.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
