### ISSUE TITLE
Why the compilation fails inside a CircleCI pipeline ?

### ISSUE THREAD

**Issue by joaopfg** [Nuitka/Nuitka#1803]
> python -m nuitka --version

```
1.0.7
Commercial: None
Python: 3.9.13 (default, Mar 28 2022, 18:48:27) 
Flavor: pyenv
Executable: ${HOME}/test_package/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.4
```

Python 3.9.13 installed from source (with pip).

Nuitka installed through pip (globally): `pip install nuitka` 

  > python -m pip freeze

```
attrs==22.1.0
iniconfig==1.1.1
Nuitka==1.0.7
ordered-set==4.1.0
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.9
pytest==7.1.3
test-package==0.0.1
tomli==2.0.1
```

I settled a CircleCI pipeline for my python package repository. I want the pipeline to compile the package code with Nuitka, erase the original python code and then run some unit tests on the compiled code with `pytest`. However, the CircleCI pipeline is failing at the Nuitka compilation step (`python setup.py bdist_nuitka`). When I ssh into the CircleCI machine, the command works fine though. So, I guess the problem is that CircleCI is executing the compilation command with `subprocess.call` and Nuitka has some problem when launched like this. The traceback is:

```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/MainControl.py", line 930, in main
    result, options = compileTree()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/MainControl.py", line 845, in compileTree
    result, options = runSconsBackend(quiet=not Options.isShowScons())
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/MainControl.py", line 701, in runSconsBackend
    SconsInterface.runScons(
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/build/SconsInterface.py", line 286, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/build/SconsCaching.py", line 345, in checkCachingSuccess
    scons_logger.warning("You are not using ccache.")
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/Tracing.py", line 280, in warning
    formatted_message = textwrap.fill(
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
Traceback (most recent call last):
  File "/home/circleci/project/setup.py", line 10, in <module>
    setup(
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/distutils/DistutilCommands.py", line 96, in run
    self._build(os.path.abspath(self.build_lib))
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/distutils/DistutilCommands.py", line 262, in _build
    check_call(command, cwd=build_lib)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/site-packages/nuitka/utils/Execution.py", line 148, in check_call
    subprocess.check_call(*popenargs, **kwargs)
  File "/home/circleci/.pyenv/versions/3.9.13/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/circleci/.pyenv/versions/3.9.13/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/home/circleci/project/build/lib', '--nofollow-import-to=*.tests', '--remove-output', '--include-package=*******_client', '--nofollow-import-to=*.tests', '--nofollow-import-to=*.distutils', '/home/circleci/project/build/lib/*******_client']' returned non-zero exit status 1.

Exited with code exit status 1

CircleCI received exit code 1
```

To reproduce, take the minimal reproducible python package from [here](https://drive.google.com/file/d/1De3cfJuK4rQuQHqUvQCxcfevMOjDwdHG/view?usp=sharing), push it to github or bitbucket and set a CircleCI pipeline for it using the `config.yml` already in the package.

**Comment by kayhayen** [comment]
I am pretty sure I have seen this one before, not sure why I cannot find the issue right now. Basically CirceCI seems to simulate a tty with width 0, which is a bug of theirs. But there is of course an easy workaround to apply, namely to override "0" values with something more meaningful.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
