### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '..\\distributed\\distributed.yaml

### ISSUE THREAD

**Issue by bluesteven** [Nuitka/Nuitka#1805]
Python version is 3.9.10 and MingGW64 is 10.0
python -m nuitka --follow-imports --standalone echotobio.py

My echotobio.py is as following:

```
import echopype as ep
print('test')
```

but when runing the echotobio.exe, I get as following:

Traceback (most recent call last):
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\echotobio.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\echopype\__init__.py", line 5, in <module echopype>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\echopype\calibrate\__init__.py", line 1, in <module echopype.calibrate>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\echopype\calibrate\api.py", line 1, in <module echopype.calibrate.api>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\xarray\__init__.py", line 1, in <module xarray>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\xarray\tutorial.py", line 13, in <module xarray.tutorial>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\xarray\backends\__init__.py", line 6, in <module xarray.backends>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\xarray\backends\cfgrib_.py", line 16, in <module xarray.backends.cfgrib_>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\xarray\backends\locks.py", line 13, in <module xarray.backends.locks>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\dask\distributed.py", line 11, in <module dask.distributed>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\distributed\__init__.py", line 4, in <module distributed>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\ECHOSO~1\code\ECHOTO~1.DIS\distributed\config.py", line 21, in <module distributed.config>
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ECHOSO~1\\code\\ECHOTO~1.DIS\\distributed\\distributed.yaml

**Comment by bluesteven** [comment]
Only using echopype, the above errors happened, 
no echopype in .py file and no error.

**Comment by kayhayen** [comment]
Seems this is a data file of `distributed` and it seems this is a real dependency beast, using pandas, dask, and what not. Using  --include-package-data` would have been an option.

**Comment by kayhayen** [comment]
The `distributed.config` data file configuration was added on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made. Might not be sufficient, report more if that's the case.

**Comment by kayhayen** [comment]
Trying your example, I only had to add one data file configuration to our package yaml, and it works, will be in 1.1.1 hotfix, or of course, you can manually add that file too with the proper command line options on 1.1

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.1 that I just made.
