### ISSUE TITLE
Nuitka doesn't support __defaults__ size changes

### ISSUE THREAD

**Issue by everping** [Nuitka/Nuitka#1807]
The problem happens when my program uses [validators](https://pypi.org/project/validators/) library. It's as follows

```python
import validators

ip_addr = '192.168.1.1'
is_ipv4 = validators.ipv4(ip_addr)
print(is_ipv4)
```

After building with the command `python.exe -m nuitka --standalone valid.py`, I got the binary and the error appeared when I ran it
```
PS D\testlab> .\valid.dist\valid.exe
Traceback (most recent call last):
  File "D\testlab\valid.dist\valid.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D\testlab\valid.dist\validators\__init__.py", line 1, in <module validators>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D\testlab\valid.dist\validators\between.py", line 5, in <module validators.between>
  File "D\testlab\valid.dist\validators\utils.py", line 85, in validator
  File "D\testlab\valid.dist\decorator.py", line 283, in decorator
  File "D\testlab\valid.dist\decorator.py", line 240, in decorate
TypeError: Nuitka doesn't support __defaults__ size changes
```
I guess that Nuitka does not support the `decorator` method currently

Testing env:
- Windows 11 Pro
- Python 3.9.13 with venv
- nuitka 1.0.7
- validators 0.20.0

**Comment by kayhayen** [comment]
The defaults were possible to update, but only the same size. This is a remnant of the time when Nuitka generated per function argument parsing, which considered default count in hard coded ways. Removing the limitation is easy now and ought to have been done a long time ago. This will solve of the remaining sources incompatibilites.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under constant development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the stable release 1.1 that I just made.
