### ISSUE TITLE
Nuitka  - Error with Autoit package

### ISSUE THREAD

**Issue by mala90** [Nuitka/Nuitka#1809]
Command used: `py -m nuitka --onefile --enable-plugin=numpy --follow-imports main.py`

When I run the exe, I have this error:
`Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~2\main.py", line 11, in <module>
    import autoit
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~2\autoit\__init__.py", line 6, in <module autoit>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~2\autoit\autoit.py", line 26, in <module autoit.autoit>
OSError: Cannot load AutoItX from path: C:\Users\Shadow\AppData\Local\Temp\ONEFIL~2\autoit\lib\AutoItX3_x64.dll`

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
