### ISSUE TITLE
No module named 'tensorflow.keras' on EXE 

### ISSUE THREAD

**Issue by mala90** [Nuitka/Nuitka#1812]
`python -m nuitka --version`

- 1.2rc1
- Commercial: None
- Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
- Flavor: Unknown
- Executable: C:\Users\Shadow\AppData\Local\Programs\Python\Python310\python.exe
- OS: Windows
- Arch: x86_64
- WindowsRelease: 10
- Installed with Pip

`python -m pip freeze`

- absl-py==1.2.0
- astunparse==1.6.3
- cachetools==5.2.0
- certifi==2022.9.24
- charset-normalizer==2.1.1
- colorama==0.4.5
- comtypes==1.1.14
- contourpy==1.0.5
- cycler==0.11.0
- decorator==5.1.1
- editdistance==0.6.0
- efficientnet==1.0.0
- essential-generators==1.0
- flatbuffers==2.0.7
- fonttools==4.37.3
- gast==0.4.0
- google-auth==2.11.1
- google-auth-oauthlib==0.4.6
- google-pasta==0.2.0
- grpcio==1.49.1
- h5py==3.7.0
- idna==3.4
- imageio==2.22.0
- imgaug==0.4.0
- keras==2.10.0
- Keras-Applications==1.0.8
- keras-ocr==0.8.9
- Keras-Preprocessing==1.1.2
- keyboard==0.13.5
- kiwisolver==1.4.4
- libclang==14.0.6
- Markdown==3.4.1
- MarkupSafe==2.1.1
- matplotlib==3.6.0
- MouseInfo==0.1.3
- networkx==2.8.6
- Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
- numpy==1.23.3
- oauthlib==3.2.1
- opencv-python==4.6.0.66
- opt-einsum==3.3.0
- ordered-set==4.1.0
- packaging==21.3
- Pillow==9.2.0
- protobuf==3.19.5
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- PyAutoGUI==0.9.53
- pyclipper==1.3.0.post3
- pycryptodome==3.15.0
- PyGetWindow==0.0.9
- pyKey==0.2
- PyMsgBox==1.0.9
- pyparsing==3.0.9
- pyperclip==1.8.2
- PyRect==0.2.0
- PyScreeze==0.1.28
- python-dateutil==2.8.2
- pytweening==1.0.4
- PyWavelets==1.4.1
- pywin32==304
- pywinauto==0.6.8
- requests==2.28.1
- requests-oauthlib==1.3.1
- rsa==4.9
- scikit-image==0.19.3
- scipy==1.9.1
- Shapely==1.8.4
- six==1.16.0
- tensorboard==2.10.0
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.1
- tensorflow==2.10.0
- tensorflow-estimator==2.10.0
- tensorflow-io-gcs-filesystem==0.27.0
- termcolor==2.0.1
- tifffile==2022.8.12
- tqdm==4.64.1
- typing_extensions==4.3.0
- urllib3==1.26.12
- validators==0.20.0
- Werkzeug==2.2.2
- wrapt==1.14.1
- zstandard==0.18.0

`py -m nuitka --onefile --enable-plugin=numpy --output-dir=dist main.py`
`Nuitka-Options:INFO: Used command line options: --onefile --enable-plugin=numpy --output-dir=dist main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc1' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: implicit-imports: Injecting pre-module load code for module 'win32ui':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 3692 files (no progress information available).
Nuitka-Scons:INFO: Running 'link @C:\\Users\\Shadow\\AppData\\Local\\Temp\\tmph_rcmmhd.lnk' took 4539.82 seconds
Nuitka-Scons:INFO: Compiled 3692 C files using clcache with 0 cache hits and 3692 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'Crypto\Util\.\.keep_dir.txt' due to empty dir needed for 'Crypto.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: matplotlib: Included 182 data files due to package data for 'matplotlib.
Nuitka-Plugins:INFO: matplotlib: Included data file 'matplotlib\mpl-data\matplotlibrc' due to updated matplotlib config file with backend to use.
Nuitka-Plugins:INFO: data-files: Included data file 'skimage\io\_plugins\fits_plugin.ini' due to package data for 'skimage'.
Nuitka-Plugins:INFO: data-files: Included 30 data files due to package data directory 'data' for 'skimage'.
Nuitka-Plugins:INFO: data-files: Included data file 'skimage\feature\orb_descriptor_positions.txt' due to package data for 'skimage.feature._orb_descriptor_positions'.
Nuitka-Plugins:INFO: numpy: Found 1 file DLLs from numpy installation.
Nuitka-Plugins:INFO: numpy: Found 33 files DLLs from scipy installation.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from shapely.geos installation.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from tensorflow.lite.experimental.microfrontend.python.ops.audio_microfrontend_op installation.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 0 cache hits and 1 cache misses.
Nuitka-Onefile:INFO: Keeping onefile build directory 'dist\\main.onefile-build'.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (20.54%) size 1649750145 to 338785649.
Nuitka:INFO: Keeping dist folder 'dist\\main.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'dist\\main.build'.
Nuitka:INFO: Successfully created 'dist\\main.exe'.`

When I start exe
`Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~1\main.py", line 108, in <module>
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~1\keras_ocr\__init__.py", line 1, in <module keras_ocr>
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~1\keras_ocr\detection.py", line 28, in <module keras_ocr.detection>
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~1\efficientnet\tfkeras.py", line 6, in <module efficientnet.tfkeras>
  File "C:\Users\Shadow\AppData\Local\Temp\ONEFIL~1\efficientnet\__init__.py", line 50, in inject_tfkeras_modules
ModuleNotFoundError: No module named 'tensorflow.keras'`

How can I fix that ?

every build I do take around 5 hours, it's my 9th tentative xD

**Comment by kayhayen** [comment]
You might want to start by providing a reproducer. I do not want to guess what code I should use to reproduce an issue.

**Comment by mala90** [comment]
Thanks for your answer, the exe crashes when keras_ocr is imported (pip install keras-ocr)

![2](https://user-images.githubusercontent.com/104407399/193614975-5702b05b-69b2-4892-ba11-66abbf44ccce.PNG)

**Comment by kayhayen** [comment]
I am not accepting screenshots as reports.

**Comment by mala90** [comment]
Thanks for your answer, the exe crashes when keras_ocr is imported (pip install keras-ocr)

```
key = input(Fore.WHITE + Style.BRIGHT + 'Coller votre licence: ')
keyauthapp.license(key)

import keras_ocr

pipeline = keras_ocr.pipeline.Pipeline()
time.sleep(10)
os.system('cls' if os.name=='nt' else 'clear')
print("Prêt à l'utilisation !")
```

**Comment by kayhayen** [comment]
I am not capable of doing this right away outside of Nuitka commercial users asking for it: https://nuitka.net/doc/commercial.html
