### ISSUE TITLE
llvmlite.dll standalone error

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1814]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
1.1
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

  > python -m pip freeze
llvmlite==0.39.1
shap==0.41.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import shap
print('hello world')
```
* Provide in your issue the Nuitka options used

python -m nuitka --enable-plugin=numpy --nofollow-import-to=IPython,dask,tensorflow,keras,matplotlib --standalone main.py

* Note if this is a regression

Don't know if this is a regression

### Explanation
When i run the compiled exe i obtain the following error:
```
Traceback (most recent call last):
  File "F:\DEV\BRANCH\C-Link_ManutenzionePredittiva\C-Link_PredictiveMaintenance\main.dist\llvmlite\binding\ffi.py", line 160, in <module llvmlite.binding.ffi>
  File "F:\DEV\BRANCH\C-Link_ManutenzionePredittiva\C-Link_PredictiveMaintenance\main.dist\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'F:\DEV\BRANCH\C-Link_ManutenzionePredittiva\C-Link_PredictiveMaintenance\main.dist\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\main.dist\main.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\pmlearn\learn\trainer.py", line 16, in <module pmlearn.learn.trainer>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\shap\__init__.py", line 12, in <module shap>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\shap\_explanation.py", line 12, in <module shap._explanation>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\shap\utils\__init__.py", line 1, in <module shap.utils>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\shap\utils\_clustering.py", l  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\numba\__init__.py", line 19,   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\numba\core\config.py", line 16, in <module numba.core.config>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\llvmlite\binding\__init__.py", line 4, in <module llvmlite.binding>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\llvmlite\binding\dylib.py", line 3, in <module llvmlite.binding.dylib>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "F:\main.dist\llvmlite\binding\ffi.py", line 167, in <module llvmlite.binding.ffi>
OSError: Could not find/load shared object file: llvmlite.dll
 Error was: Could not find module 'F:\main.dist\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by interseba5** [comment]
After this fix i can correctly see that there is the llvmlite\binding folder in the dist directory but when i try to run the .exe it simply doesnt do nothing and exits immediatly. 
So i tried to re-compile with nuitka 1.1.2 and obviously i had to manually copy the llvmlite\binding folder but after doing that it worked fine. 
At this point i dont know if theres a regression in the factory branch that prevent my exe to works. To inspect further why my exe didnt worked after compiling it with factory nuitka, i had execute it under visual studio debug and i obtained this:
`Unhandled exception in 0x00007FF6F24EBD7D in main.exe: A program exit was requested which caused a fatal error.`

**Comment by kayhayen** [comment]
@interseba5 that is strange and interesting too, right now the differences are not too many. If you are familir with git bisect, I would invite you to try it. I should document how to do it, let me know if you are willing to make a few compilations such that it gets to point at the commit that breaks your code.

**Comment by interseba5** [comment]
Yeah, i will try to do some tests

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.3 that I just made.
