### ISSUE TITLE
inspect.getsourcelines not working

### ISSUE THREAD

**Issue by nerdvegas** [Nuitka/Nuitka#182]
Installed via pip:
0.6.0.4
Python: 2.7.12 (default, Nov 20 2017, 18:23:56) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64

Given the following `test.py`:
```
from inspect import getsourcelines

path = '/tmp/myfunc.py'
f = open(path)
g = {}

exec f in g
func = g["myfunc"]
print getsourcelines(func)
```
..and the file `/tmp/myfunc.py`:
```
def myfunc():
    return 1
```

..and the binary produced by:
```
nuitka --follow-imports test.py
```

..I get the following error:
```
]$ ./test.bin
Traceback (most recent call last):
  File "/.../test.py", line 12, in <module>
    func = g["myfunc"]
  File "/usr/lib/python2.7/inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python2.7/inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code
```

However when run with `python test.py`, it works as expected.

Thx
Allan

**Comment by kayhayen** [comment]
Hello Alan,

this is indeed the case. Nuitka's re-formulation of `exec` calls `compile` manually on the read file, which then looses the information, it says `<string at test.py:7>` then. I kind of recall that the handling of "file" was not automatic to underlying functions like `compile` built-in.

But it seems I will have to make a more specialized compile variant for exec, one that remembers the file better.

I am thinking that `execfile` should also be affected, which btw is probably what you ought to be using, but it will be no better in Nuitka.

The fix however, ought to be simple, just some work.

Yours,
Kay

**Comment by nerdvegas** [comment]
Thanks! This is blocking me from using nuitka on my project, so I'll hold
off for now and wait.

Cheers
Allan

**Comment by nerdvegas** [comment]
Ps: On further investigation, this works:

```
path = "myfunc.py"
code = compile(open(path).read(), path, "exec")
g = {}

exec code in g
func = g["myfunc"]
print getsourcelines(func)
```

**Comment by nerdvegas** [comment]
Hi Kay, how do I test this? Can I just clone develop branch? Do I need the
extra cli flag anymore?

Thx
Allan
