### ISSUE TITLE
SyntaxError get_ipython, Cannot follow import to module 'rich.pretty' because of 'SyntaxError'

### ISSUE THREAD

**Issue by black-snow** [Nuitka/Nuitka#1822]
# Please check out if the develop version of Nuitka works better for you.

Nope, same

# Nuitka version, full Python version, flavor, OS, etc. as output by *this* command.

  > python -m nuitka --version

```
1.2rc1
Commercial: None
Python: 3.10.7 (main, Sep 13 2022, 14:31:33) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11
```

(tried 1.1.0 before)

# How did you install Nuitka and Python

Docker + python official + pdm

```docker
FROM python:3.10.7-bullseye@sha256:223f9bf94e456feb64ed1e1d7efee882e6f165ae7fa00984a51a5432c18eeeac

RUN : \
    && python -m pip install --upgrade pip \
    && python -m pip install pdm \
    && python -m pdm --pep582 bash >> ~/.bashrc \
    && apt update && apt dist-upgrade -y \
    && apt install -y patchelf fuse gcc ccache git \
    && python -m pdm sync \
    && :
```

```toml
[tool.pdm.dev-dependencies]
dev = [
    "zstandard>=0.17.0",
    "Nuitka @ git+https://github.com/Nuitka/Nuitka.git",
    #"Nuitka>=1.1.0",
    "black>=22.6.0",
]

[project]
dependencies = [
    "pyyaml>=6.0",
    "ping3>=4.0.3",
    "rich>=12.4.1",
]
```

```
pdm list
╭─────────────────┬─────────┬──────────╮
│ Package         │ Version │ Location │
├─────────────────┼─────────┼──────────┤
│ attrs           │ 21.4.0  │          │
│ black           │ 22.8.0  │          │
│ click           │ 8.1.3   │          │
│ commonmark      │ 0.9.1   │          │
│ iniconfig       │ 1.1.1   │          │
│ mypy-extensions │ 0.4.3   │          │
│ nuitka          │ 1.2rc1  │          │
│ packaging       │ 21.3    │          │
│ pathspec        │ 0.9.0   │          │
│ ping3           │ 4.0.3   │          │
│ platformdirs    │ 2.5.2   │          │
│ pluggy          │ 1.0.0   │          │
│ py              │ 1.11.0  │          │
│ pygments        │ 2.12.0  │          │
│ pyparsing       │ 3.0.9   │          │
│ pytest          │ 7.1.3   │          │
│ pyyaml          │ 6.0     │          │
│ rich            │ 12.5.1  │          │
│ tomli           │ 2.0.1   │          │
│ zstandard       │ 0.18.0  │          │
╰─────────────────┴─────────┴──────────╯
```

# Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

todo

# Provide in your issue the Nuitka options used

```
[tool.pdm.scripts]
dist = "python -m nuitka src/main.py --standalone --onefile -oxyz --assume-yes-for-downloads --linux-onefile-icon=icon.png --python-flag=nosite,-O"
```

# Note if this is a regression

I think so. Used to work with 0.9.x.

# build output

```
Nuitka-Options:INFO: Used command line options: src/main.py --standalone --onefile -oxyz --assume-yes-for-downloads --linux-onefile-icon=icon.png --python-flag=nosite,-O
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc1' on Python '3.10' commercial grade 'not installed'.
Nuitka-Inclusion:WARNING: Cannot follow import to module 'rich.pretty' because of 'SyntaxError'.
Nuitka:INFO: Completed Python level compilation and optimization.                       
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.          
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 117 files (no progress information available).
Nuitka-Scons:INFO: Compiled 117 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 116
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 1 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Onefile:INFO: Keeping onefile build directory 'main.onefile-build'.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (27.70%) size 57532384 to 15939260.
Nuitka:INFO: Keeping dist folder 'main.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'xyz.
```

# running the binary

```
Traceback (most recent call last):
  File "/tmp/onefile_4418_1664643321_534298/main.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_4418_1664643321_534298/commands/connect.py", line 6, in <module commands.connect>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_4418_1664643321_534298/rich/console.py", line 58, in <module rich.console>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_4418_1664643321_534298/rich/pretty.py", line 1, in <module rich.pretty>
  File "/workspaces/xyz/__pypackages__/3.10/lib/rich/pretty.py", line 246
    ip = get_ipython()  # type: ignore[name-defined]
         ^^^^^
SyntaxError: invalid syntax
```

Can't see an actual issue [there](https://github.com/Textualize/rich/blob/master/rich/pretty.py#L251).

**Comment by StayMadYourBad** [comment]
https://github.com/Nuitka/Nuitka/issues/1816

Getting same issue, the above is a duplicate of this. Waiting for Kay to push the fix

**Comment by black-snow** [comment]
How did I not find this? Thanks @StayMadYourBad - closing in favour of #1816

**Comment by kayhayen** [comment]
The is indeed a duplicate, I just pushed a fix to factory branch, hotfix should be coming as soon as possible.
