### ISSUE TITLE
thinc (spacy) persists giving same no module named thinc.backends.linalg

### ISSUE THREAD

**Issue by rayjharvey** [Nuitka/Nuitka#1823]
Python 3.10.7 : CPython : pip : no virtual environment : thinc==8.1.2 : Nuitka==1.1.1

Related: Issue #1781

`Connecting NLP           : Connected
Traceback (most recent call last):
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\adax_ctrl.py", line 70, in <module>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\net_server_interface.py", line 37, in <module net_server_interface>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\nlpmod.py", line 96, in <module nlpmod>
  File "importlib.py", line 126, in import_module
  File "C:\Hyvernion\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\kep\definition_kep.py", line 12, in <module>
    import spacy
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\spacy\__init__.py", line 6, in <module spacy>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\spacy\errors.py", line 2, in <module spacy.errors>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\spacy\compat.py", line 38, in <module spacy.compat>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\thinc\api.py", line 2, in <module thinc.api>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\thinc\initializers.py", line 4, in <module thinc.initializers>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\thinc\backends\__init__.py", line 8, in <module thinc.backends>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\server-0.2.2022.29\adax_ctrl.dist\thinc\backends\cupy_ops.py", line 4, in <module thinc.backends.cupy_ops>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
    # cython: cdivision=True
ModuleNotFoundError: No module named 'thinc.backends.linalg'`

Command line used:

`python -m nuitka --standalone --nofollow-import-to=config --nofollow-import-to=tensorflow --nofollow-import-to=black --nofollow-import-to=ipykernel --nofollow-import-to=IPython --nofollow-import-to=jedi --nofollow-import-to=jupyter_client --nofollow-import-to=jupyter_core --nofollow-import-to=scipy --nofollow-import-to=sqlite3 --nofollow-import-to=yapf --include-package=jinxed --include-package=dadjokes --include-package=pyjokes --include-package=PyDictionary --include-package=wikipediaapi --include-package=blis --include-package=preshed --include-package=en_core_web_sm --include-package=en_core_web_lg --include-package=thinc --include-package-data=thinc --include-package=spacy --include-package-data=spacy --include-package-data=contractions --include-data-dir=kep=kep --include-data-dir=resources=resources --include-data-dir=storage=storage --include-data-files=config.py=config.py --include-data-files=instance_error.pyc=instance_error.pyc --enable-plugin=tk-inter --enable-plugin=numpy --windows-icon-from-ico=resources/adax-logo.ico adax_ctrl.py`

Cheers,
-Ray

**Comment by kayhayen** [comment]
Without a reproducer this is mostly useless and also `--version` output is missing

**Comment by rayjharvey** [comment]
`1.1.1
Commercial: None
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10`

Example:
`import spacy

whatiheard = "Apple is looking at buying US startup for $1 billion."

print("whatiheard = " + whatiheard + "\n")

nlp = spacy.load("en_core_web_sm")
whatiheard = nlp(whatiheard)

print("Tokens:")
for token in whatiheard:
    print("TEXT:", token.text, "-- POS:", token.pos_, "-- DEP:", token.dep_)`

Error:
`Traceback (most recent call last):
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\test3.py", line 6, in <module>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\spacy\__init__.py", line 6, in <module spacy>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\spacy\errors.py", line 2, in <module spacy.errors>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\spacy\compat.py", line 38, in <module spacy.compat>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\thinc\api.py", line 2, in <module thinc.api>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\thinc\initializers.py", line 4, in <module thinc.initializers>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\thinc\backends\__init__.py", line 8, in <module thinc.backends>
  File "C:\HYVERN~1\Adax_Research\adax_development\nuitka\spacy-test\test3.dist\thinc\backends\cupy_ops.py", line 4, in <module thinc.backends.cupy_ops>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
    # cython: cdivision=True
ModuleNotFoundError: No module named 'preshed.maps'`

Command Line Used:
`python -m nuitka --standalone --nofollow-import-to=tensorflow --nofollow-import-to=black --nofollow-import-to=ipykernel --nofollow-import-to=IPython --nofollow-import-to=jedi --nofollow-import-to=jupyter_client --nofollow-import-to=jupyter_core --nofollow-import-to=scipy --nofollow-import-to=sqlite3 --nofollow-import-to=yapf --include-package=thinc --include-package-data=thinc --include-package=spacy --include-package-data=spacy --enable-plugin=numpy test3.py`

Note:
It is a different module (same error) but as you can see it resides in the same location of: thinc.backends.numpy_ops

**Comment by kayhayen** [comment]
I am not sure why this got closed without comment @rayjharvey
