### ISSUE TITLE
Why did this error occur when packing?

### ISSUE THREAD

**Issue by lui305** [Nuitka/Nuitka#1843]
(base) (venv) PS L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene> nuitka --mingw64 --standalone --show-memory --show-progress --output-dir=software test.py
Nuitka-Options:INFO: Used command line options: --mingw64 --standalone --show-memory --show-progress --output-dir=software test.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0.3' on Python '3.9' commercial grade 'not installed'.
Nuitka-Memory:INFO: Memory usage changed loading module '__main__': 152.00 KB (155648 bytes)
Nuitka-Progress:INFO: PASS 1:
Nuitka-Progress:INFO: Optimizing module '__main__', 0 more modules to go after that.
Nuitka-Memory:INFO: Memory usage 58.49 MB (61333504 bytes):
Nuitka-Progress:INFO: Doing module local optimizations for '__main__'.
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_builtin_ref
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Memory:INFO: Memory usage changed during optimization of '__main__': 0.00 KB (0 bytes)
Nuitka-Memory:INFO: Memory usage changed loading module 'paddleocr': 0.00 KB (0 bytes)
Nuitka-Progress:INFO: Optimizing module 'paddleocr', 382 more modules to go after that.
Nuitka-Memory:INFO: Memory usage 58.49 MB (61333504 bytes):
Nuitka-Progress:INFO: Doing module local optimizations for 'paddleocr'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: var_usage
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Memory:INFO: Memory usage changed during optimization of 'paddleocr': 0.00 KB (0 bytes)
Nuitka-Memory:INFO: Memory usage changed loading module 'paddleocr.paddleocr': 0.00 KB (0 bytes)
Nuitka-Progress:INFO: Optimizing module 'paddleocr.paddleocr', 382 more modules to go after that.
Nuitka-Memory:INFO: Memory usage 59.05 MB (61915136 bytes):
Nuitka-Progress:INFO: Doing module local optimizations for 'paddleocr.paddleocr'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
PASS 1: 0.5%|▏                        | 2/385, paddleocr.paddleocrProblem with statement at L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\paddleocr\paddleocr.py:30:
-> tools = importlib.import_module('.', 'tools')

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'L:\\MyMaster\\project\\Project\\yadi_project\\py_project\\paddleocr-test-vene\\venv\\lib\\site-packages\\paddleocr\\paddleocr.py', 'module_name': <ModuleNa
me paddleocr.paddleocr>, 'code_flags': ''}>'.
PASS 1: 0.5%|▏                        | 2/385, paddleocr.paddleocrTraceback (most recent call last):
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\MainControl.py", line 918, in main
    main_module = _createNodeTree(filename=filename)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\MainControl.py", line 206, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 98, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 536, in computeModule
    result = module_body.computeStatementsSequence(
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
    source = trace_collection.onExpression(self.subnode_source)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 624, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1222, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 822, in computeExpression
    result = makeExpressionImportModuleFixed(
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\nodes\ImportNodes.py", line 1195, in makeExpressionImportModuleFixed
    module_name = resolveModuleName(module_name)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\importing\ImportResolving.py", line 130, in resolveModuleName
    module_name = ModuleName(module_name)
  File "L:\MyMaster\project\Project\yadi_project\py_project\paddleocr-test-vene\venv\lib\site-packages\nuitka\utils\ModuleNames.py", line 37, in __init__
    assert checkModuleName(value), value
AssertionError: tools.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun.
