### ISSUE TITLE
Incorrect handling of path parameters with spaces when detecting used DLLs

### ISSUE THREAD

**Issue by topkie** [Nuitka/Nuitka#1845]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
1.1.5
Commercial: None
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

  pip, virtualenv

* The specific PyPI names and versions

```
Nuitka==1.1.5
orderedset==2.0.3
zstandard==0.18.0
```

* Many times when you get an error from Nuitka, your setup may be special

 hello world build not pass

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python3
# helloworld.py
print('Hello World')
```

* Provide in your issue the Nuitka options used

```
python -m nuitka --onefile --show-memory --show-progress --output-dir=out .\helloworld.py
```

* Terminal Output

```
...
Nuitka-Inclusion:INFO: Analyzing dependencies of 'out\helloworld.dist\helloworld.exe'.
Detecting used DLLs: 7.7%|█▉                       | 1/13, helloworld.exeTraceback (most recent call last):
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\MainControl.py", line 969, in main      
    source_dir=OutputDirectories.getSourceDirectoryPath(),
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 716, in detectUsedDLLs
    standalone_entry_point=standalone_entry_point, source_dir=source_dir
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 683, in _detectUsedDLLs
    update_cache=not Options.shallNotStoreDependsExeCachedResults(),
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 584, in _detectBinaryDLLs
    update_cache=update_cache,
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 91, in detectBinaryPathDLLsWindowsDependencyWalker
    scan_dirs = _getScanDirectories(package_name, original_dir)
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 144, in _getScanDirectories
    scan_dir = getDirectoryRealPath(scan_dir)
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\utils\FileOperations.py", line 249, in getDirectoryRealPath
    path = _getRealPathWindows(path)
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\utils\FileOperations.py", line 216, in _getRealPathWindows
    shell=False,
  File "D:\OldUsers\Documents\VSCode\Python\south-plus-sync\venv\lib\site-packages\nuitka\utils\Execution.py", line 133, in check_output
    raise NuitkaCalledProcessError(retcode, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe', '-NoProfile', 'Get-Item', 'C:\\Program Files\\dotnet', '|', 'Select-Object', '-ExpandProperty', 'Target']' returned non-zero exit status 1. Error was b"Get-Item : A positional parameter cannot be found that accepts argument 'Files\\dotnet'.\r\nAt line:1 char:1\r\n+ Get-Item C:\\Program Files\\dotnet | Select-Object -ExpandProperty Targ ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParameterBindingException\r\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetItemCommand".
```

* Note if this is a regression

  It happened at first build, once I change the ``path`` to ``f'"{path}"'`` and build success, even if I change it back, it still works.
https://github.com/Nuitka/Nuitka/blob/63b41cb73fcaa846282a2572a484e884d06ab72a/nuitka/utils/FileOperations.py#L205-L217

```python3
result = check_output( 
     [ 
         _powershell_path, 
         "-NoProfile", 
         "Get-Item", 
         f'"{path}"',   # change it
         "|", 
         "Select-Object", 
         "-ExpandProperty", 
         "Target", 
     ], 
     shell=False, 
 )

**Comment by kayhayen** [comment]
Used DLLs are cached, so once it succeeds, it needs more DLL directories, version change, etc. thanks for reporting, this looks important.

**Comment by kayhayen** [comment]
Actually the arguments are all a single one, i.e. a script, so separating never made any sense, and for the powershell script, argument needs to be quoted, it was only for the shell, so this will be on factory soon, and part of 1.1.6 hotfix release coming later today.

**Comment by topkie** [comment]
thanks for fix!
