### ISSUE TITLE
certifi.core  ImportError?

### ISSUE THREAD

**Issue by jekoie** [Nuitka/Nuitka#1850]
I use python32  V32bit to compile app, it compile fine.but when I run app, it show some error.I need help now.

**compile cmd**
`C:\Python38_V32\python.exe -m nuitka --noinclude-IPython-mode=nofollow --plugin-enable=pyqt5 --windows-icon-from-ico=./design/res/logo.ico --show-progress --lto=yes  --output-dir=dist --no-pyi-file --remove-output --show-modules --include-package=websockets,uvicorn,certifi,requests  --show-modules-output=./dist/module.txt --nofollow-import-to=PIL,lib2to3,matplotlib,tornado,tkinter FWTMES.py`

**app run error log**
```console
PS E:\projects\MES\dist\FWTMES.dist> .\FWTMES.exe
[2022-10-21 16:30:28,353|ERROR| log:hook:37]: Traceback (most recent call last):
  File "E:\projects\MES\dist\FWTMES.dist\FWTMES.py", line 1, in <module>
  File "E:\projects\MES\dist\FWTMES.dist\ui\ui.py", line 15, in <module ui.ui>
  File "E:\projects\MES\dist\FWTMES.dist\core\settings.py", line 7, in <module core.settings>
  File "E:\projects\MES\dist\FWTMES.dist\core\net.py", line 4, in <module core.net>
  File "E:\projects\MES\dist\FWTMES.dist\requests\__init__.py", line 147, in <module requests>
  File "E:\projects\MES\dist\FWTMES.dist\requests\utils.py", line 24, in <module requests.utils>
  File "E:\projects\MES\dist\FWTMES.dist\requests\certs.py", line 14, in <module requests.certs>
  File "E:\projects\MES\dist\FWTMES.dist\certifi\__init__.py", line 1, in <module certifi>
  File "E:\projects\MES\dist\FWTMES.dist\certifi\core.py", line 46, in <module certifi.core>
ImportError
```

**module log**
```console
Nuitka-Inclusion:INFO: Included compiled module '__main__'.
Nuitka-Inclusion:INFO: Included compiled module '__parents_main__'.
Nuitka-Inclusion:INFO: Included compiled module 'certifi'.
Nuitka-Inclusion:INFO: Included compiled module 'certifi.__main__'.
Nuitka-Inclusion:INFO: Included compiled module 'certifi.core'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing'.
Nuitka-Inclusion:INFO: Included compiled module 'multiprocessing-postLoad'.
Nuitka-Inclusion:INFO: Included compiled module 'multiprocessing-preLoad'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.connection'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.context'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.dummy'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.dummy.connection'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.forkserver'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.heap'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.managers'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.pool'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.popen_spawn_win32'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.process'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.queues'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.reduction'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.resource_sharer'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.resource_tracker'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.shared_memory'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.sharedctypes'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.spawn'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.synchronize'.
Nuitka-Inclusion:INFO: Included uncompiled module 'multiprocessing.util'.
Nuitka-Inclusion:INFO: Included compiled module 'requests'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.__version__'.
Nuitka-Inclusion:INFO: Included compiled module 'requests._internal_utils'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.adapters'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.api'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.auth'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.certs'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.compat'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.cookies'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.exceptions'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.help'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.hooks'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.models'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.packages'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.sessions'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.status_codes'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.structures'.
Nuitka-Inclusion:INFO: Included compiled module 'requests.utils'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.__main__'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn._subprocess'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn._types'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.config'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.importer'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.lifespan'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.lifespan.off'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.lifespan.on'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.logging'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.loops'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.loops.asyncio'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.loops.auto'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.loops.uvloop'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.main'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware.asgi2'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware.debug'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware.message_logger'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware.proxy_headers'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.middleware.wsgi'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.http'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.http.auto'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.http.flow_control'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.http.h11_impl'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.http.httptools_impl'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.utils'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.websockets'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.websockets.auto'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.websockets.websockets_impl'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.protocols.websockets.wsproto_impl'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.server'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors.basereload'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors.multiprocess'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors.statreload'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors.watchfilesreload'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.supervisors.watchgodreload'.
Nuitka-Inclusion:INFO: Included compiled module 'uvicorn.workers'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.__main__'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.auth'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.client'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.connection'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.datastructures'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.exceptions'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.extensions'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.extensions.base'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.extensions.permessage_deflate'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.frames'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.headers'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.http'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.http11'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.imports'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.auth'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.client'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.compatibility'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.framing'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.handshake'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.http'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.protocol'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.legacy.server'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.server'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.streams'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.typing'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.uri'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.utils'.
Nuitka-Inclusion:INFO: Included compiled module 'websockets.version'.

```

**File Structure**  
![image](https://user-images.githubusercontent.com/6836400/197152027-629a0605-c793-48a2-86d6-548d2e6c10d0.png)

**Comment by jekoie** [comment]
@kayhayen  add version info
```console
E:\projects\MES>C:\Python38_V32\python.exe -m nuitka --version
1.1.2
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]
Flavor: Unknown
Executable: C:\Python38_V32\python.exe
OS: Windows
Arch: x86
WindowsRelease: 1
```

**Comment by kayhayen** [comment]
Using the latest stable release is recommened for good reason.
