### ISSUE TITLE
bdist_nuitka fails with non-zero exit status 1

### ISSUE THREAD

**Issue by misantroop** [Nuitka/Nuitka#1852]
Attempting to build libraries (.so) with setuptools using the --modules flag.
Tested on 1.1.5 and latest commit.

**CODE**

```
from setuptools import setup

setup(
	name='WERK',
	package_dir={
                    '': 'src'
    },
	package_data={
                    'var': ['*.*'],
	},
	command_options={
		'nuitka': {
			'--module': True,
		}
	},
)
```

**OUTPUT**

```
Nuitka-Wheel:INFO: Building: 'containers' with command ['/home/misantroop/.pyenv/versions/3.10.6/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/home/misantroop/WERK/deploy/build/lib', '--nofollow-import-to=*.tests', '--remove-output', '--include-module=containers', '--module', '/home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so']
Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --output-dir=/home/misantroop/WERK/deploy/build/lib --nofollow-import-to=*.tests --remove-output --include-module=containers --module /home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc6' on Python '3.10' commercial grade 'not installed'.
SyntaxError: invalid or missing encoding declaration for '/home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so'

Nuitka is very syntax compatible with standard Python. It is currently running
with Python version '3.10', you might want to specify more clearly with the use
of the precise Python interpreter binary and '-m nuitka', e.g. use this
'python2.7 -m nuitka' option, if that's not the one the program expects.

Traceback (most recent call last):
  File "/home/misantroop/WERK/deploy/setup_nuitka2.py", line 19, in <module>
    setup(
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/nuitka/distutils/DistutilCommands.py", line 96, in run
    self._build(os.path.abspath(self.build_lib))
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/nuitka/distutils/DistutilCommands.py", line 262, in _build
    check_call(command, cwd=build_lib)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/site-packages/nuitka/utils/Execution.py", line 150, in check_call
    subprocess.check_call(*popenargs, **kwargs)
  File "/home/misantroop/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/misantroop/.pyenv/versions/3.10.6/bin/python', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=/home/misantroop/WERK/deploy/build/lib', '--nofollow-import-to=*.tests', '--remove-output', '--include-module=containers', '--module', '/home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so']' returned non-zero exit status 1.
```

**Running the command separately:**

```
/home/misantroop/.pyenv/versions/3.10.6/bin/python -m nuitka --module --enable-plugin=pylint-warnings --output-dir=/home/misantroop/WERK/deploy/build/lib --nofollow-import-to=\*.tests --remove-output --include-module=containers --module /home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so 
Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings --output-dir=/home/misantroop/WERK/deploy/build/lib --nofollow-import-to=*.tests --remove-output --include-module=containers --module /home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc6' on Python '3.10' commercial grade 'not installed'.
SyntaxError: invalid or missing encoding declaration for '/home/misantroop/WERK/deploy/build/lib/containers.cpython-310-x86_64-linux-gnu.so'
```

Specifying `# coding=utf8` in the .py file results in the same exception.

**Comment by kayhayen** [comment]
Specifying `--module` makes no sense, that is the default. At this time no standalone binary can be built from wheel configuration, that is something to be added in the future.

You have failed to provide the exact command used to build the wheel.

**Comment by misantroop** [comment]
Should have been more clear. I'm not looking to create standalone binaries (.bin) but compiled libraries (.so). Coming from Cython, I'm looking for the equivalent of:

```
setup(
	...
	ext_modules = cythonize(some_files, language_level=3),
)
```

Or to do "python -m nuitka --module file.py" using setuptools.

**Comment by kayhayen** [comment]
Read https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels and not that the examples given are all pointless.

This has tests in `tests/distututils` and known to work. Since you are bad at providing example, I couldn't test your setup, but I believe `package_dir` as used is supported.

**Comment by kayhayen** [comment]
The only options that anybody could consider at enabling plugins if needed.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
