### ISSUE TITLE
Standalone program using vedo cannot fonts directory

### ISSUE THREAD

**Issue by jkissi** [Nuitka/Nuitka#1853]
Hello!
I am back again! I have discovered another interesting error while attempting to compile my program. Again, the process seems to complete successfully, with no major warnings and again, very quickly (usually within 20 mins). Upon completing compilation and running the executable in the .dist/ folder using a git bash terminal, I receive the following error:

```
$ ./vedo_compile.exe 
Traceback (most recent call last):
  File "path\to\dist\folder\vedo_compile.dist\vedo_compile.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "path\to\dist\folder\vedo_compile.dist\vedo\__init__.py", line 137, in <module vedo>
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'path\\to\\dist\\folder\\vedo_compile.dist\\vedo\\fonts/'
```
Something that I have noticed is that when I take a listing of the .dist/ folder contents, there is _**no**_ vedo folder. I don't know if that is intended but it is noticeable that folders for other libraries, such as numpy and vtk, that vedo relies on are present, and, of course, the error seems to indicate that that folder is being looked for.  The usual info follows:

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.
  > python -m nuitka --version

```
  1.1
  Commercial: None
  Python: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
  Flavor: Anaconda Python
  Executable: D:\installs\programs\Anaconda3\envs\nnse\python.exe
  OS: Windows
  Arch: x86_64
  WindowsRelease: 10
```

* How did you install Nuitka and Python
**All related libraries (vedo, nuitka, python) are installed using Anaconda command line in an anaconda environment**

* The specific PyPI names and versions

  > python -m pip freeze

_Wasn't sure exactly what was relevant, so I placed the entire output here_:
```
    certifi==2022.9.24
    click @ file:///C:/ci/click_1646056762388/work
    colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1655412516417/work
    cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
    dearpygui==1.6.2
    Deprecated @ file:///home/conda/feedstock_root/build_artifacts/deprecated_1632758190537/work
    fonttools==4.25.0
    hdbscan @ file:///D:/bld/hdbscan_1644613083537/work
    joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
    kiwisolver @ file:///D:/bld/kiwisolver_1657953239132/work
    laspy @ file:///home/conda/feedstock_root/build_artifacts/laspy_1656594965604/work
    loguru @ file:///D:/bld/loguru_1649442989339/work
    matplotlib @ file:///D:/bld/matplotlib-suite_1659031634610/work
    mkl-fft==1.3.1
    mkl-random @ file:///C:/ci_310/mkl_random_1643050563308/work
    mkl-service==2.4.0
    munkres==1.1.4
    Nuitka @ file:///D:/bld/nuitka_1664172646218/work
    numpy @ file:///C:/ci/numpy_and_numpy_base_1652784037925/work
    opencv-python==4.5.5
    ordered-set @ file:///home/conda/feedstock_root/build_artifacts/ordered-set_1643221357603/work
    packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
    pandas @ file:///D:/bld/pandas_1656001224800/work
    Pillow==9.2.0
    Pympler @ file:///home/conda/feedstock_root/build_artifacts/pympler_1658620692385/work
    pyntcloud @ file:///home/conda/feedstock_root/build_artifacts/pyntcloud_1659284224615/work
    pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
    PyQt5==5.12.3
    PyQt5_sip==4.19.18
    PyQtChart==5.12
    PyQtWebEngine==5.12.1
    python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
    pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1660580468234/work
    scikit-learn @ file:///C:/ci_310/scikit-learn_1642249118560/work
    scipy @ file:///C:/ci_310/scipy_1642247684282/work
    seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work
    sip==4.19.13
    six @ file:///tmp/build/80754af9/six_1644875935023/work
    tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1655900837660/work
    threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
    torch==1.12.1
    tornado @ file:///D:/bld/tornado_1656937966227/work
    typing_extensions @ file:///C:/Windows/TEMP/abs_dd2d0moa85/croots/recipe/typing_extensions_1659638831135/work
    vedo @ file:///home/conda/feedstock_root/build_artifacts/vedo_1661755873429/work
    vtk===-PKG-VERSION
    win32-setctime @ file:///home/conda/feedstock_root/build_artifacts/win32_setctime_1642883564726/work
    wincertstore==0.2
    wrapt @ file:///D:/bld/wrapt_1651495425905/work
```

* Provide in your issue the Nuitka options used

`python -m nuitka --enable-plugin=numpy --enable-plugin=pyqt5 --enable-plugin=multiprocessing --enable-plugin=matplotlib --output-dir=<path/to/output/folder> --standalone vedo_compile.py`

Here is the full compilation output:
```
python -m nuitka --enable-plugin=numpy --enable-plugin=pyqt5 --enable-plugin=multiprocessing --enable-plugin=matplotlib --output-dir=path/to/output/folder --standalone vedo_compile.py
Nuitka-Options:INFO: Used command line options: --enable-plugin=numpy --enable-plugin=pyqt5 --enable-plugin=multiprocessing --enable-plugin=matplotlib --output-dir=path/to/output/folder --standalone vedo_compile.py
Nuitka-Plugins:WARNING: matplotlib: Plugin is defined as always enabled.
Nuitka-Plugins:WARNING: multiprocessing: Plugin is defined as always enabled.
Nuitka:INFO: Starting Python compilation with Nuitka '1.1' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyqt5: Injecting pre-module load code for module 'PyQt5':
Nuitka-Plugins:INFO: pyqt5:     Adding binary folder to runtime 'PATH' environment variable for proper Qt loading.
Nuitka-Plugins:INFO: pyqt5: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: pyqt5:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyqt5:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':   
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.                                      
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                          
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 599 files (no progress information available).
Nuitka-Scons:INFO: Running 'link @C:\\Users\\Jon\\AppData\\Local\\Temp\\tmp17x8918t.lnk' took 169.77 seconds
Nuitka-Scons:INFO: Compiled 599 C files using clcache with 599 cache hits and 0 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: matplotlib: Included 183 data files due to package data for 'matplotlib.
Nuitka-Plugins:INFO: matplotlib: Included data file 'matplotlib\mpl-data\matplotlibrc' due to updated matplotlib config file with backend to use.     
Nuitka-Plugins:INFO: pyqt5: Including Qt plugins 'iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,styles' below 'PyQt5\qt-plugins'.
Nuitka-Plugins:INFO: numpy: Found 42 files DLLs from numpy installation.
Nuitka:INFO: Keeping build directory 'D:\\life\\uwo\\ece\\phd\\code\\nuitka\\standalone\\attempt_7\\vedo_compile.build'.
Nuitka:INFO: Successfully created 'D:\\life\\uwo\\ece\\phd\\code\\nuitka\\standalone\\attempt_7\\vedo_compile.dist\\vedo_compile.exe'.
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

**_This is the reproduction code (in file vedo_compile.py):_**

```
"""
Minimum Working Example
"""
import vedo as ve



def display(file_name):
    """Nothin' but a test...
    """

    b = ve.Box(pos=(0.5,0.5,0.5), length=1, width=1, height=1).alpha(0)
    axis_opts={
                'titleFont': 'Theemim',
                'labelFont': 'Theemim',
                'numberOfDivisions':10,
                'zxGrid2':True,        # show zx plane on opposite side of the bounding box
                'yzGrid2':True,
                'xyAlpha':0.2,
                'yzAlpha':0.2,
                'zxAlpha':0.2
               }

    # Create visualization window
    vis = ve.plotter.Plotter(bg='black', size=(1080, 960), sharecam=False)

    vis.show(b, axes=axis_opts, interactive=True, zoom=1.5)


if __name__ == "__main__":
    print("Manual debugging run")

    display("nmk")
```

When run using:
`python vedo_compile.py`
the output is the following:

![vedo_compile](https://user-images.githubusercontent.com/8246894/197423764-9212b864-aa3c-4be3-99e5-e27abc0ad131.png)

When compiled using:
`python -m nuitka --enable-plugin=numpy --enable-plugin=pyqt5 --enable-plugin=multiprocessing --enable-plugin=matplotlib --output-dir=path/to/output/folder --standalone vedo_compile.py`

And then run from inside the .dist folder, the output is the following:
```
./vedo_compile.exe 
Traceback (most recent call last):
  File "path\to\dist\folder\vedo_compile.dist\vedo_compile.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "path\to\dist\folder\vedo_compile.dist\vedo\__init__.py", line 137, in <module vedo>
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'path\\to\\dist\\folder\\vedo_compile.dist\\vedo\\fonts/'
```

Once again, any help or suggestions you can provide on this would be much appreciated. Thanks for all your efforts Kay, and everybody else involved.
Cheers 
j

**Comment by kayhayen** [comment]
This is part of the 1.1.7 hotfix release I just made. You always had the option to use --include-package-data, but this is now automatically included.
