### ISSUE TITLE
Crash on «import lightgbm» if «--python-flag=no_docstrings»

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1855]
Let's consider sample program using LightGBM and nuitka call for compilation on Linux:

https://github.com/belonesox/nuitka-light-gdm-troubles-
branch
«no_docstrings»

* `./reproduce-me.sh` to (re)install virtual environment for install/build/run compiled

Running results we get crush on «import lightgbm»
```
Traceback (most recent call last):
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/test-lightgbm.dist/test-lightgbm.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/test-lightgbm.dist/lightgbm/__init__.py", line 21, in <module lightgbm>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/test-lightgbm.dist/lightgbm/dask.py", line 1088, in <module lightgbm.dask>
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/test-lightgbm.dist/lightgbm/dask.py", line 1143, in DaskLGBMClassifier
AttributeError: 'NoneType' object has no attribute 'partition'
```

The problem option is «--python-flag=no_docstrings», without it all works fine. 
But why, if anyone wants to strip docstring… 

Same problem exists even with nuitka factory.

**Comment by kayhayen** [comment]
People are often controlling behaviour with doc strings. Like automatically setting function defaults to the documentation, etc. and this might be a case. I will look at it.

Ultimately what might have to happen is that we white list some things, that must retain some doc strings. Question of course is how this code runs with pure Python and `-O`

**Comment by belonesox** [comment]
> that we white list some things, that must retain some doc strings

Is it possible to add some options " do not strip from specific python modules "?

> this code runs with pure Python and -O

Python command line options «-O», «Remove assert statements and any code conditional on the value of [__debug__](https://docs.python.org/3/library/constants.html#debug__)» ?
Why, but looks OK here.
```
$ pipenv run python -O ./test-lightgbm.py
Loading data...
Starting training...
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.028972 seconds.
You can set `force_col_wise=true` to remove the overhead.
Training until validation scores don't improve for 5 rounds
Did not meet early stopping. Best iteration is:
[20]    valid_0's l1: 0.423421  valid_0's l2: 0.19131
Saving model...
Starting predicting...
[0.66892284 0.73857574 0.75782182 ... 0.27643805 0.44325521 0.47767568]
```

**Comment by kayhayen** [comment]
Might have been `-OO` then.

**Comment by belonesox** [comment]
> Might have been -OO then.

Yes, with -OO, the bug reproduced :(
```
$   pipenv run python -OO ./test-lightgbm.py                                              ↑
Traceback (most recent call last):
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/./test-lightgbm.py", line 7, in <module>
    import lightgbm as lgb
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/.venv/lib/python3.10/site-packages/lightgbm/__init__.py", line 21, in <module>
    from .dask import DaskLGBMClassifier, DaskLGBMRanker, DaskLGBMRegressor
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/.venv/lib/python3.10/site-packages/lightgbm/dask.py", line 1088, in <module>
    class DaskLGBMClassifier(LGBMClassifier, _DaskLGBMModel):
  File "/home/stas/projects/nuitka-wtf/nuitka-light-gdm-troubles/.venv/lib/python3.10/site-packages/lightgbm/dask.py", line 1143, in DaskLGBMClassi
fier
    _before_kwargs, _kwargs, _after_kwargs = _base_doc.partition('**kwargs')
AttributeError: 'NoneType' object has no attribute 'partition'
```

**Comment by kayhayen** [comment]
Well, Nuitka allows the second `-O` and the first `-O` to be separated, and gives no hint to what this needs, or when it will work or not. I am open however to anti-bloat measures for this. If you look at the code there, and believe the doc strings are only optional, you can patch it through user yaml files, and then of course we can integrate that in our standard config as well.

Eliminating doc strings seems very much worth it, not to speak of the obfuscucation parts of having them for your code.

As an enhancement, Nuitka probably needs to make it clear to the user, that it expects from the Python flags, that the original program already works with some options.

**Comment by kayhayen** [comment]
There is https://nuitka.net/doc/nuitka-package-config.html#where-else-to-look and the post series should give you enough insight to make the change.

**Comment by KRRT7** [comment]
fixed and merged previously.
