### ISSUE TITLE
ModuleNotFoundError while importing precompiled azure packages

### ISSUE THREAD

**Issue by ilya-brykau** [Nuitka/Nuitka#1862]
Hi, i get an ModuleNotFoundError: while trying to import a precompiled azure.mgmt.compute package

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.1.5
Commercial: None
Python: 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
Flavor: Unknown
Executable: /Users/ilya.brykau/Project/venv-recovery-agent/bin/python
OS: Darwin
Arch: arm64
```

* How did you install Nuitka and Python

pip install nuitka

* The specific PyPI names and versions

```
 astroid==2.8.6
attrs==21.2.0
azure-common==1.1.28
azure-core==1.24.2
azure-identity==1.10.0
azure-mgmt-compute==29.0.0
azure-mgmt-core==1.3.2
azure-mgmt-network==21.0.1
azure-sdk-trim @ git+https://github.com/clumio-code/azure-sdk-trim@530c5ca20d42e027b5d29bb244ea26701fd2ecdb
bottle==0.12.19
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.8
colorama==0.4.5
conan==1.44.0
coverage==6.5.0
cryptography==36.0.1
dataclasses-json==0.5.6
distro==1.6.0
fasteners==0.16.3
flake8==4.0.1
humanize==4.3.0
idna==3.3
inflection==0.5.1
iniconfig==1.1.1
isodate==0.6.1
isort==5.10.1
Jinja2==3.0.3
lazy-object-proxy==1.6.0
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow-enum==1.5.1
mccabe==0.6.1
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
mypy==0.971
mypy-extensions==0.4.3
node-semver==0.6.1
Nuitka==1.1.5
oauthlib==3.2.0
orderedset==2.0.3
packaging==21.3
parameterized==0.8.1
patch-ng==1.17.4
platformdirs==2.4.0
pluggy==1.0.0
pluginbase==1.0.1
portalocker==2.5.1
psutil==5.8.0
py==1.11.0
py-zabbix==1.1.7
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.10.0
PyJWT==1.7.1
pylint==2.11.1
pyOpenSSL==21.0.0
pyparsing==3.0.6
pytest==6.2.5
pytest-cov==3.0.0
pytest-random-order==1.0.4
python-dateutil==2.8.2
python-json-logger==2.0.2
PyYAML==5.4.1
requests==2.26.0
requests-oauthlib==1.3.1
responses==0.16.0
six==1.16.0
teamcity-messages==1.29
toml==0.10.2
tomli==1.2.2
tqdm==4.62.3
types-cryptography==3.3.14
types-enum34==1.1.3
types-ipaddress==1.0.3
types-pyOpenSSL==21.0.3
types-requests==2.26.1
typing-inspect==0.7.1
typing_extensions==4.0.1
urllib3==1.26.7
wrapt==1.13.3
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
Tried to import a compiled module using python interpreter and got the following exception
```
>>> from compute import ComputeManagementClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilya.brykau/Project/draas-recovery-agent/compute/__init__.py", line 9, in <module compute>
ModuleNotFoundError: No module named 'compute._compute_management_client'
```

* Provide in your issue the Nuitka options used
Compiled the compute package using:
`--module /Users/ilya.brykau/Project/venv-recovery-agent/lib/python3.9/site-packages/azure/mgmt/compute --include-package=azure.mgmt.compute`
Also tried adding `--no-pyi` but it didnt change anything

How do i precomile azure mgmt packages and include them to applcation compilation?

**Comment by kayhayen** [comment]
Compiling in module or accelerated mode cannot include packages with extension modules and python source code mixed. This is currently not supported, use standalone mode or do not include modules that are not your module to distribute.
