### ISSUE TITLE
ModuleNotFoundError: No module named '_distutils_hack' with Nuitka 1.1.7 on Python 3.9.13

### ISSUE THREAD

**Issue by Honghe** [Nuitka/Nuitka#1864]
Environment:
- Windows 10
- conda 22.9.0
- Python 3.9.13

```
$ pip install nuitka==1.1.7
Collecting nuitka
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bb/50/d98fcb435c928e23dbc22a415dc2eb4eaf67e3e583823cb9f2afa834432e/Nuitka-1.1.7.tar.gz (3.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\x\miniconda3\envs\py39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\x\\AppData\\Local\\Temp\\pip-install-0uts_hvw\\nuitka_841212c36e4849f4890a5731f00adb80\\setup.py'"'"'; __file__='"'"'C:\\Users\\x\\AppData\\Local\\Temp\\pip-install-0uts_hvw\\nuitka_841212c36e4849f4890a5731f00adb80\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\x\AppData\Local\Temp\pip-pip-egg-info-9m3iua1m'
         cwd: C:\Users\x\AppData\Local\Temp\pip-install-0uts_hvw\nuitka_841212c36e4849f4890a5731f00adb80\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\x\miniconda3\envs\py39\lib\site-packages\setuptools\__init__.py", line 8, in <module>
        import _distutils_hack.override  # noqa: F401
    ModuleNotFoundError: No module named '_distutils_hack'
    ----------------------------------------
```

It is OK on Python 3.9.12

**Comment by kayhayen** [comment]
This looks like your pip or setuptools is broken, must be an Anaconda thing. As an side, there is a conda package of Nuitka that you ought to use anyway. I am not sure how well it works to be honest, since I only recently took over maintainership and found that it was broken, but it ought to be good now.
