### ISSUE TITLE
Win10 vtkmodules "assert self.dll_directory is not None" from ZmqPlugin.py

### ISSUE THREAD

**Issue by jdegenstein** [Nuitka/Nuitka#1867]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
(Note that I also tested against nuitka==1.1.7 and got the same exact error)
```
$ python -m nuitka --version
1.2rc7
Commercial: None
Python: 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\user\.conda\envs\nutikaCQE\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python
`pip install nuitka` into a conda env originally then using the factory package

* The specific PyPI names and versions
```
$ python -m pip freeze
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
pyzmq==24.0.1
```
* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```py
#runZMQ.py
import zmq
```

Full traceback and command using the above:
```
$ python -m nuitka --show-progress --standalone --follow-imports --include-plugin-directory=C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages runZMQ.py
Nuitka-Options:INFO: Used command line options: --show-progress --standalone --follow-imports --include-plugin-directory=C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages runZMQ.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc7' on Python '3.9' commercial grade 'not installed'.
Nuitka-Inclusion:WARNING: Cannot follow import to module 'site-packages.casadi.tools.structure' because of 'SyntaxError'.
Nuitka-Plugins:INFO: pyzmq: Detected usage of 'delvewheel' version '1.0.1' in module 'site-packages.vtkmodules'.
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\MainControl.py", line 929, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\MainControl.py", line 168, in _createNodeTree
    Recursion.checkPluginPath(plugin_filename=plugin_filename, module_package=None)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 326, in checkPluginPath
    checkPluginSinglePath(plugin_filename, module_package=module_package)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 303, in checkPluginSinglePath
    _addIncludedModule(module)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 250, in _addIncludedModule
    checkPluginSinglePath(sub_path, module_package=module.getFullName())
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 294, in checkPluginSinglePath
    module = recurseTo(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 73, in recurseTo
    module, added_flag = _recurseTo(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 42, in _recurseTo
    module, is_added = Building.buildModule(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\tree\Building.py", line 1283, in buildModule
    ) = readSourceCodeFromFilenameWithInformation(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\tree\SourceHandling.py", line 182, in readSourceCodeFromFilenameWithInformation
    source_code_modified, contributing_plugins = Plugins.onModuleSourceCode(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\plugins\Plugins.py", line 783, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(module_name, source_code)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\plugins\standard\ZmqPlugin.py", line 104, in onModuleSourceCode
    assert self.dll_directory is not None
AssertionError
```

**Comment by kayhayen** [comment]
If you read up on what `--include-plugin-directory=C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages` does, you will realize, it's totally wrong to do that.

**Comment by jdegenstein** [comment]
Apologies for that mistake, I have corrected that issue and I am getting a very similar error message. I was able to build `runZMQ.py` but I have a new `run-vtkmodules.py` that causes a very similar failure.

Same environment as above (nuitka-1.2rc7 from factory).
```
vtkmodules==9.1.0
```
```py
#run-vtkmodules.py
import vtkmodules
```
```
$ python -m nuitka --show-progress --standalone run-vtkmodules.py
Nuitka-Options:INFO: Used command line options: --show-progress --standalone run-vtkmodules.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc7' on Python '3.9' commercial grade 'not installed'.
Nuitka-Progress:INFO: PASS 1:
Nuitka-Progress:INFO: Optimizing module '__main__', 0 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for '__main__'.
Nuitka-Progress:INFO: Not changed, but retrying one more time.
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Plugins:INFO: pyzmq: Detected usage of 'delvewheel' version '1.0.1' in module 'vtkmodules'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\MainControl.py", line 929, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\MainControl.py", line 212, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\optimizations\Optimization.py", line 343, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\optimizations\Optimization.py", line 297, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\optimizations\Optimization.py", line 188, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\optimizations\Optimization.py", line 150, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 447, in considerUsedModules
    used_module = recurseTo(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 73, in recurseTo
    module, added_flag = _recurseTo(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\importing\Recursion.py", line 42, in _recurseTo
    module, is_added = Building.buildModule(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\tree\Building.py", line 1283, in buildModule
    ) = readSourceCodeFromFilenameWithInformation(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\tree\SourceHandling.py", line 182, in readSourceCodeFromFilenameWithInformation
    source_code_modified, contributing_plugins = Plugins.onModuleSourceCode(
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\plugins\Plugins.py", line 783, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(module_name, source_code)
  File "C:\Users\user\.conda\envs\nutikaCQE\Lib\site-packages\nuitka\plugins\standard\ZmqPlugin.py", line 104, in onModuleSourceCode
    assert self.dll_directory is not None
AssertionError
```
Thanks for your help.

**Comment by kayhayen** [comment]
Yes, notice how the previous error was for a package `site-packages.vtkmodules` which is of course not going to be importable, but would have many unused code alongside it. And I didn't notice that it's not about zmq, but `vtkmodules` which would be very reproducible.

**Comment by kayhayen** [comment]
Something rather strange, I checked with Anaconda and their package, and PyPI with your version, but `vtkmodules` does not use `delvewheel` there and just works for me. I have no clue why. Can you email me privately the `__init__.py` of said package.

**Comment by jdegenstein** [comment]
Thanks very much for your help so far. I was wondering why `pip list` did not show either vtk or vtkmodules, and I eventually realized this package is being "installed" by PyPI `cadquery-ocp==7.6.3a0` (by installed it is really just copying a folder called vtkmodules into site-packages). After looking at the `__init__.py` file inside the cadquery-ocp wheel I can confirm there is some additional code for `def _delvewheel_init_patch_1_0_1(): ....` inside of that file which is not present in the vanilla-vtk distribution.

I was able to get the build running again by `pip install vtk` (build is for a project I work on called CQ-editor) and it is quite a large build so it is still running. I am closing this for now because I really do not want to waste any more of your time on this.

Thanks again.

**Comment by kayhayen** [comment]
Well I was actually interested in finding out why that delvewheel patch was not working, it's supposed to be automatically supported.

**Comment by jdegenstein** [comment]
ok, the only missing piece you should need to replicate is the install that ultimately requires `cadquery-ocp`. The command below will install `cadquery-ocp` among other deps, along with the oddball vtkmodules directory.

```
pip install --pre git+https://github.com/cadquery/cadquery casadi==3.5.5
```
From this point all you have to do is run the command above against `run-vtkmodules.py` and you should get the same error.

**Comment by kayhayen** [comment]
Yes, now I got that file, but it wasn't giving the error. But it seems it wants to include 6000+ DLLs now, something is awfully wrong there, but maybe on another day, this is pre-release software. The good news is I guess that the delvewheel code was working just fine, lets see if it runs. But whatever this is, seems absurd.

**Comment by kayhayen** [comment]
After including only 5500 of them, it works... so that is probably good. I guess the code is in flux there, but if it is a upcoming vtkmodules, it appears to be good that is now supported automatically already. Old vtkmodules apparently had no DLL code at all, or it was not really needed, not sure now, but there is no config to conflict with (plugin and yaml config for DLLs), so I assume it never worked on Windows, but I think it does, but this will need to be kept in mind, should this ever come up.

Thanks, this was helpful. Generally I want Nuitka to run where Python runs, disregarding how bad an installation it is, because those bugs sometimes highlight weaknesses in our code, that will also show in other more legal situations later or reveal more general problems.
