### ISSUE TITLE
No package metadata was found for tkinter-tooltip

### ISSUE THREAD

**Issue by justabettergamer** [Nuitka/Nuitka#1868]
here is my code : 
`import customtkinter
from tktooltip import ToolTip

app = customtkinter.CTk()
app.title("CustomTkinter x Tooltip")
app.geometry("150x100")

switch = customtkinter.CTkButton(app, text = "test")
switch.grid(pady=30)

ToolTip(switch, msg="Hovering Message", delay=1)

app.mainloop()`
It is working perfectly fine when I run my .py file.
here is how I compile it with nuitka : 
` -m nuitka --clang --mingw64 --onefile --plugin-enable=tk-inter --include-data-dir="C:\Users\max\AppData\Local\Programs\Python\Python310\Lib\site-packages\customtkinter"=customtkinter test2.py`

here is what I get when I start the exe : 
`  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\tktooltip\version.py", line 6, in <module tktooltip.version>
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\importlib\metadata\__init__.py", line 984, in version
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\importlib\metadata\__init__.py", line 957, in distribution
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\importlib\metadata\__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for tkinter-tooltip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\test2.py", line 2, in <module>
    from tktooltip import ToolTip
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\tktooltip\__init__.py", line 17, in <module tktooltip>
  File "C:\Users\max\AppData\Local\Temp\ON01AE~1\tktooltip\version.py", line 8, in <module tktooltip.version>
ModuleNotFoundError: No module named 'setuptools_scm'`

I tested multiple option including --includfe-data-dir="C:\Users\max\AppData\Local\Programs\Python\Python310\Lib\site-packages\tktooltip"=tktooltip, --follow-imports

Any idea how to fix it ? Thank you very much :)

**Comment by kayhayen** [comment]
You didn't include the version information, can you provide it.

**Comment by justabettergamer** [comment]
The problem came from my nuitka version, was 1.1.3, you fixed it, thank you for your amazing work !
