### ISSUE TITLE
Torchvision with timm problem

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#1872]
I have the following script:

```
#!/usr/bin/python

import timm
import torch

print(torch.__version__)
print ("ABC")
```

Build with the following command:
```
nuitka3 --standalone --enable-plugin=numpy 1.py
```

Run binary on the same host gives error:
```Traceback (most recent call last):
  File "/home/build/torch-compile/1.dist/torch/_sources.py", line 21, in get_source_lines_and_file
  File "/home/build/torch-compile/1.dist/inspect.py", line 1129, in getsourcelines
  File "/home/build/torch-compile/1.dist/inspect.py", line 958, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/build/torch-compile/1.dist/1.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/__init__.py", line 2, in <module timm>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/__init__.py", line 1, in <module timm.models>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/beit.py", line 50, in <module timm.models.beit>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/helpers.py", line 21, in <module timm.models.helpers>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/fx_features.py", line 18, in <module timm.models.fx_features>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/__init__.py", line 10, in <module timm.models.layers>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/conv_bn_act.py", line 9, in <module timm.models.layers.conv_bn_act>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/create_norm_act.py", line 12, in <module timm.models.layers.create_norm_act>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/evo_norm.py", line 32, in <module timm.models.layers.evo_norm>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/create_act.py", line 7, in <module timm.models.layers.create_act>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/build/torch-compile/1.dist/timm/models/layers/activations_jit.py", line 18, in <module timm.models.layers.activations_jit>
  File "/home/build/torch-compile/1.dist/torch/jit/_script.py", line 1340, in script
  File "/home/build/torch-compile/1.dist/torch/jit/frontend.py", line 234, in get_jit_def
  File "/home/build/torch-compile/1.dist/torch/_sources.py", line 96, in parse_def
  File "/home/build/torch-compile/1.dist/torch/_sources.py", line 28, in get_source_lines_and_file
OSError: Can't get source for <compiled_function swish_jit at 0x7f002bf33790>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
```
Versions:
Python 3.10.8
Nuitka3 1.1.6
timm 0.6.11
torch 1.12.1
Linux

**Comment by kayhayen** [comment]
Do you expect to compile on the target machine, it seems that `timm` is using torch script and requires JIT compilation of its source code on the target hardware, because as you can see, `timm` won't launch without doing that. Not sure how its supposed to be deployed, can you give any insights there, if this is something that people typically avoid, or will your program require compilers on the target machine, or would you even include them in your binary?

**Comment by ioctl-user** [comment]
Not sure I understand you.
In my case timm is indirect torch dependency in library, that I use.

If binary program requires compiler, I would prefer option -- include it or not, because compiler is likely installed in UNIX system and unlikely in Windows.

**Comment by kayhayen** [comment]
You are not alone in that, it seems that timm just does it, but also offers a way to disable it, that you are not using and not aware of, but that Nuitka ought to add somewhat automatically unless torchscript is explicitely required.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.2.7 that I just made.
