### ISSUE TITLE
using "dotenv" gives "Starting Path Not Found"

### ISSUE THREAD

**Issue by legotheboss** [Nuitka/Nuitka#1874]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

````
❯ python3 -m nuitka --version
1.1.8
Commercial: None
Python: 3.9.6 (default, Jun 29 2021, 05:25:02) 
Flavor: Homebrew Python
Executable: /usr/local/Cellar/python@3.9/3.9.6/bin/python3.9
OS: Darwin
Arch: x86_64
````

 Stack trace
````
Traceback (most recent call last):
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/custom_bot.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/utilities.py", line 11, in <module utilities>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/webdriver_manager/chrome.py", line 4, in <module webdriver_manager.chrome>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/webdriver_manager/core/download_manager.py", line 3, in <module webdriver_manager.core.download_manager>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/webdriver_manager/core/http.py", line 4, in <module webdriver_manager.core.http>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/webdriver_manager/core/config.py", line 9, in <module webdriver_manager.core.config>
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/dotenv/main.py", line 332, in load_dotenv
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/dotenv/main.py", line 296, in find_dotenv
  File "/var/folders/x2/_cs4hm4n35l_kdglc62l4v6c0000gn/T//onefile_1109_1667872192_355921/dotenv/main.py", line 253, in _walk_to_root
OSError: Starting path not found
````
* How did you install Nuitka and Python

  Installed via Pip3, Python via brew install python@3.9

* The specific PyPI names and versions

-     Selenium 4.6.0
-     webdriver_manager 4.64.1

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

- Issue in [dotenv package](https://github.com/theskumar/python-dotenv/blob/main/src/dotenv/main.py#L253)

* Provide in your issue the Nuitka options used

`python3.9 -m nuitka  --include-package-data=selenium --disable-plugin=anti-bloat --onefile -o custom_bot.bin custom_bot.py`

* Note if this is a regression

This was working fine prior to my upgrade to Mac OS 13.0. The same executable built on Windows works just fine, without the issue.

**Comment by kayhayen** [comment]
You didn't provide the minimal reproducer. Please do.

**Comment by legotheboss** [comment]
@kayhayen sorry, here is an example program that can reproduce the error

````
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

s = Service(ChromeDriverManager().install())
o = webdriver.ChromeOptions()
o.add_experimental_option('excludeSwitches', ['enable-logging'])
browser = webdriver.Chrome(service=s, options=o)
browser.open("https://google.com")
````

**Comment by kayhayen** [comment]
It seems the `dotenv` module is trying to to walk the frame stack during a call to find the package directory, it should work with and it seems to fail with that, although the directory is probably detected from the code object and frames. So this is a missing file, that does not exist, however, the reaction is different, kind of tricky stuff.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

The dotenv checks for package directories to exist, which they do not, unless data files enforce their presence. Added a workaround that removes the directory existance check. With this, the example just works. Has nothing to do with webderiver per se, this could affect all dotnet using packages that use the default scan method.

**Comment by legotheboss** [comment]
Thank you, seems the factory build is currently failing. I ran into the same issue on MacOS as the Github Actions Ubuntu job did. I removed the code causing this issue in the Options.py file and file was able to execute successfully.

````
Traceback (most recent call last):
[9](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:10)
  File "/home/runner/work/Nuitka/Nuitka/nuitka/__main__.py", line 138, in <module>
[10](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:11)
    main()
[11](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:12)
  File "/home/runner/work/Nuitka/Nuitka/nuitka/__main__.py", line 92, in main
[12](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:13)
    Options.parseArgs()
[13](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:14)
  File "/home/runner/work/Nuitka/Nuitka/nuitka/Options.py", line 193, in parseArgs
[14](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:15)
    if options.disable_dll_dependency_cache:
[15](https://github.com/Nuitka/Nuitka/actions/runs/3439825895/jobs/5737564221#step:5:16)
AttributeError: Values instance has no attribute 'disable_dll_dependency_cache'
````

**Comment by kayhayen** [comment]
This is going into the 1.2.1 hotfix, the factory issues are bound to happen. I believe I just pushed a fix, thanks for working around to try it.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.2.1 and 1.2.2 that I just made.
