### ISSUE TITLE
Error find win32com package Dispatche method under Windows OS  PYTHONCOM310.DLL

### ISSUE THREAD

**Issue by igaisin** [Nuitka/Nuitka#1879]
Environment:
Windows 11
Python:3.10.7
Nuitka 'Nuitka-1.2'

How did you install Nuitka and Python
pip

Provide in your issue the Nuitka options used
python -m nuitka --onefile --windows-disable-console --standalone --enable-plugin=tk-inter --follow-imports --windows-icon-from-ico=update.ico --output-dir=..\deploy_47i .\janartu.py

Error during nuitka standalone compilation:
Detecting used DLLs: 81.0%|████████████████████▏    | 17/21, win32comext\shell\shell.pydTraceback (most recent call last):
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\MainControl.py", line 972, in main
    detectUsedDLLs(
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 722, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 683, in _detectUsedDLLs
    used_dlls = _detectBinaryDLLs(
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\Standalone.py", line 584, in _detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 93, in detectBinaryPathDLLsWindowsDependencyWalker
    result = detectDLLsWithDependencyWalker(
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\DependsExe.py", line 195, in detectDLLsWithDependencyWalker
    result = parseDependsExeOutput(output_filename)
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\DependsExe.py", line 137, in parseDependsExeOutput
    return _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"))
  File "C:\Users\*\Documents\projects\verder\venv\lib\site-packages\nuitka\freezer\DependsExe.py", line 129, in _parseDependsExeOutput2
    assert os.path.isfile(dll_filename), (dll_filename, line)
AssertionError: ('c:\\windows\\syswow64\\pythoncom310.dll', '     [ ? ] PYTHONCOM310.DLL')

My nuitka --version output:
emres-Air:inference emre$ python -m nuitka --version
1.2
Commercial: None
Python: 3.10.7
Flavor: Unknown
Executable: python
OS: Windows 11 22H2 22621.674
Arch: x86_64

Thanks a lot in advance.

**Comment by igaisin** [comment]
found it, just need to find 
'pythoncom*.dll' 
and copy it to 
'c:\windows\syswow64\pythoncom*.dll'

**Comment by kayhayen** [comment]
Not the case, but this lacks a reproducer, so it's basically a useless report.
