### ISSUE TITLE
wrapped file does not start

### ISSUE THREAD

**Issue by krolaper** [Nuitka/Nuitka#1891]
1.2
Commercial: None
Python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/odinson/PycharmProjects/Panning/Video/all/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Linuxmint (based on Ubuntu) 21

There is my [project](https://send.monks.tools/download/d75dd84c3a5c3c52/#hnFFFSLtfmnfzkPQE8U46g).
created from the [YOLOv5](https://github.com/ultralytics/yolov5) project files
to which I added only my main script "main.py"
It is a gui menu for working with yolov5 scripts. At first I called other scripts via full import at the right moment and after packaging I had a graphical menu run, but there was no connection with other scripts (probably nuitka did not define the necessary scripts). After I changed to a more correct spelling, namely to specify import at the beginning, and then only to call the desired function at the right moment. But after packaging the finished file just did not start (automatic completion occurred). Tell me how to pack the project, or try to pack my.

Start code package project. Linux system, python 3.10.6

`python -m nuitka --standalone --follow-imports --output-dir=result-linux --enable-plugin=tk-inter,numpy,torch,anti-bloat --disable-console --product-name=aigod --linux-icon=aigod.icol main.py`

I tried to open through the terminal, so I would see errors. Below they are. 

```
Traceback (most recent call last):
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/main.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/detect.py", line 34, in <module detect>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/__init__.py", line 964, in <module torch>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/_meta_registrations.py", line 16, in <module torch._meta_registrations>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/_refs/__init__.py", line 14, in <module torch._refs>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/_prims/__init__.py", line 31, in <module torch._prims>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/_subclasses/__init__.py", line 3, in <module torch._subclasses>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/_subclasses/fake_tensor.py", line 14, in <module torch._subclasses.fake_tensor>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/fx/__init__.py", line 84, in <module torch.fx>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/fx/_symbolic_trace.py", line 1077, in <module torch.fx._symbolic_trace>
  File "/home/odinson/PycharmProjects/Panning/Video/all/relize-linux/main.dist/torch/fx/_symbolic_trace.py", line 1009, in wrap
NotImplementedError: wrap must be called at the top level of a module
```

when packing writes:

```Nuitka-Plugins:WARNING: torch: This plugin has been deprecated, do not enable it anymore.```

and it also mentions warnings related to ipython. But it is present in import in other scripts.

```
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.mock' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.util' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.result' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.case' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.suite' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.loader' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.main' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.runner' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.signals' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.async_case' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest._log' encountered.
Nuitka-Plugins:INFO: implicit-imports: Injecting pre-module load code for module 'cv2':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.getipython' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.release' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.application' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.embed' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.interactiveshell' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.sysinfo' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.frame' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.ipapp' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.usage' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.completer' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.crashhandler' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.formatters' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.history' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magic' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.shellapp' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.extensions' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.extensions.storemagic' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.interactiveshell' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.paths' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.importstring' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.path' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.profiledir' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.process' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils._process_posix' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils._process_common' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.py3compat' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.encoding' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.async_helpers' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.terminal' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.debugger' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.magics' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.pt_inputhooks' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.prompts' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.ptutils' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.terminal.shortcuts' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.decorators' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.docs' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.displayhook' encountered.         
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.error' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.lib' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.lib.clipboard' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.testing' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.testing.skipdoctest' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.text' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.debugger' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.PyColorize' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.coloransi' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.excolors' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.ipstruct' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.colorable' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.pylabtools' encountered.       
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.contexts' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.display' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.display' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.display_functions' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.lib.display' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.auto' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.basic' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.code' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.config' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.display' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.execution' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.extension' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.history' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.logging' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.namespace' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.osm' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.packaging' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.pylab' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magics.script' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.magic_arguments' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.oinspect' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.page' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.alias' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.openpy' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.data' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.lib.pretty' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.dir2' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.wildcard' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.io' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.capture' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.displaypub' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.macro' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.module_paths' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.timing' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.inputtransformer2' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.sentinel' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.ultratb' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.display_trap' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.latex_symbols' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.generics' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils._sysinfo' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.hooks' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.prefilter' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.autocall' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.builtin_trap' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.compilerop' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.events' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.extensions' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.logger' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.payload' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.strdispatch' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.utils.syspathcontext' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.completerlib' encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'IPython.core.splitinput' encountered.`
```
**pip freeze**
absl-py==1.3.0
altgraph==0.17.3
asttokens==2.1.0
backcall==0.2.0
bottle==0.12.23
bottle-websocket==0.2.9
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
contourpy==1.0.6
cycler==0.11.0
decorator==5.1.1
dlib==19.24.0
Eel==0.14.0
executing==1.2.0
fonttools==4.38.0
future==0.18.2
gevent==22.10.2
gevent-websocket==0.10.1
google-auth==2.14.0
google-auth-oauthlib==0.4.6
greenlet==2.0.1
grpcio==1.50.0
idna==3.4
imageio==2.22.4
ipython==8.6.0
jedi==0.18.1
kiwisolver==1.4.4
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
networkx==2.8.8
Nuitka==1.2
numpy==1.23.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
opencv-python==4.6.0.66
ordered-set==4.1.0
packaging==21.3
pafy==0.5.5
pandas==1.5.1
parso==0.8.3
patchelf==0.16.1.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
prompt-toolkit==3.0.32
protobuf==3.19.6
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyglet==2.0.0
Pygments==2.13.0
pyinstaller-hooks-contrib==2022.13
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.19.3
scipy==1.9.3
seaborn==0.12.1
six==1.16.0
stack-data==0.6.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
thop==0.1.1.post2209072238
tifffile==2022.10.10
torch==1.13.0
torchvision==0.14.0
tqdm==4.64.1
traitlets==5.5.0
typing_extensions==4.4.0
urllib3==1.26.12
wcwidth==0.2.5
Werkzeug==2.2.2
whichcraft==0.6.1
youtube-dl==2021.12.17
zope.event==4.5.0
zope.interface==5.5.1

**Comment by krolaper** [comment]
please help me with the correct project compilation command.

**Comment by kayhayen** [comment]
This seems to be an issue with torch 1.3.0 not yet being supported, it is relatively new. The torch plugin has been superseded by a generic Yaml based configuration, and has no effect anymore, well it will slow down some things. You might want to try and downgrade. Changes to your program all ought to not be necessary at all. Nuitka is fully compatible with all forms of imports, but you may be hiding a problem to a later time only, with good reports like this one, no issue to make them until it works.

**Comment by kayhayen** [comment]
As an aside, I recommed you to place your program files in a package, that way all things will be easier.

**Comment by krolaper** [comment]
> This seems to be an issue with torch 1.3.0 not yet being supported, it is relatively new. The torch plugin has been superseded by a generic Yaml based configuration, and has no effect anymore, well it will slow down some things. You might want to try and downgrade. Changes to your program all ought to not be necessary at all. Nuitka is fully compatible with all forms of imports, but you may be hiding a problem to a later time only, with good reports like this one, no issue to make them until it works.

I will try an earlier version of torch, but the recommendation of yolov5 includes at least 1.7.0.



> As an aside, I recommed you to place your program files in a package, that way all things will be easier.

And tell me how to put the files in the package and after how to correctly call the nuitka command with which parameters?

**Comment by krolaper** [comment]
Where can I see the list of library versions with the latest version nuitka?

**Comment by kayhayen** [comment]
Actually kind of all are supported, but every PyPI release can invalidate that information. Right now we do not have automatic regression testing of all of PyPI, but we hope to get there.

This is part of the hotfix release 1.2.2 that I just made.

**Comment by krolaper** [comment]
> Actually kind of all are supported, but every PyPI release can invalidate that information. Right now we do not have automatic regression testing of all of PyPI, but we hope to get there.
> 
> This is part of the hotfix release 1.2.2 that I just made.

Updated, but did not help. Still the same error:
`Nuitka-Plugins:WARNING: torch: This plugin has been deprecated, do not enable it anymore.`
version of pytorch 1.3.0 as said cannot be installed, it is not in official source. only from version 1.11.0
