### ISSUE TITLE
Missing data files when using dash

### ISSUE THREAD

**Issue by yes89929** [Nuitka/Nuitka#1913]
# Environments
python 3.9.13(use venv)
Windows 11
Nuitka 1.2.3

# Reproduction
Install open3d
`pip install open3d`

Code
```
import open3d as o3d
import numpy as np

def main():
    ply_point_cloud = o3d.data.PLYPointCloud()
    print(ply_point_cloud.path)
    pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
    print(pcd)
    print(np.asarray(pcd.points))
    o3d.visualization.draw_geometries([pcd],
                                    zoom=0.3412,
                                    front=[0.4257, -0.2125, -0.8795],
                                    lookat=[2.6172, 2.0475, 1.532],
                                    up=[-0.0694, -0.9768, 0.2024])
if __name__ == "__main__":
    main()
```

# Build
`python -m nuitka ../open3d-visualization.py --standalone --enable-plugin=numpy`

# Run
```
PS C:\Users\res\Downloads\open3d-nuitka test\build\open3d-visualization.dist> .\open3d-visualization.exe
Traceback (most recent call last):
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\open3d-visualization.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\open3d\__init__.py", line 102, in <module open3d>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\open3d\visualization\__init__.py", line 38, in <module open3d.visualization>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\open3d\visualization\draw_plotly.py", line 31, in <module open3d.visualization.draw_plotly>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\dash\__init__.py", line 17, in <module dash>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\res\DOWNLO~1\OPEN3D~1\build\OPEN3D~1.DIS\dash\dcc\__init__.py", line 24, in <module dash.dcc>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\res\\DOWNLO~1\\OPEN3D~1\\build\\OPEN3D~1.DIS\\dash\\dcc\\package-info.json'
```

**Comment by kayhayen** [comment]
It seems you are missing data files of the dash package. I will look into making your example work later, for now you could use `--include-package-data=dash` and see if this gets you any further.

**Comment by yes89929** [comment]
> It seems you are missing data files of the dash package. I will look into making your example work later, for now you could use `--include-package-data=dash` and see if this gets you any further.

Thank you for the reply.
It work correctly.

**Comment by kayhayen** [comment]
Also doing some anti-bloat work first, that is already on factory branch, avoiding IPython and pytest to be included for no good reason.

**Comment by kayhayen** [comment]
This is going to be part of 1.2.4 hotfix release that I am about to make. Closing a bit early, since this is not a universal issue.
