### ISSUE TITLE
no module named "gevent.signal"

### ISSUE THREAD

**Issue by arthurchan1906** [Nuitka/Nuitka#1933]
```
# test.py
# a minimum reproducible demo

import gevent
from gevent import monkey
monkey.patch_all(thread=False)
```

```
>python -m nuitka --standalone  --output-dir=out test.py
```

```
D:\GetMailExtension\out\test.dist>test.exe
Traceback (most recent call last):
  File "D:\GetMailExtension\out\test.dist\test.py", line 3, in <module>
  File "D:\GetMailExtension\out\test.dist\gevent\monkey.py", line 1285, in patch_all
  File "D:\GetMailExtension\out\test.dist\gevent\monkey.py", line 200, in ignores
  File "D:\GetMailExtension\out\test.dist\gevent\monkey.py", line 1165, in patch_signal
  File "D:\GetMailExtension\out\test.dist\gevent\monkey.py", line 462, in _patch_module
  File "D:\GetMailExtension\out\test.dist\gevent\monkey.py", line 448, in _check_availability
ModuleNotFoundError: No module named 'gevent.signal'

```

python : 3.9.12  win10-64bit

gevent: 22.10.2
Nuitka: 0.7.7

**Comment by kayhayen** [comment]
Congratulations on finding this Nuitka release, you might want to try the latest version 1.2 first.

**Comment by damadjan** [comment]
having the same issue with the latest version

**Comment by kayhayen** [comment]
@damadjan posting below closed issues is not productive, can you please open a new issue. I suspect then that this is an update of gevent, but I lack a reproducer.
