### ISSUE TITLE
Problems with dir and object argument

### ISSUE THREAD

**Issue by joshuahaertel** [Nuitka/Nuitka#194]
* `python -m nuitka --version`
```
0.6.0.6
Python: 3.6.3 (default, Oct  3 2017, 21:45:48) 
Executable: /home/joshua/.virtualenvs/myproj/bin/python
OS: Linux
Arch: x86_64
```
* Installed via pip. Dev version was installed via pip as well and had the same problem
*  sscce - discovered in freezegun library
```
def _get_module_attributes(module):
    result = []
    try:
        module_attributes = dir(module)  # works without module arg
    except TypeError:
        return result
```
`python -m nuitka fail_dir.py`

* Error output:
```
Problem with statement at fail_dir.py:3:
->     try:

Problem with statement at fail_dir.py:1:
-> def _get_module_attributes(module):

Problem with statement at fail_dir.py:1:
-> def _get_module_attributes(module):

Nuitka:INFO:Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'fail_dir.py', 'main_added': False, 'mode': 'compiled'}>'.
Traceback (most recent call last):
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/__main__.py", line 180, in <module>
    main()
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/__main__.py", line 174, in main
    MainControl.main()
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/MainControl.py", line 802, in main
    filename = filename
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/MainControl.py", line 152, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 560, in optimize
    finished = makeOptimizationPass(initial_pass = False)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 453, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/Optimization.py", line 97, in optimizeCompiledPythonModule
    module.computeModule()
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/ModuleNodes.py", line 483, in computeModule
    trace_collection = self.trace_collection
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/StatementNodes.py", line 169, in computeStatementsSequence
    statement = statement
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 585, in onStatement
    statement.computeStatement(self)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/AssignNodes.py", line 297, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 560, in onExpression
    trace_collection = self
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/ExpressionBases.py", line 998, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 560, in onExpression
    trace_collection = self
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/FunctionNodes.py", line 879, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/FunctionNodes.py", line 414, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/FunctionNodes.py", line 428, in computeFunction
    trace_collection = trace_collection
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/StatementNodes.py", line 169, in computeStatementsSequence
    statement = statement
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 585, in onStatement
    statement.computeStatement(self)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/TryNodes.py", line 129, in computeStatement
    trace_collection = trace_collection
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    trace_collection
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/FrameNodes.py", line 195, in computeStatementsSequence
    statement = statement
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/optimizations/TraceCollections.py", line 585, in onStatement
    statement.computeStatement(self)
  File "/home/joshua/.virtualenvs/myproj/lib/python3.6/site-packages/nuitka/nodes/TryNodes.py", line 171, in computeStatement
    statement
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementAssignmentVariable" line="4" variable_name="module_attributes" is_temp="False" owner="__main__$$$function_1__get_module_attributes">
      <role name="source">
        <node kind="ExpressionBuiltinDir1" line="4">
          <role name="value">
            <node kind="ExpressionVariableRef" line="4" variable_name="module" owner="__main__$$$function_1__get_module_attributes"/>
          </role>
        </node>
      </role>
    </node>



The above information should be included in a bug report.
```

**Comment by kayhayen** [comment]
I just pushed a fix to the factory branch, expecting to make a hotfix with it this weekend.

**Comment by kayhayen** [comment]
No hotfix, but it's on develop and in the next stable release, closing therefore.
