### ISSUE TITLE
UnboundLocalError for "click" module in latest factory version "1.3rc9"

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#1947]
## Nuitka version

```
1.3rc9
Commercial: None
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Soultion-Applications\d-test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe (cl 14.2).
```

## How nuitka was added

```
.\.venv\Scripts\python.exe -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
```

## The specific PyPI names and versions

  > python -m pip freeze

```
click==8.1.3
colorama==0.4.6
Nuitka==1.3rc9
orderedset==2.0.3
```

## Code

> main.py

```python
import click

print(click.__version__)
```

## Nuitka command used

```
nuitka --standalone main.py
```

## Error

```
Nuitka-Options:INFO: Used command line options: --standalone .\main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.3rc9' on Python '3.8' commercial grade 'not installed'.
PASS 1: 5.6%|█▍                       | 20/360, click.decoratorsProblem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:439:
->                 version = metadata.version(package_name)  # type: ignore

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:438:
->             try:

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:429:
->         if version is None and package_name is not None:

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:419:
->     def callback(ctx: Context, param: Parameter, value: bool) -> None:

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:419:
->     def callback(ctx: Context, param: Parameter, value: bool) -> None:

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:355:
-> def version_option(

Problem with statement at C:\Soultion-Applications\d-test\.venv\lib\site-packages\click\decorators.py:355:
-> def version_option(

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Soultion-Applications\\d-test\\.venv\\lib\\site-packages\\click\\decorators.py', 'module_name': <ModuleName click.decorators>, 'code_flags': ''}>'.
PASS 1: 5.6%|█▍                       | 20/360, click.decoratorsTraceback (most recent call last):
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\MainControl.py", line 920, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\MainControl.py", line 210, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 341, in optimizeModules       
    finished = makeOptimizationPass()
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 297, in makeOptimizationPass  
    changed = optimizeModule(current_module)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 188, in optimizeModule        
    changed = optimizeCompiledPythonModule(module)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 99, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 550, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 172, in computeStatementsSequence   
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 184, in computeStatementsSequence       
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 340, in computeStatement       
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 668, in onExpression      
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1220, in computeExpressionRaw      
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 668, in onExpression      
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1102, in computeExpressionRaw        
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 355, in onUsedFunction    
    function_body.computeFunctionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 492, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 507, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 174, in computeStatementsSequence   
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 172, in computeStatementsSequence   
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 184, in computeStatementsSequence       
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 340, in computeStatement       
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 668, in onExpression      
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1220, in computeExpressionRaw      
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 668, in onExpression      
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1102, in computeExpressionRaw        
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 355, in onUsedFunction    
    function_body.computeFunctionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 492, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 507, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 174, in computeStatementsSequence   
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 172, in computeStatementsSequence   
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 184, in computeStatementsSequence       
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 657, in computeStatement
    yes_branch = branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 1009, in computeBranch    
    result = branch.computeStatementsSequence(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 174, in computeStatementsSequence   
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 174, in computeStatementsSequence   
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in onStatement       
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 340, in computeStatement       
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 668, in onExpression      
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\d-test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 465, in computeExpressionRaw  
    expression = trace_collection.onExpression(expression)
UnboundLocalError: local variable 'expression' referenced before assignment
```

> Works fine in 1.3rc6

**Comment by kayhayen** [comment]
Please read the issue template next time more carefully. I says to not report against factory.
