### ISSUE TITLE
Windows: Errno 126 when trying to build standalone

### ISSUE THREAD

**Issue by RNAguy** [Nuitka/Nuitka#1957]
1.3.2
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

**Just starting to try Nuitka.
A fresh install of python and Nuitka.**

**Initial build command worked:**
C:\Users\mark.delcampo\PycharmProjects\HelloWorld>hello.exe
Talk Hello World

**Then I tried to build a standalone:**
C:\Users\mark.delcampo\PycharmProjects\HelloWorld>python -m nuitka --standalone --onefile hello.py
Nuitka-Options:INFO: Used command line options: --standalone --onefile hello.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.3.2' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available).
Nuitka-Scons:INFO: Compiled 36 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 9
Detecting used DLLs: 0.0%|                         | 0/14, hello.exeTraceback (most recent call last):
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\MainControl.py", line 958, in main
    detectUsedDLLs(
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Standalone.py", line 722, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Standalone.py", line 683, in _detectUsedDLLs
    used_dlls = _detectBinaryDLLs(
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\Standalone.py", line 584, in _detectBinaryDLLs
    return detectBinaryPathDLLsWindowsDependencyWalker(
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 93, in detectBinaryPathDLLsWindowsDependencyWalker
    result = detectDLLsWithDependencyWalker(
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\DependsExe.py", line 195, in detectDLLsWithDependencyWalker
    result = parseDependsExeOutput(output_filename)
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\DependsExe.py", line 137, in parseDependsExeOutput
    return _parseDependsExeOutput2(getFileContentByLine(filename, encoding="latin1"))
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\freezer\DependsExe.py", line 98, in _parseDependsExeOutput2
    currently_loaded_dll = getWindowsRunningProcessDLLPaths()
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\SharedLibraries.py", line 718, in getWindowsRunningProcessDLLPaths
    filename = getWindowsRunningProcessModuleFilename(handle)
  File "C:\Users\mark.delcampo\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\SharedLibraries.py", line 670, in getWindowsRunningProcessModuleFilename
    raise WindowsError(
OSError: [Errno 126] The specified module could not be found.

**Comment by kayhayen** [comment]
This one is very interesting. We have made an optimization for how to locate DLLs. We locate all handles of the Windows. However, this appears to be something loaded in your Python t hat is not backed by an existing file. This can be easily addressed by ignoring this error. I will have a fix for that and it's probably for the next hotfix too.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by RNAguy** [comment]
Thank you, Kay. The fix worked for me.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.3.3 that I just made.
