### ISSUE TITLE
build error with win32com.test

### ISSUE THREAD

**Issue by stgfeng** [Nuitka/Nuitka#1967]
* Nuitka version,
C:\work\python\LinearityMeasure>nuitka --version
1.3.3
Commercial: None
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python37-64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe (cl 14.0).

* How did you install Nuitka and Python

   use pip

*  the Nuitka options used
python64 -m nuitka --assume-yes-for-downloads^
	--mingw64^
	--standalone^
	--windows-disable-console^
	--show-progress^
	--show-scons^
	--include-module=serial^
	--include-module=enum^
	--include-module=telnetlib^
	--include-module=struct^
	--include-module=re^
	--include-module=functools^
	--include-module=psutil^
	--include-module=pyvisa^
	--include-module=loguru^
	--include-module=modbus_tk^
	--include-module=tksheet^
	--include-module=matplotlib^
	--include-module=pymysql^
	--include-module=xlsxwriter^
	--include-module=pythoncom^
	--include-module=docxtpl^
	--include-module=docx^
	--include-module=win32com^
	--include-module=requests^
	--include-module=hashlib^
	--nofollow-import-to=test^
	--python-flag=no_site^
	--plugin-enable=pylint-warnings^
	--plugin-enable=tk-inter^
	--plugin-enable=numpy^
	--windows-company-name=SSZN^
	--windows-force-stderr-spec=LMerr.txt^
	--windows-force-stdout-spec=LM.out.txt^
	--windows-file-version=%VERSION%^
	--windows-product-version=%VERSION%^
	--windows-file-description=LinearityMeasure(64bit)^
	--windows-icon-from-ico=%~dp0..\image\stats_lines.ico^
	--output-dir=build64^
	LinearityMeasure.pyw
 
*  the Nuitka err
Nuitka-Progress:INFO: Finished with the module.
PASS 1: 23.5%|█████▊                   | 187/797, win32com.test.testxsltTraceback (most recent call last):
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\MainControl.py", line 915, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\MainControl.py", line 210, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\optimizations\Optimization.py", line 341, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\optimizations\Optimization.py", line 297, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\optimizations\Optimization.py", line 188, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\optimizations\Optimization.py", line 150, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\importing\Recursion.py", line 448, in considerUsedModules
    source_ref=source_ref,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\importing\Recursion.py", line 401, in _addParentPackageUsages
    reason=reason,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\importing\Recursion.py", line 76, in recurseTo
    module_kind=module_kind,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\importing\Recursion.py", line 50, in _recurseTo
    hide_syntax_error=True,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\tree\Building.py", line 1369, in buildModule
    main_added=main_added,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\tree\Building.py", line 1091, in _createModule
    source_ref=source_ref,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 707, in __init__
    source_ref=source_ref,
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 292, in __init__
    self.module_dict_name, "module_dict", self
  File "C:\Program Files\Python37-64\lib\site-packages\nuitka\nodes\LocalsScopes.py", line 63, in getLocalsDictHandle
    locals_dict_handles[locals_name].owner.getCompileTimeFilename(),
nuitka.Errors.NuitkaOptimizationError:
duplicate locals name
globals_win32com$test
module_dict
win32com.test
C:\Program Files\Python37-64\lib\test\__init__.py
win32com.test
C:\Program Files\Python37-64\lib\site-packages\win32com\test\__init__.py

The above information should be included in a bug report.

**Comment by kayhayen** [comment]
This is triggered by your pathological use of `--include-module` which includes much more stuff than necessary.

**Comment by kayhayen** [comment]
I have no idea, how `test_init` would come to be in the stdlib directory of your Python install or why it gets picked up. I do not think I will be able to reproduce this without further information.

However, be aware that while other tools do not even attempt to do proper dependencies, Nuitka does, and you ought to get away with barely ever using --include-module. If you have to, you may want to use `--nofollow-import-to` to remove it. Let me know if you can provide extra information like `PYTHONPATH` or a special history of your Python install.

**Comment by stgfeng** [comment]
* My PYTHONPAH 
['', 'C:\\Program Files\\Python37-64\\python37.zip', 'C:\\Program Files\\Python37-64\\DLLs', 'C:\\Program Files\\Python37-64\\lib', 'C:\\Program Files\\Py
thon37-64', 'C:\\Program Files\\Python37-64\\lib\\site-packages', 'C:\\Program Files\\Python37-64\\lib\\site-packages\\win32', 'C:\\Program Files\\Python3
7-64\\lib\\site-packages\\win32\\lib', 'C:\\Program Files\\Python37-64\\lib\\site-packages\\Pythonwin']

And I use nuika 0.6.18 version，it’s ok. 
C:\work\python\LinearityMeasure>nuitka --version
0.6.18
Commercial: None
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Program Files\Python37-64\python.exe
OS: Windows
Arch: x86_64

**Comment by kayhayen** [comment]
If you manage to reproduce this with a supported version, let me know.
