### ISSUE TITLE
Crash when compiling certain `match` statements

### ISSUE THREAD

**Issue by dosisod** [Nuitka/Nuitka#1969]
### Version Info

```
$ nuitka3 --version
1.3.2
Commercial: None
Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/bin/gcc (gcc).
```

Installed via `pacman -Syu nuitka`

### Installed PyPi Packages

None

### The Bug

The following file (`x.py`):

```python
def f(x):
    match x:
        case int(y) | y:
            print(y)

f(123)
f("abc")
```

Crashes when compiling:

```
$ nuitka3 x.py
Nuitka-Options:INFO: Used command line options: x.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.3.2' on Python '3.10' commercial grade 'not installed'.
Nuitka-Optimization:WARNING: Problem at 'x.py:2' with Match(subject=Name(id='x', ctx=Load()), cases=[match_case(pattern=MatchOr(patterns=[MatchClass(cls=Name(id='int', ctx=Load()), patterns=[MatchAs(name='y')],
Nuitka-Optimization:WARNING: kwd_attrs=[], kwd_patterns=[]), MatchAs(name='y')]), body=[Expr(value=Call(func=Name(id='print', ctx=Load()), args=[Name(id='y', ctx=Load())], keywords=[]))])]).
Nuitka-Optimization:WARNING: Problem at 'x.py:1' with FunctionDef(name='f', args=arguments(posonlyargs=[], args=[arg(arg='x')], kwonlyargs=[], kw_defaults=[], defaults=[]), body=[Match(subject=Name(id='x',
Nuitka-Optimization:WARNING: ctx=Load()), cases=[match_case(pattern=MatchOr(patterns=[MatchClass(cls=Name(id='int', ctx=Load()), patterns=[MatchAs(name='y')], kwd_attrs=[], kwd_patterns=[]), MatchAs(name='y')]),
Nuitka-Optimization:WARNING: body=[Expr(value=Call(func=Name(id='print', ctx=Load()), args=[Name(id='y', ctx=Load())], keywords=[]))])])], decorator_list=[]).
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nuitka/__main__.py", line 151, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/nuitka/__main__.py", line 137, in main
    MainControl.main()
  File "/usr/lib/python3.10/site-packages/nuitka/MainControl.py", line 915, in main
    main_module = _createNodeTree(filename=filename)
  File "/usr/lib/python3.10/site-packages/nuitka/MainControl.py", line 131, in _createNodeTree
    main_module = buildMainModuleTree(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/Building.py", line 1148, in buildMainModuleTree
    module, _added = buildModule(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/Building.py", line 1378, in buildModule
    createModuleTree(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/Building.py", line 1109, in createModuleTree
    module_body = buildParseTree(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/Building.py", line 772, in buildParseTree
    result = buildStatementsNode(provider=provider, nodes=body, source_ref=source_ref)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 453, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 212, in buildFunctionNode
    function_statements_body = buildFrameNode(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 471, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationMatchStatements.py", line 543, in buildMatchNode
    _buildCase(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationMatchStatements.py", line 513, in _buildCase
    conditions, assignments = _buildMatch(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationMatchStatements.py", line 452, in _buildMatch
    conditions, assignments = _buildMatchOr(
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationMatchStatements.py", line 393, in _buildMatchOr
    makeAndNode(values=or_conditions, source_ref=source_ref)
  File "/usr/lib/python3.10/site-packages/nuitka/tree/ReformulationBooleanExpressions.py", line 84, in makeAndNode
    values = list(values)
TypeError: 'NoneType' object is not iterable
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by dosisod** [comment]
Thanks, this fixed my issue! It did bring up a new bug though which I am opening an issue for right now.

**Comment by kayhayen** [comment]
Thanks, I saw your comment, and I will try and revert the breaking part, however know that this kind of call is unlikely to work until the mentioned issue #1955 is actually solved proper. You can give a shot to hotfix/1.3.5 branch where I am staging the next hotfix, and tell me if that works for you, which should be surprising.

**Comment by kayhayen** [comment]
This is part of the 1.3.4 hotfix release.
