### ISSUE TITLE
ModuleNotFoundError: No module named 'requests.packages.urllib3.contrib.appengine'

### ISSUE THREAD

**Issue by Pranavprana** [Nuitka/Nuitka#1975]
version --

> 1.3.5
> Commercial: None
> Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
> Flavor: CPython Official
> Executable: C:\Python39\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 10
> Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe (cl 14.2).

pip

```
> 2captcha-python==1.1.0
> absl-py==0.12.0
> account==0.1.0
> action==1.4.4
> adder==1.0
> aiohttp==3.7.4.post0
> airtest==1.2.6
> alembic==1.7.7
> altgraph==0.17
> amazoncaptcha==0.5.6
> amqp==2.6.1
> androidemu==0.0.2
> ansicon==1.89.0
> anticaptchaofficial==1.0.31
> anyio==3.6.1
> appdirs==1.4.4
> Appium-Python-Client==2.6.0
> apptools==5.2.0
> APScheduler==3.6.3
> asgiref==3.5.2
> astunparse==1.6.3
> async-generator==1.10
> async-timeout==4.0.2
> atomicwrites==1.4.0
> attmap==0.13.0
> attrs==21.2.0
> AuthGG==0.9
> Babel==2.10.1
> backcall==0.2.0
> bcrypt==3.2.2
> bearer==3.1.0
> beautifulsoup4==4.9.3
> billiard==3.6.4.0
> blackboxprotobuf==1.0.1
> blessed==1.19.1
> blessings==1.7
> blinker==1.4
> blowfish==0.6.1
> Brotli==1.0.9
> browser-cookie3==0.12.1
> bs4==0.0.1
> CacheControl==0.12.11
> cached-property==1.5.2
> cachetools==4.2.2
> captchatools==1.2.1
> celery==4.4.7
> certifi==2022.9.24
> cffi==1.14.6
> chardet==3.0.4
> charset-normalizer==2.0.4
> chromedriver==2.24.1
> cli-helpers==2.2.1
> click==7.1.2
> click-help-colors==0.9.1
> clickable==1.5
> clicking==0.2.0
> colorama==0.4.4
> coloredlogs==15.0.1
> comtypes==1.1.10
> configobj==5.0.6
> crypto==1.4.1
> cryptography==36.0.2
> csrf==0.1b1
> cssselect==1.1.0
> cssutils==2.4.0
> cycler==0.11.0
> Cython==0.29.32
> cytoolz==0.11.0
> dateparser==1.1.0
> DateTime==4.3
> decompyle3==3.9.0
> decorator==5.0.9
> defusedxml==0.7.1
> delegator.py==0.1.1
> Deprecated==1.2.12
> discord-webhook==0.14.0
> divvy==0.5.0
> Django==4.1.4
> dnspython==2.2.1
> docopt==0.6.2
> duration==1.1.1
> easygui==0.98.2
> ecdsa==0.17.0
> eido==0.1.5
> email-validator==1.2.1
> emails==0.5.15
> envisage==6.1.0
> eth-hash==0.3.1
> eth-typing==2.2.2
> eth-utils==1.10.0
> expand==0.2.2
> facebook-wda==1.4.3
> fake-useragent==0.1.11
> Faker==13.7.0
> fastapi==0.70.1
> ffmpeg==1.4
> filelock==3.3.2
> firebase==3.0.1
> firebase-admin==6.0.1
> Flask==2.0.1
> Flask-Cors==3.0.10
> flatbuffers==1.12
> fonttools==4.33.3
> free-proxy==1.0.3
> frida==15.1.17
> frida-tools==10.6.1
> ftfy==6.1.1
> future==0.18.2
> gast==0.4.0
> gcloud==0.17.0
> gdown==4.6.0
> geographiclib==1.52
> geopy==2.2.0
> getmac==0.8.3
> google==3.0.0
> google-api-core==2.11.0
> google-api-python-client==2.68.0
> google-auth==2.15.0
> google-auth-httplib2==0.1.0
> google-auth-oauthlib==0.4.4
> google-cloud-core==2.3.2
> google-cloud-firestore==2.7.2
> google-cloud-storage==2.7.0
> google-crc32c==1.5.0
> google-pasta==0.2.0
> google-resumable-media==2.4.0
> googleapis-common-protos==1.57.0
> greenlet==1.1.2
> grpcio==1.51.1
> grpcio-status==1.51.1
> gspread==4.0.1
> gunicorn==20.1.0
> h11==0.12.0
> h2==4.0.0
> h5py==3.1.0
> hexdump==3.3
> hpack==4.0.0
> hrpc==1.0.9
> httpcore==0.15.0
> httplib2==0.19.1
> httpx==0.23.0
> humanfriendly==10.0
> hyperframe==6.0.1
> idna==2.10
> ifaddr==0.1.7
> imap-tools==0.45.0
> importlib-metadata==4.6.4
> inflect==5.6.0
> inquirer==2.10.0
> install==1.3.4
> ipython==7.29.0
> iso8601==1.0.2
> itsdangerous==2.0.1
> jedi==0.18.0
> jeepney==0.7.1
> Jinja2==2.11.3
> jinxed==1.2.0
> joblib==1.1.0
> Js2Py==0.71
> jsonschema==4.0.1
> jws==0.1.3
> kaitaistruct==0.9
> keras-nightly==2.5.0.dev2021032900
> Keras-Preprocessing==1.1.2
> keyring==23.1.0
> keystone-engine==0.9.2
> kiwisolver==1.4.2
> kombu==4.6.11
> latest-user-agents==0.0.3
> ldap3==2.9.1
> libpython==0.2
> librespot==0.0.7
> litecli==1.8.0
> loading==0.0.1
> logmuse==0.2.7
> logomaker==0.8
> looper==1.3.1
> lxml==4.9.2
> lz4==3.1.3
> m3u8==2.0.0
> Mako==1.2.0
> Markdown==3.3.4
> MarkupSafe==2.0.1
> matplotlib==3.5.2
> matplotlib-inline==0.1.3
> maturin==0.13.2
> mayavi==4.8.0
> mitmproxy==7.0.2
> more-itertools==8.13.0
> MouseInfo==0.1.3
> msgpack==1.0.2
> mss==6.1.0
> multidict==5.1.0
> mutagen==1.44.0
> Naked==0.1.31
> names==0.3.0
> Nuitka==1.3.5
> num2words==0.5.10
> number2words==0.1.3
> numpy==1.19.3
> oauth2client==3.0.0
> oauthlib==3.1.0
> objection==1.11.0
> opencv-contrib-python==4.6.0.66
> opencv-python==4.5.5.64
> opt-einsum==3.3.0
> orderedset==2.0.3
> outcome==1.1.0
> oyaml==1.0
> packaging==21.3
> pandas==1.3.3
> parso==0.8.2
> passlib==1.7.4
> password==0.2
> pbkdf2==1.3
> Pebble==4.6.3
> pefile==2022.5.30
> peppercorn==0.6
> peppy==0.31.1
> perform==0.0.8
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==9.0.1
> pipwin==0.5.2
> platformdirs==2.5.2
> pluggy==0.13.1
> plyer==2.0.0
> pocoui==1.0.87
> premailer==3.10.0
> prices==1.1.0
> problem==0.2.3
> prompt-toolkit==3.0.30
> proto-plus==1.22.1
> protobuf==3.20.1
> proxy==0.0.1
> proxy-extractor==0.1.1
> Proxy-List-Scrapper==0.2.2
> psutil==5.8.0
> psycopg2-binary==2.9.3
> ptyprocess==0.7.0
> publicsuffix2==2.20191221
> pubproxpy==2.0.2
> py==1.10.0
> pyaes==1.6.1
> pyarmor==7.6.1
> pyarmor-webui==1.3.3
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> PyAutoGUI==0.9.53
> pycairo==1.21.0
> pychrome==0.2.3
> pycparser==2.20
> pycryptodome==3.15.0
> pycryptodomex==3.15.0
> pycuda @ file:///C:/Users/A.T/pipwin/pycuda-2022.1%2Bcuda116-cp39-cp39-win_amd64.whl
> pydantic==1.9.1
> pydivert==2.1.0
> pyelftools==0.27
> pyface==7.4.2
> pyffmpeg==2.3
> pyfiglet==0.8.post1
> PyGetWindow==0.0.9
> Pygments==2.10.0
> pyheartradio==0.0.1a1
> pyimport==0.5.6
> PyInquirer==1.0.3
> pyinstaller==4.6
> pyinstaller-hooks-contrib==2022.8
> pyjsparser==2.7.1
> PyJWT==2.6.0
> pymongo==4.2.0
> PyMsgBox==1.0.9
> PyOgg==0.6.14a1
> pyOpenSSL==22.0.0
> pyparsing==2.4.7
> pyperclip==1.8.2
> PyPrind==2.11.3
> PyQt5==5.15.7
> PyQt5-Qt5==5.15.2
> PyQt5-sip==12.11.0
> PyQt5-stubs==5.15.6.0
> pyreadline3==3.4.1
> Pyrebase==3.0.27
> PyRect==0.2.0
> pyrsistent==0.18.0
> PyScreeze==0.1.28
> PySide6==6.3.1
> PySide6-Addons==6.3.1
> PySide6-Essentials==6.3.1
> pySmartDL==1.3.4
> PySocks==1.7.1
> PySoundCloud==2020.6.2
> pyTelegramBotAPI==4.2.0
> pytesseract==0.3.9
> pytest==5.4.3
> python-anticaptcha==1.0.0
> python-binance==1.0.15
> python-dateutil==2.8.2
> python-editor==1.0.4
> python-ffmpeg-video-streaming==0.1.15
> python-generate-mac==1.3.1
> python-jose==3.3.0
> python-jwt==2.0.1
> python-multipart==0.0.5
> python-telegram-bot==13.8.1
> python-vlc==2.2.6100
> pytools==2022.1.12
> pytweening==1.0.4
> pytz==2021.1
> pytz-deprecation-shim==0.1.0.post0
> pywin32==303
> pywin32-ctypes==0.2.0
> pywinauto==0.6.3
> PyYAML==5.4.1
> pyzipcode==3.0.1
> random-password-generator==2.2.0
> random-user-agent==1.0.1
> raven==6.10.0
> readchar==4.0.2
> regex==2021.11.10
> report==0.0.1
> requests==2.28.1
> requests-oauthlib==1.3.0
> requests-toolbelt==0.7.0
> retry==0.9.2
> retrying==1.3.3
> rfc3986==1.5.0
> rlp==1.2.0
> rsa==4.7.2
> ruamel.yaml==0.17.10
> ruamel.yaml.clib==0.2.6
> scikit-learn==1.0.1
> scipy==1.7.2
> SecretStorage==3.3.1
> selenium==4.5.0
> selenium-stealth==1.0.6
> selenium-wire==4.4.1
> self==2020.12.3
> semver==2.13.0
> shellescape==3.8.1
> shiboken6==6.3.1
> six==1.16.0
> sklearn==0.0
> sniffio==1.2.0
> SocksipyChain==2.1.2.post1
> sockslib==1.7.3
> software==0.0.0
> Solution==5.4.0
> sortedcontainers==2.4.0
> soundground==0.1
> soupsieve==2.2.1
> spark-parser==1.8.9
> spotipy==2.19.0
> SQLAlchemy==1.4.36
> sqlparse==0.4.2
> starlette==0.16.0
> tabulate==0.8.9
> tenacity==6.3.1
> tensorboard==2.4.1
> tensorboard-plugin-wit==1.8.0
> tensorflow==2.5.0rc1
> tensorflow-estimator==2.5.0rc0
> tensorflow-gpu==2.5.0rc1
> termcolor==1.1.0
> text-unidecode==1.3
> threadpoolctl==3.0.0
> tidalapi==0.6.10
> tomli==2.0.1
> toolz==0.11.1
> tornado==6.1
> tqdm==4.62.3
> traitlets==5.1.1
> traits==6.4.1
> traitsui==7.4.0
> trie==1.4.0
> trio==0.19.0
> trio-websocket==0.9.2
> typing_extensions==4.3.0
> tzdata==2021.5
> tzlocal==4.1
> ubiquerg==0.6.1
> ujson==4.2.0
> uncompyle6==3.7.4
> undetected-chromedriver==3.1.5.post4
> unicorn==1.0.3
> unpy2exe==0.3
> unpyclib==0.8.1
> until==0.1.2
> uritemplate==4.1.1
> urllib3==1.26.13
> urwid==2.1.2
> utils==1.0.1
> uvicorn==0.11.8
> val==0.6
> vboxapi==1.0
> vine==1.3.0
> vtk==9.1.0
> wcwidth==0.2.5
> webapp2==2.5.2
> websocket-client==1.4.2
> websockets==8.1
> Werkzeug==2.0.1
> windows-curses==2.3.0
> WMI==1.5.1
> wordcloud==1.8.2.2
> wrapt==1.12.1
> wslink==1.7.0
> wsproto==1.0.0
> xdis==6.0.4
> xmltodict==0.13.0
> yacman==0.8.3
> yarl==1.6.3
> youtube-dl==2021.12.17
> ytmusicapi==0.21.0
> zeroconf==0.39.4
> zipp==3.5.0
> zope.interface==5.4.0
> zstandard==0.15.2
```

after compiling with this command

python -m nuitka --follow-imports main.py  --standalone --include-package=requests --include-data-files=logo2.txt=. --windows-icon-from-ico=C:\aa.ico --enable-console

and running exe
```
PS D:\Newfolder\PROJECT\compile> ./main.exe
Traceback (most recent call last):
  File "C:\Users\A.T\AppData\Local\Temp\ONEFIL~1\constanttemp.py", line 7, in <module constanttemp>
    import pyrebase
  File "C:\Users\A.T\AppData\Local\Temp\ONEFIL~1\pyrebase\__init__.py", line 1, in <module pyrebase>
  File "C:\Users\A.T\AppData\Local\Temp\ONEFIL~1\pyrebase\pyrebase.py", line 19, in <module pyrebase.pyrebase>
ModuleNotFoundError: No module named 'requests.packages.urllib3.contrib.appengine'
```

**Comment by kayhayen** [comment]
Ok, good report. I managed to reproduce the issue. Strangely the Crypto module was giving me issues with hidden dependencies before I got to this one. This is the line that triggers the issue:

> from requests.packages.urllib3.contrib.appengine import is_appengine_sandbox

This is a module name that needs to be compile to resolved to `urllib3.contrib.appengine` but apparently for this import it's not done. We have a few import hacks including the one not being done here coded up, but there must be a path that is not covered in the importing logic. I will check it out, this should be simple.

**Comment by kayhayen** [comment]
Interestly, this code:

> from requests.packages.urllib3.contrib.appengine import is_appengine_sandbox

only includes "urllib3.contrib.appengine", but then at runtime appears to lookup the value "requests" which is not included.

**Comment by Pranavprana** [comment]
i just modified and removed import from request lib and it's work thankyou I ll check factory version👍

**Comment by kayhayen** [comment]
We keep issues open until a stable release contains a fix.

**Comment by kayhayen** [comment]
This is now on develop branch.

**Comment by kayhayen** [comment]
This is part of the stable release 1.5 that I just made.
