### ISSUE TITLE
Standalone: Missing dependency for gevent

### ISSUE THREAD

**Issue by arthurchan1906** [Nuitka/Nuitka#1976]
error:
```
Traceback (most recent call last):
  File "C:\Users\admin\code\out\TEST~1.DIS\test.py", line 3, in <module>
  File "C:\Users\admin\code\out\TEST~1.DIS\gevent\monkey.py", line 1285, in patch_all
  File "C:\Users\admin\code\out\TEST~1.DIS\gevent\monkey.py", line 200, in ignores
  File "C:\Users\admin\code\out\TEST~1.DIS\gevent\monkey.py", line 1165, in patch_signal
  File "C:\Users\admin\code\out\TEST~1.DIS\gevent\monkey.py", line 462, in _patch_module
  File "C:\Users\admin\code\out\TEST~1.DIS\gevent\monkey.py", line 448, in _check_availability
ModuleNotFoundError: No module named 'gevent.signal'
```

code: test.py
```python
import gevent
from gevent import monkey
monkey.patch_all(thread=False)
```

compile
```
python -m nuitka --standalone  --output-dir=out test.py
```

env:
```
windows 10/64bit
python 3.9.15
nuitka 1.3.5
gevent 22.10.2
```

#1933

**Comment by arthurchan1906** [comment]
exactly the same error on Ubuntu 22.04.1

**Comment by kayhayen** [comment]
@arthurchan1906 for the issue template, I actually expect --version output of Nuitka, it contains most information needed.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.4.4 that I just made.
