### ISSUE TITLE
Can't compile tls-client

### ISSUE THREAD

**Issue by TrixTM** [Nuitka/Nuitka#1983]
* Nuitka version
  0.8.4
Commercial: None
Python: 3.9.0rc2 (tags/v3.9.0rc2:2bd31b5, Sep 17 2020, 00:58:12) [MSC v.1927 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\xCrysti\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* The specific PyPI names and versions
tls-client==0.1.8

main.py:
`import tls_client session = tls_client.Session( client_identifier="chrome_108" ) res = session.get( "https://httpbin.org/get", headers={ "trixtm": "true", } ) print(res.text) input() `
nuitka command:
`nuitka --standalone --follow-imports --include-data-files=C:/Users/xCrysti/AppData/Local/Programs/Python/Python39/Lib/site-packages/tls_client/dependencies/tls-client-64.dll=tls-client-64.dll main.py`

And i get this error: 
`FileNotFoundError: Could not find module 'C:\Users\xCrysti\Desktop\TLSTES~1\MAIN~1.DIS\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax. `
So i include the dll but it still can't find it

**Comment by kayhayen** [comment]
Also not using a pre-release version of Python would be great, we do not support those.

**Comment by kayhayen** [comment]
And repeat after me: DLLs are not data files

**Comment by TrixTM** [comment]
> And repeat after me: DLLs are not data files
I understand now, so i updated to python 3.10.9 and updated nuitka
1.3.6
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\xCrysti\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: F:\vscode2019\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe (cl 14.2).

Same error:
FileNotFoundError: Could not find module 'E:\Temp\onefile_12536_133174985953717362\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

command:
nuitka --onefile --follow-imports main.py

**Comment by kayhayen** [comment]
DLLs are not module files either. I wonder if you manage to use this: https://nuitka.net/doc/nuitka-package-config.html#dlls

**Comment by TrixTM** [comment]
Thank you for your response, the docs aren't very helpful, there are no examples. I made a file called mainconfigfile.yaml and i put the following code:
`dlls:
  - from_filenames:
      relative_path: 'C:/Users/xCrysti/AppData/Local/Programs/Python/Python310/Lib/site-packages/tls_client/dependencies'
      prefixes:
        - 'tls-client'

      suffixes:
        - 'pyd'
        - 'dll'

    dest_path: 'C:/Users/xCrysti/Desktop/tlstesting'
    when: 'win32'`

Then i tried to compile with `nuitka --onefile --user-package-configuration-file=mainconfigfile.yaml main.py`
And it didn't work.
![image](https://user-images.githubusercontent.com/20205415/211113634-d9456517-f2b6-4932-9f7c-d1d04825d993.png)![image](https://user-images.githubusercontent.com/20205415/211113663-19f0aa22-9725-4dda-8077-556c8ee83f9d.png)

**Comment by kayhayen** [comment]
You do know the meaning of relative path, do you? There is no way this going to work. Editing in Visual Code with the schema would be essential, e.g. you are not having the module name as required, and putting suffixes should not bee needed, and even wrong to put pyd in there, that can only cause trouble. It's strange that this contains DLLs for all platforms, but I guess that is their choice.

But what is most striking is that you lack the `module-name:` part.

From what you are showing, something like this should be done:

```
- module-name: 'pyscf.lib.numpy_helper'
  dlls:
    - from_filenames:
        prefixes:
          - 'libnp_helper'
```

Notice the absence of suffixes or relative paths. In your case, the module name should be `tls_client.dependencies` apparently, if that is included, shoud you could tell by looking if it's in `--report=compilation-report.xml` and if not, then `tsl_client` with relative path `dependencies`.

**Comment by TrixTM** [comment]
Hello, thank you for helping me so much, i did exactly what you told me
```
- module-name: 'tls_client.dependencies'
  dlls:
    - from_filenames:
        prefixes:
          - 'tls-client-64'
```
nuitka --onefile --user-package-configuration-file=mainconfigfile.yaml main.py
and i still get the error `FileNotFoundError: Could not find module 'E:\Temp\onefile_21472_133175595142896666\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.`
Sorry if i'm annoying but i really need to get this issue fixed :)

**Comment by kayhayen** [comment]
No that's actually perfect to me. As you can see, this is new stuff, and you are kind of exposing. Did you check if it has that module as part of the compilation? Since the init file is empty, it might not be imported at all. Since you are carefully hiding the traceback, I have no way of knowing which module reports the error. Always a good choice to limit the information provided to only where it says not working. :)

**Comment by TrixTM** [comment]
Here's the full traceback:
```
C:\Users\xCrysti\Desktop\tlstesting>nuitka --onefile --user-package-configuration-file=mainconfigfile.yaml main.py
Nuitka-Options:INFO: Used command line options: --onefile --user-package-configuration-file=mainconfigfile.yaml main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.3.6' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 17 files (no progress information available).
Nuitka-Scons:INFO: Compiled 17 C files using clcache with 17 cache hits and 0 cache misses.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile:INFO: Keeping onefile build directory 'main.onefile-build'.
Nuitka-Onefile:INFO: Using external Python 'C:\Users\xCrysti\AppData\Local\Programs\Python\Python39\python.exe' to compress the payload.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (32.12%) size 18014282 to 5785513.
Nuitka:INFO: Keeping dist folder 'main.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.exe'.
```

C:\Users\xCrysti\Desktop\tlstesting>main.exe
```
Traceback (most recent call last):
  File "E:\Temp\onefile_27416_133175740720843084\main.py", line 1, in <module>
    import tls_client
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_27416_133175740720843084\tls_client\__init__.py", line 15, in <module tls_client>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_27416_133175740720843084\tls_client\sessions.py", line 1, in <module tls_client.sessions>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_27416_133175740720843084\tls_client\cffi.py", line 20, in <module tls_client.cffi>
  File "E:\Temp\onefile_27416_133175740720843084\ctypes\__init__.py", line 452, in LoadLibrary
  File "E:\Temp\onefile_27416_133175740720843084\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'E:\Temp\onefile_27416_133175740720843084\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by kayhayen** [comment]
Ok, from the traceback it becomes obvious that the module name should me `tls_client.cffi` and then of course, the relative path is needed as I previously indicated.

**Comment by TrixTM** [comment]
I renamed the module to tls_client.cffi
```
- module-name: 'tls_client.cffi'
  dlls:
    - from_filenames:
        prefixes:
          - 'tls-client'
```
I ran the script: nuitka --onefile --user-package-configuration-file=mainconfigfile.yaml main.py
and same error
```
C:\Users\xCrysti\Desktop\tlstesting>main.exe
Traceback (most recent call last):
  File "E:\Temp\onefile_26848_133175774097377804\main.py", line 1, in <module>
    import tls_client
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_26848_133175774097377804\tls_client\__init__.py", line 15, in <module tls_client>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_26848_133175774097377804\tls_client\sessions.py", line 1, in <module tls_client.sessions>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Temp\onefile_26848_133175774097377804\tls_client\cffi.py", line 20, in <module tls_client.cffi>
  File "E:\Temp\onefile_26848_133175774097377804\ctypes\__init__.py", line 452, in LoadLibrary
  File "E:\Temp\onefile_26848_133175774097377804\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'E:\Temp\onefile_26848_133175774097377804\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by TrixTM** [comment]
I added relative_path and I DID IT. It finally works! You are such a nice person, i really appreciate the time you spent to teach me. Thank you so much!

**Comment by kayhayen** [comment]
Thanks, now make a PR adding that to the file `nuitka/plugins/standard/standard.nuitka-package.config.yml` to make it perfect.

**Comment by TrixTM** [comment]
There you go https://github.com/Nuitka/Nuitka/pull/1985

**Comment by kayhayen** [comment]
This was part of the 1.3.8 release and the 1.4 release.
