### ISSUE TITLE
For apscheduler, options e.g. --include-package="apscheduler.triggers" is needed and not automatic

### ISSUE THREAD

**Issue by dr-dark-flames** [Nuitka/Nuitka#1995]
I have been developing a big application and it uses python-telegram-bot package, and so far everything works fine but recently I wanted to add job schedular to my app which is included in telegram.ext.job_queue package and after I've complied everything normally  and wanted to run it, it just crashes. I was confused thinking I made an error or smth so I tried to try and test lots of times with things that I was suspicious about that could have been the reason until I reached the job schedule part. I made a simple side script that only included like 15 lines just to run 1 job from telegram.ext.job_queue, and it confirmed it as it didn't run and crashed right away.
the package is python-telegram-bot v20.
everything works fine without including smth from telegram.ext.job_queue
the whole thing included works fine in normal python interpreter

**Comment by Maxwell175** [comment]
Please provide the information that is requested in the issue template. Mainly the output of nuitka --version and a minimal reproducer that demonstrates the issue.

**Comment by dr-dark-flames** [comment]
1.3.7
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\alice\PycharmProjects\Automation\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
-----
Installed from pip and running Nuitka in a venv
-----
`from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler


def run():
    async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
        await context.bot.send_message(chat_id=update.effective_chat.id, text="I'm a bot, please talk to me!")

    async def status(context):
        await context.bot.send_message(chat_id=5640672460, text="I'm a working bot!")
        print("I'm Working")

    application = ApplicationBuilder().token("5950700899:AAFHqstEgRyr4qQ1G_lHZApWFkE2aSghMGI").build()

    start_handler = CommandHandler('start', start)
    application.add_handler(start_handler)

    application.job_queue.run_once(status, 0)

    application.run_polling()


if __name__ == '__main__':
    run()`
This is a simplified version of the main code where i've tried to narrow down the possibilities of the error. 
The line <application.job_queue.run_once(status, 0)> is the cause of this error:
`Traceback (most recent call last):
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\apscheduler\schedulers\base.py", line 900, in _create_plugin_instance
KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\test.py", line 24, in <module>
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\test.py", line 18, in run
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\telegram\ext\_jobqueue.py", line 223, in run_once
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\apscheduler\schedulers\base.py", line 424, in add_job
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\apscheduler\schedulers\base.py", line 925, in _create_trigger
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\apscheduler\schedulers\base.py", line 903, in _create_plugin_instance
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\pkg_resources\__init__.py", line 2471, in load
  File "C:\Users\alice\PycharmProjects\Automation\test.dist\pkg_resources\__init__.py", line 2477, in resolve
ModuleNotFoundError: No module named 'apscheduler.triggers.date'`
When I comment out that line and compile with Nuitka everything goes fine.
-----
Nuitka compiling options: py -m nuitka test.py --mingw64 --standalone

**Comment by kayhayen** [comment]
That is something you need to resolve with `--include-module` usages. For apscheduler we do not include all triggers automatically, since it depends on what args you call it with heavily. I wonder if we should somehow inform the user about this with options nanny.

**Comment by dr-dark-flames** [comment]
Yeah that would be great because I thought standalone will cover all imports needed.

**Comment by kayhayen** [comment]
It is not good at mind reading. Hidden dependencies will not be included, and have to be provided by you. For general packages, this is all based on configuration and automatic, but it's never complete. In this case, `apscheduler` uses entry points, to scan what should be importable, and we could include them all, but it would be terrible for compile time, or so I was thinking. I need to check that too.

**Comment by dr-dark-flames** [comment]
No need to include them. Instead, just notify the user that a hidden dependency has been detected and then it's up to the user whether they decide to include it or not. I think that would be a great solution

**Comment by kayhayen** [comment]
Yes, that is what options-nanny is designed for. Right now I think these are not too many. I think this repeats for things outside of `apscheduler.triggers`, e.g. `apscheduler.jobstores` seems pretty bad with different large packages being usable. Also `apscheduler.executors` is looking tough. Or is there something different in how these get used, which would not have us encounter these?

**Comment by dr-dark-flames** [comment]
To be honest. I'm not sure, but I'll look into it.

**Comment by kayhayen** [comment]
There are similar iteration functions that allow dynamic loading of those, but maybe it's not as critical, then we wouldn't have to make life complicated. It seems in the example I got from a customer a while ago, there is no use of anything of these 2 packages, so if you are good with `--include-package=apscheduler.triggers` then I will just add package configuration to do this automatically. Would be nice if you reported since I intend to release that one relatively soon and it's the last one for 1.3 likely.

**Comment by dr-dark-flames** [comment]
I've compiled my app with `--include-package=apscheduler.triggers` and everything seems to be working perfectly. Thanks a lot! Your work is amazing.

**Comment by kayhayen** [comment]
Keeping issues open until they are really solved. Still intend to add the configuration that makes the option unnecessary.

**Comment by kayhayen** [comment]
I have yet to decide on how to do this. Probably the `options` module could issue a warning pointing out the need to include modules used in the calls as keywords, and we would be good. It could also be that they are so small that it's not worth to be selective and to just include it.

**Comment by kayhayen** [comment]
Rather than doing a warning, I just added the missing dependency on factory, it's not that bad for `apscheduler.triggers` to pull in a few other modules.

**Comment by kayhayen** [comment]
This is part of the 1.6.3 hotfix release.
