### ISSUE TITLE
getframe bug: NameError: name 'a' is not defined

### ISSUE THREAD

**Issue by mingwugmail** [Nuitka/Nuitka#200]
```
    python -m nuitka --version
    0.6.0.6
    Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
    OS: Linux
    Arch: x86_64
```
    How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
    what is a virtualenv ...), this is very important usually.

pip in virtualenv

```
$ python --version
Python 2.7.12

$ cat getframe_bug.py 
# python -m nuitka --follow-imports getframe_bug.py
import sys

def _S(expr):
  frame = sys._getframe(1)
  result = '%s = %s ' % (expr, repr(eval(expr, frame.f_globals, frame.f_locals)))
  return result

def main():
  a = 10
  print(_S('a+10'))

if __name__ == '__main__':
  main()


$ python getframe_bug.py 
a+10 = 20 
```

compile with
```
$ python -m nuitka --follow-imports getframe_bug.py

$ ./getframe_bug.bin 
Traceback (most recent call last):
  File "/home/.../getframe_bug.py", line 14, in <module>
    main()
  File "/home/.../getframe_bug.py", line 11, in main
    print(_S('a+10'))
  File "/home/.../getframe_bug.py", line 6, in _S
    result = '%s = %s ' % (expr, repr(eval(expr, frame.f_globals, frame.f_locals)))
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined

```

**Comment by kayhayen** [comment]
That is not supported at this time. Frame variables are assigned to the frame only in case of exceptions.

Eventually I expect to enhance frame storage to make them available sooner, but this is not implemented. There is already an issue to track this, so I am closing this as unsupported.
