### ISSUE TITLE
The python source code packaged by nuitka contains input(), and an exception occurs when Chinese is input and printed.

### ISSUE THREAD

**Issue by YIRUIJIE** [Nuitka/Nuitka#2003]
Hi! I googled the problem I'm having but couldn't find any solution, can you help me?

## Device Environment

> C:\Users\YRJ>nuitka --version
> 1.3.7
> Commercial: None
> Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
> Flavor: CPython Official
> Executable: C:\Users\Python\Python36\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 10
> Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

## Python Script

```python
# -*- coding: UTF-8 -*-
import datetime
import os
import time

# function
def test():
    # Chinese prompt, test whether the command line Chinese is abnormal
    print("====测试exe运行命令行中文显示====")
    # Run the packaged exe program, enter English and numbers here and execute until the printout is normal,
    # enter Chinese and execute until printing will flash back.
    input_text = input("请输入：")

    print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S ") + input_text)
    time.sleep(3)

if __name__ == '__main__':
    # Solve the Chinese garbled characters in the command line after the packaged exe runs
    os.system("chcp 65001 && cls")
    test()

```

## Nuitka Script

```shell
# Use one of the following commands to package the exe file
nuitka --standalone --mingw64 test.py
nuitka --standalone --onefile test.py
```

## run exe result

Test input number：

```shell
====测试脚本====
请输入：12345
2023-01-18 11:39:57 12345
```

Test input English：

```shell
====测试脚本====
请输入：hello Nuitka
2023-01-18 11:42:02 hello Nuitka
```

Test input Chinese(**question**)：

```shell
====测试脚本====
请输入：哈哈哈
Traceback (most recent call last):
  File "C:\Users\YRJ\AppData\Local\Temp\ONEFIL~4\test.py", line 20, in <module>
    test()
  File "C:\Users\YRJ\AppData\Local\Temp\ONEFIL~4\test.py", line 12, in test
    input_text = input("请输入：")
EOFError

```

Pyinstaller package exe execution or run console output in PyCharm：

```shell
Active code page: 65001
====测试脚本====
请输入：哈哈哈
2023-01-18 11:44:12 哈哈哈

```

## My question:

The python source code packaged by `nuitka` contains `input()`, and an exception occurs when Chinese is input and printed.

How can I solve it so that no error is reported when inputting Chinese under `input() `when executing exe?

I think this should be a program bug, not an exception caused by my own equipment environment problems. Please identify this issue and suggest a relevant solution, thanks in advance.

**Comment by Pragmatism0220** [comment]
I think this is not the issue that Nuitka should consider, but the issue of compiler. Why don't you try clang instead of gcc?

**Comment by kayhayen** [comment]
I might be wrong, but I believe this is an issue with how Nuitka fails to get the encoding to use with older Python.

```
// Workaround older Python not handling stream setup on redirected files properly.
#if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
    {
        char const *encoding = NULL;

        if (SYSFLAG_UTF8) {
            encoding = "utf-8";
        } else {
            encoding = getenv("PYTHONIOENCODING");
            if (encoding == NULL) {
                encoding = "utf-8";
            }
        }

        Py_SetStandardStreamEncoding(encoding, NULL);
    }
#endif
```

So newer Python is very essential on non-western systems, since UTF-8 will often not be usable with your terminal.

I honestly don't know what `os.system("chcp 65001 && cls")` will have as an impact on the running Python process. Does it?

**Comment by kayhayen** [comment]
Please try with Python 3.8 or higher and let me know if that works better. The issue here is that Python in those versions requires loading the codec registry to help with setting the locale even before it's available. With the interface used to initialize the interpreter, we do not currently have that option. I was however looking at isolated mode, and that's something that will only work with the more complex setup methods, that I have so far avoided, and maybe as a side product, this limitation for older Python can fall.

You can also try setting `PYTHONIOENCOING` before program launch, that is supposed to be the workaround if you cannot upgrade.

**Comment by YIRUIJIE** [comment]
> 我可能是错的，但我相信这是 Nuitka 如何无法获得与旧 Python 一起使用的编码的问题。
> 
> ```
> // Workaround older Python not handling stream setup on redirected files properly.
> #if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
>     {
>         char const *encoding = NULL;
> 
>         if (SYSFLAG_UTF8) {
>             encoding = "utf-8";
>         } else {
>             encoding = getenv("PYTHONIOENCODING");
>             if (encoding == NULL) {
>                 encoding = "utf-8";
>             }
>         }
> 
>         Py_SetStandardStreamEncoding(encoding, NULL);
>     }
> #endif
> ```
> 
> 因此，较新的 Python 在非西方系统上非常重要，因为 UTF-8 通常无法在您的终端上使用。
> 
> 老实说，我不知道`os.system("chcp 65001 && cls")`会对正在运行的 Python 进程产生什么影响。可以？
Adding `os.system("chcp 65001 && cls")` to the first line of the main function can indeed solve the problem of garbled Chinese characters displayed on the command line, but after testing, it cannot solve the problem I am currently encountering.


> I might be wrong, but I believe this is an issue with how Nuitka fails to get the encoding to use with older Python.
> 
> ```
> // Workaround older Python not handling stream setup on redirected files properly.
> #if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
>     {
>         char const *encoding = NULL;
> 
>         if (SYSFLAG_UTF8) {
>             encoding = "utf-8";
>         } else {
>             encoding = getenv("PYTHONIOENCODING");
>             if (encoding == NULL) {
>                 encoding = "utf-8";
>             }
>         }
> 
>         Py_SetStandardStreamEncoding(encoding, NULL);
>     }
> #endif
> ```
> 
> So newer Python is very essential on non-western systems, since UTF-8 will often not be usable with your terminal.
> 
> I honestly don't know what `os.system("chcp 65001 && cls")` will have as an impact on the running Python process. Does it?

Adding `os.system("chcp 65001 && cls")` to the first line of the main function can indeed solve the problem of garbled Chinese characters displayed on the command line, but after testing, it cannot solve the problem I am currently encountering.

**Comment by YIRUIJIE** [comment]
> I might be wrong, but I believe this is an issue with how Nuitka fails to get the encoding to use with older Python.
> 
> ```
> // Workaround older Python not handling stream setup on redirected files properly.
> #if PYTHON_VERSION >= 0x340 && PYTHON_VERSION < 0x380
>     {
>         char const *encoding = NULL;
> 
>         if (SYSFLAG_UTF8) {
>             encoding = "utf-8";
>         } else {
>             encoding = getenv("PYTHONIOENCODING");
>             if (encoding == NULL) {
>                 encoding = "utf-8";
>             }
>         }
> 
>         Py_SetStandardStreamEncoding(encoding, NULL);
>     }
> #endif
> ```
> 
> So newer Python is very essential on non-western systems, since UTF-8 will often not be usable with your terminal.
> 
> I honestly don't know what `os.system("chcp 65001 && cls")` will have as an impact on the running Python process. Does it?

Adding `os.system("chcp 65001 && cls")` to the first line of the main function can indeed solve the problem of garbled Chinese characters displayed on the command line, but after testing, it cannot solve the problem I am currently encountering.

**Comment by YIRUIJIE** [comment]
> Please try with Python 3.8 or higher and let me know if that works better. The issue here is that Python in those versions requires loading the codec registry to help with setting the locale even before it's available. With the interface used to initialize the interpreter, we do not currently have that option. I was however looking at isolated mode, and that's something that will only work with the more complex setup methods, that I have so far avoided, and maybe as a side product, this limitation for older Python can fall.
> 
> You can also try setting `PYTHONIOENCODING` before program launch, that is supposed to be the workaround if you cannot upgrade.

Thank you for the solution you proposed. I have tried to set up the code before the program starts, but it can't solve the relevant problems; I will try it with python3.8.8 version in the near future and give feedback, thank you.

**Comment by kayhayen** [comment]
You mean the `PYTHONIOENCODING` does not work for you? It should have, but then I never know what values are correct here for a given OS. Windows is very hard there with the locales. I remember trying to use `chcp` to influence MSVC outputs, what it never had any effect. Programs on Windows often just output what they want. I wonder why `input` can even crash in this way, and if there is a way to get bytes from the user rather than str, but that is off topic, we need to be compatible of course.

**Comment by YIRUIJIE** [comment]
> Please try with Python 3.8 or higher and let me know if that works better. The issue here is that Python in those versions requires loading the codec registry to help with setting the locale even before it's available. With the interface used to initialize the interpreter, we do not currently have that option. I was however looking at isolated mode, and that's something that will only work with the more complex setup methods, that I have so far avoided, and maybe as a side product, this limitation for older Python can fall.
> 
> You can also try setting `PYTHONIOENCODING` before program launch, that is supposed to be the workaround if you cannot upgrade.

Thanks for the help, I have tested and determined that it is a python version issue. I use the following environment just fine.
```shell
C:\Users\admin>nuitka --version
1.4
Commercial: None
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

**Comment by kayhayen** [comment]
Using older CPython on Windows should be rare, and this is a trap. I think I will add a warning for programs that do not disable the console on affected Python about how this is an issue, because I think even if not an aisan user, others will produce binaries that then just fail to work for asian users without knowing it.

**Comment by kayhayen** [comment]
So, this is coming, I still need to produce the page this links to:

```
Nuitka:WARNING: On Windows, support for input/output on the console Windows, does not work
Nuitka:WARNING: on non-UTF8 systems, unless Python 3.8 or higher is used but this is 3.4, 
Nuitka:WARNING: so please consider upgrading, or disabling the console window for
Nuitka:WARNING: deployment.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/old-windows-python.html
```

**Comment by kayhayen** [comment]
This was released with 1.4 and reads like this:

```
Nuitka:WARNING: On Windows, support for input/output on the console    
Nuitka:WARNING: Windows, does not work on non-UTF8 systems, unless     
Nuitka:WARNING: Python 3.8 or higher is used but this is 3.7, so please
Nuitka:WARNING: consider upgrading, or disabling the console window for
Nuitka:WARNING: deployment.
Nuitka:WARNING:     Complex topic! More information can be found at    
Nuitka:WARNING: https://nuitka.net/info/old-python-windows-console.html
```
