### ISSUE TITLE
Failed to load configured propagator `tracecontext` error when using Opentelemetry

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#2014]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.4rc12
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Soultion-Applications\test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe (cl 14.2).
```

* How did you install Nuitka and Python

pip installed the actory version in a venv.

* The specific PyPI names and versions

  > python -m pip freeze

```
anyio==3.6.2
asgiref==3.6.0
click==8.1.3
colorama==0.4.6
Deprecated==1.2.13
fastapi==0.89.1
h11==0.14.0
idna==3.4
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
opentelemetry-api==1.15.0
opentelemetry-instrumentation==0.36b0
opentelemetry-instrumentation-asgi==0.36b0
opentelemetry-instrumentation-fastapi==0.36b0
opentelemetry-instrumentation-logging==0.36b0
opentelemetry-sdk==1.15.0
opentelemetry-semantic-conventions==0.36b0
opentelemetry-util-http==0.36b0
orderedset==2.0.3
pydantic==1.10.4
PyYAML==6.0
sniffio==1.3.0
starlette==0.22.0
typing-extensions==4.4.0
uvicorn==0.20.0
wrapt==1.14.1
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import asyncio
import platform

from fastapi import FastAPI
from opentelemetry import trace
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.logging import LoggingInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider

from typing import List, Optional

import fastapi
from fastapi.middleware.cors import CORSMiddleware


def initialize_telemetry_for_fast_api(app: FastAPI, service_name: str) -> None:
    resource = Resource(attributes={"service.name": service_name})
    trace.set_tracer_provider(TracerProvider(resource=resource))
    LoggingInstrumentor().instrument()
    FastAPIInstrumentor.instrument_app(app)


def create_app(cors_origins: Optional[List[str]] = None):

    app = fastapi.FastAPI(
        title="Example API",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=cors_origins or [],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/health")
    async def health():
        return "The API server is healthy."

    return app


cors_origins = ["*"]
app = create_app(cors_origins)
host = "127.0.0.1"
port = 8000

kwargs = {
    "app": app,
    "host": host,
    "port": port,
    "reload": "True",
}

if platform.system() == "Linux":
    import uvicorn

    uvicorn.run(**kwargs)
else:
    from asyncio.windows_events import ProactorEventLoop

    from uvicorn import Config, Server

    class ProactorServer(Server):
        def run(self, sockets=None):
            loop = ProactorEventLoop()
            asyncio.set_event_loop(
                loop
            )
            asyncio.run(self.serve(sockets=sockets))   
    config = Config(**kwargs)
    server = ProactorServer(config=config)
    server.run()

```

* Provide in your issue the Nuitka options used

```
nuitka --standalone .\test_otel.py
```

```
Failed to load configured propagator `tracecontext`
Traceback (most recent call last):
  File "C:\SOULTI~1\test\TEST_O~1.DIS\opentelemetry\propagate\__init__.py", line 137, in <module opentelemetry.propagate>
StopIteration
Traceback (most recent call last):
  File "C:\SOULTI~1\test\TEST_O~1.DIS\test_otel.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\SOULTI~1\test\TEST_O~1.DIS\opentelemetry\instrumentation\fastapi\__init__.py", line 181, in <module opentelemetry.instrumentation.fastapi>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\SOULTI~1\test\TEST_O~1.DIS\opentelemetry\instrumentation\asgi\__init__.py", line 205, in <module opentelemetry.instrumentation.asgi>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\SOULTI~1\test\TEST_O~1.DIS\opentelemetry\instrumentation\utils.py", line 26, in <module opentelemetry.instrumentation.utils>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\SOULTI~1\test\TEST_O~1.DIS\opentelemetry\propagate\__init__.py", line 137, in <module opentelemetry.propagate>
StopIteration
```

Does not work in stable release of nuitka as well.

Works fine when running using python normally.

This might be of some help: https://github.com/orgs/pyinstaller/discussions/6853

Made this sample code based on something I am working on. Need to use opentelemetry in it.

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: https://nuitka.net/doc/nuitka-package-config.html

And here is more of a walk through style post: https://nuitka.net/posts/nuitka-package-config-kickoff.html

Here is a similar PR for another package: https://github.com/Nuitka/Nuitka/pull/1993

**Comment by YraganTron** [comment]
I tried fix it. But my nuitka version and versions opentelemetry are slightly different

Nuitka
```
1.5rc12
Commercial: None
Python: 3.10.9 (main, Jan 22 2023, 21:45:35) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: pyenv
Executable: /Users/yragantron/Library/Caches/pypoetry/virtualenvs/test-fastapi-sA9Sk0hI-py3.10/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

My dependencies
```
python = "^3.10"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
nuitka = "^1.4.8"
opentelemetry-api = "^1.10.0"
opentelemetry-sdk = "^1.10.0"
opentelemetry-exporter-jaeger = "^1.10.0"
opentelemetry-instrumentation = "^0.29b0"
opentelemetry-instrumentation-redis = "^0.29b0"
opentelemetry-instrumentation-fastapi = "^0.29b0"
opentelemetry-instrumentation-httpx = "^0.29b0"
opentelemetry-instrumentation-sqlalchemy = "^0.29b0"
opentelemetry-instrumentation-botocore = "0.29b0"
```

I use same code and I got same error.

In the module opentelemetry.propagate there is such a piece of code

```
environ_propagators = environ.get(
    OTEL_PROPAGATORS,
    "tracecontext,baggage",
)

for propagator in environ_propagators.split(","):
    propagator = propagator.strip()
    try:
        propagators.append(  # type: ignore
            next(  # type: ignore
                iter_entry_points("opentelemetry_propagator", propagator)
            ).load()()
        )
```
It imports this class opentelemetry.trace.propagation.tracecontext.TraceContextTextMapPropagator and this opentelemetry.baggage.propagation.W3CBaggagePropagator

I pulled nuitka from the develop and added to the config standard.nuitka-package.config this code 

```
- module-name: 'opentelemetry.propagate'
  implicit-imports:
    - depends:
        - 'opentelemetry.trace.propagation.tracecontext'
        - 'opentelemetry.baggage.propagation'
```

But it didn't solve the problem, I get the same error.

**Comment by kayhayen** [comment]
The entry points are just not included. Currently Nuitka only does it when it can statically optimize the code. The above code is not like that. There is also no option to force including it. I guess, wiritng it out, such that Nuitka can see it might help. Your yaml code is good we can can it.

This is from Nuitka changelog:

```
-  Compile time optimize ``pkg_resources.iter_entry_points`` too, such
   that these can be used to resolve plugin modules, which helps with
   adding support for ``agscheduler`` package plugins. Note that these
   still need to be manually included with ``--include-module`` but now
   that works.
```

If you used ``append_code`` and put ```
iter_entry_points("opentelemetry_propagator", "tracecontext")
iter_entry_points("opentelemetry_propagator", "baggage")
```

there, it would work. But I am not entirely sure. If it does not, that would be a bug by itself in Nuitka, since the contained entry points from that code should be exposed to the generic search for sure.

**Comment by YraganTron** [comment]
I didn't succeed with this
```
iter_entry_points("opentelemetry_propagator", "tracecontext")
iter_entry_points("opentelemetry_propagator", "baggage")
```
But I solved it by directly importing these classes.
Here my config https://github.com/Nuitka/Nuitka/issues/2108

**Comment by kayhayen** [comment]
@YraganTron that's great. I think I will be able to condense that. Apparently it's not the only issue, but it's great progress. I will continue in #2108 then.

**Comment by kayhayen** [comment]
I am trying this example right now out, aiming to include this in a 1.7 hotfix maybe, this is all sorted out by you already, or so I hope.

**Comment by kayhayen** [comment]
So, I got this to work. We added a feature `--include-distribution-metadata` that in conjunction with hidden imports would solve it, but I enhanced the Yaml format to do it, and added it there, so it now works out of the box. Need to check the related issue now, if there is anything different there.

**Comment by kayhayen** [comment]
This is part of the 1.7.1 hotfix I just made.
