### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by simsanutiy** [Nuitka/Nuitka#207]
Nuitka 0.6.0.6 (installed via pip)
Python 3.6.6 x64
MinGW64
Win 10 x64
[Source file](https://github.com/simsanutiy/collective_player)

Can't understand what's wrong with utf-8

`Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\extractor\__init__.py:4: Cannot find 'lazy_extractors' in package 'youtube_dl.extractor' 1 package level up (tried youtube_dl.extractor.lazy_extractors,lazy_extractors).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\downloader\hls.py:6: Cannot find 'Crypto.Cipher' in package 'youtube_dl.downloader' as absolute import (tried Crypto.Cipher).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\downloader\hls.py:6: Cannot find 'Crypto' in package 'youtube_dl.downloader' as absolute import (tried Crypto).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\utils.py:3870: Cannot find 'xattr' in package 'youtube_dl' as absolute import (tried xattr).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:28: Cannot find 'urllib2' in package 'youtube_dl' as absolute import (tried urllib2).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:43: Cannot find 'urlparse' in package 'youtube_dl' as absolute import (tried urlparse).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:58: Cannot find 'cookielib' in package 'youtube_dl' as absolute import (tried cookielib).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:63: Cannot find 'Cookie' in package 'youtube_dl' as absolute import (tried Cookie).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:68: Cannot find 'htmlentitydefs' in package 'youtube_dl' as absolute import (tried htmlentitydefs).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:2326: Cannot find 'HTMLParser' in package 'youtube_dl' as absolute import (tried HTMLParser).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:2350: Cannot find 'BaseHTTPServer' in package 'youtube_dl' as absolute import (tried BaseHTTPServer).
Nuitka:WARNING:D:\Python\Python36\lib\site-packages\youtube_dl\compat.py:2926: Cannot find 'future_builtins' in package 'youtube_dl' as absolute import (tried future_builtins).
cl /Focp.build\module.youtube_dl.obj /c "cp.build\module.youtube_dl.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=1247 /D_NUITKA_EXE /ID:\Python\Python36\include /ID:\Python\Python36\PC /Icp.build /ID:\Python\Python36\lib\site-packages\nuitka\build\include /ID:\Python\Python36\lib\site-packages\nuitka\build\static_src
cl /Focp.build\module.youtube_dl.aes.obj /c "cp.build\module.youtube_dl.aes.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=1247 /D_NUITKA_EXE /ID:\Python\Python36\include /ID:\Python\Python36\PC /Icp.build /ID:\Python\Python36\lib\site-packages\nuitka\build\include /ID:\Python\Python36\lib\site-packages\nuitka\build\static_src
scons: *** [cp.build\module.youtube_dl.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
scons: *** [cp.build\module.youtube_dl.aes.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte`

**Comment by kayhayen** [comment]
Can you try the develop version. I think your Windows is giving non-UTF8 errors, and I did some changes to make up for that, which may help.

**Comment by simsanutiy** [comment]
Import warnings are gone, but the main part is the same. Maybe I'm using wrong command line arguments? Or something wrong with youtube-dl module I'm using? Looks like it says that it's a problem with generated C++ files, I've got no skill in it
>D:\projects\collective_player>python -m nuitka --standalone cp.py
cl /Focp.build\module.youtube_dl.obj /c "cp.build\module.youtube_dl.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=1247 /D_NUITKA_EXE /ID:\Python\Python36\include /ID:\Python\Python36\PC /Icp.build /ID:\Python\Python36\lib\site-packages\nuitka\build\include /ID:\Python\Python36\lib\site-packages\nuitka\build\static_src
cl /Focp.build\module.youtube_dl.aes.obj /c "cp.build\module.youtube_dl.aes.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_SYSFLAG_OPTIMIZE=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=1247 /D_NUITKA_EXE /ID:\Python\Python36\include /ID:\Python\Python36\PC /Icp.build /ID:\Python\Python36\lib\site-packages\nuitka\build\include /ID:\Python\Python36\lib\site-packages\nuitka\build\static_src
scons: *** [cp.build\module.youtube_dl.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 585, in spawn
    data = data.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
scons: *** [cp.build\module.youtube_dl.aes.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "D:\Python\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 585, in spawn
    data = data.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 25: invalid start byte

**Comment by kayhayen** [comment]
Hope was that `data = data.decode(sys.stdout.encoding)` is better, but apparently it is not. Can you verify what `D:\Python\Python36\python` gives for that `sys.stdout.encoding` as a value? Should be UTF-8 still, but it would be wrong.

The question is, what is the real encoding value, and how to know it from Python.

Yours,
Kay

**Comment by kayhayen** [comment]
Check out this, MSVC has its own language and along an encoding. Setting your compiler output to English will solve the crash, and barely anything else will:

https://social.msdn.microsoft.com/Forums/en-US/e82947f5-f974-4579-aec2-65c3ee8d01be/how-to-change-text-encoding-on-an-output-window-for-visual-studio-2017?forum=visualstudiogeneral

**Comment by simsanutiy** [comment]
Now I noticed that it was using Visual Studio instead of MinGW. Now it's better
`c1xx: fatal error C1356: unable to find mspdbcore.dll`
Now I just need to set Path variable, I think.
Anyway, that was my bad, sorry for disturbing you, hope this discussion will help future generations not to be as stupid as I am
