### ISSUE TITLE
Playwright: Slow C compilation detected

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#2074]
> python -m nuitka --version
1.4.7
Commercial: None
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\msys64\mingw64\bin\gcc.exe (gcc).
  If you are not providing the full output. The issue cannot be solved and will
  be considered `invalid`. It does more than you think, and we are adding more
  all the time. We do not want to left guessing or trying things out to
  reproduce your issue.

### test.py:
```py
import asyncio, os
import shutil
import subprocess
from playwright.async_api import async_playwright, expect
from playwright.sync_api import sync_playwright
from playwright._impl._driver import compute_driver_executable, get_driver_env
```

>python -m nuitka --standalone --mingw64 test.py
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 test.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python
Nuitka:WARNING: compile time performance.
Nuitka:WARNING: On Windows, support for input/output on the console Windows, does not work on non-UTF8 systems, unless
Nuitka:WARNING: Python 3.8 or higher is used but this is 3.7, so please consider upgrading, or disabling the console
Nuitka:WARNING: window for deployment.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/old-python-windows-console.html
Nuitka:INFO: Starting Python compilation with Nuitka '1.4.7' on Python '3.7' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Backend C: 97.1%|████████████████████████▎| 67/69

it stucks at here
sub process statuses:
![image](https://user-images.githubusercontent.com/26390254/220323081-b4a85f62-1407-42ca-9593-30f3b8d8f237.png)

**Comment by byehack** [comment]
after break using ctrl+c:
```
Nuitka-Scons:INFO: Running '"~\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\downloads\\ccache\\v4.6\\ccache.exe" "C:\\msys64\\mingw64\\bin\\gcc.exe" -o "module.playwright.async_api._generated.o" -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O3 -D_WIN32_WINNT=0x0501 -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=155 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -IC:\\Python37\\include -I. -IC:\\Python37\\lib\\SITE-P~1\\nuitka\\build\\include -IC:\\Python37\\lib\\SITE-P~1\\nuitka\\build\\static_src "module.playwright.async_api._generated.c"' took 163.40 seconds
Backend C: 98.6%|████████████████████████▋| 68/69scons: *** [module.playwright.async_api._generated.o] Build interrupted.
Nuitka-Scons:INFO: Running '"~\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\downloads\\ccache\\v4.6\\ccache.exe" "C:\\msys64\\mingw64\\bin\\gcc.exe" -o "module.playwright.sync_api._generated.o" -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O3 -D_WIN32_WINNT=0x0501 -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=155 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -IC:\\Python37\\include -I. -IC:\\Python37\\lib\\SITE-P~1\\nuitka\\build\\include -IC:\\Python37\\lib\\SITE-P~1\\nuitka\\build\\static_src "module.playwright.sync_api._generated.c"' took 163.17 seconds
Nuitka-Scons:INFO: Backend linking program with 69 files (no progress information available).
scons: *** [module.playwright.sync_api._generated.o] Build interrupted.
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Python37\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Python37\lib\site-packages\nuitka\MainControl.py", line 951, in main
    result, options = compileTree()
  File "C:\Python37\lib\site-packages\nuitka\MainControl.py", line 875, in compileTree
    result, options = runSconsBackend()
  File "C:\Python37\lib\site-packages\nuitka\MainControl.py", line 739, in runSconsBackend
    scons_filename="Backend.scons",
  File "C:\Python37\lib\site-packages\nuitka\build\SconsInterface.py", line 306, in runScons
    result = subprocess.call(scons_command, shell=False, cwd=source_dir)
  File "C:\Python37\lib\subprocess.py", line 341, in call
    return p.wait(timeout=timeout)
  File "C:\Python37\lib\subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "C:\Python37\lib\subprocess.py", line 1259, in _wait
    timeout_millis)
KeyboardInterrupt
```

it seems it stuck in `playwright.async_api._generated.c` and `playwright.sync_api._generated.c`
