### ISSUE TITLE
Minimal numpy import fails at start

### ISSUE THREAD

**Issue by fake-name** [Nuitka/Nuitka#209]
With the following script file:

```
import numpy as np
print("Numpy: ", np)
```

Building: 

```
C:\Code\scfft\applications\test>python -m nuitka --follow-imports nptest.py --standalone --plugin-enable=qt-plugins --nofollow-import-to=dateutil --re
curse-all --show-progress --show-modules >> log.txt  2>&1

C:\Code\scfft\applications\test>cd nptest.dist

C:\Code\scfft\applications\test\nptest.dist>ls
_asyncio.pyd      _msi.pyd              gpsvc.dll     select.pyd
_bz2.pyd          _multiprocessing.pyd  msvcrt.dll    sqlite3.dll
_ctypes.pyd       _overlapped.pyd       nlaapi.dll    sysntfy.dll
_decimal.pyd      _socket.pyd           nptest.exe    tcl86t.dll
_elementtree.pyd  _sqlite3.pyd          numpy         tk86t.dll
_hashlib.pyd      _ssl.pyd              pyexpat.pyd   unicodedata.pyd
_lzma.pyd         _tkinter.pyd          python36.dll  vcruntime140.dll

C:\Code\scfft\applications\test\nptest.dist>nptest.exe
Traceback (most recent call last):
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\core\__init__.py", line 16, in <module numpy.core>
ImportError: LoadLibraryEx 'C:\Code\scfft\applications\test\nptest.dist\numpy\core\multiarray.pyd' failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Code\scfft\applications\test\nptest.dist\nptest.py", line 2, in <module>
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\__init__.py", line 142, in <module numpy>
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\add_newdocs.py", line 13, in <module numpy.add_newdocs>
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\lib\__init__.py", line 8, in <module numpy.lib>
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\lib\type_check.py", line 11, in <module numpy.lib.type_check>
  File "C:\Code\scfft\applications\test\nptest.dist\numpy\core\__init__.py", line 26, in <module numpy.core>
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: LoadLibraryEx 'C:\Code\scfft\applications\test\nptest.dist\numpy\core\multiarray.pyd' failed

C:\Code\scfft\applications\test\nptest.dist>
```

Note that `C:\Code\scfft\applications\test\nptest.dist\numpy\core\multiarray.pyd` *exists*, and numpy operates normally otherwise.

```
C:\Code\scfft\applications\test\nptest.dist>file C:\Code\scfft\applications\test\nptest.dist\numpy\core\multiarray.pyd
C:\Code\scfft\applications\test\nptest.dist\numpy\core\multiarray.pyd: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
```

Versions:

```
C:\Code\scfft\applications\test\nptest.dist>python -m nuitka --version
0.6.0.6
Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Program Files\Python36\python.exe
OS: Windows
Arch: x86_64
C:\Code\scfft\applications\test\nptest.dist>python -c "import numpy; print(numpy.version.version)"
1.15.4
```

Sources are from PyPi, installed via Pip from get-pip.py. Python is from python.org. Platform is windows 7 x64. Platform tools are VS2017 x64, though I have 2015 installed too (if that's somehow getting used, it's a vs2017 command prompt).

Full build output is as follows:

https://pastebin.com/8dz6dfWV

**Comment by kayhayen** [comment]
This is #190 and not solved.

**Comment by fake-name** [comment]
Oh bother, I could have sworn I searched for the issue. Sorry about that!
