### ISSUE TITLE
Compiled but not starting (no errors)

### ISSUE THREAD

**Issue by bondbenz** [Nuitka/Nuitka#2096]
Hello,

I have been trying to compile a PySide6 project, it's quite a big project with multiple packages and files, I have used this command
`
nuitka --standalone --windows-icon-from-ico=assets/favicon.ico  --disable-console --include-package=constants --include-package=controllers --include-package=db --include-package=views --include-package=utils --enable-plugin=pyside6 .\main.py`

### Log
```
Nuitka-Options:INFO: Used command line options: --standalone --windows-icon-from-ico=assets/favicon.ico --disable-console --include-package=constants --include-package=controllers --include-package=db --include-package=views --include-package=utils --enable-plugin=pyside6 .\main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.4.8' on Python '3.8' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside6: Injecting pre-module load code for module 'PySide6':
Nuitka-Plugins:INFO: pyside6:     Adding binary folder to runtime 'PATH' environment variable for proper Qt loading.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.                               
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                              
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 383 files (no progress information available).
Nuitka-Scons:INFO: Compiled 383 C files using clcache with 378 cache hits and 5 cache misses.
Nuitka-Postprocessing:INFO: Adding 6 icon(s) from icon file 'assets/favicon.ico'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6\qt-plugins'.
Nuitka:INFO: Keeping build directory 'main.build'.                                                           
Nuitka:INFO: Successfully created 'main.dist\main.exe'
```

Issue is when I try to start main.exe nothing happens, no error thrown and nothing did show.

### Project Tree:
```
-code:
	-assets:
		-favicon.ico
		-loading.gif
	-constants:
		----modules----
	-controllers:
		----modules----
	-views:
		----modules----
	-db:
		----modules----
	-utils:
		----modules----
	main.py
```

I have also tried to compile with console enabled to debug, but nothing in the console too.

**Comment by bondbenz** [comment]
Now I receive a new error after several tries

`Traceback (most recent call last):
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\main.py", line 1, in <module>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\views\__init__.py", line 1, in <module views>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\views\add_panel.py", line 12, in <module views.add_panel>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\controllers\__init__.py", line 1, in <module controllers>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\controllers\main_controller.py", line 6, in <module controllers.main_controller>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\views\m3u_lists_combiner.py", line 22, in <module views.m3u_lists_combiner>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\controllers\m3u_lists_combiner_controller.py", line 5, in <module controllers.m3u_lists_combiner_controller>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\utils\__init__.py", line 1, in <module utils>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\utils\helpers.py", line 4, in <module utils.helpers>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\db\__init__.py", line 1, in <module db>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\db\engine.py", line 1, in <module db.engine>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\sqlalchemy\orm\__init__.py", line 169, in <module sqlalchemy.orm>
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\sqlalchemy\orm\__init__.py", line 165, in __go
  File "D:\Documents\my work\xtreamity\code\src\dist\main.dist\sqlalchemy\util\preloaded.py", line 137, in import_prefix
ModuleNotFoundError: No module named 'sqlalchemy.orm.dependency'
`

Why nuitka did not compile the whole sqlalchemy package?

**Comment by bondbenz** [comment]
I have fixed by running
`nuitka --standalone --output-dir=dist --include-data-dir=./assets=./assets/ --python-flag=-O --enable-plugin=pyside6 --include-package=constants --include-package=controllers --include-package=db --include-package=views --include-package=utils --include-package=sqlalchemy --include-module=src_rc --nofollow-import-to=*.tests --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --disable-console --windows-icon-from-ico=assets/favicon.ico .\main.py`

However if I add --onefile argument, same thing the exe wont launch.

**Comment by kayhayen** [comment]
You have failed to fill the issue template, so I don't think there is much of anything I can add. Disabling the console is a great way to not get error outputs indeed. Please open a new issue with the actual problems you have and proper issue template. Since this is devoid of information, I am going to delete it sorry.
