### ISSUE TITLE
Side effect notes didn't annotate that they might raise, optimization problem found compiling imap_tools code

### ISSUE THREAD

**Issue by LarsK1** [Nuitka/Nuitka#2100]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe (cl 14.3).

* How did you install Nuitka and Python

pip

* The specific PyPI names and versions

  imap-tools==1.0.0

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

`import imap_tools`

* Provide in your issue the Nuitka options used

  `python -m nuitka --standalone .\NuitkaTest.py`

While compilation the following error is shown:
```
Nuitka-Options:INFO: Used command line options: --standalone .\NuitkaTest.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5rc12' on Python '3.10' commercial grade 'not installed'.
PASS 1: 0.8%|▏                        | 3/355, imap_tools.utils Problem with statement at C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\imap_tools\utils.py:192:
-> def check_timeout_arg_support(timeout):

Problem with statement at C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\imap_tools\utils.py:192:
-> def check_timeout_arg_support(timeout):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\Lars-\\AppData\\Roaming\\Python\\Python310\\site-packages\\imap_tools\\utils.py', 'module_name': <ModuleName imap_tools.utils>, 'code_flags': ''}>'.
PASS 1: 0.8%|▏                        | 3/355, imap_tools.utilsTraceback (most recent call last):
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\MainControl.py", line 942, in main
    main_module = _createMainModule()
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\MainControl.py", line 243, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\Optimization.py", line 191, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\ModuleNodes.py", line 546, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\StatementNodes.py", line 157, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\FrameNodes.py", line 189, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\VariableAssignNodes.py", line 351, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 4868, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\FunctionNodes.py", line 1157, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\TraceCollections.py", line 341, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\FunctionNodes.py", line 495, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\FunctionNodes.py", line 511, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Lars-\AppData\Roaming\Python\Python310\site-packages\nuitka\nodes\TryNodes.py", line 127, in computeStatement
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError:
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementsFrameFunction" line="192" co_name="check_timeout_arg_support" co_kind="Function" co_varnames="timeout" co_freevars="" co_argcount="1" co_posonlyargcount="0" co_kwonlyargcount="0" co_has_starlist="False" co_has_stardict="False" co_filename="imap_tools\utils.py" co_lineno="192" co_new_locals="True" co_is_optimized="True" code_flags="">
      <role name="statements" type="list">
        <node kind="StatementExpressionOnly" line="194" expression="EXPRESSION_SIDE_EFFECTS">
          <role name="expression">
            <node kind="ExpressionSideEffects" line="194">
              <role name="side_effects" type="list">
                <node kind="ExpressionBuiltinBool" line="194">
                  <role name="value">
                    <node kind="ExpressionComparisonIsNot" line="194">
                      <role name="left">
                        <node kind="ExpressionVariableRef" line="194" variable_name="timeout" owner="imap_tools$utils$$$function__15_check_timeout_arg_support" />
                      </role>
                      <role name="right">
                        <node kind="ExpressionConstantNoneRef" line="194" />
                      </role>
                    </node>
                  </role>
                </node>
              </role>
              <role name="expression">
                <node kind="ExpressionConstantFalseRef" line="194" />
              </role>
            </node>
          </role>
        </node>
      </role>
    </node>



The above information should be included in a bug report.

```

**Comment by kayhayen** [comment]
So, this is triggered by compiling this in acceleration mode

```
import sys

def check_timeout_arg_support(timeout):
    if timeout is not None and sys.version_info.minor < 9:
        raise ValueError('imaplib.IMAP4 timeout argument supported since python 3.9')
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by LarsK1** [comment]
Thanks for the quick bugfix. Can confirm it's working fine now!

**Comment by kayhayen** [comment]
Part of the 1.5 release I made.
