### ISSUE TITLE
TypeError: 'NoneType' object is not callable with jaeger exporter in opentelemetry

### ISSUE THREAD

**Issue by YraganTron** [Nuitka/Nuitka#2108]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

 ```
 1.6rc2
Commercial: None
Python: 3.10.9 (main, Jan 22 2023, 21:45:35) [Clang 14.0.0 (clang-1400.0.29.202)]
Flavor: pyenv
Executable: /Users/yragantron/Library/Caches/pypoetry/virtualenvs/test-fastapi-sA9Sk0hI-py3.10/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
 ```

* How did you install Nuitka and Python

I installed nuitla from develop this commit 40d212ee81916769c7bc730b868ecb2114c94775. pip install -e .
And I use pyenv for python.

* The specific PyPI names and versions

  > python -m pip freeze

```
python = "^3.10"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
nuitka = "^1.4"
opentelemetry-api = "^1.10.0"
opentelemetry-sdk = "^1.10.0"
opentelemetry-exporter-jaeger = "^1.10.0"
opentelemetry-instrumentation = "^0.29b0"
opentelemetry-instrumentation-redis = "^0.29b0"
opentelemetry-instrumentation-fastapi = "^0.29b0"
opentelemetry-instrumentation-httpx = "^0.29b0"
opentelemetry-instrumentation-sqlalchemy = "^0.29b0"
opentelemetry-instrumentation-botocore = "0.29b0"
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import uvicorn

from fastapi import FastAPI
from opentelemetry import trace
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

from typing import List, Optional

import fastapi
from fastapi.middleware.cors import CORSMiddleware
from opentelemetry.exporter.jaeger.thrift import JaegerExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor


def setup_tracing(*, app: FastAPI, service_name: str, jaeger_agent_host_name: str, jaeger_agent_port: int) -> None:
    tracer_provider = TracerProvider(resource=Resource.create({SERVICE_NAME: service_name}))
    jaeger_exporter = JaegerExporter(agent_host_name=jaeger_agent_host_name, agent_port=jaeger_agent_port)
    tracer_provider.add_span_processor(BatchSpanProcessor(jaeger_exporter))
    trace.set_tracer_provider(tracer_provider)
    FastAPIInstrumentor.instrument_app(app=app)


def create_app(cors_origins: Optional[List[str]] = None):

    app = fastapi.FastAPI(
        title="Example API",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=cors_origins or [],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/health")
    async def health():
        return "The API server is healthy."

    return app


cors_origins = ["*"]
app = create_app(cors_origins)
host = "127.0.0.1"
port = 8000

kwargs = {
    "app": app,
    "host": host,
    "port": port,
    "reload": "True",
}

if __name__ == '__main__':
    uvicorn.run(app=create_app, port=8080, access_log=False)

```

* Provide in your issue the Nuitka options used

```
python -m nuitka --standalone --follow-imports --static-libpython=no main.py
```
```
Traceback (most recent call last):
  File "/Users/yragantron/projects/test_fastapi/main.dist/main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/projects/test_fastapi/main.dist/opentelemetry/exporter/jaeger/thrift/__init__.py", line 93, in <module opentelemetry.exporter.jaeger.thrift>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/projects/test_fastapi/main.dist/opentelemetry/exporter/jaeger/thrift/translate/__init__.py", line 21, in <module opentelemetry.exporter.jaeger.thrift.translate>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1222, in __init__
  File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1244, in _recalculate
TypeError: 'NoneType' object is not callable
```

I install Nutila with a modified config standard.nuitka-package.config.yml, which solves some of the problems with opentelemetry
Here my changes
```
- module-name: 'opentelemetry.exporter.jaeger.thrift.gen.agent.ttypes'
  anti-bloat:
    - replacements_plain:
        'import jaeger.ttypes': "from ..jaeger import ttypes as jaegerTtypes"
        'import zipkincore.ttypes': "from ..zipkincore import ttypes as zipkincoreTtypes"

- module-name: 'opentelemetry.exporter.jaeger.thrift.gen.agent.Agent'
  anti-bloat:
    - replacements_plain:
        'jaeger.ttypes': "jaegerTtypes"
        'zipkincore.ttypes': "zipkincoreTtypes"


- module-name: 'opentelemetry.propagate'
  anti-bloat:
    - module_code: |
        import typing
        from logging import getLogger
        from pkg_resources import iter_entry_points
        from opentelemetry.context.context import Context
        from opentelemetry.propagators import composite, textmap
        logger = getLogger(__name__)
        def extract(
            carrier: textmap.CarrierT,
            context: typing.Optional[Context] = None,
            getter: textmap.Getter = textmap.default_getter,
        ) -> Context:
            return get_global_textmap().extract(carrier, context, getter=getter)
        def inject(
            carrier: textmap.CarrierT,
            context: typing.Optional[Context] = None,
            setter: textmap.Setter = textmap.default_setter,
        ) -> None:
            get_global_textmap().inject(carrier, context=context, setter=setter)
        from opentelemetry.trace.propagation.tracecontext import TraceContextTextMapPropagator
        from opentelemetry.baggage.propagation import W3CBaggagePropagator
        propagators = [TraceContextTextMapPropagator(), W3CBaggagePropagator()]
        _HTTP_TEXT_FORMAT = composite.CompositePropagator(propagators)  # type: ignore
        def get_global_textmap() -> textmap.TextMapPropagator:
            return _HTTP_TEXT_FORMAT
        def set_global_textmap(
            http_text_format: textmap.TextMapPropagator,
        ) -> None:
            global _HTTP_TEXT_FORMAT  # pylint:disable=global-statement
            _HTTP_TEXT_FORMAT = http_text_format  # type: ignore
```

I do not understand what the problem is and how it can be debugged(

**Comment by kayhayen** [comment]
It's a shame, but I didn't manage to look at this in time.

**Comment by YraganTron** [comment]
I hope someday you have free time because I didn't understand the problem

**Comment by kayhayen** [comment]
The example is not working for me, `uvicorn.run('app.app:app', port=8080, access_log=False)` tries to read the source code, which of course with Nuitka will not exist. Can you use uvicorn in a way that this doesn't happen?

**Comment by YraganTron** [comment]
Of course, I changed the original example by passing a function instead of a string. 
```
uvicorn.run(app=create_app, port=8080, access_log=False)
```

Can you tell a little more about how to use it ```--include-distribution-metadata```?

**Comment by kayhayen** [comment]
Yes, docs are lacking there, I added it for the hotfix of opentelemetry with 1.7.x only and didn't add it to https://nuitka.net/doc/nuitka-package-config.html yes, which I want to make though, along with a posting explaining the opentelemetry case.

**Comment by kayhayen** [comment]
So, it seems we need this one at least, since it does the evil thing, and expands `sys.path` with one of its package folders, which is terribly bad thing to do, but it's the second package we see this in. 

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by YraganTron** [comment]
```
Failed to load configured propagator `tracecontext`
Traceback (most recent call last):
  File "/Users/yragantron/evo_projects/facilities/main.dist/opentelemetry/propagate/__init__.py", line 137, in <module opentelemetry.propagate>
StopIteration
Traceback (most recent call last):
  File "/Users/yragantron/evo_projects/facilities/main.dist/main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/app/app.py", line 9, in <module app.app>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/fleet_backend_sdk/tracing_async/__init__.py", line 1, in <module fleet_backend_sdk.tracing_async>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/fleet_backend_sdk/tracing_async/tracing.py", line 9, in <module fleet_backend_sdk.tracing_async.tracing>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/fleet_backend_sdk/tracing_async/patched/fastapi_instrumentor.py", line 6, in <module fleet_backend_sdk.tracing_async.patched.fastapi_instrumentor>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/opentelemetry/instrumentation/fastapi/__init__.py", line 87, in <module opentelemetry.instrumentation.fastapi>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/opentelemetry/instrumentation/asgi/__init__.py", line 110, in <module opentelemetry.instrumentation.asgi>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/opentelemetry/instrumentation/utils.py", line 25, in <module opentelemetry.instrumentation.utils>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/yragantron/evo_projects/facilities/main.dist/opentelemetry/propagate/__init__.py", line 137, in <module opentelemetry.propagate>
StopIteration
```

he error has changed a little, apparently the package needs fixing opentelemetry-instrumentation-fastapi

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.6 that I just made.
