### ISSUE TITLE
Suggestion: Abort compilation if python env is missing a module

### ISSUE THREAD

**Issue by Bingdom** [Nuitka/Nuitka#2120]
I'm setting up a CD environment, and I've noticed I've released binaries with the missing required modules.
Fortunately not in production yet, but this could've caused catastrophic damage.

Just wondering if it would be a good idea if Nuitka could verify that the current python environment has the available modules for the project it's compiling, so we avoid errors like this:

```
2023-03-17 21:12:22 Traceback (most recent call last):
2023-03-17 21:12:22   File "/home/pi/service/backend/server.py", line 31, in <module>
2023-03-17 21:12:22   File "/home/pi/service/backend/GraphQL/Query.py", line 13, in <module GraphQL.Query>
2023-03-17 21:12:22   File "/home/pi/service/backend/Updater.py", line 17, in <module Updater>
2023-03-17 21:12:22 ModuleNotFoundError: No module named 'github'
```

Am going to incorporate some basic tests on the build to prevent this from happening of course. It would be nice to completely avoid waiting on the build if it's going to fail anyways.

**Comment by kayhayen** [comment]
I have started `nuitka-watch` which will recompile for PyPI changes and Nuitka changes, producing report diffs for tracking in said repo. It lacks the dependency recognition, but I do not want to track it here really, so I am closing it. At some point we will probably describe how to add to that repo for general PyPI packages and how to use the tool for your own compilation to recognise changes, but I do not see this as a good place to track that.
