### ISSUE TITLE
Distutils: Providing script name doesn't work in pyproject.toml

### ISSUE THREAD

**Issue by spbaecchi** [Nuitka/Nuitka#2126]
Hi, I'm having some trouble building a project with nuitka 1.5 (works fine with 1.4). I've prepared a simple project to show the issue:
```
project/
├── pyproject.toml
└── src
    └── mylib
        ├── __init__.py
        └── script.py
```

script.py:
```
def main():
    pass
```

pyproject.toml:
```
[build-system]
requires = ["setuptools>=66.1", "wheel", "toml", "nuitka"]
build-backend = "nuitka.distutils.Build"

[project]
name = "mylib"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
my-program = "mylib.script:main"

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["mylib"]
```

`__init__.py` is empty.

I'm using Ubuntu 22.04 with python 3.10.6 in a clean virtualenv with only `build` installed:
```
$ pip freeze
build==0.10.0
packaging==23.0
pyproject_hooks==1.0.0
toml==0.10.2
tomli==2.0.1
```

And I'm building with the command `python3 -m build .` to generate the wheel.

I'm also attaching the complete output of the build command:
```
* Creating venv isolated environment...
* Installing packages in isolated environment... (nuitka, setuptools>=66.1, toml, wheel)
* Getting build dependencies for sdist...
/tmp/build-env-f8sdf_pp/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running egg_info
creating src/mylib.egg-info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
* Building sdist...
/tmp/build-env-f8sdf_pp/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running sdist
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating mylib-0.1.0
creating mylib-0.1.0/src
creating mylib-0.1.0/src/mylib
creating mylib-0.1.0/src/mylib.egg-info
copying files to mylib-0.1.0...
copying pyproject.toml -> mylib-0.1.0
copying src/mylib/__init__.py -> mylib-0.1.0/src/mylib
copying src/mylib/script.py -> mylib-0.1.0/src/mylib
copying src/mylib.egg-info/PKG-INFO -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/SOURCES.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/dependency_links.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/entry_points.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/top_level.txt -> mylib-0.1.0/src/mylib.egg-info
Writing mylib-0.1.0/setup.cfg
Creating tar archive
removing 'mylib-0.1.0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (nuitka, setuptools>=66.1, toml, wheel)
* Getting build dependencies for wheel...
/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running bdist_nuitka
running build
Nuitka-Wheel:INFO: Specified packages: ['mylib'].
Nuitka-Wheel:INFO: Specified modules: None.
running build_py
creating build
creating build/lib
creating build/lib/mylib
copying src/mylib/script.py -> build/lib/mylib
copying src/mylib/__init__.py -> build/lib/mylib
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/tmp/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/tmp/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/nuitka/distutils/Build.py", line 43, in build_wheel
    return self._build_with_temp_dir(
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
    self.run_command("build")
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/nuitka/distutils/DistutilCommands.py", line 113, in run
    self._build(os.path.abspath(self.build_lib))
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/nuitka/distutils/DistutilCommands.py", line 219, in _build
    for is_package, module_name in self._findBuildTasks():
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/nuitka/distutils/DistutilCommands.py", line 148, in _findBuildTasks
    ) = decideModuleSourceRef(
  File "/tmp/build-env-53jhgjkw/lib/python3.10/site-packages/nuitka/importing/Importing.py", line 778, in decideModuleSourceRef
    assert filename is not None
AssertionError

ERROR Backend subprocess exited when trying to invoke build_wheel
```

The "problem" seems to be tied to the 
```
[project.scripts]
my-program = "mylib.script:main"
```
part in the `pyproject.toml` file. If I remove the script, the compilation completes successfully.

Thanks.

**Comment by kayhayen** [comment]
Maybe it is related to using `src`. We have in fact an example `tests/distutils/example_pyproject_3/pyproject.nuitka.toml` which appears to work. The first order of action, is of course to know if it is searching for the proper module name or not. I will try and enhance the error message there.

**Comment by kayhayen** [comment]
Thanks for your report, please report what happens with this on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

This will output the name of the module. If you add 

```
[nuitka]
explain-imports = true
```

to your configuration, it will output bad traces for the import mechanism. That should allow us to close in somewhat, ideally use a minimal test case like mentioned for that.

**Comment by spbaecchi** [comment]
Hi, thanks for the instructions. I did the following changes:

pyproject.toml
```
[build-system]
requires = ["setuptools>=66.1", "wheel", "toml", "https://github.com/Nuitka/Nuitka/archive/factory.zip"]
build-backend = "nuitka.distutils.Build"

[project]
name = "mylib"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
my-program = "mylib.script:main"

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["mylib"]

[nuitka]
explain-imports = true
```

And got the following output:
```
* Creating venv isolated environment...
* Installing packages in isolated environment... (https://github.com/Nuitka/Nuitka/archive/factory.zip, setuptools>=66.1, toml, wheel)
* Getting build dependencies for sdist...
/tmp/build-env-20vt_9p_/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
* Building sdist...
/tmp/build-env-20vt_9p_/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running sdist
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating mylib-0.1.0
creating mylib-0.1.0/src
creating mylib-0.1.0/src/mylib
creating mylib-0.1.0/src/mylib.egg-info
copying files to mylib-0.1.0...
copying pyproject.toml -> mylib-0.1.0
copying src/mylib/__init__.py -> mylib-0.1.0/src/mylib
copying src/mylib/script.py -> mylib-0.1.0/src/mylib
copying src/mylib.egg-info/PKG-INFO -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/SOURCES.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/dependency_links.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/entry_points.txt -> mylib-0.1.0/src/mylib.egg-info
copying src/mylib.egg-info/top_level.txt -> mylib-0.1.0/src/mylib.egg-info
Writing mylib-0.1.0/setup.cfg
Creating tar archive
removing 'mylib-0.1.0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (https://github.com/Nuitka/Nuitka/archive/factory.zip, setuptools>=66.1, toml, wheel)
* Getting build dependencies for wheel...
/tmp/build-env-15wk7u8z/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
/tmp/build-env-15wk7u8z/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running bdist_nuitka
running build
Nuitka-Wheel:INFO: Specified packages: ['mylib'].
Nuitka-Wheel:INFO: Specified modules: None.
running build_py
creating build
creating build/lib
creating build/lib/mylib
copying src/mylib/script.py -> build/lib/mylib
copying src/mylib/__init__.py -> build/lib/mylib
running egg_info
writing src/mylib.egg-info/PKG-INFO
writing dependency_links to src/mylib.egg-info/dependency_links.txt
writing entry points to src/mylib.egg-info/entry_points.txt
writing top-level names to src/mylib.egg-info/top_level.txt
reading manifest file 'src/mylib.egg-info/SOURCES.txt'
writing manifest file 'src/mylib.egg-info/SOURCES.txt'
FATAL: Error, failed to locate script containing module 'mylib.script'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

I also tried building without the script (using the factory branch) and it completed successfully.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

I am closing this early due to being considered a duplicate, and the solution being tracked eleswhere.

**Comment by spbaecchi** [comment]
I confirm it is now working properly using the factory branch.

Thank you very much. Have a nice weekend.

**Comment by kayhayen** [comment]
It's going out as part of 1.5.4 today.
