### ISSUE TITLE
Compile python module with taichi code

### ISSUE THREAD

**Issue by ustcfdm** [Nuitka/Nuitka#2132]
I have a python module with [taichi](https://github.com/taichi-dev/taichi) code, which can compile python functions with `@taichi.kernel` decorators into CPU/GPU machine code to improve performance. 

When I compile a python module into exe using Nuitka, the exe works well; but if I compile it into a pyd module, it raise an error when I import this pyd module.

The following is my sample code with filename as `taichi_test.py`.
```python
import taichi as ti
ti.init(arch=ti.cpu)

@ti.kernel
def calc_sum_taichi(n: int) -> int:
    s = 0
    for i in range(1, n+1):
        s += i
    return s

def calc_sum_python(n: int) -> int:
    s = 0
    for i in range(1, n+1):
        s += i
    return s
    
print('Python:', calc_sum_python(100))
print('Taichi:', calc_sum_taichi(100))
```

Command to compile to exe: `python -m nuitka taichi_test.py`
Result after executing the compiled `taichi_test.exe` file:
```
[Taichi] version 1.4.0, llvm 15.0.1, commit fbe92fd8, win, python 3.10.5
[I 03/23/23 10:42:30.811 22012] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=x64
Python: 5050
Taichi: 5050
```

Command to compile to pyd: `python -m nuitka --module taichi_test.py`
Result when I try to import this pyd in a python code:
```
>>> import taichi_test
[Taichi] version 1.4.0, llvm 15.0.1, commit fbe92fd8, win, python 3.10.5
[I 03/23/23 10:38:10.386 7496] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=x64
Python: 5050
Traceback (most recent call last):
  File "C:\Users\username\scoop\apps\python\current\lib\site-packages\taichi\lang\_wrap_inspect.py", line 104, in _Python_IPython_findsource
    return _builtin_findsource(obj)
  File "C:\Users\username\scoop\apps\python\current\lib\inspect.py", line 958, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

I am not sure whether this issue belongs to Taichi or Nuitka, since Taichi also makes a compilation work in the backend. The purpose that I want to compile to pyd file is to protect source code. If there is any other way to achieve this purpose, it will also be helpful.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by ustcfdm** [comment]
@kayhayen I apologized that I did not pay attention to the issue template. I have modified my description as detail as I can following the template. Please let me know if I need to provide additional information.

**Comment by kayhayen** [comment]
So much better. Now I would also welcome you to use the latest release. Not hoping it will change anyway. But I am pretty sure the issue template tried to encourage that. I am however maybe guilty of not yet announcing 1.5 on the blog.

Also, am I correct in assuming, you want to load inside Blender a plugin? Notice that for accelerated mode, the source code reference is probably full path, where as for the module it is, where that file actually lives. If you put it along the source code, that code will be found.

Now knowing what Nuitka is frequently used for of course, I assume you do not want the source code to be deployed, because  otherwise, your issue is easily resolved.

When that is not the case, I asume this is the JIT trying to do magic. With the torch, etc. we got it under control, but no idea if for taichi it can be done. If you have any pointers on that, please provide them.

**Comment by kayhayen** [comment]
Then this is a duplicate. We need to do similar for Numba, but so far it has not been implemented. I need somebody to step up to pay me for this, or it will happen only far later, as obviously it's not as much a priority yet. At some point, we would like to e.g. be able to replace Numba JIT with a or comparable better one from Nuitka, but we are not yet there in terms of infrastructure.

**Comment by jarmitage** [comment]
@ustcfdm I am also interested in using Nuitka and Taichi together.

Did you consider using Taichi AOT export (https://docs.taichi-lang.org/docs/tutorial) and combining that with a Nuitka build for the rest of your Python program?

**Comment by ustcfdm** [comment]
@jarmitage Currently, there is not a stable release of Taichi AOT, according to its document:

> Currently, only TiRT for Linux systems is included in the nightly distributions. If you need one for Android / Windows, please see the FAQ below to build it from source.

In addition, I am a Windows user. I am not going to try AOT until a stable version for Windows is released.

**Comment by Ziqiliu** [comment]
@ustcfdm Was exe also improved by Taichi, like directly run python code?

**Comment by jarmitage** [comment]
@ustcfdm did you do any more experiments with taichi and nuitka?
