### ISSUE TITLE
FATAL: delvewheel: Plugin issue while working on 'module 'matplotlib''. Please report the bug with the above traceback included.

### ISSUE THREAD

**Issue by wangyexiang** [Nuitka/Nuitka#2150]
*  python -m nuitka --version

 ```
1.5.3
Commercial: None
Python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\abc\.virtualenvs\api\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).
```

* How did you install Nuitka and Python

nuitka: `  pip`
python:  `it's a venv with Anaconda Python `

* The specific PyPI names and versions

```
autopep8            2.0.2
black               23.1.0
click               8.1.3
colorama            0.4.6
contourpy           1.0.7
cycler              0.11.0
Flask               2.2.3
fonttools           4.39.2
imageio             2.27.0
importlib-metadata  6.1.0
importlib-resources 5.12.0
itsdangerous        2.1.2
Jinja2              3.1.2
kiwisolver          1.4.4
MarkupSafe          2.1.2
matplotlib          3.7.1
mypy-extensions     1.0.0
Nuitka              1.5.3
numpy               1.24.2
ordered-set         4.1.0
packaging           23.0
pathspec            0.11.1
Pillow              9.4.0
pip                 23.0.1
platformdirs        3.1.1
pycodestyle         2.10.0
pyparsing           3.0.9
python-dateutil     2.8.2
setuptools          58.1.0
six                 1.16.0
tomli               2.0.1
typing_extensions   4.5.0
Werkzeug            2.2.3
zipp                3.15.0
zstandard           0.20.0
```
* nuitka command
`python -m nuitka --onefile --disable-console a.py`
I get the results:

```
Nuitka-Options:INFO: Used command line options: --onefile --disable-console a.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.3' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: delvewheel: Detected usage of 'delvewheel' version '1.3.3' in module 'matplotlib'.
PASS 1: 0.3%|                         | 1/344, appTraceback (most recent call last):
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\Plugins.py", line 77, in withPluginProblemReporting
    yield
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\Plugins.py", line 912, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(module_name, source_code)
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\standard\DelvewheelPlugin.py", line 103, in onModuleSourceCode
    assert self.dll_directory is not None, module_name
AssertionError: matplotlib
FATAL: delvewheel: Plugin issue while working on 'module 'matplotlib''. Please report the bug with the above traceback included.
```
How to fix it? Thanks.

**Comment by kayhayen** [comment]
How about using the latest stable release?

I am not aware of DLLs in `matplotlib` and so this appears to be dead code there, which is kind of strange to see. But of course, it can be possible that they use it and even have their DLL patching in place without actual DLLs. This doesn't appear to be from Conda packages.

**Comment by wangyexiang** [comment]
Dear sir, thank you for your reply. It is fixed by using the latest stable release.

**Comment by kayhayen** [comment]
This has to be Anaconda specific, not sure how that would happen. I managed to compile matplotlib in the given version from PyPI no problem. When I find the time, I will try and do it on Anaconda as well, but this may have to wait for me to add support for it to Nuitka-Watch.

**Comment by kayhayen** [comment]
This looks like a duplicate of #2260 that is now fixed on factory branch. Closing as a duplicate.
