### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com.shell' when importing winshell

### ISSUE THREAD

**Issue by sw2719** [Nuitka/Nuitka#2185]
* Nuitka version
```
1.6rc7
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 19:43:38) [MSC v.1934 32 bit (Intel)]
Flavor: CPython Official
Executable: C:\Users\sw2719\AppData\Local\Programs\Python\Python310-32\python.exe
OS: Windows
Arch: x86
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x86\cl.exe (cl 14.3)
```

Used following command to install dev version: ```pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"```
Python is installed with Windows installer.
Note that I tried stable and dev version but results were the same.

* PyPI packages Involved
```
pywin32==304
winshell==0.6
```

* Test code and Nuitka options used
```python
import winshell

if __name__ == "__main__":
    desktop = winshell.desktop()
    print(f"Desktop directory is {desktop}")
```
```python -m nuitka --standalone main.py```
Also tried ```--include-package=win32com``` but didn't make any difference.

Compilation goes without issues but following error occurs when running the compiled executable:
```
Traceback (most recent call last):
  File "C:\Users\sw2719\Desktop\TESTGR~1\MAIN~1.DIS\main.py", line 1, in <module>
  File "C:\Users\sw2719\Desktop\TESTGR~1\MAIN~1.DIS\winshell.py", line 32, in <module winshell>
ModuleNotFoundError: No module named 'win32com.shell'
```

Please let me know if I did anything wrong, more info is needed or this is just unsupported. Thanks.

**Comment by kayhayen** [comment]
For some reason this is not effective (anymore):

```
- module-name: 'win32com'
  import-hacks:
    # This package adds another directory to the search path of itself,
    # which we will not find packages in unless added.
    - package-dirs:
        - 'win32comext'
      when: 'win32'
```

**Comment by sw2719** [comment]
Yep it does work on factory branch.
