### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by GF-Huang** [Nuitka/Nuitka#2187]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this* command.
```
1.5.6
Commercial: None
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Miniconda3\envs\auto-maple\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).
```

* How did you install Nuitka and Python
```
Anaconda environment install by pip.
```
* The specific PyPI names and versions
```
absl-py==1.4.0
altgraph==0.17.3
astunparse==1.6.3
boltons @ file:///home/conda/feedstock_root/build_artifacts/boltons_1677499911949/work
brotlipy @ file:///D:/bld/brotlipy_1666764804378/work
cachetools==5.3.0
certifi==2022.12.7
cffi @ file:///D:/bld/cffi_1671179506518/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1678108872112/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda==23.3.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/work
cryptography @ file:///D:/bld/cryptography-split_1681508778756/work
flatbuffers==23.3.3
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.17.3
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.54.0
h5py==3.8.0
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
jax==0.4.8
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpointer==2.0
keras==2.12.0
keyboard==0.13.5
libclang==16.0.0
Markdown==3.4.3
MarkupSafe==2.1.2
menuinst @ file:///D:/bld/menuinst_1666839998718/work
ml-dtypes==0.1.0
mss==8.0.3
Nuitka==1.5.6
numpy==1.23.5
oauthlib==3.2.2
opencv-python-headless==4.7.0.72
opt-einsum==3.3.0
ordered-set==4.1.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pefile==2023.2.7
Pillow==9.5.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
protobuf==4.22.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///D:/bld/pycosat_1666836675990/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pygame==2.3.0
pyinstaller==5.10.1
pyinstaller-hooks-contrib==2023.2
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1680037383858/work
PySocks @ file:///D:/bld/pysocks_1661604991356/work
pywin32==306
pywin32-ctypes==0.2.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1680286922386/work
requests-oauthlib==1.3.1
rsa==4.9
ruamel.yaml @ file:///D:/bld/ruamel.yaml_1678273308128/work
ruamel.yaml.clib @ file:///D:/bld/ruamel.yaml.clib_1670412994006/work
scipy==1.10.1
six==1.16.0
smmap==5.0.0
tensorboard==2.12.2
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-intel==2.12.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.2.0
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
typing_extensions==4.5.0
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
Werkzeug==2.2.3
win-inet-pton @ file:///D:/bld/win_inet_pton_1667051142467/work
wrapt==1.14.1
zstandard==0.19.0
```

* Provide in your issue the Nuitka options used
```
(auto-maple) C:\Users\Xxx\Desktop\auto-maple-2.3.6>nuitka.bat --standalone --include-data-dir=assets=assets --include-
data-dir=resources=resources --nofollow-import-to=unittest main.py
Nuitka-Options:INFO: Used command line options: --standalone --include-data-dir=assets=assets --include-data-dir=resources=resources --nofollow-import-to=unittest main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.6' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 322 files (no progress information available).
Nuitka-Scons:INFO: Compiled 322 C files using clcache with 322 cache hits and 0 cache misses.
Nuitka-Options:INFO: Included 20 data files due to specified data dir 'assets' on command line.
Nuitka-Options:INFO: Included 55 data files due to specified data dir 'resources' on command line.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from cv2 installation.
Nuitka-Plugins:WARNING: dll-files: DLL configuration by filename code for 'numpy' did not give a result. Either
Nuitka-Plugins:WARNING: conditions are missing, or this version of the module needs treatment added.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from numpy installation.
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.dist\main.exe'.

(auto-maple) C:\Users\Xxx\Desktop\auto-maple-2.3.6>cd main.dist\

(auto-maple) C:\Users\Xxx\Desktop\auto-maple-2.3.6\main.dist>main.exe
Traceback (most recent call last):
  File "C:\Users\Xxx\Desktop\AUTO-M~1.6\MAIN~1.DIS\main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Xxx\Desktop\AUTO-M~1.6\MAIN~1.DIS\src\modules\bot.py", line 11, in <module src.modules.bot>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1222, in __init__
  File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1244, in _recalculate
TypeError: 'NoneType' object is not callable
```

**Comment by kayhayen** [comment]
My mind reading skills are not good enough to do anything without a minimal reproducer.

**Comment by kayhayen** [comment]
I am not sure you if know what *minimal* means. I can unfortunately not just run big chunks of foreign code or make sure it is harmless to extra a minimal reproducer. I expect you do to that for me. Then I fix the bug of Nuitka. That is how it works unless somebody pays for my time to do it in their environment, etc.

**Comment by GF-Huang** [comment]
So, can you tell please how to debug this issue? 

```
Traceback (most recent call last):
  File "C:\Users\Xxx\Desktop\AUTO-M~1.6\MAIN~1.DIS\main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Xxx\Desktop\AUTO-M~1.6\MAIN~1.DIS\src\modules\bot.py", line 11, in <module src.modules.bot>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1222, in __init__
  File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1244, in _recalculate
TypeError: 'NoneType' object is not callable
```

**Comment by kayhayen** [comment]
By making a small script that exhibits just that issue. You remove stuff and come up with a small thing.

**Comment by kayhayen** [comment]
Nothing coming forward here sadly, I guess I will have to close this when nothing small is provided to reproduce.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
