### ISSUE TITLE
NameError: name 'importlib' is not defined

### ISSUE THREAD

**Issue by PJDude** [Nuitka/Nuitka#2190]
Hi.

sources of project:
https://github.com/PJDude/dude

How to repeat:
pip install -r requirements.txt
scripts\nuitka.run.bat
build-nuitka-win\dude.exe

error:

C:\temp\ve\3.11\d\build-nuitka-win>dude
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\dude.py", line 62, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\send2trash\__init__.py", line 14, in <module send2trash>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\send2trash\plat_win.py", line 14, in <module send2trash.plat_win>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\send2trash\plat_win_modern.py", line 12, in <module send2trash.plat_win_modern>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\pythoncom.py", line 2, in <module pythoncom>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\pywintypes.py", line 126, in <module pywintypes>
  File "C:\Users\user\AppData\Local\Temp\ONF1D0~1\pywintypes.py", line 26, in __import_pywin32_system_module__
NameError: name 'importlib' is not defined

virtual environment that WORKS:
#################################
1.5.6
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\temp\ve\3.10\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
#################################

virtual environment with ERROR:
#################################
1.5.6
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\temp\ve\3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
#################################

virtual environment with ERROR and nuitka from factory branch:
#################################
1.6rc7
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\temp\ve\3.11-fact\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
#################################

windows only (linux works)

**Comment by kayhayen** [comment]
While it's laudable that you provide your project source code, I really need something more minimal. I cannot afford to run just arbitrary code, not even pip install random projects.

It appears that you are saying that pywin32 is not working with 3.11 which may well be and would be something to check. Can you try and come up with a minimal code snippet. I guess `import pythoncom` will already do.

**Comment by PJDude** [comment]
Nuitka is semi-commercial product is that right ? and since we both value our time, testing and reporting bugs is something that need time and has value too. I provided an example. too big ? tough. I guess I just need to wait.

**Comment by kayhayen** [comment]
Well, Nuitka is Free Software and supported on my time. It is the basis for Nuitka commercial, which does things most people don't need. That doesn't make it so, that I will go to arbitrary lengths when search issues. Since this is largely irrelevant, I am going to delete it later.
