### ISSUE TITLE
FATAL: implicit-imports: Plugin issue while working on 'module 'pyodbc''.

### ISSUE THREAD

**Issue by shoma-kagami** [Nuitka/Nuitka#2200]
### Configurations
`nuitka --mingw64 --follow-import-to=pyodbc --standalone --enable-plugin=tk-inter traceability.py`

When executed, the following error is output.

Nuitka-Options:INFO: Used command line options: --mingw64 --follow-import-to=pyodbc --standalone --enable-plugin=tk-inter test.py
Nuitka:WARNING: The Python version '3.11' is only experimentally supported by Nuitka '1.5.7', but an upcoming release
Nuitka:WARNING: will change that. In the mean time use Python version '3.10' instead or newer Nuitka.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.7' on Python '3.11' commercial grade 'not installed'.
PASS 1: 0.3%|                         | 1/367, pyodbcTraceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 77, in withPluginProblemReporting
    yield
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 469, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 361, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 338, in iterateModuleNames
    for v in value:
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\plugins\standard\ImplicitImports.py", line 270, in getImplicitImports
    for used_module_name in module.getPyIModuleImportedNames():
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\nodes\ModuleNodes.py", line 1078, in getPyIModuleImportedNames
    self._readPyIFile()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\nodes\ModuleNodes.py", line 996, in _readPyIFile
    assert parts[2] == "import"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
FATAL: implicit-imports: Plugin issue while working on 'module 'pyodbc''. Please report the bug with the above traceback included.

### Nuitka version
1.5.7
Commercial: None
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).

### pyodbc version
4.0.39

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by LeonidShamis** [comment]
I have the same problem:

**Nuitka** 
1.5.7
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/package-with-dependencies/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).

**pyodbc**
4.0.39

```
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ python -m nuitka --onefile db_app_query_generic.py
Nuitka-Options:INFO: Used command line options: --onefile db_app_query_generic.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.7' on Python '3.10' commercial grade 'not installed'.
PASS 1: 8.2%|██                       | 32/391, pyodbc   Traceback (most recent call last):
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 77, in withPluginProblemReporting
    yield
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 469, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 361, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 338, in iterateModuleNames
    for v in value:
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 270, in getImplicitImports
    for used_module_name in module.getPyIModuleImportedNames():
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 1078, in getPyIModuleImportedNames
    self._readPyIFile()
  File "/home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 996, in _readPyIFile
    assert parts[2] == "import"
AssertionError
FATAL: implicit-imports: Plugin issue while working on 'module 'pyodbc''. Please report the bug with the above traceback included.
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ pip freeze | grep pyodbc
pyodbc==4.0.39
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ python -m nuitka --version
1.5.7
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/package-with-dependencies/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$
```

**Comment by LeonidShamis** [comment]
Confirming that the issue is fixed in the factory branch as suggested by @kayhayen [here](https://github.com/Nuitka/Nuitka/issues/2200#issuecomment-1527069699)

```
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ pip uninstall nuitka
Found existing installation: Nuitka 1.5.7
Uninstalling Nuitka-1.5.7:
  Would remove:
    /home/leonid/dev/python/package-with-dependencies/.venv/bin/nuitka3
    /home/leonid/dev/python/package-with-dependencies/.venv/bin/nuitka3-run
    /home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/Nuitka-1.5.7.dist-info/*
    /home/leonid/dev/python/package-with-dependencies/.venv/lib/python3.10/site-packages/nuitka/*
Proceed (Y/n)? y
  Successfully uninstalled Nuitka-1.5.7
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
Collecting https://github.com/Nuitka/Nuitka/archive/factory.zip
  Downloading https://github.com/Nuitka/Nuitka/archive/factory.zip
     \ 6.4 MB 7.1 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ordered-set>=4.1.0
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (pyproject.toml) ... done
  Created wheel for Nuitka: filename=Nuitka-1.6rc8-cp310-cp310-linux_x86_64.whl size=2849777 sha256=d7d1034d2a1e9143ebc7fe31383046ce586b4e930065936ee913d6d43407b5c1
  Stored in directory: /tmp/pip-ephem-wheel-cache-8ymvy6n3/wheels/12/88/12/96e4d1cdf9bcbea957e644c0a1e1ba5843c0143b1b03e240ed
Successfully built Nuitka
Installing collected packages: zstandard, ordered-set, Nuitka
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.21.0
    Uninstalling zstandard-0.21.0:
      Successfully uninstalled zstandard-0.21.0
  Attempting uninstall: ordered-set
    Found existing installation: ordered-set 4.1.0
    Uninstalling ordered-set-4.1.0:
      Successfully uninstalled ordered-set-4.1.0
Successfully installed Nuitka-1.6rc8 ordered-set-4.1.0 zstandard-0.21.0
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$

(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ python -m nuitka --version
1.6rc8
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/package-with-dependencies/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$

(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$ python -m nuitka --onefile db_app_query_generic.py
Nuitka-Options:INFO: Used command line options: --onefile db_app_query_generic.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc8' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 578 files (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar.txt' due to package data for 'lib2to3.pygram'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar.txt' due to package data for 'lib2to3.pygram'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html_style.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/html_table.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex_longtable.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/latex_table.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas/io/formats/templates/string.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (23.34%) size 182820512 to 42678406.
Nuitka-Onefile:INFO: Keeping onefile build directory 'db_app_query_generic.onefile-build'.
Nuitka:INFO: Keeping dist folder 'db_app_query_generic.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'db_app_query_generic.build'.
Nuitka:INFO: Successfully created 'db_app_query_generic.bin'.
(.venv) leonid@xlr2:~/dev/python/package-with-dependencies$
```

**Comment by shoma-kagami** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

Confirmed this works.

Thank you.

**Comment by cafinn** [comment]
This worked for me too.  Thank you for providing the factory branch.
