### ISSUE TITLE
No module named 'gymnasium.envs.box2d'

### ISSUE THREAD

**Issue by smelfungus** [Nuitka/Nuitka#2208]
Hello! I'm trying to use Nuitka with Gymnasium: https://gymnasium.farama.org/

**Environment:**
- Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
- Flavor: CPython Official
- OS: Windows
- Arch: x86_64
- WindowsRelease: 10
- Nuitka: 1.6rc8
- Nuitka: 1.5.7

**Installation:**
pip, venv

**Dependencies:**
```
box2d-py==2.3.5
cloudpickle==2.2.1
Farama-Notifications==0.0.4
gymnasium==0.28.1
jax-jumpy==1.0.0
Nuitka==1.5.7
numpy==1.24.3
ordered-set==4.1.0
pygame==2.1.3
pypiwin32==223
pywin32==306
swig==4.1.1
typing_extensions==4.5.0
zstandard==0.21.0
```

**Sample:**

```
import gymnasium as gym

env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()  # this is where you would insert your policy
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
env.close()
```

**Command:**
`nuitka --follow-imports test.py`

**Error:**

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    env = gym.make("LunarLander-v2", render_mode="human")
  File "venv\lib\site-packages\gymnasium\envs\registration.py", line 755, in make
    env_creator = load_env_creator(env_spec.entry_point)
  File "venv\lib\site-packages\gymnasium\envs\registration.py", line 553, in load_env_creator
    mod = importlib.import_module(mod_name)
  File "Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gymnasium.envs.box2d'
```

**Log:**
```
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 195 files (no progress information available).
Nuitka-Scons:INFO: Compiled 195 C files using clcache with 124 cache hits and 71 cache misses.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.exe'.
Nuitka:INFO: Execute it by launching 'test.cmd', the batch file needs to set environment.
```

**Comment by smelfungus** [comment]
It seems like `gymnasium.envs.box2d` was dynamically imported. 
`nuitka --follow-imports --include-module=gymnasium.envs.box2d test.py` did the trick! Thank you!

**Comment by kayhayen** [comment]
All it ever would have taken is to use `--include-module` but since backends are taken from the models used, doing it statically would have been a bad idea. So I added a non-deployment mode hook that makes it tell you to do that on whatever backend module is being attempted to be used and not found. This should make it easier to use for noobs.

**Comment by kayhayen** [comment]
Part of the 1.9.2 hotfix release I just made.
