### ISSUE TITLE
cassandra-driver - ModuleNotFoundError: No module named 'concurrent'

### ISSUE THREAD

**Issue by LeonidShamis** [Nuitka/Nuitka#2211]
I'm getting ```ModuleNotFoundError: No module named 'concurrent'``` with a very simple test Python program that demonstrates the issue encountered with a full program:

```
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ cat cassandra-driver-test.py
import cassandra
from cassandra.cluster import Cluster
print(f"cassandra version: {cassandra.__version__}")
print(f"Cluster info: {Cluster.__module__}")
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
```

Tested against Nuitka development version:

```
leonid@xlr2:~/dev/python/nuitka-test$ ls -al
total 12
drwxrwxr-x 2 leonid leonid 4096 May  2 13:47 .
drwxrwxr-x 4 leonid leonid 4096 May  2 13:15 ..
-rw-rw-r-- 1 leonid leonid  154 May  2 13:28 cassandra-driver-test.py
leonid@xlr2:~/dev/python/nuitka-test$ cat cassandra-driver-test.py
import cassandra
from cassandra.cluster import Cluster
print(f"cassandra version: {cassandra.__version__}")
print(f"Cluster info: {Cluster.__module__}")
leonid@xlr2:~/dev/python/nuitka-test$

leonid@xlr2:~/dev/python/nuitka-test$ python3 -m venv .venv
leonid@xlr2:~/dev/python/nuitka-test$ . .venv/bin/activate
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python --version
Python 3.10.6
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip --version
pip 22.0.2 from /home/leonid/dev/python/nuitka-test/.venv/lib/python3.10/site-packages/pip (python 3.10)
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install cassandra-driver
Collecting cassandra-driver
  Using cached cassandra_driver-3.26.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.6 MB)
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: six, click, geomet, cassandra-driver
Successfully installed cassandra-driver-3.26.0 click-8.1.3 geomet-0.2.1.post1 six-1.16.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/develop.zip"
Collecting https://github.com/Nuitka/Nuitka/archive/develop.zip
  Using cached https://github.com/Nuitka/Nuitka/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ordered-set>=4.1.0
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (pyproject.toml) ... done
  Created wheel for Nuitka: filename=Nuitka-1.6rc8-cp310-cp310-linux_x86_64.whl size=2846295 sha256=bc4798569ee1f4a3792c5ba1f3fbe4ed60de8d7787f29054bfc68ae63193e897
  Stored in directory: /tmp/pip-ephem-wheel-cache-hiy1hx94/wheels/66/e4/73/87b26aef9dd484b474b4b648400b5c9bbe37ae816aef871625
Successfully built Nuitka
Installing collected packages: zstandard, ordered-set, Nuitka
Successfully installed Nuitka-1.6rc8 ordered-set-4.1.0 zstandard-0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m pip freeze
cassandra-driver==3.26.0
click==8.1.3
geomet==0.2.1.post1
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip
ordered-set==4.1.0
six==1.16.0
zstandard==0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --version
1.6rc8
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/nuitka-test/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python cassandra-driver-test.py
cassandra version: 3.26.0
Cluster info: cassandra.cluster
(.venv) leonid@xlr2:~/dev/python/nuitka-test$

(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --standalone cassandra-driver-test.py
Nuitka-Options:INFO: Used command line options: --standalone cassandra-driver-test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc8' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 8 files (no progress information available).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'cassandra-driver-test.build'.
Nuitka:INFO: Successfully created 'cassandra-driver-test.dist/cassandra-driver-test.bin'.
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ls -lh cassandra-driver-test.dist/cassandra-driver-test.bin
-rwxrwxr-x 1 leonid leonid 10M May  2 13:49 cassandra-driver-test.dist/cassandra-driver-test.bin
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ./cassandra-driver-test.dist/cassandra-driver-test.bin
Traceback (most recent call last):
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/cassandra-driver-test.py", line 2, in <module>
  File "cassandra/cluster.py", line 24, in init cassandra.cluster
ModuleNotFoundError: No module named 'concurrent'
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
```

**Comment by kayhayen** [comment]
This seems like an easy case of missing implicit dependency:

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by kayhayen** [comment]
Did this myself now.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the 1.6.5 hotfix release just made.

**Comment by LeonidShamis** [comment]
Thank you for the fix.
I tested it with the Stable Release 1.6.6.
The original problem that I reported was resolved - Nuitka has successfully built the binary.
However, the binary did not work as the original Python program and in fact had issues - hence I'm adding the details here in case there should be any follow-up:

```
leonid@xlr2:~/dev/python/nuitka-test$ ls -l
total 4
-rw-rw-r-- 1 leonid leonid 154 May  2 13:28 cassandra-driver-test.py
leonid@xlr2:~/dev/python/nuitka-test$
leonid@xlr2:~/dev/python/nuitka-test$ cat cassandra-driver-test.py
import cassandra
from cassandra.cluster import Cluster

print(f"cassandra version: {cassandra.__version__}")
print(f"Cluster info: {Cluster.__module__}")
leonid@xlr2:~/dev/python/nuitka-test$
leonid@xlr2:~/dev/python/nuitka-test$ python3 -m venv .venv
leonid@xlr2:~/dev/python/nuitka-test$ . .venv/bin/activate
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python --version
Python 3.10.6
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip --version
pip 22.0.2 from /home/leonid/dev/python/nuitka-test/.venv/lib/python3.10/site-packages/pip (python 3.10)
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install cassandra-driver
Collecting cassandra-driver
  Downloading cassandra_driver-3.28.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 7.5 MB/s eta 0:00:00
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: six, click, geomet, cassandra-driver
Successfully installed cassandra-driver-3.28.0 click-8.1.3 geomet-0.2.1.post1 six-1.16.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m pip install -U nuitka
Collecting nuitka
  Using cached Nuitka-1.6.6-cp310-cp310-linux_x86_64.whl
Collecting zstandard>=0.15
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Collecting ordered-set>=4.1.0
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-1.6.6 ordered-set-4.1.0 zstandard-0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip freeze
cassandra-driver==3.28.0
click==8.1.3
geomet==0.2.1.post1
Nuitka==1.6.6
ordered-set==4.1.0
six==1.16.0
zstandard==0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --version
1.6.6
Commercial: None
Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/nuitka-test/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python cassandra-driver-test.py
cassandra version: 3.28.0
Cluster info: cassandra.cluster
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --standalone cassandra-driver-test.py
Nuitka-Options:INFO: Used command line options: --standalone cassandra-driver-test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.6' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 37 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'cassandra-driver-test.build'.
Nuitka:INFO: Successfully created 'cassandra-driver-test.dist/cassandra-driver-test.bin'.
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ls -l cassandra-driver-test.dist/cassandra-driver-test.bin
-rwxrwxr-x 1 leonid leonid 12933120 Jul  3 17:24 cassandra-driver-test.dist/cassandra-driver-test.bin
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ./cassandra-driver-test.dist/cassandra-driver-test.bin
Traceback (most recent call last):
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/cassandra-driver-test.py", line 2, in <module>
  File "cassandra/cluster.py", line 93, in init cassandra.cluster
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/cassandra/datastax/cloud/__init__.py", line 22, in <module cassandra.datastax.cloud>
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 97, in __get__
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 165, in _resolve
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 87, in _import_module
ModuleNotFoundError: No module named 'urllib.request'
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
```

**Comment by kayhayen** [comment]
@LeonidShamis please make this a new report, so it can be addressed
