### ISSUE TITLE
Create standalone nuitka deployment with only some parts of PyTorch

### ISSUE THREAD

**Issue by GelLiNN** [Nuitka/Nuitka#2218]
python3 -m nuitka --version
1.4.8
Commercial: None
Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Flavor: Debian Python
Executable: <path>/env/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).

pip freeze
absl-py==1.4.0
certifi==2022.12.7
charset-normalizer==3.1.0
cmake==3.26.3
filelock==3.12.0
h5py==3.8.0
idna==3.4
Jinja2==3.1.2
lit==16.0.2
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.1
Nuitka==1.4.8
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
ordered-set==4.1.0
packaging==23.1
pandas==2.0.1
Pillow==9.5.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.30.0
robust-loss-pytorch @ git+https://github.com/jonbarron/robust_loss_pytorch@9831f1db8006105fe7a383312fba0e8bd975e7f6
scipy==1.10.1
six==1.16.0
sympy==1.11.1
torch==2.0.0
torch-dct==0.1.6
torchmetrics==0.11.4
torchvision==0.15.1
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==2.0.2

I have a very simple question.  We are using torch for Data Science but must compile it to C in order to deploy to our customer's environment so we decided to use Nuitka.  I am very familiar with it at this point but I'm having a hard time finding the right way to use torch.  At first, the python code had 'import torch' and 'import torch.nn' statements throughout, which I've replaced with more specific imports of specific submodules.

However, on the next Nuitka compile I didn't see a difference in what was picked up.  The hope is that we will only include the submodules within torch that we are actually using, rather than everything.  This is so we can use the default anti-bloat option of Nuitka.  I noticed that if I use torch with Nuitka, it always fails with the following callstack if I use the default anti-bloat option:

No sympy found
Traceback (most recent call last):
  File "/home/knealy/dev/seismic-modules/__main__.dist/__main__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/denoiser/SMLDRunnerVOL.py", line 2, in <module denoiser.SMLDRunnerVOL>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/denoiser/ema.py", line 1, in <module denoiser.ema>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/__init__.py", line 1465, in <module torch>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_meta_registrations.py", line 7, in <module torch._meta_registrations>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_decomp/__init__.py", line 169, in <module torch._decomp>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_decomp/decompositions.py", line 10, in <module torch._decomp.decompositions>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_prims/__init__.py", line 33, in <module torch._prims>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_subclasses/__init__.py", line 3, in <module torch._subclasses>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_subclasses/fake_tensor.py", line 13, in <module torch._subclasses.fake_tensor>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_guards.py", line 78, in <module torch._guards>
  File "/home/knealy/dev/seismic-modules/__main__.dist/torch/_guards.py", line 79, in ShapeGuard
NameError: name 'sympy' is not defined

Now it thinks sympy is not defined but the real reason it's failing is because it doesn't have unittest which is ignored with the default anti-bloat.  And THIS is the reason we want to include parts of torch with our nuitka dist, but not all of it.

**Comment by GelLiNN** [comment]
This was the Nuitka command we used to compile:

python3 -m nuitka --standalone --lto=no --noinclude-default-mode=nofollow --nofollow-import-to=sqlalchemy --nofollow-import-to=pip --nofollow-import-to=tornado --nofollow-import-to=jinja2 --nofollow-import-to=lxml --nofollow-import-to=networkx --nofollow-import-to=contourpy --nofollow-import-to=charset-normalizer --nofollow-import-to=cmake --nofollow-import-to=plotly --nofollow-import-to=matplotlib --nofollow-import-to=seaborn --nofollow-import-to=filelock --nofollow-import-to=triton --nofollow-import-to=obspy --remove-output denoiser/__main__.py

**Comment by kayhayen** [comment]
I am working on anti-bloat for torch 2.0, I have noticed it is very keen on picking up `setuptools`. Using `nofollow` is not a replacement for anti-bloat, it's a try, and if it fails, you need to do things properly. If you could help there, that would be sweet.

I think `unittest` has frequently to be exempted from default handling because of `unittest.mock` which people use a lot to do actual stuff. As it stands, without example code, I don't think this issue has a lot to offer though. If you want to include unittest, then do.

**Comment by GelLiNN** [comment]
Thanks for the reply.  The example code would be no more than importing torch and doing some stuff with Torch.Tensor, Torch.nn.<submodules> and other various things in a simple __main__ python script.

as for your suggestion "Using nofollow is not a replacement for anti-bloat, it's a try, and if it fails, you need to do things properly. If you could help there, that would be sweet." can you elaborate more on what that means?  Thanks again!

**Comment by GelLiNN** [comment]
Actually a simpler version of my question would be, how can we use parts of PyTorch for the nuitka build, so when we call the executable at runtime we don't have to hit line 7, 427, and 429 here: https://github.com/pytorch/pytorch/blob/main/torch/_guards.py

When doing imports like this in the actual python
`from torch.nn import DataParallel as dp`

Is there a way to do that using `--no-follow-import-to`, or some other method?

**Comment by kayhayen** [comment]
The ability to exclude modules and have things work, is not a given unfortunately. Python projects barely support that, and torch doesn't seem to be one of them. The anti-bloat engine is however very powerful, it can replace module code e.g. and you can of course  try to empty the code, etc. 

The 427/429 line numbers didn't tell me anything. Can you elaborate?

**Comment by kayhayen** [comment]
So pytorch should work nicely with standalone and current develop and even with 1.6.4 as it is now, but the anti-bloat will be coming. This issue hasn't brought a clear problem forth for me and now there is a lack of feedback.

Should there be anti-bloat still missing, and if you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

But I dont see anything here, esp. nothing like a reproducer, so I am closing it.
