### ISSUE TITLE
sympy_1.12 causes RecursionError

### ISSUE THREAD

**Issue by chnccy** [Nuitka/Nuitka#2228]
Report an execution failure caused by recursion. I have solved the problem by modifying the version of sympy. I am not sure if this example is a problem that needs to be fixed by nuikta. I will try to describe this problem clearly.

When I use sympy1.12, nuitka reports an error when processing sympy.polys.numberfields.galois_resolventsTraceback.
Then I rolled back the sympy version to 1.11.1 and nuitka executed successfully.

**python -m nuitka --version**
1.5.7
Commercial: None
Python: 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: ~\.conda\envs\dev\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

**How did you install Nuitka and Python**
use pip, anaconda.

**The specific PyPI names and versions**
certifi==2023.5.7
charset-normalizer==3.1.0
colorama==0.4.6
filelock==3.12.0
idna==3.4
Jinja2==3.1.2
llvmlite==0.40.0
MarkupSafe==2.1.2
more-itertools==9.1.0
mpmath==1.3.0
networkx==3.1
Nuitka==1.5.7
numba==0.57.0
numpy==1.24.3
openai-whisper @ git+https://github.com/openai/whisper.git@248b6cb124225dd263bb9bd32d060b6517e067f8
ordered-set==4.1.0
regex==2023.5.5
requests==2.30.0
sympy==1.12
tiktoken==0.3.3
torch==2.0.1
tqdm==4.65.0
typing_extensions==4.5.0
urllib3==2.0.2
zstandard==0.21.0

PASS 1: 60.1%|███████████████          | 796/1324, sympy.polys.numberfields.galois_resolventsTraceback (most recent call last):
  File "···\.conda\envs\dev\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "···\.conda\envs\dev\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "···\.conda\envs\dev\lib\site-packages\nuitka\MainControl.py", line 1090, in main
    _main()
  File "···\.conda\envs\dev\lib\site-packages\nuitka\MainControl.py", line 950, in _main
    main_module = _createMainModule()
  File "···\.conda\envs\dev\lib\site-packages\nuitka\MainControl.py", line 244, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "···\.conda\envs\dev\lib\site-packages\nuitka\optimizations\Optimization.py", line 337, in optimizeModules
    finished = makeOptimizationPass()
  File "···\.conda\envs\dev\lib\site-packages\nuitka\optimizations\Optimization.py", line 293, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\optimizations\Optimization.py", line 180, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\optimizations\Optimization.py", line 140, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\importing\Recursion.py", line 455, in considerUsedModules
    new_module = recurseTo(
  File "···\.conda\envs\dev\lib\site-packages\nuitka\importing\Recursion.py", line 84, in recurseTo
    module, added_flag = _recurseTo(
  File "···\.conda\envs\dev\lib\site-packages\nuitka\importing\Recursion.py", line 43, in _recurseTo
    module, is_added = Building.buildModule(
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 1357, in buildModule
    createModuleTree(
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 1093, in createModuleTree
    module_body = buildParseTree(
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 771, in buildParseTree
    result = buildStatementsNode(provider=provider, nodes=body, source_ref=source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 473, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\ReformulationAssignmentStatements.py", line 543, in buildAssignNode
    source = buildNode(provider, node.value, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\ReformulationDictionaryCreation.py", line 94, in buildDictionaryNode
    values=buildNodeTuple(provider, node.values, source_ref),
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 381, in buildNodeTuple
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\ReformulationSequenceCreation.py", line 117, in buildListCreationNode
    elements=buildNodeTuple(provider, node.elts, source_ref),
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 381, in buildNodeTuple
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\ReformulationLambdaExpressions.py", line 114, in buildLambdaNode
    body = buildNode(provider=code_body, node=node.body, source_ref=source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
.........................................................................................................................................
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 598, in buildBinaryOpNode
    left = buildNode(provider, node.left, source_ref)
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\Building.py", line 593, in buildBinaryOpNode
  File "···\.conda\envs\dev\lib\site-packages\nuitka\tree\TreeHelpers.py", line 57, in getKind
    return node.__class__.__name__.rsplit(".", 1)[-1]
RecursionError: maximum recursion depth exceeded while calling a Python object

python -m nuitka --mingw64 --standalone .\test.py

**Comment by vision1v1** [comment]
I had the same problem. My enviroments is

Nuitka==1.5.7
python==3.8.2
CentOS: 7.9.2009

**Comment by kayhayen** [comment]
I have forgotten when, but when I came across this, I enhanced the behaviour of the detection for too complex code. It can happen in the ast parsing, and it can happen in the Nuitka conversion of ast tree to Nuitka tree both. The later was not handled, and first time seen here, for close margins it can happen. I believe that factory should be good already.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made.
