### ISSUE TITLE
SQL qt plugin error on Release & Factory - FATAL: Error, failed to find path /usr/local/opt/libiodbc/lib/libiodbc.2.dylib

### ISSUE THREAD

**Issue by ben-hearn-sb** [Nuitka/Nuitka#2229]
Hello!

We are trying to build our application with Nuitka, the release version for 1.5.7 originally gave us a shiboken error: https://github.com/Nuitka/Nuitka/issues/2209.

We switched to the 1.5.6 build to test it there and we got an SQL driver error related to the qt plugins detailed in this report. 

We switched to factory to test the shiboken error was gone (it was) but the SQL driver error is still present. This leads me to suspect that the shiboken error in the 1.5.7 build triggers before the SQL driver error and that the error is also present in 1.5.7.

**Full traceback:**
```
FATAL: Error, failed to find path /usr/local/opt/libiodbc/lib/libiodbc.2.dylib (resolved DLL to /usr/local/opt/libiodbc/lib/libiodbc.2.dylib) for /Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/PySide6/Qt/plugins/sqldrivers/libqsqlodbc.dylib, please report the bug.
Traceback (most recent call last):
  File "/Users/benhearn/Documents/project/build/nuitka_build.py", line 37, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'nuitka', '--standalone', '--follow-imports', '--enable-plugin=pyside6', '--include-qt-plugins=all', '--output-dir=nuitka_dist', '--macos-create-app-bundle', '--onefile', '--include-module=core', '--include-module=music_tag', '--include-module=tools', '--include-module=ui', '--include-module=utils', '/Users/benhearn/Documents/project/main.py']' returned non-zero exit status 1.
```

**Below is a list of info on the system and versions of modules we are running:**

**Our build module currently:**

```
import subprocess
from pathlib import Path

# Define the entry point of the application
p = Path(__file__)
root_dir = p.parents[1]
entry_point = f"{str(root_dir)}/project/main.py"

# Define the internal modules to include in the build
internal_modules = ["core", "music_tag", "tools", "ui", "utils"]

# Build the application
nuitka_command = [
    "python", "-m", "nuitka",
    "--standalone",
    "--follow-imports",
    #"--remove-output",
    "--enable-plugin=pyside6",
    "--include-qt-plugins=all",
    #"--enable-plugin=numpy",
    "--output-dir=nuitka_dist",
    "--macos-create-app-bundle",
    "--onefile"
]
for module in internal_modules:
    nuitka_command.extend(["--include-module={}".format(module)])

nuitka_command.extend([
    #"--windows-disable-console",
    entry_point,
])

subprocess.check_call(nuitka_command)
```

**Nuitka, python flavor, system etc:**

**_NOTE: Although this report is written against the factory build (which you asked not to do) the issue is still present in 1.5.6 so in theory should also be present in 1.5.7_**

```
1.6rc8
Commercial: None
Python: 3.9.16 (main, Dec  7 2022, 10:15:43) 
Flavor: Homebrew Python
Executable: /Users/benhearn/Documents/project/venv_py39/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

**How did you install Nuitka and Python:**

Installed into a PyCharm initialised virtual environment (I believe it is using the built in venv for this setup):
https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html

Force installed the factory version via the below command:

`pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
`

**Minimum repro example:**

```
from PySide6 import QtSql
from PySide6 import QtCore
from PySide6 import QtGui
from PySide6 import QtWidgets
import sys

class Min(QtWidgets.QDialog):
    def __init__(self):
        QtWidgets.QDialog.__init__(self)
        self.resize(500, 500)
        print('Init of min example finished')

def main():
    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName("Minimum Example")

    window = Min()
    window.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    main()
```

**The specific PyPI names and versions**

```
altgraph==0.17
blessings==1.7
certifi==2022.12.7
cffi==1.15.0
chardet==4.0.0
charset-normalizer==3.0.1
Cython==0.29.27
dmgbuild==1.6.1
ds-store==1.3.1
ftfy==6.0.3
ftransc==7.0.3
helpdev==0.7.1
idna==3.4
joblib==1.2.0
lxml==4.6.5
mac-alias==2.2.2
macholib==1.14
music-tag==0.4.3
mutagen==1.45.1
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
numpy==1.24.3
ordered-set==4.1.0
packaging==21.3
pafy==0.5.5
plumbum==1.7.0
pycparser==2.20
pyinstaller==5.6.2
pyinstaller-hooks-contrib==2022.13
pyparsing==3.0.7
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
python-vlc==3.0.16120
pyuca==1.2
QDarkStyle==3.1
QtPy==2.3.1
requests==2.28.2
scikit-learn==0.24.1
scipy==1.10.1
shiboken2==5.15.2.1
shiboken6==6.5.0
six==1.15.0
sklearn==0.0
SoundFile==0.10.3.post1
sparse-dot-topn==0.2.9
threadpoolctl==3.1.0
timeloop==1.0.2
urllib3==1.26.14
wcwidth==0.2.5
youtube-dl==2021.12.17
zstandard==0.21.0
```

**Our entire build output from Nuitka up until the error with the SQL driver:**

```
/Users/benhearn/Documents/project/venv_py39/bin/python /Users/benhearn/Documents/project/build/nuitka_build.py
Nuitka-Options:INFO: Used command line options: --standalone --follow-imports --enable-plugin=pyside6 --include-qt-plugins=all --output-dir=nuitka_dist --macos-create-app-bundle --onefile --include-module=core --include-module=music_tag --include-module=tools --include-module=ui --include-module=utils /Users/benhearn/Documents/project/main.py
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.6rc8' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: implicit-imports: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise high resolution will not be available and a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback information.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'qml' below 'PySide6/qml'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Running /Users/benhearn/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache /usr/bin/clang -o module.numpy.ma.core.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=x86_64-apple-macos12.0 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_ONEFILE_MODE -D_NUITKA_ONEFILE_TEMP_BOOL -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=152 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -I/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/static_src module.numpy.ma.core.c took 78.90 seconds
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.
Nuitka-Scons:INFO: Running /Users/benhearn/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache /usr/bin/clang -o module.scipy.stats._stats_py.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=x86_64-apple-macos12.0 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_ONEFILE_MODE -D_NUITKA_ONEFILE_TEMP_BOOL -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=152 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -I/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/static_src module.scipy.stats._stats_py.c took 65.20 seconds
Nuitka-Scons:INFO: Running /Users/benhearn/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache /usr/bin/clang -o module.scipy.stats._continuous_distns.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -w -fvisibility=hidden -fvisibility-inlines-hidden --target=x86_64-apple-macos12.0 -O3 -D_XOPEN_SOURCE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_ONEFILE_MODE -D_NUITKA_ONEFILE_TEMP_BOOL -D_NUITKA_CONSTANTS_FROM_MACOS_SECTION -D_NUITKA_FROZEN=152 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -I/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I. -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/include -I/Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/nuitka/build/static_src module.scipy.stats._continuous_distns.c took 135.33 seconds
Nuitka-Scons:INFO: Backend linking program with 960 files (no progress information available).
Nuitka-Scons:INFO: Compiled 960 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 839
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 121
Nuitka-Plugins:INFO: pyside6: Included 1394 data files due to Qt QML datafile.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'all' below 'PySide6/qt-plugins'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from soundfile installation.
FATAL: Error, failed to find path /usr/local/opt/libiodbc/lib/libiodbc.2.dylib (resolved DLL to /usr/local/opt/libiodbc/lib/libiodbc.2.dylib) for /Users/benhearn/Documents/project/venv_py39/lib/python3.9/site-packages/PySide6/Qt/plugins/sqldrivers/libqsqlodbc.dylib, please report the bug.
Traceback (most recent call last):
  File "/Users/benhearn/Documents/project/project/build/nuitka_build.py", line 37, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'nuitka', '--standalone', '--follow-imports', '--enable-plugin=pyside6', '--include-qt-plugins=all', '--output-dir=nuitka_dist', '--macos-create-app-bundle', '--onefile', '--include-module=core', '--include-module=music_tag', '--include-module=tools', '--include-module=ui', '--include-module=utils', '/Users/benhearn/Documents/project/main.py']' returned non-zero exit status 1.
```

**Comment by kayhayen** [comment]
Not sure, I think Nuitka may not know about that global DLL directory there, or how it would. Homebrew packages mixed with a venv might not be a good idea at all.

**Comment by kayhayen** [comment]
You might want to try it with CPython and current factory branch, which has a fix for PySide6, that looks similar, but is actually something different. If you confirm or deny it works there, we can look into this.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by ben-hearn-sb** [comment]
Ok, I will dig into the issue further and comment with my findings

**Comment by kayhayen** [comment]
Deleting for lack of feedback and completeness.
