### ISSUE TITLE
ModuleNotFoundError: No module named 'webview.platforms.qt' from compiled nuitka executable

### ISSUE THREAD

**Issue by NethercraftMC5608** [Nuitka/Nuitka#2231]
I am using pywebview and PyQt5 to display a webpage.
Nuitka info:
```
1.5.7
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Nether\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```
Using modules:
fastapi uvicorn pywebview[qt] pyperclip psutil requests tdqm tkinter
Code:
```
import urllib.request
import webview
class Api:
    def __init__(self):
        self._window = None

    def set_window(self, window):
        self._window = window

    def quit(self):
        window.destroy()

def on_closed():
    urllib.request.urlopen('http://127.0.0.1:36113/quit')
if __name__ == '__main__':
    api = Api()
    window = webview.create_window('test', 'http://127.0.0.1:36113/', width=600, height=500, resizable=False, js_api=api)
    window.events.closed += on_closed
    webview.start(gui='qt')
```
I encountered an error with the executable when compiled with nuitka, here is the parameters that i used to compile:
`python -m nuitka --onefile --follow-imports --include-data-dir=ui=ui --enable-plugin=pyqt5 --enable-plugin=tk-inter frame.py`
 The error message when running executable:
```
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "C:\Users\Nether\AppData\Local\Temp\ONEFIL~1\webview\guilib.py", line 29, in import_qt
ModuleNotFoundError: No module named 'webview.platforms.qt'
Traceback (most recent call last):
  File "C:\Users\Nether\AppData\Local\Temp\ONEFIL~1\frame.py", line 23, in <module>
    webview.start(gui='qt')
  File "C:\Users\Nether\AppData\Local\Temp\ONEFIL~1\webview\__init__.py", line 132, in start
  File "C:\Users\Nether\AppData\Local\Temp\ONEFIL~1\webview\guilib.py", line 102, in initialize
webview.util.WebViewException: You must have pythonnet installed in order to use pywebview.
```
Here's what i get when compiling:
```
Nuitka:WARNING: The Python version '3.11' is only experimentally supported by Nuitka '1.5.7', but an upcoming release
Nuitka:WARNING: will change that. In the mean time use Python version '3.10' instead or newer Nuitka.
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka-Plugins:WARNING: pyqt5: For the obsolete PyQt5 the Nuitka support is incomplete. Threading, callbacks to compiled
Nuitka-Plugins:WARNING: functions, etc. may not be working.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/pyqt5.html
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.7' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pyqt5: Injecting pre-module load code for module 'PyQt5':
Nuitka-Plugins:INFO: pyqt5:     Adding binary folder to runtime 'PATH' environment variable for proper Qt loading.
Nuitka-Plugins:INFO: pyqt5: Injecting post-module load code for module 'PyQt5.QtCore':
Nuitka-Plugins:INFO: pyqt5:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyqt5:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PyQt5', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback information.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'tkinter', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback information.
Nuitka-Plugins:WARNING: pyqt5: Unwanted import of 'tkinter' that is redundant with 'PyQt5' encountered. Use
Nuitka-Plugins:WARNING: '--nofollow-import-to=tkinter' or uninstall it for best compatibility with pure Python
Nuitka-Plugins:WARNING: execution.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 316 files (no progress information available).
Nuitka-Scons:INFO: Compiled 636 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 314
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka-Options:INFO: Included data file 'ui\d.html' due to specified data dir 'ui' on command line.
Nuitka-Options:INFO: Included data file 'ui\settings.html' due to specified data dir 'ui' on command line.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:INFO: tk-inter: Included 835 data files due to Tcl needed for tkinter usage.
Nuitka-Plugins:INFO: data-files: Included data file 'webview\lib\Microsoft.Web.WebView2.LICENSE.md' due to package data directory 'lib' for 'webview'.
Nuitka-Plugins:INFO: pyqt5: Including Qt plugins 'iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,styles' below 'PyQt5\qt-plugins'.
Nuitka-Plugins:INFO: pyqt5: Found 2 files DLLs from 'OpenSSL' PyQt5 installation.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from clr_loader.ffi installation.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from pythonnet installation.
Nuitka-Plugins:INFO: dll-files: Found 4 files DLLs from webview installation.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: gcc (gcc).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available).
Nuitka-Scons:INFO: Compiled 2 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (26.77%) size 113821266 to 30471350.
Nuitka-Onefile:INFO: Keeping onefile build directory 'frame.onefile-build'.
Nuitka:INFO: Keeping dist folder 'frame.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'frame.build'.
Nuitka:INFO: Successfully created 'frame.exe'.
```

**Help would be greatly appreciated, Thanks!**

**Comment by kayhayen** [comment]
Does `--include-module=webview.platforms.qt` help this, I am almost assuming that is a kind of implicit dependency missing right there. The pywebview plugin combined with a qt binding plugin should probably add it.

And it does so, but not on Windows.

```
        # Make sure webview platforms are included as needed.
        if module_name.isBelowNamespace("webview.platforms"):
            if isWin32Windows():
                result = module_name in (
                    "webview.platforms.winforms",
                    "webview.platforms.edgechromium",
                    "webview.platforms.edgehtml",
                    "webview.platforms.mshtml",
                    "webview.platforms.cef",
                )
                reason = "Platforms package of webview used on '%s'." % getOS()
            elif isMacOS():
                result = module_name == "webview.platforms.cocoa"
                reason = "Platforms package of webview used on '%s'." % getOS()
            elif getActiveQtPlugin() is not None:
                result = module_name = "webview.platforms.qt"
                reason = (
                    "Platforms package of webview used due to '%s'."
                    % getActiveQtPlugin()
                )
            else:
                result = module_name = "webview.platforms.gtk"
                reason = (
                    "Platforms package of webview used on '%s' without Qt plugin enabled."
                    % getOS()
                )
```

BTW: Enabling the tk-inter and pyqt5 plugin means you are confused, using more than one is surprising, but not a problem by itself, the PyQt5 plugin just prevents tkinter from being included anyway.

Reordering these branches will work too and might be a sane choice. The above code replicates platform defaults I think, but selecting Qt should be doable I guess.

I believe the pythonnet message is probably just bad bug hiding of pywebview making guesses that are not warranted unless a pythonnet update is no longer working with Nuitka.

**Comment by NethercraftMC5608** [comment]
**I decided to use pywebview with GTK and works perfectly with the built nuitka executable.** 👍
And compiled with only --enable-plugin=tk-inter
```
import urllib.request
import webview
class Api:
    def __init__(self):
        self._window = None

    def set_window(self, window):
        self._window = window

    def quit(self):
        window.destroy()

def on_closed():
    urllib.request.urlopen('http://127.0.0.1:36113/quit')
if __name__ == '__main__':
    api = Api()
    window = webview.create_window('test', 'http://127.0.0.1:36113/', width=600, height=500, resizable=False, js_api=api)
    window.events.closed += on_closed
    webview.start(gui='gtk')
```

**Comment by kayhayen** [comment]
The PyQt5 support is also incomplete unlike PySide6 which is perfect, as is GTK for all I know. I am however keeping this open, to checkout if we can give some sort of warning to the user. If it's really Qt5 only, and we are speaking of Windows, there are indeed better options. Curious as to why you went with GTK and not the platform default, which I think is edge based stuff. With no argument for `gui` I guess, it would just work?

**Comment by NethercraftMC5608** [comment]
When gtk is not found, it defaults to mshtml on Windows, as far as I know. 
When I use an older version of Windows 10 (2004), I get the following:
[pywebview] MSHTML is no longer supported. Details on how to use Edge Chromium can be found at https://pywebview.flowrl.com/guide/renderer.html#web-engine.


I could have used the default settings, as you suggested,  in the order: edgechromium, mshtml.
But i dont want to run into any rendering issues when using different web engines, so might as well stick with one.

**Comment by kayhayen** [comment]
Yes, fair point. Making things work on older systems is of course an art by itself. Recognizing the argument given is not yet practical, so this will remain the packagers obligation. I wonder if there is an environment variable, that I forgot to check and persist to runtime. Can you look that up? Because then, it could be done by forcing its value to the compile time value, avoiding unnecessary dependencies.

**Comment by kayhayen** [comment]
Any feedback on my last question?

**Comment by kayhayen** [comment]
Closing for lack of feedback
