### ISSUE TITLE
Transformers raises "no sympy" after compiling

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2261]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed
Mentioned here 
https://github.com/Nuitka/Nuitka/issues/2228

Tried to build with torch and transformers it seems to be missing sympy?

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

1.6
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\aiengine.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe (cl 14.3).

* How did you install Nuitka and Python

using a virtual env then using pip3 

* The specific PyPI names and versions

anyio==3.7.0
backoff==2.2.1
certifi==2022.12.7
click==8.1.3
clickhouse-connect==0.5.25
colorama==0.4.6
coloredlogs==15.0.1
duckdb==0.8.0
exceptiongroup==1.1.1
fastapi==0.95.2
filelock==3.9.0
flatbuffers==23.5.26
fsspec==2023.5.0
h11==0.14.0
hnswlib==0.7.0
httptools==0.5.0
huggingface-hub==0.14.1
humanfriendly==10.0
idna==3.4
Jinja2==3.1.2
lz4==4.3.2
MarkupSafe==2.1.2
monotonic==1.6
mpmath==1.2.1
networkx==3.0
Nuitka==1.6
numpy==1.24.1
onnxruntime==1.15.0
ordered-set==4.1.0
overrides==7.3.1
packaging==23.1
pandas==2.0.2
Pillow==9.3.0
posthog==3.0.1
protobuf==4.23.2
pydantic==1.10.8
pyreadline3==3.4.1
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.28.1
safetensors==0.3.1
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
sympy==1.11.1
tokenizers==0.13.3
torch==2.0.0+cu117
torchaudio==2.0.1+cu117
torchvision==0.15.1+cu117
tqdm==4.65.0
transformers==4.29.2
typing_extensions==4.6.2
tzdata==2023.3
urllib3==1.26.13
uvicorn==0.22.0
watchfiles==0.19.0
websockets==11.0.3
zstandard==0.21.0

Heres the output after compiling with hugging face and torch.

No sympy found
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\__init__.py", line 1465, in <module torch>       
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_meta_registrations.py", line 7, in <module torch._meta_registrations>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_decomp\__init__.py", line 169, in <module torch._decomp>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_decomp\decompositions.py", line 10, in <module torch._decomp.decompositions>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_prims\__init__.py", line 33, in <module torch._prims>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_subclasses\__init__.py", line 3, in <module torch._subclasses>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_subclasses\fake_tensor.py", line 13, in <module 
torch._subclasses.fake_tensor>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_guards.py", line 78, in <module torch._guards>  
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_guards.py", line 79, in ShapeGuard
NameError: name 'sympy' is not defined

Command to execute
```
python -m nuitka main.py --standalone --follow-imports --show-progress --show-scons --show-modules --include-package=setuptools --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-dask-mode=nofollow --noinclude-numba-mode=nofollow --lto=no  --standalone
```

Code used
```

from transformers import AutoTokenizer
import time
import torch
import torch.nn as nn

DEV = torch.device('cuda:0')
model_name = "EleutherAI/gpt-j-6b"

tokenizer = AutoTokenizer.from_pretrained(model_name)
input_ids = tokenizer.encode("Hello world this is a test of the context and how it should work.", return_tensors="pt").to(DEV)
print(input_ids)
```

**Comment by ArEnSc** [comment]
Were almost there! =D only maybe one more stop haha

**Comment by kayhayen** [comment]
How cool is this:

**Comment by kayhayen** [comment]
```
try:
    import sympy  # type: ignore[import]
except ImportError:
    log.warning("No sympy found")
```

I would assume this to be bug hiding of some sorts. I am adding a raise to see why it wouldn't import if it does at all.

**Comment by kayhayen** [comment]
@ArEnSc your reduced case just worked fine for me, if you can reproduce that, and but have normal python work in the same environment, you need to send the file output by `--report` option. Right now I don't believe the issue exist.

**Comment by ArEnSc** [comment]
```
No sympy found
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\transformers\utils\import_utils.py", line 1172, in _get_module
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\transformers\models\gptj\modeling_gptj.py", line 20, in <module transformers.models.gptj.modeling_gptj>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\__init__.py", line 1465, in <module torch>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_meta_registrations.py", line 7, in <module torch._meta_registrations>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_decomp\__init__.py", line 169, in <module torch._decomp>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_decomp\decompositions.py", line 10, in <module torch._decomp.decompositions>     
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_prims\__init__.py", line 33, in <module torch._prims>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_subclasses\__init__.py", line 3, in <module torch._subclasses>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_subclasses\fake_tensor.py", line 13, in <module torch._subclasses.fake_tensor>   
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_guards.py", line 78, in <module torch._guards>
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\torch\_guards.py", line 79, in ShapeGuard
NameError: name 'sympy' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\transformers\utils\import_utils.py", line 1163, in __getattr__
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\transformers\utils\import_utils.py", line 1162, in __getattr__
  File "C:\Users\Tensor\Desktop\aiengine\test\MAIN~1.DIS\transformers\utils\import_utils.py", line 1177, in _get_module
RuntimeError: Failed to import transformers.models.gptj.modeling_gptj because of the following error (look up to see its traceback):
name 'sympy' is not defined
```

**Comment by ArEnSc** [comment]
@kayhayen 
here is my build command as well
```
python -m nuitka main.py --follow-imports --show-progress --show-scons --show-modules --include-package=setuptools --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-dask-mode=nofollow --noinclude-numba-mode=nofollow --lto=no  --standalone --report="report"  
```

**Comment by kayhayen** [comment]
@ArEnSc 

I can confirm that:

```
  <command_line>
    <option value="main.py" />
    <option value="--follow-imports" />
    <option value="--show-progress" />
    <option value="--show-scons" />
    <option value="--show-modules" />
    <option value="--include-package=setuptools" />
    <option value="--noinclude-pytest-mode=nofollow" />
    <option value="--noinclude-unittest-mode=nofollow" />
    <option value="--noinclude-dask-mode=nofollow" />
    <option value="--noinclude-numba-mode=nofollow" />
    <option value="--lto=no" />
    <option value="--standalone" />
    <option value="--report=report" />
  </command_line>
```

Reports strive to make sure I do not need ask questions anymore.

**Comment by kayhayen** [comment]
So, what's annoying to me, is that I see this:

```
  <module name="torch._guards" kind="CompiledPythonModule" reason="Instructed by user to follow to all non-standard library modules.">
    <optimization-time pass="1" time="0.12" />
    <optimization-time pass="2" time="0.02" />
    <module_usages>
      <module_usage name="dataclasses" finding="absolute" line="1" />
      <module_usage name="enum" finding="absolute" line="2" />
      <module_usage name="logging" finding="absolute" line="3" />
      <module_usage name="weakref" finding="absolute" line="4" />
      <module_usage name="abc" finding="absolute" line="5" />
      <module_usage name="contextlib" finding="absolute" line="6" />
      <module_usage name="typing" finding="absolute" line="7" />
      <module_usage name="sympy" finding="absolute" line="14" />
    </module_usages>
  </module>
```

Also we have this:

```
    <distribution name="sympy" version="1.11.1" />
```

And this:

```
  <module name="sympy" kind="CompiledPythonPackage" reason="Instructed by user to follow to all non-standard library modules.">
    <optimization-time pass="1" time="2.32" />
    <optimization-time pass="2" time="0.51" />
    <distributions>
      <distribution name="sympy" />
    </distributions>
```

So we can confirm it works from the packaging side, `sympy` is included as a module. The `NameError`  must be due to their bug hiding, in `torch._guards`. If for whatever reason sympy fails to load, we won't see it, outside of the log.

**Comment by kayhayen** [comment]
Please find this code in `torch/_guards.py` in your torch installation:

```
try:
    import sympy  # type: ignore[import]
except ImportError:
    log.warning("No sympy found")
```

Change it to 

try:
    import sympy  # type: ignore[import]
except ImportError:
    log.warning("No sympy found")
    raise
```

And then report the exception it will give you. Since it doesn't happen for me, I need you there.

**Comment by ArEnSc** [comment]
> Please find this code in `torch/_guards.py` in your torch installation:
> 
> ```
> try:
>     import sympy  # type: ignore[import]
> except ImportError:
>     log.warning("No sympy found")
> ```
> 
> Change it to
> 
> try: import sympy # type: ignore[import] except ImportError: log.warning("No sympy found") raise
> 
> ```
> 
> And then report the exception it will give you. Since it doesn't happen for me, I need you there.
> ```

ok ill do that!

**Comment by ArEnSc** [comment]
@kayhayen gonna try without the noinclude pytest and noinclude unittest mode
```Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\main.py", line 4, in <module>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\__init__.py", line 1465, in <module torch>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_meta_registrations.py", line 7, in <module torch._meta_registrations>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_decomp\__init__.py", line 169, in <module torch._decomp>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_decomp\decompositions.py", line 10, in <module torch._decomp.decompositions>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_prims\__init__.py", line 33, in <module torch._prims>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_subclasses\__init__.py", line 3, in <module torch._subclasses>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_subclasses\fake_tensor.py", line 13, in <module torch._subclasses.fake_tensor>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\torch\_guards.py", line 14, in <module torch._guards>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\__init__.py", line 57, in <module sympy>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\core\__init__.py", line 8, in <module sympy.core>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\core\expr.py", line 6, in <module sympy.core.expr>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\core\evalf.py", line 28, in <module sympy.core.evalf>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\utilities\__init__.py", line 18, in <module sympy.utilities>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\sympy\utilities\runtests.py", line 28, in <module sympy.utilities.runtests>
ModuleNotFoundError: No module named 'doctest'```
I get this instead I am guessing this has to do with the fact that I do noinclude the pytests ? and noinclude unittests?

**Comment by ArEnSc** [comment]
So I removed it and it did work thanks! @kayhayen

**Comment by kayhayen** [comment]
Since doctest will not work without unittest, it's excluded too. I recall making anti-bloat against sympy recently, specifically `sympy.testing` but I guess, this one might be worth too. I usually have to leave it enabled due to `unittest.mock` having legit uses in many places. On day we might have something that will be able to handle that and not allow the others. And we will need an `ImportError` or rather `ModuleNotFoundError` that indicates *why* a used module was not included.

**Comment by kayhayen** [comment]
It doesn't happen to me though, so this remains unsolved. My bad for looking at issues which do not remove the noinclude options in their reports.

**Comment by xingtianqz** [comment]
在导入sympy时，缺少对应的模块或者包，这些包大部分是python自带的，没有输出报错信息，把python环境下的lib自带包复制到打包后的文件夹下，基本就可以运行，good luck to you

**Comment by kayhayen** [comment]
Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
