### ISSUE TITLE
ModuleNotFoundError: 'fractions'

### ISSUE THREAD

**Issue by Chainfire** [Nuitka/Nuitka#2266]
`python -m nuitka --version`:

```
1.6
Commercial: None
Python: 3.9.12 (main, Apr 18 2022, 22:40:46)
Flavor: Debian Python
Executable: /home/jorrit/nuitka-test/env/bin/python
OS: Linux
Arch: x86_64
Distribution: Linuxmint (based on Ubuntu) 20.3
Version C compiler: /usr/bin/gcc (gcc).
```

Installation:

```
virtualenv -p python3.9 env
. env/bin/activate
pip3 install nuitka==1.6.0
```

`python -m pip freeze`:

```
Nuitka==1.6
ordered-set==4.1.0
zstandard==0.21.0
```

Code (`test.py`):

```
from statistics import stdev, mean

data = [1, 2, 3, 4, 5]
mn = mean(data)
sd = stdev(data, mn)
print(mn, sd)
```

Build:

```
python -m nuitka --standalone test.py

Nuitka-Options:INFO: Used command line options: --standalone test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist/test.bin'.
```

Execution:

```
./test.dist/test.bin

Traceback (most recent call last):
  File "/home/jorrit/nuitka-test/test.dist/test.py", line 1, in <module>
  File "/home/jorrit/nuitka-test/test.dist/statistics.py", line 107, in <module>
ModuleNotFoundError: No module named 'fractions'
```

The example works in `1.5.8` but throws this error on `1.6.0`. It is fixed easily enough by adding `import fractions` to `test.py`. But as these are standard library modules and it worked fine previous release, I thought I should mention it.

**Comment by kayhayen** [comment]
That's due to size optimizations for the standard library, but sometimes this reveals hidden dependencies like this one. We are gradually shifting to making these proper compilations. Adding `statistics` to also not being automatically included, but only if needed, means it's properly analysed, and pulling `fractions` in.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by Chainfire** [comment]
Confirmed working on `factory` branch:

```
virtualenv -p python3.9 env
. env/bin/activate
pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
```

```
python -m nuitka --standalone test.py

Nuitka-Options:INFO: Used command line options: --standalone test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7rc1' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 7 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 4
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist/test.bin'.
```

```
test.dist/test.bin

3 1.5811388300841898
```

Thank you for all you do.

**Comment by Groostav** [comment]
I'm sorry, first time using nuitka and I'm sure im missing something obvious:

```
import torch

def main():
    t_test = torch.tensor([1.0, 1.0, 1.0], dtype=torch.float32)
    print("hi nuitka!")

if __name__ == "__main__":
    main()

```

python output: 
```
hi nuitka!
```

`nuitka src --standalone && src.dist/src.exe` output:
```
Traceback (most recent call last):
  File "C:\Users\geoff\Code\HELLOP~1\SRC~1.DIS\__main__.py", line 6, in <module>
ModuleNotFoundError: No module named 'torch'
```

ptyhon 3.11, nutika 1.6.0 (and 1.5.8)

I'm missing something obvious...

**Comment by kayhayen** [comment]
@Groostav posting below other issues is a surefire way to get ignored by me at least, make a new issue with template filled out if you have an issue.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.2 that I just made.
