### ISSUE TITLE
TypeError: Method name overrides method from <class 'chromadb.errors.ChromaError'> but does not have @override decorator

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2272]
Nuitka 1.6
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\aiengine.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe (cl 14.3).

How did you install Nuitka and Python?
using a virtual env then using pip3

```
absl-py==0.13.0
aiohttp==3.7.4.post0
alembic==1.9.2
altgraph==0.17
anyio==3.7.0
appdirs==1.4.4
asttokens==2.0.5
astunparse==1.6.3
async-timeout==3.0.1
attrs==21.2.0
audioread==2.1.9
autopep8==1.5.7
azure-ai-formrecognizer==3.2.0
azure-common==1.1.28
azure-core==1.26.2
backcall==0.2.0
backoff==1.11.1
backports.zoneinfo==0.2.1
beautifulsoup4==4.10.0
boto3==1.17.78
botocore==1.20.78
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.6
chardet==4.0.0
charset-normalizer==3.0.1
chromadb==0.3.25
click==8.0.1
clickhouse-connect==0.5.25
cloudpickle==2.2.1
colorama==0.4.4
coloredlogs==15.0.1
contourpy==1.0.7
cycler==0.11.0
databricks-cli==0.17.4
debugpy==1.6.0
decorator==5.0.9
deepspeech==0.9.3
dill==0.3.6
distlib==0.3.1
docker==6.0.1
docopt==0.6.2
duckdb==0.8.0
elasticsearch==7.17.8
entrypoints==0.4
exceptiongroup==1.1.1
executing==0.8.3
farm-haystack==1.12.2
fastapi==0.95.2
fastapi-utils==0.2.1
filelock==3.0.12
Flask==2.2.2
flatbuffers==2.0
fonttools==4.38.0
future==0.18.2
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.30
google-api-core==1.25.0
google-auth==1.24.0
google-auth-oauthlib==0.4.4
google-cloud-speech==2.0.1
google-pasta==0.2.0
googleapis-common-protos==1.52.0
greenlet==2.0.1
grpcio==1.34.1
h11==0.12.0
h2==4.0.0
h5py==3.1.0
hnswlib==0.7.0
hpack==4.0.0
httptools==0.5.0
huggingface-hub==0.11.1
humanfriendly==10.0
Hypercorn==0.11.1
hyperframe==6.0.0
idna==2.10
importlib-metadata==5.2.0
importlib-resources==5.10.2
inflect==5.6.0
install==1.3.4
ipykernel==6.13.0
ipython==8.2.0
isodate==0.6.1
itsdangerous==2.1.2
jarowinkler==1.2.3
jedi==0.18.1
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.2.0
Js2Py==0.71
jsonschema==4.17.3
jupyter-client==7.2.2
jupyter-core==4.10.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
keyboard==0.13.5
kiwisolver==1.4.4
langdetect==1.0.9
libcst==0.3.16
librosa==0.8.1
llvmlite==0.36.0
log-symbols==0.0.14
loguru==0.5.3
lxml==4.9.2
lz4==4.3.2
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.3
mlflow==2.1.1
mmh3==3.0.0
monotonic==1.6
more-itertools==9.0.0
mpmath==1.3.0
msrest==0.7.1
multidict==5.1.0
mypy-extensions==0.4.3
nanopq==0.1.10
nest-asyncio==1.5.5
networkx==3.0
nltk==3.8.1
Nuitka==1.6
num2words==0.5.12
numba==0.53.1
numpy==1.22.4
oauthlib==3.1.1
onnxruntime==1.15.0
onnxruntime-gpu==1.11.1
opt-einsum==3.3.0
ordered-set==4.1.0
overrides==7.3.1
packaging==21.0
pandas==1.5.3
parso==0.8.3
pdoc3==0.9.2
pedalboard==0.3.8
pefile==2021.5.24
pickleshare==0.7.5
Pillow==9.2.0
pipwin==0.5.1
pkgutil_resolve_name==1.3.10
pooch==1.4.0
posthog==3.0.1
priority==1.3.0
prompt-toolkit==3.0.29
proto-plus==1.13.0
protobuf==4.21.1
psutil==5.9.0
pure-eval==0.2.2
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio @ file:///C:/Users/Tensor/pipwin/PyAudio-0.2.11-cp38-cp38-win_amd64.whl
pybind11==2.9.2
pycodestyle==2.7.0
pycparser==2.20
pydantic==1.9.1
pydub==0.25.1
Pygments==2.11.2
pyinstaller==4.4
pyinstaller-hooks-contrib==2021.1
pyjsparser==2.7.1
PyJWT==2.6.0
pyparsing==2.4.7
PyPrind==2.11.3
pyreadline3==3.4.1
pyrsistent==0.19.3
PySide2==5.15.2.1
pySmartDL==1.3.4
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
pytz==2020.5
pytz-deprecation-shim==0.1.0.post0
pywin32==305
pywin32-ctypes==0.2.0
PyYAML==5.4.1
pyzmq==22.3.0
QtPy==2.3.0
quantulum3==0.8.1
querystring-parser==1.2.4
rank-bm25==0.2.2
rapidfuzz==2.7.0
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.0
resampy==0.2.2
rii==0.2.8
rsa==4.7
Rx==3.2.0
ryven==3.1.1
ryvencore==0.3.1.2
ryvencore-qt==0.3.1.4
s3transfer==0.4.2
sacremoses==0.0.45
scikit-learn==1.2.1
scipy==1.8.1
sentence-transformers==2.2.2
sentencepiece==0.1.97
seqeval==1.2.2
shap==0.41.0
shiboken2==5.15.2.1
six==1.15.0
slicer==0.0.7
smmap==5.0.0
sniffio==1.3.0
SoundFile==0.10.3.post1
soupsieve==2.3.1
spinners==0.0.24
SQLAlchemy==1.4.46
sqlparse==0.4.3
stack-data==0.2.0
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
tensorflow-gpu==2.5.0
tensorflow-hub==0.12.0
tensorflow-text==2.5.0
termcolor==1.1.0
textdistance==4.5.0
threadpoolctl==2.2.0
tika==2.6.0
tinyaes==1.0.1
tinydb==4.7.0
tokenizers==0.13.2
toml==0.10.2
torch==1.13.1
torchaudio==0.13.1+cu117
torchvision==0.14.1
tornado==6.1
tqdm==4.65.0
traitlets==5.1.1
transformers==4.25.1
twitchAPI==2.3.2
typing-inspect==0.6.0
typing_extensions==4.6.2
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.2
uvicorn==0.22.0
virtualenv==20.4.6
waiting==1.4.1
waitress==2.1.2
watchfiles==0.19.0
watchgod==0.6
wcwidth==0.2.5
webrtcvad==2.0.10
websocket-client==1.1.0
websockets==11.0.3
Werkzeug==2.2.2
win32-setctime==1.0.3
wrapt==1.12.1
wsproto==1.0.0
yarl==1.6.3
zipp==3.11.0
zstandard==0.21.0
```
Sample Code

pip3 install chromadb
```
import chromadb
chroma_client = chromadb.Client()
collection = chroma_client.create_collection(name="my_collection")

collection.add(
    documents=["go up stairs","go to bed"],
    metadatas=[{"source": "my_source"}, {"source": "my_source"}],
    ids=["id1", "id2"]
)

results = collection.query(
    query_texts=["go to sleep"],
    n_results=2
)
print(results)
```

**Comment by ArEnSc** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\mainchromadb.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\__init__.py", line 1, in <module chromadb>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\config.py", line 6, in <module chromadb.config>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\db\__init__.py", line 5, in <module chromadb.db>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\api\__init__.py", line 5, in <module chromadb.api>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\api\models\Collection.py", line 5, in <module chromadb.api.models.Collection>      
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\api\types.py", line 3, in <module chromadb.api.types>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\chromadb\errors.py", line 21, in <module chromadb.errors>
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\overrides\enforce.py", line 18, in __new__
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAINCH~1.DIS\overrides\enforce.py", line 33, in _check_if_overrides_without_overrides_decorator
TypeError: Method name overrides method from <class 'chromadb.errors.ChromaError'> but does not have @override decorator
```

**Comment by ArEnSc** [comment]
@kayhayen  you mentioned it was a incompatiblity problem

**Comment by kayhayen** [comment]
Well, we added support for some form of older overrides package, and the one from stdlib or coming there, I don't know, was good., but apparently not all of them is working. We do this:

```
- module-name: 'overrides.overrides'
  anti-bloat:
    - description: 'disable overrides function checking'
      change_function:
        '_overrides': "'(lambda method, *args, **kwargs: method)'"
```

I think the original one insisted on bytecode for no good reason. I think we can try and see where this comes from and disable it as well. These checks only harm performance, which for deployment/acceleration is not wanted. It's going through another decorator to enable it probably.

**Comment by ArEnSc** [comment]
@kayhayen is there anything I can do to get past this error? is there a flag?

**Comment by kayhayen** [comment]
So, what I found, is that it uses `EnforceOverridesMeta`  and not only `overrides` through this code, `from overrides import EnforceOverrides, override`

That is a separate mechanism, by which class hierarchies can give the error seen, if the disabled decorator didn't take effect. Unfortunately, in terms of a minimal reproducer, this is kind of worst case, also because the anti-bloat for torch 2.x is not yet fully restored, with it using `setuptools` to pull in too much stuff still. I guess, though, my next stop there has to be the `unittest.mock` kind of false `unittest` usage. But surely, torch2 could be more tame once I get to that.

I am trying to devise an anti-bloat measure of `overrides.enforce`.  What I came up with this is this:

```
- module-name: 'overrides.enforce'
  anti-bloat:
    - description: 'disable overrides function checking'
      module_code: |
        from abc import ABCMeta
        class EnforceOverridesMeta(ABCMeta):
          pass
        class EnforceOverrides(metaclass=EnforceOverridesMeta):
          pass
```

For testing it is going to take a while, but I don't see why it wouldn't help if it's proper syntax.

**Comment by ArEnSc** [comment]
> --skip-my-error

haha oh you are being facetious haha sorry half awake here =)

**Comment by kayhayen** [comment]
You can try what I put above as user yaml though, like I do right now. If you find the option in help to do it. :)

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.3 that I just made.
