### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'convert' with open_clip

### ISSUE THREAD

**Issue by JanWerder** [Nuitka/Nuitka#2278]
Hello,
I'm getting the following problem, when I run the command ```python -m nuitka --follow-imports --standalone .\app-demo.py``` on my project.

```
Loading model
INFO:root:Loaded coca_ViT-L-14 model config.
INFO:root:Loading pretrained coca_ViT-L-14 weights (mscoco_finetuned_laion2B-s13B-b90k).
C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
Traceback (most recent call last):
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\app-demo.py", line 20, in <module>
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\torchvision\transforms\transforms.py", line 95, in __call__
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\open_clip\transform.py", line 53, in _convert_to_rgb
    return image.convert('RGB')
AttributeError: 'Tensor' object has no attribute 'convert'
```

So the actual program launches, but crashes almost instantly because of a missing attribute.
The error above is the second error, I got. First I got this:

```
Traceback (most recent call last):
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\app-demo.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\open_clip\__init__.py", line 3, in <module open_clip>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\open_clip\factory.py", line 20, in <module open_clip.factory>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\open_clip\tokenizer.py", line 153, in <module open_clip.tokenizer>
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\open_clip\tokenizer.py", line 76, in __init__
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\gzip.py", line 58, in open
  File "C:\Users\janwe\dev\SUPERS~2\TAURI-~1\SRC-TA~1\clip\APP-DE~1.DIS\gzip.py", line 174, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\janwe\\dev\\SUPERS~2\\TAURI-~1\\SRC-TA~1\\clip\\APP-DE~1.DIS\\open_clip\\bpe_simple_vocab_16e6.txt.gz'
```

So the open_clip module is missing bpe_simple_vocab_16e6.txt.gz file in the open_clip subfolder. I solved this by copying the module folder from my site-packages folder over to the dist directory. This seemed odd to me. First it's unlikely that I have to do that and second I wonder, why the folder wasn't copied even though it's in my import statement in my app-demo.py.

Here's a minmal example with which I can reproduce the issue:

```
import logging
import sys
import time
import torch
from PIL import Image
import open_clip

print("Loading model")

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

model, _, transform = open_clip.create_model_and_transforms(
    model_name="coca_ViT-L-14", pretrained="mscoco_finetuned_laion2B-s13B-b90k"
)

with torch.no_grad(), torch.cuda.amp.autocast():
    start = time.time() 
    # Generate a random image for performance measurement
    im = torch.randn(1, 3, 224, 224)
    im = transform(im).unsqueeze(0)
    generated = model.generate(im)
    end = time.time()
    performanceSample = end - start
```

<details>

<summary>Compile log</summary>

```
Nuitka-Options:INFO: Used command line options: --follow-imports --standalone .\app-demo.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.1' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' in 'torch._dynamo.config_utils' (at
Nuitka-Plugins:WARNING: 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_dynamo\config_utils.py:7')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: delvewheel: Detected usage of 'delvewheel' version '1.3.1' in module 'scipy'.
Nuitka-Plugins:INFO: implicit-imports: Injecting pre-module load code for module 'torch.jit._state':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka-Inclusion:INFO: Cannot find distribution 'jax' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:107', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'flax' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:108', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'datasets' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:120', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'datasets' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:121', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'detectron2' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:130', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'faiss' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:138', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'faiss-cpu' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:142', expect potential run time problem, unless this is unused code.Nuitka-Inclusion:INFO: Cannot find distribution 'coloredlogs' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:158', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'tf2onnx' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:174', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'onnx' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:182', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'pytorch_quantization' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:190', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'soundfile' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:198', expect potential run time problem, unless this is unused code.Nuitka-Inclusion:INFO: Cannot find distribution 'tensorflow_probability' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:206', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'natten' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:222', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'phonemizer' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:238', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'pyctcdecode' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:246', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'librosa' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:254', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'oneccl_bind_pt' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:265', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'decord' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:272', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'jieba' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:279', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'intel_extension_for_pytorch' at 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py:532', expect potential run time problem, unless this is unused code.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'doctest' in 'sympy.testing.runtests' (at
Nuitka-Plugins:WARNING: 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\sympy\testing\runtests.py:26')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:8')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Users\janwe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:24')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 3947 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 3947 C files using clcache with 3945 cache hits and 2 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch\bin\nvfuser_tests.exe' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included data file 'torch\bin\protoc.exe' due to package data directory 'bin' for 'torch'.
Nuitka-Plugins:INFO: data-files: Included 8105 data files due to package data directory 'include' for 'torch'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from numpy installation.
Nuitka-Plugins:INFO: dll-files: Found 36 files DLLs from torch installation.
Nuitka-Plugins:INFO: dll-files: Found 3 files DLLs from torchvision installation.
Nuitka:INFO: Keeping build directory 'app-demo.build'.
Nuitka:INFO: Successfully created 'app-demo.dist\app-demo.exe'.
```

</details>

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.6.1
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\janwe\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

Installed from pip

* The specific PyPI names and versions

  > python -m pip freeze

<details>

<summary>Output</summary>

```
absl-py==1.4.0
altgraph==0.17.3
asttokens==2.0.8
astunparse==1.6.3
backcall==0.2.0
bark==0.1.0
boto3==1.26.118
botocore==1.29.118
cachetools==5.3.1
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
debugpy==1.6.3
decorator==5.1.1
einops==0.6.1
encodec==0.1.1
entrypoints==0.4
executing==1.1.1
filelock==3.12.0
Flask==2.2.3
flatbuffers==23.5.26
ftfy==6.1.1
funcy==2.0
gast==0.4.0
google-auth==2.19.1
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.54.2
h5py==3.8.0
huggingface-hub==0.13.4
idna==3.4
ipykernel==6.16.0
itsdangerous==2.1.2
jax==0.4.12
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
jupyter-core==4.11.1
jupyter_client==7.3.5
keras==2.12.0
libclang==16.0.0
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib-inline==0.1.6
ml-dtypes==0.2.0
mpmath==1.3.0
nest-asyncio==1.5.6
netaddr==0.8.0
networkx==3.1
Nuitka==1.6.1
numpy==1.23.5
oauthlib==3.2.2
open-clip-torch==2.17.1
opt-einsum==3.3.0
ordered-set==4.1.0
packaging==23.1
parso==0.8.3
pefile==2023.2.7
pickleshare==0.7.5
Pillow==9.5.0
prompt-toolkit==3.0.31
protobuf==3.20.3
psutil==5.9.2
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyinstaller==5.10.1
pyinstaller-hooks-contrib==2023.2
python-dateutil==2.8.2
pywin32==304
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==24.0.1
regex==2023.3.23
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
s3transfer==0.6.0
scipy==1.10.1
sentencepiece==0.1.98
six==1.16.0
stack-data==0.5.1
suno-bark @ file:///C:/Users/janwe/dev/bark
sympy==1.11.1
tensorboard==2.12.3
tensorboard-data-server==0.7.0
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-intel==2.12.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.3.0
timm==0.6.13
tokenizers==0.13.3
torch==2.0.0+cu117
torchaudio==2.0.1
torchvision==0.15.1+cu117
tornado==6.2
tqdm==4.65.0
traitlets==5.4.0
transformers==4.28.1
typing_extensions==4.5.0
urllib3==1.26.15
waitress==2.1.2
wcwidth==0.2.5
WebOb==1.8.7
Werkzeug==2.2.3
wrapt==1.14.1
zstandard==0.21.0
```

</details>

**Comment by kayhayen** [comment]
This report is a bit messed up, I think you are saying it needs a data file configuration. And then, if you manually workaround that, there is an error as well. I like to deal with first errors first.

**Comment by JanWerder** [comment]
Yes, sure, that would make sense. I just wanted to document the steps I tried to resolve the issue.

**Comment by kayhayen** [comment]
I really would have preferred if you had read the manual to check out, how to add data files, but you can retry once I added the config, so it's done by default.
