### ISSUE TITLE
PySide6 QtWebEngineWidgets related: No module named 'logging'

### ISSUE THREAD

**Issue by Canvis-Me** [Nuitka/Nuitka#2279]
It did work at a commit, however, it cannot run the program due to another error.

  > python -m nuitka --version

  ```
1.6.2
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\CanvisMe\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```

  > python -m pip freeze

```
anyio==3.7.0
anytree==2.8.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-lru==2.0.2
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
docstring-to-markdown==0.12
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.17.1
filelock==3.9.0
fonttools==4.39.4
fqdn==1.5.1
fsspec==2023.5.0
graphviz==0.20.1
huggingface-hub==0.15.1
idna==3.4
ipykernel==6.23.1
ipython==8.14.0
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.1
jupyterlab-pygments==0.2.2
jupyterlab_server==2.22.1
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mistune==2.0.5
mpmath==1.2.1
nbclient==0.8.0
nbconvert==7.4.0
nbformat==5.9.0
nest-asyncio==1.5.6
networkx==3.0
nodejs-bin==18.4.0a4
notebook_shim==0.2.3
Nuitka==1.6.2
numpy==1.24.3
ordered-set==4.1.0
overrides==7.3.1
packaging==23.1
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.1
pluggy==1.0.0
polars==0.18.0
prometheus-client==0.17.0
prompt-toolkit==3.0.38
psutil==5.9.5
pure-eval==0.2.2
pycparser==2.21
Pygments==2.15.1
pyparsing==3.0.9
pyrsistent==0.19.3
PySide6==6.5.1.1
PySide6-Addons==6.5.1.1
PySide6-Essentials==6.5.1.1
python-dateutil==2.8.2
python-json-logger==2.0.7
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.7.3
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.1.0
regex==2023.6.3
requests==2.28.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
Send2Trash==1.8.2
shiboken6==6.5.1.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
sympy==1.11.1
terminado==0.17.1
tinycss2==1.2.1
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchvision==0.15.2+cu118
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.29.2
typing_extensions==4.4.0
ujson==5.7.0
uri-template==1.2.0
urllib3==1.26.13
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.2
zstandard==0.21.0
```

* The basic func of python is valid, for

  > python

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print("Hello world")
Hello world
>>>
```

* A Short, Self Contained, Correct, Example

```
import sys
from PySide6 import QtWidgets, QtWebEngineWidgets

class MyWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.webpg = QtWebEngineWidgets.QWebEngineView()
        self.webpg.load(u"https://www.qt.io")

        self.layout = QtWidgets.QVBoxLayout(self)
        self.layout.addWidget(self.webpg)

if __name__ == "__main__":
    app = QtWidgets.QApplication([])

    widget = MyWidget()
    widget.resize(800, 600)
    widget.show()

    sys.exit(app.exec())
```

* Provide in your issue the Nuitka options used

`--mingw64 --standalone --plugin-enable=pyside6`

* Note if this is a regression

  It did work fine at a factory branch commit, but it failed now.

Trace back:

 > python -m nuitka --mingw64 --standalone --plugin-enable=pyside6 .\hello_world.py

```
Nuitka-Options:INFO: Used command line options: --mingw64 --standalone --plugin-enable=pyside6 .\hello_world.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.2' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside6: Injecting pre-module load code for module 'PySide6':
Nuitka-Plugins:INFO: pyside6:     Adding binary folder to runtime 'PATH' environment variable for proper Qt loading.
Nuitka-Plugins:INFO: implicit-imports: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback information.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 12 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 23 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka-Plugins:INFO: pyside6: Included data file 'qt6.conf' due to QtWebEngine needs Qt configuration file.
Nuitka-Plugins:INFO: pyside6: Included data file 'icudtl.dat' due to Qt resources.
Nuitka-Plugins:INFO: pyside6: Included data file 'qtwebengine_devtools_resources.pak' due to Qt resources.
Nuitka-Plugins:INFO: pyside6: Included data file 'qtwebengine_resources.pak' due to Qt resources.
Nuitka-Plugins:INFO: pyside6: Included data file 'qtwebengine_resources_100p.pak' due to Qt resources.
Nuitka-Plugins:INFO: pyside6: Included data file 'qtwebengine_resources_200p.pak' due to Qt resources.
Nuitka-Plugins:INFO: pyside6: Included 321 data files due to Qt translation.
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6\qt-plugins'.
Nuitka-Plugins:INFO: pyside6: Including QtWebEngine executable.
Nuitka:INFO: Keeping build directory 'hello_world.build'.
Nuitka:INFO: Successfully created 'hello_world.dist\hello_world.exe'.
```

 > .\hello_world.dist\hello_world.exe

```
Problem importing shibokensupport:
ModuleNotFoundError: No module named 'logging'
Traceback (most recent call last):
  File "signature_bootstrap.py", line 63, in ensure_shibokensupport
  File "signature_bootstrap.py", line 83, in bootstrap
  File "signature_bootstrap.py", line 194, in exec_module
  File "shibokensupport/signature/loader.py", line 117, in <module>
  File "signature_bootstrap.py", line 194, in exec_module
  File "shibokensupport/signature/lib/pyi_generator.py", line 14, in <module>
ModuleNotFoundError: No module named 'logging'
sys.path:
  D:\Downloads\hello_pyside6_again\nuitka_webengine\hello_world.dist
  D:\Downloads\hello_pyside6_again\nuitka_webengine\hello_world.dist
```

**Comment by kayhayen** [comment]
That's a regression of 1.6.2 unfortunately. The `logging` module got added to the modules that are not automatically included, and that's biting us there. I had shiboken on my mind, but I thought it was not doing it in a hidden way, so then it should be included, shame on me there, for not testing it.

**Comment by kayhayen** [comment]
Part of the 1.6.3 hotfix release I just made.
