### ISSUE TITLE
Error with psutil._psutil_windows with Nuitka-Python

### ISSUE THREAD

**Issue by jshenguru** [Nuitka/Nuitka#2286]
**Problem**: Compilation error when processing psutil importing

Nuitka version:
```
1.6.3
Commercial: 2.1.1
Python: 3.9.15+ (heads/3.9-dirty:5f7d77a601, May 18 2023, 09:54:58) [MSC v.1929 64 bit (AMD64)]
Flavor: Nuitka Python
Executable: C:\Users\test\Documents\Python3.9-amd64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

```
Options:
```
--show-scons\
        --standalone \
        --remove-output \
        --company-name=$(SOFTWARE_COMPANY_NAME) \
        --product-name=$(PRODUCT_NAME) \
        --file-version=$(FILE_VERSION) \
        --product-version=$(PRODUCT_VERSION) \
        --file-description=$(FILE_DESCRIPTION) \
        --copyright=$(COPYRIGHT) \
        --trademarks=$(TRADEMARK) \
        --windows-icon-from-ico=$(ICON_FILE) \
        --embed-data-files-run-time-pattern=* \
```
Minimal example:

`import psutil
`
Error:
```
PASS 1: 23.4%|█████▊                   | 86/368, psutil    Traceback (most recent call last):
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\MainControl.py", line 1103, in main
    _main()
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\MainControl.py", line 963, in _main
    main_module = _createMainModule()
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\MainControl.py", line 257, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\optimizations\Optimization.py", line 337, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\optimizations\Optimization.py", line 293, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\optimizations\Optimization.py", line 180, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\optimizations\Optimization.py", line 140, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\importing\Recursion.py", line 429, in considerUsedModules
    Importing.warnAbout(
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\importing\Importing.py", line 179, in warnAbout
    if not isIgnoreListedNotExistingModule(
  File "C:\Users\test\Documents\Python3.9-amd64\lib\site-packages\nuitka\importing\IgnoreListing.py", line 439, in isIgnoreListedNotExistingModule
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError:

Your CPython version has a built-in module 'psutil._psutil_windows', that is not ignore listed
please report this as a bug.

The above information should be included in a bug report.
```

**Comment by kayhayen** [comment]
Hah, I think I saw you mention this, I was pretty sure this one should be fixed, because I saw a similar one myself, and there was a round of fixes for Nuitka-Python, for maybe even a hotfix of 1.5 I believe.

**Comment by kayhayen** [comment]
So, what I fixed then was a different kind of check for non-found modules, it seems.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.6.4 that I just made.
