### ISSUE TITLE
Missing data files for apkutils 

### ISSUE THREAD

**Issue by martinmiglio** [Nuitka/Nuitka#2289]
Adding [apkutils](https://gitee.com/kin9-0rz/apkutils) to my project results in a non-functioning onefile build.

Nuitka installed with poetry, using version 1.6.3.

`poetry show nuitka`:
```
 name         : nuitka
 version      : 1.6.3
 description  : Python compiler with full language support and CPython compatibility

dependencies
 - ordered-set >=4.1.
```

`poetry env info`:
```
 Virtualenv
Python:         3.11.1
Implementation: CPython
Path:           C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-py3.11
Executable:     C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-py3.11\Scripts\python.exe
Valid:          True

System
Platform:   win32
OS:         nt
Python:     3.11.1
Path:       C:\python311
Executable: C:\python311\python.exe
```

Non-working dependency list:
```toml
[tool.poetry.dependencies]
python = "^3.10"
pymemuc = "^0.4.2"
wmi = { version = "^1.5.1", markers = "sys_platform == 'win32'" }
numpy = "^1.24.3"
pillow = "^9.5.0"
requests = "^2.31.0"
nltk = "^3.8.1"
pysimplegui = "^4.60.5"
psutil = "^5.9.5"
apkutils = "^1.5.0"
```

Working dependency list:
```toml
[tool.poetry.dependencies]
python = "^3.10"
pymemuc = "^0.4.2"
wmi = { version = "^1.5.1", markers = "sys_platform == 'win32'" }
numpy = "^1.24.3"
pillow = "^9.5.0"
requests = "^2.31.0"
nltk = "^3.8.1"
pysimplegui = "^4.60.5"
psutil = "^5.9.5"
```

`apkutils` depends on:
```toml
[tool.poetry.dependencies]
Pygments = "^2.12.0"
beautifulsoup4 = "^4.10.0"
click = "^8.0.3"
cryptography = "^35.0.0"
lxml = "^4.6.4"
pyelftools = "^0.27"
pyftype = "^1.2.4"
python = ">=3.8"
colorlog = "^6.7.0"
```

This is the script I use to build my onefile:
```toml
[tool.poe.tasks.build-dist]
shell = """
poetry run nuitka src/main.py \
  --onefile \
  --enable-plugin=tk-inter \
  --enable-plugin=pylint-warnings \
  --disable-console \
  --windows-uac-admin \
  --prefer-source-code \
  --assume-yes-for-downloads \
  --report=build\\report-$Env:tagname.xml \
  --output-dir=build \
  --output-filename=XXX-$Env:tagname
"""
interpreter = "pwsh"
```

Here's a [gist with build reports](https://gist.github.com/martinmiglio/3d2765d3a52793141d59cd2441f5f988) from with and without `apkutils`

**Comment by martinmiglio** [comment]
caused by a missing XML in the package:
```
Traceback (most recent call last):
  ...
  File "C:\XXX\AppData\Local\Temp\ON8510~1\apkutils\__init__.py", line 1, in <module apkutils>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\XXX\AppData\Local\Temp\ON8510~1\apkutils\apk.py", line 14, in <module apkutils.apk>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\XXX\AppData\Local\Temp\ON8510~1\apkutils\axml\__init__.py", line 12, in <module apkutils.axml>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\XXX\AppData\Local\Temp\ON8510~1\apkutils\axml\public.py", line 22, in <module apkutils.axml.public>
Exception: need to copy the sdk/platforms/android-?/data/res/values/public.xml here
```

Fixed with a custom package config
```yml
- module-name: "apkutils.axml"
  data-files:
    patterns:
      - "public.xml"
```

This also happens with two other _very_ similar packages, [pyaxmlparser](https://github.com/appknox/pyaxmlparser) and [androguard](https://github.com/androguard/androguard), both with the same missing XML file.

**Comment by kayhayen** [comment]
Very glad you made it, I will be on the road today and merge later today or tomorrow, for inclusion in the next hotfix.

**Comment by kayhayen** [comment]
Part of the 1.6.4 hotfix release I just made.
