### ISSUE TITLE
ModuleNotFoundError when using pydantic without --prefer-source-code

### ISSUE THREAD

**Issue by chaosct** [Nuitka/Nuitka#2300]
Hi, 
I am encountering a problem when using nuitka with pydantic. If I compile a file with pydantic as a dependency, it will fail at runtime, unless I specify `--prefer-source-code`.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.6.5
Commercial: None
Python: 3.9.13 (main, Oct 19 2022, 16:06:06)
Flavor: pyenv
Executable: /tmp/nuitka_issue/env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

  I am using `pyenv` to install Python 3.9.13. I am using `venv` to create a clean environment.

* The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka==1.6.5
ordered-set==4.1.0
pydantic==1.10.9
pydantic-argparse==0.8.0
typing_extensions==4.6.3
zstandard==0.21.0
```

* Example

```
$  cat program2.py
import pydantic
print("Hello")

$  python -m nuitka --standalone program2.py
Nuitka-Options:INFO: Used command line options: --standalone program2.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.5' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 8 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 8
Nuitka:INFO: Keeping build directory 'program2.build'.
Nuitka:INFO: Successfully created 'program2.dist/program2.bin'.

$  program2.dist/program2.bin
Traceback (most recent call last):
  File "/tmp/nuitka_issue/program2.dist/program2.py", line 1, in <module>
  File "/tmp/nuitka_issue/program2.dist/pydantic/__init__.py", line 2, in <module pydantic>
  File "pydantic/dataclasses.py", line 43, in init pydantic.dataclasses
  File "pydantic/class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic/errors.py", line 1, in init pydantic.errors
ModuleNotFoundError: No module named 'decimal'

$ python -m nuitka --standalone --prefer-source-code program2.py
...

$  program2.dist/program2.bin
Hello
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Nuitka no longer includes modules like `decimal` automatically, which is why 1.6 broke this.

**Comment by kayhayen** [comment]
Part of the 1.6.6 hotfix I just made.
