### ISSUE TITLE
Error when running binary - ModuleNotFoundError: No module named 'urllib.request'

### ISSUE THREAD

**Issue by LeonidShamis** [Nuitka/Nuitka#2308]
Thank you for the fix that closed the Issue https://github.com/Nuitka/Nuitka/issues/2211

I tested it with the Stable Release 1.6.6.
The original problem that I reported was resolved - Nuitka has successfully built the binary.

However, the binary that was built did not work as the original Python program as shown below, which seems to be a new/different issue:

```
leonid@xlr2:~/dev/python/nuitka-test$ ls -l
total 4
-rw-rw-r-- 1 leonid leonid 154 May  2 13:28 cassandra-driver-test.py
leonid@xlr2:~/dev/python/nuitka-test$
leonid@xlr2:~/dev/python/nuitka-test$ cat cassandra-driver-test.py
import cassandra
from cassandra.cluster import Cluster

print(f"cassandra version: {cassandra.__version__}")
print(f"Cluster info: {Cluster.__module__}")
leonid@xlr2:~/dev/python/nuitka-test$
leonid@xlr2:~/dev/python/nuitka-test$ python3 -m venv .venv
leonid@xlr2:~/dev/python/nuitka-test$ . .venv/bin/activate
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python --version
Python 3.10.6
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip --version
pip 22.0.2 from /home/leonid/dev/python/nuitka-test/.venv/lib/python3.10/site-packages/pip (python 3.10)
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install cassandra-driver
Collecting cassandra-driver
  Downloading cassandra_driver-3.28.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 7.5 MB/s eta 0:00:00
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: six, click, geomet, cassandra-driver
Successfully installed cassandra-driver-3.28.0 click-8.1.3 geomet-0.2.1.post1 six-1.16.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m pip install -U nuitka
Collecting nuitka
  Using cached Nuitka-1.6.6-cp310-cp310-linux_x86_64.whl
Collecting zstandard>=0.15
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Collecting ordered-set>=4.1.0
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-1.6.6 ordered-set-4.1.0 zstandard-0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip freeze
cassandra-driver==3.28.0
click==8.1.3
geomet==0.2.1.post1
Nuitka==1.6.6
ordered-set==4.1.0
six==1.16.0
zstandard==0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --version
1.6.6
Commercial: None
Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/nuitka-test/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python cassandra-driver-test.py
cassandra version: 3.28.0
Cluster info: cassandra.cluster
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --standalone cassandra-driver-test.py
Nuitka-Options:INFO: Used command line options: --standalone cassandra-driver-test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.6' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 37 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'cassandra-driver-test.build'.
Nuitka:INFO: Successfully created 'cassandra-driver-test.dist/cassandra-driver-test.bin'.
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ls -l cassandra-driver-test.dist/cassandra-driver-test.bin
-rwxrwxr-x 1 leonid leonid 12933120 Jul  3 17:24 cassandra-driver-test.dist/cassandra-driver-test.bin
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ./cassandra-driver-test.dist/cassandra-driver-test.bin
Traceback (most recent call last):
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/cassandra-driver-test.py", line 2, in <module>
  File "cassandra/cluster.py", line 93, in init cassandra.cluster
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/cassandra/datastax/cloud/__init__.py", line 22, in <module cassandra.datastax.cloud>
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 97, in __get__
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 165, in _resolve
  File "/home/leonid/dev/python/nuitka-test/cassandra-driver-test.dist/six.py", line 87, in _import_module
ModuleNotFoundError: No module named 'urllib.request'
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
```

_Originally posted by @LeonidShamis in https://github.com/Nuitka/Nuitka/issues/2211#issuecomment-1617557989_

**Comment by kayhayen** [comment]
This can be reduced to even this:

```
from six.moves.urllib.request import urlopen
```

We are handling `six.moves` at least somewhat, but this specific case apparently not.

**Comment by kayhayen** [comment]
This is part of the 1.7 release I about to make, right now it's on factory branch.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Ultimately, this was an entry from `six.moves` that we didn't support yet. I took the chance to do a major refactoring for the way we treat stdlib and technical imports in general, but it turns out unrelated to all of that.

**Comment by LeonidShamis** [comment]
I have confirmed that the reported **issue** is now **resolved** with the [factory branch](https://nuitka.net/doc/factory.html) - please see below.

I've noticed that there were more "Nuitka-Plugins:WARNING" messages during the build process compared to the original test - not sure whether this is related to the factory branch specifics compared to the release branch used originally. 

```
leonid@xlr2:~/dev/python/nuitka-test$ ls -al
total 12
drwxrwxr-x 2 leonid leonid 4096 Jul  4 17:03 .
drwxrwxr-x 5 leonid leonid 4096 May 15 23:29 ..
-rw-rw-r-- 1 leonid leonid  154 May  2 13:28 cassandra-driver-test.py
leonid@xlr2:~/dev/python/nuitka-test$
leonid@xlr2:~/dev/python/nuitka-test$ python3 -m venv .venv
leonid@xlr2:~/dev/python/nuitka-test$ . .venv/bin/activate
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install cassandra-driver
Collecting cassandra-driver
  Using cached cassandra_driver-3.28.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.1 MB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: six, click, geomet, cassandra-driver
Successfully installed cassandra-driver-3.28.0 click-8.1.3 geomet-0.2.1.post1 six-1.16.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
Collecting https://github.com/Nuitka/Nuitka/archive/factory.zip
  Downloading https://github.com/Nuitka/Nuitka/archive/factory.zip
     \ 6.4 MB 8.9 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ordered-set>=4.1.0
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (pyproject.toml) ... done
  Created wheel for Nuitka: filename=Nuitka-1.7-cp310-cp310-linux_x86_64.whl size=2872650 sha256=9845ed17e887933d4d9d07e392a7189dcc55160e49950250c86a08b4a5751df2
  Stored in directory: /tmp/pip-ephem-wheel-cache-pk4t_n6a/wheels/12/88/12/96e4d1cdf9bcbea957e644c0a1e1ba5843c0143b1b03e240ed
Successfully built Nuitka
Installing collected packages: zstandard, ordered-set, Nuitka
Successfully installed Nuitka-1.7 ordered-set-4.1.0 zstandard-0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ pip freeze
cassandra-driver==3.28.0
click==8.1.3
geomet==0.2.1.post1
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
ordered-set==4.1.0
six==1.16.0
zstandard==0.21.0
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --version
1.7
Commercial: None
Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/leonid/dev/python/nuitka-test/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python cassandra-driver-test.py
cassandra version: 3.28.0
Cluster info: cassandra.cluster
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ python -m nuitka --standalone cassandra-driver-test.py
Nuitka-Options:INFO: Used command line options: --standalone cassandra-driver-test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' (intending to avoid 'unittest') in 'test.support' (at '/usr/lib/python3.10/test/support/__init__.py:15') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'doctest' (intending to avoid 'unittest') in 'test.support' (at '/usr/lib/python3.10/test/support/__init__.py:1177') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 37 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar.txt' due to package data for 'lib2to3.pygram'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar.txt' due to package data for 'lib2to3.pygram'.
Nuitka:INFO: Keeping build directory 'cassandra-driver-test.build'.
Nuitka:INFO: Successfully created 'cassandra-driver-test.dist/cassandra-driver-test.bin'.
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ls -l cassandra-driver-test.dist/cassandra-driver-test.bin
-rwxrwxr-x 1 leonid leonid 14230560 Jul  4 17:06 cassandra-driver-test.dist/cassandra-driver-test.bin
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
(.venv) leonid@xlr2:~/dev/python/nuitka-test$ ./cassandra-driver-test.dist/cassandra-driver-test.bin
cassandra version: 3.28.0
Cluster info: cassandra.cluster
(.venv) leonid@xlr2:~/dev/python/nuitka-test$
```

**Comment by kayhayen** [comment]
Part of the 1.7 release I just made.
