### ISSUE TITLE
DataComposer error with Nuitka 1.7: BuiltinAnonValue object is not callable

### ISSUE THREAD

**Issue by sebdelsol** [Nuitka/Nuitka#2311]
It looks like a duplicate of #2312.
It works fine when commenting the code from this commit: eabda5f.

## Minimal sample
```python3
def bug(_: list[int]):
    pass
```
**Environment:**
```console
1.7
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\sebmo\VS_Workspaces\test\.bug\scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```

## Nuitka
```console
python -m nuitka --standalone bug.py
```
**Log:**
```console
Nuitka-Options:INFO: Used command line options: --standalone bug.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.    
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka-DataComposer:WARNING: Problem with constant file 'module.__main__.const'.
```

**Error:**
```console
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\tools\data_composer\__main__.py", line 40, in <module>
    main()
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\tools\data_composer\DataComposer.py", line 407, in main
    count, part = _writeConstantStream(constants_reader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\tools\data_composer\DataComposer.py", line 318, in _writeConstantStream
    constant_value = constants_reader.readConstantValue()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\Serialization.py", line 167, in readConstantValue
    return self.pickle.load()
           ^^^^^^^^^^^^^^^^^^
TypeError: 'BuiltinAnonValue' object is not callable
Traceback (most recent call last):
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\MainControl.py", line 1109, in main
    _main()
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\MainControl.py", line 978, in _main
    result, options = compileTree()
                      ^^^^^^^^^^^^^
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\MainControl.py", line 888, in compileTree
    runDataComposer(source_dir)
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\build\DataComposerInterface.py", line 33, in runDataComposer
    blob_filename = _runDataComposer(source_dir=source_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebmo\VS_Workspaces\test\.bug\Lib\site-packages\nuitka\build\DataComposerInterface.py", line 54, in _runDataComposer
    subprocess.check_call(
  File "C:\Users\sebmo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\sebmo\\VS_Workspaces\\test\\.bug\\scripts\\python.exe', 'C:\\Users\\sebmo\\VS_Workspaces\\test\\.bug\\Lib\\site-packages\\nuitka\\tools\\data_composer', 'bug.build', 'bug.build\\__constants.bin']' returned non-zero exit status 1.
```

**Comment by d53dave** [comment]
While we're waiting for a response (and for closing one of the issues as duplicate), you could try patching your nuitka installation by modifying the Serialization.py to look like this:

```python
class BuiltinAnonValue(object):
    """Used to pickle anonymous values."""

    # Python3 values has no index, turn into a tuple.
    anon_values = tuple(builtin_anon_values.values())

    def __init__(self, anon_name):
        self.anon_name = anon_name

    def getStreamValueByte(self):
        """Return byte value, encoding the anon built-in value."""

        return to_byte(self.anon_values.index(self.anon_name))

    def __call__(self, *args: Any, **kwds: Any) -> Any:
        pass
```

This change made my build finish successfully, although I'm not sure what the ramifications are.

**Comment by sebdelsol** [comment]
On a more complex project it crashed at runtime. So it's safer to comment this commit: eabda5f.

**Comment by kayhayen** [comment]
The fix is under way, no panic. The workaround from @sebdelsol is indeed workable. It seems making a small fix can reveal other issues at times, but such is life.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I will make a hotfix release as well shortly. I didn't know that such simple code triggers it, I only noticed it at the edge of my CI in test_typing of CPython test suites, and that one does absurd things.

**Comment by sebdelsol** [comment]
It works fine with version 1.8rc1
