### ISSUE TITLE
TypeError: 'BuiltinAnonValue' object is not callable on MacOS

### ISSUE THREAD

**Issue by d53dave** [Nuitka/Nuitka#2312]
Hi, I'm running into the error message from the title when trying to build a small-to-medium sized project with Nuitka.

I use Python 3.10 (installed via brew) with pipenv and nuitka 1.7 (installed via pip).

```  ❯ python -m nuitka --version                                                                            [14:22:15]
1.7
Commercial: None
Python: 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Flavor: Homebrew Python
Executable: /Users/dsere/.virtualenvs/sample-project-tests-sNefaGVF/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

When building my project (`python -m nuitka --standalone sample_project.py`), I run into the following error:

```
Nuitka-DataComposer:WARNING: Problem with constant file 'module.sample_project.client.const'.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/tools/data_composer/__main__.py", line 40, in <module>
    main()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/tools/data_composer/DataComposer.py", line 407, in main
    count, part = _writeConstantStream(constants_reader)
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/tools/data_composer/DataComposer.py", line 318, in _writeConstantStream
    constant_value = constants_reader.readConstantValue()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/Serialization.py", line 164, in readConstantValue
    return self.pickle.load()
TypeError: 'BuiltinAnonValue' object is not callable
Traceback (most recent call last):
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/__main__.py", line 155, in <module>
    main()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/__main__.py", line 141, in main
    MainControl.main()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/MainControl.py", line 1109, in main
    _main()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/MainControl.py", line 978, in _main
    result, options = compileTree()
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/MainControl.py", line 888, in compileTree
    runDataComposer(source_dir)
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/build/DataComposerInterface.py", line 33, in runDataComposer
    blob_filename = _runDataComposer(source_dir=source_dir)
  File "/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/build/DataComposerInterface.py", line 54, in _runDataComposer
    subprocess.check_call(
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/bin/python', '/Users/d53dave/.virtualenvs/sample-project-tests-sNefaGVF/lib/python3.10/site-packages/nuitka/tools/data_composer', 'sample-project.build', 'sample-project.build/__constants.bin']' returned non-zero exit status 1.
```

While I'm not sure why the serializer would want to call `BuiltinAnonValue`, it seems that adding a `__call__` method does indeed allow the build to finish successfully in my case. I've also added a print statement to check what exactly the call looks like, and it seems to be rather boring:

```
BuiltinAnonValue __call__((<class 'list'>, (<class 'bytes'>,)), {})
```

**Comment by kayhayen** [comment]
Next time provide a reproducer please.
