### ISSUE TITLE
AssertionError， in getQtPluginsSelected

### ISSUE THREAD

**Issue by subtle99** [Nuitka/Nuitka#2323]
Traceback (most recent call last):                                                                    
  File "..\venv\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "..\venv\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "..\venv\lib\site-packages\nuitka\MainControl.py", line 1109, in main
    _main()
  File "..\venv\lib\site-packages\nuitka\MainControl.py", line 973, in _main
    addIncludedDataFilesFromPlugins()
  File "..\venv\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 418, in addIncludedDataFilesFromPlugins
    for included_datafile in Plugins.considerDataFiles(module=module):
  File "..\venv\lib\site-packages\nuitka\plugins\Plugins.py", line 738, in considerDataFiles
    for value in plugin.considerDataFiles(module):
  File "..\venv\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 816, in considerDataFiles
    "qml" in self.getQtPluginsSelected() or "all" in self.getQtPluginsSelected()
  File "..\venv\lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 212, in getQtPluginsSelected
    assert self.qt_plugins
AssertionError

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
