### ISSUE TITLE
The specified module could not be found: torchaudio 

### ISSUE THREAD

**Issue by joelmo** [Nuitka/Nuitka#2332]
Tried with both development version and this:
```ps
(env) PS C:\Users\joelm\Sync\gokaraoke\native> python -m nuitka --version
1.7.4
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\joelm\Sync\gokaraoke\native\env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe (cl 14.3).
```

```py
#nuitka_test.py
import torchaudio
print(torchaudio.get_audio_backend())
```

```ps
(env) PS C:\Users\joelm\Sync\gokaraoke\native> (nuitka --standalone --onefile .\nuitka_test.py) -and (.\nuitka_test.exe)
Traceback (most recent call last):                                                                                                              
  File "C:\Users\joelm\AppData\Local\Temp\ONEFIL~3\nuitka_test.py", line 1, in <module>
    import torchaudio
  File "C:\Users\joelm\AppData\Local\Temp\ONEFIL~3\torchaudio\__init__.py", line 1, in <module torchaudio>
  File "C:\Users\joelm\AppData\Local\Temp\ONEFIL~3\torchaudio\_extension\__init__.py", line 45, in <module torchaudio._extension>
ImportError: LoadLibraryExW 'C:\Users\joelm\AppData\Local\Temp\ONEFIL~3\torchaudio\lib\_torchaudio.pyd' failed: The specified module could not be found.
False
```

**Comment by kayhayen** [comment]
There might be DLLs missing, although it's rare for that to happen with extension modules, going to look at that.

**Comment by joelmo** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/336631/5541f06f-9f3f-42f4-a828-c5551a8eb59b)
`_torchaudio.pyd` is in the dist folder. Maybe some hard coded file path is causing this?

**Comment by joelmo** [comment]
`libtorchaudio` seems to be missing in dist folder.

From `env\Lib\site-packages\torchaudio\_extension\utils.py`
```py
def _load_lib(lib: str) -> bool:
    """Load extension module

    Note:
        In case `torchaudio` is deployed with `pex` format, the library file
        is not in a standard location.
        In this case, we expect that `libtorchaudio` is available somewhere
        in the search path of dynamic loading mechanism, so that importing
        `_torchaudio` will have library loader find and load `libtorchaudio`.
        This is the reason why the function should not raising an error when the library
        file is not found.

    Returns:
        bool:
            True if the library file is found AND the library loaded without failure.
            False if the library file is not found (like in the case where torchaudio
            is deployed with pex format, thus the shared library file is
            in a non-standard location.).
            If the library file is found but there is an issue loading the library,
            (such as missing dependency) then this function raises the exception as-is.

    Raises:
        Exception:
            If the library file is found, but there is an issue loading the library file,
            (when underlying `ctype.DLL` throws an exception), this function will pass
            the exception as-is, instead of catching it and returning bool.
            The expected case is `OSError` thrown by `ctype.DLL` when a dynamic dependency
            is not found.
            This behavior was chosen because the expected failure case is not recoverable.
            If a dependency is missing, then users have to install it.
    """
```

**Comment by kayhayen** [comment]
I managed to reproduce this, got to check out the code you pointed to. With `--list-package-dlls` there were no DLLs listed, but it seems you refer to one there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by joelmo** [comment]
Thanks this works.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.6 that I just made.
