### ISSUE TITLE
[bug] pyi encoding leads to error in different OS

### ISSUE THREAD

**Issue by monchin** [Nuitka/Nuitka#2361]
Hello, sometimes I use cython to define some classes or functions. For better programming hints, I write stub files `.pyi` for cython `.pyx` files. But if I write Chinese comments in pyi, `UTF8` will lead to error when I use nuitka `--standalone` in windows, while `gbk` will lead to error when I use nuitka `--standalone` in ubuntu, which confuses me when I need cross platform.

### Example
```cython
# test.pyx
def test():
    print("这是一个测试函数\nThis is a test function")
```
```python
# setup.py
from Cython.Build import cythonize
from setuptools import Extension, setup
extension = Extension(
        "test_pyi",
        sources = ["test.pyx"],
)
extensions = [extension]
setup(ext_modules=cythonize(extensions, language_level=3))
```
```python
# test_pyi.pyi
# save as utf-8
def test():
    '''
    这是一个测试函数
    This is a test function
    '''
    ...
```
```python
# main.py
from test_pyi import test
if __name__ == '__main__':
    test()
```
steps:
1. install cython and `python setup.py build_ext --inplace` to compile `test.pyx` to `test_pyi.cp3*.pyd/so`
2. install nuitka, I installed 1.7.7. In ubuntu install patchelf

Then, when I use ubuntu 22.04, I run `python -m nuitka main.py --standalone`, everything works well, and I `cd main.dist` and `./main.bin`, the output is what I want. But when I use windows 10, I run `python -m nuitka main.py --standalone`, an error raises
```
Nuitka-Options:INFO: Used command line options: .\main.py --standalone
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.7' on Python '3.10' commercial grade 'not installed'.
PASS 1: 0.4%|                         | 1/278, test_pyiTraceback (most recent call last):
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 81, in withPluginProblemReporting
    yield
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 533, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 424, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 401, in iterateModuleNames
    for v in value:
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\ImplicitImports.py", line 272, in getImplicitImports
    for used_module_name in module.getPyIModuleImportedNames():
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 1002, in getPyIModuleImportedNames
    self._readPyIFile()
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 979, in _readPyIFile
    pyi_deps = parsePyIFile(
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\tree\SourceHandling.py", line 304, in parsePyIFile
    for line_number, line in enumerate(getFileContentByLine(pyi_filename), start=1):
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 666, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 684, in getFileContents
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 34: illegal multibyte sequence
FATAL: implicit-imports: Plugin issue while working on 'module 'test_pyi''. Please report the bug with the above traceback included.
```
There are 3 ways to solve this problem:
- just use English to comment in pyi
- delete pyi
- save pyi as gbk

I don't want to use the first 2 ways, but if I use the 3rd way, ubuntu would raise almost the same error
```
Nuitka-Options:INFO: Used command line options: main.py --standalone
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.7' on Python '3.10' commercial grade 'not installed'.
PASS 1: 0.3%|                         | 1/292, test_pyiTraceback (most recent call last):
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 81, in withPluginProblemReporting
    yield
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 533, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 424, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 401, in iterateModuleNames
    for v in value:
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 272, in getImplicitImports
    for used_module_name in module.getPyIModuleImportedNames():
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 1002, in getPyIModuleImportedNames
    self._readPyIFile()
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 979, in _readPyIFile
    pyi_deps = parsePyIFile(
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/tree/SourceHandling.py", line 304, in parsePyIFile
    for line_number, line in enumerate(getFileContentByLine(pyi_filename), start=1):
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/utils/FileOperations.py", line 666, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
  File "/home/mon/.local/lib/python3.10/site-packages/nuitka/utils/FileOperations.py", line 684, in getFileContents
    return f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 26: invalid continuation byte
FATAL: implicit-imports: Plugin issue while working on 'module 'test_pyi''. Please report the bug with the above traceback included.
```
### Reason
I guess it is because default encodings are different in windows(gbk) and linux(utf-8), and when nuitka analyse pyi files, `encoding=None` and program uses the default OS encoding, then the error raises. So maybe nuitka should jump the pyi files to avoid cross platform encoding error.

**Comment by kayhayen** [comment]
Yes, very much it either would have to specify the encoding, but I doubt tools allow that, and since UTF8 is the default for Python now, it should just use that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.7.8 hotfix I just made.
