### ISSUE TITLE
Trouble with Python 3.11 Exception Groups

### ISSUE THREAD

**Issue by yqxk** [Nuitka/Nuitka#2386]
Hello,

This looks like an amazing project, and I'm excited to try it. I've been playing around with python 3.11 exception groups, and I'm not sure if I'm doing something wrongly, but I can't seem to get a simple example to run with nuitka:

```
root@9af304f0cf5e:/tmp# cat test.py
def main():
    try:
        pass
    except* Exception:
        pass

root@9af304f0cf5e:/tmp# python3.11 -m nuitka --version
1.7.9
Commercial: None
Python: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3.11
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
Version C compiler: /usr/bin/gcc (gcc).
```

```
root@9af304f0cf5e:/tmp# python3.11 -m nuitka --standalone test.py
Nuitka-Options:INFO: Used command line options: --standalone test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Optimization:WARNING: Problem at 'test.py:2' with TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[]).
Nuitka-Optimization:WARNING: Problem at 'test.py:1' with FunctionDef(name='main', args=arguments(posonlyargs=[], args=[], kwonlyargs=[], kw_defaults=[], defaults=[]), body=[TryStar(body=[Pass()],
Nuitka-Optimization:WARNING: handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])], decorator_list=[]).
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 155, in <module>
    main()
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 141, in main
    MainControl.main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 1109, in main
    _main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 969, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 159, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1135, in buildMainModuleTree
    module, _added = buildModule(
                     ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1365, in buildModule
    createModuleTree(
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1101, in createModuleTree
    module_body = buildParseTree(
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 772, in buildParseTree
    result = buildStatementsNode(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 473, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/ReformulationFunctionStatements.py", line 326, in buildFunctionNode
    function_statements_body = buildFrameNode(
                               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 491, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 325, in buildNode
    assert False, ast.dump(node)
AssertionError: TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])
```

I also tried with the develop version, with similar results:

```
root@9af304f0cf5e:/tmp# python3.11 -m nuitka --version
1.8rc9
Commercial: None
Python: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
Flavor: Debian Python
Executable: /usr/bin/python3.11
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
Version C compiler: /usr/bin/gcc (gcc).
```

```
root@9af304f0cf5e:/tmp# python3.11 -m nuitka --standalone test.py
Nuitka-Options:INFO: Used command line options: --standalone test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8rc9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Optimization:WARNING: Problem at 'test.py:2' with TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[]).
Nuitka-Optimization:WARNING: Problem at 'test.py:1' with FunctionDef(name='main', args=arguments(posonlyargs=[], args=[], kwonlyargs=[], kw_defaults=[], defaults=[]), body=[TryStar(body=[Pass()],
Nuitka-Optimization:WARNING: handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])], decorator_list=[]).
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 155, in <module>
    main()
  File "/usr/lib/python3/dist-packages/nuitka/__main__.py", line 141, in main
    MainControl.main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 1103, in main
    raise orig_exception
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 1096, in main
    _main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 956, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 161, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1161, in buildMainModuleTree
    module = buildModule(
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1411, in buildModule
    createModuleTree(
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1127, in createModuleTree
    module_body = buildParseTree(
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 775, in buildParseTree
    result = buildStatementsNode(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 472, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/ReformulationFunctionStatements.py", line 326, in buildFunctionNode
    function_statements_body = buildFrameNode(
                               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 490, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 325, in buildNode
    assert False, ast.dump(node)
AssertionError: TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

```
root@9af304f0cf5e:/tmp# cat nuitka-crash-report.xml
<nuitka-compilation-report nuitka_version="1.8rc9" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="AssertionError" exception_value="TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])">
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 1096, in main
    _main()
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 956, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/MainControl.py", line 161, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1161, in buildMainModuleTree
    module = buildModule(
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1411, in buildModule
    createModuleTree(
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 1127, in createModuleTree
    module_body = buildParseTree(
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/Building.py", line 775, in buildParseTree
    result = buildStatementsNode(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 472, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/ReformulationFunctionStatements.py", line 326, in buildFunctionNode
    function_statements_body = buildFrameNode(
                               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 490, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/nuitka/tree/TreeHelpers.py", line 325, in buildNode
    assert False, ast.dump(node)
AssertionError: TryStar(body=[Pass()], handlers=[ExceptHandler(type=Name(id='Exception', ctx=Load()), body=[Pass()])], orelse=[], finalbody=[])
</exception>
  <performance>
    <memory_usage name="after_launch" value="69201920" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="--standalone" />
    <option value="test.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="data-files" user_enabled="no" />
    <plugin name="delvewheel" user_enabled="no" />
    <plugin name="dll-files" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gevent" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="glfw" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="kivy" user_enabled="no" />
    <plugin name="matplotlib" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pbr-compat" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="pywebview" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python3.11" python_flavor="Debian Python" python_version="3.11.4" os_name="Linux" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.prefix}/lib/python3.11" />
      <path value="${sys.prefix}/lib/python3.11/lib-dynload" />
      <path value="${sys.prefix}/local/lib/python3.11/dist-packages" />
      <path value="${sys.prefix}/lib/python3/dist-packages" />
    </search_path>
  </python>
</nuitka-compilation-report>
```

I couldn't find any mention of exception groups in the issues besides from [this recent issue](https://github.com/Nuitka/Nuitka/issues/2355) which seems like a different problem. 

I'm running this in the official ubuntu 22.04 container (on an ubuntu 22.04 host), with python3.11 installed via the deadsnakes PPA and nuitka installed via the nuitka PPA. (nuitka initially complained about missing the yaml module so I additionally also installed pyyaml via pip to get it working.) 

```
root@9af304f0cf5e:/# python3.11 -m nuitka z.py
Nuitka-Options:INFO: Used command line options: z.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
FATAL: Error, expected inline copy of 'yaml' to be in '/usr/lib/python3/dist-packages/nuitka/build/inline_copy/yaml', error was: ModuleNotFoundError("No module named 'yaml'").
```

As a sanity check a simple `print('hello world')` runs fine with nuitka.

**Comment by kayhayen** [comment]
Ok, never saw this one yet, I have added exception group support in a couple of places, but that notation I don't think I saw so far.

**Comment by kayhayen** [comment]
Unfortunately this didn't get done yet.

**Comment by KevinRodriguez777** [comment]
```
❯ cat main.py
def main():
    try:
        pass
    except* Exception:
        pass

main()

░▒▓ 🎭  ~\Desktop\PyDis 02:16
❯ main.dist\main.exe
```
works nowadays looks like

**Comment by kayhayen** [comment]
The details are not yet fully correct, not using it works, but matching in them is not as it's supposed to be.

**Comment by grvstick** [comment]
Hi, I'm experiencing a similar issue with exception groups


The logging and sleep does not get executed. As if it was hanged.
```python
    async def run_ac_(self):
        delay = 5
        while True:
            try:
                await self.ac.main_task()
            except* Exception:
                logging.error(f"Error occurred. Retrying in {delay} seconds...")
                await asyncio.sleep(delay)
```

On the other hand, this works fine. I'm using this as workaround.
```python
    async def run_ac(self):
        delay = 5
        try:
            await self.ac.main_task()
        finally:
            logging.error(f"Error occurred. Closing in {delay} seconds...")
            await asyncio.sleep(delay)
            sys.exit()
```

This works as expected as well
```python
    async def run_ac(self):
        delay = 5
        try:
            await self.ac.main_task()
        except *Exception:
            pass
        finally:
            logging.error(f"Error occurred. Closing in {delay} seconds...")
            await asyncio.sleep(delay)
            sys.exit()
```

This works as expected as well
```python
    async def run_ac(self):
        delay = 5
        try:
            await self.ac.main_task()
        except *Exception:
            logging.error(f"Error occurred. Closing in {delay} seconds...")

        logging.error(f"Error occurred. Closing in {delay} seconds...")
        await asyncio.sleep(delay)
        sys.exit()
```


This does not work
```python
    async def run_ac(self):
        delay = 5
        try:
            await self.ac.main_task()
        except *MyException:
            logging.error(f"Error occurred. Closing in {delay} seconds...")

```

**Comment by ZeroIntensity** [comment]
@kayhayen Would you mind assigning this one to me?

**Comment by kayhayen** [comment]
Depending on how involved the solution is, I would love to have it in 2.7 or as a hotfix generally, but lets wait and see what it entails code wise.

**Comment by ZeroIntensity** [comment]
2.7? Exception groups were added in 3.11. Does Nuitka backport features?

**Comment by kayhayen** [comment]
Sorry for the late reply, Nuitka 2.7 is what I was talking about. I will bump Nuitka to 4.0 rather than a 2.10 to keep the number space more separate, I am personally dying from these, and with a Nuitka 3 things would get even more rough.

**Comment by ZeroIntensity** [comment]
Ah, ok, thanks for the clarification. I'll finish up the exception groups PR after I do the function type syntax.

**Comment by kayhayen** [comment]
I was kind of at a loss at how to handle the code explosion from the try/finally use. I wonder if you would dare and implement separate from the `Try` which has code branches for break, continue, except that all get the finally code tacked on in re-formulation of try/finally, a specialized `TryFinally` where the re-formulation would be using a C (not Python) temporary boolean "had_exception" and does a re-raise after executing the finally code branch. Many of the `Try` used for temporary variables lead to bloated C code, which in theory could be better optimized, e.g. knowing for sure that a variable is assigned or not, but that's two folded.

a) It would allow us to add nodes that manage published exception state not in a push/pop manner as what is the only form we currently have, but the exception group branches would just work on one state and change it, and restore the previous one in the end if necessary.

b) It would be very good for C side and likely Python side scalability, since less branches have to be merged, and Python compile time would be positively affected only if we put that to good use.

It would require that you kind of imitate the `Try` node, but have only a tried and a final block, and then just automatically resume break/continue/exception (if any) outwards with a `goto` from the C temporary indicator variable. We definitely would have to work closely there. I would say it's not simple, but it is also very doable and would give you a hang of how the control flow in generated code works.

**Comment by kayhayen** [comment]
@ZeroIntensity how does that sound to you?

**Comment by ZeroIntensity** [comment]
Sorry, missed that message. I think that makes sense, but I plan on finishing up the type syntax before going back to exception groups.

**Comment by kayhayen** [comment]
I fully agree, type tasks all should be relatively quick in comparison, this is more like a master class thing for when we are fully caught up. Might also still discover 3.14 things for you to take on after we do that.
