### ISSUE TITLE
Doesn't catch user error when non-Python filename is provided in module mode

### ISSUE THREAD

**Issue by gjmhmm8** [Nuitka/Nuitka#2389]
nuitka --module testmodel.pyx
Nuitka-Options:INFO: Used command line options: --module testmodel.pyx
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.9' on Python '3.9' commercial grade 'not installed'.
Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 155, in <module>
    main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 1109, in main
    _main()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 969, in _main
    main_module = _createMainModule()
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 159, in _createMainModule
    main_module = buildMainModuleTree(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\tree\Building.py", line 1135, in buildMainModuleTree
    module, _added = buildModule(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\tree\Building.py", line 1238, in buildModule
    ) = Importing.decideModuleSourceRef(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\importing\Importing.py", line 802, in decideModuleSourceRef
    assert type(module_name) is ModuleName, module_name
AssertionError: None

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Closing this one early for lack of general relevance, in 1.8 a better error will be given.

**Comment by kayhayen** [comment]
This is now on develop and will be in 1.8 release.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
