### ISSUE TITLE
Pickle/cloudpickle compiled local functions

### ISSUE THREAD

**Issue by hysmichael** [Nuitka/Nuitka#2392]
* Nuitka version, full Python version, flavor, OS, etc.
 
```
1.5.8
Commercial: None
Python: 3.9.17 (main, Jul  5 2023, 20:41:20)
Flavor: Anaconda Python
Executable: [...]/bin/python
OS: Linux
Arch: x86_64
Distribution: Centos (based on Fedora) 7
Version C compiler: [...]/gcc-10.1.0/bin/gcc (gcc).
```
 
Nuitka and Python installed via conda.
 
* The specific PyPI names and versions
 
```
cloudpickle==2.2.1
```
 
* Example to reproduce
 
```python
# example.py
def get_test_func():
    def local_func(x):
        return x + 1
    return local_func
```
 
Compile with nuitka:
```
python -m nuitka --module example.py
```
 
Then run the following:
```python
from example import get_test_func
import cloudpickle
import pickle
 
if __name__ == "__main__":
    t = get_test_func()
    print(type(t))   # <class 'compiled_function'>
 
    with open("compiled_func.pckl", "wb") as f:
        cloudpickle.dump(t, f)
    with open("compiled_func.pckl", "rb") as f:
        t2 = pickle.load(f)
 
    print(type(t2))  # <class 'function'>
    print(t2(1))  # Exception
```
 
Exception traceback:
```
XXX lineno: 17, opcode: 0
Traceback (most recent call last):
  File "[...]/mytest.py", line 45, in <module>
    print(t2(1))
  File "[...]/example.py", line 17, in local_func
    def local_func(x):
SystemError: unknown opcode
```
 
It looks like on loading the prickled function, a "function" class instead of a "compiled_function" class is constructed. Compiled module-level functions work fine with normal pickle because normal pickle pickles by reference. But cloudpickle adds support for pickling local functions and closures by value (see: https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs). I wonder if there is a way to serialize/desterilize a compiled local function so that I can pickle it by value?
 
Thank you!

**Comment by kayhayen** [comment]
The `dill` plugin carries code that can do it. You are using old Nuitka. With the plugin, compiled functions can be pickled and unpickled even when local. I am not sure that closure variables work, but they might. This has been used to make non-trivial programs work.

I think I would need funding through https://nuitka.net/doc/commercial.html to make it work by default and probably repair it, it has been known to regress every now and then.

**Comment by kayhayen** [comment]
You are using old Nuitka, and I no longer remember if the plugin is tied to dill, probably not. Notice that there was an issue of it not working inside `__main__`  which could be remedied as well.

**Comment by chpeagle7** [comment]
The same thing happened to me too, do you mind telling me how you eventually solved the problem?
I tried both Windows and macos and ran into this problem。It's just been sitting there forever。

```
➜  src git:(main) ✗ python3 -m nuitka --follow-imports  --standalone main.py
Nuitka-Options:INFO: Used command line options: --follow-imports --standalone main.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.10' on Python '3.11' commercial grade 'not installed'.
PASS 1: 1.2%|▎                        | 4/333, telethon.tl.types
```

**Comment by hysmichael** [comment]
Thank you @kayhayen. With my current setup I tried to compile with dill-compact plugin but the resulting module segfaults on import. We are reviewing the commercial options and will reach out separately.

**Comment by kayhayen** [comment]
Thanks for the feedback @hysmichael and I am looking forward to that.

**Comment by kayhayen** [comment]
So, I have adapted the dill compat code to the recent changes. I am getting an `AttributeError` with the dill version I happened to have installed. My plan is now to add support for the most recent version as well, they changed some of the internals there, and I will have to follow that.

**Comment by kayhayen** [comment]
As for cloudpickle, this is going to be fully true for "local" functions with the 2.7 release only.
