### ISSUE TITLE
Failed to initialize pythonnet

### ISSUE THREAD

**Issue by utkucorbaci** [Nuitka/Nuitka#2401]
I was trying to analyze .net samples with pythonnet in Nuitka compiled python binary. But I got the error that didn't load python.runtime.dll

 Nuitka Version:
```
utku@utkutest:~/test$ python3.11 -m nuitka --version
1.7.6
Commercial: None
Python: 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0]
Flavor: Debian Python
Executable: /usr/bin/python3.11
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

I used this code to install Nuitka:
`python3.11 -m pip install nuitka`

clr-loader and pythonnet versions:
```
pythonnet==3.0.1
clr-loader==0.2.5
```
The file that I use for test:
```python
import clr
clr.AddReference("/home/utku/dnlib.dll")
import dnlib
from dnlib.DotNet import *
sad = ModuleDefMD.Load("../1cd346c54de5119303b2387f3341e8d20920d3e3c5ad8ace7f095457d71a12ce.exe")
print(sad)
print(sad.EntryPoint)
```
> utku@utkutest:~/test$ python3 test.py
Client.exe
System.Void Client.Program::Main()

Fully Output:

```
utku@utkutest:~/test$ python3.11 -m nuitka test.py
Nuitka-Options:INFO: Used command line options: test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.6' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.bin'
utku@utkutest:~/test$ ./test.bin
Failed to initialize pythonnet: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception. ---> Python.Runtime.BadPythonDllException: Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net ---> System.MissingMethodException: Failed to load symbol Py_Main: ./test.bin: undefined symbol: Py_Main
  at Python.Runtime.Platform.PosixLoader.GetFunction (System.IntPtr dllHandle, System.String name) [0x00053] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Runtime+Delegates.GetFunctionByName (System.String functionName, System.IntPtr libraryHandle) [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
   --- End of inner exception stack trace ---
  at Python.Runtime.Runtime+Delegates.GetFunctionByName (System.String functionName, System.IntPtr libraryHandle) [0x00038] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Runtime+Delegates..cctor () [0x001ea] in <02a0d26b83f24e67b6a0456fd958e703>:0 
   --- End of inner exception stack trace ---
  at Python.Runtime.Runtime.PyGILState_Ensure () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.PythonEngine.AcquireLock () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Py+GILState..ctor () [0x00006] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Py.GIL () [0x00007] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Loader.Initialize (System.IntPtr data, System.Int32 size) [0x00029] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Runtime.PyGILState_Ensure () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.PythonEngine.AcquireLock () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Py+GILState..ctor () [0x00006] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Py.GIL () [0x00007] in <02a0d26b83f24e67b6a0456fd958e703>:0 
  at Python.Runtime.Loader.Initialize (System.IntPtr data, System.Int32 size) [0x00029] in <02a0d26b83f24e67b6a0456fd958e703>:0 Traceback (most recent call last):
  File "/home/utku/test/test.py", line 1, in <module>
    import clr
    
  File "/home/utku/.local/lib/python3.11/site-packages/clr.py", line 6, in <module>
    load()
  File "/home/utku/.local/lib/python3.11/site-packages/pythonnet/__init__.py", line 144, in load
    raise RuntimeError("Failed to initialize Python.Runtime.dll")
RuntimeError: Failed to initialize Python.Runtime.dll

Unhandled Exception:
System.InvalidOperationException: GIL must always be released, and it must be released from the same thread that acquired it.
  at Python.Runtime.Py+GILState.Finalize () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: GIL must always be released, and it must be released from the same thread that acquired it.
  at Python.Runtime.Py+GILState.Finalize () [0x00000] in <02a0d26b83f24e67b6a0456fd958e703>:0 
```

**Comment by kayhayen** [comment]
I don't think I would have the files necessary to reproduce this, do I, can you please reproduce this in a way that is easier. I think I have seen this package work on Windows. Since it crashes on `clr` import, your reproducer is too large.

**Comment by kayhayen** [comment]
Since your not even using standalone, but using the actual Python install, and system mono (likely), things ought to work. I wonder if this is somehow catching a release during the DLL loading of the GIL that is gone wrong.

When I tried standalone for good measure, I got this

> FATAL: Error, call to 'patchelf' failed: ['/usr/bin/patchelf', '--set-rpath', '$ORIGIN/../..', 'Mini.dist/pythonnet/runtime/Python.Runtime.dll'] -> b'patchelf: not an ELF executable'.

Seems we would have to actually treat these like data files on at least Linux, or know somehow that they are PE files and not ELF.

**Comment by kayhayen** [comment]
Also, with 3.10 I reproduced this on Ubuntu Python right now. The message is complete non-sense, I don't think Nuitka even touched the GIL itself yet, it imports the clr module, and then Python core code is taking over. Not sure what kind of setup its lacking there, maybe threading was not initialized, but is later, and then GIL checks trigger that are kind of wrong.

**Comment by kayhayen** [comment]
It seems something there wants a symbol that Nuitka doesn't expose.

`Failed to initialize pythonnet: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception. ---> Python.Runtime.BadPythonDllException: Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net ---> System.MissingMethodException: Failed to load symbol Py_Main: Mini.dist/Mini.bin: undefined symbol: Py_Main`

**Comment by kayhayen** [comment]
So, I think I have a suspect, that in accelerated mode, as you use it, it calls `Py_Main` after Nuitka did on its own create an interpreter, etc. already, and that code then duplicates stuff, which then causes the GIL conflict. I have no idea, why it would do that, and now in standard Python the reaction is supposed to be.

**Comment by kayhayen** [comment]
So, adding that function, and changing the assembly to be data files, I am having indeed success.

According to https://docs.python.org/3/c-api/veryhigh.html#c.Py_Main this function is for making sure the `__main__` is executed when embedding Python. Nuitka is embedding Python already, and as such that function is allowed to just do nothing, and is probably only used on Linux, I didn't see anything about this on Windows.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
