### ISSUE TITLE
Litestar: Invalid Locale configuration error in Faker when built with Nuitka.

### ISSUE THREAD

**Issue by itskanny** [Nuitka/Nuitka#2413]
I am trying to create executable of litestar library. But when the exeutable is created I get locale configurations issues from faker. Following is the stacktrace containing the error.

```
Traceback (most recent call last):
  File "D:\Projects\PythonProjects\pos-integration\main.dist\main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\app\app.py", line 15, in <module app.app>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\__init__.py", line 1, in <module litestar>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\app.py", line 15, in <module litestar.app>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\path_item.py", line 9, in <module litestar._openapi.path_item>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\__init__.py", line 1, in <module litestar._openapi.schema_generation>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\schema.py", line 45, in <module litestar._openapi.schema_generation.schema>        
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\examples.py", line 10, in <module litestar._openapi.schema_generation.examples>    
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\__init__.py", line 2, in <module polyfactory>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\__init__.py", line 1, in <module polyfactory.factories>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\base.py", line 157, in <module polyfactory.factories.base>
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\base.py", line 191, in BaseFactory
  File "D:\Projects\PythonProjects\pos-integration\main.dist\faker\proxy.py", line 70, in __init__
  File "D:\Projects\PythonProjects\pos-integration\main.dist\faker\factory.py", line 43, in create
AttributeError: Invalid configuration for faker locale `en_US`
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration\main.dist> nuitka --standalone --include-module="faker" .\main.py 
Nuitka-Options:INFO: Used command line options: --standalone --include-module=faker .\main.py
FATAL: Error, file '.\main.py' is not found.
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration\main.dist> cd ..                                                  
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration> nuitka --standalone --include-module="faker" .\main.py 
Nuitka-Options:INFO: Used command line options: --standalone --include-module=faker .\main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.10' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.                                         
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                          
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 1134 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 1134 C files using clcache with 992 cache hits and 142 cache misses.
Nuitka:INFO: Keeping build directory 'main.build'.                                                    
Nuitka:INFO: Successfully created 'main.dist\main.exe'.
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration> cd .\main.build\
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration\main.build> cd ../
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration> cd .\main.dist\ 
(pos-integration-py3.9) PS D:\Projects\PythonProjects\pos-integration\main.dist> .\main.exe
Traceback (most recent call last):
  File "D:\Projects\PythonProjects\pos-integration\main.dist\main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\app\app.py", line 15, in <module app.app>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\__init__.py", line 1, in <module litestar>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\app.py", line 15, in <module litestar.app>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\path_item.py", line 9, in <module litestar._openapi.path_item>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\__init__.py", line 1, in <module litestar._openapi.schema_generation>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\schema.py", line 45, in <module litestar._openapi.schema_generation.schema>        
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\litestar\_openapi\schema_generation\examples.py", line 10, in <module litestar._openapi.schema_generation.examples>    
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\__init__.py", line 2, in <module polyfactory>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\__init__.py", line 1, in <module polyfactory.factories>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\base.py", line 157, in <module polyfactory.factories.base>
  File "D:\Projects\PythonProjects\pos-integration\main.dist\polyfactory\factories\base.py", line 191, in BaseFactory
  File "D:\Projects\PythonProjects\pos-integration\main.dist\faker\proxy.py", line 70, in __init__
  File "D:\Projects\PythonProjects\pos-integration\main.dist\faker\factory.py", line 43, in create
AttributeError: Invalid configuration for faker locale `en_US`
```

The application works correctly when running from non executable state. and also I tried building using pyinstaller and it worked correctly. So it seems that somehow locales are missing in executable.

To test the code you can use following minimal example:

* app.py
```
from litestar import Litestar, get


@get("/")
async def hello_world() -> str:
    return "Hello, world!"


app = Litestar([hello_world])
```

* main.py
```
import uvicorn

from app import app
app = create_app()

if __name__ == "__main__":
    uvicorn.run(
        app,
    )
```
I used following nuitka command to compile the project
`nuitka --standalone --include-module=faker --include-module=locale .\main.py `

Nuitka Version

> python -m nuitka --version
1.7.10
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\muham\AppData\Local\pypoetry\Cache\virtualenvs\pos-integration-oUhk7PKL-py3.9\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

* How did you install Nuitka and Python

Python: Through msi installer provided by the python website
Nuitka: Using poetry package manager

Main packages used

  . polyfactory==2.7.2
  . pydantic==2.3.0
  . Faker==19.3.0
  . litestar==2.0.1

**Comment by kayhayen** [comment]
We have config for `faker` but maybe it's not enough.

**Comment by kayhayen** [comment]
It seems `pkgutil.iter_modules` is the culprit here, which is strange because we have tests for skimage and sklearn that are based around walking the whole and forcefully included package, but maybe this is for Windows only an issue, and the tests didn't gete added to Nuitka-Watch yet, and maybe only ran for Linux or macOS so far, at least `import faker`  works there. 

On Windows it seems it fails to iterate its providers, may have something to do with using the short path inconsistenly or at all, not sure now.

**Comment by itskanny** [comment]
Okay so I tried to import faker in my own main file and it built correctly. Even though I was already using `--include-module=faker` before but it was giving error. No that I just imported faker in my main file the error went away.

**Comment by itskanny** [comment]
I think somehow complete faker package was not being imported before

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
