### ISSUE TITLE
qtpy: @Slot workaround does not work

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#2415]
The workaround that Nuitka has in place to make PyQt5 threading code work by using the explicit `@pyqtSlot` decorator for slot methods does not work when PyQt5 is accessed via qtpy (an abstraction layer between the different Qt bindings in Python) and its `@Slot`

Note that in this case `@Slot` resolves to `@pyqtSlot` in the end. I suppose Nuitka does not see that because of its dynamic nature.

I suppose you know of it, but the symptom I am having without the decorator on PyQt5 and in all cases on qtpy is an unresponsive UI when the worker "works" and vice versa, as if the UI and the worker shared the same thread.

Also of note is that, when not run via Nuitka the explicit decorator is not necessary at all in most cases (including this case).

One last side note: using the `@pyqtSlot` decorator on a function instead of a method raises an exception under Nuitka and not under Python.  I don't think the decorator is meant to be used like that but since this works under Python, I suppose you are interested to know this. For example, when using it on the stop_worker function below, I get the following traceback:

```python
Traceback (most recent call last):
  File "<...>\TEST_P~3.DIS\test_progress4.py", line 60, in <module>
  File "<...>\TEST_P~3.DIS\test_progress4.py", line 53, in test
NameError: name 'stop_worker' is not defined
```

* Nuitka version

1.7.10
Commercial: None
Python: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\[...]\Miniconda3x64\envs\nuitka_qtpy_slot\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

* How did you install Nuitka and Python

conda create -n nuitka_qtpy_slot python=3.10
conda activate nuitka_qtpy_slot
pip install nuitka qtpy PyQt5

* The specific PyPI names and versions

Nuitka==1.7.10
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.2
QtPy==2.4.0

* Also supply a Short, Self Contained, Correct, Example

```python
# nuitka-project: --standalone
# nuitka-project: --enable-plugin=pyqt5
import time

from qtpy.QtCore import Qt, Signal, Slot, QObject, QThread
from qtpy.QtWidgets import QApplication, QProgressDialog


class WorkerWithProgress(QObject):
    finished = Signal()
    progress = Signal(int)

    def __init__(self):
        QObject.__init__(self)
        self.canceled = False

    @Slot()       # <--- does not change anything
    def start(self):
        self.progress.emit(0)
        for i in range(10):
            time.sleep(2)
            if self.canceled:
                break
            self.progress.emit(i + 1)
        self.finished.emit()

    def stop(self):
        self.canceled = True


def test():
    app = QApplication([])
    worker = WorkerWithProgress()

    progress_dialog = QProgressDialog(f"Computing",
                                      "Abort", 0, 10, None)
    progress_dialog.setWindowModality(Qt.WindowModal)

    thread = QThread()
    worker.moveToThread(thread)

    def stop_worker():
        if thread.isRunning():
            worker.stop()
            thread.quit()
            thread.wait()

    thread.started.connect(worker.start)
    thread.finished.connect(thread.deleteLater)
    worker.finished.connect(thread.quit)
    worker.finished.connect(worker.deleteLater)
    worker.finished.connect(progress_dialog.close)
    worker.progress.connect(progress_dialog.setValue)
    progress_dialog.canceled.connect(stop_worker)
    progress_dialog.show()
    thread.start()

    app.exec_()


test()
```

The exact same code using PyQt5 directly (and thus @pyqtSlot) works:

```python
# nuitka-project: --standalone
# nuitka-project: --enable-plugin=pyqt5
import time

from PyQt5.QtCore import Qt, pyqtSignal, pyqtSlot, QObject, QThread
from PyQt5.QtWidgets import QApplication, QProgressDialog


class WorkerWithProgress(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(int)

    def __init__(self):
        QObject.__init__(self)
        self.canceled = False

    @pyqtSlot()     # <---- makes the UI responsive
    def start(self):
        self.progress.emit(0)
        for i in range(10):
            time.sleep(2)
            if self.canceled:
                break
            self.progress.emit(i + 1)
        self.finished.emit()

    def stop(self):
        self.canceled = True


def test():
    app = QApplication([])
    worker = WorkerWithProgress()

    progress_dialog = QProgressDialog(f"Computing",
                                      "Abort", 0, 10, None)
    progress_dialog.setWindowModality(Qt.WindowModal)

    thread = QThread()
    worker.moveToThread(thread)

    def stop_worker():
        if thread.isRunning():
            worker.stop()
            thread.quit()
            thread.wait()

    thread.started.connect(worker.start)
    thread.finished.connect(thread.deleteLater)
    worker.finished.connect(thread.quit)
    worker.finished.connect(worker.deleteLater)
    worker.finished.connect(progress_dialog.close)
    worker.progress.connect(progress_dialog.setValue)
    progress_dialog.canceled.connect(stop_worker)
    progress_dialog.show()
    thread.start()

    app.exec_()


test()
```

**Comment by kayhayen** [comment]
The workaround right now insists on the decorator to be a name reference to `pyqtSlot` exactly. I don't know what `Slot` is supposed to do, but we can add it to that list of course, and have that work.

This is not the most sophisticated code ever:

```
def decideFunctionCompilationMode(decorators):
    """Decide how to compile a function based on decorator names."""

    global _has_pyqt_plugin  # singleton, pylint: disable=global-statement

    if _has_pyqt_plugin is None:
        _has_pyqt_plugin = hasActivePlugin("pyqt5") or hasActivePlugin("pyqt6")

    # TODO: Expose the interface to plugins, so we don't hardcode stuff for
    # specific plugins here, but for performance I guess, we would have to add a
    # registry for the plugins to use, so not every decorator name is being
    # called for every plugin.

    # TODO: This can only work with 3.9 or higher so far.
    if _has_pyqt_plugin and python_version >= 0x390:
        for decorator in decorators:
            if (
                decorator.isExpressionCall()
                and decorator.subnode_called.isExpressionVariableNameRef()
            ):
                if decorator.subnode_called.variable_name == "pyqtSlot":
                    return "bytecode"

    return "compiled"
```

But adding more names there, surely would be supposed to work.

**Comment by kayhayen** [comment]
I would love for you to make a PR on this, if you oversee the impact of that. Since it's limited to when plugin is enabled, we can do it like that even globally if you ask me.

**Comment by gdementen** [comment]
> I don't know what `Slot` is supposed to do,

Well, that's the trick: it actually ***is*** pyqtSlot, just imported "dynamically" instead of "statically". qtpy.QtCore has code like this:

```python
if PYQT5:
    from PyQt5.QtCore import pyqtSlot as Slot
    [...]
elif PYQT6:
    from PyQt6.QtCore import pyqtSlot as Slot
    [...]
elif PYSIDE6:
    import PySide6.QtCore
    from PySide6.QtCore import *
```
See https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtCore.py

> I would love for you to make a PR on this, if you oversee the impact of that. Since it's limited to when plugin is enabled, we can do it like that even globally if you ask me.

I will try. But `Slot` seems like a much more generic name than pyqtSlot so I fear that somebody using the pyqt plugin will have a Slot decorator somewhere unrelated to pyqt.

**Comment by kayhayen** [comment]
I think we might better direct efforts to become able to *redo*  a function after the fact. That would mean, we would compile the function as is. I think right now, imports, and everything are lost cause in this approach. It happens to work for some things, but it clearly is really bad. Even worse than demoting the whole module to bytecode after the compilation.

But what if we were to become capable of making these decisions at compile time. Maybe even only by whilelisting a variable like `Slot` to be used cross module for some modules, or when they have these kind of "hard" values. Then the optimization could recognize the actual decorator being used, and not rely on a specfic import form being used. That would be something much more useful.

In that "pass 3", doing cross module optimization (that cannot be cached unless separately with dependencies), would actually do these things and affected modules would be computed another pass, in which a function can get that "shadow", which is bytecode or source code.

**Comment by gdementen** [comment]
> But what if we were to become capable of making these decisions at compile time.

You lost me here. Isn't this what is currently happening? Or is the decision done at runtime currently??? Or do you mean that currently the decision is done in an earlier phase than the compilation?

> Then the optimization could recognize the actual decorator being used, and not rely on a specific import form being used

I don't understand the change you are proposing, but the current solution seems very fragile (*) to me indeed, so if what you propose solves that, that would be great.

(*) in both ways: it does not pickup the decorator when its name is different (the current issue), but could also pick up other stuff if the name is the same.

> In that "pass 3", doing cross module optimization (that cannot be cached unless separately with dependencies)

You probably mean the same thing, but AFAICT, you could cache the "cross-module optimized" module as long as the key includes all its dependencies **and** all the information that cross the module boundary. But for optimized caching I think I would try to cache per function instead of per module. 

Speaking of caching, I don't understand why some things are re-compiled on every run. When I update a script using Pandas for example and the new version does not use any extra functionality in Pandas, I don't expect Pandas to be recompiled, but it is, at least in large part and personally, this is what makes my compile times annoying. The examples I gave in this issue, were almost a joy to create ***after*** I realized Pandas wasn't necessary to trigger the issue (but given the compile times, it took me a looong time to realize that).

**Comment by kayhayen** [comment]
The reason they are re-compiled is because I am not productive enough to produce a compiler and make it cache perfectly at the same time. I am constantly struggling to keep up in terms of feature completeness and correctness and size, and speed of the result, I just cannot add caching bugs to the mix easily. And structurally, how variables are currently created, I do not feel I can persist the module/function objects very well yet, so I cannot even start it yet.

**Comment by gdementen** [comment]
Hey, you seem to take my remark badly but I really did not mean it as criticism, just as a genuine "I don't understand".

**Comment by kayhayen** [comment]
Ah, nah, that was just me being reallistic, however, I always tke caching into account even if I don't get there (yet?). I am not sure if people appreciate that I really would like to be there and have that. I do however think implementing and debugging that is probably a year of my time, which would mean to fall back on other things. Maybe slowly and steady, like I always do, I can further it one by one until it becomes a thing without a dedicated effort. I will see what loop analysis makes me change.

But yeah, it feels bad. The thing that right now would need the cleanup that probably takes a month or two just to be where it was would change how variable scopes are not really detached and detachable from functions as well as they ought to be. That is the one thing that prevents streaming to and from XML the module state.

The decision to do source or bytecode for functions is done indeed during "tree buiding", and based on name of the decorator, which is like the weakest possible thing. That is when the ast module output is converted to a Nuitka re-formulation, and functions have that too. And in there it's done now. The only thing weaker would be change the source code directly. Pushing that down to code generation would be ever so sweet obviously, because it allows to base the decision on optimized code, where say things like inlining from other modules did already happen.

My initial goal with this was however to demonstrate that it can be done, and to potentially have a tool that will make some things work with say numba eventually, by e.g. treating their `@jit` annotation like that as well. The fact that PyQt5 can be made work a little better was just the playground, albeit a serioues one, since PyQt5 will forever remain commercially relevant.

**Comment by gdementen** [comment]
I am unsure now that you assigned yourself if you expect me to do that PR for supporting Slot in addition to pyqtSlot or if what you envisioned obsoletes that.

**Comment by kayhayen** [comment]
Ah, assigning I am not treating it like that, which is probably wrong of me. I just more am like accepting an issue with that as such. 

I will appreciate it if you try and come up with a way of evaluating these decorator calls on function creations in the node tree depending on them being kind of what we call hard imports. Checkout `nuitka.HardImportRegistry` on current factory and develop. Plugins like that pyqt5 plugin probably want to add hard import name nodes for the decorators, and then do different for them in code generation, creating these function objects much like the re-formulation does not from ´compile` built-in and so on, probably just re-using the code generation of those nodes.

That shift is not terribly hard, but I am sure can be annoying. Cross-module stuff is not needed there, and caching already takes plugin enable/disable into account. The plugin could for now handle `Slot` from the module you mentioned in a hard coded way. Only later, when cross module stuff becomes real, it would then become possible to drop it, and use that instead.

**Comment by pHiney** [comment]
> I will try. But `Slot` seems like a much more generic name than pyqtSlot so I fear that somebody using the pyqt plugin will have a Slot decorator somewhere unrelated to pyqt.

ok, from this, am I supposed to change all my Slot() decorators to pyqtSlot(). Is this and other advice written somewhere ?

thanks
pH

**Comment by gdementen** [comment]
@pHiney : I do not think **PySide6** has any problem to begin with, so simply using Slot should work AFAIK

For qtpy, the workaround I currently use is simply:
```python
from qtpy.QtCore import Slot as pyqtSlot
```

**Comment by kayhayen** [comment]
For now however, you are of course free to abuse the existing hack until it's replaced with a better solution as outlined.

**Comment by pHiney** [comment]
What will happen if I comment out all the Slot(). Other documents on the web indicate the function will still be called by the connected component/widget.
Is that something that someone knows (with respect to Nuitka) ?

ty
pH

**Comment by kayhayen** [comment]
Nuitka is compatible with these things. However, if not recognized by the older Qt bindings PyQt5 and PySide2, compiled methods do not work well for things like threading, etc. but if you use the newer bindings, ideally PySide6, it's actually supported by Qt company and me both that everything works.

**Comment by kayhayen** [comment]
The slot decorators are only used with PyQt5 to indicate a workaround where methods are not compiled, but used uncompiled, which PyQt5 won't have issues with. Wrapping them in exec e.g. would also do for now (still not optimizing it for constant strings even).

**Comment by kayhayen** [comment]
I am currently working on bytecode preservation for `numba.stencil` decorator and once that is implemented, we can treat this just the same, and have it generally working for everything with these decorators as well.

**Comment by kayhayen** [comment]
I can add `Slot` to be treated, just like `pyqtslot`, but private names are still not going to work, since there is no name mangling done on methods, that is an issue of course, where I don't have a good idea to fix it. But it's still better than nothing i guess. Of course this only applies to PyQt5/PyQt6 and their Nuitka plugins being active.

**Comment by kayhayen** [comment]
This is based on #650 implementation and turns this into sort of its duplicate, just adding that name to the plugins return value of `getUncompiledDecoratorNames` make this easy now.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Part of the 4.0 release.
