### ISSUE TITLE
[MACOS 12.5][Qt5/Qt6] No such file or directory: '/usr/local/lib/python3.9/site-packages/PyQt5/Qt5/libexec'

### ISSUE THREAD

**Issue by shangdibufashi** [Nuitka/Nuitka#2419]
- [nuitka-crash-report.xml.txt](https://github.com/Nuitka/Nuitka/files/12492141/nuitka-crash-report.xml.txt)

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
    
      1.8
      Commercial: None
      Python: 3.9.13 (main, Aug 11 2022, 14:05:15) 
      Flavor: Homebrew Python
      Executable: /usr/local/Cellar/python@3.9/3.9.13_3/bin/python3.9
      OS: Darwin
      Arch: x86_64
      Version C compiler: /usr/bin/clang (clang).

   **Nuitka 1.7.10 fails too**
   **QT6 also fails too**

- How did you install Nuitka and Python
      
      python3.9 -m pip show nuitka 
      Name: Nuitka
      Version: 1.8
      Summary: Python compiler with full language support and CPython compatibility
      Home-page: https://nuitka.net
      Author: Kay Hayen
      Author-email: Kay.Hayen@gmail.com
      License: Apache License, Version 2.0
      Location: /usr/local/lib/python3.9/site-packages
      Requires: ordered-set, zstandard
      Required-by: 
      
      python3.9 --version          
      Python 3.9.13

- The specific PyPI names and versions

  It should be taken from this output if there specific packages involved, e.g. `numpy`, you are
  expected to shorten this to the relevant ones.

  > python -m pip freeze
        
        aiobotocore==2.4.0
        aiofiles==23.2.1
        aiohttp==3.8.5
        aioitertools==0.10.0
        aiosignal==1.2.0
        aniso8601==9.0.1
        anyio==3.7.1
        appdirs==1.4.4
        appnope==0.1.3
        astroid==2.4.2
        asttokens==2.0.5
        async-timeout==4.0.2
        attrs==21.2.0
        audioread==2.1.9
        autopep8==1.6.0
        backcall==0.2.0
        black==21.10b0
        boto3==1.24.59
        botocore==1.27.59
        bottle==0.12.25
        cachetools==5.0.0
        cefpython3==66.0
        certifi==2023.7.22
        cffi==1.14.6
        chardet==3.0.4
        charset-normalizer==2.0.12
        click==7.1.2
        cloudscraper==1.2.64
        coloredlogs==15.0.1
        cycler==0.10.0
        debugpy==1.6.0
        decorator==5.1.0
        dill==0.3.4
        entrypoints==0.4
        exceptiongroup==1.1.3
        executing==0.8.3
        ExifRead==3.0.0
        fastapi==0.101.1
        feature-selector===N-A
        filelock==3.8.0
        Flask==2.0.2
        Flask-Cors==3.0.10
        flask-restx==0.5.1
        Flask-WTF==0.15.1
        flatbuffers==23.5.26
        frozendict==2.3.8
        frozenlist==1.3.1
        fsspec==2022.8.2
        fuzzywuzzy==0.18.0
        gevent==21.8.0
        google-api-core==2.5.0
        google-api-python-client==2.38.0
        google-auth==2.6.0
        google-auth-httplib2==0.1.0
        googleapis-common-protos==1.55.0
        greenlet==1.1.2
        h11==0.14.0
        httpcore==0.17.3
        httplib2==0.20.4
        httpx==0.24.1
        huggingface-hub==0.10.1
        humanfriendly==10.0
        idna==3.4
        imageio==2.31.1
        importlib-metadata==2.1.1
        inflect==5.3.0
        iniconfig==2.0.0
        ipykernel==6.15.0
        ipython==8.4.0
        isort==5.7.0
        itsdangerous==2.0.1
        jedi==0.18.1
        Jinja2==3.0.2
        jmespath==1.0.1
        joblib==1.1.0
        jsonpatch==1.32
        jsonpointer==2.1
        jsonschema==4.1.0
        jupyter-client==7.3.4
        jupyter-core==4.10.0
        kiwisolver==1.3.2
        lazy-object-proxy==1.4.3
        librosa==0.8.1
        lightgbm==3.3.2
        llvmlite==0.38.1
        MarkupSafe==2.0.1
        matplotlib==3.4.3
        matplotlib-inline==0.1.3
        mccabe==0.6.1
        mpmath==1.3.0
        msgpack==1.0.5
        multidict==6.0.2
        multiprocess==0.70.12.2
        mypy-extensions==0.4.3
        nest-asyncio==1.5.5
        netaddr==0.8.0
        netease-musicbox==0.3.1
        Nuitka @ https://github.com/Nuitka/Nuitka/archive/refs/tags/1.8.zip
        numba==0.55.2
        numpy==1.22.4
        oauth2client==4.1.3
        onnxruntime==1.15.1
        opencv-contrib-python-headless==4.6.0.66
        opencv-python-headless==4.6.0.66
        ordered-set==4.1.0
        orderedset==2.0.3
        packaging==21.0
        pandas==1.4.4
        parso==0.8.3
        pathspec==0.9.0
        pexpect==4.8.0
        pickleshare==0.7.5
        piexif==1.1.3
        Pillow==10.0.0
        platformdirs==2.4.0
        pluggy==1.2.0
        pooch==1.5.1
        prettytable==2.1.0
        prompt-toolkit==3.0.30
        protobuf==4.21.5
        proxy-tools==0.1.0
        psutil==5.9.1
        ptyprocess==0.7.0
        pure-eval==0.2.2
        pyasn1==0.4.8
        pyasn1-modules==0.2.8
        pycodestyle==2.8.0
        pycparser==2.20
        pycryptodome==3.18.0
        pycryptodomex==3.10.1
        pydantic==1.10.12
        PyDrive==1.3.1
        pyee==8.2.2
        pygame==2.1.2
        Pygments==2.12.0
        PyJWT==2.0.0
        pylint==2.6.0
        pymusic-dl==3.0.1
        pynndescent==0.5.4
        pyobjc-core==9.2
        pyobjc-framework-Cocoa==9.2
        pyobjc-framework-Security==9.2
        pyobjc-framework-WebKit==9.2
        pyparsing==2.4.7
        pypinyin==0.43.0
        pyppeteer==1.0.2
        PyQt5==5.15.9
        PyQt5-Qt5==5.15.2
        PyQt5-sip==12.12.2
        PyQt6-WebEngine-Qt6==6.5.2
        PyQtWebEngine==5.15.6
        PyQtWebEngine-Qt5==5.15.2
        pyrsistent==0.18.0
        pytest==7.4.0
        pytest-asyncio==0.21.1
        pytest-mock==3.11.1
        python-dateutil==2.8.2
        python-Levenshtein==0.12.2
        python-multipart==0.0.6
        pytz==2021.3
        PyYAML==6.0
        pyzmq==23.2.0
        QtPy==2.4.0
        regex==2021.11.10
        requests==2.28.0
        requests-cache==0.5.2
        requests-toolbelt==0.9.1
        resampy==0.2.2
        rsa==4.8
        rumps==0.4.0
        s3fs==2022.8.2
        s3transfer==0.6.0
        scikit-learn==1.0
        scipy==1.7.1
        seaborn==0.12.0
        six==1.16.0
        sklearn==0.0
        sniffio==1.3.0
        sounddevice==0.4.2
        SoundFile==0.10.3.post1
        stack-data==0.3.0
        starlette==0.27.0
        StrEnum==0.4.15
        sympy==1.12
        tenacity==8.2.3
        threadpoolctl==3.0.0
        tokenizers==0.13.1
        toml==0.10.2
        tomli==1.2.2
        torch==1.9.1
        torchfile==0.1.0
        tornado==6.1
        tqdm==4.60.0
        traitlets==5.3.0
        transformers==4.23.1
        typing_extensions==4.7.1
        umap-learn==0.5.1
        Unidecode==1.3.2
        uritemplate==4.1.1
        urllib3==1.26.9
        uvicorn==0.23.2
        validators==0.20.0
        visdom==0.1.8.9
        wcwidth==0.2.5
        webrtcvad==2.0.10
        websocket-client==1.2.1
        websockets==10.3
        Werkzeug==2.0.2
        wrapt==1.12.1
        WTForms==2.3.3
        wxPython==4.2.1
        yapf==0.31.0
        yarl==1.8.1
        zipp==3.4.1
        zope.event==4.5.0
        zope.interface==5.4.0
        zstandard==0.21.0

- Many times when you get an error from Nuitka, your setup may be special

      Nuitka-Plugins:INFO: pyqt5: Including Qt plugins 'all,iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,styles' below 'PyQt5/qt-plugins'.
      Nuitka-Plugins:INFO: pyqt5: Including QtWebEngine executable.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 82, in withPluginProblemReporting
          yield
        File "/usr/local/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 654, in considerExtraDlls
          for entry_point in _iterateExtraBinaries(
        File "/usr/local/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 644, in _iterateExtraBinaries
          for v in _iterateExtraBinaries(plugin, val):
        File "/usr/local/lib/python3.9/site-packages/nuitka/plugins/Plugins.py", line 643, in _iterateExtraBinaries
          for val in value:
        File "/usr/local/lib/python3.9/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 860, in _getExtraBinariesWebEngineGeneric
          for filename, filename_relative in listDir(qt_web_engine_dir):
        File "/usr/local/lib/python3.9/site-packages/nuitka/utils/FileOperations.py", line 297, in listDir
          [(os.path.join(path, filename), filename) for filename in os.listdir(real_path)]
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/PyQt5/Qt5/libexec'
      FATAL: pyqt5: Plugin issue while working on 'module 'PyQt5.QtWebEngineCore''. Please report the bug with the above traceback included.
      Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.

- Avoid unnecessary options

      
      python3.9 -m nuitka \
      --show-scons \
      --disable-console \
      --onefile \
      --windows-disable-console \
      --standalone  \
      --python-flag=no_site,no_docstrings,isolated \
      --macos-app-icon=assets/logo.png \
      --show-progress \
      --plugin-enable=pyqt5 \
      --include-qt-plugins=all \
      \
      --nofollow-import-to=astropy \
      --nofollow-import-to=sympy \
      --nofollow-import-to=dask \
      \
      --nofollow-import-to=ipywidgets \
      --nofollow-import-to=ipython_genutils \
      --nofollow-import-to=ipykernel \
      \
      --nofollow-import-to=IPython \
      --nofollow-import-to=pexpect \
      --nofollow-import-to=nbformat \
      \
      --nofollow-import-to=numpydoc \
      --nofollow-import-to=matplotlib \
      --nofollow-import-to=pandas \
      \
      --nofollow-import-to=pytest \
      --noinclude-pytest-mode=nofollow \
      --noinclude-setuptools-mode=nofollow \
      --nofollow-import-to=nose \
      --macos-create-app-bundle \
      \
      --include-data-dir=./assets=assets \
      
      --follow-imports engine.py

## nuitka-crash-report.xml
[nuitka-crash-report.xml.txt](https://github.com/Nuitka/Nuitka/files/12492141/nuitka-crash-report.xml.txt)

**Comment by shangdibufashi** [comment]
File in /usr/local/lib/python3.9/site-packages/PyQt5

```shell
 % ls /usr/local/lib/python3.9/site-packages/PyQt5
Qt                                      QtMacExtras.abi3.so                     QtQml.pyi                               QtTest.abi3.so                          QtXml.pyi
Qt.abi3.so                              QtMacExtras.pyi                         QtQuick.abi3.so                         QtTest.pyi                              QtXmlPatterns.abi3.so
Qt5                                     QtMultimedia.abi3.so                    QtQuick.pyi                             QtTextToSpeech.abi3.so                  QtXmlPatterns.pyi
QtBluetooth.abi3.so                     QtMultimedia.pyi                        QtQuick3D.abi3.so                       QtTextToSpeech.pyi                      _QOpenGLFunctions_2_0.abi3.so
QtBluetooth.pyi                         QtMultimediaWidgets.abi3.so             QtQuick3D.pyi                           QtWebChannel.abi3.so                    _QOpenGLFunctions_2_1.abi3.so
QtCore.abi3.so                          QtMultimediaWidgets.pyi                 QtQuickWidgets.abi3.so                  QtWebChannel.pyi                        _QOpenGLFunctions_4_1_Core.abi3.so
QtCore.pyi                              QtNetwork.abi3.so                       QtQuickWidgets.pyi                      QtWebEngine.abi3.so                     __init__.py
QtDBus.abi3.so                          QtNetwork.pyi                           QtRemoteObjects.abi3.so                 QtWebEngine.pyi                         __pycache__
QtDBus.pyi                              QtNfc.abi3.so                           QtRemoteObjects.pyi                     QtWebEngineCore.abi3.so                 bindings
QtDesigner.abi3.so                      QtNfc.pyi                               QtSensors.abi3.so                       QtWebEngineCore.pyi                     py.typed
QtDesigner.pyi                          QtOpenGL.abi3.so                        QtSensors.pyi                           QtWebEngineWidgets.abi3.so              pylupdate.abi3.so
QtGui.abi3.so                           QtOpenGL.pyi                            QtSerialPort.abi3.so                    QtWebEngineWidgets.pyi                  pylupdate_main.py
QtGui.pyi                               QtPositioning.abi3.so                   QtSerialPort.pyi                        QtWebSockets.abi3.so                    pyrcc.abi3.so
QtHelp.abi3.so                          QtPositioning.pyi                       QtSql.abi3.so                           QtWebSockets.pyi                        pyrcc_main.py
QtHelp.pyi                              QtPrintSupport.abi3.so                  QtSql.pyi                               QtWidgets.abi3.so                       sip.cpython-39-darwin.so
QtLocation.abi3.so                      QtPrintSupport.pyi                      QtSvg.abi3.so                           QtWidgets.pyi                           sip.pyi
QtLocation.pyi                          QtQml.abi3.so                           QtSvg.pyi                               QtXml.abi3.so                           uic


 % ls /usr/local/lib/python3.9/site-packages/PyQt5/Qt5 
lib             plugins         qml             qsci            translations
```
