### ISSUE TITLE
Can't run Nuitka on a FIPS-compliant host

### ISSUE THREAD

**Issue by khanfluence** [Nuitka/Nuitka#2422]
I'm unable to use Nuitka on a FIPS-compliant host because the application uses MD5, which is non-compliant.

I generally followed the user manual tutorial, choosing to install with `pip` in a virtual environment:

```shell
> python3 -m venv .venv
> source .venv/bin/activate
> python -m pip install nuitka
> printf 'print("hello")\n' > hello.py
> python -m nuitka hello.py
```

Nuitka version, full Python version, flavor, OS, etc.

```shell
> python -m nuitka --version
1.7.10
Commercial: None
Python: 3.9.13 (main, Jun 15 2022, 11:24:50)
Flavor: Fedora Python
Executable: /tmp/test-nuitka/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Rhel (based on Fedora) 8.7
Version C compiler: /usr/bin/gcc (gcc).
```

Here's the output of `--report`:
```xml
<nuitka-compilation-report nuitka_version="1.7.10" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="ValueError" exception_value="[digital envelope routines: EVP_DigestInit_ex] disabled for FIPS">
Traceback (most recent call last):
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 1109, in main
    _main()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 978, in _main
    result, options = compileTree()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 850, in compileTree
    makeSourceDirectory()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 462, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeGeneration.py", line 578, in generateModuleCode
    return _generateModuleCode(module=module, data_filename=data_filename)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeGeneration.py", line 565, in _generateModuleCode
    return getModuleCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/ModuleCodes.py", line 75, in getModuleCode
    generateStatementSequenceCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeHelpers.py", line 248, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeHelpers.py", line 232, in _generateStatementSequenceCode
    generateStatementsFrameCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/FrameCodes.py", line 86, in generateStatementsFrameCode
    code_identifier = context.getCodeObjectHandle(code_object=code_object)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/Contexts.py", line 331, in getCodeObjectHandle
    self.code_objects[key] = "codeobj_%s" % self._calcHash(key)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/Contexts.py", line 336, in _calcHash
    return getStringHash("-".join(str(s) for s in key))
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/utils/Hashing.py", line 90, in getStringHash
    result = Hash()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/utils/Hashing.py", line 67, in __init__
    self.hash = hashlib.md5()
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
</exception>
  <module name="__main__" kind="PythonMainModule" reason="Root module">
    <optimization-time pass="1" time="0.00" />
    <optimization-time pass="2" time="0.00" />
    <module_usages>
      <module_usage name="site" finding="absolute" line="1" />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="42237952" />
    <memory_usage name="before_c_code_generation" value="42442752" />
  </performance>
  <command_line>
    <option value="--report=nuitka.xml" />
    <option value="--" />
    <option value="hello.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Fedora Python" python_version="3.9.13" os_name="Linux" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}/lib64/python3.9" />
      <path value="${sys.real_prefix}/lib64/python3.9/lib-dynload" />
      <path value="${sys.prefix}/lib64/python3.9/site-packages" />
      <path value="${sys.prefix}/lib/python3.9/site-packages" />
    </search_path>
  </python>
</nuitka-compilation-report>
```

FWIW, I monkey-patched the package's `hashlib.md5()` calls with `usedforsecurity=False` to see if the build would succeed, and it did (not to suggest that as a solution).

**Comment by kayhayen** [comment]
Well, we just want a fast hash, and not too long either there, that option and its availability is something to discover, the argument seems to be available for 3.9 or higher, so we could just use it.

**Comment by kayhayen** [comment]
Stupid question, is this every RHEL out there, I think on OBS things should build fine.

**Comment by kayhayen** [comment]
So, this will go into our `__past__` module, limiting the performance damage to only your kind of system:

```
from hashlib import md5 as _md5
try:
    _md5()
except ValueError:
    def md5(value):
        return _md5(value, usedforsecurity=False)
else:
    md5 = _md5
```

Still need update all uses, going to do that for the next hotfix maybe.

**Comment by khanfluence** [comment]
> Stupid question, is this every RHEL out there, I think on OBS things should build fine.

FIPS mode isn't enabled on every RHEL deployment out there, if that's what you mean. It's the administrator's choice. Unfortunately, I don't administer this host - I just have to use it for work (all of our engineering hosts use FIPS mode).

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening#federal-information-processing-standards-140-and-fips-mode_assembly_installing-the-system-in-fips-mode
> To ensure that your RHEL system generates and uses all cryptographic keys only with FIPS-approved algorithms, you must switch RHEL to FIPS mode.

**Comment by kayhayen** [comment]
Thanks for the information. As you can imagine, this is critical for Nuitka commercial success. I am currently in the midst of a bigger change, expect a fix on factory and hotfix soon though. You may want to consider https://nuitka.net/doc/commercial.html for what seems to be a real competent company use.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
This is going to be in the 1.9 release only, but will hit develop as soon as factory is stabilized.

**Comment by khanfluence** [comment]
The patch fails for two reasons:

**1. The alternate definition requires a positional argument.**

<details>
<summary>Crash report</summary>

```xml
<nuitka-compilation-report nuitka_version="1.9rc1" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="TypeError" exception_value="md5() missing 1 required positional argument: 'value'">
Traceback (most recent call last):
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 1093, in main
    _main()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 962, in _main
    result, options = compileTree()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 836, in compileTree
    makeSourceDirectory()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/MainControl.py", line 437, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeGeneration.py", line 578, in generateModuleCode
    return _generateModuleCode(module=module, data_filename=data_filename)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeGeneration.py", line 565, in _generateModuleCode
    return getModuleCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/ModuleCodes.py", line 74, in getModuleCode
    generateStatementSequenceCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeHelpers.py", line 241, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/CodeHelpers.py", line 225, in _generateStatementSequenceCode
    generateStatementsFrameCode(
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/FrameCodes.py", line 86, in generateStatementsFrameCode
    code_identifier = context.getCodeObjectHandle(code_object=code_object)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/Contexts.py", line 331, in getCodeObjectHandle
    self.code_objects[key] = "codeobj_%s" % self._calcHash(key)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/code_generation/Contexts.py", line 336, in _calcHash
    return getStringHash("-".join(str(s) for s in key))
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/utils/Hashing.py", line 89, in getStringHash
    result = Hash()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/utils/Hashing.py", line 66, in __init__
    self.hash = md5()
TypeError: md5() missing 1 required positional argument: 'value'
</exception>
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="hello.py">
    <optimization-time pass="1" time="0.00" />
    <optimization-time pass="2" time="0.00" />
    <module_usages>
      <module_usage name="site" finding="absolute" line="1" />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="42893312" />
    <memory_usage name="before_c_code_generation" value="43098112" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="hello.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Fedora Python" python_version="3.9.13" os_name="Linux" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}/lib64/python3.9" />
      <path value="${sys.real_prefix}/lib64/python3.9/lib-dynload" />
      <path value="${sys.prefix}/lib64/python3.9/site-packages" />
      <path value="${sys.prefix}/lib/python3.9/site-packages" />
    </search_path>
  </python>
</nuitka-compilation-report>
```
</details>

`hashlib.md5`'s signature is:
```python
>>> inspect.signature(hashlib.md5)
<Signature (string=b'', *, usedforsecurity=True)>
```

A few possible solutions could be:
```python
# Hard-code a compatible signature
def md5(value=b''):
    return _md5(value, usedforsecurity=False)

# Forward positional args
def md5(*args):
    return _md5(*args, usedforsecurity=False)

# Forward all args, override the default for `usedforsecurity`
def md5(*args, **kwargs):
    usedforsecurity = kwargs.pop("usedforsecurity", False)
    return _md5(*args, **kwargs, usedforsecurity=usedforsecurity)
```

**2. SCons uses `hashlib.md5`.**

It didn't initially occur to me that its source is inlined. I blindly changed all calls when experimenting.

```
nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Util.py
1465:        m = hashlib.md5()
1482:        m = hashlib.md5()

nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Tool/msvs.py
90:    m = hashlib.md5()
```

<details>
<summary>Crash report</summary>

```xml
<nuitka-compilation-report nuitka_version="1.9rc1" nuitka_commercial_version="not installed" completion="error exit message (1)" exit_message="">
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="hello.py">
    <optimization-time pass="1" time="0.00" />
    <optimization-time pass="2" time="0.00" />
    <module_usages>
      <module_usage name="site" finding="absolute" line="1" />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="42819584" />
    <memory_usage name="before_c_code_generation" value="43016192" />
    <memory_usage name="before_running_scons" value="44957696" />
  </performance>
  <data_composer blob_size="943" total="97">
    <module_data filename="__bytecode.const" input_size="0" blob_name=".bytecode" blob_size="3" />
    <module_data filename="__constants.const" input_size="1894" blob_name="" blob_size="793" />
    <module_data filename="module.__main__.const" input_size="205" blob_name="__main__" blob_size="107" />
  </data_composer>
  <command_line>
    <option value="--show-scons" />
    <option value="hello.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Fedora Python" python_version="3.9.13" os_name="Linux" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}/lib64/python3.9" />
      <path value="${sys.real_prefix}/lib64/python3.9/lib-dynload" />
      <path value="${sys.prefix}/lib64/python3.9/site-packages" />
      <path value="${sys.prefix}/lib/python3.9/site-packages" />
    </search_path>
  </python>
</nuitka-compilation-report>
```
</details>

<details>
<summary>Output with `--show-scons`</summary>

```
> python -m nuitka --show-scons hello.py
Nuitka-Options:INFO: Used command line options: --show-scons hello.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc1' on Python '3.9' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Scons command: /tmp/test-nuitka/.venv/bin/python -W ignore /tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/bin/scons.py -f /tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/Backend.scons --jobs 48 --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/tmp/test-nuitka/hello source_dir=. nuitka_python=false debug_mode=false python_debug=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.9 nuitka_src=/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build file_reference_mode=original module_count=1 result_exe=/tmp/test-nuitka/hello.bin fedora_python=true python_prefix=/usr no_deployment= show_scons=true target_arch=x86_64
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (8,)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (8,)
Scons: Compiler used /usr/bin/gcc
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: LTO mode auto was resolved to mode: 'no' (not known to be supported).
Nuitka-Scons:INFO: Using C11 mode: True
Nuitka-Scons:INFO: Using resource mode: 'incbin' (default).
Nuitka-Scons:INFO: Told to run compilation on 48 CPUs.
Nuitka-Scons:INFO: Launching Scons target: ['/tmp/test-nuitka/hello.bin']
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [__constants.c] ValueError : [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
scons: internal stack trace:
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 387, in start
    task.prepare()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 191, in prepare
    return SCons.Taskmaster.OutOfDateTask.prepare(self)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 179, in prepare
    self.exception_raise()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 563, in _exception_raise
    exec("raise exc_value.with_traceback(exc_traceback)")
  File "<string>", line 1, in <module>
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 984, in next_task
    task.make_ready()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 328, in make_ready
    SCons.Taskmaster.OutOfDateTask.make_ready(self)
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 435, in make_ready_current
    t.release_target_info()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/FS.py", line 3042, in release_target_info
    self.get_contents_sig()
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/FS.py", line 3639, in get_contents_sig
    result = self.contentsig = SCons.Util.MD5signature(executor.get_contents())
  File "/tmp/test-nuitka/.venv/lib64/python3.9/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Util.py", line 1465, in MD5signature
    m = hashlib.md5()
scons: building terminated because of errors.
```
</details>

**Comment by kayhayen** [comment]
It seems that Nuitka is fine. I am adding monkey patching to the scons launcher for hashlib, to avoid changing scons there.

**Comment by kayhayen** [comment]
So, updated factory, please retry with that.

**Comment by khanfluence** [comment]
It works!

**Comment by kayhayen** [comment]
This is currently on the develop version and will be in 1.9 release

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
