### ISSUE TITLE
CherryPy problem on Redhat (Can't open orphan path)

### ISSUE THREAD

**Issue by fabiochelly** [Nuitka/Nuitka#2441]
I compiled my script with Nuitka on 2 different Linux.
It works fine on Ubuntu but I can't run it on Redhat. I always get this error related to CherryPy:

```
Traceback (most recent call last):
  File "/tmp/onefile_300467_1694708520_212333/single-fra-cherry.py", line 14, in <module>
    import cherrypy
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/tmp/onefile_300467_1694708520_212333/cherrypy/__init__.py", line 66, in <module cherrypy>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/tmp/onefile_300467_1694708520_212333/cherrypy/_cperror.py", line 135, in <module cherrypy._cperror>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/tmp/onefile_300467_1694708520_212333/cherrypy/lib/httputil.py", line 20, in <module cherrypy.lib.httputil>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/tmp/onefile_300467_1694708520_212333/jaraco/collections.py", line 10, in <module jaraco.collections>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/tmp/onefile_300467_1694708520_212333/jaraco/text/__init__.py", line 227, in <module jaraco.text>
  File "/tmp/onefile_300467_1694708520_212333/importlib_resources/abc.py", line 73, in read_text
  File "/tmp/onefile_300467_1694708520_212333/importlib_resources/_adapters.py", line 141, in open
FileNotFoundError: Can't open orphan path
```

I'm using this version on redhat:
```
1.8.1
Commercial: None
Python: 3.6.8 (default, May 31 2023, 10:28:59)
Flavor: Fedora Python
Executable: /bin/python3
OS: Linux
Arch: x86_64
Distribution: Rhel (based on Fedora) 8.8
Version C compiler: /usr/lib64/ccache/gcc (gcc).
```

On Ubuntu where it works fine, the only difference is that is it Python 3.8 and not 3.6. Is it possible that CherryPy can't work with Nuitka on Python 3.6?

And here is my pip freeze (on redhat):

```
Babel==2.5.1
cffi==1.11.5
chardet==3.0.4
cheroot==10.0.0
CherryPy==18.8.0
cloud-init==22.1
configobj==5.0.6
cryptography==3.2.1
dbus-python==1.2.4
decorator==4.2.1
ethtool==0.14
gpg==1.13.1
idna==2.5
importlib-metadata==4.8.3
importlib-resources==5.4.0
iniparse==0.4
isc==2.0
jaraco.classes==3.2.1
jaraco.collections==3.4.0
jaraco.context==4.1.1
jaraco.functools==3.4.0
jaraco.text==3.7.0
Jinja2==2.10.1
jsonpatch==1.21
jsonpointer==1.10
jsonschema==2.6.0
Levenshtein==0.21.1
libcomps==0.1.18
MarkupSafe==0.23
more-itertools==8.14.0
netifaces==0.10.6
nftables==0.1
Nuitka==1.8.1
numpy==1.19.5
oauthlib==2.1.0
orderedset==2.0.3
orjson==3.6.1
pandas==1.1.5
perf==0.1
ply==3.9
portend==3.0.0
prettytable==0.7.2
pyasn1==0.3.7
pycparser==2.14
PyGObject==3.28.3
pyinotify==0.9.6
PyJWT==1.6.1
pyserial==3.1.1
PySocks==1.6.8
python-dateutil==2.8.2
python-dmidecode==3.12.2
python-linux-procfs==0.7.0
pytz==2017.2
pyudev==0.21.0
PyYAML==3.12
rapidfuzz==2.11.1
requests==2.20.0
rpm==4.14.3
selinux==2.9
sepolicy==1.1
setools==4.3.0
six==1.11.0
slip==0.6.4
slip.dbus==0.6.4
subscription-manager==1.28.36
supervisor==4.2.2
syspurpose==1.28.36
systemd-python==234
tempora==4.1.2
typing_extensions==4.1.1
Unidecode==1.3.6
urllib3==1.24.2
WALinuxAgent==2.7.0.6
zc.lockfile==2.0
zipp==3.6.0
zstandard==0.20.0
```

**Comment by kayhayen** [comment]
And this is the point, where I invent a script that exhibits the problem? Without a reproducer, I have to close this sorry.

**Comment by fabiochelly** [comment]
Hi, after installing Python 3.11 on this machine, it finally worked. So the problem was because of Python 3.6

**Comment by kayhayen** [comment]
Not behaving the same as Python is a problem, but I have no trust you had even tried that, and probably lost interest, going to delete the issue.
