### ISSUE TITLE
AssertionError: Lib.site-packages.lightning.app.cli.component-template..github.workflows

### ISSUE THREAD

**Issue by AIforks** [Nuitka/Nuitka#2442]
This error began occurred randomly after I had generated a around 25 tests. 

`AssertionError:`` `Lib.site-packages.lightning.app.cli.component-template..github.workflows`

I believe i exited the last text with clt-c but it could have have been the test prior to that.

I have tried uninstalling and reinstalling both Nuitka and Lightning.

I also tried to installed the 1.7 version of Nuitka to see if it was a version issue, even though the current version was working fine for a week.

additionally, I tried running it in another environment.

`
<nuitka-compilation-report nuitka_version="1.8" nuitka_commercial_version="not installed" completion="exception">
<exception exception_type="AssertionError" exception_value="fsuenv.Lib.site-packages.lightning.app.cli.component-template..github.workflows"> Traceback (most recent call last): File "E:\fsuenv\lib\site-packages\nuitka\MainControl.py", line 1093, in main _main() File "E:\fsuenv\lib\site-packages\nuitka\MainControl.py", line 953, in _main main_module = _createMainModule() File "E:\fsuenv\lib\site-packages\nuitka\MainControl.py", line 161, in _createMainModule main_module = buildMainModuleTree( File "E:\fsuenv\lib\site-packages\nuitka\tree\Building.py", line 1192, in buildMainModuleTree module = buildModule( File "E:\fsuenv\lib\site-packages\nuitka\tree\Building.py", line 1422, in buildModule module = _createModule( File "E:\fsuenv\lib\site-packages\nuitka\tree\Building.py", line 1087, in _createModule mode=decideCompilationMode( File "E:\fsuenv\lib\site-packages\nuitka\tree\Building.py", line 1025, in decideCompilationMode if module_name in detectStdlibAutoInclusionModules(): File "E:\fsuenv\lib\site-packages\nuitka\freezer\ImportDetection.py", line 343, in detectStdlibAutoInclusionModules _stdlib_modules_names = _detectStdlibAutoInclusionModules() File "E:\fsuenv\lib\site-packages\nuitka\freezer\ImportDetection.py", line 268, in _detectStdlibAutoInclusionModules for module_name in scanStandardLibraryPath(stdlib_dir): File "E:\fsuenv\lib\site-packages\nuitka\importing\StandardLibrary.py", line 250, in scanStandardLibraryPath yield ModuleName(import_path + "." + dirname) File "E:\fsuenv\lib\site-packages\nuitka\utils\ModuleNames.py", line 58, in __init__ assert checkModuleName(value), value AssertionError: fsuenv.Lib.site-packages.lightning.app.cli.component-template..github.workflows </exception>
<performance>
<memory_usage name="after_launch" value="35934208"/>
</performance>
<data_composer blob_size="None"/>
<command_line>
<option value="--onefile"/>
<option value="--include-package=kivy.uix"/>
<option value="--include-module=win32timezone"/>
<option value="--plugin-enable=multiprocessing"/>
<option value="MD.py"/>
</command_line>
<plugins>
<plugin name="anti-bloat" user_enabled="no"/>
<plugin name="data-files" user_enabled="no"/>
<plugin name="delvewheel" user_enabled="no"/>
<plugin name="dll-files" user_enabled="no"/>
<plugin name="eventlet" user_enabled="no"/>
<plugin name="gevent" user_enabled="no"/>
<plugin name="gi" user_enabled="no"/>
<plugin name="glfw" user_enabled="no"/>
<plugin name="implicit-imports" user_enabled="no"/>
<plugin name="kivy" user_enabled="no"/>
<plugin name="matplotlib" user_enabled="no"/>
<plugin name="multiprocessing" user_enabled="no"/>
<plugin name="options-nanny" user_enabled="no"/>
<plugin name="pbr-compat" user_enabled="no"/>
<plugin name="pkg-resources" user_enabled="no"/>
<plugin name="pywebview" user_enabled="no"/>
<plugin name="transformers" user_enabled="no"/>
</plugins>
<distributions/>
<python python_exe="${sys.prefix}\Scripts\python.exe" python_flavor="CPython Official" python_version="3.10.11" os_name="Windows" arch_name="x86_64">
<search_path>
<path value="${sys.prefix}\FullSuite\FullSuite"/>
<path value="${sys.prefix}\FullSuite\FullSuite\nuitka\suitediffusion"/>
<path value="${sys.prefix}\Scripts"/>
<path value="E:\MD\MD\mdvenv\Scripts"/>
<path value="E:\fsenv\Scripts"/>
<path value="${sys.real_prefix}\DLLs"/>
<path value="${sys.real_prefix}\lib"/>
<path value="~\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10"/>
<path value="${sys.prefix}"/>
<path value="${sys.prefix}\lib\site-packages"/>
<path value="${sys.prefix}\lib\site-packages\win32"/>
<path value="${sys.prefix}\lib\site-packages\win32\lib"/>
<path value="${sys.prefix}\lib\site-packages\Pythonwin"/>
</search_path>
</python>
</nuitka-compilation-report>uitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).
`

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
