### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by CheshireCC** [Nuitka/Nuitka#2447]
After I compiled my project with nuitka, the following error occurred:

```
Traceback (most recent call last):
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 969, in distribution
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 542, in from_name
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 969, in distribution
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 543, in from_name
SystemError: <built-in method find_distributions of type object at 0x00007FF6369A73A0> returned a result with an exception set

...
(Repetitive content)
...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\fasterwhispergui.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\faster_whisper_GUI\UI_MainWindows.py", line 18, in <module faster_whisper_GUI.UI_MainWindows>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\faster_whisper_GUI\modelLoad.py", line 8, in <module faster_whisper_GUI.modelLoad>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\faster_whisper\__init__.py", line 2, in <module faster_whisper>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\faster_whisper\transcribe.py", line 8, in <module faster_whisper.transcribe>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\ctranslate2\__init__.py", line 53, in <module ctranslate2>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\ctranslate2\converters\__init__.py", line 8, in <module ctranslate2.converters>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\ctranslate2\converters\transformers.py", line 14, in <module ctranslate2.converters.transformers>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\__init__.py", line 26, in <module transformers>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\dependency_versions_check.py", line 16, in <module transformers.dependency_versions_check>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\utils\__init__.py", line 30, in <module transformers.utils>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\utils\generic.py", line 29, in <module transformers.utils.generic>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\utils\import_utils.py", line 34, in <module transformers.utils.import_utils>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\transformers\utils\logging.py", line 35, in <module transformers.utils.logging>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\huggingface_hub\utils\__init__.py", line 44, in <module huggingface_hub.utils>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\huggingface_hub\utils\_headers.py", line 20, in <module huggingface_hub.utils._headers>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\huggingface_hub\utils\_runtime.py", line 68, in <module huggingface_hub.utils._runtime>
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 996, in version
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 969, in distribution
  File "G:\PythonProjectBuild\fatser_whisper_GUI_0917\fasterwhispergui.dist\importlib\metadata\__init__.py", line 543, in from_name
SystemError: <built-in method find_distributions of type object at 0x00007FF6369A73A0> returned a result with an exception set

```

It looks like a bug cased by `transformers`、`huggingface_hub`、`ctranslate2`

My `Nuitka`:
```
nuitka --version
1.7.6
Commercial: None
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\py_workspace\fatser_whsiper_GUI\python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer
Nuitka-Scons:WARNING: for adding it.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

I used the following command:
```
python -m nuitka --mingw --clang --standalone --show-progress --include-package=av,huggingface_hub,faster_whisper,tokenizers,ctranslate2,transformers --plugin-enable=pyside6 --output-dir="G:\PythonProjectBuild\" --windows-uac-admin  fasterwhispergui.py 
```

I also tried `Nuitka` 1.8.1 ,failed too.
I don't know how to fixed this.

**Comment by CheshireCC** [comment]
> I am not too interested in the 1.7 tracebacks, can you provide the 1.8 information?

The same bug `RecursionError: maximum recursion depth exceeded`.
The same error message.

and I tried to add codes:

```
import sys
sys.setrecursionlimit(3000) 
```
but that not work.

I tried to upgrade "importlib-metadata", not work .

**Comment by kayhayen** [comment]
Since this lacks a reproducer, I don't think I can do much about this.

**Comment by CheshireCC** [comment]
> Since this lacks a reproducer, I don't think I can do much about this.因为这张照片没有复制器，我想我也无能为力。

I know ,it's difficult , but all these was cased by the third party package, just like `huggingface_hub`、`transformers` and so on.
So, I don't know what the minimum recurrence code should be like.
I will continue to investigate problem of my code and follow up this issue.

**Comment by kayhayen** [comment]
I am deleting the issue in the meantime, as there are already issues for the others.
