### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend' when using cryptography from Mac M1 arm64 -> x86

### ISSUE THREAD

**Issue by andyfase** [Nuitka/Nuitka#2475]
Before submitting an Issue, please review the
[Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

If you want to post a problem/bug, to help us understand and resolve your issue please check that
you have provided at least the information below, and discard up to here:

**- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.**

```
> python3 -m nuitka --version
1.9rc4
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

**- How did you install Nuitka and Python**

Installed both develop and release versions via pip 

```
pip3 install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
```

**- The specific PyPI names and versions**

```
cryptography==41.0.2
```

**- Also supply a Short, Self Contained, Correct, Example**

test.py
```
import cryptography.exceptions

raise cryptography.exceptions.UnsupportedAlgorithm('foo')
```

**- Provide in your issue the Nuitka options used**

```
python3 -m nuitka --macos-target-arch=x86_64 --macos-signed-app-name=test --output-filename=test --remove-output  --standalone --output-dir=./build/ ./test.py
Nuitka-Options:INFO: Used command line options: --macos-target-arch=x86_64 --macos-signed-app-name=test --output-filename=test --remove-output --standalone --output-dir=./build/ ./test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc4' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 11 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 11
Nuitka:INFO: Removing build directory 'build/test.build'.
Nuitka:INFO: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka:INFO: Successfully created 'build/test.dist/test'.
```

**Produces a build, running said build outputs:** 

```
> ./build/test.dist/
cryptography/ test*
~/.../proserve/scratch/test_nuitka_build> ./build/test.dist/test
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/scratch/test_nuitka_build/build/test.dist/test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/scratch/test_nuitka_build/build/test.dist/cryptography/exceptions.py", line 9, in <module cryptography.exceptions>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
pyo3_runtime.PanicException: Python API call failed
```

**Confirmed `_cffi_backend.c` does not exist** 

```
> ls ./build/test.dist/_cffi_backend.so
ls: ./build/test.dist/_cffi_backend.so: No such file or directory
```

**Running the same build using platform arm64**

```
python3 -m nuitka --macos-target-arch=arm64 --macos-signed-app-name=test  --output-filename=test --remove-output  --standalone --output-dir=./build/ ./test.py
Nuitka-Options:INFO: Used command line options: --macos-target-arch=arm64 --macos-signed-app-name=test --output-filename=test --remove-output --standalone --output-dir=./build/ ./test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc4' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:INFO: Backend linking program with 11 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 11
Nuitka:INFO: Removing build directory 'build/test.build'.
Nuitka:INFO: Created binary that runs on macOS 10.9 (arm64) or higher.
Nuitka:INFO: Successfully created 'build/test.dist/test'.
```

**Correctly produces _cffi_backend.so**

```
ls ./build/test.dist/_cffi_backend.so
./build/test.dist/_cffi_backend.so
```

**and test file works** 

```
> ./build/test.dist/test
Traceback (most recent call last):
  File "/scratch/test_nuitka_build/build/test.dist/test.py", line 4, in <module>
cryptography.exceptions.UnsupportedAlgorithm: foo
```

**Comment by andyfase** [comment]
So just to follow up on this the issue is the installation of the `cryptography` library in general. 

On M1 by default this install we create a arm specific "_cffi_backend.cpython-311-darwin.so" file

```
pip3 install --force-reinstall cryptography
file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so

```
produces 

```
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so: Mach-O 64-bit bundle arm64
```
Nuitka, correctly only includes this in the arm64 build. 

If you can install a x86 version of python you can run 

```
arch -x86_64 /usr/local/bin/pip3 install --force-reinstall cryptography
```

Which then results in 

```
~/.../proserve/watchwood/cli> file /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so: Mach-O 64-bit bundle x86_64
```

using this Nuitka only includes the file in the x86 build - but for whatever reason the arm64 build continues to work even without _cffi_backend.so

**Comment by kayhayen** [comment]
Can you try the current factory version: https://nuitka.net/doc/factory.html as the architecture handling got better there.

**Comment by kayhayen** [comment]
So, I didn't immediately get it, but Nuitka is fully compatible to Python. If you run your example with `arch -x86_64 python` it will behave identical. Nuitka is only going to be able to make things run than already ran.

The `--target-arch` is not a magic cross compile, but a choice, which arch parts to throw away from a universal installation. If that then cannot run, that's tough luck.

From my observation, arches are not properly represented on PyPI for macOS. If you build the wheel yourself, it probably won't build universal. The best I can do is really to point out to the user, that he/she needs to compare and install into the arch Python.

**Comment by kayhayen** [comment]
So, now it says this:

```
Nuitka:INFO: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka:WARNING: It will only work as well as 'arch -x86_64
Nuitka:WARNING: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
Nuitka:WARNING: Mini.py' does.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/macos-cross-compile.html
```

Need to create the page for that mnemonic still and maybe even make it even more alarming, since I believe it will be increasingly unlikely that anything works that way.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.8.4 that I just made.
