### ISSUE TITLE
`os.environ` didn't return unicode after compiled

### ISSUE THREAD

**Issue by T-256** [Nuitka/Nuitka#2479]
Also discussed in https://github.com/pyinstaller/pyinstaller/issues/7989
```

C:\Py37x64>python -m nuitka --mingw64 --standalone app.py
Nuitka-Options:INFO: Used command line options: --mingw64 --standalone app.py
Nuitka:WARNING: On Windows, support for input/output on the console Windows, does not work on non-UTF8 systems, unless
Nuitka:WARNING: Python 3.8 or higher is used but this is 3.7, so please consider upgrading, or disabling the console
Nuitka:WARNING: window for deployment.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/old-python-windows-console.html
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.3' on Python '3.7' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in 'C:\Users\0254~1\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3'.

Fully automatic, cached. Proceed and download? [Yes]/No :
Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3.zip'.
Nuitka:INFO: Extracting to 'C:\Users\0254~1\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe'
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 6 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka will make use of Dependency Walker (https://dependencywalker.com) tool
to analyze the dependencies of Python extension modules.

Is it OK to download and put it in 'C:\Users\0254~1\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64'.

Fully automatic, cached. Proceed and download? [Yes]/No :
Nuitka:INFO: Downloading 'https://dependencywalker.com/depends22_x64.zip'.
Nuitka:INFO: Extracting to 'C:\Users\0254~1\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64\depends.exe'
Nuitka:INFO: Keeping build directory 'app.build'.
Nuitka:INFO: Successfully created 'app.dist\app.exe'.

C:\Py37x64>app.dist\app.exe
appdata = 'C:\\Users\\???\\AppData\\Roaming'
appdata len = 28
appdata encoded = b'C:\\Users\\???\\AppData\\Roaming'
appdata encoded len = 28

sys.flags = sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=1, no_site=1, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0)
sys.getdefaultencoding() = 'utf-8'
sys.getfilesystemencoding() = 'utf-8'
sys.getfilesystemencodeerrors() = 'surrogatepass'

Traceback (most recent call last):
  File "C:\Py37x64\APP~1.DIS\app.py", line 18, in <module>
  File "C:\Py37x64\APP~1.DIS\pathlib.py", line 1166, in resolve
  File "C:\Py37x64\APP~1.DIS\pathlib.py", line 205, in resolve
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\???\\AppData\\Roaming'

C:\Py37x64>python app.py
appdata = 'C:\\Users\\ممد\\AppData\\Roaming'
appdata len = 28
appdata encoded = b'C:\\Users\\\xd9\x85\xd9\x85\xd8\xaf\\AppData\\Roaming'
appdata encoded len = 31

sys.flags = sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0)
sys.getdefaultencoding() = 'utf-8'
sys.getfilesystemencoding() = 'utf-8'
sys.getfilesystemencodeerrors() = 'surrogatepass'

contents of WindowsPath('C:/Users/ممد/AppData/Roaming')
 WindowsPath('C:/Users/ممد/AppData/Roaming/Adobe')
 WindowsPath('C:/Users/ممد/AppData/Roaming/Microsoft')

C:\Py37x64>
```

**Comment by kayhayen** [comment]
Which part of the link in the warning do you not understand?

https://nuitka.net/info/old-python-windows-console.html

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by T-256** [comment]
You can follow the pointed discussed, it is about compile flags issues. I just note that this issue exists on Nuitka and thought it can help to also fix it on its side.
FYI reproduced on py3.8+ with same result as above.

**Comment by kayhayen** [comment]
I am not interested in following other discussions on the hunt for potential problems. I need a reproducer, but you didn't given one. I have clearly stated that one is needed in the template, but you don't read, and I am not going to invent the script that would expose an issue, but much rather wait for somebody with the skills to provide the needed stuff.
