### ISSUE TITLE
[OpenGL]Code with pyqtgraph.opengl Runtime Error After Compile

### ISSUE THREAD

**Issue by tedwgit** [Nuitka/Nuitka#2538]
Similar with issue #2394 (Not the issue in title, but the one posted at bottom after labelled closed).

I used pyqtgraph.opengl to draw some 3D graphics and could successfully compiled the Python code, but got runtime errors.

python -m nuitka --version
1.9rc5 (also tried 1.8.4)
Commercial: None
Python: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Miniconda3\envs\isp64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).

**Nuitka Install & Version:**
1.9rc5: python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"

**Code Example:**
My project contains many irrelevant files thus no need to paste them here, it's very easy to reproduce this issue, just use below code is enough:

import numpy as np
import pyqtgraph.opengl as gl

class HSVViewer(gl.GLViewWidget):
    def __init__(self, parent=None):
        gl.GLViewWidget.__init__(self, parent)
        ax = gl.GLAxisItem()
        ax.setSize(1.1, 1.1, 1.1)
        self.addItem(ax)

# Create any main function to use above class.

**Compile cmd:**
python -m nuitka --standalone --plugin-enable=pyqt6 --output-dir=out test.py

**Error log:**
Unable to import OpenGL.platform.win32.Win32Platform: cannot import name 'util' from 'ctypes' (D:\Src\test\out\MIVISI~1.DIS\ctypes\__init__.py)
Traceback (most recent call last):
  File "D:\Src\test\out\MIVISI~1.DIS\GuiLayer\lut3d\gamut_mapping_tab.py", line 8, in <module GuiLayer.lut3d.gamut_mapping_tab>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\test\out\MIVISI~1.DIS\pyqtgraph\__init__.py", line 281, in <module pyqtgraph>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\test\out\MIVISI~1.DIS\pyqtgraph\widgets\RawImageWidget.py", line 13, in <module pyqtgraph.widgets.RawImageWidget>
  File "D:\Src\test\out\MiVision.dist\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\Src\test\out\MiVision.dist\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\Src\test\out\MiVision.dist\OpenGL\platform\__init__.py", line 56, in <module>
    _load()
  File "D:\Src\test\out\MiVision.dist\OpenGL\platform\__init__.py", line 50, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable

**Comment by Rayterex** [comment]
Getting the similar error with Python 3.11.5, PySide6 and PyOpenGL in other project with this command:
 ```
Command is: Nuitka-Options:INFO: Used command line options: --windows-company-name="3Vial Technologies" --windows-product-name="3Vial OS" --windows-product-version=0.1 --windows-file-description="3Vial Operating System" --msvc=latest --jobs=16 --standalone --onefile --follow-imports --enable-plugin=pyside6 --include-plugin-directory=pg_tools --include-data-dir=pg_assets=pg_assets --windows-icon-from-ico=pg_assets/pg_ico/trivial.ico --remove-output "3Vial OS.py"
```
```
Unable to import OpenGL.platform.win32.Win32Platform: cannot import name 'util' from 'ctypes' (C:\Users\neman\AppData\Local\Temp\ONEFIL~1\ctypes\__init__.py)
Traceback (most recent call last):
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\3Vial OS.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_trivial_os\pg_ui\pg_app.py", line 5, in <module pg_trivial_os.pg_ui.pg_app>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_trivial_os\pg_ui\pg_gui.py", line 2, in <module pg_trivial_os.pg_ui.pg_gui>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_trivial_os\pg_ui\pg_tool_display.py", line 5, in <module pg_trivial_os.pg_ui.pg_tool_display>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_tools\trivial_engine.py", line 6, in <module pg_tools.trivial_engine>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_tools\pg_trivial_engine\pg_ui\pg_node_editor\pg_node_editor.py", line 4, in <module pg_tools.pg_trivial_engine.pg_ui.pg_node_editor.pg_node_editor>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_tools\pg_trivial_engine\pg_ui\pg_node_editor\pg_nodes_menu.py", line 5, in <module pg_tools.pg_trivial_engine.pg_ui.pg_node_editor.pg_nodes_menu>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_tools\pg_trivial_engine\pg_ui\pg_gui.py", line 6, in <module pg_tools.pg_trivial_engine.pg_ui.pg_gui>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\pg_tools\pg_trivial_engine\pg_ui\pg_node_editor\pg_view_3d.py", line 6, in <module pg_tools.pg_trivial_engine.pg_ui.pg_node_editor.pg_view_3d>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\OpenGL\GL\__init__.py", line 3, in <module OpenGL.GL>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\OpenGL\error.py", line 12, in <module OpenGL.error>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\OpenGL\platform\__init__.py", line 56, in <module OpenGL.platform>
  File "C:\Users\neman\AppData\Local\Temp\ONEFIL~1\OpenGL\platform\__init__.py", line 50, in _load
TypeError: 'NoneType' object is not callable
```

**Comment by kayhayen** [comment]
This `ctypes.util` issue seems bad, going to have a look.

**Comment by kayhayen** [comment]
Didn't see `pyqtgraph.util.numba_helper` before, doing anti-bloat to remove `numba` there to make it a leaner compile.

**Comment by kayhayen** [comment]
Your example doesn't reproduce anything for me, which of course aligns with the stack trace not being from your example code obviously.

**Comment by tedwgit** [comment]
> Your example doesn't reproduce anything for me, which of course aligns with the stack trace not being from your example code obviously.

Yes it's not from my code because they are copied them from pieces of notes just tried to make an example, as I didn't have the environment when writing this ticket. I'll update the example code and corresponding logs, thank you for the reply.

**Comment by tedwgit** [comment]
> > Your example doesn't reproduce anything for me, which of course aligns with the stack trace not being from your example code obviously.
> 
> Yes it's not from my code because they were copied from pieces of notes just tried to make an example, as I didn't have the environment when writing this ticket. I'll update the example code and corresponding logs, thank you for the reply.

# Update Example & Logs
# Example
```
import numpy as np
import pyqtgraph.opengl as gl
from PyQt6.QtWidgets import QApplication, QVBoxLayout, QMainWindow, QWidget
import sys

class TestWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setGeometry(300, 300, 500, 350)
        self.D3wid = gl.GLViewWidget()
        centralWidget = QWidget()
        main_layout = QVBoxLayout()
        main_layout.addWidget(self.D3wid)
        centralWidget.setLayout(main_layout)
        self.setCentralWidget(centralWidget)
        self.shape_3d_map()

    def shape_3d_map(self):
        x_mat = np.linspace(-10, 10, 21)
        y_mat = np.linspace(0, 10, 11)
        z_mat = np.random.rand(len(x_mat), len(y_mat)) * 10 - 5
        self.D3 = gl.GLSurfacePlotItem(x_mat, y_mat, z_mat, shader='normalColor', color=(0.2, 0.2, 0.8, 0.8))
        self.D3wid.addItem(self.D3)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    qb = TestWindow()
    qb.show()
    sys.exit(app.exec())
```

# Log
D:\Src\OGL_Nuitka_Test\out\OGLNuitkaTest.dist>OGLNuitkaTest.exe
Unable to import OpenGL.platform.win32.Win32Platform: cannot import name 'util' from 'ctypes' (D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\ctypes\__init__.py)
Traceback (most recent call last):
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\OGLNuitkaTest.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\pyqtgraph\__init__.py", line 281, in <module pyqtgraph>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\pyqtgraph\widgets\RawImageWidget.py", line 13, in <module pyqtgraph.widgets.RawImageWidget>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\OpenGL\GL\__init__.py", line 3, in <module OpenGL.GL>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\OpenGL\error.py", line 12, in <module OpenGL.error>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\OpenGL\platform\__init__.py", line 56, in <module OpenGL.platform>
  File "D:\Src\OGL_NU~1\out\OGLNUI~1.DIS\OpenGL\platform\__init__.py", line 50, in _load
TypeError: 'NoneType' object is not callable

**Comment by kayhayen** [comment]
I changed the plugin, and now it works very well. You might want to try staging, but honestly, I cannot explain why it happened, but the standalone improvements for Linux specifically for PyPI and Anaconda packages should not make it work. If this is Anaconda only, that would be bad, but an option. Can you provide a `--report=compilation-report.xml` output from the factory branch, it should allow me to reproduce from the report your Anaconda environment used.

**Comment by tedwgit** [comment]
> I changed the plugin, and now it works very well. You might want to try staging, but honestly, I cannot explain why it happened, but the standalone improvements for Linux specifically for PyPI and Anaconda packages should not make it work. If this is Anaconda only, that would be bad, but an option. Can you provide a `--report=compilation-report.xml` output from the factory branch, it should allow me to reproduce from the report your Anaconda environment used.

No problem, attach is the compilation-report.xml: 
[compilation-report.zip](https://github.com/Nuitka/Nuitka/files/13372547/compilation-report.zip)

However, it's weird because similar error still exists when I tried it in native Python instead of Anaconda, here is the version info under native Python (python -m nuitka --version):
```
D:\Src\OGL_Nuitka_Test\out\OGLNuitkaTest.dist>python -m nuitka --version
1.8.6
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).
```

BTW, how to try staging or plugin as you mentioned in "I changed the plugin, and now it works very well. You might want to try staging"?

**Comment by kayhayen** [comment]
So, I think I finally made some progress, kind of hard to believe, but maybe `from` imports are somewhat broken, at least in ctypesloader, this code if ran isolated, doesn't lead to usage of the from imported module.

`from ctypes import util`

I have no clue why on my side it doesn't show up in the result. Maybe something else being different, but that is not nearly correct, and also very surprising, I am so sure I would know if this was a general problem (from imports of packages not working), lets see what turns out to be cause.

**Comment by kayhayen** [comment]
Oh my, good old habit of mine, documenting my bugs with TODOs ahead of time.

```
                    # TODO: Should add this, such that these imports are
                    # properly resolved: pylint: disable=condition-evals-to-constant

                    if self.is_package and False:
```

The attribute lookup of what are "hard" modules is not going to resolved to the import, as it should be, but remains as a kind of attribute lookup only. Hard modules are used for highly optimized modules in Nuitka, mostly from stdlib, but recently also for some things that are lazy loading. I need to check what it entails to implement this TODO item.

**Comment by tedwgit** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Staging is factory for commercial users, I miswrote there. It not working with CPython for you is very strange. Maybe you got something in your project, I will check your report.

Factory branch 1.9rc8 works, thank you very much!

**Comment by tedwgit** [comment]
> Oh my, good old habit of mine, documenting my bugs with TODOs ahead of time.
> 
> ```
>                     # TODO: Should add this, such that these imports are
>                     # properly resolved: pylint: disable=condition-evals-to-constant
> 
>                     if self.is_package and False:
> ```
> 
> The attribute lookup of what are "hard" modules is not going to resolved to the import, as it should be, but remains as a kind of attribute lookup only. Hard modules are used for highly optimized modules in Nuitka, mostly from stdlib, but recently also for some things that are lazy loading. I need to check what it entails to implement this TODO item.

I wish I could have the same good habit :)

**Comment by kayhayen** [comment]
It's a good habit. Every time I write something that I know will not be fully adequate, I comment it with a TODO item. I am just bad at resolving them later without a reason to do it.

**Comment by kayhayen** [comment]
There was a bunch of fallback from enabling this, but it should be sorted out, and is part of the 1.9 release.
