### ISSUE TITLE
AttributeError: 'nuitka_resource_reader_files' object has no attribute 'as_posix'

### ISSUE THREAD

**Issue by es617** [Nuitka/Nuitka#2540]
Hello,

when importing the `gradio` library in my code, the executable is created, but I get the following error when trying to run it

```
 Traceback (most recent call last):
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/main2.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/__init__.py", line 3, in <module gradio>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/_simple_templates/__init__.py", line 1, in <module gradio._simple_templates>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/_simple_templates/simpledropdown.py", line 6, in <module gradio._simple_templates.simpledropdown>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/components/__init__.py", line 1, in <module gradio.components>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/components/annotated_image.py", line 12, in <module gradio.components.annotated_image>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/components/base.py", line 23, in <module gradio.components.base>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/blocks.py", line 27, in <module gradio.blocks>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/networking.py", line 20, in <module gradio.networking>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio/routes.py", line 78, in <module gradio.routes>
AttributeError: 'nuitka_resource_reader_files' object has no attribute 'as_posix'
```

Here is the line of code
STATIC_TEMPLATE_LIB = files("gradio").joinpath("templates").as_posix()  # type: ignore
https://github.com/gradio-app/gradio/blob/4d3aad33a0b66639dbbb2928f305a79fb7789b2d/gradio/routes.py#L79

This is the script (main2.py):
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

if __name__ == "__main__":
    demo.launch(show_api=False)
```

This is the command I used:
```
/opt/homebrew/bin/python3 -m nuitka --static-libpython=no  --follow-imports --include-data-dir=./gradio_test/data=data --noinclude-setuptools-mode=nofollow --standalone --macos-create-app-bundle --include-module=huggingface_hub --include-module=gradio_client --include-module=pydantic.root_model --clang gradio_test/main2.py
```

Here is the version I am using
```
1.8.5
Commercial: None
Python: 3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Flavor: Homebrew Python
Executable: /opt/homebrew/Cellar/python@3.11/3.11.6_1/bin/python3.11
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

I installed python using homebrew, and nuitka using pip. I did not use a virtual env.

Here is the output of pip freeze:
```
aiofiles==23.2.1
altair==5.1.2
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
bottle==0.12.25
certifi==2023.7.22
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
fastapi==0.104.1
ffmpy==0.3.1
filelock==3.13.1
fonttools==4.44.0
fsspec==2023.10.0
gradio==4.1.2
gradio_client==0.7.0
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
huggingface==0.0.1
huggingface-hub==0.19.0
idna==3.4
importlib-resources==6.1.1
Jinja2==3.1.2
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.1
mdurl==0.1.2
Nuitka==1.8.5
numpy==1.26.1
ordered-set==4.1.0
orjson==3.9.10
packaging==23.2
pandas==2.1.2
Pillow==10.1.0
proxy-tools==0.1.0
pydantic==2.4.2
pydantic_core==2.10.1
pydub==0.25.1
Pygments==2.16.1
pyobjc-core==10.0
pyobjc-framework-Cocoa==10.0
pyobjc-framework-Security==10.0
pyobjc-framework-WebKit==10.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3.post1
pywebview==4.4.1
PyYAML==6.0.1
referencing==0.30.2
requests==2.31.0
rich==13.6.0
rpds-py==0.12.0
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
tomlkit==0.12.0
toolz==0.12.0
tqdm==4.66.1
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
uvicorn==0.24.0.post1
websockets==11.0.3
zstandard==0.22.0
```

Note that I get the same outcome if I use pyenv with no virtual environment, or pyenv via poetry. 
When using pyenv, I got this error right away. When using Homebrew python, I had some initial "file not found" and "module not found"  errors, which I addressed by explicitly including some gradio-related modules (--include-module=huggingface_hub --include-module=gradio_client --include-module=pydantic.root_model) and manually copying some gradio files ([types.json](https://github.com/gradio-app/gradio/blob/main/client/python/gradio_client/types.json), to be specific).

Also note that things run well if I don't use --standalone, the executable works
```
/opt/homebrew/bin/python3 -m nuitka --static-libpython=no --include-data-dir=./gradio_test/data=data --noinclude-setuptools-mode=nofollow --clang gradio_test/main2.py
```

Thank you!

**Comment by kayhayen** [comment]
I tried this on Windows first, and encountered a few issues, these includes for `pydantic` and `huggingface_hub` ought to be no longer needed on develop and coming 1.9 already, I failed to reproduce the issue though, probably the `as_posix` issue is specific to it. I also did a bunch of anti-bloat work in order to avoid IPython inclusion, but not sure if it's complete yet.

**Comment by es617** [comment]
Thanks for looking into this @kayhayen - much appreciated!

Curious, did you encounter the following errors in your test?
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/first.lastname/Projects/gradio_test/main2.app/Contents/MacOS/gradio_client/types.json'
```

I had to manually copy this file ([types.json](https://github.com/gradio-app/gradio/blob/main/client/python/gradio_client/types.json)) in the path above to make it work. It seems like using `--include-package-data=gradio_client` does the trick too. Is it expected to have to explicitly do that?


On the "as_posix", could clarify what you meant with :
> probably the as_posix issue is specific to it. 

Thank you!

**Comment by kayhayen** [comment]
So, I think I was running it with my internal version just now. Needs a bunch of anti-bloat against IPython, and in fact that's not yet finished entirely yet. I added datafiles to be automatic, and a workaround of it querying the source code of itself for an automatic update of the .pyi file each time people use the package, really nice.

But with that it should work. I was doing this on macOS now, but with 3.9 first, just because it happens to be my Python3, going to try 3.11 after that as well.

**Comment by es617** [comment]
That sounds great! I'd love to try it on my end - will this require a new nuitka release?

**Comment by kayhayen** [comment]
Yes, it does, I am not going to do hotfixes for 1.8 anymore, so it's going to be in 1.9 only, but I will put it on factory branch and tell you when it should work for you.

**Comment by kayhayen** [comment]
So, I got it to run with data files added, anti-bloat and workaround added, but I think something internally is not working, which ideally you would know how to debug, the web interface doesn't respond. I am not familiar with it, and didn't immediately see where the error traces are activated with `gradio`. Anyway, that was with 3.9 on macOS, now trying 3.11 on macOS to see if I get your error there. These metadata files interactions are highly version specific, so no surprise in not seeing it with 3.9, they add/change/start to use things there all the time.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

Also, if you figure out why gradle is not doing what the demo is supposed to do, let me know, might just be missing more files, which arguable for a demo wouldn't have to be default, but the "as_posix()" is now added and works on all OSes properly. I am going to close this issue at 1.9 release.

**Comment by es617** [comment]
One more question here, regarding the anti-bloat you mentioned above, is this something that is done in the background or do I need to explicitly add a flag in the command?

**Comment by kayhayen** [comment]
It's all automatic, if you wanted to use e.g. IPython on your program, you would have to allow it excplitely, but it would then tell you that once it sees its usage. You probably saw those warnings before, but ignored them. They should no longer happen with these packages now.

**Comment by es617** [comment]
Thank you, it all makes sense! This issue is good to be closed from my end. Thanks again for your help!
