### ISSUE TITLE
FATAL: options-nanny: Plugin issue while working on 'module 'trio._core._ki''

### ISSUE THREAD

**Issue by Nnamdi-Ike** [Nuitka/Nuitka#2550]
I have been unable to resolve this issue. My hello world examples work, not working for my program. It is not large but does use PySide2, and tkinter which may make this more complex than most. 

**The Issue I am having**
Doesnt seem to like some module " 'trio._core._ki'' cant find information on this online

```
(Alpha) C:\Users\Me\PycharmProjects\Alpha production>python -m nuitka --follow-imports main.py
Nuitka-Options:INFO: Used command line options: --follow-imports main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.6' on Python '3.8' commercial grade 'not installed'.
PASS 1: 99.2%|████████████████████████▊| 5606/5654, trio._core._ki       Traceback (most recent call last):
  File "C:\Users\Me\\anaconda3\envs\Alpha\lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\Users\Me\\anaconda3\envs\Alpha\lib\site-packages\nuitka\plugins\Plugins.py", line 536, in considerImplicitImports
    cls._considerImplicitImports(plugin=plugin, module=module)
  File "C:\Users\Me\\anaconda3\envs\Alpha\lib\site-packages\nuitka\plugins\Plugins.py", line 428, in _considerImplicitImports
    for full_name in iterateModuleNames(plugin.getImplicitImports(module)):
  File "C:\Users\Me\\anaconda3\envs\Alpha\lib\site-packages\nuitka\plugins\standard\OptionsNannyPlugin.py", line 159, in getImplicitImports
    self._checkSupportedVersion(
  File "C:\Users\Me\\anaconda3\envs\Alpha\lib\site-packages\nuitka\plugins\standard\OptionsNannyPlugin.py", line 71, in _checkSupportedVersion
    ".".join(str(d) for d in self.getPackageVersion(full_name)),
TypeError: 'NoneType' object is not iterable
FATAL: options-nanny: Plugin issue while working on 'module 'trio._core._ki''. Please report the bug with the above traceback included.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

**Current Version and Environment**

```
1.8.6
Commercial: None
Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Me\anaconda3\envs\Alpha\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**- How did you install Nuitka and Python**

Running pyrhon 3.8 using anaconda, Nuitka 1.8.6 installed using Conda.

  

**- The specific PyPI names and versions**

```
aiohttp                        3.8.2
alpaca-trade-api         3.0.2                  
appdirs                       1.4.4                  
attrs                            23.1.0                 
backtesting                 0.3.3                    
blas                      1.0 
bokeh                     3.1.1
cryptography              41.0.3         
cycler                    0.11.0       
deprecation               2.1.0                
freetype                  2.12.1         
frozendict                2.3.8                
jmetalpy                  1.5.5               
matplotlib                3.1.3           
matplotlib-base           3.1.3          
multitasking              0.0.11               
nuitka                    1.8.6           
numpy                     1.21.5           
numpy-base                1.21.5          
ordered-set               4.1.0             
packaging                 23.1            
pandas                    2.0.3                
pillow                    10.1.0                  
pip                       23.3          
plotly                    5.18.0                
ply                       3.11                  
pthread-stubs             0.3                  
pycparser                 2.21                
pyopenssl                 23.2.0           
pyparsing                 3.0.9          
pyqt                      5.15.10          
pyqt5-sip                 12.13.0           
pyside2                   5.15.8           
python                    3.8.18              
qt-main                   5.15.8               
requests                  2.31.0            
scipy                     1.10.1                  
setuptools                68.0.0            
sip                       6.7.12            
six                       1.16.0              
soupsieve                 2.5                       
sqlite                    3.41.2               
statsmodels               0.14.0                    
stripe                    2.49.0              
ta-lib                    0.4.19          
tk                        8.6.12               
webencodings              0.5.1                    
websocket-client          1.6.4                  
websockets                10.4                   
wheel                     0.41.2       
```   

**- Many times when you get an error from Nuitka, your setup may be special**

Happens every time for various options. Hello work with tikinter worked flawlessly (reported as virus though)

**- Provide in your issue the Nuitka options used**
I have tried these three independently 
--follow-imports
--standalone
--onefile

**Any help is appreciated!**

**Comment by Nnamdi-Ike** [comment]
Sorry, took a while to run this. Seems like the issue has been resolved. Now I am facing a PySide2 Issue. 

**Command Line Options**
nuitka main.py --standalone --show-progress --enable-plugin=tk-inter --disable-console --enable-plugin=pyside2

**Error Message**
```
Nuitka-Plugins:WARNING: pyside2: Unwanted import of 'tkinter' that is redundant with 'PySide2' encountered. Use '--nofollow-import-to=tkinter' or uninstall it for best compatibility with pure Python execution.
.
.
.
Nuitka-Plugins:INFO: data-files: Included data file 'pandas\io\formats\templates\string.tpl' due to package data directory 'templates' for 'pandas.io.formats'.
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:INFO: tk-inter: Included 830 data files due to Tcl needed for tkinter usage.
Nuitka-Plugins:INFO: pyside2: Including Qt plugins 'iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,styles' below 'PySide2\qt-plugins'.
Nuitka-Plugins:INFO: dll-files: Found 30 files DLLs from numpy installation.
Nuitka-Inclusion:INFO: Analyzing dependencies of 'main.dist\main.exe'.
Nuitka:INFO: Running 'depends.exe' for main.dist\main.exe took 1.61 seconds
Nuitka:INFO: Running 'depends.exe' for C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\PIL\_imaging.cp38-win_amd64.pyd took 0.01 seconds
Nuitka:INFO: Running 'depends.exe' for C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\PIL\_imagingcms.cp38-win_amd64.pyd took 0.01 seconds
Nuitka:INFO: Running 'depends.exe' for C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\PIL\_webp.cp38-win_amd64.pyd took 0.01 seconds
Nuitka:INFO: Running 'depends.exe' for C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\PySide2\QtCore.cp38-win_amd64.pyd took 0.02 seconds
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Detecting used DLLs: 1.7%|▍                        | 5/301, PySide2\QtCore.pydTraceback (most recent call last):
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\__main__.py", line 163, in <module>
    main()
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\__main__.py", line 149, in main
    MainControl.main()
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\MainControl.py", line 1123, in main
    _main()
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\MainControl.py", line 1015, in _main
    detectUsedDLLs(
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\freezer\Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\freezer\Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\plugins\Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 418, in decideAllowOutsideDependencies
    if not isDistributionSystemPackage(getDistributionName(distribution)):
  File "C:\Users\Me\anaconda3\envs\alpha\lib\site-packages\nuitka\utils\Distributions.py", line 230, in isDistributionSystemPackage
    assert isLinux(), (
AssertionError: ('PySide2', 'Unknown')
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```
**Thank you for the quick response!**
