### ISSUE TITLE
python3.11.6+playwright1.39.0+windows11x64+nuitka1.8.6  BUG

### ISSUE THREAD

**Issue by xingzheseo** [Nuitka/Nuitka#2551]
Task exception was never retrieved
future: <Task finished name='Task-189' coro=<Connection.run() done, defined at D:\py_tools\sg\years\testm.dist\playwright\_impl\_connection.py:264> exception=KeyError('deviceDescriptors')>
Traceback (most recent call last):
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_connection.py", line 273, in run
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_transport.py", line 163, in run
    self.on_message(obj)
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_connection.py", line 232, in <lambda>
    super().__init__()
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_connection.py", line 386, in dispatch
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_connection.py", line 435, in _create_remote_object
    print("Error occurred in event listener", file=sys.stderr)
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_object_factory.py", line 81, in create_remote_object
    if type == "Response":
  File "D:\py_tools\sg\years\testm.dist\playwright\_impl\_playwright.py", line 52, in __init__
    def __getitem__(self, value: str) -> "BrowserType":
KeyError: 'deviceDescriptors'

**Comment by xingzheseo** [comment]
C:\Users\Administrator>nuitka --version
1.8.6
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

**Comment by kayhayen** [comment]
I definitely need a minimal reproducer or else this is not usable information.

**Comment by KevinRodriguez777** [comment]
i have encountered this error before, this is an issue with playwright and not nuitka, you should open a bug report in the playwright repo.

**Comment by kayhayen** [comment]
See #1029 for support of playwright.
