### ISSUE TITLE
trouble compiling with --include-distribution-metadata=scipy and without --include-distribution-metadata=scipy

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2557]
@kayhayen 
Same Issue here except for Scipy
https://github.com/Nuitka/Nuitka/issues/2549#issue-1993814603

When not compiling with --include-distribution-metadata=scipy
it complains when you run the executable

When compiling with --include-distribution-metadata=scipy
Nuitka-Inclusion:INFO: Cannot compile module 'sympy.polys.numberfields.resolvent_lookup' because its code is too complex, included as bytecode.
FATAL: Error, including metadata for distribution 'scipy' without including related package 'scipy-1.11.3-cp310-cp310-win_amd64.whl'.

sample code
```
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer, TextStreamer
## loop over numbers from 1 to 10

def main():
    quant_path = r"C:\Users\Tensor\Desktop\jsonformertest\OpenHermes-2-Mistral-7B-AWQ"
    quant_file = r"model.safetensors"

    # Load model
    model = AutoAWQForCausalLM.from_quantized(quant_path, quant_file, fuse_layers=True)
    tokenizer = AutoTokenizer.from_pretrained(quant_path, trust_remote_code=True)
    streamer = TextStreamer(tokenizer, skip_special_tokens=True)

    # Convert prompt to tokens
    prompt_template = """\
    A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

    USER: {prompt}
    ASSISTANT:"""

    tokens = tokenizer(
        prompt_template.format(prompt="How are you today?"), 
        return_tensors='pt'
    ).input_ids.cuda()

    # Generate output
    generation_output = model.generate(
        tokens, 
        streamer=streamer,
        max_new_tokens=512
    )

main()
```

Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\jsonformertest\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe (cl 14.3).

installed pip3 cloning the latest develop  a577a77ba04dda360e5dec35c4bd4f2432549fe5

- Note if this is a regression
seems to be!

[report.txt](https://github.com/Nuitka/Nuitka/files/13401537/report.txt)
ression.

thanks again! I am trying to really get this compiled haha, it seems to be fighting me hard, and blocking me from updating any python packages

**Comment by kayhayen** [comment]
I have maybe encountered this myself in Nuitka-Watch I believe, there it showed in not detecting the package name for a one module only package, `threadpoolctl`, but I didn't even come close to see the issue with my many scipy uses, the name complained about should come from the `RECORD` file, but this `.whl` filename makes no sense I guess, not sure where that could be coming from at all, maybe it's something new, I will try and update PyPI for Nuitka-Watch once I think I have 1.9 release ready, maybe it's a new scipy thing.

**Comment by kayhayen** [comment]
Can you retry with current factory, and if it happens, identify the metadata of your scipy installation, and post it here, should be in site-packages folder and match`scipy*dist-info`

**Comment by ArEnSc** [comment]
ok!

**Comment by ArEnSc** [comment]
So it compiles now but this is the problem, also didn't require peft metadata or safetensors metadata oddly. Heres the output sadly
```
(.venv) PS C:\Users\Tensor\Desktop\awqprototype\main.dist> .\main.exe
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 23, in get_source_lines_and_file
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\inspect.py", line 1129, in getsourcelines
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\inspect.py", line 958, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\__init__.py", line 2, in <module awq>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\models\__init__.py", line 7, in <module awq.models>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\models\gpt_bigcode.py", line 2, in <module awq.models.gpt_bigcode>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\transformers\models\gpt_bigcode\modeling_gpt_bigcode.py", line 55, in <module transformers.models.gpt_bigcode.modeling_gpt_bigcode>
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\jit\_script.py", line 1338, in script
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\jit\frontend.py", line 262, in get_jit_def
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 120, in parse_def
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 32, in get_source_lines_and_file
OSError: Can't get source for <compiled_function upcast_masked_softmax at 0x0000024436A966B0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
```
this was using latest factory I feel we are pretty close!

**Comment by kayhayen** [comment]
This might be duplicate and I do not accept new issues under solved issues.
