### ISSUE TITLE
ValueError: DelphiFMX module not found

### ISSUE THREAD

**Issue by itcd** [Nuitka/Nuitka#2566]
I am encountering difficulties when attempting to run my DelphiFMX GUI program, which was compiled with Nuitka 1.9rc10 on Python 3.11.

The program was compiled with Nuitka using the --standalone option, but the "ValueError: DelphiFMX module not found" error occurred when running the program.

The command used to compile the program was:
python -m nuitka --standalone Project3.py

When attempting to run the compiled Project3.exe, an error occurred stating "ValueError: DelphiFMX module not found".

C:\d4p\b>Project3.exe
Traceback (most recent call last):
  File "C:\d4p\b\Project3.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\d4p\b\delphifmx\__init__.py", line 96, in <module delphifmx>
  File "C:\d4p\b\delphifmx\__init__.py", line 81, in new_import
  File "C:\d4p\b\delphifmx\__init__.py", line 59, in find_extension_module
ValueError: DelphiFMX module not found.             Try to reinstall the delphifmx package or check for support compatibility.

Screenshot
![DelphiFMX](https://github.com/Nuitka/Nuitka/assets/753851/f7f2276e-816f-4e5a-8174-1eee6eb8c73b)

Source code
[Project3.zip](https://github.com/Nuitka/Nuitka/files/13439289/Project3.zip)

**Comment by kayhayen** [comment]
Seems like an implicit dependency, the example seems good. Please avoid screenshots, they hurt my eyes.

**Comment by shenjackyuanjie** [comment]
```
ValueError: DelphiFMX module not found.Try to reinstall thedelphifmx package or check for support compatibility.
```

**Comment by kayhayen** [comment]
I wonder if this is related to Delphi, a RAD tool I used last century?

**Comment by kayhayen** [comment]
I have added the DLLs and encountered a `SystemError` because the data file `.pyfmx` was not included, very ugly by upstream, please poke them to handle file not found more elegantly, or maybe I was blind. I will have a fix for you shortly.

**Comment by kayhayen** [comment]
So, on factory there is a change that will make it work on Windows. I still need to add Linux and macOS, but for that I need to find the chance, and also think of a way how to e.g. put test cases in Nuitka-Watch (our monitoring tool) that are to be executed randomly and not regularily, and might need fixes, as that would make it easier to queue these things.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by itcd** [comment]
> So, on factory there is a change that will make it work on Windows. I still need to add Linux and macOS, but for that I need to find the chance, and also think of a way how to e.g. put test cases in Nuitka-Watch (our monitoring tool) that are to be executed randomly and not regularily, and might need fixes, as that would make it easier to queue these things.
> 
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

This is working on Windows. Thank you for resolving the issue.

I have installed the factory branch:
python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"

And compiled the program with the .pyfmx files included:
python -m nuitka --standalone --include-data-files=*.pyfmx=. Project3.py

**Comment by itcd** [comment]
> Seems like an implicit dependency, the example seems good. Please avoid screenshots, they hurt my eyes.

Apologies for the screenshot of error messages. I have removed it as they are already described in the text.

**Comment by itcd** [comment]
> I wonder if this is related to Delphi, a RAD tool I used last century?

Delphi FMX is a cross-platform GUI framework, similar to Qt.
UI forms can be exported as .pyfmx files from Delphi, which is the RAD tool you mentioned.

**Comment by kayhayen** [comment]
Changing to 1.9 milestone, I will add it for 1.9.1 release for all platforms, it might be that "android" is not yet testable in the yaml config, will need to add that to the plugin code, but that's fine for a hotfix.

**Comment by kayhayen** [comment]
So, the Windows part is in 1.9.1 now, but the Linux and macOS I didn't yet do.

**Comment by kayhayen** [comment]
This is coming for 1.9.2, and currently it is on factory now, also including Android, but I don't test that one.
