### ISSUE TITLE
AssertionError with --standalone & pydantic

### ISSUE THREAD

**Issue by John-Colvin** [Nuitka/Nuitka#2571]
See test below with `develop`, but I get the same error with 1.9

```
john@Johns-MacBook-Pro pydantic_test % ls -a
.       ..      main.py

john@Johns-MacBook-Pro pydantic_test % cat main.py
from pydantic import BaseModel

john@Johns-MacBook-Pro pydantic_test % python3 -m venv test_env                                                                  

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/pip install "https://github.com/Nuitka/Nuitka/archive/develop.zip" pydantic
Collecting https://github.com/Nuitka/Nuitka/archive/develop.zip
  Using cached https://github.com/Nuitka/Nuitka/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic
  Using cached pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
Collecting ordered-set>=4.1.0 (from Nuitka==2.0rc1)
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15 (from Nuitka==2.0rc1)
  Using cached zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.9 kB)
Collecting annotated-types>=0.4.0 (from pydantic)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.5 (from pydantic)
  Using cached pydantic_core-2.14.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.5 kB)
Collecting typing-extensions>=4.6.1 (from pydantic)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Using cached pydantic-2.5.2-py3-none-any.whl (381 kB)
Using cached pydantic_core-2.14.5-cp311-cp311-macosx_11_0_arm64.whl (1.7 MB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl (703 kB)
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (pyproject.toml) ... done
  Created wheel for Nuitka: filename=Nuitka-2.0rc1-cp311-cp311-macosx_14_0_arm64.whl size=3196800 sha256=9bc4ddd68a836acd0445d9ccdc7b08d26b2d13138d18ba9d6f43987b6eeafc8b
  Stored in directory: /private/var/folders/bg/ncfhn34x10b5m6cw_n_kr8580000gn/T/pip-ephem-wheel-cache-6m22vu0f/wheels/82/73/76/93e4e3aa0a95e81c5738b08ef30b6c118c24811ede4422a559
Successfully built Nuitka
Installing collected packages: zstandard, typing-extensions, ordered-set, annotated-types, pydantic-core, Nuitka, pydantic
Successfully installed Nuitka-2.0rc1 annotated-types-0.6.0 ordered-set-4.1.0 pydantic-2.5.2 pydantic-core-2.14.5 typing-extensions-4.8.0 zstandard-0.22.0

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/python -m nuitka --version 
2.0rc1
Commercial: None
Python: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
Flavor: Homebrew Python
Executable: /Users/john/Git/pydantic_test/test_env/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/pip freeze                
annotated-types==0.6.0
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip#sha256=d0ef5ed0374d2cf984f23cd250c69213cf6c2ec7c457dc46e7cbcbfe5b933b44
ordered-set==4.1.0
pydantic==2.5.2
pydantic_core==2.14.5
typing_extensions==4.8.0
zstandard==0.22.0

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/python -m nuitka --standalone main.py                                   
Nuitka-Options:INFO: Used command line options: --standalone main.py
Nuitka:INFO: Starting Python compilation with Nuitka '2.0rc1' on Python '3.11' commercial grade 'not installed'.
Problem with statement at main.py:1:                 
-> from pydantic import BaseModel

Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'main.py', 'module_name': <ModuleName '__main__'>, 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/__main__.py", line 170, in <module>
    main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/__main__.py", line 156, in main
    MainControl.main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 1116, in main
    _main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 965, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 255, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 92, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ModuleNodes.py", line 549, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/VariableAssignNodes.py", line 352, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ChildrenHavingMixins.py", line 11293, in computeExpressionRaw
    expression = trace_collection.onExpression(self.subnode_module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ChildrenHavingMixins.py", line 11524, in computeExpressionRaw
    return self.computeExpression(trace_collection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ImportNodes.py", line 1026, in computeExpression
    trace_collection.onModuleUsageAttempt(module_usage_attempt)
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 1152, in onModuleUsageAttempt
    decision, _reason = decideRecursion(
                        ^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/importing/Recursion.py", line 154, in decideRecursion
    Plugins.onModuleUsageLookAhead(
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/plugins/Plugins.py", line 1074, in onModuleUsageLookAhead
    plugin.onModuleUsageLookAhead(
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 587, in onModuleUsageLookAhead
    sub_module_name = module_name.getChildNamed(sub_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/utils/ModuleNames.py", line 211, in getChildNamed
    return ModuleName(".".join([self] + list(args)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/utils/ModuleNames.py", line 58, in __init__
    assert checkModuleName(value), value
AssertionError: pydantic.pydantic_core.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

had to add `.txt` to make github accept the file
[nuitka-crash-report.xml.txt](https://github.com/Nuitka/Nuitka/files/13453779/nuitka-crash-report.xml.txt)

**Comment by ONEPANTSU** [comment]
I have the same error (

**Comment by kayhayen** [comment]
You are not using the latest version of Nuitka

**Comment by John-Colvin** [comment]
> You are not using the latest version of Nuitka

I'm confused. I initially ran the test with the latest version installed by `pip install nuitka`, which was at the time `1.9`. I think I followed the instructions for submitting an issue, which includes the suggestion to try with `develop`, which I did. I got the same error & that experiment is what I shared above.

What did I do wrong? Which version should I have used?

**Comment by John-Colvin** [comment]
I just tried again with `1.9` (same crash, as expected) and then with `1.9.1` and the bug seems fixed. Hooray! Thanks whoever fixed it.

I would like to know what I did wrong to have this bug report closed as invalid though, in case I need to report something again. I think I followed the instructions reasonably.

**Comment by kayhayen** [comment]
You reported against 1.9 while 1.9.1 was already out at the time.

**Comment by kayhayen** [comment]
And also, develop would have not shown the issue, had you tried it, as asked for in the issue template, although I tend to be very forgiving about skipping that, reports of issues already fixed in the current stable release are invalid by definition.

**Comment by John-Colvin** [comment]
I reported about 12 hours before 1.9.1 was released (unless there's some timezone confusion happening?). I also did try `develop,` you can see that in what I posted, that is a copy-paste from my terminal showing me installing develop getting the error. Maybe there is something else going on, idk...

**Comment by kayhayen** [comment]
Ok, of course I can be totally wrong, and I didn't properly read it, once I was sure it's a solved issue. The me too post however was clearly wrong. In fact, this may well have been the issue that triggered the hotfix release with the fix. As you can imagine, I am getting a lot of less than optimal interactions in the GitHub. I corrected it.
