### ISSUE TITLE
PySpice packaged by nuitka does not work properly

### ISSUE THREAD

**Issue by liangychao** [Nuitka/Nuitka#2573]
PySpice is a Python module which provides a Python interface to the Ngspice and Xyce circuit simulators.
I just want to packaged the PySpice official example but the .exe file didn't work.
## Installation
reference to  [https://pyspice.fabrice-salvaire.fr/releases/v1.5/installation.html#on-windows](url) 
via `command pip install PySpice` install the PySpice
`pyspice-post-installation --install-ngspice-dll` install the ngspice Windows 64-bit DLL library.
and `pyspice-post-installation --download-example` get the Examples
## Successfully run the code in the command window
Extract the examples to a local directory，such as：D:\examples
The example I chose is `D:\examples\PySpice-1.5\examples\resistor\resistor-bridge.py`, Its introduction in [https://pyspice.fabrice-salvaire.fr/releases/v1.5/examples/resistor/resistor-bridge.html](url)
```
D:\examples\PySpice-1.5\examples\resistor>python resistor-bridge.py
Node 3:  6.0 V
Node 2:  4.0 V
Node 1: 10.0 V

D:\examples\PySpice-1.5\examples\resistor>
```
The following is the contents of the resistor-bridge.py
```python
#r# This example shows the computation of the DC biases in a resistor bridge.

####################################################################################################

import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()

####################################################################################################

from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *

####################################################################################################

#f# circuit_macros('resistor-bridge.m4')

circuit = Circuit('Resistor Bridge')

circuit.V('input', 1, circuit.gnd, 10@u_V)
circuit.R(1, 1, 2, 2@u_kΩ)
circuit.R(2, 1, 3, 1@u_kΩ)
circuit.R(3, 2, circuit.gnd, 1@u_kΩ)
circuit.R(4, 3, circuit.gnd, 2@u_kΩ)
circuit.R(5, 3, 2, 2@u_kΩ)

simulator = circuit.simulator(temperature=25, nominal_temperature=25)
analysis = simulator.operating_point()

for node in analysis.nodes.values():
    print('Node {}: {:4.1f} V'.format(str(node), float(node))) # Fixme: format value + unit
#o#
```
## Nuitka compile command:
`python -m nuitka --output-dir=out --standalone  --show-progress --show-memory --enable-plugin=numpy resistor-bridge.py`
## Output when First run the .exe file
```
D:\examples\PySpice-1.5\examples\resistor>D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\resistor-bridge.exe
Traceback (most recent call last):
  File "D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\resistor-bridge.py", line 6, in <module>
  File "D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\PySpice\Logging\Logging.py", line 46, in setup_logging
  File "D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\PySpice\Config\ConfigInstall.py", line 65, in find
  File "D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\PySpice\Tools\Path.py", line 53, in find
NameError: File logging.yml not found in directories ('D:\\examples\\PySpice-1.5\\examples\\resistor\\out\\resistor-bridge.dist\\PySpice\\Config',)

D:\examples\PySpice-1.5\examples\resistor>
```
## Then I copy the PySpice package into the directory the .exe file in 
```
D:\examples\PySpice-1.5\examples\resistor>D:\examples\PySpice-1.5\examples\resistor\out\resistor-bridge.dist\resistor-bridge.exe

D:\examples\PySpice-1.5\examples\resistor>
D:\examples\PySpice-1.5\examples\resistor>
```
There's nothing output

## Environment Information
```
D:\examples\PySpice-1.5\examples\resistor>python -m nuitka --version
0.8
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\***\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

``` 
```
D:\examples\PySpice-1.5\examples\resistor>pip list
Package                   Version
------------------------- -----------
altgraph                  0.17.2
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
asttokens                 2.0.8
async-generator           1.10
attrs                     21.4.0
backcall                  0.2.0
beautifulsoup4            4.11.1
bleach                    5.0.1
cachetools                5.1.0
cairocffi                 0.9.0
certifi                   2022.6.15
cffi                      1.15.0
chardet                   5.1.0
charset-normalizer        2.0.12
click                     7.1.2
colorama                  0.4.5
cryptography              37.0.2
cycler                    0.11.0
debugpy                   1.6.3
decorator                 5.1.1
defusedxml                0.7.1
distlib                   0.3.4
dxfgrabber                1.0.1
entrypoints               0.4
et-xmlfile                1.1.0
executing                 0.10.0
face-recognition-models   0.3.0
fastjsonschema            2.16.1
filelock                  3.7.0
fonttools                 4.33.3
future                    0.18.2
glob2                     0.7
h11                       0.13.0
hdl                       0.0.0
idna                      3.3
imageio                   2.19.2
importlib-metadata        4.12.0
intel-bhs                 0.0.1
ipykernel                 6.15.1
ipython                   8.4.0
ipython-genutils          0.2.0
ipywidgets                8.0.1
jedi                      0.18.1
Jinja2                    3.1.2
jsonschema                4.14.0
jupyter                   1.0.0
jupyter-client            7.3.4
jupyter-console           6.4.4
jupyter-core              4.11.1
jupyterlab-pygments       0.2.2
jupyterlab-widgets        3.0.2
kdFileFinder              1.0.2
kiwisolver                1.4.2
lxml                      4.9.1
MarkupSafe                2.1.1
matplotlib                3.5.2
matplotlib-inline         0.1.6
mistune                   2.0.4
mpmath                    1.2.1
nbclient                  0.6.7
nbconvert                 7.0.0
nbformat                  5.4.0
nest-asyncio              1.5.5
notebook                  6.4.12
Nuitka                    0.8
numpy                     1.22.4
opencv-python             4.5.5.64
openpyxl                  3.0.10
ordered-set               4.1.0
outcome                   1.2.0
packaging                 21.3
pandas                    2.0.3
pandocfilters             1.5.0
parso                     0.8.3
pbr                       6.0.0
pcb-tools                 0.1.6
pcb-tools-extension       0.9.3
PCBpy                     0.0.1
pdfminer                  20191125
pdfminer.six              20220524
pdfplumber                0.7.1
pefile                    2021.9.3
pickleshare               0.7.5
Pillow                    9.1.1
pio                       0.0.3
pip                       23.3.1
platformdirs              2.5.2
ply                       3.11
prometheus-client         0.14.1
prompt-toolkit            3.0.30
psutil                    5.9.1
pure-eval                 0.2.2
py2exe                    0.11.1.0
pycairo                   1.21.0
pycparser                 2.21
pycryptodome              3.14.1
Pygments                  2.13.0
pyinstaller               5.1
pyinstaller-hooks-contrib 2022.5
pynput                    1.7.6
pyOpenSSL                 22.0.0
pyparsing                 3.0.9
pypiwin32                 223
PyQt5                     5.15.4
pyqt5-plugins             5.15.4.2.2
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.13.0
pyqt5-tools               5.15.4.3.2
PyQt6                     6.6.0
PyQt6-Qt6                 6.6.0
PyQt6-sip                 13.6.0
PyQtChart                 5.15.6
PyQtChart-Qt5             5.15.2
PyQtWebEngine             5.15.6
PyQtWebEngine-Qt5         5.15.2
pyrsistent                0.18.1
PySide6                   6.6.0
PySide6-Addons            6.6.0
PySide6-Essentials        6.6.0
PySocks                   1.7.1
PySpice                   1.5
python-dateutil           2.8.2
python-dotenv             0.20.0
python-tkdnd              0.2.1
pytz                      2023.3
pywin32                   304
pywin32-ctypes            0.2.0
pywinpty                  2.0.7
PyYAML                    6.0.1
pyzmq                     23.2.1
qt5-applications          5.15.2.2.2
qt5-tools                 5.15.2.1.2
qtconsole                 5.3.1
QtPy                      2.2.0
requests                  2.31.0
scapy                     2.5.0
scipy                     1.9.0
selenium                  4.2.0
Send2Trash                1.8.0
setuptools                58.1.0
shiboken6                 6.6.0
shutilwhich               1.1.0
six                       1.16.0
sniffio                   1.2.0
sortedcontainers          2.4.0
soupsieve                 2.3.2.post1
stack-data                0.4.0
stevedore                 5.1.0
sympy                     1.11.1
terminado                 0.15.0
tinui                     4.4.0
tinyaes                   1.0.3
tinycss2                  1.1.1
tk                        0.1.0
tkinterdnd2               0.3.0
tornado                   6.2
traitlets                 5.3.0
trio                      0.21.0
trio-websocket            0.9.2
ttkbootstrap              1.10.1
ttkwidgets                0.12.1
tzdata                    2023.3
urllib3                   1.26.9
usnparser                 4.1.5
virtualenv                20.14.1
virtualenv-clone          0.5.7
virtualenvwrapper         4.8.4
Wand                      0.6.7
wcwidth                   0.2.5
webencodings              0.5.1
wheel                     0.37.1
widgetsnbextension        4.0.2
windnd                    1.0.7
wsproto                   1.1.0
wxPython                  4.1.1
xlrd                      1.2.0
xlutils                   2.0.0
xlwt                      1.3.0
zipp                      3.8.1
zstandard                 0.17.0
```

**Comment by kayhayen** [comment]
Your report has an amazing quality otherwise for using an obsolete version of Nuitka `0.8` is not as good as `1.9` or so I would hope.

**Comment by kayhayen** [comment]
If you retry with new Nuitka and still have issues, we can reopen it.
