### ISSUE TITLE
1.9.x AssertionError: ('pywin32', 'Unknown')

### ISSUE THREAD

**Issue by abdelouahabb** [Nuitka/Nuitka#2576]
Nuitka crashes on Windows assuming it's a linux package ?

```
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="1.9.1" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="AssertionError" exception_value="('pywin32', 'Unknown')">
Traceback (most recent call last):
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1116, in main
    _main()
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1008, in _main
    detectUsedDLLs(
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 418, in decideAllowOutsideDependencies
    if not isDistributionSystemPackage(getDistributionName(distribution)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\Distributions.py", line 266, in isDistributionSystemPackage
    assert isLinux(), (
AssertionError: ('pywin32', 'Unknown')
```

Latest 1.8.6 works fine, only crashes with 1.9.0 and 1.9.1

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
