### ISSUE TITLE
segfault with get() call on temp dict in min. example with no imports

### ISSUE THREAD

**Issue by preetjuniper** [Nuitka/Nuitka#2578]
Compilation of the included minimal example causes a segmentation fault that seems to occur after the suspect code has been run (so possibly during clean up -- the gdb trace seems to indicate the issue is happening during gc). The code runs fine when it is not compiled via nuitka.

- Nuitka version
  Tried with nuitka 1.8.4, 1.9.1 and dev. Also tried with python 3.8.18, all have the same issue.
```
>> python3 -m nuitka --version
2.0rc2
Commercial: None
Python: 3.8.10 (default, Mar 13 2023, 10:26:41)
Flavor: Debian Python
Executable: /b/me/dev/scratch/nuitka_crash/venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9)
```
- How did you install Nuitka and Python
  Via pip, `pip3 install Nuitka==1.x.y` and `pip3 install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`

- The specific PyPI names and versions
  No additional packages

- Short, Self Contained, Correct, Example
  Save the following as `nuitka_crash_aio.py`, and compile with the provided command. Sorry for the odd example with potentially useless code, but playing around with removing some loops or lists seemed to avoid the crash.
```
# coding=utf-8

class TempData:
    def __init__(self):
        self.data = {}

def run_me():
    attr0_one = "d8e2275d"
    attr0_two = "36a78a21"
    attr1_one = "48a7ec0b"
    attr1_two = "76bd599e"

    ref_data = [
        [
            {
                "attr0": "d8e2275d",
                "attr1": "48a7ec0b",
                "attr2": "fd39764b",
            },
            {
                "attr0": "36a78a21",
                "attr1": "76bd599e",
                "attr2": "caaf2c9d",
            }
        ],
    ]

    r = TempData()
    r.data = ref_data[0]

    for dat in r.data:
        # this block with x = { ... }.get(...) crashes with a segfault
        x = {
            attr0_one: {
                'attr0': attr0_one,
                'attr1': attr1_one,
                'attr2': 'fd39764b',
            },
            attr0_two: {
                'attr0': attr0_two,
                'attr1': attr1_two,
                'attr2': 'caaf2c9d',
            },
        }.get(dat['attr0'])
        print(x)

        # but moving the .get(...) to a separate line works
        # x = { ... }
        # y = x.get(dat['attr0'])
        # print(y)

if __name__ == "__main__":
    run_me()

```

- Provide in your issue the Nuitka options used
```
>> python3 -m nuitka --follow-imports nuitka_crash_aio.py --output-dir=out --report=out/build.xml --no-pyi-file --remove-output
```
  The issue also occurs when compiling as an extension and importing + calling the method from a trivial 'main' entrypoint.

- More info
```
>> ./nuitka_crash_aio.bin
{'attr0': 'd8e2275d', 'attr1': '48a7ec0b', 'attr2': 'fd39764b'}
{'attr0': '36a78a21', 'attr1': '76bd599e', 'attr2': 'caaf2c9d'}
Segmentation fault

// through gdb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
{'attr0': 'd8e2275d', 'attr1': '48a7ec0b', 'attr2': 'fd39764b'}
{'attr0': '36a78a21', 'attr1': '76bd599e', 'attr2': 'caaf2c9d'}

Program received signal SIGSEGV, Segmentation fault.
0x00005555557179a3 in PyObject_GC_Del ()
(gdb) bt
#0  0x00005555557179a3 in PyObject_GC_Del ()
#1  0x00005555556453e5 in PyDict_ClearFreeList ()
#2  0x0000555555716998 in ?? ()
#3  0x00005555557171f1 in PyGC_Collect ()
#4  0x00005555556f29bb in Py_FinalizeEx ()
#5  0x00005555556f32ec in Py_Exit ()
#6  0x00005555555ca32f in ?? ()
#7  0x00007ffff7c28083 in __libc_start_main (main=0x5555555c8f90, argc=1, argv=0x7fffffffe798,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe788) at ../csu/libc-start.c:308
#8  0x00005555555d5dfe in _start ()
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.9.2 hotfix release I just made.
