### ISSUE TITLE
(Another) AssertionError with --standalone & pydantic

### ISSUE THREAD

**Issue by John-Colvin** [Nuitka/Nuitka#2579]
Following on from https://github.com/Nuitka/Nuitka/issues/2571, it seems there is some other problem with using pydantic. Here I am importing `openai` instead of `pydantic` directly, so it's getting a lot more real use. Same error with `develop`, I am showing nuitka 1.9.1 below.

```
john@Johns-MacBook-Pro pydantic_test % ls -a          
.	..	main.py

john@Johns-MacBook-Pro pydantic_test % cat main.py
import openai

john@Johns-MacBook-Pro pydantic_test % python3 -m venv test_env

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/pip install nuitka openai
Collecting nuitka
  Using cached Nuitka-1.9.1-cp311-cp311-macosx_14_0_arm64.whl
Collecting openai
  Using cached openai-1.3.5-py3-none-any.whl.metadata (16 kB)
Collecting ordered-set>=4.1.0 (from nuitka)
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting zstandard>=0.15 (from nuitka)
  Using cached zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.9 kB)
Collecting anyio<4,>=3.5.0 (from openai)
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Collecting httpx<1,>=0.23.0 (from openai)
  Using cached httpx-0.25.2-py3-none-any.whl.metadata (6.9 kB)
Collecting pydantic<3,>=1.9.0 (from openai)
  Using cached pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
Collecting tqdm>4 (from openai)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting typing-extensions<5,>=4.5 (from openai)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting idna>=2.8 (from anyio<4,>=3.5.0->openai)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio>=1.1 (from anyio<4,>=3.5.0->openai)
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting certifi (from httpx<1,>=0.23.0->openai)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)
  Using cached httpcore-1.0.2-py3-none-any.whl.metadata (20 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai)
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting annotated-types>=0.4.0 (from pydantic<3,>=1.9.0->openai)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.5 (from pydantic<3,>=1.9.0->openai)
  Using cached pydantic_core-2.14.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.5 kB)
Using cached openai-1.3.5-py3-none-any.whl (220 kB)
Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Using cached httpx-0.25.2-py3-none-any.whl (74 kB)
Using cached httpcore-1.0.2-py3-none-any.whl (76 kB)
Using cached pydantic-2.5.2-py3-none-any.whl (381 kB)
Using cached pydantic_core-2.14.5-cp311-cp311-macosx_11_0_arm64.whl (1.7 MB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl (703 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Installing collected packages: zstandard, typing-extensions, tqdm, sniffio, ordered-set, idna, h11, distro, certifi, annotated-types, pydantic-core, nuitka, httpcore, anyio, pydantic, httpx, openai
Successfully installed annotated-types-0.6.0 anyio-3.7.1 certifi-2023.11.17 distro-1.8.0 h11-0.14.0 httpcore-1.0.2 httpx-0.25.2 idna-3.6 nuitka-1.9.1 openai-1.3.5 ordered-set-4.1.0 pydantic-2.5.2 pydantic-core-2.14.5 sniffio-1.3.0 tqdm-4.66.1 typing-extensions-4.8.0 zstandard-0.22.0

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/python -m nuitka --version
1.9.1
Commercial: None
Python: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
Flavor: Homebrew Python
Executable: /Users/john/Git/pydantic_test/test_env/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).

john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/pip freeze
annotated-types==0.6.0
anyio==3.7.1
certifi==2023.11.17
distro==1.8.0
h11==0.14.0
httpcore==1.0.2
httpx==0.25.2
idna==3.6
Nuitka==1.9.1
openai==1.3.5
ordered-set==4.1.0
pydantic==2.5.2
pydantic_core==2.14.5
sniffio==1.3.0
tqdm==4.66.1
typing_extensions==4.8.0
zstandard==0.22.0
                                   
john@Johns-MacBook-Pro pydantic_test % ./test_env/bin/python -m nuitka --standalone main.py --debug
Nuitka-Options:INFO: Used command line options: --standalone main.py --debug
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.1' on Python '3.11' commercial grade 'not installed'.
Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:534:
->         except pydantic.ValidationError as err:

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:526:
->         try:

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:526:
->         try:

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:513:
->     def _process_response_data(

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:513:
->     def _process_response_data(

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:318:
-> class BaseClient(Generic[_HttpxClientT, _DefaultStreamT]):

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:318:
-> class BaseClient(Generic[_HttpxClientT, _DefaultStreamT]):

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:318:
-> class BaseClient(Generic[_HttpxClientT, _DefaultStreamT]):

Problem with statement at /Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py:318:
-> class BaseClient(Generic[_HttpxClientT, _DefaultStreamT]):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/openai/_base_client.py', 'module_name': <ModuleName 'openai._base_client'>, 'code_flags': 'CO_FUTURE_ANNOTATIONS'}>'.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
PASS 1: 96.5%|████████████████████████▏| 473/490, openai._base_clientTraceback (most recent call last):
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/__main__.py", line 170, in <module>
    main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/__main__.py", line 156, in main
    MainControl.main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 1116, in main
    _main()
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 965, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 255, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 92, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ModuleNodes.py", line 549, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/VariableAssignNodes.py", line 352, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/OutlineNodes.py", line 248, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/LocalsDictNodes.py", line 425, in computeStatement
    return StatementLocalsDictOperationSetBase.computeStatement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementBasesGenerated.py", line 2224, in computeStatement
    result, change_tags, change_desc = self.computeStatementSubExpressions(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/NodeBases.py", line 715, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ChildrenHavingMixins.py", line 4870, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 1154, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 348, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 494, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 510, in computeFunction
    result = statements_sequence.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 140, in computeStatement
    result = except_handler.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ConditionalNodes.py", line 590, in computeStatement
    condition = trace_collection.onExpression(self.subnode_condition)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ChildrenHavingMixins.py", line 9589, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ExpressionBasesGenerated.py", line 819, in computeExpressionRaw
    return self.computeExpression(trace_collection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/AttributeLookupNodes.py", line 43, in computeExpression
    return self.subnode_expression.computeExpressionAttribute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/VariableRefNodes.py", line 148, in computeExpressionAttribute
    return attribute_node.computeExpressionAttribute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ImportNodes.py", line 639, in computeExpressionAttribute
    return self._computeExpressionAttribute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ImportNodes.py", line 606, in _computeExpressionAttribute
    result = trust_node_factory[self.value_name, attribute_name](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 619, in <lambda>
    return lambda source_ref: ExpressionImportModuleNameHardExists(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ImportHardNodes.py", line 71, in __init__
    ExpressionImportHardBase.__init__(
  File "/Users/john/Git/pydantic_test/test_env/lib/python3.11/site-packages/nuitka/nodes/ImportHardNodes.py", line 48, in __init__
    assert self.finding != "not-found", self.module_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: pydantic.pydantic_core
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

[nuitka-crash-report.xml.txt](https://github.com/Nuitka/Nuitka/files/13467199/nuitka-crash-report.xml.txt)

**Comment by kayhayen** [comment]
Ah, I remember this one, it actually is a top level package `pydantic_core` isn't it.

**Comment by ONEPANTSU** [comment]
So... Does somebody have a resolve for this problem? 
I just follow your steps (of errors), man!)

**Comment by John-Colvin** [comment]
> Ah, I remember this one, it actually is a top level package `pydantic_core` isn't it.

Yes that seems right. https://pypi.org/project/pydantic-core/

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Seems that the lazy loader code needed some massage, it was expecting submodule names, but now that is only so for actual `lazy` module usages, and the factory for `pydantic` already does it itself, previously it was stripping the prefix to mold in. This will be in 1.9.2 likely, but I almost feel like there is a need for some sort of test in Nuitka-Watch to cover the various pydantic versions, since they are all slightly different, and maybe now the old one is broken again.

**Comment by John-Colvin** [comment]
The problem appears fixed for me when using factory, thanks.

**Comment by kayhayen** [comment]
Part of the 1.9.2 hotfix release I just made.
