### ISSUE TITLE
Regression in 1.9: AssertionError with poetry on Windows

### ISSUE THREAD

**Issue by Aksem** [Nuitka/Nuitka#2582]
Nuitka version: tested both 1.9.2 and factory. In 1.8 it worked well, so it is a **regression**.
The problem appears only on Windows, the same app is compilable on Linux and macOS.
Poetry version doesn't matter, tried 1.4-1.7.

```
 1.9.2
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons:INFO: For Python version 3.11 MSVC 14.3 or later is required, not 14.2 which is too old.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in 'C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1'.

FATAL: Only this specific gcc is supported with Nuitka.
Fully automatic, cached. Proceed and download? [Yes]/No : 
```

Installed with pyenv and poetry.

Minimal example: https://github.com/Aksem/nuitka_assertion_error

Installed aiohttp with 'speedup' extras via poetry and tried to build minimal app:

```
from aiohttp import web
```

**Command:** 
```
poetry run python -m nuitka \
            --standalone \
            --follow-imports \
            --assume-yes-for-downloads \
            --plugin-enable="pylint-warnings" \
            --warn-unusual-code \
            --warn-implicit-exceptions \
            --show-memory \
            --show-modules \
            --trace-execution \
            --mingw64 \
            nuitka_bug/main.py
```

**Compilation Output:**
```
 Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Traceback (most recent call last):
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\__main__.py", line 170, in <module>
    main()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\__main__.py", line 156, in main
    MainControl.main()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\MainControl.py", line 1116, in main
    _main()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\MainControl.py", line 1008, in _main
    detectUsedDLLs(
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\freezer\Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\freezer\Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\plugins\Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 418, in decideAllowOutsideDependencies
    if not isDistributionSystemPackage(getDistributionName(distribution)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\nuitka-bug-4B0JvDqT-py3.11\Lib\site-packages\nuitka\utils\Distributions.py", line 266, in isDistributionSystemPackage
    assert isLinux(), (
AssertionError: ('aiohttp', 'poetry 1.5.0')
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

**Comment by kayhayen** [comment]
Ah, interesting, poetry is even properly annotating itself as an installer, very well. 

```
  <distributions>
    <distribution name="aiohttp" version="3.9.1" installer="poetry 1.5.0" />
    <distribution name="aiosignal" version="1.3.1" installer="poetry 1.5.0" />
    <distribution name="attrs" version="23.1.0" installer="poetry 1.5.0" />
    <distribution name="frozenlist" version="1.4.0" installer="poetry 1.5.0" />
    <distribution name="idna" version="3.6" installer="poetry 1.5.0" />
    <distribution name="multidict" version="6.0.4" installer="poetry 1.5.0" />
    <distribution name="yarl" version="1.9.3" installer="poetry 1.5.0" />
  </distributions>
```

For our purposes, I guess, poetry and pip are largely the same, however, I noticed that poetry occasionally installs things wrong, we at least will be able to tell. I will add it for 1.9.3 then.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by Aksem** [comment]
Current factory works well on all operating systems, thanks!

**Comment by kayhayen** [comment]
Part of the 1.9.3 release I just made.
