### ISSUE TITLE
nuitka 1.9.2 --nofollow option with --report raises exception when generating report

### ISSUE THREAD

**Issue by preetjuniper** [Nuitka/Nuitka#2587]
Using nuitka to build a project with the `--nofollow-import-to` option along with a `--report` path specified causes an exception with 1.9.2. This seems to be a regression as 1.8.5 does not raise an error. The output binary seems fine and the failure looks to be in report generation.

  - Nuitka version
```
>> python3 -m nuitka --version
1.9.2
Commercial: None
Python: 3.8.10 (default, Mar 13 2023, 10:26:41)
Flavor: Debian Python
Executable: /b/me/dev/scratch/nuitka_crash/venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).
```
  - How did you install Nuitka and Python
    Via pip, `pip3 install Nuitka==1.x.y`

  - The specific PyPI names and versions
    N/A

   - Short, Self Contained, Correct, Example
```
ex. dir structure
$project_root/proj/foo.py
$project_root/proj/foo_test.py

// foo.py
def foo(a, b):
    return a+b

// foo_test.py
from foo import foo

def test_foo():
    print(foo(1, 2))

if __name__ == "__main__":
    test_foo()
```

  - Provide in your issue the Nuitka options used
    explicitly added the debug-report-traceback after seeing the error initially as suggested by nuitka's output
```
python3 -m nuitka --module proj --include-package=proj --nofollow-import-to='*test' --output-dir=out --report=out/build.xml --experimental=debug-report-traceback
```

  - More info
```
Nuitka-Options:INFO: Used command line options: --module proj --include-package=proj --nofollow-import-to=*test --output-dir=out --report=out/build.xml --experimental=debug-report-traceback
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.2' on Python '3.8' commercial grade 'not installed'.
Nuitka-Inclusion:WARNING: Not allowed to include module 'proj.foo_test' due to 'Module matches pattern '*test' instructed by user to not follow to.'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 9).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka:INFO: Keeping build directory 'out/proj.build'.
Nuitka:INFO: Successfully created 'out/proj.cpython-38-x86_64-linux-gnu.so'.
Nuitka:WARNING: Report writing was prevented by exception KeyError(None), use option '--experimental=debug-report-traceback' for full traceback.
Traceback (most recent call last):
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/MainControl.py", line 1116, in main
    _main()
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/MainControl.py", line 1086, in _main
    writeCompilationReports(aborted=False)
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/reports/Reports.py", line 673, in writeCompilationReports
    report_input_data = _getReportInputData(aborted)
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/reports/Reports.py", line 172, in _getReportInputData
    module_exclusions[_using_module_name][_module_name] = _reason
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/__main__.py", line 170, in <module>
    main()
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/__main__.py", line 156, in main
    MainControl.main()
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/MainControl.py", line 1119, in main
    writeCompilationReports(aborted=True)
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/reports/Reports.py", line 673, in writeCompilationReports
    report_input_data = _getReportInputData(aborted)
  File "/b/me/dev/scratch/nuitka_crash/venv/lib/python3.8/site-packages/nuitka/reports/Reports.py", line 172, in _getReportInputData
    module_exclusions[_using_module_name][_module_name] = _reason
KeyError: None
```

**Comment by kayhayen** [comment]
Ah, yes. The include options do not have a using module name, and that's biting the code in a couple of places, I found one in anti-bloat today myself.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.9.3 release I just made.
