### ISSUE TITLE
[msys2] --enable-plugin=pyside2/pyside6 was broken since Nuitka >= 1.9 (ImportError in shiboken module)

### ISSUE THREAD

**Issue by podsvirov** [Nuitka/Nuitka#2628]
Report for [hello](https://doc-snapshots.qt.io/qtforpython-6.2/deployment-nuitka.html) example:

```console
user@host UCRT64 /c/tmp
$ nuitka3 --version
1.9.5
Commercial: None
Python: 3.11.7 (main, Dec  7 2023, 09:09:57)  [GCC UCRT 13.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/ucrt64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/ucrt64/bin/gcc.exe (gcc 13.2.0).

user@host UCRT64 /c/tmp
$ cat hello.pyw
#!/usr/bin/env python3

import sys
import random
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton,
                               QVBoxLayout, QWidget)
from PySide6.QtCore import Slot, Qt

class MyWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)

        self.hello = ["Hallo Welt", "你好，世界", "Hei maailma",
            "Hola Mundo", "Привет мир"]

        self.button = QPushButton("Click me!")
        self.text = QLabel("Hello World")
        self.text.setAlignment(Qt.AlignCenter)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.text)
        self.layout.addWidget(self.button)
        self.setLayout(self.layout)

        # Connecting the signal
        self.button.clicked.connect(self.magic)

    @Slot()
    def magic(self):
        self.text.setText(random.choice(self.hello))

if __name__ == "__main__":
    app = QApplication(sys.argv)

    widget = MyWidget()
    widget.resize(800, 600)
    widget.show()

    sys.exit(app.exec())


user@host UCRT64 /c/tmp
$ nuitka3 --standalone --plugin-enable=pyside6 hello.pyw
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pyside6 hello.pyw
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.5' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so delay this until your program working and remove once you find it non-working, and use '--enable-console' to make it explicit and not see this message.
Nuitka-Plugins:INFO: anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons:INFO: Backend linking program with 13 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 13 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 13
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
Nuitka:INFO: Keeping build directory 'hello.build'.
Nuitka:INFO: Successfully created 'hello.dist/hello.exe'.

user@host UCRT64 /c/tmp
$ ./hello.dist/hello.exe
PySide6/__init__.py: Unable to import Shiboken from C:/tmp/hello.dist, C:\tmp\HELLO~1.DIS
Traceback (most recent call last):
  File "C:\tmp\HELLO~1.DIS\hello.pyw", line 5, in <module>
  File "C:\tmp\HELLO~1.DIS\PySide6/__init__.py", line 124, in <module PySide6>
  File "C:\tmp\HELLO~1.DIS\PySide6/__init__.py", line 64, in _setupQtDirectories
  File "C:\tmp\HELLO~1.DIS\shiboken6/__init__.py", line 27, in <module shiboken6>
ImportError

user@host UCRT64 /c/tmp
$ echo "But..."
But...

user@host UCRT64 /c/tmp
$ pacman -U https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-python-nuitka-1.8.3-1-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-ucrt-x86_64-python-nuitka (1.9.5-1 => 1.8.3-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-ucrt-x86_64-python-nuitka-1.8.3-1

Total Installed Size:  33.69 MiB
Net Upgrade Size:      -1.02 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                     [###################################################################] 100%
(1/1) checking package integrity                                                                                   [###################################################################] 100%
(1/1) loading package files                                                                                        [###################################################################] 100%
(1/1) checking for file conflicts                                                                                  [###################################################################] 100%
(1/1) checking available disk space                                                                                [###################################################################] 100%
:: Processing package changes...
(1/1) downgrading mingw-w64-ucrt-x86_64-python-nuitka                                                              [###################################################################] 100%

user@host UCRT64 /c/tmp
$ nuitka3 --version
1.8.3
Commercial: None
Python: 3.11.7 (main, Dec  7 2023, 09:09:57)  [GCC UCRT 13.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/ucrt64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/ucrt64/bin/gcc.exe (gcc).

user@host UCRT64 /c/tmp
$ nuitka3 --standalone --plugin-enable=pyside6 hello.pyw
Nuitka-Options:INFO: Used command line options: --standalone --plugin-enable=pyside6 hello.pyw
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.3' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so delay this until your program working and remove once you find it non-working.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 12 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
Nuitka:INFO: Keeping build directory 'hello.build'.
Nuitka:INFO: Successfully created 'hello.dist/hello.exe'.

user@host UCRT64 /c/tmp
$ ./hello.dist/hello.exe

user@host UCRT64 /c/tmp
$
```

**Comment by kayhayen** [comment]
How is PySide6 installed, is it a MSYS2 package, and how do I install that one, or is it the pip package maybe.

**Comment by podsvirov** [comment]
> How is PySide6 installed, is it a MSYS2 package, and how do I install that one, or is it the pip package maybe.

Environment (MSYS2):

```console
user@host ~
$ pacman -S --needed --noconfirm pactoys
warning: pactoys-r55.8860e1f-1 is up to date -- skipping
 there is nothing to do

user@host ~
$ pacboy -S --needed --noconfirm gcc:u ccache:u pyside6:u python-nuitka:u
warning: mingw-w64-ucrt-x86_64-gcc-13.2.0-3 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-ccache-4.8.3-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-pyside6-6.6.1-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-python-nuitka-1.9.5-1 is up to date -- skipping
 there is nothing to do
```

**Comment by kayhayen** [comment]
I didn't manage to reproduce this on my current version of factory. However, I noticed that the installer is given as "UNKNOWN" which is not bad, because it will cause things to be considered as a system package, which it is. If it was classified as "pip", that would explain it not including errors.

For me ccache is always crashing, so I did this:

> /ucrt64/bin/python bin/nuitka-run --report=out.xml --disable-ccache tests/standalone/PySide6Using.py

Can you confirm or deny that it works for you, and if not provide the out.xml report?

Nuitka doesn't detect UCRT and MinGW64 differently. I uninstalled MinGW64 Python and only used that UCRT Python and the PySide6 package: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
My last comment refers to accelerated mode of Nuitka, and doesn't relate much to this issue other than that I was looking if it's good generally with it.

**Comment by podsvirov** [comment]
> Can you confirm or deny that it works for you, and if not provide the out.xml report?

Sorry for delay. It's not works for me:
```console
kot@DESKTOP-636MIDN MINGW64 ~/src/MINGW-packages/mingw-w64-python-nuitka/src/Nuitka-1.9.6
$ nuitka3 --version
1.9.6
Commercial: None
Python: 3.11.7 (main, Dec  7 2023, 09:07:50)  [GCC 13.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:/msys64/mingw64/bin/gcc.exe (gcc 13.2.0).

kot@DESKTOP-636MIDN MINGW64 ~/src/MINGW-packages/mingw-w64-python-nuitka/src/Nuitka-1.9.6
$ nuitka3 --report=out.xml --disable-ccache tests/standalone/PySide6Using.py
Nuitka-Options:INFO: Used command line options: --standalone --enable-plugin=pyside6 --report=out.xml --disable-ccache tests/standalone/PySide6Using.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.6' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Note, when using 'PySide6', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so delay this until your program working and remove once you find it non-working, and use '--enable-console' to make it explicit and not see this message.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons:INFO: Backend linking program with 13 files (no progress information available for this stage).
Nuitka-Plugins:INFO: pyside6: Including Qt plugins 'imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
Nuitka:INFO: Keeping build directory 'PySide6Using.build'.
Nuitka:INFO: Successfully created 'PySide6Using.dist/PySide6Using.exe'.
Nuitka-Reports:INFO: Compilation report written to file 'out.xml'.

kot@DESKTOP-636MIDN MINGW64 ~/src/MINGW-packages/mingw-w64-python-nuitka/src/Nuitka-1.9.6
$ ls
Changelog.rst         LICENSE.txt  Nuitka.egg-info  PySide6Using.build  README.rst  doc  misc    out.xml         setup.cfg  tests
Developer_Manual.rst  MANIFEST.in  PKG-INFO         PySide6Using.dist   bin         lib  nuitka  pyproject.toml  setup.py

kot@DESKTOP-636MIDN MINGW64 ~/src/MINGW-packages/mingw-w64-python-nuitka/src/Nuitka-1.9.6
$ PySide6Using.dist/PySide6Using.exe
PySide6/__init__.py: Unable to import Shiboken from C:/msys64/home/kot/src/MINGW-packages/mingw-w64-python-nuitka/src/Nuitka-1.9.6/PySide6Using.dist, C:\msys64\home\kot\src\MINGW-~1\MIC6D7~1\src\NUITKA~1.6\PYSIDE~1.DIS
Traceback (most recent call last):
  File "C:\msys64\home\kot\src\MINGW-~1\MIC6D7~1\src\NUITKA~1.6\PYSIDE~1.DIS\PySide6Using.py", line 31, in <module>
  File "C:\msys64\home\kot\src\MINGW-~1\MIC6D7~1\src\NUITKA~1.6\PYSIDE~1.DIS\PySide6/__init__.py", line 124, in <module PySide6>
  File "C:\msys64\home\kot\src\MINGW-~1\MIC6D7~1\src\NUITKA~1.6\PYSIDE~1.DIS\PySide6/__init__.py", line 64, in _setupQtDirectories
  File "C:\msys64\home\kot\src\MINGW-~1\MIC6D7~1\src\NUITKA~1.6\PYSIDE~1.DIS\shiboken6/__init__.py", line 27, in <module shiboken6>
ImportError
```
Report: [out.zip](https://github.com/Nuitka/Nuitka/files/13932774/out.zip).

**Comment by kayhayen** [comment]
it has this:

```
  <distributions>
    <distribution name="PySide6" version="6.6.1" installer="Unknown" />
    <distribution name="shiboken6" version="6.6.1" installer="Unknown" />
  </distributions>
```

So it seems PySide6 MSYS2 package installer is not recognized by Nuitka. I need to test that, but I believe pip install of PySide6 would have pip there.

**Comment by kayhayen** [comment]
It seems, I didn't see that you mentioned the MSYS2 package name you used originally.

**Comment by kayhayen** [comment]
Lots of issues with non-native `/` and `\` paths were triggering assertions making for a lot of improvements for the recent attempts to improve the situation, plugin code, module location, and many mode things producing non-native paths, which we assert against for at least included entry points, as we use paths for comparison there. Should now be more correct for many cases there.

**Comment by kayhayen** [comment]
These seem to have been all issues, for me the standalone test for PySide6 just worked, I didn't use the crt variant, since that's what I have around, but I don't think that was ever the issue.
