### ISSUE TITLE
Error with Toga Widget Toolkit - ModuleNotFoundError: No module named 'setuptools_scm'

### ISSUE THREAD

**Issue by itcd** [Nuitka/Nuitka#2633]
Nuitka version, full Python version, flavor, OS, etc.
`python -m nuitka --version`
```python
1.9.5
Commercial: None
Python: 3.11.7 (main, Dec  8 2023, 22:59:22) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```

How did you install Nuitka and Python
`python -m pip install -U nuitka`

The specific PyPI names and versions
`python -m pip freeze`
```python
aiodav==0.1.12
aiodns==3.1.1
aiofiles==23.2.1
aiohttp==3.9.1
aiosignal==1.3.1
albumentations==1.3.1
anyio==4.2.0
arrow==1.3.0
asttokens==2.4.1
attrs==23.1.0
beautifulsoup4==4.12.2
binaryornot==0.4.4
briefcase==0.3.16
build==1.0.3
certifi==2023.11.17
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.0
cookiecutter==2.5.0
dataclasses==0.6
debugpy==1.8.0
decorator==5.1.1
delphifmx==1.0.8
distlib==0.3.8
docutils==0.20.1
et-xmlfile==1.1.0
executing==2.0.1
faust-cchardet==2.1.19
filelock==3.13.1
frozenlist==1.4.1
gitdb==4.0.11
GitPython==3.1.40
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.6
imageio==2.33.1
iniconfig==2.0.0
ipykernel==6.27.1
ipython==8.18.1
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
jupyter_client==8.6.0
jupyter_core==5.5.0
lxml==4.9.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mdurl==0.1.2
nest-asyncio==1.5.8
Nuitka==1.9.5
numpy==1.26.2
oauthlib==3.2.2
openpyxl==3.1.2
ordered-set==4.1.0
packaging==23.2
parso==0.8.3
pexpect==4.9.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.43
psutil==5.9.7
ptyprocess==0.7.0
pure-eval==0.2.2
pycares==4.4.0
pycparser==2.21
Pygments==2.17.2
pypiwin32==223
pypng==0.20220715.0
pyproject_hooks==1.0.0
pysnowball==0.1.2
pytest==7.4.3
python-dateutil==2.8.2
python-slugify==8.0.1
pythonnet==3.0.3
pytz==2023.3.post1
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.2
qrcode==7.4.2
qudida==0.0.4
repath==0.9.0
requests==2.31.0
rich==13.7.0
setuptools-scm==8.0.4
sh==2.0.6
simpleaudio==1.0.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
text-unidecode==1.3
toga==0.4.1
toga-android==0.4.1
toga-core==0.4.1
toga-winforms==0.4.1
tomli_w==1.0.0
tornado==6.4
traitlets==5.14.0
travertino==0.3.0
types-python-dateutil==2.8.19.14
typing_extensions==4.9.0
tzdata==2023.3
urllib3==2.1.0
virtualenv==20.25.0
watchdog==3.0.0
wcwidth==0.2.12
webdav4==0.9.8
websocket-client==1.7.0
websockets==11.0.3
WMI==1.5.1
yarl==1.9.4
zstandard==0.22.0
```

#### Error with Toga Widget Toolkit - ModuleNotFoundError: No module named 'setuptools_scm'

I encountered an error while running the complied exe of a Python program that uses the Toga widget toolkit. The error message suggests that the module 'setuptools_scm' was not found, which led to subsequent exceptions.

#### Toga Widget Toolkit
I installed the Toga Widget Toolkit using the following command:
`python -m pip install toga`

#### Example
Here is an example script 'toga1.py' that uses the Toga widget toolkit:
```python
import toga

def button_handler(widget):
    print("hello")

def build(app):
    box = toga.Box()
    button = toga.Button("Hello world", on_press=button_handler)
    button.style.padding = 50
    button.style.flex = 1
    box.add(button)
    return box

def main():
    return toga.App("First App", "org.beeware.helloworld", startup=build)

if __name__ == "__main__":
    main().main_loop()
```

Running 'toga1.py' displays a window with a button.
`python toga1.py`

![Screenshot 2023-12-30 120015](https://github.com/Nuitka/Nuitka/assets/753851/195cdc61-9694-4809-861a-1c29a1e5b4e1)

I attempted to compile 'toga1.py' using Nuitka and run the compiled 'toga1.exe' file.
`python -m nuitka --standalone toga1.py`

The following errors occurred when running 'toga1.exe':
```python
Traceback (most recent call last):
  File "C:\py\dist\toga\__init__.py", line 99, in _package_version
ModuleNotFoundError: No module named 'setuptools_scm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\py\dist\importlib\metadata\__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\py\dist\toga1.py", line 1, in <module>
  File "C:\py\dist\toga\__init__.py", line 116, in <module toga>
  File "C:\py\dist\toga\__init__.py", line 113, in _package_version
  File "C:\py\dist\importlib\metadata\__init__.py", line 1008, in version
  File "C:\py\dist\importlib\metadata\__init__.py", line 981, in distribution
  File "C:\py\dist\importlib\metadata\__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for toga-core
```

#### Installing setuptools_scm
I tried installing the 'setuptools_scm' module using the following command:
`python -m pip install setuptools_scm`
After installing the 'setuptools_scm' module, I tried compiling the program and running the compiled 'toga1.exe' file again. However, I encountered warnings during the compilation process and errors during the execution.

The following warnings occurred when compiling:
```python
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools_scm' (intending to
Nuitka-Plugins:WARNING: avoid 'setuptools') in 'toga' (at
Nuitka-Plugins:WARNING: 'c:\3\Lib\site-packages\toga\__init__.py:99') encountered. It may 
Nuitka-Plugins:WARNING: slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
```

The following errors occurred during the execution:
```python
Traceback (most recent call last):
  File "C:\py\dist\toga1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\toga\__init__.py", line 1, in <module toga>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\toga\app.py", line 20, in <module toga.app>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\toga\widgets\base.py", line 7, in <module toga.widgets.base>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\travertino\__init__.py", line 4, in <module travertino>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\setuptools_scm\__init__.py", line 7, in <module setuptools_scm>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\setuptools_scm\_config.py", line 15, in <module setuptools_scm._config>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\setuptools_scm\_integration\pyproject_reading.py", line 8, in <module setuptools_scm._integration.pyproject_reading>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\py\dist\setuptools_scm\_integration\setuptools.py", line 62, in <module setuptools_scm._integration.setuptools>
  File "C:\py\dist\setuptools_scm\_integration\setuptools.py", line 29, in _warn_on_old_setuptools
ValueError: invalid literal for int() with base 10: 'unknown'
```

**Comment by KevinRodriguez777** [comment]
Thank you for the report, this will be added to nuitka in a future version, for the moment you can easily support it yourself with the following flag `--user-package-configuration-file=config.yaml` with the following content as your config.yaml
```yaml
- module-name: 'toga'
  data-files:
    include-metadata:
      - 'toga-core'
  implicit-imports:
    - depends:
        - 'toga_winforms'
      when: 'win32'

- module-name: 'toga_winforms'
  data-files:
    dirs:
      - 'resources'
    patterns:
      - '**/*.py'
    include-metadata:
      - 'toga-winforms'
  dlls:
    - from_filenames:
        relative_path: 'libs/WebView2/arm64'
        prefixes:
          - 'WebView2Loader'
      when: 'win32 and arch_arm64'
    - from_filenames:
        relative_path: 'libs/WebView2/x86'
        prefixes:
          - 'WebView2Loader'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: 'libs/WebView2/x64'
        prefixes:
          - 'WebView2Loader'
      when: 'win32 and arch_amd64'

    - from_filenames:
        relative_path: 'libs/WebView2'
        prefixes:
          - 'Microsoft.'
      when: 'win32'
  implicit-imports:
    - depends:
        - 'toga_winforms.libs.wrapper'
        - 'ctypes.wintypes'
```
in order for this to work you will need to have `setuptools-scm` uninstalled, i'm still working on getting it to work with it installed.

**Comment by itcd** [comment]
> Thank you for the report, this will be added to nuitka in a future version, for the moment you can easily support it yourself with the following flag `--user-package-configuration-file=config.yaml` with the following content as your config.yaml
> 
> ```yaml
> - module-name: 'toga'
>   data-files:
>     include-metadata:
>       - 'toga-core'
>   implicit-imports:
>     - depends:
>         - 'toga_winforms'
>       when: 'win32'
> 
> - module-name: 'toga_winforms'
>   data-files:
>     dirs:
>       - 'resources'
>     patterns:
>       - '**/*.py'
>     include-metadata:
>       - 'toga-winforms'
>   dlls:
>     - from_filenames:
>         relative_path: 'libs/WebView2/arm64'
>         prefixes:
>           - 'WebView2Loader'
>       when: 'win32 and arch_arm64'
>     - from_filenames:
>         relative_path: 'libs/WebView2/x86'
>         prefixes:
>           - 'WebView2Loader'
>       when: 'win32 and arch_x86'
>     - from_filenames:
>         relative_path: 'libs/WebView2/x64'
>         prefixes:
>           - 'WebView2Loader'
>       when: 'win32 and arch_amd64'
> 
>     - from_filenames:
>         relative_path: 'libs/WebView2'
>         prefixes:
>           - 'Microsoft.'
>       when: 'win32'
>   implicit-imports:
>     - depends:
>         - 'toga_winforms.libs.wrapper'
>         - 'ctypes.wintypes'
> ```
> 
> in order for this to work you will need to have `setuptools-scm` uninstalled, i'm still working on getting it to work with it installed.

Thanks a lot! I got it working by uninstalling 'setuptools-scm' and then recompiling using:
`python -m nuitka --standalone --user-package-configuration-file=config.yaml toga1.py`
