### ISSUE TITLE
Regression on included modules between 1.8.4 and 1.9.6 for passlib and uvicorn

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#2642]
When building a project with Nuitka 1.8.4, I need some manual `--include-module` parameters to get standalone to work.  
Migrating to Nuitka 1.9.6, I now need more `--include-module` parameters to obtain a working standalone program.

In order to achieve the same working build with 1.9.6 than with 1.8.4, I need to add the following arguments
```
--include-module=passlib.handlers
--include-module=passlib.handlers.argon2
--include-module=uvicorn.workers
```

Without those, I get the following errors on execution:
```
Traceback (most recent call last):
  File "/var/myapp_compile/myapp_server.dist/myapp_server.py", line 29, in <module>
  File "/var/myapp_compile/myapp_server.dist/myapp/user_interface.py", line 147, in <module myapp.user_interface>
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 1402, in __init__
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 1597, in load
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 635, in __init__
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 653, in _init_scheme_list
  File "/var/myapp_compile/myapp_server.dist/passlib/registry.py", line 352, in get_crypt_handler
ModuleNotFoundError: No module named 'passlib.handlers'
```

```
Traceback (most recent call last):
  File "/var/myapp_compile/myapp_server.dist/myapp_server.py", line 29, in <module>
  File "/var/myapp_compile/myapp_server.dist/myapp/user_interface.py", line 147, in <module myapp.user_interface>
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 1402, in __init__
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 1597, in load
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 635, in __init__
  File "/var/myapp_compile/myapp_server.dist/passlib/context.py", line 653, in _init_scheme_list
  File "/var/myapp_compile/myapp_server.dist/passlib/registry.py", line 352, in get_crypt_handler
ModuleNotFoundError: No module named 'passlib.handlers.argon2'
```

```
Error: class uri 'uvicorn.workers.UvicornWorker' invalid or not found:

[Traceback (most recent call last):
  File "/var/myapp_compile/myapp_server.dist/gunicorn/util.py", line 111, in load_class
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'uvicorn.workers'
]
```

Successful compilation with Nuitka 1.8.4
```
Nuitka-Options:INFO: Used command line options: --python-flag=no_docstrings --python-flag=no_asserts --enable-plugin=data-hiding --python-flag=no_docstrings --python-flag=no_asserts --include-module=myapp --include-module=passlib --include-module=pydantic.type_adapter --include-module=gunicorn.glogging --include-module=urllib3 --include-module=uvicorn --include-module=argon2 --include-data-dir=www.myapp=www.myapp --include-data-dir=www.startup_interface=www.startup_interface --include-data-dir=venv/lib/python3.9/site-packages/fastapi_offline/static=fastapi_offline/static --standalone myapp_server.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.4' on Python '3.9' commercial grade '2.2.6'.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' (intending to avoid 'unittest') in 'passlib.tests.backports' (at
Nuitka-Plugins:WARNING: '/var/myapp_compile/venv/lib64/python3.9/site-packages/passlib/tests/backports.py:31') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 832 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 831 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 824
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 7
Nuitka-Options:INFO: Included 128 data files due to specified data dir 'www.myapp' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/index.tpl.html' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/wait_for_device.html' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/css/bootstrap.min.css' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/logo/favicon.png' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/logo/logo.svg' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/svg-loaders/ball-triangle.svg' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/js/bootstrap.bundle.min.js' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/js/jquery-3.7.1.min.js' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/favicon.png' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/redoc.standalone.js' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/swagger-ui-bundle.js' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/swagger-ui.css' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Plugins:INFO: data-files: Included data file 'Cryptodome/Util/.keep_dir.txt' due to empty dir needed for 'Cryptodome.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka:INFO: Keeping build directory 'myapp_server.build'.
Nuitka:INFO: Successfully created 'myapp_server.dist/myapp_server.bin'.
```

Successful compilation with Nuitka 1.9.6
```
Nuitka-Options:INFO: Used command line options: --python-flag=no_docstrings --python-flag=no_asserts --enable-plugin=data-hiding --python-flag=no_docstrings --python-flag=no_asserts --include-module=myapp --include-module=passlib --include-module=passlib.handlers --include-module=passlib.handlers.argon2 --include-module=pydantic.type_adapter --include-module=gunicorn.glogging --include-module=urllib3 --include-module=uvicorn --include-module=uvicorn.workers --include-module=argon2 --include-data-dir=www.myapp=www.myapp --include-data-dir=www.startup_interface=www.startup_interface --include-data-dir=venv/lib/python3.9/site-packages/fastapi_offline/static=fastapi_offline/static --standalone myapp_server.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.6' on Python '3.9' commercial grade '2.3.2'.
FATAL: Error, failed to locate module 'ucivorn.workers' you asked to include.
[root@myapp myapp_compile]# venv/bin/python -m nuitka ${COMMERCIAL_OPTS} --python-flag=no_docstrings --python-flag=no_asserts --include-module=myapp --include-module=passlib --include-module=passlib.handlers --include-module=passlib.handlers.argon2 --include-module=pydantic.type_adapter --include-module=gunicorn.glogging --include-module=urllib3 --include-module=uvicorn --include-module=uvicorn.workers --include-module=argon2 --include-data-dir=www.myapp=www.myapp --include-data-dir=www.startup_interface=www.startup_interface --include-data-dir=venv/lib/python3.9/site-packages/fastapi_offline/static=fastapi_offline/static --standalone myapp_server.py
Nuitka-Options:INFO: Used command line options: --python-flag=no_docstrings --python-flag=no_asserts --enable-plugin=data-hiding --python-flag=no_docstrings --python-flag=no_asserts --include-module=myapp --include-module=passlib --include-module=passlib.handlers --include-module=passlib.handlers.argon2 --include-module=pydantic.type_adapter --include-module=gunicorn.glogging --include-module=urllib3 --include-module=uvicorn --include-module=uvicorn.workers --include-module=argon2 --include-data-dir=www.myapp=www.myapp --include-data-dir=www.startup_interface=www.startup_interface --include-data-dir=venv/lib/python3.9/site-packages/fastapi_offline/static=fastapi_offline/static --standalone myapp_server.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.6' on Python '3.9' commercial grade '2.3.2'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 11).
Nuitka-Scons:INFO: Backend linking program with 746 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 746 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 744
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 2
Nuitka-Options:INFO: Included 128 data files due to specified data dir 'www.myapp' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/index.tpl.html' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/wait_for_device.html' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/css/bootstrap.min.css' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/logo/favicon.png' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/logo/logo.svg' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/images/svg-loaders/ball-triangle.svg' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/js/bootstrap.bundle.min.js' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'www.startup_interface/assets/js/jquery-3.7.1.min.js' due to specified data dir 'www.startup_interface' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/favicon.png' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/redoc.standalone.js' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/swagger-ui-bundle.js' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Options:INFO: Included data file 'fastapi_offline/static/swagger-ui.css' due to specified data dir 'venv/lib/python3.9/site-packages/fastapi_offline/static' on command line.
Nuitka-Plugins:INFO: data-files: Included data file 'Cryptodome/Util/.keep_dir.txt' due to empty dir needed for 'Cryptodome.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi/cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka:INFO: Keeping build directory 'myapp_server.build'.
Nuitka:INFO: Successfully created 'myapp_server.dist/myapp_server.bin'.
```

  > python -m nuitka --version

```
1.9.6
Commercial: 2.3.2
Python: 3.9.18 (main, Sep  7 2023, 00:00:00)
Flavor: Fedora Python
Executable: /var/ztl_compile/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Almalinux (based on Fedora) 9.2
Version C compiler: /usr/lib64/ccache/gcc (gcc 11).
```
- How did you install Nuitka and Python

```python -m pip install /path/to/nuitka-commercial-1.9.6.zip```

Zip comes from github release page

- The specific PyPI names and versions

  > python -m pip freeze

List is not full, but contains necessary elements IMO
```
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
bcrypt==4.0.1
command-runner==1.5.2
cryptidy==1.2.2
fastapi==0.108.0
fastapi-offline==1.7.0
gunicorn==21.2.0
Nuitka @ file:///home/zerotouch/Nuitka-commercial-1.9.6.zip
passlib==1.7.4
pydantic==2.5.3
pydantic_core==2.14.6
starlette==0.32.0.post1
urllib3==2.0.6
uvicorn==0.25.0
uvloop==0.17.0
```

**Comment by deajan** [comment]
Not using Nuitka alot since two years, but still enjoying it alot ;)

**Comment by kayhayen** [comment]
I think the passlib stuff is actionalble, we got this:

```
- module-name: 'passlib.apache' # checksum: 4e9f8101
  implicit-imports:
    - depends:
        - 'passlib.handlers.digests'
        - 'passlib.handlers.bcrypt'
        - 'passlib.handlers.md5_crypt'
        - 'passlib.handlers.des_crypt'
        - 'passlib.handlers.ldap_digests'

- module-name: 'passlib.hash' # checksum: 7794431b
  implicit-imports:
    - depends:
        - 'passlib.handlers.sha2_crypt'
```

There is a lazy loader in `hashlib.hash`, one that hides things. Not sure if this ever worked, since you do not have a reproducer supplied, there is no way of knowing. I would suspect that for the passlib code I looked at right now, the config is probably not that good. The test case apparently was `import passlib.apache` and the dependencies maybe got misattributed entirely.

**Comment by deajan** [comment]
While I do understand that this should have never worked, I don't really understand that v1.8.4 worked better than v1.9.6 here.
Would be useful if I can make a reproducer ?

**Comment by kayhayen** [comment]
With a reproducer, things are relatively hard to reproduce and check. The lazy loader support for `passlib` I can do without one though, the uvicorn issue definitely needs one. I guess it kind of is just how you setup your server that somehow exposes an implicit dependency.

**Comment by deajan** [comment]
Okay, I'll try to trim everything down to the bare minimum.

**Comment by kayhayen** [comment]
Closing for lack of feedback

**Comment by abdelouahabb** [comment]
Any update about this issue ? passlib still throws this error

```
Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\abdelouahab\AppData\Local\Programs\Python\Python312\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: Non downloaded winlibs-gcc 'C:\w64devkit\bin\gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

```
File "C:\Users\ABDELO~1\Desktop\STOCK_~1\APP~1.DIS\passlib\utils\handlers.py", line 2176, in set_backend
passlib.exc.MissingBackendError: argon2: no backends available -- recommend you install one (e.g. 'pip install argon2_cffi')
```

**Comment by KRRT7** [comment]
> Any update about this issue ? passlib still throws this error
> 
> ```
> Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
> Flavor: CPython Official
> Executable: C:\Users\abdelouahab\AppData\Local\Programs\Python\Python312\python.exe
> OS: Windows
> Arch: x86_64
> WindowsRelease: 10
> Nuitka-Scons: Non downloaded winlibs-gcc 'C:\w64devkit\bin\gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
> Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
> ```
> 
> ```
> File "C:\Users\ABDELO~1\Desktop\STOCK_~1\APP~1.DIS\passlib\utils\handlers.py", line 2176, in set_backend
> passlib.exc.MissingBackendError: argon2: no backends available -- recommend you install one (e.g. 'pip install argon2_cffi')
> ```

please open a new issue with an reproducer, thanks.
