### ISSUE TITLE
os.path.normcase cause FileNotFoundError

### ISSUE THREAD

**Issue by lidanqing123** [Nuitka/Nuitka#2645]
Environment
```
 python -m nuitka --version
1.9.6
Commercial: None
Python: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Anaconda3\envs\project\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).

```

error info:

```
Traceback (most recent call last): 
File "C:\ProgramData\Anaconda3\envs\project\lib\site-packages\nuitka\MainControl.py", line 1116, in main _main() 
File "C:\ProgramData\Anaconda3\envs\project\lib\site-packages\nuitka\MainControl.py", line 996, in _main executePostProcessing() 
File "C:\ProgramData\Anaconda3\envs\project\lib\site-packages\nuitka\PostProcessing.py", line 317, in executePostProcessing executePostProcessingResources(manifest=manifest, onefile=False) 
File "C:\ProgramData\Anaconda3\envs\project\lib\site-packages\nuitka\PostProcessing.py", line 276, in executePostProcessingResources _addWindowsIconFromIcons(onefile=onefile) 
File "C:\ProgramData\Anaconda3\envs\project\lib\site-packages\nuitka\PostProcessing.py", line 158, in _addWindowsIconFromIcons with open(icon_path, "rb") as icon_file: 
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\lenovo\\documents\\work\\script\\project\\project\\src\\main\\icons\\icon.ico' 
```

But the `--windows-icon-from-ico=` I assignmented was 'c:\\users\\lenovo\\documents\\work\\script\\project\\project\\src\\main\\icons\\Icon.ico', not `icon.ico`. 

By reading the nuitka script, i find the following code:
![图片](https://github.com/Nuitka/Nuitka/assets/21281783/f82def45-3883-4655-822f-4567a05c1581)

This may be the cause of the problem

```
import os
path = "./Test/aa.txt"
os.path.normcase(path)
'.\\test\\aa.txt'
os.path.normpath(path)
'Test\\aa.txt'

```

**Comment by lidanqing123** [comment]
![图片](https://github.com/Nuitka/Nuitka/assets/21281783/5a564a2b-4b15-43a3-b96e-59dddadf4195)

**Comment by kayhayen** [comment]
I think you probably just specified a wrong value for the option. Since you are not giving the actual example, but are jumping to wrong conclusions, I cannot know.

**Comment by lidanqing123** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by lidanqing123** [comment]
I developing on Windows. This error may be due to the fact that I have set up my Windows system's environment.

```
fsutil file setCaseSensitiveInfo path enable
```
This is because when using Git, I often run into file or directory name case conflicts.

I'd suggest that nuitka could change os.path.normcase to os.path.normpath
