### ISSUE TITLE
jupyter_client error when starting a KernelManager

### ISSUE THREAD

**Issue by ybou10** [Nuitka/Nuitka#2648]
Hello,

First of all, thank you a lot for this amazing project. I am planning to use it in order to deploy on Windows a python application involving notably PySide6 and jupyter_client.

- Nuitka version, full Python version, flavor, OS, etc..

```
1.9 
Commercial: None                                                                                                                   
Python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]                                           
Flavor: CPython Official                                                                                                           
Executable: C:\Users\YBO\Envs\nanofrazor311\Scripts\python.exe                                                                     
OS: Windows                                                                                                                        
Arch: x86_64                                                                                                                       
WindowsRelease: 10                                                                                                                 
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl14.3).
```

- How did you install Nuitka and Python

`pip3 install nuitka
`
- The specific PyPI names and versions

```
alabaster==0.7.13
anyio==4.0.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
astor==0.8.1
asttokens==2.4.1
async-lru==2.0.4
attrs==23.1.0
Babel==2.13.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.11.0
bleach==6.1.0
breathe==4.35.0
certifi==2023.7.22
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
contourpy==1.2.0
coverage==7.3.2
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.7
docutils==0.18.1
dominate==2.8.0
executing==2.0.1
fastjsonschema==2.19.0
ffmpeg==1.4
filelock==3.13.1
fonttools==4.44.1
fpdf2==2.7.6
fqdn==1.5.1
identify==2.5.31
idna==3.4
imageio==2.31.5
imagesize==1.4.1
imutils==0.5.4
iniconfig==2.0.0
ipykernel==6.26.0
ipython==8.17.2
ipython-genutils==0.2.0
ipywidgets==8.1.1
isoduration==20.11.0
isort==5.12.0
jedi==0.19.1
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.2
jsonschema-specifications==2023.11.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.9.0
jupyter-lsp==2.2.0
jupyter_client==8.6.0
jupyter_core==5.5.0
jupyter_server==2.10.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.8
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.1
kiwisolver==1.4.5
lazy_loader==0.3
MarkupSafe==2.1.3
matplotlib==3.8.1
matplotlib-inline==0.1.6
mistune==3.0.2
mypy-extensions==1.0.0
nbclassic==0.5.1
nbclient==0.9.0
nbconvert==7.11.0
nbformat==5.9.2
nest-asyncio==1.5.8
networkx==3.2.1
nodeenv==1.8.0
notebook==7.0.6
notebook_shim==0.2.3
nudged==0.3.1
Nuitka==1.9
numpy==1.26.2
opencv-contrib-python==4.9.0.80
opencv-python==4.8.1.78
ordered-set==4.1.0
overrides==7.4.0
packaging==23.2
pandas==2.1.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.2
pickleshare==0.7.5
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
pprofile==2.1.0
pre-commit==2.21.0
prometheus-client==0.18.0
prompt-toolkit==3.0.41
psutil==5.9.6
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
pynsist==2.8
PyOpenGL==3.1.7
pyparsing==3.1.1
pypylon==3.0.0
PyQt5==5.15.10
PyQt5-commercial==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
pyqtgraph==0.13.3
PyQtWebEngine-commercial==5.15.6
pyrsistent==0.19.3
pyserial==3.5
PySide6==6.6.0
PySide6-Addons==6.6.0
PySide6-Essentials==6.6.0
pytest==7.4.3
pytest-subtests==0.9.0
pytest-timeout==2.2.0
python-dateutil==2.8.2
python-http-client==3.3.7
python-json-logger==2.0.7
pytz==2023.3.post1
PyWavelets==1.4.1
pywin32==306
pywinpty==2.0.12
PyYAML==6.0.1
pyzmq==25.1.1
qtconsole==5.4.0
QtPy==2.4.1
referencing==0.31.0
requests==2.31.0
requests_download==0.1.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.12.0
scikit-image==0.20.0
scipy==1.11.3
secure-smtplib==0.1.1
Send2Trash==1.8.2
sendgrid==6.3.1
shiboken6==6.6.0
simplegeneric==0.8.1
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.6
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
stack-data==0.6.3
starkbank-ecdsa==2.2.0
terminado==0.18.0
tifffile==2023.9.26
tinycss2==1.2.1
toml==0.10.2
tornado==6.3.3
traitlets==5.13.0
types-python-dateutil==2.8.19.14
tzdata==2023.3
uri-template==1.3.0
urllib3==2.1.0
virtualenv==20.24.6
wcwidth==0.2.10
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.4
wget==3.2
widgetsnbextension==4.0.9
xgboost==1.7.6
xlrd==2.0.1
yarg==0.1.9
zstandard==0.22.0
```

- Many times when you get an error from Nuitka, your setup may be special

Basic print hello world program works fine.

- Also supply a Short, Self Contained, Correct, Example

```
from jupyter_client import KernelManager

a = KernelManager()
a.start_kernel()
```

- Command

`
python -m nuitka --standalone --noinclude-default-mode=allow --msvc=14.3 myfile.py`

- Output

```
0.01s - Debugger warning: It seems the debugger cannot find os.path.realpath.__code__.co_filename (C:\Users\YBO\a\aa\ntpath.py).
0.00s - This may make the debugger miss breakpoints in the standard library.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "C:\Users\YBO\a\myfile.py", line 6, in <module>
  File "C:\Users\YBO\a\jupyter_core\utils\__init__.py", line 173, in wrapped
  File "C:\Users\YBO\a\asyncio\base_events.py", line 653, in run_until_complete
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 87, in wrapper
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 435, in _async_start_kernel
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 395, in _async_pre_start_kernel
  File "C:\Users\YBO\a\jupyter_client\provisioning\factory.py", line 101, in create_provisioner_instance
TypeError: 'module' object is not callable
```

The traceback is triggered by the start_kernel() call and, as it is shown, finds its origin within the jupyter_client package.
If Im not mistaken, jupyter_client is part of the [unwanted modules](https://nuitka.net/info/unwanted-module.html) for which there are known issues.

Also, after the compilation, I had to manually copy the debugpy package into the dist folder. Otherwise I have this traceback in the console : 

```
Traceback (most recent call last):
  File "C:\Users\YBO\a\myfile.py", line 6, in <module>
  File "C:\Users\YBO\a\jupyter_core\utils\__init__.py", line 173, in wrapped
  File "C:\Users\YBO\a\asyncio\base_events.py", line 653, in run_until_complete
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 87, in wrapper
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 435, in _async_start_kernel
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 397, in _async_pre_start_kernel
  File "C:\Users\YBO\a\jupyter_client\manager.py", line 195, in kernel_spec
  File "C:\Users\YBO\a\jupyter_client\kernelspec.py", line 282, in get_kernel_spec
  File "C:\Users\YBO\a\jupyter_client\kernelspec.py", line 265, in _find_spec_directory
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\YBO\a\aa\ipykernel\kernelspec.py", line 21, in <module ipykernel.kernelspec>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\YBO\a\aa\ipykernel\debugger.py", line 23, in <module ipykernel.debugger>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\YBO\a\aa\debugpy\server\__init__.py", line 7, in <module debugpy.server>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\YBO\a\aa\debugpy\_vendored\__init__.py", line 16, in <module debugpy._vendored>
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\YBO\\a\\aa\\debugpy\\_vendored'
```

Many thanks for your help!

**Comment by kayhayen** [comment]
Well, I think IPython ought to work, it's just causing too big compiles. What might easily happen is that we break IPython when we do changes and do not guard them with `use_ipython` which has happened in the past. You can put it to "allow" to not see the warning. In case of the IPython knob, it probably should allow some other modules. We do something for `torch` like this in the package configuration for a while now:

```
  anti-bloat:
    - description: 'allow unittest inside of torch, too dependent to remove'
      bloat-mode-overrides:
        'unittest': 'allow'
      when: 'not use_unittest'
```

Manual copying is not allowed and the results are not considered.  I am not sure what lead you to conclude to copy `debugpy`. 

We should consider `PYDEVD_DISABLE_FILE_VALIDATION=1` either way, as that's probably not too useful for end users.

As indicated without source code, it's not necessarily going to be good at breakpoints. 

Also 1.9 is not the best release, there were quite a few changes since that in hotfixes, but nothing that makes me believe it could resolve your issue.

**Comment by kayhayen** [comment]
I am revisiting this one, I am seeing that it uses `black` and that's a trouble maker currently with 3.12 which is what I am trying, due to an issue with package loading on that version for extension modules, so I am switching to 3.11 again, not sure if that's really needed, but the underlying issue should be fixed.

Using `--noinclude-IPython-mode=allow` should be good. Unwanted modules are typically less well supported and tested, since they are commonly avoided as first things in issues.

**Comment by kayhayen** [comment]
The crash is about metadata, it seems that we include it already, but it becomes kind of wrong, I printed it, before it resolves to a module in its load:

Nuitka:
```
MM local-provisioner EntryPoint(name='local-provisioner', value='jupyter_client.provisioning', group='LocalProvisioner')
```

CPython:
```
MM local-provisioner EntryPoint(name='local-provisioner', value='jupyter_client.provisioning:LocalProvisioner', group='jupyter_client.kernel_provisioners')
```

Both the values of value and group are wrong. It seems our construction of them at compile time might be wrong, the colon maybe misinterpreted as group, which it is not. I have to find where that happens.

**Comment by kayhayen** [comment]
We are not including any metadata and this is dynamic, I wonder if some sort of default handling kicks in there, it shouldn't work really at all and crash on not finding the entry points there. So there might be a lack of understand of mine here, where this comes from, but I don't see it in configuration as being added.

**Comment by kayhayen** [comment]
With metadata explicitely added by --include-distribution-metadata=jupyter_client it is better, however it wants to execute a Python interpreter:

```
  File "/home/hayen/repos/Py2C/Mini.dist/jupyter_client/provisioning/local_provisioner.py", line 210, in launch_kernel
  File "/home/hayen/repos/Py2C/Mini.dist/jupyter_client/launcher.py", line 155, in launch_kernel
  File "/home/hayen/repos/Py2C/Mini.dist/subprocess.py", line 1026, in __init__
  File "/home/hayen/repos/Py2C/Mini.dist/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/hayen/repos/Py2C/Mini.dist/python3.11'
```

I will add the meta data need to our Yaml configuration, but I guess, this one needs more work.

**Comment by kayhayen** [comment]
I traced what it tries to do, and this is something we can easily support, 

> ['/home/hayen/repos/Py2C/Mini.dist/python3.11', '-m', 'ipykernel_launcher', '-f', '/tmp/tmp3x2nq3sw.json']

This is for Linux, I think Win32 does it a bit different, but it also forks the same. We can change that over to be calling the binary itself and handle this module name, like we do for joblib, multiprocessing, etc. and then it ought to work from the same binary, of course that means we might have to depend on `ipykernel_launcher` implicitly as well.

**Comment by kayhayen** [comment]
I added the metadata change for the 2.5.1 hotfix release, but as indicated there is more work to do to get the kernel fork working properly, that is not yet done.

**Comment by kayhayen** [comment]
This is working with current develop and will be part of 4.1 release.

**Comment by kayhayen** [comment]
Part of the 4.1 release I just made.
