### ISSUE TITLE
UPX BUG

### ISSUE THREAD

**Issue by ChiHnLeong** [Nuitka/Nuitka#2670]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\Plugins.py", line 585, in onCopiedDLLs
    plugin.onCopiedDLL(dll_path)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\UpxPlugin.py", line 142, in onCopiedDLL
    self._compressFile(filename=dll_filename, use_cache=not self.upx_nocache)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\standard\UpxPlugin.py", line 121, in _compressFile
    executeToolChecked(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\utils\Execution.py", line 348, in executeToolChecked
    logger.sysexit(absence_message)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\nuitka\plugins\PluginBase.py", line 1285, in sysexit
    cls.plugin_name + ": " + message, mnemonic=mnemonic, reporting=reporting
TypeError: can only concatenate str (not "NoneType") to str
FATAL: upx: Plugin issue while working on 'DLL 'bin\ArriveUpload.dist\PySide6\QtCore.pyd''. Please report the bug with the above traceback included.
Nuitka-Reports:INFO: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports:INFO: Compilation crash report written to file 'nuitka-crash-report.xml'.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
