### ISSUE TITLE
Python3.8 --onefile softlock

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Nuitka/Nuitka#2688]
There is a problem with my environment, but I don't know why. When using `--onefile` option, the program is always acquiring a lock, and freezes.
This only happens with this version of python, I have python 3.10 and that works fine.
`Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.`

```
2.0.1
Commercial: None
Python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: E:\Python\py.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: Mismatch between Python binary ('E:\Python\py.exe' -> 'pei-x86-64') and C
Nuitka-Scons: compiler ('C:\bin\gcc.exe' -> 'pei-i386') arches, that compiler is ignored!
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```
(By the way, the gcc version downloaded by python3.10 and 3.8 is strangely different.)
```
# python -m nuitka 1.py --show-progress --onefile
Nuitka-Options: Used command line options: 1.py --show-progress --onefile
Nuitka: Starting Python compilation with Nuitka '2.0.1' on Python '3.8' commercial grade 'not
Nuitka: installed'.
Nuitka-Memory: Total memory usage before processing:: 35.61 MB (37343232 bytes)
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\nuitka\__main__.py", line 172, in <module>
    main()
  File "E:\Python\lib\site-packages\nuitka\__main__.py", line 158, in main
    MainControl.main()
  File "E:\Python\lib\site-packages\nuitka\MainControl.py", line 1120, in main
    _main()
  File "E:\Python\lib\site-packages\nuitka\MainControl.py", line 969, in _main
    main_module = _createMainModule()
  File "E:\Python\lib\site-packages\nuitka\MainControl.py", line 156, in _createMainModule
    main_module = buildMainModuleTree(
  File "E:\Python\lib\site-packages\nuitka\tree\Building.py", line 1224, in buildMainModuleTree
    stdlib_modules_names=detectStdlibAutoInclusionModules(),
  File "E:\Python\lib\site-packages\nuitka\freezer\ImportDetection.py", line 343, in detectStdlibAutoInclusionModules
    _stdlib_modules_names = _detectStdlibAutoInclusionModules()
  File "E:\Python\lib\site-packages\nuitka\freezer\ImportDetection.py", line 330, in _detectStdlibAutoInclusionModules
    return _detectImports(command=import_code)
  File "E:\Python\lib\site-packages\nuitka\freezer\ImportDetection.py", line 74, in _detectImports
    _stdout, stderr, exit_code = executeProcess(
  File "E:\Python\lib\site-packages\nuitka\utils\Execution.py", line 452, in executeProcess
    stdout, stderr = process.communicate(input=process_input)
  File "E:\Python\lib\subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "E:\Python\lib\subprocess.py", line 1395, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "E:\Python\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "E:\Python\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
1..py
```
print(1)
```

**Comment by kayhayen** [comment]
Your flavor not being detected probably means it's a very non-standard Python, what is it?

**Comment by ZzzzzzzSkyward** [comment]
>>> import sys
>>> sys.implementation
namespace(cache_tag='cpython-38', hexversion=50856176, name='cpython', version=sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0))
OK, since I know it is because the flavor is not detected, this may not be a bug.

**Comment by kayhayen** [comment]
The flavor is not that, this value is never changed by any flavor, e.g. Anaconda will have it too, and probably every other one too.

Nuitka not detecting the origin means it's not a supported one, and you seem incapable of telling which one it is. If that's like so, we better give up on this.

**Comment by ZzzzzzzSkyward** [comment]
Thanks! Then I'd better close it.
