### ISSUE TITLE
numpy: No module named 'secrets'

### ISSUE THREAD

**Issue by jjhesk** [Nuitka/Nuitka#2711]
Tried with build command:
```
python3.11 -m nuitka --standalone --plugin-enable=pylint-warnings,numpy --clang --prefer-source-code --warn-implicit-exceptions --follow-imports --prefer-source-code --output-dir=dist --include-data-dir='./lib/dat=./lib/dat' main.py
```

Before submitting an Issue, please review the
```
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'secrets'
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
2.1rc3
Commercial: None
Python: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /usr/local/bin/python3.11
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 14.0.0).
```

  If you are not providing the full output. The issue cannot be solved and will be considered
  `invalid`. The command outputs more than you think, and we are adding more all the time. We do not
  want to left guessing or trying things out to reproduce your issue.

- How did you install Nuitka and Python
virtual env, pip3.11 

  > python -m pip freeze
```
aiohttp==3.9.3
aiosignal==1.3.1
altgraph==0.17.4
attrs==23.2.0
base58==2.1.1
beautifulsoup4==4.12.3
bitarray==2.9.2
bitcoin==1.1.42
bitcoinlib==0.6.14
btclib==2023.7.12
btclib_libsecp256k1==0.4.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
cytoolz==0.12.3
ecdsa==0.18.0
et-xmlfile==1.1.0
eth-account==0.10.0
eth-hash==0.6.0
eth-keyfile==0.7.0
eth-keys==0.5.0
eth-rlp==1.0.1
eth-typing==4.0.0
eth-utils==3.0.0
eth_abi==5.0.0
fastecdsa==2.3.0
frozenlist==1.4.1
greenlet==3.0.3
hdwallet==2.2.1
hexbytes==0.3.1
idna==3.6
iniconfig==2.0.0
jeepney==0.8.0
json5==0.9.14
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
lru-dict==1.2.0
lz4==4.3.2
macholib==1.16.3
mnemonic==0.21
mpmath==1.3.0
multidict==6.0.5
numpy==1.26.2
openpyxl==3.1.2
packaging==23.2
pandas==2.1.4
parsimonious==0.9.0
pluggy==1.4.0
protobuf==4.25.2
py==1.11.0
pycparser==2.21
pycryptodome==3.19.0
pycryptodomex==3.19.0
pyinstaller==6.4.0
pyinstaller-hooks-contrib==2024.1
pynpm==0.2.0
pyotp==2.9.0
pytest==6.2.5
pytest-repeat==0.9.1
python-bitcointx==1.1.5
python-dateutil==2.8.2
pytz==2023.3.post1
pyunormalize==15.1.0
referencing==0.33.0
regex==2023.12.25
requests==2.31.0
rlp==4.0.0
rpds-py==0.17.1
six==1.16.0
soupsieve==2.5
SQLAlchemy==2.0.25
SQLiteAsJSON==1.0.4
sympy==1.12
tls-client==0.2.2
toml==0.10.2
toolz==0.12.1
typing_extensions==4.9.0
tzdata==2023.3
urllib3==2.1.0
web3==6.11.4
websockets==12.0
yarl==1.9.4

```
from the backtrack is was related to the reported paths:
```
Traceback (most recent call last):
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/main.py", line 3, in <module>
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/lib/app.py", line 6, in <module lib.app>
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/lib/lib.py", line 6, in <module lib.lib>
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/lib/com/req.py", line 12, in <module lib.com.req>
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/lib/com/util.py", line 7, in <module lib.com.util>
  File "/Users/xxxx/Documents/xxxx/dist/main.dist/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'secrets'
```

**Comment by kayhayen** [comment]
No reproducer, so there is nothing to do.

**Comment by KevinRodriguez777** [comment]
i don't see `secrets` in your `pip --freeze` output, you most likely need to install it before it works, but i agree, without an MRE, impossible to tell.

**Comment by kayhayen** [comment]
Probably somebody expecting a program that wouldn't run uncompiled to run compiled. Wouldn't be the first time.
