### ISSUE TITLE
SystemError: <built-in function __import__> returned a result with an exception set

### ISSUE THREAD

**Issue by Quicksticks-oss** [Nuitka/Nuitka#2714]
nuitka --version
```
1.7.9
Commercial: None
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc).
```

How did you install Nuitka and Python
`pip`

Trying to compile RVC but I get this error on runtime and I was wondering if anyone knew how to fix this :)

```
TypeError: bases must be types

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/example.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/rvc/modules/vc/modules.py", line 21, in <module rvc.modules.vc.modules>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/rvc/modules/vc/utils.py", line 3, in <module rvc.modules.vc.utils>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/fairseq/__init__.py", line 21, in <module fairseq>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/fairseq/logging/progress_bar.py", line 407, in <module fairseq.logging.progress_bar>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/torch/utils/tensorboard/__init__.py", line 12, in <module torch.utils.tensorboard>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/torch/utils/tensorboard/writer.py", line 12, in <module torch.utils.tensorboard.writer>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/tensorboard/compat/proto/event_pb2.py", line 6, in <module tensorboard.compat.proto.event_pb2>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/google/protobuf/descriptor.py", line 40, in <module google.protobuf.descriptor>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/media/reaktor/GithubRepos/Retrieval-based-Voice-Conversion/example.dist/google/protobuf/internal/api_implementation.py", line 104, in <module google.protobuf.internal.api_implementation>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
SystemError: <built-in function __import__> returned a result with an exception set
```
I'm not sure where or how to write an example that would output this error so I hope this is enough.

Provide in your issue the Nuitka options used
`nuitka --standalone main.py`

**Comment by KevinRodriguez777** [comment]
can you show us the code you tried to compile?

**Comment by Quicksticks-oss** [comment]
Just found the line that causes issues just try and import this.
`from fairseq import checkpoint_utils`

**Comment by KevinRodriguez777** [comment]
can you update to the latest nuitka version and try again?

**Comment by kayhayen** [comment]
@KevinRodriguez777 I think this is a direct delete, at least closing for lack of feedback and marking it as invalid
