### ISSUE TITLE
AssertionError: ()

### ISSUE THREAD

**Issue by EricDing618** [Nuitka/Nuitka#2715]
Nuitka:`1.1.0`
Python:`3.11.0`

```python
PASS 1: 99.8%|████████████████████████▉| 536/537, abcTraceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 924, in main
    main_module = _createNodeTree(filename=filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 208, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\optimizations\Optimization.py", line 343, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\optimizations\Optimization.py", line 333, in makeOptimizationPass
    current_module.setChild("functions", used_functions)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\nodes\NodeBases.py", line 605, in setChild
    assert old_value is not value, value
AssertionError: ()
```

**Comment by KevinRodriguez777** [comment]
Can you double check the Nuitka version? or are you really using `1.1.0`?

**Comment by kayhayen** [comment]
@KevinRodriguez777 this for me is a clear "invalid/delete" issue. I am not even sure 3.11 was actually supported very well in 1.1 at all.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by EricDing618** [comment]
@kayhayen Could I ask you something in Chinese? I can't speak English well,because I'm a junior high school student in China.

**Comment by kayhayen** [comment]
I am no longer responding to private questions about Nuitka, because they
end up invisible to everybody else, risking repetition from my side. I am
also getting too many such questions. Therefore please raise it in the
Github issue tracker and I will probably reply. Also I cannot do better
Chinese than Google Translate anyways. There are Chinese groups using
Nuitka, search for them to help you raise a proper issue or resolve yours.

Yours, Kay

Am Sa., 17. Feb. 2024 um 13:10 Uhr schrieb Eric学编程 ***@***.***
