### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by lrq51678** [Nuitka/Nuitka#2716]
Hello, I have manually copied the entire inflect package to the project, but I am still getting errors. The version of nuitka is 2.1rc2, and the version of Python is 3.11.5

Traceback (most recent call last):
  File "D:\准备编译\HR_Live\TTS.dist\TTS.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\webui.py", line 21, in <module webui>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\infer.py", line 6, in <module infer>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\text\cleaner.py", line 1, in <module text.cleaner>
    from text import chinese, english, cleaned_text_to_sequence

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\text\english.py", line 4, in <module text.english>
    from g2p_en import G2p

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\g2p_en\__init__.py", line 1, in <module g2p_en>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\g2p_en\g2p.py", line 19, in <module g2p_en.g2p>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\g2p_en\expand.py", line 10, in <module g2p_en.expand>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\准备编译\HR_Live\TTS.dist\inflect\__init__.py", line 2027, in <module inflect>
    class engine:

  File "D:\准备编译\HR_Live\TTS.dist\inflect\__init__.py", line 2048, in engine
    @validate_call

TypeError: 'module' object is not callable

**Comment by KevinRodriguez777** [comment]
copy pasting packages is not supported, without an minimal reproducible example it's impossible to help.

**Comment by lrq51678** [comment]
Okay, I'll try again. Thanks.
