### ISSUE TITLE
Getting `OSError: [Errno 22] Invalid argument` while making standalone!!

### ISSUE THREAD

**Issue by OnlinePage** [Nuitka/Nuitka#2718]
Hi I have just started with `Nuitka`, made some couple of small exes too.
I tired convert one of my script into single file standalone, although script is quite long and took almost 3.5 hrs to complete the `c compilation`:
My system details:
Amd Ryzen 5
16GB RAM, Windows 11

Now at last i encountered issue `OSError: [Errno 22] Invalid argument`. I tried to run the compilation again and WAITTT.. still the same issue.
Below is the complete log:

```python
myScript.py
Nuitka-Options: Used command line options: --follow-imports --onefile --standalone --plugin-enable=upx --windows-icon-from-ico=.\my_icon.ico
Nuitka-Options: --output-dir=.\dumps\ --output-filename=MyFasterExe.\myScript.py
Nuitka-Options: Following all imports is the default for onefile mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.0.3' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.2' in module 'numpy'.
Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.2' in module 'pandas'. 
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to
Nuitka-Plugins:anti-bloat: create Qt image objects.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                           
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 2956 files (no progress information available for this stage).
Nuitka-Scons: Compiled 2956 C files using clcache with 2091 cache hits and 865 cache misses.
Nuitka-Postprocessing: Adding 1 icon(s) from icon file '.\my_icon.ico'.
Nuitka-Plugins:data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\html.tpl' due to package data directory 'templates' for
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\html_style.tpl' due to package data directory 'templates' for       
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\html_table.tpl' due to package data directory 'templates' for       
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\latex.tpl' due to package data directory 'templates' for
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\latex_longtable.tpl' due to package data directory 'templates' for  
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\latex_table.tpl' due to package data directory 'templates' for      
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included data file 'pandas\io\formats\templates\string.tpl' due to package data directory 'templates' for
Nuitka-Plugins:data-files: 'pandas.io.formats'.
Nuitka-Plugins:data-files: Included 603 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka:WARNING: Report writing was prevented by exception OSError(22, 'Invalid argument'), use option '--experimental=debug-report-traceback'
Nuitka:WARNING: for full traceback.
Detecting used DLLs: 1.7%|▍                        | 2/117, PIL\_imaging.pydTraceback (most recent call last):
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\__main__.py", line 175, in <module>
    main()
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\__main__.py", line 161, in main
    MainControl.main()
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\MainControl.py", line 1131, in main
    _main()
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\MainControl.py", line 1023, in _main
    detectUsedDLLs(
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\freezer\Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\freezer\Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\plugins\Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 411, in decideAllowOutsideDependencies
    distribution = getDistributionFromModuleName(module_name)
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\utils\Distributions.py", line 217, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\utils\Distributions.py", line 196, in getDistributionsFromModuleName
    _package_to_distribution = _initPackageToDistributionName()
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\utils\Distributions.py", line 164, in _initPackageToDistributionName
    for package_name in getDistributionTopLevelPackageNames(distribution):
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\utils\Distributions.py", line 73, in getDistributionTopLevelPackageNames
    top_level_txt = _getDistributionMetadataFileContents(distribution, "top_level.txt")
  File "C:\Users\sexyuser1\MyPythonScripts\myvenv2\lib\site-packages\nuitka\utils\Distributions.py", line 62, in _getDistributionMetadataFileContents
    result = distribution.read_text(filename)
  File "C:\Users\sexyuser1\anaconda3\envs\my_conda_env1\lib\importlib\metadata\__init__.py", line 927, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "C:\Users\sexyuser1\anaconda3\envs\my_conda_env1\lib\pathlib.py", line 1135, in read_text
    return f.read()
OSError: [Errno 22] Invalid argument
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
``` 
I am unable figure it out why this happening, any help is highly appreicated!!!!!

**Comment by kayhayen** [comment]
Nuitka scans the package list and one of it is having a corrupted file, this happens for some people now. Trying reinstalling Anaconda, or wait for me to make Nuitka become more resilient about these things.

**Comment by kayhayen** [comment]
I think it can still be corrupted. If you were to find out what path it is working on, you could try reading the file yourself. An OSError of "invalid argument" can only really be something strange, unless we want to entertain the possibility of `importlib.metadata` being able to open a file, and then closing it before it reads it, which I at this point am not going to believe.

In the other corruption case I saw, what happened there is that the file failed to exist (due to corruption), and then no name could be determined for a distribution as a result. In your case, the top level file has a fallback code that may even work, if not the files list file is also broken, and at that point things get broken. However, it would appear that many times, that information is for a package you don't even use.

**Comment by kayhayen** [comment]
So, with my changes you should get a warning from `Nuitka-Metadata` now for every file it cannot access due to corruptions, this should allow us to tell what it is, and you can check where that comes from.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I updated factory, make sure to follow the instructions to actually update it on your end too, then it should be better.

**Comment by kayhayen** [comment]
Hm, seems that code didn't yet make its way to factory somehow, I need to check where it's at.

**Comment by KevinRodriguez777** [comment]
does following the pydantic error info and instructions not help?
also we would need a minimal working example in order to be able to test and fix locally.

**Comment by kayhayen** [comment]
Please make a new report for the `pydantic` issue please. We will keep track of it separately, the issue template will tell you what to provide us with, so we can resolve that too swiftly.

**Comment by kayhayen** [comment]
I am closing this one early for lack of general relevance, the changes are going to be in the hotfix 2.0.4 once it comes out.

**Comment by kayhayen** [comment]
This is part of the hotfix release 2.0.4 that I just made.
