### ISSUE TITLE
pyside6: Plugin issue while working on 'Plugin initialization failed'

### ISSUE THREAD

**Issue by bearsh** [Nuitka/Nuitka#2725]
```
pipenv run python -m nuitka --standalone --plugin-enable=pyside6 --follow-import-to=charset_normalizer.md__mypyc  --disable-console  --linux-onefile-icon=resources/images/logo.png flexconfigurator.py
Nuitka-Options: Used command line options: --standalone --plugin-enable=pyside6 --follow-import-to=charset_normalizer.md__mypyc --disable-console --linux-onefile-icon=resources/images/logo.png flexconfigurator.py
Traceback (most recent call last):
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/Plugins.py", line 123, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 1419, in __init__
    NuitkaPluginQtBindingsPluginBase.__init__(
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 79, in __init__
    sensible_qt_plugins = self._getSensiblePlugins()
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 218, in _getSensiblePlugins
    tuple(
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 238, in <genexpr>
    if self.hasPluginFamily(family)
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 393, in hasPluginFamily
    for plugin_dir in self.getQtPluginDirs()
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 357, in getQtPluginDirs
    qt_info = self._getQtInformation()
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 275, in _getQtInformation
    info = self.queryRuntimeInformationMultiple(
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/plugins/PluginBase.py", line 1186, in queryRuntimeInformationMultiple
    feedback = check_output([sys.executable, "-c", cmd], env=env)
  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/nuitka/utils/Execution.py", line 141, in check_output
    raise NuitkaCalledProcessError(exit_code, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/bin/python', '-c', '\\\nfrom __future__ import print_function\nfrom __future__ import absolute_import\n\ntry:\n   \n   import os\n   import PySide6.QtCore\nexcept ImportError:\n    import sys\n    sys.exit(38)\nprint(repr(PySide6.QtCore.QCoreApplication.libraryPaths()))\nprint("-" * 27)\nprint(repr(os.path.join(os.path.dirname(PySide6.__file__), \'plugins\')))\nprint("-" * 27)\nprint(repr(os.path.join(os.path.dirname(PySide6.__file__), \'..\', \'..\', \'..\', \'Library\', \'plugins\')))\nprint("-" * 27)\nprint(repr(PySide6.__version_info__))\nprint("-" * 27)\nprint(repr(getattr(PySide6, \'_nuitka_patch_level\', 0)))\nprint("-" * 27)\nprint(repr(PySide6.QtCore.QLibraryInfo.location(PySide6.QtCore.QLibraryInfo.TranslationsPath)))\nprint("-" * 27)\nprint(repr(PySide6.QtCore.QLibraryInfo.location(PySide6.QtCore.QLibraryInfo.LibraryExecutablesPath)))\nprint("-" * 27)\nprint(repr(PySide6.QtCore.QLibraryInfo.location(PySide6.QtCore.QLibraryInfo.DataPath)))\nprint("-" * 27)\n']' died with <Signals.SIGABRT: 6>. Error was b'Traceback (most recent call last):\n  File "signature_bootstrap.py", line 77, in bootstrap\n  File "signature_bootstrap.py", line 93, in find_incarnated_files\n  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__\n    self = cls._from_parts(args)\n  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts\n    drv, root, parts = self._parse_args(args)\n  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args\n    a = os.fspath(a)\nTypeError: expected str, bytes or os.PathLike object, not NoneType\nFatal Python error: could not initialize part 2\nPython runtime state: initialized\n\nCurrent thread 0x00007f734f9201c0 (most recent call first):\n  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed\n  File "<frozen importlib._bootstrap_external>", line 1176 in create_module\n  File "<frozen importlib._bootstrap>", line 571 in module_from_spec\n  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked\n  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load\n  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed\n  File "<frozen importlib._bootstrap>", line 1078 in _handle_fromlist\n  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/PySide6/__init__.py", line 64 in _setupQtDirectories\n  File "/home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/lib/python3.10/site-packages/PySide6/__init__.py", line 124 in <module>\n  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed\n  File "<frozen importlib._bootstrap_external>", line 883 in exec_module\n  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked\n  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load\n  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed\n  File "<frozen importlib._bootstrap>", line 992 in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load\n  File "<string>", line 8 in <module>\n\nExtension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, xxsubtype (total: 14)'.
FATAL: pyside6: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
```

```bash
$ pipenv run python -m nuitka --version
2.0.3
Commercial: None
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Flavor: Debian Python
Executable: /home/bearsh/.virtualenvs/flex-configurator-W-NwfveD/bin/python
OS: Linux
Arch: x86_64
Distribution: Neon (based on Ubuntu) 5.27
Version C compiler: /usr/bin/gcc (gcc 11).
```

```
pipenv graph
appimage-builder==1.1.0
├── docker [required: Any, installed: 7.0.0]
│   ├── packaging [required: >=14.0, installed: 23.2]
│   ├── requests [required: >=2.26.0, installed: 2.31.0]
│   │   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   │   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   │   ├── idna [required: >=2.5,<4, installed: 3.6]
│   │   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.1]
│   └── urllib3 [required: >=1.26.0, installed: 2.2.1]
├── emrichen [required: Any, installed: 0.4.0]
│   ├── jsonpath-rw [required: ~=1.4.0, installed: 1.4.0]
│   │   ├── decorator [required: Any, installed: 5.1.1]
│   │   ├── ply [required: Any, installed: 3.11]
│   │   └── six [required: Any, installed: 1.16.0]
│   ├── pyaml [required: ~=21.10, installed: 21.10.1]
│   │   └── PyYAML [required: Any, installed: 6.0.1]
│   └── PyYAML [required: Any, installed: 6.0.1]
├── lief [required: Any, installed: 0.14.1]
├── packaging [required: Any, installed: 23.2]
├── python-gnupg [required: Any, installed: 0.5.2]
├── pyyaml [required: >=5, installed: 6.0.1]
├── questionary [required: Any, installed: 2.0.1]
│   └── prompt-toolkit [required: >=2.0,<=3.0.36, installed: 3.0.36]
│       └── wcwidth [required: Any, installed: 0.2.13]
├── requests [required: Any, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.6]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.1]
├── roam [required: Any, installed: 0.3.1]
├── ruamel.yaml [required: Any, installed: 0.18.6]
│   └── ruamel.yaml.clib [required: >=0.2.7, installed: 0.2.8]
├── schema [required: Any, installed: 0.7.5]
│   └── contextlib2 [required: >=0.5.5, installed: 21.6.0]
└── urllib3 [required: Any, installed: 2.2.1]
ecdsa==0.18.0
└── six [required: >=1.9.0, installed: 1.16.0]
ft4222==1.10.0
hidapi==0.14.0
└── setuptools [required: >=19.0, installed: 69.1.0]
Nuitka==2.0.3
├── ordered-set [required: >=4.1.0, installed: 4.1.0]
└── zstandard [required: >=0.15, installed: 0.22.0]
Pillow==9.2.0
pyqtdarktheme==2.1.0
└── darkdetect [required: >=0.7.1,<0.8.0, installed: 0.7.1]
pyqtgraph==0.13.3
└── numpy [required: >=1.20.0, installed: 1.26.4]
PySide6==6.6.2
├── PySide6-Addons [required: ==6.6.2, installed: 6.6.2]
│   ├── PySide6-Essentials [required: ==6.6.2, installed: 6.6.2]
│   │   └── shiboken6 [required: ==6.6.2, installed: 6.6.2]
│   └── shiboken6 [required: ==6.6.2, installed: 6.6.2]
├── PySide6-Essentials [required: ==6.6.2, installed: 6.6.2]
│   └── shiboken6 [required: ==6.6.2, installed: 6.6.2]
└── shiboken6 [required: ==6.6.2, installed: 6.6.2]
python-box==7.1.1
```

**Comment by bearsh** [comment]
Mmh, this doesn't seem to be a Nuitka issue but a PySide-6.6.2 issue. It works fine with PySide-6.6.1 and furthermore my app does also not run with PySide-6.6.2 when run via python.

Sorry for the noise, I should have checked before...

**Comment by kayhayen** [comment]
@bearsh thanks for letting me know, deleting it
