### ISSUE TITLE
Windows. Failed build on the mounted network disk.

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2732]
Nuitka is running on the Windows 10 in VirtualBox.
Linux host directory "dd" shared to the virtual PC as a network disk "\\VBOXSVR\dd", which is automatically mounted as disk "Z:".
This is a standard way to share directories in VirtualBox with the guest Windows.
Building inside shared disk makes possible using of the host utilities and editors to edit source files.

Python installed from the official site, nuitka installed via pip.

  > python -m nuitka --version

```
2.0.5
Commercial: None
Python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

> cat 1.py
```
print("Hello world!")
```

> PS Z:\> python.exe -m nuitka 1.py
```
Nuitka-Options: Used command line options: 1.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka: Starting Python compilation with Nuitka '2.0.5' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\__main__.py", line 175, in <module>
    main()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\__main__.py", line 161, in main
    MainControl.main()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\MainControl.py", line 1131, in main
    _main()
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\MainControl.py", line 989, in _main
    result, scons_options = compileTree()
                            ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\MainControl.py", line 906, in compileTree
    result, scons_options = runSconsBackend()
                            ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\MainControl.py", line 757, in runSconsBackend
    runScons(
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\build\SconsInterface.py", line 276, in runScons
    options["result_name"] = getExternalUsePath(
                             ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 1182, in getExternalUsePath
    dirname = getWindowsShortPathName(os.path.dirname(filename))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 1107, in getWindowsShortPathName
    raiseWindowsError("getWindowsShortPathName for %s" % filename)
  File "C:\Program Files\Python311\Lib\site-packages\nuitka\utils\Utils.py", line 416, in raiseWindowsError
    raise WindowsError(
ProcessLookupError: [Errno 3] getWindowsShortPathName for \\VBoxSvr\dd\VBoxSvr\dd (The system cannot find the path specified.)
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
```

Crash report renamed to the txt-file is attached.
[nuitka-crash-report.txt](https://github.com/Nuitka/Nuitka/files/14446832/nuitka-crash-report.txt)

**Comment by kayhayen** [comment]
Ah, we had a solution for this and compiled programs at runtime, but that's of course different. I am not confident all the tools are working with the network paths rather than filenames, there is a reason we want to use short paths there, and MinGW64 is among those tools if I recall correctly. Not sure if it's possible (easily) to turn a network path into a drive letter using path.

**Comment by kayhayen** [comment]
The report hides `cwd` and so it's hard to tell, but you were not using `Z:` as the current working directory, but the server mount path, right?

**Comment by ioctl-user** [comment]
> The report hides `cwd` and so it's hard to tell, but you were not using `Z:` as the current working directory, but the server mount path, right?

Not sure I understand your question. Current path is namely disk "Z:" :
```
PS Z:\> pwd

Path
----
Z:\

PS Z:\> get-variable pwd

Name                           Value
----                           -----
PWD                            Z:\

```

**Comment by kayhayen** [comment]
Ok, so it seems the `\\VBoxSvr` comes from some `realpath` call then, so compiling on netdrives is broken entirely then.

**Comment by kayhayen** [comment]
I added a fix for that and it's going to be in 2.1, right now it's on the develop branch. I am closing this early, with the release being immanent.
