### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '=4'

### ISSUE THREAD

**Issue by CyberRSR** [Nuitka/Nuitka#2745]
```(base) c:\My_Documents\Work\alorAPI_setkaNG>python -m nuitka --onefile --mingw64 --lto=yes --disable-ccache --jobs==4 setkaNG.py
Nuitka-Options: Used command line options: --onefile --mingw64 --lto=yes --disable-ccache --jobs==4 setkaNG.py
Nuitka: Starting Python compilation with Nuitka '2.1' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:16') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:17') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:18') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:18') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:19') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:19') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:20') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:33') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'numba' in 'pandas.core._numba.extensions' (at
Nuitka-Plugins:WARNING: 'C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\_numba\extensions.py:257') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: options-nanny: Using module 'numba' (version 0.59.0) with incomplete support due to untrue condition 'not use_numba and standalone': Numba is not yet
Nuitka-Plugins:WARNING: fully working with Nuitka standalone, try to use '--noinclude-numba-mode=nofollow', but it may fail.
Nuitka-Plugins:WARNING: options-nanny: Module has parameter: Numba JIT is disabled by default in standalone mode, make a choice explicit with
Nuitka-Plugins:WARNING: '--module-parameter=numba-disable-jit=yes|no'
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka-Plugins:anti-bloat: Not including 'qtpy' automatically in order to avoid bloat, but this may cause: pandas will not be able to use Qt for clipboard interaction.
Nuitka-Plugins:anti-bloat: Not including 'PyQt5' automatically in order to avoid bloat, but this may cause: pandas will not be able to use Qt for clipboard interaction.
Nuitka-Plugins:matplotlib: Using configuration file or default backend 'QtAgg'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\__main__.py", line 161, in <module>
    main()
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\__main__.py", line 147, in main
    MainControl.main()
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\MainControl.py", line 1127, in main
    _main()
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\MainControl.py", line 979, in _main
    result, scons_options = compileTree()
                            ^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\MainControl.py", line 896, in compileTree
    result, scons_options = runSconsBackend()
                            ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\MainControl.py", line 747, in runSconsBackend
    runScons(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\build\SconsInterface.py", line 280, in runScons
    scons_command = _buildSconsCommand(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\build\SconsInterface.py", line 217, in _buildSconsCommand
    str(Options.getJobLimit()),
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nuitka\Options.py", line 1574, in getJobLimit
    return int(options.jobs)
           ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '=4'
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.`
[nuitka-crash-report.zip](https://github.com/Nuitka/Nuitka/files/14500341/nuitka-crash-report.zip)

New problem in MinGW?
```

**Comment by CyberRSR** [comment]
I try in same anaconda: 
`python -m nuitka --onefile --lto=yes --jobs==4 setkaNG.py`

have the same Error.

**Comment by kayhayen** [comment]
The use of `--jobs==4` ends up as `=4` for what is expected to be an integer value. That is not checked at call time and passed down to scons, which then falls down. The option parsing core could also handle this, but I don't want to outlaw values starting with an `=` sign.

I am adding a check to the options parsing to catch this.

**Comment by kayhayen** [comment]
Now on factory branch, integer conversion is checked early, and negative values are caught too.

> Nuitka-Options: Used command line options: --nofollow-imports --jobs=-1 tests/basics/AssertsTest.py
> FATAL: For --jobs value, use positive integer values onl, not, but not '-1'.

Your use of Nuitka is invalid, I agree however, that it can be hard to spot this mistake.
