### ISSUE TITLE
tensorflow: 'NoneType' object has no attribute 'pick_unused_port'

### ISSUE THREAD

**Issue by KevinRodriguez777** [Nuitka/Nuitka#2751]
requires:
tensorflow latest, nuitka latest, standalone build
code

```
import tensorflow as tf

ds = tf.data.Dataset.from_tensor_slices([1.0, 2.0, 3.0, 4.0])


@tf.function
def calc_mean(ds, length):
    n = 0.0
    m = tf.zeros(shape=length)
    for value in ds:
        n += 1.0
        delta = value - m
        m += delta / n
    return m


m = calc_mean(ds, 4)
print(m)
```

```
❯ nuitka --version
2.1
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Divine\Desktop\OSS contributions\Nuitka-850-tensorflow\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
error

```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\__init__.py", line 48, in <module tensorflow>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module tensorflow._api.v2.__internal__>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module tensorflow._api.v2.__internal__.distribute>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module tensorflow._api.v2.__internal__.distribute.combinations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\python\distribute\combinations.py", line 36, in <module tensorflow.python.distribute.combinations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NU24A2~1\MAIN~1.DIS\tensorflow\python\distribute\multi_worker_test_base.py", line 53, in <module tensorflow.python.distribute.multi_worker_test_base>
AttributeError: 'NoneType' object has no attribute 'pick_unused_port'
```

found while taking a look at #850

**Comment by kayhayen** [comment]
I been doing massive amounts of anti-bloat on this one for tensorflow, they changed how their imports work, and changed their test modules somewhat, resulting in test case being included, making the compilation also larger than necessary. That said, I also have a fix for when this module is being imported, but in the future it should not normally be. Still making some touchups to get tensorflow to work properly again.

**Comment by kayhayen** [comment]
This is solved on factory, however the other issue you reported becomes visible now.

**Comment by kayhayen** [comment]
Part of the 2.1.3 hotfix release I just made.
