### ISSUE TITLE
Support for hydra needs to be added

### ISSUE THREAD

**Issue by GuillaumeTong** [Nuitka/Nuitka#2752]
I have a script where I use [hydra](https://hydra.cc/docs/intro/#basic-example), which wraps around the main function, trying to create a spawn-context multiprocessing queue.

It works in the native python environment, but it fails after compiling with Nuitka

# Nuitka version

``` bash
$ python -m nuitka --version
2.0.6
Commercial: None
Python: 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/[...]/miniconda3/envs/nuitka-env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc 11).
```

# How did you install Nuitka and Python

Create conda env with `conda create -n nuitka-env python=3.10 libpython-static`, then `pip install -U nuitka`

# The specific PyPI names and versions

`hydra-core==1.1.2`

# A Short Example

``` python
import multiprocessing as mp
import hydra

@hydra.main()
def main(config):
    context = mp.get_context("spawn")
    q = context.Queue()

if __name__ == '__main__':
    main()
```

## Expected output when run without nuitka
(no action, warnings are due to not supplying options to hydra in order to keep the example concise):
``` bash
$ python process_queue_test.py
[...]/process_queue_test.py:16: UserWarning:
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main()
```

## Output with Nuitka
(build succeeds, but execution throws `BrokenPipeError`)
``` bash
$ python -m nuitka --run process_queue_test.py
Nuitka-Options: Used command line options: --run process_queue_test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.1' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 11).
Nuitka-Scons: Backend linking program with 10 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka: Keeping build directory 'process_queue_test.build'.
Nuitka: Successfully created 'process_queue_test.bin'.
Nuitka: Launching 'process_queue_test.bin'.
/home/guillaume/tests/20230307-nuitka-multiprocess/process_queue_test.py:16: UserWarning:
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main()
Error executing job with overrides: []
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/process_queue_test.py", line 34, in <module>
    main()
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/guillaume/tests/20230307-nuitka-multiprocess/process_queue_test.py", line 19, in main
    q = context.Queue()
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/synchronize.py", line 80, in __init__
    register(self._semlock.name, "semaphore")
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/resource_tracker.py", line 155, in register
    self._send('REGISTER', name, rtype)
  File "/home/guillaume/miniconda3/envs/nuitka-env/lib/python3.10/multiprocessing/resource_tracker.py", line 168, in _send
    nbytes = os.write(self._fd, msg)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by GuillaumeTong** [comment]
Additionally, here are 2 sample codes that compile and run without errors:

### Using "fork" instead of "spawn"
(Unfortunately, due to other parts of my code base, I have to use "spawn" in my app)

``` python
import multiprocessing as mp
import hydra

@hydra.main()
def main(config):
    context = mp.get_context("fork")
    q = context.Queue()

if __name__ == '__main__':
    main()
```

### Without Hydra
(my app heavily relies on Hydra for configuration)

``` python
import multiprocessing as mp

def main():
    context = mp.get_context("spawn")
    q = context.Queue()

if __name__ == '__main__':
    main()
```

**Comment by kayhayen** [comment]
With the hydra I happened to have installed (hydra-core==1.0.7), I got this:

```
Traceback (most recent call last):
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/utils.py", line 198, in run_and_report
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/utils.py", line 320, in <lambda>
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/hydra.py", line 73, in create_main_hydra2
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/config_loader_impl.py", line 79, in __init__
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/config_repository.py", line 22, in __init__
  File "/home/hayen/repos/Py2C/Mini.dist/hydra/_internal/sources_registry.py", line 29, in resolve
ValueError: No config source registered for schema pkg, supported types : []
```

**Comment by GuillaumeTong** [comment]
Alright, it seems like I was a bit too aggressive in trying to simplify the provided example, and hydra is now crashing on some versions due to not being provided with a config path. Here is an updated example that should run more smoothly, but requires creating the `configs` dir:

``` python
import multiprocessing as mp
import hydra

@hydra.main(config_path="configs/")
def main(config):
    context = mp.get_context("spawn")
    q = context.Queue()
    print(config)

if __name__ == '__main__':
    main()
```
Tested with `hydra-core==1.0.7`
``` bash
$ mkdir configs
$ python process_queue_test.py +a=0 +b=8
{'a': 0, 'b': 8}
$ python -m nuitka --run process_queue_test.py +a=0 +b=8
[...]
BrokenPipeError: [Errno 32] Broken pipe
[...]
AssertionError
```

**Comment by kayhayen** [comment]
So, your original example works for me now, adding a few implicit dependencies for hydra plugins and data files needed from "conf" directory. The crash from multiprocessing went away too, so I figure that is it.

**Comment by kayhayen** [comment]
This is part of the 2.1.1 hotfix release I made

**Comment by GuillaumeTong** [comment]
Sorry, the issue still seems to be the same for me, after getting 2.1.1 via `pip install nuitka==2.1.1`

**Comment by GuillaumeTong** [comment]
Could you clarify what you mean by "adding a few implicit dependencies for hydra plugins"?

**Comment by kayhayen** [comment]
I added that to Nuitka, but seems I lied about adding it to the hotfix.

```
- module-name: 'hydra' # checksum: 380a0a91
  data-files:
    dirs:
      - 'conf'

- module-name: 'hydra.core.plugins' # checksum: f4d9feae
  implicit-imports:
    - depends:
        - 'hydra._internal.core_plugins.*'
        - 'hydra_plugins.*'
```

**Comment by kayhayen** [comment]
It's on the 2.1.2 branch that I have not yet made stable.

**Comment by kayhayen** [comment]
Part of the 2.1.3 hotfix release I just made.

**Comment by GuillaumeTong** [comment]
I am still seeing the same issue on both 2.1.2, and 2.1.3 from pip

**Comment by KevinRodriguez777** [comment]
> I am still seeing the same issue on both 2.1.2, and 2.1.3 from pip

both examples shown here work for me, what error do you get?

**Comment by GuillaumeTong** [comment]
Is there any chance you are testing with a development version containing the fix, but it has not reached the pip releases?

**Comment by kayhayen** [comment]
I just checked, the history, and it's actually already in 2.1.2 indeed, commit 83d94f4e725aa907ea81c8c6f26ceda23049327d and I don't know how much not using `--standalone` makes a difference there. I feel it should not, but maybe it does, I think multiprocessing is explicitly tested in that configuration though.

**Comment by kayhayen** [comment]
> Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.

That's probably causing the multiprocessing plugin to not do its work. You would have to follow/include at least that at least or else, it cannot work I think.

**Comment by GuillaumeTong** [comment]
Good to hear the fix is released already. `--standalone` does do the trick here, the following command succeeds:
`python -m nuitka --standalone --run original.py +a=0 +b=8`

However, I cannot use `--standalone` in my project due to some other packages causing issues (as I recall, mainly librosa and fairseq).

Trying to follow/include multiprocessing, I tried both `--include-package=multiprocessing` and `--enable-plugins=multiprocessing` with no success.

**Comment by kayhayen** [comment]
After enabling tensorflow JIT, we can look into Numba JIT, maybe that will work too soon enough, I guess 2.3 days.
