### ISSUE TITLE
[Shapely]Shapely ImportError after compile and run

### ISSUE THREAD

**Issue by tedwgit** [Nuitka/Nuitka#2753]
- When I import and use shapely (2.0.3) in my Python code, compile it into an executable file and run it, ImportError would happen; the program works normally if run directly under Python.
- Code is compiled under MiniConda, but should not be a conda problem as everything works well (even if compiled into an exe) without shapely imported.
- There are several reported issues related to shapely, but seems all of them are kind of long time ago (> 1 year), thus I guess this is probably a new issue.

**Nuitka Version**
```
(dpu64) D:\Src\Shapely_Nuitka_Test>python -m nuitka --version
2.1
Commercial: None
Python: 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\Miniconda3\envs\dpu64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).
```

**How did you install Nuitka and Python**
- I use MiniConda to create a Python environment, and install Nuitka through "pip install nuitka". 
- I think it should not be a conda problem as everything works well (even if compiled into an exe) without shapely imported.

**Shapely Version**
shapely==2.0.3

**Code example to reproduce this issue**
```
from shapely.geometry import Polygon

def test_shapely():
    # calculate gamut coverage
    x_list = [0.680, 0.265, 0.150]
    y_list = [0.320, 0.690, 0.060]
    triangle = Polygon([(x_list[0], y_list[0]), (x_list[1], y_list[1]), (x_list[2], y_list[2])])
    return triangle

if __name__ == "__main__":
    anyVal = test_shapely()
```

**Nuitka options / cmd**
`python -m nuitka --standalone --output-dir=out ShapelyNuitkaTest.py`

**Error message after run**
```
D:\Src\Shapely_Nuitka_Test\out\ShapelyNuitkaTest.dist>ShapelyNuitkaTest.exe
Traceback (most recent call last):
  File "D:\Src\SHAPEL~1\out\SHAPEL~1.DIS\ShapelyNuitkaTest.py", line 1, in <module>
  File "D:\Src\SHAPEL~1\out\SHAPEL~1.DIS\shapely\__init__.py", line 28, in <module shapely>
ImportError
```

**Comment by KevinRodriguez777** [comment]
This works fine on normal non-conda nuitka, might be a conda error.

**Comment by KRRT7** [comment]
I think we can just close this, can't repro

**Comment by kayhayen** [comment]
Shapely ought to work for a long time indeed.
