### ISSUE TITLE
python program using cherrypy, doesn´t work

### ISSUE THREAD

**Issue by nauj69** [Nuitka/Nuitka#2754]
the hello world program example with cherrypy
compiles but doesn't work, seems to fail the import 

version Im using is.....

0.6.19.1
Commercial: None
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu 22.04.2

And the error is......

Traceback (most recent call last):
  File "/home/pi/Bino2/src/HolaMundo.py", line 1, in <module>
    import cherrypy
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/nauj/.local/lib/python3.10/site-packages/cherrypy/__init__.py", line 66, in <module cherrypy>
    from ._cperror import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/nauj/.local/lib/python3.10/site-packages/cherrypy/_cperror.py", line 135, in <module cherrypy._cperror>
    from cherrypy.lib import httputil as _httputil
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/nauj/.local/lib/python3.10/site-packages/cherrypy/lib/httputil.py", line 20, in <module cherrypy.lib.httputil>
    import jaraco.collections
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/nauj/.local/lib/python3.10/site-packages/jaraco/collections/__init__.py", line 11, in <module jaraco.collections>
    import jaraco.text
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/nauj/.local/lib/python3.10/site-packages/jaraco/text/__init__.py", line 231, in <module jaraco.text>
    files(__name__).joinpath('Lorem ipsum.txt').read_text(encoding='utf-8')
  File "/usr/lib/python3.10/importlib/abc.py", line 378, in read_text
    with self.open(encoding=encoding) as strm:
  File "/usr/lib/python3.10/importlib/_adapters.py", line 54, in open
    raise ValueError()
ValueError

Any clues on how to fix it?
jjps69@hotmail.com

**Comment by KevinRodriguez777** [comment]
we need a minimal reproducible example.

**Comment by KevinRodriguez777** [comment]
just noticed you're using nuitka version 0.6.19.1, which is very old, update to latest and try again.

**Comment by kayhayen** [comment]
Please open a new issue if it's still an issue with Nuitka 2.1 or higher. This one looks familiar though and will go away.
