### ISSUE TITLE
AttributeError: partially initialized module 'keras'

### ISSUE THREAD

**Issue by KevinRodriguez777** [Nuitka/Nuitka#2775]
requirements
`pip install tensorflow nuitka`
code

```py
import keras
from keras import layers
import numpy as np

# Parameters for the model and dataset.
TRAINING_SIZE = 50000
DIGITS = 3
REVERSE = True
MAXLEN = DIGITS + 1 + DIGITS


class CharacterTable:
    def __init__(self, chars):
        self.chars = sorted(set(chars))
        self.char_indices = dict((c, i) for i, c in enumerate(self.chars))
        self.indices_char = dict((i, c) for i, c in enumerate(self.chars))

    def encode(self, C, num_rows):
        x = np.zeros((num_rows, len(self.chars)))
        for i, c in enumerate(C):
            x[i, self.char_indices[c]] = 1
        return x

    def decode(self, x, calc_argmax=True):
        if calc_argmax:
            x = x.argmax(axis=-1)
        return "".join(self.indices_char[x] for x in x)


# All the numbers, plus sign and space for padding.
chars = "0123456789+ "
ctable = CharacterTable(chars)

questions = []
expected = []
seen = set()
print("Generating data...")
while len(questions) < TRAINING_SIZE:
    f = lambda: int("".join(np.random.choice(list("0123456789")) for i in range(np.random.randint(1, DIGITS + 1))))
    a, b = f(), f()

    key = tuple(sorted((a, b)))
    if key in seen:
        continue
    seen.add(key)
    q = "{}+{}".format(a, b)
    query = q + " " * (MAXLEN - len(q))
    ans = str(a + b)

    ans += " " * (DIGITS + 1 - len(ans))
    if REVERSE:
        query = query[::-1]
    questions.append(query)
    expected.append(ans)
print("Total questions:", len(questions))
print("Vectorization...")
x = np.zeros((len(questions), MAXLEN, len(chars)), dtype=bool)
y = np.zeros((len(questions), DIGITS + 1, len(chars)), dtype=bool)
for i, sentence in enumerate(questions):
    x[i] = ctable.encode(sentence, MAXLEN)
for i, sentence in enumerate(expected):
    y[i] = ctable.encode(sentence, DIGITS + 1)

# Shuffle (x, y) in unison as the later parts of x will almost all be larger
# digits.
indices = np.arange(len(y))
np.random.shuffle(indices)
x = x[indices]
y = y[indices]

# Explicitly set apart 10% for validation data that we never train over.
split_at = len(x) - len(x) // 10
(x_train, x_val) = x[:split_at], x[split_at:]
(y_train, y_val) = y[:split_at], y[split_at:]

print("Training Data:")
print(x_train.shape)
print(y_train.shape)

print("Validation Data:")
print(x_val.shape)
print(y_val.shape)

"""
## Build the model
"""

print("Build model...")
num_layers = 1  # Try to add more LSTM layers!

model = keras.Sequential()
model.add(layers.Input((MAXLEN, len(chars))))
model.add(layers.LSTM(128))

model.add(layers.RepeatVector(DIGITS + 1))

for _ in range(num_layers):
    model.add(layers.LSTM(128, return_sequences=True))

# Apply a dense layer to the every temporal slice of an input. For each of step
# of the output sequence, decide which character should be chosen.
model.add(layers.Dense(len(chars), activation="softmax"))
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.summary()

"""
## Train the model
"""

# Training parameters.
epochs = 30
batch_size = 32

# Formatting characters for results display.
green_color = "\033[92m"
red_color = "\033[91m"
end_char = "\033[0m"


for epoch in range(1, epochs):
    print()
    print("Iteration", epoch)
    model.fit(
        x_train,
        y_train,
        batch_size=batch_size,
        epochs=1,
        validation_data=(x_val, y_val),
    )
    # Select 10 samples from the validation set at random so we can visualize
    # errors.
    for i in range(10):
        ind = np.random.randint(0, len(x_val))
        rowx, rowy = x_val[np.array([ind])], y_val[np.array([ind])]
        preds = np.argmax(model.predict(rowx, verbose=0), axis=-1)
        q = ctable.decode(rowx[0])
        correct = ctable.decode(rowy[0])
        guess = ctable.decode(preds[0], calc_argmax=False)
        print("Q", q[::-1] if REVERSE else q, end=" ")
        print("T", correct, end=" ")
        if correct == guess:
            print(f"{green_color}☑ {guess}{end_char}")
        else:
            print(f"{red_color}☒ {guess}{end_char}")

"""
You'll get to 99+% validation accuracy after ~30 epochs.
"""
```

setup:
you will have to remove this standard YAML entry

```yaml
- module-name: 'tensorflow.python.distribute.multi_worker_test_base' # checksum: 3d614bbf
  anti-bloat:
    - description: 'remove useless tensorflow testing usage'
      replacements_plain:
        'import unittest': 'test = None'
        'from tensorflow.python.framework import test_util': 'test_util = None'
        'from tensorflow.python.platform import test': 'test = None'
```
in order to avoid this error after compilation

```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\main.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\__init__.py", line 8, in <module keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\_tf_keras\__init__.py", line 1, in <module keras._tf_keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\_tf_keras\keras\__init__.py", line 8, in <module keras._tf_keras.keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\activations\__init__.py", line 8, in <module keras.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\__init__.py", line 1, in <module keras.src>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\activations\__init__.py", line 3, in <module keras.src.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\activations\activations.py", line 1, in <module keras.src.activations.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\__init__.py", line 33, in <module keras.src.backend>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\tensorflow\__init__.py", line 1, in <module keras.src.backend.tensorflow>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\tensorflow\core.py", line 4, in <module keras.src.backend.tensorflow.core>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\__init__.py", line 45, in <module tensorflow>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module tensorflow._api.v2.__internal__>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module tensorflow._api.v2.__internal__.distribute>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module tensorflow._api.v2.__internal__.distribute.combinations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\python\distribute\combinations.py", line 36, in <module tensorflow.python.distribute.combinations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\python\distribute\multi_worker_test_base.py", line 53, in <module tensorflow.python.distribute.multi_worker_test_base>
AttributeError: 'NoneType' object has no attribute 'pick_unused_port'
```
after this is compiled with the removed YAML entry we get

```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\__init__.py", line 8, in <module keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\_tf_keras\__init__.py", line 1, in <module keras._tf_keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\_tf_keras\keras\__init__.py", line 8, in <module keras._tf_keras.keras>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\activations\__init__.py", line 8, in <module keras.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\__init__.py", line 1, in <module keras.src>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\activations\__init__.py", line 3, in <module keras.src.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\activations\activations.py", line 1, in <module keras.src.activations.activations>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\__init__.py", line 33, in <module keras.src.backend>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\tensorflow\__init__.py", line 1, in <module keras.src.backend.tensorflow>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\keras\src\backend\tensorflow\core.py", line 4, in <module keras.src.backend.tensorflow.core>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\__init__.py", line 499, in <module tensorflow>
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\python\util\lazy_loader.py", line 181, in __getattr__
  File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\python\util\lazy_loader.py", line 149, in _initialize
AttributeError: partially initialized module 'keras' has no attribute '__version__' (most likely due to a circular import)
```

i suspect this has to do with the lazy loading itself.

**Comment by kayhayen** [comment]
The portpicker function can actually be inlined, I will do that instead of giving up on it, but we can also try to get rid of it too, since it seems to be a test code itself, checking it out now with `--noinclude-custom-mode=tensorflow.python.distribute.multi_worker_test_base:error` and lets see if that helps, pushing the bloat problem closer to its origin.

**Comment by kayhayen** [comment]
This reproduces it for me too `from tensorflow.experimental import dtensor` causing this:

```
  File "C:\Users\kayha\repos\Py2C\MINI3~1.DIS\keras\src\backend\tensorflow\distribution_lib.py", line 10, in <module keras.src.backend.tensorflow.distribution_lib>
ModuleNotFoundError: No module named 'tensorflow.experimental'
```

I don't see how it doesn't work, indeed something the lazy loader would be supposed to do, but is not happening with tensorflow or keras somehow. The `tensorflow.experimental` will only be set when the code returns from that import.

**Comment by kayhayen** [comment]
So, I traced this down to where it crashes, and it seems that the `tf` imported nearby, does have the `experimental` name. Now I am not yet convinced this can be a import mechanic error, but at first glance it's non-obvious why it wouldn't work in this case, and I will have to look into this.

**Comment by kayhayen** [comment]
So, this is self inflicted damage.

```
      append_plain: |
        import sys
        sys.modules["tensorflow.compat"] = compat
        sys.modules["tensorflow.compat.v1"] = compat.v1
        sys.modules["tensorflow.compat.v2"] = compat.v2
        sys.modules["tensorflow.compat.v1.logging"] = compat.v1.logging
        sys.modules["tensorflow.compat.v2.experimental"] = compat.v2.experimental
        sys.modules["tensorflow.keras"] = keras
        sys.modules["tensorflow.keras.layers"] = keras.layers
        sys.modules["tensorflow.keras.activations"] = keras.activations
        sys.modules["tensorflow.keras.models"] = keras.models
```

This triggers the lazy loader I think, and then the bad thing happens. There is no line for this:

```
File "C:\Users\Divine\Desktop\OSSCON~1\NUITKA~1\1242-S~1\MAIN~1.DIS\tensorflow\__init__.py", line 499, in <module tensorflow>
```

So something in the import design changed there at some time. Now question is of course, what version needed that, and what version doesn't need it anymore, and did it need it for `keras` ever. These things have critically underdocumented history. I guess, the way forward is to make use see old tensorflow works as is, and then make newest one work, and then bisect to the point where it fails. Given the time a single compilation of these takes, no a quick thing.

**Comment by KevinRodriguez777** [comment]
removing your append_plain results in `ModuleNotFoundError: No module named 'tensorflow.experimental'`
keeping it, still gives the `AttributeError: partially initialized module 'keras' has no attribute '__version__' (most likely due to a circular import)` on factory

**Comment by kayhayen** [comment]
Part of the 2.1.4 hotfix release.
