### ISSUE TITLE
assert memory_usage_name not in _memory_infos - AssertionError

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#2786]
I'm testing functions and see errors:
```
Traceback (most recent call last):
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\MainControl.py", line 1127, in main
    _main()
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\MainControl.py", line 970, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\MainControl.py", line 246, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\optimizations\Optimization.py", line 330, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\optimizations\Optimization.py", line 279, in makeOptimizationPass
    _traceProgressModuleStart(current_module)
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\optimizations\Optimization.py", line 213, in _traceProgressModuleStart
    reportMemoryUsage(
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\utils\MemoryUsage.py", line 122, in reportMemoryUsage
    memory_usage = collectMemoryUsageValue(identifier)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SOFTWARE\Python311-venv\Lib\site-packages\nuitka\utils\MemoryUsage.py", line 99, in collectMemoryUsageValue
    assert memory_usage_name not in _memory_infos
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
 - Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.1.2
Nuitka-2.1.2-cp311-cp311-win_amd64.whl size=3291853 sha256=574f57890252819ffe292fdcb4171e2f45cffd1b16d909b986b224e64bae3a32
 
- How did you install Nuitka and Python

pip

**Comment by kayhayen** [comment]
As a reminder to you, options given and reproducer are needed always.

**Comment by kayhayen** [comment]
I added on the factory branch a debugging enhancement, that will output the memory name that conflicts, this might give an idea next time this happens absent a reproducer.

**Comment by ManPython** [comment]
> First question of order would of course be what name is a duplicate there.

I meet this with many variations with parameter `--show-memory`

**Comment by kayhayen** [comment]
Closing for lack of feedback.
