### ISSUE TITLE
Problem error ModuleNotFoundError: No module named 'sspilib.raw._text'

### ISSUE THREAD

**Issue by musashi919** [Nuitka/Nuitka#2821]
When I use from `requests_ntlm import HttpNtlmAuth` and compile it into a windows console program and then run that program I receive an error 

```
nuitka --onefile token_test.py
----------------------
Python 3.12.3  64bit
Python 3.10.5  64bit
Python 3.7.8   64bit
Name: Nuitka
Version: 2.1.6
Name: requests-ntlm
Version: 1.2.0
```

sample code:

```python
from requests_ntlm import HttpNtlmAuth


import pwinput



def main():
    print("\n┌───────────────────────────────────┐")
    print("│ Please enter your  log-in details │")
    print("└───────────────────────────────────┘")
    print("Username:")
    username = input()
    password = pwinput.pwinput(prompt='Password: ')
        
if __name__ == "__main__":
    main();
```

Error
-----------------------------------
```none
*Traceback (most recent call last):
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\token_test.py", line 4, in <module>
    import requests_ntlm
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\requests_ntlm\__init__.py", line 1, in <module requests_ntlm>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\requests_ntlm\requests_ntlm.py", line 11, in <module requests_ntlm.requests_ntlm>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\spnego\__init__.py", line 26, in <module spnego>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\spnego\auth.py", line 10, in <module spnego.auth>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\spnego\_negotiate.py", line 31, in <module spnego._negotiate>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\spnego\_sspi.py", line 39, in <module spnego._sspi>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\sspilib\__init__.py", line 6, in <module sspilib>
  File "C:\Users\matt_2\AppData\Local\Temp\ONEFIL~2\sspilib\raw\__init__.py", line 8, in <module sspilib.raw>
  File "src\\sspilib\\raw\\_context_attributes.pyx", line 1, in init sspilib.raw._context_attributes
  File "src\\sspilib\\raw\\_security_context.pyx", line 1, in init sspilib.raw._security_context
  File "src\\sspilib\\raw\\_credential.pyx", line 1, in init sspilib.raw._credential
ModuleNotFoundError: No module named 'sspilib.raw._text'*
```

--------------------------------

Pyinstaller had the exact same issue [see here](https://github.com/pyinstaller/pyinstaller/issues/8136)
This was fixed in pyinstaller by compiling the exe with `--collect-submodules=sspilib`
There does not seem to be a similar option with nuitka

I have tried multiple versions of python and had the same results
Pyinstaller works for me at home but I am unable to use that within the office which is why I need Nuitka

**Comment by kayhayen** [comment]
No such problem on Linux, where I first tried.

**Comment by musashi919** [comment]
I managed to get it working by downgrading requests-ntlm to ==1.1.0

**Comment by kayhayen** [comment]
On Windows, I found it's an issue of `sspilib` but it was easy to add its implicit dependency.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by musashi919** [comment]
Works!

**Comment by SarthakNikhal** [comment]
@kayhayen Is this issue still open? Can I work on it?

**Comment by kayhayen** [comment]
@SarthakNikhal it's open because it's not yet in stable, but it's on the factory branch already and will be part of 2.2 and soon a pre-release at least, i.e. develop

**Comment by kayhayen** [comment]
This is part of the current pre-release and on develop now.

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
