### ISSUE TITLE
Unable to compile with specific library versions, I tried compiling with nuitka using a speicifc (older) package version of discord.py

### ISSUE THREAD

**Issue by Tore09** [Nuitka/Nuitka#2849]
output:
Traceback (most recent call last):
  File "C:\Users\tobia\AppData\Local\Temp\ONEFIL~1\main.py", line 4, in <module>
    import gratient

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tobia\AppData\Local\Temp\ONEFIL~1\main.py", line 18, in <module multidist-1-main>
    client = discord.Client()

TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

'intents' is an argument that is required in todays version of discord.py, however it is not required in the version of discord.py my code is running (1.7.3)

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
