### ISSUE TITLE
playwright error

### ISSUE THREAD

**Issue by maxurovich** [Nuitka/Nuitka#2851]
Hi all, I want to use nuitka to compile my code in which I use playwright, but after compiling I get an error , I saw a similar topic in this section, but never found a solution, please help me a lot. 

error:
FileNotFoundError: [WinError 2] The system cannot find the file specified
Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)>
Traceback (most recent call last):
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\concurrent\futures\thread.py", line 58, in run
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\spammer.py", line 133, in main_func
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\spammer.py", line 217, in main_emulation_func
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\spammer.py", line 148, in main_spam_func
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\playwright\sync_api\_context_manager.py", line 77, in __enter__
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\playwright\sync_api\_context_manager.py", line 56, in greenlet_main
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\playwright\_impl\_connection.py", line 263, in run_as_sync
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\playwright\_impl\_connection.py", line 272, in run
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\playwright\_impl\_transport.py", line 120, in connect
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\subprocess.py", line 223, in create_subprocess_exec
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\base_events.py", line 1708, in subprocess_exec
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\windows_events.py", line 399, in _make_subprocess_transport
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\base_subprocess.py", line 36, in __init__
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\windows_events.py", line 929, in _start
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\asyncio\windows_utils.py", line 153, in __init__
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\subprocess.py", line 1026, in __init__
  File "C:\Users\marvel\AppData\Local\Temp\ON9CAD~1\subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

Here's the command I use to compile - nuitka --onefile --follow-imports --standalone --include-module=Crypto.Cipher._pkcs1_decode --enable-plugin=tk-inter main.py

Also if I run the source py file all the paths are found and everything works, the driver as far as I understand is stored in the global path and this should not be a problem, but for some reason it doesn't work as it should.

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
