### ISSUE TITLE
playwright can't find the driver after compilation

### ISSUE THREAD

**Issue by orislegit** [Nuitka/Nuitka#2856]
python ：3.11.9
nuitka ： 2.2.1
playwright ：1.43.0

`python -m nuitka --version`
```
2.2.1
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\marvel\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
How did you install Nuitka and Python
`pip install`

I want to use nuitka to compile my code in which I use playwright, but after compiling I get an error , I saw a similar topic in this section, but never found a solution, please help me a lot.

error:
```
FileNotFoundError: [WinError 2] The system cannot find the file specified
Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)>
Traceback (most recent call last):
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\concurrent\futures\thread.py", line 58, in run
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\spammer.py", line 133, in main_func
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\spammer.py", line 217, in main_emulation_func
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\spammer.py", line 148, in main_spam_func
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\playwright\sync_api_context_manager.py", line 77, in enter
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\playwright\sync_api_context_manager.py", line 56, in greenlet_main
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\base_events.py", line 654, in run_until_complete
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\playwright_impl_connection.py", line 263, in run_as_sync
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\playwright_impl_connection.py", line 272, in run
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\playwright_impl_transport.py", line 120, in connect
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\subprocess.py", line 223, in create_subprocess_exec
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\base_events.py", line 1708, in subprocess_exec
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\windows_events.py", line 399, in _make_subprocess_transport
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\base_subprocess.py", line 36, in init
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\windows_events.py", line 929, in _start
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\asyncio\windows_utils.py", line 153, in init
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\subprocess.py", line 1026, in init
File "C:\Users\marvel\AppData\Local\Temp\ON9CAD1\subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Here's the command I use to compile -
nuitka --onefile --follow-imports --standalone --include-module=Crypto.Cipher._pkcs1_decode --enable-plugin=tk-inter main.py

Also if I run the source py file all the paths are found and everything works, the driver as far as I understand is stored in the global path and this should not be a problem, but for some reason it doesn't work as it should.

**THIS THREAD DID NOT HELP ME IN SOLVING MY PROBLEM, I TRIED DOING EXACTLY THE SAME THING**
https://github.com/Nuitka/Nuitka/issues/1029

**Comment by kayhayen** [comment]
Creating duplicates on purpose makes no sense esp. if you even fail to provide the requested minimal example
