### ISSUE TITLE
I have encountered common opencv-python problem: ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

### ISSUE THREAD

**Issue by bjpietrzak** [Nuitka/Nuitka#2861]
Docker version: 26.1.2
Docker image: python:3.11-bullseye
Python version: 3.11.9
Nautika version: 2.2.2 and 2.3rc3

Build command: 
python -m nuitka --follow-imports main.

Output of the build:

```
Nuitka-Options: Used command line options: --follow-imports main.py
Nuitka: Starting Python compilation with Nuitka '2.2.2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                                  
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                    
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 10).
Nuitka-Scons: Backend linking program with 402 files (no progress information available for this stage).
Nuitka-Scons: Compiled 401 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 401
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.bin'.
```
How I run the binary: ./main.bin

Run output:
```
Traceback (most recent call last):
  File "/app/cython_building/main.py", line 4, in <module>
    from sco.logger import logger
    
  File "/app/cython_building/sco/__init__.py", line 2, in <module sco>
    import cv2
    
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module cv2>
    bootstrap()
    
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")

  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module cv2>
    bootstrap()
    
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')

ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

I have installed python via docker image `docker pull python:3.11-bullseye` and run it on my project. I have installed Nuitka via pip: `pip install Nuitka`. Later when I couldn't solve the problem I tried it on my local system (Ubuntu 22.04, Python 3.11 - installed via apt get, Nuitka installed via `python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`

* PyPI:
The only package that matters is opencv. I have tried two versions, same problem:
- 4.6.0.66
- 4.9.0.80

* I have tried hello world. It works.

* How to replicate:
```py
# test.py
import cv2

print('Hello world!')
```
Command build: python -m nuitka --follow-imports test.py

**Comment by bjpietrzak** [comment]
Ok! I can see that the --follow-imports command is causing this behaviour. However, I need to keep looking for a solution. My project comprises a couple of modules stored in separate directories:

.
├── config
├── main.py
├── dir1
│   ├── file6.py
│   ├── file5.py
│   ├── file4.py
│   ├── file3.py
│   ├── file2.py
│   ├── file1.py
│   ├── dir2
│   │   ├── file3.py
│   │   ├── file2.py
│   │   └── file1.py
│   └── dir1
│       ├── file4py
│       ├── file2.py
│       ├── file2.py
│       └── file1.py
└── setup.py

**Comment by bjpietrzak** [comment]
When I try to build this project with this command `python -m nuitka --onefile main.py` I get this error message:
```
FATAL: anti-bloat: Error, failed to evaluate expression "textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')" in this context, exception was '[Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/cv2/config-3.py''.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```
I'm passing the content of nuitika-crash-report.xml below:
```
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.2.2" nuitka_commercial_version="not installed" completion="error exit message (1)" exit_message="anti-bloat: Error, failed to evaluate expression &quot;textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')&quot; in this context, exception was '[Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/cv2/config-3.py''.">
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="main.py">
    <optimization-time pass="1" time="0.02" />
    <module_usages>
      <module_usage name="fastapi" finding="absolute" line="1" />
      <module_usage name="fastapi.FastAPI" finding="not-found" line="1" />
      <module_usage name="fastapi.Request" finding="not-found" line="1" />
      <module_usage name="uvicorn" finding="absolute" line="2" />
      <module_usage name="uvicorn.run" finding="not-found" line="2" />
      <module_usage name="sco.logger" finding="absolute" line="4" />
      <module_usage name="sco" finding="absolute" line="5" />
      <module_usage name="sco.config" finding="not-found" line="5" />
      <module_usage name="sco.camera_router" finding="absolute" line="6" />
      <module_usage name="sco.config_setup" finding="absolute" line="7" />
      <module_usage name="_codecs_cn" finding="absolute" line="1" />
      <module_usage name="_codecs_hk" finding="absolute" line="1" />
      <module_usage name="_codecs_iso2022" finding="absolute" line="1" />
      <module_usage name="_codecs_jp" finding="absolute" line="1" />
      <module_usage name="_codecs_kr" finding="absolute" line="1" />
      <module_usage name="_codecs_tw" finding="absolute" line="1" />
      <module_usage name="_collections_abc" finding="absolute" line="1" />
      <module_usage name="_multibytecodec" finding="absolute" line="1" />
      <module_usage name="abc" finding="absolute" line="1" />
      <module_usage name="ast" finding="absolute" line="1" />
      <module_usage name="binascii" finding="absolute" line="1" />
      <module_usage name="codecs" finding="absolute" line="1" />
      <module_usage name="collections" finding="absolute" line="1" />
      <module_usage name="collections.abc" finding="absolute" line="1" />
      <module_usage name="contextlib" finding="absolute" line="1" />
      <module_usage name="copyreg" finding="absolute" line="1" />
      <module_usage name="dis" finding="absolute" line="1" />
      <module_usage name="encodings" finding="absolute" line="1" />
      <module_usage name="encodings.aliases" finding="absolute" line="1" />
      <module_usage name="encodings.ascii" finding="absolute" line="1" />
      <module_usage name="encodings.big5" finding="absolute" line="1" />
      <module_usage name="encodings.big5hkscs" finding="absolute" line="1" />
      <module_usage name="encodings.charmap" finding="absolute" line="1" />
      <module_usage name="encodings.cp037" finding="absolute" line="1" />
      <module_usage name="encodings.cp1006" finding="absolute" line="1" />
      <module_usage name="encodings.cp1026" finding="absolute" line="1" />
      <module_usage name="encodings.cp1125" finding="absolute" line="1" />
      <module_usage name="encodings.cp1140" finding="absolute" line="1" />
      <module_usage name="encodings.cp1250" finding="absolute" line="1" />
      <module_usage name="encodings.cp1251" finding="absolute" line="1" />
      <module_usage name="encodings.cp1252" finding="absolute" line="1" />
      <module_usage name="encodings.cp1253" finding="absolute" line="1" />
      <module_usage name="encodings.cp1254" finding="absolute" line="1" />
      <module_usage name="encodings.cp1255" finding="absolute" line="1" />
      <module_usage name="encodings.cp1256" finding="absolute" line="1" />
      <module_usage name="encodings.cp1257" finding="absolute" line="1" />
      <module_usage name="encodings.cp1258" finding="absolute" line="1" />
      <module_usage name="encodings.cp273" finding="absolute" line="1" />
      <module_usage name="encodings.cp424" finding="absolute" line="1" />
      <module_usage name="encodings.cp437" finding="absolute" line="1" />
      <module_usage name="encodings.cp500" finding="absolute" line="1" />
      <module_usage name="encodings.cp720" finding="absolute" line="1" />
      <module_usage name="encodings.cp737" finding="absolute" line="1" />
      <module_usage name="encodings.cp775" finding="absolute" line="1" />
      <module_usage name="encodings.cp850" finding="absolute" line="1" />
      <module_usage name="encodings.cp852" finding="absolute" line="1" />
      <module_usage name="encodings.cp855" finding="absolute" line="1" />
      <module_usage name="encodings.cp856" finding="absolute" line="1" />
      <module_usage name="encodings.cp857" finding="absolute" line="1" />
      <module_usage name="encodings.cp858" finding="absolute" line="1" />
      <module_usage name="encodings.cp860" finding="absolute" line="1" />
      <module_usage name="encodings.cp861" finding="absolute" line="1" />
      <module_usage name="encodings.cp862" finding="absolute" line="1" />
      <module_usage name="encodings.cp863" finding="absolute" line="1" />
      <module_usage name="encodings.cp864" finding="absolute" line="1" />
      <module_usage name="encodings.cp865" finding="absolute" line="1" />
      <module_usage name="encodings.cp866" finding="absolute" line="1" />
      <module_usage name="encodings.cp869" finding="absolute" line="1" />
      <module_usage name="encodings.cp874" finding="absolute" line="1" />
      <module_usage name="encodings.cp875" finding="absolute" line="1" />
      <module_usage name="encodings.cp932" finding="absolute" line="1" />
      <module_usage name="encodings.cp949" finding="absolute" line="1" />
      <module_usage name="encodings.cp950" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jp" finding="absolute" line="1" />
      <module_usage name="encodings.euc_kr" finding="absolute" line="1" />
      <module_usage name="encodings.gb18030" finding="absolute" line="1" />
      <module_usage name="encodings.gb2312" finding="absolute" line="1" />
      <module_usage name="encodings.gbk" finding="absolute" line="1" />
      <module_usage name="encodings.hp_roman8" finding="absolute" line="1" />
      <module_usage name="encodings.hz" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2004" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_ext" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_kr" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_10" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_11" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_13" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_14" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_15" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_16" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_4" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_5" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_6" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_7" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_8" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_9" finding="absolute" line="1" />
      <module_usage name="encodings.johab" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_r" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_t" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_u" finding="absolute" line="1" />
      <module_usage name="encodings.kz1048" finding="absolute" line="1" />
      <module_usage name="encodings.latin_1" finding="absolute" line="1" />
      <module_usage name="encodings.mac_arabic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_croatian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_cyrillic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_farsi" finding="absolute" line="1" />
      <module_usage name="encodings.mac_greek" finding="absolute" line="1" />
      <module_usage name="encodings.mac_iceland" finding="absolute" line="1" />
      <module_usage name="encodings.mac_latin2" finding="absolute" line="1" />
      <module_usage name="encodings.mac_roman" finding="absolute" line="1" />
      <module_usage name="encodings.mac_romanian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_turkish" finding="absolute" line="1" />
      <module_usage name="encodings.palmos" finding="absolute" line="1" />
      <module_usage name="encodings.ptcp154" finding="absolute" line="1" />
      <module_usage name="encodings.punycode" finding="absolute" line="1" />
      <module_usage name="encodings.quopri_codec" finding="absolute" line="1" />
      <module_usage name="encodings.raw_unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.tis_620" finding="absolute" line="1" />
      <module_usage name="encodings.undefined" finding="absolute" line="1" />
      <module_usage name="encodings.unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_7" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8_sig" finding="absolute" line="1" />
      <module_usage name="encodings.uu_codec" finding="absolute" line="1" />
      <module_usage name="encodings.zlib_codec" finding="absolute" line="1" />
      <module_usage name="enum" finding="absolute" line="1" />
      <module_usage name="functools" finding="absolute" line="1" />
      <module_usage name="genericpath" finding="absolute" line="1" />
      <module_usage name="importlib" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap_external" finding="absolute" line="1" />
      <module_usage name="importlib.machinery" finding="absolute" line="1" />
      <module_usage name="inspect" finding="absolute" line="1" />
      <module_usage name="io" finding="absolute" line="1" />
      <module_usage name="keyword" finding="absolute" line="1" />
      <module_usage name="linecache" finding="absolute" line="1" />
      <module_usage name="locale" finding="absolute" line="1" />
      <module_usage name="opcode" finding="absolute" line="1" />
      <module_usage name="operator" finding="absolute" line="1" />
      <module_usage name="os" finding="absolute" line="1" />
      <module_usage name="posixpath" finding="absolute" line="1" />
      <module_usage name="quopri" finding="absolute" line="1" />
      <module_usage name="re" finding="absolute" line="1" />
      <module_usage name="re._casefix" finding="absolute" line="1" />
      <module_usage name="re._compiler" finding="absolute" line="1" />
      <module_usage name="re._constants" finding="absolute" line="1" />
      <module_usage name="re._parser" finding="absolute" line="1" />
      <module_usage name="reprlib" finding="absolute" line="1" />
      <module_usage name="stat" finding="absolute" line="1" />
      <module_usage name="token" finding="absolute" line="1" />
      <module_usage name="tokenize" finding="absolute" line="1" />
      <module_usage name="types" finding="absolute" line="1" />
      <module_usage name="warnings" finding="absolute" line="1" />
      <module_usage name="zipimport" finding="absolute" line="1" />
      <module_usage name="zlib" finding="absolute" line="1" />
      <module_usage name="__future__" finding="absolute" line="1" />
      <module_usage name="__hello__" finding="absolute" line="1" />
      <module_usage name="__phello__" finding="absolute" line="1" />
      <module_usage name="__phello__.spam" finding="absolute" line="1" />
      <module_usage name="_aix_support" finding="absolute" line="1" />
      <module_usage name="_bootsubprocess" finding="absolute" line="1" />
      <module_usage name="_compat_pickle" finding="absolute" line="1" />
      <module_usage name="_compression" finding="absolute" line="1" />
      <module_usage name="_datetime" finding="absolute" line="1" />
      <module_usage name="_markupbase" finding="absolute" line="1" />
      <module_usage name="_osx_support" finding="absolute" line="1" />
      <module_usage name="_pickle" finding="absolute" line="1" />
      <module_usage name="_py_abc" finding="absolute" line="1" />
      <module_usage name="_pyio" finding="absolute" line="1" />
      <module_usage name="_random" finding="absolute" line="1" />
      <module_usage name="_sha512" finding="absolute" line="1" />
      <module_usage name="_sitebuiltins" finding="absolute" line="1" />
      <module_usage name="_strptime" finding="absolute" line="1" />
      <module_usage name="_struct" finding="absolute" line="1" />
      <module_usage name="_sysconfigdata__linux_x86_64-linux-gnu" finding="absolute" line="1" />
      <module_usage name="_threading_local" finding="absolute" line="1" />
      <module_usage name="_typing" finding="absolute" line="1" />
      <module_usage name="_weakrefset" finding="absolute" line="1" />
      <module_usage name="base64" finding="absolute" line="1" />
      <module_usage name="bisect" finding="absolute" line="1" />
      <module_usage name="calendar" finding="absolute" line="1" />
      <module_usage name="cgi" finding="absolute" line="1" />
      <module_usage name="cgitb" finding="absolute" line="1" />
      <module_usage name="chunk" finding="absolute" line="1" />
      <module_usage name="cmd" finding="absolute" line="1" />
      <module_usage name="code" finding="absolute" line="1" />
      <module_usage name="codeop" finding="absolute" line="1" />
      <module_usage name="colorsys" finding="absolute" line="1" />
      <module_usage name="configparser" finding="absolute" line="1" />
      <module_usage name="contextvars" finding="absolute" line="1" />
      <module_usage name="copy" finding="absolute" line="1" />
      <module_usage name="crypt" finding="absolute" line="1" />
      <module_usage name="dataclasses" finding="absolute" line="1" />
      <module_usage name="datetime" finding="absolute" line="1" />
      <module_usage name="difflib" finding="absolute" line="1" />
      <module_usage name="encodings.base64_codec" finding="absolute" line="1" />
      <module_usage name="encodings.bz2_codec" finding="absolute" line="1" />
      <module_usage name="encodings.hex_codec" finding="absolute" line="1" />
      <module_usage name="encodings.idna" finding="absolute" line="1" />
      <module_usage name="encodings.rot_13" finding="absolute" line="1" />
      <module_usage name="fcntl" finding="absolute" line="1" />
      <module_usage name="filecmp" finding="absolute" line="1" />
      <module_usage name="fileinput" finding="absolute" line="1" />
      <module_usage name="fnmatch" finding="absolute" line="1" />
      <module_usage name="ftplib" finding="absolute" line="1" />
      <module_usage name="getopt" finding="absolute" line="1" />
      <module_usage name="gettext" finding="absolute" line="1" />
      <module_usage name="glob" finding="absolute" line="1" />
      <module_usage name="graphlib" finding="absolute" line="1" />
      <module_usage name="gzip" finding="absolute" line="1" />
      <module_usage name="heapq" finding="absolute" line="1" />
      <module_usage name="html" finding="absolute" line="1" />
      <module_usage name="html.entities" finding="absolute" line="1" />
      <module_usage name="html.parser" finding="absolute" line="1" />
      <module_usage name="imaplib" finding="absolute" line="1" />
      <module_usage name="imghdr" finding="absolute" line="1" />
      <module_usage name="imp" finding="absolute" line="1" />
      <module_usage name="importlib._abc" finding="absolute" line="1" />
      <module_usage name="importlib.abc" finding="absolute" line="1" />
      <module_usage name="importlib.metadata" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._adapters" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._collections" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._functools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._itertools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._meta" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._text" finding="absolute" line="1" />
      <module_usage name="importlib.readers" finding="absolute" line="1" />
      <module_usage name="importlib.resources" finding="absolute" line="1" />
      <module_usage name="importlib.resources._adapters" finding="absolute" line="1" />
      <module_usage name="importlib.resources._common" finding="absolute" line="1" />
      <module_usage name="importlib.resources._itertools" finding="absolute" line="1" />
      <module_usage name="importlib.resources._legacy" finding="absolute" line="1" />
      <module_usage name="importlib.resources.abc" finding="absolute" line="1" />
      <module_usage name="importlib.resources.readers" finding="absolute" line="1" />
      <module_usage name="importlib.resources.simple" finding="absolute" line="1" />
      <module_usage name="importlib.simple" finding="absolute" line="1" />
      <module_usage name="importlib.util" finding="absolute" line="1" />
      <module_usage name="ipaddress" finding="absolute" line="1" />
      <module_usage name="json" finding="absolute" line="1" />
      <module_usage name="json.decoder" finding="absolute" line="1" />
      <module_usage name="json.encoder" finding="absolute" line="1" />
      <module_usage name="json.scanner" finding="absolute" line="1" />
      <module_usage name="mailcap" finding="absolute" line="1" />
      <module_usage name="math" finding="absolute" line="1" />
      <module_usage name="mimetypes" finding="absolute" line="1" />
      <module_usage name="modulefinder" finding="absolute" line="1" />
      <module_usage name="netrc" finding="absolute" line="1" />
      <module_usage name="nturl2path" finding="absolute" line="1" />
      <module_usage name="numbers" finding="absolute" line="1" />
      <module_usage name="pathlib" finding="absolute" line="1" />
      <module_usage name="pickle" finding="absolute" line="1" />
      <module_usage name="pickletools" finding="absolute" line="1" />
      <module_usage name="pipes" finding="absolute" line="1" />
      <module_usage name="pkgutil" finding="absolute" line="1" />
      <module_usage name="platform" finding="absolute" line="1" />
      <module_usage name="poplib" finding="absolute" line="1" />
      <module_usage name="pprint" finding="absolute" line="1" />
      <module_usage name="pstats" finding="absolute" line="1" />
      <module_usage name="pyclbr" finding="absolute" line="1" />
      <module_usage name="rlcompleter" finding="absolute" line="1" />
      <module_usage name="sched" finding="absolute" line="1" />
      <module_usage name="shlex" finding="absolute" line="1" />
      <module_usage name="shutil" finding="absolute" line="1" />
      <module_usage name="signal" finding="absolute" line="1" />
      <module_usage name="sndhdr" finding="absolute" line="1" />
      <module_usage name="socketserver" finding="absolute" line="1" />
      <module_usage name="sre_compile" finding="absolute" line="1" />
      <module_usage name="sre_constants" finding="absolute" line="1" />
      <module_usage name="sre_parse" finding="absolute" line="1" />
      <module_usage name="string" finding="absolute" line="1" />
      <module_usage name="stringprep" finding="absolute" line="1" />
      <module_usage name="struct" finding="absolute" line="1" />
      <module_usage name="symtable" finding="absolute" line="1" />
      <module_usage name="sysconfig" finding="absolute" line="1" />
      <module_usage name="tarfile" finding="absolute" line="1" />
      <module_usage name="threading" finding="absolute" line="1" />
      <module_usage name="timeit" finding="absolute" line="1" />
      <module_usage name="tomllib" finding="absolute" line="1" />
      <module_usage name="tomllib._parser" finding="absolute" line="1" />
      <module_usage name="tomllib._re" finding="absolute" line="1" />
      <module_usage name="tomllib._types" finding="absolute" line="1" />
      <module_usage name="trace" finding="absolute" line="1" />
      <module_usage name="traceback" finding="absolute" line="1" />
      <module_usage name="tracemalloc" finding="absolute" line="1" />
      <module_usage name="typing" finding="absolute" line="1" />
      <module_usage name="unicodedata" finding="absolute" line="1" />
      <module_usage name="uu" finding="absolute" line="1" />
      <module_usage name="weakref" finding="absolute" line="1" />
      <module_usage name="webbrowser" finding="absolute" line="1" />
      <module_usage name="xdrlib" finding="absolute" line="1" />
      <module_usage name="zipfile" finding="absolute" line="1" />
    </module_usages>
  </module>
  <module name="sco.config_setup" kind="CompiledPythonModule" usage="import" reason="Instructed by user to follow to all modules." source_path="${cwd}/sco/config_setup.py">
    <module_usages>
      <module_usage name="json" finding="absolute" line="1" />
      <module_usage name="httpx" finding="absolute" line="2" />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="51326976" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="--onefile" />
    <option value="main.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="data-files" user_enabled="no" />
    <plugin name="delvewheel" user_enabled="no" />
    <plugin name="dll-files" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gevent" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="glfw" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="kivy" user_enabled="no" />
    <plugin name="matplotlib" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pbr-compat" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="pywebview" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Unknown" python_version="3.11.9" os_name="Linux" os_release="Debian-11" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.prefix}/lib/python3.11" />
      <path value="${sys.prefix}/lib/python3.11/lib-dynload" />
      <path value="${sys.prefix}/lib/python3.11/site-packages" />
    </search_path>
  </python>
  <output run_filename="${cwd}/main.bin" />
</nuitka-compilation-report>
```

**Comment by bjpietrzak** [comment]
Ok I have solved this error. Just renamed file /usr/local/lib/python3.11/site-packages/cv2/config-3.11.py to config-3.py.

I have also found a workaround for my use case. To reiterate I wanted to just combine all my project files into one binary executable, without having to put into it every external library that I was using. This is the workaround:

```
python -m python -m nuitka --follow-imports \
                           --nofollow-import-to=cv2 \
                           --nofollow-import-to=numpy \
                           --nofollow-import-to=fastapi \
                           --nofollow-import-to=httpx \
                           --nofollow-import-to=pandas \
                           --nofollow-import-to=pillow \
                           --nofollow-import-to=portalocker \
                           main.py
```

Is there a more elegant way to implement this in Nuitka?

**Comment by kayhayen** [comment]
In accelerate mode, mixing compiled modules with extension modules is not working well yet, use standalone then it will be fine, and don't follow third party modules that have this. Using Debian Python packages is also warned about. I was not aware that it will cause a crash with Debian package cv2, but it's not advised to do it like that anyway.

**Comment by bjpietrzak** [comment]
Great, thanks. I was actually building opencv from source. However the opencv installed with pip also didn't work.

**Comment by kayhayen** [comment]
For accelerated mode, I think it would not. The use of `<distributions />` should be telling indeed. I am going to make the detection of the `config3.py` more resiliant, also checking for a file with a minor Python version. Self compiled distributions are not very likely to work in all cases, nor really am I too intent on supporting them without a ready served test case or excellent report.

**Comment by bjpietrzak** [comment]
Thank you for the clarification, and for the project you are building :). It's a great tool. I've tried to do the same with just Cython... it's a mess, and pyinstaller creates bigger executables. Great job!

**Comment by zoldaten** [comment]
i have almost the same issue on Bullseye aarch64:
```
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'torch.utils.cpp_extension' (intending to avoid 'setuptools') in 'peft.tuners.boft.layer' (at
Nuitka-Plugins:WARNING: '/home/pi/.local/lib/python3.9/site-packages/peft/tuners/boft/layer.py:81') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: implicit-imports: Exception during compile time command execution: b'AttributeError("module \'cv2.cv2\' has no attribute
Nuitka-Plugins:WARNING: \'__collect_extra_submodules\'")'
FATAL: implicit-imports: Error, failed to evaluate variables for 'cv2'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

but if i build simple example:
`import cv2`
everything is ok.

command - `python3 -m nuitka --follow-imports --enable-plugin=no-qt --disable-ccache image_describe.py --jobs=3`
report - 
[nuitka-crash-report.zip](https://github.com/user-attachments/files/19813340/nuitka-crash-report.zip)

```
nuitka --version
2.6.9
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: aarch64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc 10).
```

how to fix that ? it only opencv issue i think.

*i tried opencv==4.5, 4.9, 4.10

**Comment by zoldaten** [comment]
additionally i found out that if use `pip3 install opencv-contrib-python`  not `pip3 install opencv-python` everything builds successfully.
but when use .bin file it gives error:
`
Traceback (most recent call last):
  File "/home/pi/Desktop/test/test9_cm4_with_ports.py", line 96, in <module>
    # utils.ONLINE = False
  File "/home/pi/.local/lib/python3.9/site-packages/ultralytics/__init__.py", line 11, in <module ultralytics>
    from ultralytics.data.explorer.explorer import Explorer
  File "/home/pi/.local/lib/python3.9/site-packages/ultralytics/data/__init__.py", line 3, in <module ultralytics.data>
    from .base import BaseDataset
  File "/home/pi/.local/lib/python3.9/site-packages/ultralytics/data/base.py", line 12, in <module ultralytics.data.base>
    import cv2
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 209, in <module cv2>
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in bootstrap
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 209, in <module cv2>
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 76, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
`
it seems something wrong with ultralytics.

**Comment by kayhayen** [comment]
Posting below closed or unrelated issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you. @zoldaten

**Comment by kayhayen** [comment]
The issue is a duplicate of #689 and others, no need to keep it open for longer.
