### ISSUE TITLE
Blender bpy package compiles but does not run

### ISSUE THREAD

**Issue by jack-loci** [Nuitka/Nuitka#2880]
I have a simple program which imports the blender python package, and perform a simple operation:
```
import bpy
if __name__ == "__main__":
    bpy.data.objects["Cube"].data.vertices[0].co.x += 1.0
    print("Success!")
```
Running `python -m nuitka --follow-imports test_script.py` successfully compiles the script.

However, running the program results in the following error:
```
./test_script.bin
Traceback (most recent call last):
  File "/home/jack/Loci/loci/packages/loci-asset/loci_asset/test_script.py", line 4, in <module>
    bpy.data.objects["Cube"].data.vertices[0].co.x += 1.0
AttributeError: module 'bpy' has no attribute 'data'
```

## What I have tried 
1. Compiling without --follow-imports works + the program runs: `python -m nuitka test_script.py && ./test_script.bin` but I want to be able to build this as a stand alone program, so I believe I need the --follow-imports argument

2. Including the data dir for bpy, but this results in the following compilation error.
```
> python -m nuitka --follow-imports --include-data-dir=~/.cache/pypoetry/virtualenvs/abc-py3.10/lib/python3.10/site-packages/bpy=bpy  test_script.py 

Nuitka-Options: Used command line options: --follow-imports
Nuitka-Options: --include-data-dir=~/.cache/pypoetry/virtualenvs/abc-py3.10/lib/python3.10/site-packages/bpy=bpy test_script.py
Nuitka: Starting Python compilation with Nuitka '2.3rc5' on Python '3.10' commercial grade 'not installed'.
FATAL: Error, cannot change paths for data files in accelerated mode 'bpy/4.0/datafiles/assets/LICENSE'.
```

## Extra Info
```
python -m nuitka --version

2.3rc5
Commercial: None
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Flavor: Debian Python
Executable: /home/jack/.cache/pypoetry/virtualenvs/loci-asset-Zw8VtnVM-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.4
Version C compiler: /usr/bin/gcc (gcc 11).
```

- How did you install Nuitka and Python (into poetry venv)
`python -m pip install -U nuitka`

- The specific PyPI names and versions
`bpy==4.0.0`

**Comment by Maxwell175** [comment]
As [explained in the manual](https://nuitka.net/user-documentation/tutorial-setup-and-build.html#distribute) for distribution you should be using `--standalone` or `--onefile`.

**Comment by jack-loci** [comment]
The same error occurs with `--standalone` and `--onefile`, but I reduced the toy example down to the same error with `--follow-imports`:

```
> python -m nuitka --standalone test_script.py

Nuitka-Options: Used command line options: --standalone test_script.py
Nuitka: Starting Python compilation with Nuitka '2.2.3' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                            
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 11).
Nuitka-Scons: Backend linking program with 8 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka: Keeping build directory 'test_script.build'.                         
Nuitka: Successfully created 'test_script.dist/test_script.bin'.

> ./test_script.dist/test_script.bin 

Traceback (most recent call last):
  File "test_script.dist/test_script.py", line 4, in <module>
AttributeError: module 'bpy' has no attribute 'data'
```

**Comment by jack-loci** [comment]
Thank you for the help!

Sadly this doesn't work with the same error message:

```
> python -m nuitka --standalone --include-package-data=bpy test_file.py && ./test_file.dist/test_file.bin 

Traceback (most recent call last):
  File "/test_file.dist/test_file.py", line 4, in <module>
AttributeError: module 'bpy' has no attribute 'data'
```

The cube from blender is not a data file - it is generated in blender upon startup in the default scene, and so I think there is something else going on.

The issue seems to be that none of the modules (e.g. `bpy.data, bpy.types, bpy.ops, bpy.app, bpy.context` etc), inside bpy are available.

For example, even this test script fails:
```
import bpy
from bpy import types

if __name__ == "__main__":
    print("Doing nothing")
```

with error:

```
> ./test_file.dist/test_file.bin 

Traceback (most recent call last):
  File "/test_file.dist/test_file.py", line 2, in <module>
ImportError: cannot import name 'types' from 'bpy' (unknown location)
```

**Comment by kayhayen** [comment]
Hm, this is strange one:

```
 N  hayen@Neyah: ~/repos/Py2C$ python bin/nuitka --edit=bpy
FATAL: Error, bpy is a namespace package with no code
 N  hayen@Neyah: ~/repos/Py2C$ python bin/nuitka --edit=bpy.types
FATAL: Error, did not find 'bpy.types' module
```

Ah, it's one of those:

`/home/hayen/.local/lib/python3.10/site-packages/bpy/__init__.so`

So, that's more or less of a duplicate. I forgot which other package has this too, but Nuitka is very confused about that, wrongfully so, of course. I can give it a quick stab, enhancing at least the detection side of things, I can imagine it might require a few corrections here and there though.

**Comment by kayhayen** [comment]
From what I recall, Nuitka will work with this, but fail to find imports below, if this structure is not replicated, which it might not do. From the example though, it looks like it didn't include it at all yet. I am cleaning up code now that checks for `__init__.py` only.

**Comment by kayhayen** [comment]
I have recently added support for extension module inits, lets see how it fares.

**Comment by kayhayen** [comment]
So, this actually needed indeed more work for extension module packages with other extension module packages to work, but it now does. I have observed that the `__file__` value is garbage, and attempts to correct it will trigger assertions, caused by the module loading itself and not liking it. Setting the module in `sys.modules` only goes so far, since other modules have issues then, I suspect this is a lack of 2 phase loading.

So for now this becomes a duplicate of #2833 which will eventually be solved.

**Comment by kayhayen** [comment]
These days it is necessary to do:  `python3.10 -m pip install --extra-index-url https:/
/download.blender.org/pypi/ bpy` as they don't host on PyPI anymore.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is now on develop and wwill be part of the 4.1 release.

**Comment by kayhayen** [comment]
Part of the 4.1 release I just made.
