### ISSUE TITLE
pyperf support

### ISSUE THREAD

**Issue by KRRT7** [Nuitka/Nuitka#2883]
we need to add https://github.com/psf/pyperf pyperf support, it creates subprocess using the sys.executable in order to perform benchmarks, for obvious reasons, with nuitka, this fails.
when compiling this file
https://github.com/KRRT7/Nuitka-pyperf-suite/blob/main/benchmarks/bm_async_generators/run_benchmark.py
```
Nuitka: Successfully created 'run_benchmark.dist\run_benchmark.exe'.
Running command run_benchmark.dist/run_benchmark.exe
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\run_benchmark.py", line 47, in <module>
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_runner.py", line 605, in bench_async_func
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_runner.py", line 460, in _main
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_runner.py", line 673, in _manager
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_manager.py", line 232, in create_bench
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_manager.py", line 131, in create_worker_bench
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_manager.py", line 121, in create_suite
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\pyperf\_manager.py", line 98, in spawn_worker
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\subprocess.py", line 1026, in __init__
  File "C:\Users\NUITKA~1\Desktop\NUITKA~4\BENCHM~1\BM_ASY~1\RUN_BE~1.DIS\subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed to run command run_benchmark.dist/run_benchmark.exe
```

the command that causes the issue is 
`C:\Users\NuitkaDevOps\Desktop\Nuitka-pyperf-suite\benchmarks\bm_async_generators\run_benchmark.dist\python.exe run_benchmark.dist/run_benchmark.exe --worker --pipe 304 --worker-task=0 --values 3 --min-time 0.1 --calibrate-loops --warmups 1`

**Comment by kayhayen** [comment]
I am not sure, why pyperf is being compiled there?

**Comment by kayhayen** [comment]
Otherwise, for timeit and the like, we sort of need the `nuitka.jit` that would compile code to a module and load it, but we don't have that, although it really is only a bunch of tooling.
