### ISSUE TITLE
Hyperspy dynamic import fails when packaging an application that contains hyperspy

### ISSUE THREAD

**Issue by werfei** [Nuitka/Nuitka#2887]

**Comment by KRRT7** [comment]
can you provide a miminal reproducible example?

**Comment by werfei** [comment]
@KRRT7 https://github.com/werfei/hyperspy-nuitka

**Comment by KRRT7** [comment]
@kayhayen 
once the program is compiled, it seems that some functions are being passed an additional arg
```
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 524, in _dispatch_change_event
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 486, in dispatch
TypeError: BaseDataAxis._update_bounds() takes 1 positional argument but 2 were given
Exception occurred in traits notification handler for object: width axis, trait: size, old value: 0, new value: 1024
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 524, in _dispatch_change_event
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 486, in dispatch
TypeError: BaseDataAxis.update_index_bounds() takes 1 positional argument but 2 were given
Exception occurred in traits notification handler for object: width axis, trait: axis, old value: [], new value: [0.00000000e+00 2.50313474e-01 5.00626947e-01 ... 2.55570057e+02
 2.55820370e+02 2.56070684e+02]
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 524, in _dispatch_change_event
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 486, in dispatch
TypeError: BaseDataAxis._update_bounds() takes 1 positional argument but 2 were given
ERROR | Hyperspy | If this file format is supported, please report this error to the HyperSpy developers. (hyperspy.io:599)
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\main.py", line 13, in <module>
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\io.py", line 536, in load
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\io.py", line 596, in load_single_file
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\io.py", line 631, in load_with_reader
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\io.py", line 834, in dict2signal
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\_signals\signal2d.py", line 352, in __init__
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\signal.py", line 2483, in __init__
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\signal.py", line 2816, in _load_dictionary
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\axes.py", line 1545, in __init__
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\hyperspy\axes.py", line 1563, in _update_trait_handlers
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\has_traits.py", line 2700, in on_trait_change
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\traits_listener.py", line 428, in register
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\traits_listener.py", line 701, in _register_list
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\has_traits.py", line 2320, in _on_trait_change
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 412, in __init__
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\hyperspy\MAIN~1.DIS\traits\trait_notifiers.py", line 449, in init
traits.trait_errors.TraitNotificationError: Invalid number of arguments for the dynamic trait change notification handler: handle_error. A maximum of 4 arguments is allowed, but 5 were specified.


```

**Comment by KRRT7** [comment]
```
- module-name: "hyperspy"
  data-files:
    patterns:
      - "*.yaml"
  implicit-imports:
    - depends:
        - "hyperspy.io"
        - "hyperspy._components.*"
        - "rsciio"

- module-name: "traits"
  anti-bloat:
    - description: "do not follow tests"
      no-auto-follow:
        "traits.testing": "ignore"
        "traits.utils.tests": "ignore"
        "traits.tests": "ignore"
        "traits.observation.tests": "ignore"
        "traits.examples": "ignore"
        "traits.etsconfig.tests": "ignore"
  dlls:
    - from_filenames:
        prefixes:
          - "ctraits"

- module-name: "rsciio"
  data-files:
    dirs:
      - "."
  implicit-imports:
    - depends:
        - "rsciio.*"
```
you will need this config to reproduce.

**Comment by werfei** [comment]
Thank you very much, after adding the configuration, the packaged program works fine，But, When I add the --standalone parameter, the packaged program doesn't run with a new error
![图片](https://github.com/Nuitka/Nuitka/assets/18606985/72e4389f-dd81-440b-b787-423a9dcb5db3)

**Comment by KRRT7** [comment]
@werfei apologies, hyperspy isn't ready for general use yet, we will update you when it is.

**Comment by Spooyler** [comment]
@werfei did you manage to make it work? I had a similar issue, using pyinstaller.

**Comment by werfei** [comment]
> @werfei did you manage to make it work? I had a similar issue, using pyinstaller.

pyinstaller  You can write a hook file
`
 from PyInstaller.utils.hooks import collect_all

  datas, binaries, hiddenimports = collect_all('hyperspy')
`

**Comment by Spooyler** [comment]
@werfei I finally I was able to make it work. I added hyperspy as data. the drawback is I had to manually add the dependencies. But the project is finished so it is fine.

**Comment by kayhayen** [comment]
What a garbage collection of a report, but the repo looks good as a reproducer. If only it was clear what OS to use.

**Comment by kayhayen** [comment]
This needs a reproducer, or I feel we should close it as invalid.
