### ISSUE TITLE
Error including exe files in nuitka build

### ISSUE THREAD

**Issue by OlegXio** [Nuitka/Nuitka#2912]
OUTPUT:
```
D:\PycharmProjects\_XioProjects\BOSINN_num3>nuitka --follow-imports --enable-plugin=tk-inter --onefile --jobs=3 --company-name="Bo Sinn Inc." --product-version=0.8.11.1985 --include-data-files="D:/PycharmProjects/_XioProjects/BOSINN_num3/*.exe"=*.exe/ --product-version=0.8.11.1985 --include-data-file="D:/PycharmProjects/_XioProjects/BOSINN_num3/audio_bosinn.mp3"=audio_bosinn.mp3 --include-data-file="D:/PycharmProjects/_XioProjects/BOSINN_num3/video_bosinn.mp4"=video_bosinn.mp4 main.py --output-filename=Bo.exe

Nuitka-Options: Used command line options: --follow-imports --enable-plugin=tk-inter --onefile --jobs=3
Nuitka-Options: --company-name="Bo Sinn Inc." --product-version=0.8.11.1985
Nuitka-Options: --include-data-files=D:/PycharmProjects/_XioProjects/BOSINN_num3/*.exe=*.exe/
Nuitka-Options: --product-version=0.8.11.1985
Nuitka-Options: --include-data-file=D:/PycharmProjects/_XioProjects/BOSINN_num3/audio_bosinn.mp3=audio_bosinn.mp3
Nuitka-Options: --include-data-file=D:/PycharmProjects/_XioProjects/BOSINN_num3/video_bosinn.mp4=video_bosinn.mp4
Nuitka-Options: main.py --output-filename=Bo.exe
Nuitka-Options: Following all imports is the default for onefile mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.2rc3' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Note, when using 'pygame', consider using '--disable-console' option. Otherwise a terminal
Nuitka-Plugins:options-nanny: window will open. However for debugging, terminal output is the easiest way to see
Nuitka-Plugins:options-nanny: informative traceback and error information, so delay this until your program is working
Nuitka-Plugins:options-nanny: and remove once you find it non-working, and use '--enable-console' to make it explicit
Nuitka-Plugins:options-nanny: and not see this message.
Nuitka-Plugins:options-nanny: Note, when using 'tkinter', consider using '--disable-console' option. Otherwise a
Nuitka-Plugins:options-nanny: terminal window will open. However for debugging, terminal output is the easiest way to
Nuitka-Plugins:options-nanny: see informative traceback and error information, so delay this until your program is
Nuitka-Plugins:options-nanny: working and remove once you find it non-working, and use '--enable-console' to make it
Nuitka-Plugins:options-nanny: explicit and not see this message.
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL
Nuitka-Plugins:anti-bloat: will not be able to create Qt image objects.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 424 files (no progress information available for this stage).
Nuitka-Scons: Compiled 422 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 422
Nuitka-Plugins:dll-files: Found 1 file DLLs from numpy installation.
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\nuitka\__main__.py", line 161, in <module>
    main()
  File "D:\Program Files\Python310\lib\site-packages\nuitka\__main__.py", line 147, in main
    MainControl.main()
  File "D:\Program Files\Python310\lib\site-packages\nuitka\MainControl.py", line 1124, in main
    _main()
  File "D:\Program Files\Python310\lib\site-packages\nuitka\MainControl.py", line 1028, in _main
    copyDataFiles(standalone_entry_points=getStandaloneEntryPoints())
  File "D:\Program Files\Python310\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 597, in copyDataFiles
    _handleDataFile(
  File "D:\Program Files\Python310\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 559, in _handleDataFile
    makePath(os.path.dirname(dest_path))
  File "D:\Program Files\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 189, in makePath
    os.makedirs(path)
  File "D:\Program Files\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'main.dist\\*.exe'
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
```
Technical info:
```
Nuitka v.  2.2rc3
Python v.  3.10.0
OC: Windows v.  10.0.19041 Н/Д build 19041
Locale: ru_RU
```
The code with `print("hello world!")` works fine.
Crash report: 
[nuitka-crash-report.xml](https://github.com/user-attachments/files/15753086/nuitka-crash-report.xml.txt) 

!!
**This error appeared after adding the argument `--include-data-files=“D:/PycharmProjects/_XioProjects/BOSINN_num3/*.exe”=*.exe/`**

**Comment by kayhayen** [comment]
Please use release versions. Your quoting seems off, and you are using the option in the wrong way. I don't think folder can contain `*` so it fails to create the target folder for the executables that would be `*.exe` which is most definitely not what you want.

I will try and find a way to error out when destination paths for data files contain illegal characters.

**Comment by kayhayen** [comment]
So, I added a check, which makes an explicit error


> FATAL: Error, cannot add data file with '*.exe' path, as 'contains illegal character '*''

But since you added the trailing slash based on getting an error message, I am not convinced it would have helped you. When matching multiple files, it would do this:

> FATAL: Error, cannot add data file with '*.exe/CODE_OF_CONDUCT.rst' path, as 'contains illegal character '*''

So, that's probably more helpful. I added illegal characters for Windows, of which there are quite a few, for Linux only `\0` really which can happen if fed by scripts, and `:` on macOS since it's problematic there at least.

I am closing this for lack of general relevance, the change will appear on factory branch shortly and be part of 2.4 release.
