### ISSUE TITLE
opencv + python3.12 fails on "ModuleNotFoundError: No module named 'imp'"

### ISSUE THREAD

**Issue by ShapingView** [Nuitka/Nuitka#2922]
Hello!

Thanks for working actively on python3.12! I hope to switch from 3.10 to 3.12 with a bigger project, but having trouble switching. I built a minimal example for the issue I found.

A similar bug ticket exists, but it was closed since insufficient information was provided: https://github.com/Nuitka/Nuitka/issues/2908

I'm happy to provide further information if necessary

<details><summary><h3>My Environment</h3></summary>

Running python 3.12.3 on windows 11 23H2
- installed python from <https://www.python.org/ftp/python/3.12.3/python-3.12.3-amd64.exe> and created a virtual environment from it using `python -m venv venv-312-test`
- installed nuitka with `python.exe -m pip install https://github.com/Nuitka/Nuitka/archive/develop.zip`

Nuitka version (used with mingw64)
```
python -m nuitka --version
2.4rc4
Commercial: None
Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\shapingview\Desktop\repos\venv-312-test\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding it.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

python environment:
```
python -m pip freeze
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip#sha256=f41c76398792ce0f2f61970debafef654275356e240b34e0fa0491b1fcc4f2e1
numpy==1.26.4
opencv-python-headless==4.9.0.80
ordered-set==4.1.0
zstandard==0.22.0
```

</details>

### Script

Compiling this script (`hw.py`) does not work

```python
import cv2
import numpy as np

def f(inp):
    print("Hello " + inp)

def main():
    f("nuitka!")
    rng = np.random.default_rng(0)
    image = rng.uniform(size=(8, 8))
    print(cv2.imencode(".png", image))



if __name__ == "__main__":
    main()
```

### Behavior

Running this script with python works fine, but after compilation with nutika it doesnt

#### Expected output
```
> python hw.py
Hello nuitka!
(True, array([137,  80,  78,  71,  13,  10,  26,  10,   0,   0,   0,  13,  73,
        72,  68,  82,   0,   0,   0,   8,   0,   0,   0,   8,   8,   0,
         0,   0,   0, 225, 100, 225,  87,   0,   0,   0,  36,  73,  68,
        65,  84,   8,  29,  13, 193,   1,   1,   0,   0,   8, 195, 160,
       209,  63, 244,  21,  88, 169, 168, 153, 209,  42,  49, 189,  73,
        75,  99, 150, 145, 102,  37, 235,  57,  22,  73,  15,  13,  22,
        64, 198, 237,   0,   0,   0,   0,  73,  69,  78,  68, 174,  66,
        96, 130], dtype=uint8))
```

#### Output after compiling

```
> .\hw.dist\hw.exe     
Traceback (most recent call last):
  File "C:\Users\STEFAN~1\Desktop\repos\test\HWBF46~1.DIS\hw.py", line 1, in <module>
  File "C:\Users\STEFAN~1\Desktop\repos\test\HWBF46~1.DIS\cv2\__init__.py", line 209, in <module cv2>
  File "C:\Users\STEFAN~1\Desktop\repos\test\HWBF46~1.DIS\cv2\__init__.py", line 181, in bootstrap
ModuleNotFoundError: No module named 'imp'
```

#### Build command and log

Remark: 
- I am also using `--mingw64` because I currently can't install newer MSVC versions. Not sure if that is relevant for this issue
- Without `--standalone` it works too

```
>  python.exe -m nuitka --mingw64 --standalone --output-dir=. --main=.\hw.py
Nuitka-Options: Used command line options: --mingw64 --standalone --output-dir=. --main=.\hw.py
Nuitka: Starting Python compilation with Nuitka '2.4rc4' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                 
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 102 files (no progress information available for this stage).
Nuitka-Scons: Compiled 102 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 102
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka: Keeping build directory 'hw.build'.
Nuitka: Successfully created 'hw.dist\hw.exe'
```

Thanks for your help! I'm looking forward to your feedback

**Comment by kayhayen** [comment]
Are you sure your program is running with Python3.12, since there is no imp module.

**Comment by kayhayen** [comment]
Ah, it's probably these things:

```
      replacements:
        "load_first_config(['config.py'], True)": "textwrap.indent(pkgutil.get_data('cv2', 'config.py').decode('utf8'), '    ') + textwrap.indent(pkgutil.get_data('cv2', 'config-3.py').decode('utf8'), '    ')"
        # Before OpenCV 4.6
        'native_module = importlib.import_module("cv2.cv2")': '"import imp; native_module = imp.load_dynamic(\"cv2\", os.path.join(os.path.dirname(__file__), \"cv2%s\"))" % getSharedLibrarySuffix(False)'
        # After OpenCV 4.6
        'native_module = importlib.import_module("cv2")': '"import imp; native_module = imp.load_dynamic(\"cv2\", os.path.join(os.path.dirname(__file__), \"cv2%s\"))" % getSharedLibrarySuffix(False)'
```

These could be changed to use `_imp` I suppose.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Let me know if it works, I only changed the code, expecting everything else to be fine now.

**Comment by kayhayen** [comment]
Too bad, I think I saw it on older versions, wasn't expecting it to not be there.

**Comment by kayhayen** [comment]
So, in the tests of CPython 3.12, they copied the code of `load_dynamic` from the former `imp` module, which would be one way of doing it, and probably what we have to do. I will give it a shot, if anything is needed at all there, maybe for 4.6+ it is now needed at all, and we continued doing it.

**Comment by kayhayen** [comment]
Unfortunately the workaround is still needed though.

**Comment by kayhayen** [comment]
I devised a manual load with ExtensionFileLoader just as done in the 3.12 test suite, for which there seems to be no function in proper Python anymore. Manual module loading is going to spread like wildfire, and people barely get those things correct, but what do I know, slightly annoyed here.

**Comment by kayhayen** [comment]
So right now factory is actually working.

**Comment by ShapingView** [comment]
I tested it, the test script works for me, too! Thanks

**Comment by kayhayen** [comment]
This has been forgotten to be closed simply it seems.
