### ISSUE TITLE
moviepy breaks nuitka

### ISSUE THREAD

**Issue by tymoshh** [Nuitka/Nuitka#2928]
the compilations goes good but when i try to run the executable i get following error :

nuitka installed with pip

used command : py -m nuitka --follow-imports --onefile main.py

error:

D:\data\programming\miniProjekty\automatyczneTiktoki>main.exe
Traceback (most recent call last):
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\main.py", line 21, in <module>
    from moviepy.editor import *

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\editor.py", line 36, in <module moviepy.editor>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\video\io\VideoFileClip.py", line 3, in <module moviepy.video.io.VideoFileClip>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\audio\io\AudioFileClip.py", line 3, in <module moviepy.audio.io.AudioFileClip>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\audio\AudioClip.py", line 7, in <module moviepy.audio.AudioClip>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\audio\io\ffmpeg_audiowriter.py", line 7, in <module moviepy.audio.io.ffmpeg_audiowriter>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\moviepy\config.py", line 36, in <module moviepy.config>
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\imageio\plugins\ffmpeg.py", line 173, in get_exe
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\imageio_ffmpeg\_utils.py", line 28, in get_ffmpeg_exe
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\imageio_ffmpeg\_utils.py", line 44, in _get_ffmpeg_exe
  File "C:\Users\tymek\AppData\Local\Temp\ONEFIL~1\imageio_ffmpeg\_utils.py", line 74, in _get_bin_dir
AttributeError: 'nuitka_resource_reader_files' object has no attribute 'parent'

**Comment by KRRT7** [comment]
the error is quite confusing, but doesn't actually have to do with nuitka, it's coming from imageio_ffmpeg.

**Comment by kayhayen** [comment]
So, I assume we got the fix on factory, can you try it, KRRT seems to have made it.

**Comment by kayhayen** [comment]
Closing for lack of feedback, assuming it has been resolvved.
