### ISSUE TITLE
PEP 695 support

### ISSUE THREAD

**Issue by trebinor** [Nuitka/Nuitka#2930]
Python 3.12 added support for [PEP 695: Type Parameter Syntax](https://docs.python.org/3/whatsnew/3.12.html#pep-695-type-parameter-syntax).  How much of this is intended to be supported?

Here is an example of the upper bound specification working in CPython, but not when built with Nuitka.

```
# main.py
def foo[T: str](b: T) -> None:
    print(b)

if __name__ == "__main__":
    foo("bar")
```
```
# pyproject.toml
[project]
name = "pep695"
version = "0.1.0"
requires-python = ">= 3.12"
dependencies = [ "nuitka" ]
```
```
# Running CPython version in .venv (works)
$ python3 main.py
bar
```
```
# Running Nuitka version (error)
$ python3 -m nuitka main.py && ./main.bin
Nuitka-Options: Used command line options: main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.3.4' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 14.1.1).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.bin'.
Traceback (most recent call last):
  File "/home/trebinor/ws/raw/pep695/main.py", line 1, in <module>
    def foo[T: str](b: T) -> None:

NameError: name 'T' is not defined
```
Here is environment information required by the issue submission template.
```
$ python -m nuitka --version
2.3.4
Commercial: None
Python: 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]
Flavor: Arch Python
Executable: /home/trebinor/ws/raw/pep695/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/bin/gcc (gcc 14.1.1).
```

**Comment by kayhayen** [comment]
All of 3.12 is intended to be supported. I haven't managed to run the CPython test suite yet to discover these things, so some Python 3.12-only constructs have not yet been encountered.

**Comment by caphrim007** [comment]
i've come across a similar failure that I thought would be useful to post here.

I created a `main.py` with the following in it

```
# -*- mode: python; -*-
"""Caching functions."""

from collections.abc import Callable

def nncache[*Ts, U](f: Callable[[*Ts], U]) -> Callable[[*Ts], U]:
    """Return a function that caches non-null return values.

    >>> @nncache
    ... def f(x: int) -> int | None:
    ...     y = x if x % 2 == 0 else None
    ...     print("[cache miss] ", end="")
    ...     return y
    >>> for x in [0, 1, 2, 0, 1, 2]:
    ...     print(f"{x} -> {f(x)}")
    [cache miss] 0 -> 0
    [cache miss] 1 -> None
    [cache miss] 2 -> 2
    0 -> 0
    [cache miss] 1 -> None
    2 -> 2

    """
    cachemap: dict[tuple[*Ts], U] = {}

    def cached_f(*ts: *Ts) -> U:
        if ts in cachemap:
            return cachemap[ts]
        u = f(*ts)
        if u is not None:
            cachemap[ts] = u
        return u

    return cached_f
```

and saw that I could produce the following crash report related to the generic type annotations.
    
```
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.5.6" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="AssertionError" exception_value="Starred(value=Name(id='Ts', ctx=Load()), ctx=Load())">
Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/nuitka/MainControl.py", line 1160, in main
    _main()
  File ".venv/lib/python3.12/site-packages/nuitka/MainControl.py", line 999, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/MainControl.py", line 146, in _createMainModule
    main_module = buildMainModuleTree(
                  ^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/Building.py", line 1173, in buildMainModuleTree
    module = buildModule(
             ^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/Building.py", line 1428, in buildModule
    createModuleTree(
  File ".venv/lib/python3.12/site-packages/nuitka/tree/Building.py", line 1132, in createModuleTree
    module_body = buildParseTree(
                  ^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/Building.py", line 803, in buildParseTree
    result = buildStatementsNode(
             ^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 469, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 358, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 309, in buildNode
    result = build_nodes_args3[kind](
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 317, in buildFunctionNode
    function_statements_body = buildFrameNode(
                               ^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 487, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 358, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 309, in buildNode
    result = build_nodes_args3[kind](
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 343, in buildFunctionNode
    annotations = buildParameterAnnotations(provider, node, source_ref)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 635, in buildParameterAnnotations
    extractArgAnnotation(node.args.vararg)
  File ".venv/lib/python3.12/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 603, in extractArgAnnotation
    value=buildAnnotationNode(provider, arg.annotation, source_ref),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 427, in buildAnnotationNode
    return buildNode(provider, node, source_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/nuitka/tree/TreeHelpers.py", line 319, in buildNode
    assert False, ast.dump(node)
           ^^^^^
AssertionError: Starred(value=Name(id='Ts', ctx=Load()), ctx=Load())
</exception>
  <performance>
    <memory_usage name="after_launch" value="55951360" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="--standalone" />
    <option value="--output-dir=dist" />
    <option value="--output-filename=my-app" />
    <option value="main.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="data-files" user_enabled="no" />
    <plugin name="delvewheel" user_enabled="no" />
    <plugin name="dll-files" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gevent" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="glfw" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="kivy" user_enabled="no" />
    <plugin name="matplotlib" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pbr-compat" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="playwright" user_enabled="no" />
    <plugin name="pywebview" user_enabled="no" />
    <plugin name="spacy" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Rye Python" python_version="3.12.5" os_name="Darwin" os_release="14.6.1" arch_name="arm64" filesystem_encoding="utf-8">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.real_prefix}/lib/python3.12" />
      <path value="${sys.real_prefix}/lib/python3.12/lib-dynload" />
      <path value="${sys.prefix}/lib/python3.12/site-packages" />
    </search_path>
  </python>
  <output run_filename="${cwd}/dist/main.dist/my-app" />
</nuitka-compilation-report>
```

Hope this helps provide another test case when adding support. thanks!

**Comment by kayhayen** [comment]
Work on this has begun, but is not finished, this new star syntax, is also something different maybe.

**Comment by ZeroIntensity** [comment]
Will be added by #3561.

**Comment by kayhayen** [comment]
These are actually generic functions. Recently we were discussing if people will be using that or not, but it seems they actually are. The PR you mentioned did only do classes, we have others in the making for other sides of things. This is why I don't like PEP numbers for reference. Often they contain multiple features that are to be implemented individually or not. Generic functions and classes and types share only so much.

**Comment by ChenPi11** [comment]
<img width="985" height="834" alt="Image" src="https://github.com/user-attachments/assets/5d8bb251-e523-40ef-b448-0ac8f384557e" />
Same problem

**Comment by ZeroIntensity** [comment]
Could you post the code in the traceback? This might be something we've already fixed.

**Comment by ChenPi11** [comment]
```text
Traceback (most recent call last):
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/__main__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/cli/main/main.py", line 31, in <module rubisco.cli.main.main>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/cli/main/arg_parser.py", line 25, in <module rubisco.cli.main.arg_parser>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/cli/argparse_generator.py", line 26, in <module rubisco.cli.argparse_generator>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/kernel/command_event/__init__.py", line 24, in <module rubisco.kernel.command_event>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/kernel/command_event/cmd_event.py", line 29, in <module rubisco.kernel.command_event.cmd_event>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/kernel/command_event/args.py", line 27, in <module rubisco.kernel.command_event.args>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/lib/typecheck.py", line 30, in <module rubisco.lib.typecheck>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/lib/variable/fast_format_str.py", line 36, in <module rubisco.lib.variable.fast_format_str>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/lib/variable/var_container.py", line 31, in <module rubisco.lib.variable.var_container>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/lib/variable/variable.py", line 24, in <module rubisco.lib.variable.variable>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/workspaces/cppp/rubisco/dist/rubisco.dist/rubisco/lib/stack.py", line 29, in <module rubisco.lib.stack>
NameError: name 'T' is not defined
```

**Comment by ZeroIntensity** [comment]
Please send the code, not the traceback.

**Comment by ChenPi11** [comment]
This can cause the error in pip-installed Nuitka

```
from queue import Empty, LifoQueue
from typing import Any


class Stack[T](LifoQueue[T]):
    """A LifoQueue that can get the top value."""

    def top(
        self,
        *,
        block: bool = True,
        timeout: int | None = None,
    ) -> Any:  # noqa: ANN401
        pass

Stack[int]()
```

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/rubisco/c.py", line 5, in <module>
    class Stack[T](LifoQueue[T]):

NameError: name 'T' is not defined
```

**Comment by caphrim007** [comment]
as the error suggests, you need to import and define T before using it.

```
from typing import TypeVar
T = TypeVar("T")
```

unless you've defined it somewhere else that you haven't posted here

**Comment by ZeroIntensity** [comment]
Since Python 3.12 ([PEP 695](https://peps.python.org/pep-0695/)), type variables can be implicitly defined using `class Whatever[T]` and similar. That's supposed to be implemented in Nuitka now, but I'm not sure if it's been released yet (cc @kayhayen).

**Comment by caphrim007** [comment]
ahh. i wasn't aware. thanks for bringing me up-to-date!

**Comment by ChenPi11** [comment]
> ahh. i wasn't aware. thanks for bringing me up-to-date!

It's a valid syntax after Python 3.12. This code can run successfully in CPython but failed in Nuitka.

**Comment by kayhayen** [comment]
This one does generic functions. Generic classes are released with 3.12 but your PR isn't yet merged.
