### ISSUE TITLE
Standalone fails with numpy 2 (1.26.4 works)

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2934]
> python -m nuitka --version

```
2.3.6
Commercial: None
Python: 3.12.4 (main, Jun 13 2024, 11:12:24) [GCC 13.2.0]
Flavor: pyenv
Executable: /home/bers/.pyenv/versions/project3.12/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 24.04
Version C compiler: /usr/bin/gcc (gcc 13).
```

> How did you install Nuitka and Python

`pyenv` and `uv pip`

> python -m pip list -v

```
numpy                     2.0.0
```

> MWE
```python
import numpy as np  # noqa
```

> `python -m nuitka --standalone bug.py && bug.dist/bug.bin`

```
Traceback (most recent call last):
  File "/mnt/c/ws/project/bug.dist/numpy/__init__.py", line 114, in <module numpy>
  File "/mnt/c/ws/project/bug.dist/numpy/__config__.py", line 4, in <module numpy.__config__>
  File "/mnt/c/ws/project/bug.dist/numpy/_core/__init__.py", line 96, in <module numpy._core>
  File "/mnt/c/ws/project/bug.dist/numpy/_core/_add_newdocs.py", line 4874, in <module numpy._core._add_newdocs>
  File "/mnt/c/ws/project/bug.dist/numpy/_core/function_base.py", line 549, in add_newdoc
ModuleNotFoundError: No module named 'numpy._core._multiarray_tests'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/ws/project/bug.dist/bug.py", line 1, in <module>
  File "/mnt/c/ws/project/bug.dist/numpy/__init__.py", line 119, in <module numpy>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by KRRT7** [comment]
This is fixed by #2929

**Comment by KRRT7** [comment]
this is on factory now, it'll be released soon on pypi.
https://nuitka.net/doc/factory.html#pip

**Comment by bersbersbers** [comment]
2.3.7 seems to work, thanks!

**Comment by kayhayen** [comment]
Part of the 2.3.7 hotfix I made.
