### ISSUE TITLE
Pygments lexers aren't compiled

### ISSUE THREAD

**Issue by Moosems** [Nuitka/Nuitka#2937]
I couldn't figure out how to add the lexers based on the nuitka docs but I may be missing somethign super simple. Below is a minimum reproducible example that should recreate the issue. These python files aren't exactly data files but it doesn't appear they are caught in compilation either. Any pointers are appreciated!

```shell
python3 -m pip install pygments nuitka
echo "from pygments.lexers import get_lexer_by_name; get_lexer_by_name('python')" >> test.py
python3 -m nuitka test.py -o test --standalone --follow-imports
./test.dist/test
```

Error:
```
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/salve_app_test/test.dist/test.py", line 1, in <module>
  File "/Users/Moosems/Desktop/salve_app_test/test.dist/pygments/lexers/__init__.py", line 126, in get_lexer_by_name
  File "/Users/Moosems/Desktop/salve_app_test/test.dist/pygments/lexers/__init__.py", line 45, in _load_lexers
ModuleNotFoundError: No module named 'pygments.lexers.python'
```

**Comment by kayhayen** [comment]
You might want to use --include-module to include modules.

**Comment by Moosems** [comment]
@kayhayen Using `--include-module=pygments` did not fix it.

**Comment by kayhayen** [comment]
Feel free to read the manual for correct usage of the option.
