### ISSUE TITLE
Numpy 2.0 + standalone +no_docstrings causes TypeError: argument docstring of add_docstring should be a str

### ISSUE THREAD

**Issue by WeisSeb** [Nuitka/Nuitka#2948]
Using standalone mode with python-flag=no_docstrings causes a `TypeError: argument docstring of add_docstring should be a str` when executing compiled code that imports Numpy 2.0.0

Full error:
```
Traceback (most recent call last):
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\__init__.py", line 128, in <module numpy>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\__config__.py", line 4, in <module numpy.__config__>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\_core\__init__.py", line 23, in <module numpy._core>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\_core\multiarray.py", line 83, in <module numpy._core.multiarray>
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\_core\overrides.py", line 178, in decorator
  File "C:\_dev\IDEAPR~1\PYTHON~1\TEST~1.DIS\numpy\_core\overrides.py", line 158, in decorator
TypeError: argument docstring of add_docstring should be a str
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.3.9
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\sebastian.weis\AppData\Local\pypoetry\Cache\virtualenvs\server-zTl8wjuY-py3.11\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python

 With poetry

- The specific PyPI names and versions

  > python -m pip list -v
 numpy             2.0.0

- Example code:

```
import numpy as np

print('Hello world')
```

- Compiled with:
 ```
python -m nuitka --standalone --python-flag=no_docstrings test.py
```

**Comment by kayhayen** [comment]
Needs config added now, the module has been renamed and therefore our workarounds are no longer applied.

```
- module-name: 'numpy._core.overrides' # checksum: cda0efc0
  anti-bloat:
    - description: 'workaround numpy issues with compiled code'
      replacements_plain:
        'add_docstring(implementation, dispatcher.__doc__)': "add_docstring(implementation, dispatcher.__doc__ or '')"
        'public_api.__code__ = ': ''

```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by WeisSeb** [comment]
Can confirm it's working on factory. ty for the quick fix!

**Comment by kayhayen** [comment]
This is part of the 2.3.10 hotfix release I just made.
