### ISSUE TITLE
Unexpected error: `AttributeError: 'compiled_cell' object has no attribute`

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#2951]
Hello! Thank you for Nuitka!

In [xonsh-binary](https://github.com/anki-code/xonsh-binary) project I'm trying to build xonsh shell portable standalone binary using Nuitka on Alpine using this [Dockerfile](https://github.com/anki-code/xonsh-binary/blob/7a59ff68e8063cec0e9375eeb858f133a543c0e5/xonsh-musl-binary.Dockerfile). 
I faced with issue and I'm going to provide you minimal example.

main.py implements lazy lodaing the object:
```python
import typing as tp

class LazyObject:
    def __init__(self, load, ctx, name):
        self._lasdo = {"loaded": False, "load": load, "ctx": ctx, "name": name}

    def _lazy_obj(self):
        d = self._lasdo
        if d["loaded"]:
            obj = d["obj"]
        else:
            obj = d["load"]()
            d["ctx"][d["name"]] = d["obj"] = obj
            d["loaded"] = True
        return obj

    def __getattribute__(self, name):
        if name == "_lasdo" or name == "_lazy_obj":
            return super().__getattribute__(name)
        obj = self._lazy_obj()
        return getattr(obj, name)

    def __iter__(self):
        obj = self._lazy_obj()
        yield from obj

    def __getitem__(self, item):
        obj = self._lazy_obj()
        return obj[item]

    def __setitem__(self, key, value):
        obj = self._lazy_obj()
        obj[key] = value

    # UNCOMMENTING THIS LEADS TO THE ERROR
    #def __len__(self):
    #    return len(self._lazy_obj())

RT = tp.TypeVar("RT")

def lazyobject(f: tp.Callable[..., RT]) -> RT:
    return LazyObject(f, f.__globals__, f.__name__)


import random

@lazyobject
def TAGLINES():
    return ["a", "b", "c"]

def f():
    return random.choice(list(TAGLINES))

if __name__ == "__main__":
    print('Random:', f())
```

If I build this code without `__len__` it works:
```xsh
nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports main.py
# Starting Python compilation with Nuitka '2.3.9' on Python '3.10'
# Backend C compiler: gcc (gcc 12.2.1)
# Scons: Inherited LDFLAGS='-static -l:libpython3.10.a' variable.

main.dist/main.bin
# Random: b
```
But if you uncomment `__len__` you will have:
```xsh
main.dist/main.bin
# Traceback (most recent call last):
#  File "/tmp/main.dist/main.py", line 59, in <module>
#  File "/tmp/main.dist/main.py", line 56, in f
#  File "/tmp/main.dist/main.py", line 27, in __iter__
# AttributeError: 'compiled_cell' object has no attribute '_lazy_obj'
```

How I can fix this? Thanks!

**Comment by kayhayen** [comment]
I really want issues to have issue templates filled out. I do not reproduce the issue at all.

**Comment by kayhayen** [comment]
Honestly, please validate your Python self compilation working without me please. If you find issues like this, try say a Ubuntu Python, and if it happens there, you got something, but don't waste my time with these kinds of issues.
