### ISSUE TITLE
Using `tsdownsample` gives pyo3_runtime.PanicException: Failed to access NumPy array API capsule

### ISSUE THREAD

**Issue by my1e5** [Nuitka/Nuitka#2962]
Related to https://github.com/Nuitka/Nuitka/issues/2958. 

Using the `tsdownsample` library gives
```bash
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/numpy-0.20.0/src/npyffi/array.rs:52:14:
Failed to access NumPy array API capsule: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'numpy.core.multiarray'"), traceback: None }
```
This has been tested on Windows and MacOS and both give the same error.
## Minimal example on MacOS

```bash
$ python -m nuitka --version
2.4rc7
Commercial: None
Python: 3.12.3 (main, Apr 15 2024, 17:43:11) [Clang 17.0.6 ]
Flavor: Rye Python
Executable: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.5
Version C compiler: /usr/bin/clang (clang 15.0.0).
```
Create a file called `foo.py`
```py
from tsdownsample import LTTBDownsampler
import numpy as np

# Create a time series
y = np.random.randn(10_000_000)

# Downsample the time series
s_ds = LTTBDownsampler().downsample(y, n_out=1000)
```
and run `python -m nuitka --standalone foo.py`
```bash
$ python -m nuitka --standalone foo.py
Nuitka-Options: Used command line options: --standalone foo.py
Nuitka: Starting Python compilation with Nuitka '2.4rc7' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                         
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                           
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 147 files (no progress information available for this stage).
Nuitka-Scons: Compiled 147 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 147
Nuitka: Keeping build directory 'foo.build'.                                                       
Nuitka: Created binary that runs on macOS 11.0 (arm64) or higher.
Nuitka: Successfully created 'foo.dist/foo.bin'.
```
```bash
$ cd foo.dist/
$ ./foo.bin
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/numpy-0.20.0/src/npyffi/array.rs:52:14:
Failed to access NumPy array API capsule: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'numpy.core.multiarray'"), traceback: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/foo.dist/foo.py", line 8, in <module>
  File "/Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/foo.dist/tsdownsample/downsampling_interface.py", line 376, in downsample
  File "/Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/foo.dist/tsdownsample/downsampling_interface.py", line 135, in downsample
  File "/Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/foo.dist/tsdownsample/downsampling_interface.py", line 362, in _downsample
pyo3_runtime.PanicException: Failed to access NumPy array API capsule: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'numpy.core.multiarray'"), traceback: None }
```

## Full workflow 

I'm using rye to manage my Python project, this is the full workflow. I'm adding the `factory` branch of Nuitka as a dependency. `numpy` and `tsdownsample` are also added as dependencies.

```bash
$ rye init nuitka-tsdownsample
$ cd nuitka-tsdownsample/

$ rye add numpy
Added numpy>=2.0.0 as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements.lock
Generating dev lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements-dev.lock
Installing dependencies
   Built file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample                                                                                                                                  Built 1 editable in 328ms
Uninstalled 1 package in 0.67ms
Installed 2 packages in 16ms
 - nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + numpy==2.0.0
Done!

$ rye add tsdownsample
Added tsdownsample>=0.1.3 as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements.lock
Generating dev lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements-dev.lock
Installing dependencies
   Built file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample                                                                                                                                  Built 1 editable in 301ms
Uninstalled 1 package in 0.74ms
Installed 2 packages in 2ms
 - nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + tsdownsample==0.1.3
Done!

$ rye add nuitka --git https://github.com/Nuitka/Nuitka.git@factory
Added nuitka @ git+https://github.com/Nuitka/Nuitka.git@factory as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements.lock
Generating dev lockfile: /Users/rd/Documents/Users/my1e5/nuitka-tsdownsample/requirements-dev.lock
Installing dependencies
   Built file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample                                                                                                                                  Built 1 editable in 322ms
Uninstalled 1 package in 0.70ms
Installed 4 packages in 18ms
 + nuitka==2.4rc7 (from git+https://github.com/Nuitka/Nuitka.git@20886f658e58051c1d2329c6bddca315d5c531f6)
 - nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + nuitka-tsdownsample==0.1.0 (from file:///Users/rd/Documents/Users/my1e5/nuitka-tsdownsample)
 + ordered-set==4.1.0
 + zstandard==0.22.0
Done!
```
Then create the `foo.py` file and run `python -m nuitka --standalone foo.py`

**Comment by kayhayen** [comment]
This rust crap is hiding the module name it's working for, so it's impossible to tell from the traceback where to put the implicit dependency. Tools like Cython do this a lot more gracefully. Anyway, with more effort than necessary, I was able to figure it out.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by my1e5** [comment]
Thanks. It's working.

**Comment by kayhayen** [comment]
This is part of the 2.3.11 hotfix release.
