### ISSUE TITLE
TypeError when trying to iterate through a type

### ISSUE THREAD

**Issue by seasonsteven** [Nuitka/Nuitka#2963]
```
python -m nuitka --version

2.3.10
Commercial: None
Python: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Stephen\AppData\Local\pypoetry\Cache\virtualenvs\boom2zoom-cR8eIvh9-py3.12\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).
```
How did you install Nuitka and Python?

`poetry add nuitka --group dev`

The following Python code works just fine under the same interpreter:

```python
from enum import Flag, auto


class Base(Flag):
    def get_names(self) -> list[str]:
        return [flag.name for flag in type(self) if flag in self and flag.name is not None]


class Child(Base):
    a = auto()
    b = auto()


flags = Child.a | Child.b

print(flags.get_names())
```
```
['a', 'b']
```

But when I compile it with nuitka, it breaks.

```
python -m nuitka --standalone --output-dir=nuitka_bug_build .\nuitka_bug.py
.\nuitka_bug_build\nuitka_bug.dist\nuitka_bug.exe                          
Traceback (most recent call last):
  File "C:\Users\Stephen\projects\BOOM2Z~1\NUITKA~1\NUITKA~1.DIS\nuitka_bug.py", line 16, in <module>
  File "C:\Users\Stephen\projects\BOOM2Z~1\NUITKA~1\NUITKA~1.DIS\nuitka_bug.py", line 6, in get_names
TypeError: 'type' object is not iterable
```

**Comment by kayhayen** [comment]
This is supposed to work since Python3.9 and it's based off static optimization, that has since become invalid.

```
Nuitka-Optimization: Mini.py:6 : new_builtin : Replaced call to built-in 'type' with built-in call 'EXPRESSION_BUILTIN_TYPE1'.
Nuitka-Optimization: Mini.py:6 : new_raise : Raising for use of 'iter' on type 'type'.
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by seasonsteven** [comment]
> Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

I can confirm it is working.

```
PS C:\Nuitka\bin> git rev-parse --short HEAD
3830b59a8
```
```
PS C:\Nuitka\bin> python .\nuitka --version
2.4rc7
Commercial: None
Python: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Stephen\AppData\Local\pypoetry\Cache\virtualenvs\boom2zoom-cR8eIvh9-py3.12\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
Part of the 2.3.11 hotfix I just made.
