### ISSUE TITLE
sklearn missing .pyd file _special_ufuncs.cp312-win_amd64.pyd No module named 'scipy.special._special_ufuncs 

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [Nuitka/Nuitka#2966]
The isuse is so basic and no need complex explanation. Here is the issue:
Arguments: `python -m nuitka --standalone --onefile --windows-icon-from-ico="C:\Users\victim\Documents\HydraDragonAntivirus\assets\HydraDragonAV.png" --windows-uac-admin --include-module=win32file --include-module=win32con --include-module=notifypy --include-module=yara --include-module=yara_x --include-module=watchdog --include-module=joblib --include-module=scapy --include-module=pefile --include-data-file="C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\special\_special_ufuncs.cp312-win_amd64.pyd=scipy/special/_special_ufuncs.cp312-win_amd64.pyd" --enable-plugin=pyside6 antivirus.py`
https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/nuitka.txt
https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/antivirus.py When I compile this file without` --include-data-file="C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\special\_special_ufuncs.cp312-win_amd64.pyd=scipy/special/_special_ufuncs.cp312-win_amd64.pyd `then it cause this issue due to missing .pyd file: 
```
Traceback (most recent call last):
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\antivirus.py", line 12, in <module>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\__init__.py", line 96, in <module sklearn>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\base.py", line 19, in <module sklearn.base>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\utils\__init__.py", line 13, in <module sklearn.utils>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\utils\_chunking.py", line 8, in <module sklearn.utils._chunking>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\utils\_param_validation.py", line 14, in <module sklearn.utils._param_validation>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\utils\validation.py", line 29, in <module sklearn.utils.validation>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\sklearn\utils\_array_api.py", line 8, in <module sklearn.utils._array_api>
  File "C:\Users\victim\AppData\Local\Temp\ONEFIL~1\scipy\special\__init__.py", line 807, in <module scipy.special>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'
```
That's it. It's so clear to understand and basic issue.
nuitka --version
```
2.3.10
Commercial: None
Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\victim\AppData\Local\Programs\Python\Python312\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
python -m pip list -v
```
DEPRECATION: Loading egg at c:\users\victim\appdata\local\programs\python\python312\lib\site-packages\ssdeep_windows_32_64-0.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Package                   Version  Location                                                                                                        Installer
------------------------- -------- --------------------------------------------------------------------------------------------------------------- ---------
altgraph                  0.17.4   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
blinker                   1.7.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
certifi                   2024.2.2 C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
charset-normalizer        3.3.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
click                     8.1.7    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
colorama                  0.4.6    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
cx_Freeze                 7.0.0rc0 C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
cx_Logging                3.2.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
DateTime                  5.5      C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
Flask                     3.0.3    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
future                    1.0.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
idna                      3.7      C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
imageio                   2.34.2   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
ipaddress                 1.0.23   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
itsdangerous              2.2.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
Jinja2                    3.1.3    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
joblib                    1.4.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
lief                      0.14.1   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
loguru                    0.6.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
MarkupSafe                2.1.5    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
notify-py                 0.3.42   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
Nuitka                    2.3.10   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
numpy                     2.0.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
ordered-set               4.1.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
packaging                 24.0     C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pefile                    2023.2.7 C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pillow                    10.3.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pip                       24.1     C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
psutil                    5.9.8    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
py-tlsh                   4.7.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pyinstaller               6.6.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pyinstaller-hooks-contrib 2024.4   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
PySide6                   6.7.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
PySide6_Addons            6.7.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
PySide6_Essentials        6.7.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pytz                      2024.1   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pywin32                   306      C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
pywin32-ctypes            0.2.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
requests                  2.31.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
scapy                     2.5.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
scikit-learn              1.5.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
scipy                     1.14.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
setuptools                69.5.1   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
shiboken6                 6.7.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
ssdeep-windows-32_64      0.0.1    c:\users\victim\appdata\local\programs\python\python312\lib\site-packages\ssdeep_windows_32_64-0.0.1-py3.12.egg
ssdeep-windows-32_64      0.0.1    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\ssdeep_windows_32_64-0.0.1-py3.12.egg
threadpoolctl             3.5.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
typing_extensions         4.11.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
urllib3                   2.2.1    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
userpaths                 0.1.3    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
watchdog                  4.0.1    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
Werkzeug                  3.0.2    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
wheel                     0.43.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
win32-setctime            1.1.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
yara-python               4.5.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
yara-x                    0.4.0    C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
zope.interface            6.3      C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip
zstandard                 0.22.0   C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages                                       pip

```

**Comment by jiejie-dev** [comment]
solved this problem by downgrade scipy version to 1.13.1

**Comment by kayhayen** [comment]
There is a hotfix coming shorty that addresses it, we noticed this ourselves in Nuitka-Watch, but I was too detracted to release the hotfix yet.

**Comment by kayhayen** [comment]
Part of the 2.3.11 hotfix I just made.
