### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 75

### ISSUE THREAD

**Issue by ashutoshmishra1014** [Nuitka/Nuitka#2980]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.3.11
Commercial: None
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) 
Flavor: Anaconda Python
Executable: /home/ashu/conda/uv_project/nuitka11.8/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.4
Version C compiler: /usr/bin/gcc (gcc 11).
```

- How did you install Nuitka and Python

My application is based on the below project:
https://github.com/nerfstudio-project/nerfstudio

The repo has all the dependencies in a requirements file.
All the python dependencies were installed using pip.

One of the dependencies on the the below package:
tinycudann
tinycudann is a library written in C++/Cuda for fully fused MLPs with Python bindings to be used directly in Python.

- The specific PyPI names and versions

  > python -m pip list -v
```
Package                  Version      Editable project location                             Location                                                    Installer
------------------------ ------------ ----------------------------------------------------- ----------------------------------------------------------- ---------
absl-py                  1.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
addict                   2.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
aiosignal                1.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
anyio                    3.7.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
appdirs                  1.4.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
argon2-cffi              21.3.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
argon2-cffi-bindings     21.2.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
arrow                    1.2.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
asttokens                2.2.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
async-lru                2.0.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
attrs                    23.1.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
av                       10.0.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
awscli                   1.32.45                                                            <nuitka installation path>/lib/python3.8/site-packages pip
Babel                    2.12.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
backcall                 0.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
beautifulsoup4           4.12.2                                                             <nuitka installation path>/lib/python3.8/site-packages pip
bidict                   0.22.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
bleach                   6.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
botocore                 1.34.45                                                            <nuitka installation path>/lib/python3.8/site-packages pip
Brotli                   1.0.9                                                              <nuitka installation path>/lib/python3.8/site-packages conda
cachetools               5.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
certifi                  2023.5.7                                                           <nuitka installation path>/lib/python3.8/site-packages pip
cffi                     1.15.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
cfgv                     3.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
chardet                  5.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
charset-normalizer       2.0.4                                                              <nuitka installation path>/lib/python3.8/site-packages conda
click                    8.1.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
cmake                    3.26.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
colorama                 0.4.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
colorlog                 6.7.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
comet-ml                 3.33.11                                                            <nuitka installation path>/lib/python3.8/site-packages pip
comm                     0.1.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
commentjson              0.9.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
ConfigArgParse           1.5.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
configobj                5.0.8                                                              <nuitka installation path>/lib/python3.8/site-packages pip
contourpy                1.0.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
cryptography             40.0.2                                                             <nuitka installation path>/lib/python3.8/site-packages pip
cycler                   0.11.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
dash                     2.10.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
dash-core-components     2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
dash-html-components     2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
dash-table               5.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
debugpy                  1.6.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
decorator                5.1.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
defusedxml               0.7.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
descartes                1.1.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
dill                     0.3.8                                                              <nuitka installation path>/lib/python3.8/site-packages pip
distlib                  0.3.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
docker-pycreds           0.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
docstring-parser         0.14.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
docutils                 0.16                                                               <nuitka installation path>/lib/python3.8/site-packages pip
dulwich                  0.21.6                                                             <nuitka installation path>/lib/python3.8/site-packages pip
easydict                 1.10                                                               <nuitka installation path>/lib/python3.8/site-packages pip
everett                  3.1.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
exceptiongroup           1.1.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
executing                1.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
fastjsonschema           2.17.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
ffmpeg                   1.4                                                                <nuitka installation path>/lib/python3.8/site-packages pip
filelock                 3.12.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
fire                     0.5.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Flask                    2.2.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
fonttools                4.39.4                                                             <nuitka installation path>/lib/python3.8/site-packages pip
fqdn                     1.5.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
frozendict               2.3.8                                                              <nuitka installation path>/lib/python3.8/site-packages pip
frozenlist               1.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
gdown                    4.7.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
gitdb                    4.0.10                                                             <nuitka installation path>/lib/python3.8/site-packages pip
GitPython                3.1.31                                                             <nuitka installation path>/lib/python3.8/site-packages pip
gmpy2                    2.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages conda
google-auth              2.19.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
google-auth-oauthlib     1.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
grpcio                   1.54.2                                                             <nuitka installation path>/lib/python3.8/site-packages pip
gsplat                   0.1.5                                                              <nuitka installation path>/lib/python3.8/site-packages pip
h5py                     3.8.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
identify                 2.5.24                                                             <nuitka installation path>/lib/python3.8/site-packages pip
idna                     3.4                                                                <nuitka installation path>/lib/python3.8/site-packages pip
imageio                  2.31.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
importlib-metadata       6.6.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
importlib-resources      5.12.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
iniconfig                2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
ipykernel                6.23.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
ipython                  8.12.2                                                             <nuitka installation path>/lib/python3.8/site-packages pip
ipython-genutils         0.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
ipywidgets               8.0.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
isoduration              20.11.0                                                            <nuitka installation path>/lib/python3.8/site-packages pip
itsdangerous             2.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jaxtyping                0.2.19                                                             <nuitka installation path>/lib/python3.8/site-packages pip
jedi                     0.18.2                                                             <nuitka installation path>/lib/python3.8/site-packages pip
Jinja2                   3.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jmespath                 1.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
joblib                   1.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
json5                    0.9.14                                                             <nuitka installation path>/lib/python3.8/site-packages pip
jsonpointer              2.3                                                                <nuitka installation path>/lib/python3.8/site-packages pip
jsonschema               4.17.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
jupyter                  1.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter_client           8.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter-console          6.6.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter_core             5.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter-events           0.6.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter-lsp              2.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter_server           2.6.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyter_server_terminals 0.4.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyterlab               4.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyterlab-pygments      0.2.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
jupyterlab_server        2.22.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
jupyterlab-widgets       3.0.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
kiwisolver               1.4.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
lark-parser              0.7.8                                                              <nuitka installation path>/lib/python3.8/site-packages pip
lazy_loader              0.2                                                                <nuitka installation path>/lib/python3.8/site-packages pip
lightning-utilities      0.9.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
lit                      16.0.5                                                             <nuitka installation path>/lib/python3.8/site-packages pip
lpips                    0.1.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
lxml                     4.9.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
mapbox-earcut            1.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Markdown                 3.4.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
markdown-it-py           2.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
MarkupSafe               2.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
matplotlib               3.7.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
matplotlib-inline        0.1.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
mdurl                    0.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
mediapy                  1.1.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
mistune                  2.0.5                                                              <nuitka installation path>/lib/python3.8/site-packages pip
mkl-fft                  1.3.8                                                              <nuitka installation path>/lib/python3.8/site-packages conda
mkl-random               1.2.4                                                              <nuitka installation path>/lib/python3.8/site-packages conda
mkl-service              2.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages
mpmath                   1.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages conda
msgpack                  1.0.5                                                              <nuitka installation path>/lib/python3.8/site-packages pip
msgpack-numpy            0.4.8                                                              <nuitka installation path>/lib/python3.8/site-packages pip
multiprocess             0.70.16                                                            <nuitka installation path>/lib/python3.8/site-packages pip
nbclassic                1.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
nbclient                 0.8.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
nbconvert                7.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
nbformat                 5.7.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
nerfacc                  0.5.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
nerfstudio               1.0.1        														<nuitka installation path>/lib/python3.8/site-packages pip
nest-asyncio             1.5.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
networkx                 3.1                                                                <nuitka installation path>/lib/python3.8/site-packages conda
ninja                    1.11.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
nodeenv                  1.8.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
notebook                 6.5.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
notebook_shim            0.2.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Nuitka                   2.3.11                                                             <nuitka installation path>/lib/python3.8/site-packages pip
numpy                    1.24.3                                                             <nuitka installation path>/lib/python3.8/site-packages conda
nuscenes-devkit          1.1.9                                                              <nuitka installation path>/lib/python3.8/site-packages pip
oauthlib                 3.2.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
open3d                   0.17.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
opencv-python            4.8.0.76                                                           <nuitka installation path>/lib/python3.8/site-packages pip
ordered-set              4.1.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
overrides                7.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
packaging                23.1                                                               <nuitka installation path>/lib/python3.8/site-packages pip
pandas                   2.0.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pandocfilters            1.5.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
parso                    0.8.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pathos                   0.3.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pathtools                0.1.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pexpect                  4.8.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pickleshare              0.7.5                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Pillow                   9.5.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pip                      24.0                                                               <nuitka installation path>/lib/python3.8/site-packages
pkgutil_resolve_name     1.3.10                                                             <nuitka installation path>/lib/python3.8/site-packages pip
platformdirs             3.5.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
plotly                   5.14.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
pluggy                   1.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
plyfile                  1.0.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pox                      0.3.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
ppft                     1.7.6.8                                                            <nuitka installation path>/lib/python3.8/site-packages pip
pre-commit               3.3.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
prometheus-client        0.17.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
prompt-toolkit           3.0.38                                                             <nuitka installation path>/lib/python3.8/site-packages pip
protobuf                 3.20.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
psutil                   5.9.5                                                              <nuitka installation path>/lib/python3.8/site-packages pip
ptyprocess               0.7.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pure-eval                0.2.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
py                       1.11.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
pyarmor                  8.5.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyarmor.cli.core         6.5.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyarmor-webui            2.5                                                                <nuitka installation path>/lib/python3.8/site-packages pip
pyarrow                  12.0.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
pyasn1                   0.5.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyasn1-modules           0.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pycocotools              2.0.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pycollada                0.7.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pycparser                2.21                                                               <nuitka installation path>/lib/python3.8/site-packages pip
pyequilib                0.5.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Pygments                 2.15.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
pyliblzfse               0.4.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pymeshlab                2022.2.post4                                                       <nuitka installation path>/lib/python3.8/site-packages pip
pyngrok                  6.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyparsing                3.0.9                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyquaternion             0.9.9                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pyrsistent               0.19.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
PySocks                  1.7.1                                                              <nuitka installation path>/lib/python3.8/site-packages conda
pytest                   7.4.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pytest-html              3.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pytest-metadata          3.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
python-box               6.1.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
python-dateutil          2.8.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
python-engineio          4.4.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
python-json-logger       2.0.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
python-socketio          5.8.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pytorch-msssim           1.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
pytz                     2023.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
PyWavelets               1.4.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
PyYAML                   6.0                                                                <nuitka installation path>/lib/python3.8/site-packages pip
pyzmq                    25.1.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
qtconsole                5.4.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
QtPy                     2.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
rawpy                    0.18.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
ray                      2.6.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
requests                 2.31.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
requests-oauthlib        1.3.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
requests-toolbelt        1.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
rfc3339-validator        0.1.4                                                              <nuitka installation path>/lib/python3.8/site-packages pip
rfc3986-validator        0.1.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
rich                     13.3.5                                                             <nuitka installation path>/lib/python3.8/site-packages pip
rsa                      4.7.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
Rtree                    1.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
s3transfer               0.10.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
scikit-image             0.20.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
scikit-learn             1.2.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
scipy                    1.9.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
semantic-version         2.10.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
Send2Trash               1.8.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
sentry-sdk               1.24.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
setproctitle             1.3.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
setuptools               67.8.0                                                             <nuitka installation path>/lib/python3.8/site-packages
shapely                  2.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
shtab                    1.6.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
simplejson               3.19.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
six                      1.16.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
smmap                    5.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
sniffio                  1.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
soupsieve                2.4.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
splines                  0.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
stack-data               0.6.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
svg.path                 6.3                                                                <nuitka installation path>/lib/python3.8/site-packages pip
sympy                    1.12                                                               <nuitka installation path>/lib/python3.8/site-packages conda
tenacity                 8.2.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tensorboard              2.13.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
tensorboard-data-server  0.7.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
termcolor                2.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
terminado                0.17.1                                                             <nuitka installation path>/lib/python3.8/site-packages pip
threadpoolctl            3.1.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tifffile                 2023.4.12                                                          <nuitka installation path>/lib/python3.8/site-packages pip
timm                     0.6.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tinycss2                 1.2.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tinycudann               1.7                                                                <nuitka installation path>/lib/python3.8/site-packages pip
tomli                    2.0.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
torch                    2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages
torch-fidelity           0.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
torchaudio               2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages
torchmetrics             1.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
torchvision              0.15.0                                                             <nuitka installation path>/lib/python3.8/site-packages
tornado                  6.3.2                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tqdm                     4.65.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
traitlets                5.9.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
trimesh                  3.21.7                                                             <nuitka installation path>/lib/python3.8/site-packages pip
triton                   2.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages
typeguard                4.0.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
typing_extensions        4.11.0                                                             <nuitka installation path>/lib/python3.8/site-packages conda
tyro                     0.7.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
tzdata                   2023.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
uri-template             1.2.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
urllib3                  1.26.16                                                            <nuitka installation path>/lib/python3.8/site-packages pip
virtualenv               20.23.0                                                            <nuitka installation path>/lib/python3.8/site-packages pip
viser                    0.1.21                                                             <nuitka installation path>/lib/python3.8/site-packages pip
wandb                    0.15.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
wcwidth                  0.2.6                                                              <nuitka installation path>/lib/python3.8/site-packages pip
webcolors                1.13                                                               <nuitka installation path>/lib/python3.8/site-packages pip
webencodings             0.5.1                                                              <nuitka installation path>/lib/python3.8/site-packages pip
websocket-client         1.3.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
websockets               11.0.3                                                             <nuitka installation path>/lib/python3.8/site-packages pip
Werkzeug                 2.2.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
wheel                    0.38.4                                                             <nuitka installation path>/lib/python3.8/site-packages
widgetsnbextension       4.0.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
wrapt                    1.15.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
wurlitzer                3.0.3                                                              <nuitka installation path>/lib/python3.8/site-packages pip
xatlas                   0.0.7                                                              <nuitka installation path>/lib/python3.8/site-packages pip
xxhash                   3.3.0                                                              <nuitka installation path>/lib/python3.8/site-packages pip
yourdfpy                 0.0.53                                                             <nuitka installation path>/lib/python3.8/site-packages pip
zipp                     3.15.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
zstandard                0.22.0                                                             <nuitka installation path>/lib/python3.8/site-packages pip
```

- Also supply a Short, Self Contained, Correct, Example

`python -m nuitka --follow-imports --standalone nerfstudio/scripts/train.py`

- Error
```
Traceback (most recent call last):
  File "<current working dir>/train.dist/train.py", line 62, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/configs/method_configs.py", line 40, in <module nerfstudio.configs.method_configs>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/data/datasets/depth_dataset.py", line 31, in <module nerfstudio.data.datasets.depth_dataset>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/model_components/losses.py", line 26, in <module nerfstudio.model_components.losses>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/field_components/__init__.py", line 17, in <module nerfstudio.field_components>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/field_components/encodings.py", line 30, in <module nerfstudio.field_components.encodings>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/nerfstudio/utils/external.py", line 42, in <module nerfstudio.utils.external>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/tinycudann/__init__.py", line 9, in <module tinycudann>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<current working dir>/train.dist/tinycudann/modules.py", line 58, in <module tinycudann.modules>
OSError: Could not find compatible tinycudann extension for compute capability 75.
```

**Comment by ashutoshmishra1014** [comment]
FYI, when I had previously tried pyinstaller for bundling my application I had received a similar error but I could resolve it by using
`hiddenimports += collect_submodules('tinycudann_bindings')` as my bundle was missing the `tinycudann_bindings._75_C`.

Is there something similar to achieve in Nuitka as well?

**Comment by ashutoshmishra1014** [comment]
I have tried this option since the module is a dynamically loaded one but no luck yet.
```
python -m nuitka --follow-imports --standalone --include-module=tinycudann_bindings nerfstudio/scripts/train.py
```
Please find this as reference:
https://github.com/NVlabs/tiny-cuda-nn/blob/4892659e015b12bd2fce446b8a8e33e646b21746/bindings/torch/tinycudann/modules.py#L54-L63

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
