### ISSUE TITLE
Adding method `__len__` produces `segmentation fault`

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#2985]
Hello!

The code is working in Python but after compilation in Nuitka standalone produces `segmentation fault` if the class has `__len__` method.

I'm going to provide: 
* Minimal example.
* Full repeatable list of commands in docker.
* Full detailed build log.
* Full detailed run log.
* The difference after tracing this.

Please help to fix the issue.

Code `run.py`:

```xsh
class LazyObject:
    def __init__(self, load, ctx, name):
        self._lasdo = {"loaded": False, "load": load, "ctx": ctx, "name": name}

    def _lazy_obj(self):
        d = self._lasdo
        if d["loaded"]:
            obj = d["obj"]
        else:
            obj = d["load"]()
            d["ctx"][d["name"]] = d["obj"] = obj
            d["loaded"] = True
        return obj

    def __getattribute__(self, name):
        if name == "_lasdo" or name == "_lazy_obj":
            # print(super()) # <super: <class 'LazyObject'>, <LazyObject object>>
            return super().__getattribute__(name)
        obj = self._lazy_obj()
        return getattr(obj, name)

    def __iter__(self):
        # print('iter')
        obj = self._lazy_obj()
        yield from obj

    def __getitem__(self, item):
        obj = self._lazy_obj()
        return obj[item]

    def __setitem__(self, key, value):
        obj = self._lazy_obj()
        obj[key] = value

    # REMOVING THIS FUNCTION REMOVES THE ERROR
    def __len__(self):
        # print('len')  # we have `len+iter` when doing `run.py` and `len+len+segfault` when doing `run.bin`.
        return len(self._lazy_obj())


def lazyobject(f):
    return LazyObject(f, f.__globals__, f.__name__)


@lazyobject
def TAGLINES():
    return ["a", "b", "c"]

def f():
    return list(TAGLINES)

if __name__ == "__main__":
    print('List:', f())
```

Build:

```xsh
docker run --rm -it ubuntu:24.04 bash

apt update && apt install -y curl git vim patchelf elfutils binutils-common binutils

# Install mamba
"${SHELL}" <(curl -L https://micro.mamba.pm/install.sh)

source ~/.bashrc
micromamba activate base
micromamba install -c conda-forge libpython-static==3.11.3 gcc ccache  # 3.11.3 because #2521
pip install nuitka

python run.py
# List: [a,b,c]

nuitka3 --standalone --static-libpython=yes \
        --show-progress --show-scons --show-modules --python-flag=nosite,-O,-v \
        --assume-yes-for-downloads --jobs=6  run.py
# Nuitka '2.3.11' on Python '3.11'
# Nuitka: Successfully created 'run.dist/run.bin'.

./run.dist/run.bin
# ...
# Nuitka: A segmentation fault has occurred.

ldd ./run.dist/run.bin
#        linux-vdso.so.1 (0x0000ffffb4157000)
#        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffb3470000)
#        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffb33c0000)
#        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffb3390000)
#        libutil.so.1 => /lib/aarch64-linux-gnu/libutil.so.1 (0x0000ffffb3360000)
#        librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000ffffb3330000)
#        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb3170000)
#        /lib/ld-linux-aarch64.so.1 (0x0000ffffb411a000)
```

Log:

* [build.log](https://github.com/user-attachments/files/16116650/build.log)
* [run.log](https://github.com/user-attachments/files/16116651/run.log)

The difference I caught if we add `print('len')` and `print('iter')` to appropriate dunder methods:
```xsh
python run.py
# len
# -------- __getattribute__ _lazy_obj
# -------- __getattribute__ _lasdo
# iter
# -------- __getattribute__ _lazy_obj
# -------- __getattribute__ _lasdo
# List: ['a', 'b', 'c']

./run.bin
# len
# -------- __getattribute__ _lazy_obj
# -------- __getattribute__ _lasdo
# len    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 🔴 not iter like above
# -------- __getattribute__ _lazy_obj
# -------- __getattribute__ _lasdo
# Nuitka: A segmentation fault has occurred.
```

Please help. Thanks!

**Comment by kayhayen** [comment]
I am not sure why you use standalone, etc. for me, mere accelerated mode gives me this:

```
Nuitka: Launching 'Mini.bin'.
Traceback (most recent call last):
  File "/home/hayen/repos/Py2C/Mini.py", line 53, in <module>
    print('List:', f())
  File "/home/hayen/repos/Py2C/Mini.py", line 50, in f
    return list(TAGLINES)
  File "/home/hayen/repos/Py2C/Mini.py", line 24, in __iter__
    obj = self._lazy_obj()
```

**Comment by kayhayen** [comment]
And with `--debug` I am getting this:

> Mini.bin: /home/hayen/repos/Py2C/nuitka/build/static_src/HelpersLists.c:163: LIST_EXTEND_FROM_ITERABLE: Assertion `Py_REFCNT(other) > 0' failed.

So it seems some form of corruption is going on, and that can segfault or confuse objects, anything can happen, very bad kind of bug. I haven't seen the kind in a while, curious what it is.

**Comment by kayhayen** [comment]
So, it seems the `len` made by the list (intended to pre-allocate the list) somehow releases the lazy object, which means it needs to be found out, how that is happening.

**Comment by kayhayen** [comment]
So, the lazy object is self-removing its reference in the globals dictionary which at the time is the only reference, so when then converting to a list, after getting a size hint, the object is corrupt, we need to hold a reference while using it and that fixes it.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is part of the stable release 2.4 that I just made.
