### ISSUE TITLE
Mac M1: symbol not found in flat namespace '_PyExc_MemoryError'

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#2987]
Hello!
I've built simple app with one line `import subprocess` and compile with Nuitka `factory` on Mac M1 with Python 3.11.1 from Mamba but I have `_PyExc_MemoryError` as the result of run.

I'm not installing clang because xcode already installed.
```xsh
uname -a
# Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; 
# root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64 arm Darwin

# Install mamba
"${SHELL}" <(curl -L https://micro.mamba.pm/install.sh)

source ~/.bashrc
micromamba activate base
micromamba install -c conda-forge libpython-static==3.11.3
# libpython-static    3.11.3        hb7217d7_0_cpython  conda-forge
# python              3.11.3        h1456518_0_cpython  conda-forge

echo "import subprocess" > run.py
nuitka --standalone --static-libpython=yes  --show-progress --show-scons --show-modules  --
assume-yes-for-downloads --jobs=6 run.py
# Nuitka: Starting Python compilation with Nuitka '2.4rc8' on Python '3.11' commercial grade
# Nuitka: 'not installed'.

./run.dist/run.bin
# Traceback (most recent call last):
#   File "/Users/pc/git/nui/run.dist/run.py", line 1, in <module>
#   File "/Users/pc/git/nui/run.dist/subprocess.py", line 104, in <module>
# ImportError: dlopen(/Users/pc/git/nui/run.dist/_posixsubprocess.so, 0x0002): 
# symbol not found in flat namespace '_PyExc_MemoryError'
```

Could you please help me understand the root of the problem?
I can provide more information if it's needed. Thanks!

**Comment by kayhayen** [comment]
Like I said, I don't think there is a difference anymore, like in they are the same these days, but proving me wrong would be good.

**Comment by Jaydenha09** [comment]
also have that isssue, tried using --static-libpython=no, compiled successfully and I can run it without any issue

**Comment by kayhayen** [comment]
I believe this has been dealt with outside of this issue.

**Comment by Jaydenha09** [comment]
I tested it, works well for me

**Comment by kayhayen** [comment]
```
python bin/nuitka-run tests/standalone/CtypesUsing.py

Nuitka-Options: Used command line options: --standalone
Nuitka-Options: tests/standalone/CtypesUsing.py
Nuitka-Options: Detected static libpython to exist, consider
Nuitka-Options: '--static-libpython=yes' for better performance, but errors may
Nuitka-Options: happen.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install
Nuitka:WARNING: 'ordered-set' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka: Starting Python compilation with Nuitka '2.5rc0' on Python '3.11'
Nuitka: commercial grade '3.7.4'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to    
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: may slow down by
Nuitka-Plugins:anti-bloat: using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: can break calls of
Nuitka-Plugins:anti-bloat: 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 16.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 6
Nuitka: Keeping build directory 'CtypesUsing.build'.                            
Nuitka: Created binary that runs on macOS 11.1 (arm64) or higher.
Nuitka: Successfully created 'CtypesUsing.dist/CtypesUsing.bin'.
Nuitka: Launching 'CtypesUsing.dist/CtypesUsing.bin'.
Hello, World
OK.
(base) hayen@kaymac Py2C % python bin/nuitka-run --static-libpython=yes tests/standalone/CtypesUsing.py
Nuitka-Options: Used command line options: --standalone --static-libpython=yes
Nuitka-Options: tests/standalone/CtypesUsing.py
Nuitka:WARNING: Using very slow fallback for ordered sets, please install
Nuitka:WARNING: 'ordered-set' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka: Starting Python compilation with Nuitka '2.5rc0' on Python '3.11'
Nuitka: commercial grade '3.7.4'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to    
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: may slow down by
Nuitka-Plugins:anti-bloat: using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to
Nuitka-Plugins:anti-bloat: avoid bloat, but this may cause: can break calls of
Nuitka-Plugins:anti-bloat: 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 16.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 6
Nuitka: Keeping build directory 'CtypesUsing.build'.                            
Nuitka: Created binary that runs on macOS 11.1 (arm64) or higher.
Nuitka: Successfully created 'CtypesUsing.dist/CtypesUsing.bin'.
Nuitka: Launching 'CtypesUsing.dist/CtypesUsing.bin'.
IMPORT_HARD_CTYPES : "Unexpected failure of hard import of 'ctypes'"
zsh: abort      python bin/nuitka-run --static-libpython=yes tests/standalone/CtypesUsing.py
```

**Comment by kayhayen** [comment]
I think disabling LTO was what I did there, but it seems their static libpython is no longer good or what.

**Comment by kayhayen** [comment]
So, at least by default it's working, and it suggesting to use the option, that it told you might not work, is then the issue.

**Comment by kayhayen** [comment]
Seems the warning is even given in cases known not to work, which however, for Anaconda on macOS is only true as an exception, and maybe not persistently true anyway. So this issue is invalid from my point of view. If we find out better linker options, this may be rescued, but it's better tracked elsewhere.
