### ISSUE TITLE
Application error when buiid exe uses package selenium_driverless

### ISSUE THREAD

**Issue by tuandoan1608** [Nuitka/Nuitka#3000]
Why when I use the Selenium_driverless package in my application, when building the exe with nuitka I get an error like the following

error output
```
Path to the extension doesn't exist
Traceback (most recent call last):
  File "C:\Users\tuan\AppData\Local\Temp\ONEFIL~1\selenium_driverless\webdriver.py", line 154, in start_session
  File "C:\Users\tuan\AppData\Local\Temp\ONEFIL~1\selenium_driverless\types\options.py", line 311, in add_extension
OSError: Path to the extension doesn't exist
```

my code:
```
          from selenium_driverless import webdriver
          import asyncio
          import traceback
          
          async def main():
              try:
                  options = webdriver.ChromeOptions()
                  async with webdriver.Chrome(options=options) as driver:
                      await driver.get('https://discord.com/login', wait_load=True)
                      print(await driver.title)
              except Exception as e:
                  traceback.print_exc()
          
          
          asyncio.run(main())
```

I use the following command to build exe: python -m nuitka --follow-imports --mingw64 --onefile --include-package=selenium_driverless  run_form.py

**Comment by kayhayen** [comment]
Thanks, good job, I am merging this to develop and then for the next hotfix.

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made, not sure what happening in 2.4, probably was in the hotfix too, but I didn't update this.
