### ISSUE TITLE
TypeVar's created during class creation do not carry over to the class's local scope

### ISSUE THREAD

**Issue by Rooba** [Nuitka/Nuitka#3005]
`Nuitka version, full Python version, flavor, OS, etc. as output by this exact command.`

```sh
% python3 -m nuitka --version
2.3.11
Commercial: None
Python: 3.12.4 (main, Jun 17 2024, 22:50:04) [GCC 13.2.0]
Flavor: pyenv
Executable: /home/ra/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian sid
Version C compiler: /usr/bin/gcc (gcc 13).
```

`How did you install Nuitka and Python`

```sh
% pyenv install 3.12.4
% pyenv local 3.12.4
% python3 -m venv .venv
% source .venv/bin/activate
% pip install nuitka
```

The following should run without issue
```py
class Foo[A]:
    def foo(self, a: A) -> A: ...


Foo[int]().foo(1)
```

but even when ran with `--full-compat`, it gives an error
```sh
% python3 -m nuitka --full-compat --run test-2.py
Nuitka-Options: Used command line options: --full-compat --run test-2.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.3.11' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 4
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 2
Nuitka: Keeping build directory 'test-2.build'.
Nuitka: Successfully created 'test-2.bin'.
Nuitka: Launching 'test-2.bin'.
Traceback (most recent call last):
  File "/home/ra/test-2.py", line 1, in <module>
    class Foo[A]:
    
  File "/home/ra/test-2.py", line 2, in Foo
    def foo(self, a: A) -> A: ...

NameError: name 'A' is not defined
```

**Comment by kayhayen** [comment]
This is indeed not yet implemented.

**Comment by kayhayen** [comment]
I checked it out, and find that's actually relatively simple to implement. All it takes will be a function wrapping the class creation functions there already is, and these generics are mostly closure variables, like we already have for `__class__` with the class body, so this probably could be a manually managed normal function or what we call an outline function (an inlined function effectively that still looks like a function).

I don't want to do this before 2.4 release, but it will be high on the list right after release. Might be hotfixable, but I am not sure of that.

**Comment by kayhayen** [comment]
I did the wrapping, but the way `__bases__` is extended here, with a temporary value first and then it becomes visible as the class attribute is not yet properly handled, thus segfaulting, but this will be an easy step to add I hope.

**Comment by nukemiko** [comment]
Reproduced on Nuitka 2.4.11:

```sh-session
$ > python3 -m nuitka --clang --version
2.4
Commercial: None
Python: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Flavor: Arch Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/bin/clang (clang 18.1.8).
$ >
```

With the following code:

```python
# -*- encoding: utf-8 -*-
import sys
from collections.abc import Callable


def uselessDecorator[** P, R](func: Callable[P, R], /) -> Callable[P, R]:
    return func


@uselessDecorator
def printSysArgv(*argv: str) -> None:
    print('sys.argv:', *argv)


if __name__ == '__main__':
    printSysArgv(*sys.argv)
```

Compile with the following command line:

```sh-session
$ > nuitka --standalone --clang nuitka-bug-reproduce.py
```

And the following error occurred:

```sh-session
$ > nuitka-bug-reproduce.dist/nuitka-bug-reproduce.bin $(factor 2147483648)
Traceback (most recent call last):
  File "/home/user/compiled/nuitka-bug-reproduce.dist/nuitka-bug-reproduce.py", line 6, in <module>
NameError: name 'P' is not defined
$ >
```

**Comment by kayhayen** [comment]
My work for this is still incomplete, so 2.5 won't even have it yet, but it's high on the list of things to get done.

**Comment by kayhayen** [comment]
Works with 4.0.4 now
