### ISSUE TITLE
Bug with --windows-console-mode=attach

### ISSUE THREAD

**Issue by Sash0check** [Nuitka/Nuitka#3030]
```
2.4.3
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: .venv\Scripts\python.exe
OS: Windows
```

Python installed via python website as standalone
Nuitka installed via pip install nuitka

The specific PyPI names and versions:
None

compile command
```
python -m nuitka --standalone example.py  --windows-console-mode=attach
```

example code:
```python
import subprocess
import traceback


def get_hardware_id():
    current_machine_id = (
        subprocess.check_output('wmic csproduct get uuid', shell=True)
        .split(b'\n')[1]
        .strip()
    )
    return current_machine_id


if __name__ == '__main__':
    try:
        get_hardware_id()
    except:
        with open('output.txt', 'w') as f:
            f.write(traceback.format_exc())

```

Error Log
```
Traceback (most recent call last):
  File "F:\Projects\ub\example.dist\example.py", line 16, in <module>
  File "F:\Projects\ub\example.dist\example.py", line 7, in get_hardware_id
  File "F:\Projects\ub\example.dist\subprocess.py", line 421, in check_output
  File "F:\Projects\ub\example.dist\subprocess.py", line 503, in run
  File "F:\Projects\ub\example.dist\subprocess.py", line 837, in __init__
  File "F:\Projects\ub\example.dist\subprocess.py", line 1272, in _get_handles
OSError: [WinError 6] The handle is invalid

```

Problem discription:
Error presist if programm starts without terminal and only in attach mode. There is problem with commands: subprocess.check_output or subprocess.Popen. 

Workaround for fix it:
Add stdin=subprocess.DEVNULL
```python
current_machine_id = (
                subprocess.check_output('wmic csproduct get uuid', shell=True, stdin=subprocess.DEVNULL)
                .split(b'\n')[1]
                .strip()
            )
```

**Comment by Sash0check** [comment]
Looks like problem presists only if you redirecting stdout. subprocess. Popen without redirecting works normally

**Comment by kayhayen** [comment]
With the terminal, no problem is observed, but I take that you are saying it's happening without it. And I hate how it's hard to test that at all. I redirected stderr to a file with --force-stderr and that file remains empty, and seemingly is ineffective, since I see it on the terminal with a console and nothing in the file. That might be an unrelated bug though, but I really don't want to write to a file manually for this.

**Comment by kayhayen** [comment]
There is way too much of a mess going on, the various output modes overlap to get them good with forcing and attaching easily, None, NULL, attach and forced stderr are fighting a fierce battle in the code.

However, this code here:

```
        int int_res = dup2(os_handle, fileno(std_handle));

        // Without a console, this is normal.
        if (int_res == -1) {
            perror("_open_osfhandle");
            abort();
        }
```

Should probably be this

```
        int _int_res = dup2(os_handle, fileno(std_handle));

        if (_int_res == -1) {
            // Note: Without a console, this is normal to get no file number to
            // work with.
        }
```

But I don't think it is affected by your code at all, since that's only happening when forcing outputs, and it seems only attach is triggering it.

**Comment by kayhayen** [comment]
I somehow feel 4 years is a bit much for any statement about that feature.

The handles produced by attaching are not suitable for all code, that is probably a hard to change fact. If somebody wanted to produce a monkey-patch for the various subprocess functions, to default arguments as needed, be my guest, but the next best thing is to not use that mode. Probably this issue should become a deployment hook, where we catch subprocess errors like this one. But I think that I know that e.g. `os.system` cannot be made to work.

Also not sure, if this only affects stdin, but if not also stdout and stderr need that too.

**Comment by kayhayen** [comment]
These are two different things, not having a `sys.stdin` (and all other handles) with `pythonw.exe` was initially what Nuitka did, and then it changed to making it a `NUL` file by default. Your code not working with `pythonw.exe` is a bug of your code. That would be an old issue by now, and long since resolved. 

However, attach has problems providing file handles that can be passed to child processes, and therefore it won't work. I was wondering however, if this maybe *only* affected stdin. In which case, as most programs don't use input, we might just do NUL on those inputs. At least in the issue code, it's strange how stderr doesn't seem to need it. Maybe it's some sort of security thing of Windows, where you won't be able to pass the terminal input on. But otherwise, why does sys.stderr not pose the issue in the checked output call, that makes no sense.

**Comment by kayhayen** [comment]
So, I checked the code, and found that the code for stdin has a bug indeed, opening the attached handle for writing, rather than reading:

-        FILE_HANDLE win_handle = CreateFileW(L"CONIN$", GENERIC_WRITE, FILE_SHARE_READ, &security_attributes,
+        FILE_HANDLE win_handle = CreateFileW(L"CONIN$", GENERIC_READ, FILE_SHARE_READ, &security_attributes,

With that it works. Notice how I had only changed one of the modes to READ, my bad.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This didn't make the 2.6 release, but it will be in 2.6.1 hotfix once I make it.

**Comment by kayhayen** [comment]
Part of the 2.6.1 hotfix release I just made.
