### ISSUE TITLE
UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 56546: illegal multibyte sequence

### ISSUE THREAD

**Issue by diannehidalgo** [Nuitka/Nuitka#3031]
Hello, I'm having an issue with compiling my python script. Please help. 
I tried running this command first ->` chcp 932`
Then this command to compile the python script -> `nuitka --standalone --windows-console-mode=disable --lto=yes export_excel.py`
But still got the same error.

Below is the crash report.

`<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.4.4" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="UnicodeDecodeError" exception_value="'cp932' codec can't decode byte 0x85 in position 56421: illegal multibyte sequence">
Traceback (most recent call last):
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\MainControl.py", line 1155, in main
    _main()
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\MainControl.py", line 1004, in _main
    result, scons_options = compileTree()
                            ^^^^^^^^^^^^^
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\MainControl.py", line 919, in compileTree
    result, scons_options = runSconsBackend()
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\MainControl.py", line 767, in runSconsBackend
    runScons(
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\build\SconsInterface.py", line 403, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 336, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\build\SconsCaching.py", line 282, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 793, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\社内開発ツール\1230394_情報管理ツール\excel_tool_prototype\prototype1\scripts\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 811, in getFileContents
    return f.read()       
^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 56421: illegal multibyte sequence`

I installed Nuitka and python using poetry.  Below are the dependecies installed:
[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.11.0"
xlwings = "^0.31.10"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
ruff = "^0.5.4"
nuitka = "^2.4.4"

**Comment by Choonholic** [comment]
From what I've tested, if your code is old and written in Shift-JIS, you'll have problems. Maybe in Japan they still use Shift-JIS in their code instead of Unicode? If you don't convert the code to Unicode, you'll continue to get the same error. I suggest you have an internal discussion and seriously consider converting your code to Unicode.

私がテストした結果、コードがShift-JISで書かれている古いコードであれば、問題が発生します。まさか日本ではまだUnicodeの代わりにShift-JISをコードで使っているのでしょうか？コードをUnicodeに変換しないと同じエラーが発生し続けます。内部的に協議して、Unicodeにコードを変換することを真剣に検討することをお勧めします。

**Comment by diannehidalgo** [comment]
Thank you for your comment! I actually wrote the code in UTF-8. 
We've made a requirement internally to code in UTF-8.

**Comment by kayhayen** [comment]
Nuitka is supposed to be compatible with all codes. I think this is about module names that are not ASCII showing up in the ccache log file. We are reading this file with the default locale, however, it seems ccache is writing with in UTF8, so we need to enforce that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
I wasn't able to test this, so I just did it, obviously ccache doesn't respect platform locale of Windows, which is why this is happening. Ought to work and will be part of the next hotfix too.

**Comment by diannehidalgo** [comment]
thank you sir! I tried doing it but I still got the same error.

**Comment by kayhayen** [comment]
Can you provide the new traceback so I can see what it does?
