### ISSUE TITLE
Error in using nuitka-hints.py to perform hints compilation. Any compatible problem between nuitka 2.4.4 and nuitka-hints.py?

### ISSUE THREAD

**Issue by jhsa26** [Nuitka/Nuitka#3043]
Platform: Windows 10
Nuitka Version 2.4.4

Nuitka-Reports: report.
(SWDITpy310) PS E:\SurfaceWaveTomoSoftwaresDevelopment\Work\tomo\Share-SWDI-0718\Share-wangshuaibing0718> python .\nuitka-hints.py --enable-plugin=numpy --enable-plugin=pyqt5 .\SurfaceWaveTomoEXE.py
.\SurfaceWaveTomoEXE-310-win32-64.json
NUITKA v(2, 4, 4) on Python 3.10.14 (win32) is compiling '.\SurfaceWaveTomoEXE.py' with these options:
 --standalone
 --nofollow-imports
 --hinted-json-file=.\SurfaceWaveTomoEXE-310-win32-64.json
 --enable-plugin=numpy
 --enable-plugin=pyqt5

Nuitka-Options: Used command line options: --standalone --nofollow-imports
Nuitka-Options: --user-plugin=E:\SurfaceWaveTomoSoftwaresDevelopment\Work\tomo\Share-SWDI-0718\Share-wangshuaibing0718\hinted-mods.py
Nuitka-Options: --hinted-json-file=.\SurfaceWaveTomoEXE-310-win32-64.json --enable-plugin=numpy --enable-plugin=pyqt5
Nuitka-Options: .\SurfaceWaveTomoEXE.py
Nuitka-Options:WARNING: Following no imports is unlikely to work for standalone mode and should not be specified.
Nuitka-Plugins:WARNING: numpy: This plugin has been deprecated, do not enable it anymore.
Nuitka-Plugins:WARNING: pyqt5: For the obsolete PyQt5 the Nuitka support is incomplete. Threading, callbacks to compiledNuitka-Plugins:WARNING: functions, etc. may not be working.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/pyqt5.html
Nuitka-Plugins:hinted-mods: 'hinted-mods' is adding the following options:
numpy {'matplotlib': True, 'scipy': True}
qt-plugins {}
multiprocessing {}
Did you enable the above plugins (if any) manually?yes
Nuitka-Plugins:hinted-mods: --recurse-to=zmq.utils and 1870 more modules
Nuitka: Starting Python compilation with Nuitka '2.4.4' on Python '3.10' commercial grade 'not installed'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\__main__.py", line 206, in <module>
    main()
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\MainControl.py", line 1155, in main
    _main()
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\MainControl.py", line 995, in _main
    main_module = _createMainModule()
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\MainControl.py", line 256, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\optimizations\Optimization.py", line 332, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\optimizations\Optimization.py", line 288, in makeOptimizationPass
    changed, micro_passes = optimizeModule(current_module)
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\optimizations\Optimization.py", line 166, in optimizeModule
    return optimizeCompiledPythonModule(module)
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\optimizations\Optimization.py", line 126, in optimizeCompiledPythonModule
    considerUsedModules(module=module, pass_count=pass_count)
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\importing\Recursion.py", line 513, in considerUsedModules
    decision, decision_reason = decideRecursion(
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\importing\Recursion.py", line 128, in decideRecursion
    _recursion_decision_cache[key] = _decideRecursion(
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\importing\Recursion.py", line 185, in _decideRecursion
    plugin_decision, deciding_plugins = Plugins.onModuleEncounter(
  File "C:\Program Files\Anaconda3\envs\SWDITpy310\lib\site-packages\nuitka\plugins\Plugins.py", line 1004, in onModuleEncounter
    must_recurse = plugin.onModuleEncounter(
TypeError: HintedModsPlugin.onModuleEncounter() got an unexpected keyword argument 'using_module_name'
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.

**Comment by kayhayen** [comment]
This plugin is supported no more for many years now. The coming PGO feature will replace it.
