### ISSUE TITLE
[BUG] --jobs options with negative values is not working on nuitka 2.4

### ISSUE THREAD

**Issue by shenwpo** [Nuitka/Nuitka#3047]
- python -m nuitka --version
```
2.4.5
Commercial: None
Python: 3.12.4 (main, Jul 29 2024, 10:35:32) [GCC 11.4.0]
Flavor: Unknown
Executable: /opt/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.4
Version C compiler: /usr/bin/gcc (gcc 11).
```

- How did you install Nuitka and Python
```
 pip install nuitka -U
```

The following error occurs after executing ```python3 -m nuitka --job=-2 hello.py```
```
0.525 Nuitka-Options: Used command line options: --jobs=-2  hello.py
0.534 Traceback (most recent call last):
0.534   File "/opt/venv/lib/python3.10/site-packages/nuitka/__main__.py", line 206, in <module>
0.534     main()
0.534   File "/opt/venv/lib/python3.10/site-packages/nuitka/__main__.py", line 151, in main
0.535     Options.commentArgs()
0.535   File "/opt/venv/lib/python3.10/site-packages/nuitka/Options.py", line 1040, in commentArgs
0.535     getJobLimit()
0.535   File "/opt/venv/lib/python3.10/site-packages/nuitka/Options.py", line 1707, in getJobLimit
0.535     result = max(1, getCPUCoreCount() + jobs)
0.535 TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by shenwpo** [comment]
Maybe we should replace ```result = max(1, getCPUCoreCount() + jobs)``` with ```result = max(1, getCPUCoreCount() + result)```.

**Comment by kayhayen** [comment]
Oh, seems I added that, but never tried it. We intend to use that with CI to not starve Azure processes during compilation, but I didn't get around to it yet.

**Comment by kayhayen** [comment]
Released as part of the current hotfix.
