### ISSUE TITLE
`anyio`'s `to_process.run_sync` breaks after compilation by nuitka

### ISSUE THREAD

**Issue by monchin** [Nuitka/Nuitka#3054]
Hello, I'm using `anyio` like this:
```python
# test.py
from anyio import to_process
import anyio

def cpu_bound_func():
    a = 0
    for i in range(1000000):
        a += i
    return a

async def task():
    res = await to_process.run_sync(cpu_bound_func)
    print(res) # 499999500000
    return res

def main():
    anyio.run(task)

if __name__ == '__main__':
    main()
```
When I directly `python test.py`, it prints what I want(499999500000). But after I `python -m nuitka test.py --standalone`, it can't run anymore. On my wsl2 ubuntu, it prints
```
Traceback (most recent call last):
  File "/mnt/c/Project/test/test/build/test.dist/test.py", line 19, in <module>
  File "/mnt/c/Project/test/test/build/test.dist/test.py", line 16, in main
  File "/mnt/c/Project/test/test/build/test.dist/anyio/_core/_eventloop.py", line 74, in run
  File "/mnt/c/Project/test/test/build/test.dist/anyio/_backends/_asyncio.py", line 2034, in run
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/runners.py", line 118, in run
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/base_events.py", line 687, in run_until_complete
  File "/mnt/c/Project/test/test/build/test.dist/anyio/_backends/_asyncio.py", line 2022, in wrapper
  File "/mnt/c/Project/test/test/build/test.dist/test.py", line 11, in task
  File "/mnt/c/Project/test/test/build/test.dist/anyio/to_process.py", line 142, in run_sync
  File "/mnt/c/Project/test/test/build/test.dist/anyio/_core/_subprocesses.py", line 131, in open_process
  File "/mnt/c/Project/test/test/build/test.dist/anyio/_backends/_asyncio.py", line 2270, in open_process
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/subprocess.py", line 224, in create_subprocess_exec
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/base_events.py", line 1744, in subprocess_exec
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/unix_events.py", line 211, in _make_subprocess_transport
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/base_subprocess.py", line 36, in __init__
  File "/mnt/c/Project/test/test/build/test.dist/asyncio/unix_events.py", line 820, in _start
  File "/mnt/c/Project/test/test/build/test.dist/subprocess.py", line 1026, in __init__
  File "/mnt/c/Project/test/test/build/test.dist/subprocess.py", line 1955, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Project/test/test/build/test.dist/python'
```
windows got simillar message `FileNotFoundError`.

I checked the code of [`anyio.to_process.run_sync`](https://github.com/agronholm/anyio/blob/master/src/anyio/to_process.py#L141), and found that it ues `sys.executable`, maybe that's the reason why it wants to find `python` but failed. 

I found in #2919 that `pywebview` also uses `sys.executable`, and it was added into `nuitka`, so I think maybe `anyio` should be added too? Thank you!

**Comment by kayhayen** [comment]
These run a risk of becoming fork bombs if not done carefully, which is why by default `sys.executable` tries to be rather a non-existent file and not your binary, that then fails to handle the re-execution, we will have to look into this one and make it work like joblib, multiprocessing, etc.

**Comment by kayhayen** [comment]
So, it would appear, it's not doing something too bad, it's calling with `-u -m anyio.to_process` which then gets its information from the stdin. So we just need to allow that to happen I guess.

**Comment by kayhayen** [comment]
So, it tries to load the Python code for `__main__` and to re-execute that in its `init` command, and that of course fails spectacularly and will need some work. I already used parts of the multiprocessing plugin to get `sys.executable` into the desired form, but I get the feeling, this will be a bit more work than I can do right now on this.

**Comment by MatthijsBurgh** [comment]
I am also experiencing an issue with `anyio`. It might be related.

Info:

```py
nuitka --version
2.6.9
Commercial: None
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
Flavor: Debian Python
Executable: ~/.cache/pypoetry/virtualenvs/poetry-nuitka-yptN7rxY-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.5
Version C compiler: /usr/lib/ccache/gcc (gcc 11).
```

Traceback:
```py
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1859, in post
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 115, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 228, in connect_tcp
    async with create_task_group() as tg:
RuntimeError: Task got bad yield: True
```

Let me know whether you agree it is related. Please let me know when you need more information
