### ISSUE TITLE
SCONS-linker crashes at linking stage with error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 184714: invalid continuation byte

### ISSUE THREAD

**Issue by Nixccc** [Nuitka/Nuitka#3071]
When compiling my program SCONS fails at the linking stage with the error:
```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 184714: invalid continuation byte
```
Full traceback is:
```python
Traceback (most recent call last):
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\__main__.py", line 206, in <module>
    main()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\MainControl.py", line 1155, in main
    _main()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\MainControl.py", line 1004, in _main
    result, scons_options = compileTree()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\MainControl.py", line 919, in compileTree
    result, scons_options = runSconsBackend()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\MainControl.py", line 767, in runSconsBackend
    runScons(
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\build\SconsInterface.py", line 403, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\build\SconsCaching.py", line 336, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\build\SconsCaching.py", line 282, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile, encoding="utf8"):
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\utils\FileOperations.py", line 793, in getFileContentByLine
    return getFileContents(filename, mode, encoding=encoding).splitlines()
  File "C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\lib\site-packages\nuitka\utils\FileOperations.py", line 811, in getFileContents
    return f.read()
  File "C:\Users\G4U5AAG\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 701, in read
    return self.reader.read(size)
  File "C:\Users\G4U5AAG\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 184714: invalid continuation byte
```

I've included the the nuitka-crash-report.xml
[nuitka-crash-report.zip](https://github.com/user-attachments/files/16622346/nuitka-crash-report.zip)

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

2.4.5
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] 
Flavor: CPython Official
Executable: C:\Users\G4U5AAG\Documents\prj\edd-compare\edd-compare\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3). (included MingGW64 used)

- How did you install Nuitka and Python

pip install nuitka in virtual environment

- The specific PyPI names and versions

altgraph==0.17.4
annotated-types==0.7.0
certifi==2024.7.4
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
contourpy==1.2.1
cryptography==42.0.8
cycler==0.12.1
Deprecated==1.2.14
eos_util @ file:///B:/###/######/######-0.1.7-py3-none-any.whl#sha256=1d2f6f96515951cca2815fa9b15a2da1181dfc6c1c4328ec65fb2#########
-e git+https://##############/scm/~####/###.git@####################egg=######
EPPy @ file:///B:/####/###########/####-1.0.6-py3-none-any.whl#sha256=51f629708b6d3c474481c4e6736e367d89f836c718a2e4d7155e5########
importlib_metadata==8.0.0
mypy-extensions==1.0.0
Nuitka==2.4.5
numpy==2.0.1
openpyxl==3.1.5
ordered-set==4.1.0
packaging==24.1
pandas==2.2.2
pdfrw==0.4
pefile==2023.2.7
PerfEmisCalc @ file:///B:/###/######/############-none-any.whl#sha256=fb6e7cb1e7307c36013dbe8458d91d15c3db12892e############
pikepdf==9.0.0
pillow==10.4.0
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
pyinstaller==6.9.0
pyinstaller-hooks-contrib==2024.7
PyJWT==2.8.0
pyodbc==5.1.0
pyparsing==3.1.2
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5_sip==12.15.0
pyqt_tools==0.1.37
pyQuark @ file:///B:/######/##########/######-0.2.9-py3-none-any.whl#sha256=56b43189d333a1633b8e2fb0711d2d1fbbabecf5944f0b08b###########
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
pywin32-ctypes==0.2.2
reportlab==4.2.2
requests==2.32.3
scipy==1.14.0
six==1.16.0
tomli==2.0.1
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
wrapt==1.16.0
zipp==3.19.2
zstandard==0.23.0

- Provide in your issue the Nuitka options used

python.exe -m nuitka src/main.py --mingw64 --windows-console-mode=force --lto=no --follow-imports --standalone --deployment --assume-yes-for-downloads --enable-plugin=pyqt5 --include-qt-plugins=sensible --output-filename="main" --windows-icon-from-ico=src/App.ico --include-data-files=C:\Users\########\Documents\prj\###\###\src\#######\local_range_data.json=#######\local_range_data.json --include-data-files=src\__version__.txt=__version__.txt --include-data-files=src\gui\*.ui=gui\ --include-data-files=src\App.ico=App.ico --include-data-files=src\libs\dPLib\*.ui=libs\dPLib\

- Note if this is a regression

This is a regression worked in Nuitka verison 2.4.1

**Comment by Nixccc** [comment]
This seems to be an issue with reading the CCACHE, but I'm not 100% sure, though I've noted that the linking stage takes a lot longer than it used to.

**Comment by kayhayen** [comment]
you might want to use the latest hotfix.

**Comment by Nixccc** [comment]
F.Y.I the pypi hasn't been updated
