### ISSUE TITLE
ImportError: cannot import name ChromeService from selenium.webdriver.chrome.service

### ISSUE THREAD

**Issue by mgeeky** [Nuitka/Nuitka#3080]
Hello there!

I'm struggling to compile **onefile** executable importing _Selenium_ Chrome driver.

Here're the compilation flags I'm using:

```
py -3.11 -m nuitka ^
	--msvc=latest ^
	--include-data-dir="C:\Path\To\Program\assets\data=assets\data" ^
	--follow-imports ^
	--include-package=selenium ^
	--include-package-data=selenium ^
	--include-package=selenium.webdriver.chrome ^
	--include-module=selenium.webdriver.chrome.service ^
	--debug ^
	--python-flag=-v ^
	--unstriped ^
	--show-modules ^
	--include-module=win32api ^
	--include-module=ctypes ^
	--noinclude-custom-mode=numpy:nofollow ^
	--noinclude-custom-mode=numpy.libs:nofollow ^
	--noinclude-custom-mode=matplotlib:nofollow ^
	--noinclude-custom-mode=cv2:nofollow ^
	--noinclude-custom-mode=PIL:nofollow ^
	--noinclude-custom-mode=scipy:nofollow ^
	--noinclude-custom-mode=PyQt2:nofollow ^
	--noinclude-custom-mode=PyQt3:nofollow ^
	--noinclude-custom-mode=PyQt4:nofollow ^
	--noinclude-custom-mode=PyQt5:nofollow ^
	--noinclude-custom-mode=PyQt6:nofollow ^
	--noinclude-custom-mode=PyQt7:nofollow ^
	--noinclude-custom-mode=PySide2:nofollow ^
	--noinclude-custom-mode=PySide3:nofollow ^
	--noinclude-custom-mode=PySide4:nofollow ^
	--noinclude-custom-mode=PySide5:nofollow ^
	--noinclude-custom-mode=PySide6:nofollow ^
	--noinclude-custom-mode=PySide7:nofollow ^
	--python-flag=no_site ^
	--python-flag=no_docstrings ^
	--windows-icon-from-ico="C:\Path\To\Program\assets\icons\pager.png" ^
	--windows-file-version="2.0" ^
	--windows-product-version="2.0" ^
	--no-deployment-flag=self-execution ^
	--onefile-tempdir-spec="{TEMP}/tmp{PID}_{TIME}" ^
	--enable-plugin=pylint-warnings ^
	--enable-plugin=data-hiding ^
	--enable-plugin=anti-debugger ^
	--warn-unusual-code ^
	--assume-yes-for-downloads ^
	--enable-plugin=upx ^
	--upx-binary="C:\Path\To\Program\release\upx.exe" ^
	--windows-console-mode=force -o "pager.exe" ^
	--onefile ^
	--output-dir="C:\Path\To\Program\release\_temp" "pager.py"
```

Nuitka version:

```
2.3.11
Commercial: 2.6.2
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```

Compiled in debug mode artifact throws this exception:

```
import selenium.webdriver.chrome.ChromeService # considering responsibility (find_spec)
import selenium.webdriver.chrome.ChromeService # denied responsibility
import selenium.webdriver.chrome.ChromeService # considering responsibility (find_spec)
import selenium.webdriver.chrome.ChromeService # denied responsibility
Traceback (most recent call last):
  File "C:\Users\Mariusz\AppData\Local\Temp\TMP276~1\pager.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Mariusz\AppData\Local\Temp\TMP276~1\lib\pager.py", line 43, in <module lib.pager>
ImportError: cannot import name 'ChromeService' from 'selenium.webdriver.chrome.service' (C:\Users\Mariusz\AppData\Local\Temp\TMP276~1\selenium\webdriver\chrome\service.py)
```

And this is the line that throws above exception:

```py
from selenium.webdriver.chrome.service import ChromeService
```

My `pager.dist` directory containing all the assets has `selenium` subdirectory with following contents:

```
C:\Path\To\Program\release\_Temp\pager.dist\selenium
\---webdriver
    +---common
    |   +---linux
    |   +---macos
    |   \---windows
    +---firefox
    \---remote
```

As we can see, there's no **chrome** directory inside of **webdrive**, which is worrisome.

Please let me know what else might be needed to further nail down this one!

Best regards,
Mariusz.

**Comment by mgeeky** [comment]
Turned out this was my error in my code as the latest selenium library versions don't export `ChromeService` object anymore.

I must have had some legacy imports that for some reason never crashed my programs and only nuitka compiled artifacts let me know about this compatibility debt I had.
