### ISSUE TITLE
Error using newest version of KivyMD==2.0.1.dev0

### ISSUE THREAD

**Issue by regybean** [Nuitka/Nuitka#3084]
### Environment information:
```
2.5rc5
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: d:\AutoscapeMobile\ASM\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Tried with both pip and conda venvs - same error 
Also used latest stable nuitka - same error
```
Package            Version    Location                                 Installer
------------------ ---------- ---------------------------------------- ---------
asyncgui           0.6.3      d:\AutoscapeMobile\ASM\Lib\site-packages pip      
asynckivy          0.6.4      d:\AutoscapeMobile\ASM\Lib\site-packages pip
certifi            2024.7.4   d:\AutoscapeMobile\ASM\Lib\site-packages pip
charset-normalizer 3.3.2      d:\AutoscapeMobile\ASM\Lib\site-packages pip
docutils           0.21.2     d:\AutoscapeMobile\ASM\Lib\site-packages pip
idna               3.7        d:\AutoscapeMobile\ASM\Lib\site-packages pip
Kivy               2.3.0      d:\AutoscapeMobile\ASM\Lib\site-packages pip
kivy-deps.angle    0.4.0      d:\AutoscapeMobile\ASM\Lib\site-packages pip
kivy-deps.glew     0.3.1      d:\AutoscapeMobile\ASM\Lib\site-packages pip
kivy-deps.sdl2     0.7.0      d:\AutoscapeMobile\ASM\Lib\site-packages pip
Kivy-Garden        0.1.5      d:\AutoscapeMobile\ASM\Lib\site-packages pip
kivymd             2.0.1.dev0 d:\AutoscapeMobile\ASM\Lib\site-packages pip
materialyoucolor   2.0.9      d:\AutoscapeMobile\ASM\Lib\site-packages pip
Nuitka             2.5rc5     d:\AutoscapeMobile\ASM\Lib\site-packages pip
ordered-set        4.1.0      d:\AutoscapeMobile\ASM\Lib\site-packages pip
pillow             10.4.0     d:\AutoscapeMobile\ASM\Lib\site-packages pip
pip                24.0       d:\AutoscapeMobile\ASM\Lib\site-packages pip
Pygments           2.18.0     d:\AutoscapeMobile\ASM\Lib\site-packages pip
pypiwin32          223        d:\AutoscapeMobile\ASM\Lib\site-packages pip
pywin32            306        d:\AutoscapeMobile\ASM\Lib\site-packages pip
requests           2.32.3     d:\AutoscapeMobile\ASM\Lib\site-packages pip
setuptools         65.5.0     d:\AutoscapeMobile\ASM\Lib\site-packages pip
urllib3            2.2.2      d:\AutoscapeMobile\ASM\Lib\site-packages pip
zstandard          0.23.0     d:\AutoscapeMobile\ASM\Lib\site-packages pip
```

### Minimum failing example 

```
#main.py
from kivymd.uix.label import MDLabel
```

`nuitka --standalone --follow-imports main.py`

### The Error
```
[INFO   ] [Logger      ] Record log in C:\Users\reggy\.kivy\logs\kivy_24-08-22_3.txt
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "D:\AutoScapeMobile\src\main.dist\kivy\__init__.py"
[INFO   ] [Python      ] v3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\AutoScapeMobile\src\main.dist\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 2.0.1.dev0, git-edf022a, 2024-08-22 (installed at "D:\AutoScapeMobile\src\main.dist\kivymd\__init__.py")
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 536.23'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: winctypes
[ERROR  ] 
Traceback (most recent call last):
  File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 553, in execute_directives
  File "<frozen importlib._bootstrap>", line 1283, in __import__
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.icon_definitions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 556, in execute_directives
  File "<frozen importlib._bootstrap>", line 1283, in __import__
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.icon_definitions'
 Traceback (most recent call last):
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 553, in execute_directives
   File "<frozen importlib._bootstrap>", line 1283, in __import__
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 556, in execute_directives
   File "<frozen importlib._bootstrap>", line 1283, in __import__
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'kivymd.icon_definitions'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "D:\AutoScapeMobile\src\main.dist\main.py", line 3, in <module>
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
   File "D:\AutoScapeMobile\src\main.dist\kivymd\uix\label\__init__.py", line 1, in <module kivymd.uix.label>
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
   File "D:\AutoScapeMobile\src\main.dist\kivymd\uix\label\label.py", line 598, in <module kivymd.uix.label.label>
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\builder.py", line 377, in load_string
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 483, in __init__
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 590, in parse
   File "D:\AutoScapeMobile\src\main.dist\kivy\lang\parser.py", line 565, in execute_directives
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 1:
 ...
 >>    1:#:import md_icons kivymd.icon_definitions.md_icons
       2:
       3:
 ...
 Unable to import package 'kivymd.icon_definitions.md_icons'
```
standard kivy apps such as https://kivy.org/doc/stable/examples/gen__canvas__canvas_stress__py.html work fine
I can provide more information if necessary.
Please let me know if anyone can reproduce this issue or if there are any obvious configuration errors or easy fixes !

**Comment by KRRT7** [comment]
please share your compilation report. i will try this on another machine now to see if i can repro.
