### ISSUE TITLE
pip module can't exe after build

### ISSUE THREAD

**Issue by wszgrcy** [Nuitka/Nuitka#3087]
version: `Nuitka: Starting Python compilation with Nuitka '2.4.7' on Python '3.12' commercial grade 'not installed'.`
code:
```python
from pip._internal.cli.main import main as pip_entry_point
pip_entry_point(['install','torch'])
```
command:
```
python -m nuitka --standalone --include-module=pip._internal,pip,pip._internal.cli,pip._internal.cli.main ./install-dep.py 
```
error:
```
Traceback (most recent call last):
  File "C:\code\MY-PRO~1\SHB-PY~1\INSTAL~1.DIS\install-dep.py", line 2, in <module>
  File "C:\code\MY-PRO~1\SHB-PY~1\INSTAL~1.DIS\pip\_internal\cli\main.py", line 78, in main
  File "C:\code\MY-PRO~1\SHB-PY~1\INSTAL~1.DIS\pip\_internal\commands\__init__.py", line 114, in create_command
  File "importlib.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pip._internal.commands.install'
```
I want to know if it is impossible to import and build 'pip' as a package?
Because I want to package the source code part and manually install the dependency part, which can speed up the transfer speed

**Comment by KRRT7** [comment]
this isn't supported Nuitka, you bundle all it's dependencies from the beginning.

**Comment by wszgrcy** [comment]
> this isn't supported Nuitka, you bundle all it's dependencies from the beginning.

thanks
