### ISSUE TITLE
unsloth, bitsandbytes fail with triton installed, giving OSError: could not get source code

### ISSUE THREAD

**Issue by deepakHonakeri05** [Nuitka/Nuitka#3107]
When importing unsloth executable is created, but when running it, It throws:
OSError: could not get source code
and exits.

Full log:

```
Traceback (most recent call last):
  File "D:\Project\ui.dist\program.py", line 2, in load_model
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\unsloth\__init__.py", line 97, in <module unsloth>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\bitsandbytes\__init__.py", line 16, in <module bitsandbytes>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\bitsandbytes\nn\__init__.py", line 17, in <module bitsandbytes.nn>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\bitsandbytes\nn\triton_based_modules.py", line 7, in <module bitsandbytes.nn.triton_based_modules>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\bitsandbytes\triton\int8_matmul_mixed_dequantize.py", line 9, in <module bitsandbytes.triton.int8_matmul_mixed_dequantize>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\__init__.py", line 8, in <module triton>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\runtime\__init__.py", line 1, in <module triton.runtime>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\runtime\autotuner.py", line 7, in <module triton.runtime.autotuner>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\testing.py", line 8, in <module triton.testing>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\language\__init__.py", line 6, in <module triton.language>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Project\ui.dist\triton\language\standard.py", line 11, in <module triton.language.standard>
  File "D:\Project\ui.dist\triton\runtime\jit.py", line 714, in jit
  File "D:\Project\ui.dist\triton\runtime\jit.py", line 705, in decorator
  File "D:\Project\ui.dist\triton\runtime\jit.py", line 584, in __init__
  File "D:\Project\ui.dist\inspect.py", line 1240, in getsourcelines
  File "D:\Project\ui.dist\inspect.py", line 1077, in findsource
OSError: could not get source code
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.4.7
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Deepak\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual
Nuitka-Scons:WARNING: Studio installer for adding it.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python

  I used pip install nuitka

- The specific PyPI names and versions
  xformers == 0.0.25.post1, unsloth==2024.8, trl== 0.8.6, triton== 2.1.0, transformers==4.43.4,
  torch==2.2.2+cu121, torchaudio==2.2.2+cu121, torchvision== 0.17.2+cu121, tokenizers==0.19.1,
  sentencepiece==0.2.0, safetensors==0.4.4, rich==13.7.1, deepspeed==0.13.1, bitsandbytes== 0.43.0.dev0,  decord == 0.6.0,
  accelerate== 0.33.0.

- Also supply a Short, Self Contained, Correct, Example

```

def load_model(path="unsloth/Meta-Llama-3.1-8B"):
    from unsloth import FastLanguageModel

    max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
    dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
    load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = path,
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
        device_map = 'auto'
        # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj",],
        lora_alpha = 16,
        lora_dropout = 0, # Supports any, but = 0 is optimized
        bias = "none",    # Supports any, but = "none" is optimized
        # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
        use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
        random_state = 3407,
        use_rslora = False,  # We support rank stabilized LoRA
        loftq_config = None, # And LoftQ
    )

    return model, tokenizer

model, tokenizer = load_model()

Just FYI, the source can be found here : https://colab.research.google.com/drive/1Ys44kVvmeZtnICzWz0xgpRnrIOjZAuxp?usp=sharing
```

- Provide in your issue the Nuitka options used

python -m nuitka --standalone --include-package='unsloth' --include-package='triton'  --module-parameter=torch-disable-jit=no --module-parameter=numba-disable-jit=no --follow-imports .\program.py

**Comment by kayhayen** [comment]
Another JIT to conquer, we will aim at 2.6 for this kind of operations to have plugin supports.

**Comment by zexi136** [comment]
Does this issue appear to be unfixed at https://github.com/Nuitka/Nuitka/milestone/35?
I'm testing whether copying the Triton source code to dist works.
dist_nuitka/server.dist/
├── server.bin (executable file)
└── triton/ (Official triton source code package directly copied from here)
├── __init__.py (Official included)
└── backends/
└── nvidia/
└── compiler.py (Official source code, kept as is)
