### ISSUE TITLE
FATAL: tk-inter: Plugin issue while working on 'module 'tkinterdnd2.TkinterDnD''

### ISSUE THREAD

**Issue by gookie-dev** [Nuitka/Nuitka#3108]
### Nuitka version 
(also tested with dev version (2.5rc6))
```
2.4.8
Commercial: None
Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Development\Python\nuitkaissue\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```

### Installation
- Nuitka via pip / Pycharm GUI into virtualenv 
- Python via windows installer

### PyPI names and versions
```
Package       Version Location                                                  Installer
------------- ------- --------------------------------------------------------- ---------
customtkinter 5.2.2   C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
darkdetect    0.8.0   C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
Nuitka        2.4.8   C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
ordered-set   4.1.0   C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
packaging     24.1    C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
pip           23.2.1  C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
tkinterdnd2   0.4.2   C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
zstandard     0.23.0  C:\Development\Python\nuitkaissue\.venv\Lib\site-packages pip
```

###  Example
```py
import customtkinter
from tkinterdnd2 import TkinterDnD, DND_ALL


class Tk(customtkinter.CTk, TkinterDnD.DnDWrapper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.TkdndVersion = TkinterDnD._require(self)


class App(Tk):
    def __init__(self):
        super().__init__()

        self.title("test")

        self.textbox = customtkinter.CTkTextbox(self, wrap="none")
        self.textbox.grid(row=0, column=0, padx=10, pady=(10, 5), sticky="nesw")
        self.textbox.drop_target_register(DND_ALL)
        self.textbox.dnd_bind("<<Drop>>", self.drop_event)

    def drop_event(self, event):
        print("dropped")


if __name__ == "__main__":
    app = App()
    app.mainloop()
```

### Command
```
python -m nuitka --deployment --onefile --enable-plugin=tk-inter --windows-console-mode=disable --assume-yes-for-downloads main.py
```

### Error
```
Traceback (most recent call last):
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\plugins\Plugins.py", line 69, in withPluginProblemReporting
    yield
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\plugins\Plugins.py", line 639, in considerExtraDlls
    for entry_point in _iterateExtraBinaries(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\plugins\Plugins.py", line 628, in _iterateExtraBinaries
    for val in value:
               ^^^^^
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\plugins\standard\TkinterPlugin.py", line 313, in getExtraDlls
    for filename, _dll_filename in listDllFilesFromDirectory(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 533, in listDllFilesFromDirectory
    for fullpath, filename in listDir(path):
                              ^^^^^^^^^^^^^
  File "C:\Development\Python\nuitkaissue\.venv\Lib\site-packages\nuitka\utils\FileOperations.py", line 384, in listDir
    for filename in os.listdir(real_path)
                    ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Development\\Python\\nuitkaissue\\.venv\\Lib\\site-packages\\tkinterdnd2\\tkdnd\\win64'
FATAL: tk-inter: Plugin issue while working on 'module 'tkinterdnd2.TkinterDnD''. Please report the bug with the above traceback included.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

**Comment by ccppi3** [comment]
I run into the same issue.
The problem is the path is wrong.
'C:\\Development\\Python\\nuitkaissue\\.venv\\Lib\\site-packages\\tkinterdnd2\\tkdnd\\win64'
should be:
'C:\\Development\\Python\\nuitkaissue\\.venv\\Lib\\site-packages\\tkinterdnd2\\tkdnd\\win-x64'

workaround:
just go to 'C:\\Development\\Python\\nuitkaissue\\.venv\\Lib\\site-packages\\tkinterdnd2\\tkdnd\\
copy folder win-x64 and name it win64.

**Comment by kayhayen** [comment]
I made the PR work across versions of tkinterdnd2 and added the new platforms that they added, e.g. 32 bits and ARM Windows, and ARM Linux and macOS ARM, and going to merge this for the hotfix that is coming soon.
