### ISSUE TITLE
nuitka build of "wxhello.py" file fails when using msys2 "C:\msys64" on Windows 10

### ISSUE THREAD

**Issue by noeldiviney** [Nuitka/Nuitka#3112]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.1.6
Commercial: None
Python: 3.11.9 (main, Apr 12 2024, 09:55:27)  [GCC UCRT 13.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/msys64/ucrt64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/msys64/ucrt64/bin/gcc.exe' is being ignored, Nuitka is
Nuitka-Scons: very dependent on the precise one.
Version C compiler: ~/AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-ms
vcrt-r1/mingw64/bin/gcc.exe (gcc 13.2.0).

- How did you install Nuitka and Python
 Install MSYS2 from "https://www.msys2.org download installer msys2-x86-_64-20240727.exe
 install to "c:\msys64"
 "C:\msys64\ucrt64.exe" is run by clicking the f"inish" button
 Input the command "pacman -Suy --noconfirm"  and press enter.

 Restart "C:\msys64\ucrt64.exe' and run the following commands :-
 pacman -S --noconfirm mingw-w64-ucrt-x86_64-toolchain
 pacman -S --noconfirm mingw-w64-ucrt-x86_64-python-nuitka
 pacman -S --noconfirm mingw-w64-ucrt-x86_64-python-pip
 pacman -S --noconfirm mingw-w64-ucrt-x86_64-gcc
 pacman -S --noconfirm mingw-w64-ucrt-x86_64-wxPython
 
 Install the "nuitkamsys2" test program "wxhello.py" to "C:\nuitkamsys2" folder

 Create "wxhello.py " to have the following contents
# First things, first. Import the wxPython package.
import wx
# Next, create an application object.
app = wx.App()
# Then a frame.
frm = wx.Frame(None, title="Hello World")
# Show it.
frm.Show()
# Start the event loop.
app.MainLoop()

In  "C:\msys64\ucrt64.ese" terminal execute the following commands
 "cd /c/nuitkamsys2"
 "nuitka3 --standalone --follow-imports wxhello.py --python-flag=-O"
 "./wxhello.dist/wxhello.exe"

Executing "./wxhello.dist/wxhello.exe" produces the following output
$ ./wxhello.dist/wxhello.exe
Traceback (most recent call last):
  File "C:\NUITKA~1\WXHELL~1.DIS\wxhello.py", line 2, in <module>
  File "C:\NUITKA~1\WXHELL~1.DIS\wx/__init__.py", line 17, in <module wx>
  File "C:\NUITKA~1\WXHELL~1.DIS\wx/core.py", line 12, in <module wx.core>
ImportError: LoadLibraryExW 'C:\NUITKA~1\WXHELL~1.DIS\wx\_core.pyd' failed: The specified module could not be found.

Executing "ls -al C:/NUITKA~1/WXHELL~1.DIS/wx" produces the hollowing output (note the use of "/" instesd of "\"
$ ls -al C:/NUITKA~1/WXHELL~1.DIS/wx
total 13784
drwxr-xr-x 1 esdev None        0 Sep  9 21:10 .
drwxr-xr-x 1 esdev None        0 Sep  9 21:10 ..
-rwxr-xr-x 1 esdev None  1787236 Sep  9 21:10 _adv.pyd
-rwxr-xr-x 1 esdev None 11177940 Sep  9 21:10 _core.pyd
-rwxr-xr-x 1 esdev None   936204 Sep  9 21:10 _html.pyd
-rwxr-xr-x 1 esdev None   193232 Sep  9 21:10 siplib.pyd

Hoping the above helps.
Noel Diviney

**Comment by noeldiviney** [comment]
I have updated nuitka and it is now version 2.4.8
$ python -m nuitka --version
2.4.8
Commercial: None
Python: 3.11.10 (main, Sep 10 2024, 13:02:13)  [GCC 14.2.0 64 bit (AMD64)]
Flavor: MSYS2 MinGW
Executable: C:/nuitka248/msys64/mingw64/bin/python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/nuitka248/msys64/mingw64/bin/gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Version C compiler: ~/AppData/Local/Nuitka/Nuitka/Cache/DOWNLO~1/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/gcc.exe (gcc 13.2.0).
------------------------------------------------------------------------------------------------------------------------

The wxhello.py is built as follows ;-

esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup
$ nuitka --standalone wxhello.py --python-flag=-O
Nuitka-Options: Used command line options: --standalone wxhello.py --python-flag=-O
Nuitka: Starting Python compilation with Nuitka '2.4.8' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/nuitka248/msys64/mingw64/bin/gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 15 files (no progress information available for this stage).
Nuitka-Scons: Compiled 15 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 15
Nuitka: Keeping build directory 'wxhello.build'.
Nuitka: Successfully created 'wxhello.dist/wxhello.exe'.

esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup
$ ls -al
total 61
drwxr-xr-x 1 esdev None     0 Sep 27 12:14 .
drwxr-xr-x 1 esdev None     0 Sep 27 11:52 ..
-rwxr-xr-x 1 esdev None 15909 Sep 27 11:33 msys64setup.sh
drwxr-xr-x 1 esdev None     0 Sep 27 12:18 wxhello.build
drwxr-xr-x 1 esdev None     0 Sep 27 12:18 wxhello.dist
-rw-r--r-- 1 esdev None   573 Sep 26 11:53 wxhello.py

esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup
Executing wxhello.exe when run fails as follows :-
$ ./wxhello.dist/wxhello.exe
Traceback (most recent call last):
  File "C:\NUITKA~3\MSYS64~1\WXHELL~1.DIS\wxhello.py", line 7, in <module>
  File "C:\NUITKA~3\MSYS64~1\WXHELL~1.DIS\wx/__init__.py", line 17, in <module wx>
  File "C:\NUITKA~3\MSYS64~1\WXHELL~1.DIS\wx/core.py", line 12, in <module wx.core>
ImportError: LoadLibraryExW 'C:\NUITKA~3\MSYS64~1\WXHELL~1.DIS\wx\_core.pyd' failed: The specified module could not be found.

esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup

The error is the same as with nuitka version 2.1.2
esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup
$ ls -al wxhello.dist\\wx
total 13772
drwxr-xr-x 1 esdev None        0 Sep 27 12:18 .
drwxr-xr-x 1 esdev None        0 Sep 27 12:18 ..
-rwxr-xr-x 1 esdev None  1783575 Sep 27 12:18 _adv.pyd
-rwxr-xr-x 1 esdev None 11176098 Sep 27 12:18 _core.pyd
-rwxr-xr-x 1 esdev None   933567 Sep 27 12:18 _html.pyd
-rwxr-xr-x 1 esdev None   190787 Sep 27 12:18 siplib.pyd

esdev@DESKTOP-9O7V7JD MINGW64 /c/nuitka248/msys64setup
If I use two backward slashes instead of one I can access the wx folder correctly.
Using one forward slash as the folder separator also works correctly.

Hope this helps

**Comment by noeldiviney** [comment]
To make it easier to demonstrate this issue I have created a Bash script to perform the following steps.
         1.    Installs a msys64 embedded development environment on Windows 10.
         2.    Builds and installs nuitka version 2.4.8, which is the latest version.
         3 .   Creates wxhello.py which is a python program to test nuitka's wxhello.exe build.
         4.    Builds wxhello.exe using "nuitka --standalone wxhello.py --python-flag=-O" command line.
         4.    Executes wxhello.exe and  gets the following error :-
                     ImportError: LoadLibraryExW 'C:\NUITKA~3\PYTHON~1\WXHELL~1.DIS\wx\_core.pyd' 
                     failed: The specified module could not be found.
         5.   Demonstrates that using two "backward slashes" in the path ie'C:\\NUITKA~3\\PYTHON~1\\WXHELL~1.DIS\\wx'
                     displays the wx contents to have "_core.pyd" which is the desired module.
                    'C:/NUITKA~3/PYTHON~1/WXHELL~1.DIS/wx' will also work correctly.
         6.   Uses the command "ls -al  C:\\NUITKA~3\\PYTHON~1\\WXHELL~1.DIS\\wx to display the contents as
               drwxr-xr-x 1 esdev None        0 Sep 29 10:59 .
               drwxr-xr-x 1 esdev None        0 Sep 29 10:59 ..
                -rwxr-xr-x 1 esdev None  1787236 Sep 29 10:59 _adv.pyd
                -rwxr-xr-x 1 esdev None 11177940 Sep 29 10:59 _core.pyd
                -rwxr-xr-x 1 esdev None   936204 Sep 29 10:59 _html.pyd
                -rwxr-xr-x 1 esdev None   193232 Sep 29 10:59 siplib.pyd

The steps to run the Bash script are as follows
         1.   Install the following Bash script zip file of msys64setup.sh
                   [msys64setup.zip](https://github.com/user-attachments/files/17178260/msys64setup.zip)
                   'msys64setup.sh' to 'c::\nuitka248\msys64setup\msys64setup.sh'
         2.   install msys64 from 'https://www.msys2.org'
                   Download Installer 'msys2-x86_64-20270727.exe'
                   Install to 'C:\nuitka248\msys64' and follow GUI instructions to complete installation.
          3.  Click "Finish" button to run the 'C:\nuitka248\msys64\ucrt64.exe' terminal
          4.   Enter the following bash commands to execute the script :- 
                    $ 'cd /c/nuitka248/msys64setup' 
                    $ ./msys64setup.sh

I have attached my install output log (see the following 'msys64-install-log-2.zip.)
          [msys64setup-install-log-2.zip](https://github.com/user-attachments/files/17178307/msys64setup-install-log-2.zip)

Hope this helps.
Noel Diviney

**Comment by kayhayen** [comment]
I am giving it a quick shot on Linux first, but I do have msys2, and will be upgrading it, but haven't done this in a while. The fact that wxPython depends on installed GTK makes it very ugly. I suspect, this is about something, where system packages are excluded by default, but for GTK that must not be done.

**Comment by kayhayen** [comment]
I noticed that `--version` was broken since wintypes.ntdll doesn't work in POSIX mode, I added an alternative implementation for it, such that ucrt flavor of MSYS2 no longer crashes.

**Comment by kayhayen** [comment]
Ok, switching to MinGW64 Python, I am going to first add to reporting, what DLLs used by what other DLL were removed due to the trimming, to see if anything that extension module uses is subject to that.

**Comment by kayhayen** [comment]
There, we go, the report reveals that indeed "system DLLs" are discarded for the extension module causing the issue here.

```
  <excluded_dll name="${sys.prefix}/bin/libgcc_s_seh-1.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/libwinpthread-1.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/libpython3.11.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/libstdc++-6.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/wxbase32u_gcc_custom.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/liblzma-5.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
  <excluded_dll name="${sys.prefix}/bin/zlib1.dll" used_by="wx/_core.pyd" reason="no outside dependencies allowed for wx._core" />
```

**Comment by kayhayen** [comment]
So, for the flavor we have there, this should be done:

```
    if isMSYS2MingwPython():
        inside_paths.insert(0, os.path.join(getSystemPrefixPath(), "bin"))
```

With that it works for me.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by noeldiviney** [comment]
Hello Kay.
Delighted to hear from you.
I have cloned the factory branch development version and used it to build my wxhello.py successfully.
I then executed command ./wxhello.dist/wxhello.exe and IT WORKS displaying wxPython GUI Window.

Thank you for the fix and the "excellent report" tag.
I can now get back to my wxPython Project which is designed to install a "Embed"ded Systems Development Environment".
I will be using Nuitka for this and our Company will be using "Nuitka Commercial " when we have set it up.
So looking forward to working with you.

I am devloping a new Bash Script to install Msys64, install Nuitka and test that all is working.
I will send you a copy of the Script tomorrow.
I am now going to celebrate now with some "Guinness"

Best regards Noel
screen shot
[NuitkaSuccess.zip](https://github.com/user-attachments/files/17201881/NuitkaSuccess.zip)
build log
[NuitkaBuild1.zip](https://github.com/user-attachments/files/17201851/NuitkaBuild1.zip)
