### ISSUE TITLE
ModuleNotFoundError: No module named 'pyexpat'

### ISSUE THREAD

**Issue by aylitat** [Nuitka/Nuitka#3114]
`Traceback (most recent call last):
  File "F:\project\vv_cloud\out\get_vv_ck.dist\xml\etree\ElementTree.py", line 1522, in __init__
    from xml.parsers import expat
  File "F:\project\vv_cloud\out\get_vv_ck.dist\xml\parsers\expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\project\vv_cloud\out\get_vv_ck.dist\xml\etree\ElementTree.py", line 1525, in __init__
    import pyexpat as expat
ModuleNotFoundError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\project\vv_cloud\out\get_vv_ck.dist\get_vv_ck.py", line 26, in <module>
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DrissionPage\__init__.py", line 8, in <module>
    from ._pages.chromium_page import ChromiumPage
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DrissionPage\_pages\chromium_page.py", line 14, in <module>
    from .._base.browser import Browser
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DrissionPage\_base\browser.py", line 16, in <module>
    from .._units.downloader import DownloadManager
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DrissionPage\_units\downloader.py", line 13, in <module>
    from DataRecorder.tools import get_usable_path
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DataRecorder\__init__.py", line 1, in <module>
    from .byte_recorder import ByteRecorder
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DataRecorder\byte_recorder.py", line 5, in <module>
    from .base import OriginalRecorder
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DataRecorder\base.py", line 7, in <module>
    from .setter import OriginalSetter, BaseSetter
  File "F:\project\vv_cloud\out\get_vv_ck.dist\DataRecorder\setter.py", line 4, in <module>
    from openpyxl.reader.excel import load_workbook
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\__init__.py", line 7, in <module>
    from openpyxl.workbook import Workbook
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\workbook\__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\workbook\workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\worksheet\worksheet.py", line 24, in <module>
    from openpyxl.cell import Cell, MergedCell
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\cell\__init__.py", line 3, in <module>
    from .cell import Cell, WriteOnlyCell, MergedCell
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\cell\cell.py", line 27, in <module>
    from openpyxl.styles.styleable import StyleableObject
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\styles\styleable.py", line 13, in <module>
    from .builtins import styles
  File "F:\project\vv_cloud\out\get_vv_ck.dist\openpyxl\styles\builtins.py", line 1346, in <module>
    ('Normal', NamedStyle.from_tree(fromstring(normal))),
  File "F:\project\vv_cloud\out\get_vv_ck.dist\xml\etree\ElementTree.py", line 1341, in XML
    parser = XMLParser(target=TreeBuilder())
  File "F:\project\vv_cloud\out\get_vv_ck.dist\xml\etree\ElementTree.py", line 1527, in __init__
    raise ImportError(
ImportError: No module named expat; use SimpleXMLTreeBuilder instead`

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
