### ISSUE TITLE
cannot locate symbol "_Py_FalseStruct" referenced

### ISSUE THREAD

**Issue by Jzhenli** [Nuitka/Nuitka#3119]
Hi, I use nuitka to bulid a py file to .so file on termux,  then copy the so file to windows10, and package it with [briefcase](https://github.com/beeware/briefcase) to android apk, but when run the apk on the android device, it will raise error: cannot locate symbol "_Py_FalseStruct" referenced. I'm not sure if this is a bug, detail output as below:

E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.example.testtoga, PID: 8437
E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testtoga/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ImportError: dlopen failed: cannot locate symbol "_Py_FalseStruct" referenced by "/data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so"...
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3751)
E/AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3919)
E/AndroidRuntime:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
E/AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime:   at android.os.Looper.loopOnce(Looper.java:238)
E/AndroidRuntime:   at android.os.Looper.loop(Looper.java:357)
E/AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:8089)
E/AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime: Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: cannot locate symbol "_Py_FalseStruct" referenced by "/data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so"...
E/AndroidRuntime:   at <python>.java.android.importer.extension_create_module_override(importer.py:734)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:20)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:60)
E/AndroidRuntime:   at <python>.__main__.<module>(__main__.py:1)
E/AndroidRuntime:   at <python>.runpy._run_code(runpy.py:86)
E/AndroidRuntime:   at <python>.runpy._run_module_code(runpy.py:96)
E/AndroidRuntime:   at <python>.runpy.run_module(runpy.py:224)
E/AndroidRuntime:   at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
E/AndroidRuntime:   at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
E/AndroidRuntime:   at org.beeware.android.MainActivity.onCreate(MainActivity.java:85)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8232)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8212)
E/AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3724)
E/AndroidRuntime:   ... 12 more

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by kayhayen** [comment]
Without a good reproducer, this report means nothing.
