### ISSUE TITLE
keyring module missing win32ctypes and its submodules on Windows

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka#3133]
When building a standalone on Windows that uses the latest `keyring` package, there are problems due to missing modules.

```
Traceback (most recent call last):
  File "C:\Users\jim\AppData\Local\Temp\ONEFIL~2\login.py", line 7, in <module>
    from win32ctypes.pywin32 import pywintypes, win32cred

  File "C:\Users\jim\AppData\Local\Temp\ONEFIL~2\win32ctypes\pywin32\__init__.py", line 9, in <module win32ctypes.pywin32>
  File "C:\Users\jim\AppData\Local\Temp\ONEFIL~2\win32ctypes\pywin32\win32api.py", line 9, in <module win32ctypes.pywin32.win32api>
  File "C:\Users\jim\AppData\Local\Temp\ONEFIL~2\win32ctypes\core\__init__.py", line 30, in create_module
  File "importlib.py", line 90, in import_module
ModuleNotFoundError: No module named 'win32ctypes.core.ctypes._common'
```

Adding the following to `nuitka\plugins\standard\standard.nuitka-package.config.yml` seems to fix the issue:

``` yaml
- module-name: 'keyring.backends.Windows' # checksum: 2531fce0
  implicit-imports:
    - depends:
        - 'win32timezone'
        - 'win32ctypes.core.ctypes.*'  # <- this fixes the issue
```

**Comment by jimkring** [comment]
Created a PR here: https://github.com/Nuitka/Nuitka/pull/3134

**Comment by jimkring** [comment]
FYI, a work-around to this issue is to add the `--include-module=win32ctypes.core.ctypes._common` option when running `nuitka`. It doesn't work to try to put it into a project-level `nuitka_package_configuration.yml` due to errors stating that there is already an entry in the default nuitka package configuration for the `keyring` package -- ideally, nuitka would merge the implicit dependencies of the default package configuration and the project-level package configuration.

**Comment by kayhayen** [comment]
Reminds me of the merge PR, sorry for being very delaying here, but I will get to these, doing the 2.4.9 release process right now
