### ISSUE TITLE
Problem with separating module from standalone executable

### ISSUE THREAD

**Issue by ShapingView** [Nuitka/Nuitka#3136]
Hello,

I am trying to isolate building a dependency of the shapely package (in order to ensure, that LGPL requirements are fulfilled).

I am coming from this suggestion here: https://github.com/Nuitka/Nuitka/issues/1191#issuecomment-903298943

<details><summary>Nuitka Version</summary>

```
python -m nuitka --version
2.4.8
Commercial: None
Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\USR~1\Desktop\repos\venv-312-test\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding
Nuitka-Scons:WARNING: it.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

</details>

<details><summary>Pip freeze</summary>

```
pip freeze
Nuitka==2.4.8
numpy==2.1.1
ordered-set==4.1.0
shapely==2.0.4
zstandard==0.23.0
```
</details>

<details><summary>File `hw.py` to isolate the issue</summary>

```python
from shapely import Point

def main():
    print("Hello nuitka!")
    circle = Point([0, 0]).buffer(distance=1)
    print(circle.area)

if __name__ == "__main__":
    main()
```
</details>

Building it like this works fine: `python.exe -m nuitka --standalone hw.py`

My approach to isolate the shapely dependency does not:

```powershell
# build the shapely module independently
python.exe -m nuitka --output-dir=isolated_modules --module '<path-to-my-python-venv>\Lib\site-packages\shapely'
# build the standalone executable without including shapely
python.exe -m nuitka --standalone --nofollow-import-to=shapely hw.py
# copy the isolated shapely build into the standalone folder
cp isolated_modules\*.pyd hw.dist\
```

Running it:

```
.\hw.dist\hw.exe
Traceback (most recent call last):
  File "C:\Users\USR~1\Desktop\repos\test\HWBF46~1.DIS\hw.py", line 1, in <module>
  File "C:\Users\USR~1\Desktop\repos\test\hw.dist\shapely\__init__.py", line 13, in <module shapely>
ModuleNotFoundError: No module named 'shapely.lib'
```

Probably, it is a mistake on my side how to set this up properly. I am not sure how to continue, though. Any help is appreciated!

Thank you!

**Comment by kayhayen** [comment]
The --module mode doesn't include submodules automatically, you have to tell it yourself to do that. Checkout https://nuitka.net/user-documentation/use-cases.html#use-case-3-package-compilation

This is unintuitive admitted, and a trap to fall into. Doing that your chances will be highly increased.

**Comment by kayhayen** [comment]
> Nuitka-Options:WARNING: You did not specify to follow or include anything
> Nuitka-Options:WARNING: but main module. Check options and make sure that
> Nuitka-Options:WARNING: is intended.

You should have gotten and ignored this warning, so I believe this is a severe user error? Convince me otherwise, but for now I think of this as solved.

**Comment by ShapingView** [comment]
I actually considered that before, but since it didn't affect the outcome, I dropped it in favor of simplicity (the issue guidelines tell to "avoid unnecessary options").

So with these steps, I came to the same result (note, that the first command includes `--include-package=shapely`, such that the warning does not occur anymore.)

```
python.exe -m nuitka --output-dir=isolated_modules --module '<path-to-my-python-venv>\Lib\site-packages\shapely' --include-package=shapely
python.exe -m nuitka --standalone --nofollow-import-to=shapely hw.py
cp isolated_modules\*.pyd hw.dist\
```

_Sidenote:_ I also don't have visual studio code installed and thus use gcc to compile it. (Again, for simplicity I skipped the `--mingw64` part, but this generates a warning below)

<details><summary> Log output during build </details>

```
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> python.exe -m nuitka --output-dir=isolated_modules --module 'C:\Users\USR~1\Desktop\repos\venv-312-test\Lib\site-packages\shapely' --include-package=shapely
Nuitka-Options: Used command line options: --output-dir=isolated_modules --module "C:\Users\USR~1\Desktop\repos\venv-312-test\Lib\site-packages\shapely" --include-package=shapely
Nuitka: Starting Python compilation with Nuitka '2.4.8' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                                
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                           
Nuitka: Running C compilation via Scons.
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding it.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 127 files (no progress information available for this stage).
Nuitka-Scons: Compiled 127 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 127
Nuitka: Keeping build directory 'isolated_modules\shapely.build'.
Nuitka: Successfully created 'isolated_modules\shapely.cp312-win_amd64.pyd'.
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> python.exe -m nuitka --output-dir=isolated_modules --module 'C:\Users\USR~1\Desktop\repos\venv-312-test\Lib\site-packages\shapely' --include-package=shapely^C
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> python.exe -m nuitka --output-dir=isolated_modules --module 'C:\Users\USR~1\Desktop\repos\venv-312-test\Lib\site-packages\shapely' --include-package=shapely^C
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> -include-package=^C
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> python.exe -m nuitka --standalone --nofollow-import-to=shapely hw.py
Nuitka-Options: Used command line options: --standalone --nofollow-import-to=shapely hw.py
Nuitka: Starting Python compilation with Nuitka '2.4.8' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding it.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'hw.build'.
Nuitka: Successfully created 'hw.dist\hw.exe'.
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> cp isolated_modules\*.pyd hw.dist\
(venv-312-test) PS C:\Users\USR~1\Desktop\repos\test> .\hw.dist\hw.exe
Traceback (most recent call last):
  File "C:\Users\USR~1\Desktop\repos\test\HWBF46~1.DIS\hw.py", line 1, in <module>
  File "C:\Users\USR~1\Desktop\repos\test\hw.dist\shapely\__init__.py", line 13, in <module shapely>
ModuleNotFoundError: No module named 'shapely.lib'
```

**Comment by kayhayen** [comment]
Manual copying into the dist folder is unsupported, but you could manipulate your Python installation such, that the extension module you created would be found and used by Nuitka, right now it is not.

**Comment by ShapingView** [comment]
I haven't figured out a way for nuitka to build the (extension) module in a way while also including it, as you suggested. I would appreciate any guidance.

With the following  approach I got it working for this example. This sadly still relies on manual copying into the dist-folder, so I fear this still relies on implementation details which you said to be "not supported". 

```powershell
python.exe -m nuitka --standalone --nofollow-import-to=shapely hw.py
cp <path-to-my-python-venv>\Lib\site-packages\shapely hw.dist\ -Recurse
cp <path-to-my-python-venv>\Lib\site-packages\shapely.libs hw.dist\ -Recurse
```

**Comment by kayhayen** [comment]
Try other support forums then, I cannot help each user that doesn't read or understand the manuals, unless they make it clear why it wouldn't help them.
