### ISSUE TITLE
Running `python -m nuitka --version` yields `ImportError: Module use of python310.dll conflicts with this version of Python.`

### ISSUE THREAD

**Issue by ItsCubeTime** [Nuitka/Nuitka#3142]
Installation and error (my Python installation is a portable install from python.org):
```
PS C:\Users\olliv\Desktop\Fast Python Library Test Files\pulse\bin\Pulse by PlaySoft> python -m pip install nuitka
Collecting nuitka
  Using cached Nuitka-2.4.8-cp312-cp312-win_amd64.whl
Collecting ordered-set>=4.1.0 (from nuitka)
  Using cached ordered_set-4.1.0-py3-none-any.whl.metadata (5.3 kB)
Collecting zstandard>=0.15 (from nuitka)
  Using cached zstandard-0.23.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Using cached zstandard-0.23.0-cp312-cp312-win_amd64.whl (495 kB)
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-2.4.8 ordered-set-4.1.0 zstandard-0.23.0
PS C:\Users\olliv\Desktop\Fast Python Library Test Files\pulse\bin\Pulse by PlaySoft> python -m nuitka --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\__main__.py", line 206, in <module>
    main()
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\__main__.py", line 131, in main
    reExecuteNuitka(pgo_filename=None)
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\utils\ReExecute.py", line 96, in reExecuteNuitka
    from nuitka.importing.PreloadedPackages import (
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\importing\PreloadedPackages.py", line 14, in <module>
    from nuitka.Tracing import recursion_logger
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\Tracing.py", line 23, in <module>
    from nuitka.__past__ import BrokenPipeError  # pylint: disable=redefined-builtin
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\site-packages\nuitka\__past__.py", line 64, in <module>
    from urllib.request import urlretrieve
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Users\olliv\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 52, in <module>
    import _socket
ImportError: Module use of python310.dll conflicts with this version of Python.
```

Systeminfo:
```
PS C:\Users\olliv\Desktop\Fast Python Library Test Files\pulse\bin\Pulse by PlaySoft> python --version
Python 3.12.2
PS C:\Users\olliv\Desktop\Fast Python Library Test Files\pulse\bin\Pulse by PlaySoft> systeminfo

Host Name:                 ENTERPRISE
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          olliver.aira@gmail.com
Registered Organization:
Product ID:                00330-80000-42875-AA670
Original Install Date:     5/12/2024, 3:58:03 PM
System Boot Time:          9/30/2024, 10:49:39 PM
System Manufacturer:       ASUS
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 151 Stepping 2 GenuineIntel ~3187 Mhz
BIOS Version:              American Megatrends Inc. 0407, 9/13/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              sv;Swedish
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32,509 MB
Available Physical Memory: 12,862 MB
Virtual Memory: Max Size:  65,019 MB
Virtual Memory: Available: 34,913 MB
Virtual Memory: In Use:    30,106 MB
Page File Location(s):     F:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\ENTERPRISE
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5027397
                           [03]: KB5041585
                           [04]: KB5041584
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Hardware not present
                           [02]: Realtek Gaming 2.5GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.1.100
                                 [02]: fe80::aa16:9645:9fb1:7122
                                 [03]: 2001:2042:9a18:a00:68a5:d853:2c8e:abbf
                                 [04]: 2001:2042:9a18:a00:569a:b8fb:81:6b4e
                                 [05]: 2001:2042:9a18:a00:10e2:5112:7545:db8b
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by kayhayen** [comment]
Your Python setup is broken, if it finds the wrong Python DLL, not a Nuitka bug in any way. If by portable you mean embeddable or so, that one is unsupported by Nuitka anyway.
