### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by mosol1** [Nuitka/Nuitka#3147]
[2024-10-13 07:34:10] [INFO    ] discord.client: logging in using static token
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 15306, in <module>
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 952, in __init__
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\EliteOptimizer.py", line 1436, in home
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 869, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\runners.py", line 194, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\runners.py", line 118, in run
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\base_events.py", line 687, in run_until_complete
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 858, in runner
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 786, in start
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\client.py", line 620, in login
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\http.py", line 816, in static_login
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\discord\http.py", line 638, in request
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\client.py", line 1355, in __aenter__
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\client.py", line 659, in _request
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 557, in connect
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1002, in _create_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1305, in _create_direct_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohttp\connector.py", line 1061, in _wrap_create_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\impl.py", line 88, in start_connection
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\_staggered.py", line 91, in staggered_race
  |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\asyncio\taskgroups.py", line 145, in __aexit__
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Solar\AppData\Local\Temp\onefile_8088_133733036194204284\aiohappyeyeballs\_staggered.py", line 88, in run_one_coro
    | aiohappyeyeballs._staggered._Done
    +------------------------------------

**Comment by kayhayen** [comment]
In the template, we have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that we do not want to be left guessing. For you it's easy to erase the issue template and expect us to ask you questions only as necessary, but we cannot do that. We would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore we are  likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."
