### ISSUE TITLE
Install playwright in exe-file with Nuitka

### ISSUE THREAD

**Issue by BotovodWF** [Nuitka/Nuitka#3170]
Hello, can you please help me to package Chromium from Playwright into a single executable exe file, looked at previous requests, but couldn't solve the problem with them. Hoping for specific help rather than forwarding to other threads.
Code:
```
from playwright.sync_api import sync_playwright
import os

def main():
    with sync_playwright() as p:
        browser_path = os.path.join(os.path.dirname(__file__), 'chrome-win', 'chrome.exe')
        browser = p.chromium.launch(executable_path=browser_path, headless=False)
        page = browser.new_page()
        page.goto(“https://www.google.com”)
        title = page.title()
        print(f “Page title: {title}”)
        browser.close()

if __name__ == “__main__”:
    main()
    input(2)
```
Nuitka:
`nuitka --standalone --onefile --include-data-dir=chrome-win=chrome-win --output-dir=output_folder tests_playwright.py`

Versions:
```
2.4.11
Commercial: None
Python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).

Python 3.9.9
```

My error:
```
Traceback (most recent call last):
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 21, in <module>
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 4, in main
  File "C:\Temp\ONEFIL~1\playwright\sync_api\_context_manager.py", line 77, in __enter__
  File "C:\Temp\ONEFIL~1\playwright\sync_api\_context_manager.py", line 56, in greenlet_main
  File "C:\Temp\ONEFIL~1\asyncio\base_events.py", line 642, in run_until_complete
  File "C:\Temp\ONEFIL~1\playwright\_impl\_connection.py", line 267, in run_as_sync
  File "C:\Temp\ONEFIL~1\playwright\_impl\_connection.py", line 276, in run
  File "C:\Temp\ONEFIL~1\playwright\_impl\_transport.py", line 120, in connect
  File "C:\Temp\ONEFIL~1\asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "C:\Temp\ONEFIL~1\asyncio\base_events.py", line 1661, in subprocess_exec
  File "C:\Temp\ONEFIL~1\asyncio\windows_events.py", line 389, in _make_subprocess_transport
  File "C:\Temp\ONEFIL~1\asyncio\base_subprocess.py", line 36, in __init__
  File "C:\Temp\ONEFIL~1\asyncio\windows_events.py", line 885, in _start
  File "C:\Temp\ONEFIL~1\asyncio\windows_utils.py", line 153, in __init__
  File "C:\Temp\ONEFIL~1\subprocess.py", line 951, in __init__
  File "C:\Temp\ONEFIL~1\subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)>
Traceback (most recent call last):
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 21, in <module>
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 4, in main
  File "C:\Temp\ONEFIL~1\playwright\sync_api\_context_manager.py", line 77, in __enter__
  File "C:\Temp\ONEFIL~1\playwright\sync_api\_context_manager.py", line 56, in greenlet_main
  File "C:\Temp\ONEFIL~1\asyncio\base_events.py", line 642, in run_until_complete
  File "C:\Temp\ONEFIL~1\playwright\_impl\_connection.py", line 267, in run_as_sync
  File "C:\Temp\ONEFIL~1\playwright\_impl\_connection.py", line 276, in run
  File "C:\Temp\ONEFIL~1\playwright\_impl\_transport.py", line 120, in connect
  File "C:\Temp\ONEFIL~1\asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "C:\Temp\ONEFIL~1\asyncio\base_events.py", line 1661, in subprocess_exec
  File "C:\Temp\ONEFIL~1\asyncio\windows_events.py", line 389, in _make_subprocess_transport
  File "C:\Temp\ONEFIL~1\asyncio\base_subprocess.py", line 36, in __init__
  File "C:\Temp\ONEFIL~1\asyncio\windows_events.py", line 885, in _start
  File "C:\Temp\ONEFIL~1\asyncio\windows_utils.py", line 153, in __init__
  File "C:\Temp\ONEFIL~1\subprocess.py", line 951, in __init__
  File "C:\Temp\ONEFIL~1\subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

C:\Projects\Pycharm\AUTOREG_WARFACE\output_folder>tests_playwright.exe
Traceback (most recent call last):
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 34, in <module>
  File "C:\Temp\ONEFIL~1\tests_playwright.py", line 11, in main
  File "C:\Temp\ONEFIL~1\shutil.py", line 564, in copytree
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:\\Temp\\ONEFIL~1\\browser_chromium'
```

**Comment by kayhayen** [comment]
We have a PR merged that adds a playwrite plugin, please test that on the develop branch or upcoming 2.5

**Comment by BotovodWF** [comment]
Please advise how to use it, where can I read about it?

**Comment by kayhayen** [comment]
If you need to ask that kind question, you will be able to use it when 2.5 is released, at a time not yet known, but knowable by following the release announcement of Nuitka.
