### ISSUE TITLE
I can't package code that uses Mediapipe

### ISSUE THREAD

**Issue by qietsray** [Nuitka/Nuitka#3172]
```mptest.py
from mediapipe import solutions as mp
print(mp)
```
I'm trying to package this code with Nuitka.
When I run this code alone, it outputs the following in my environment:
`<module 'mediapipe.python.solutions' from 'C:\\Users\\PC_User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mediapipe\\python\\solutions\\__init__.py'>`

However, when I tried to package this code, an error occurred and it failed to start. The build process and the error message are shown below.
```
PS C:\Users\PC_User\Desktop\Python\mptest> nuitka mptest.py --follow-imports --include-module=mediapipe.python._framework_bindings --enable-plugin=no-qt --standalone --run
Nuitka-Options: Used command line options: mptest.py --follow-imports
Nuitka-Options: --include-module=mediapipe.python._framework_bindings --enable-plugin=no-qt --standalone --run
Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:matplotlib: Using configuration file or default backend 'tkagg'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 632 files (no progress information available for this stage).
Nuitka-Scons: Compiled 632 C files using clcache with 629 cache hits and 3 cache misses.
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka-Plugins:dll-files: Found 2 files DLLs from sounddevice installation.
Nuitka-Plugins:data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:matplotlib: Included 182 data files due to package data for 'matplotlib.
Nuitka-Plugins:matplotlib: Included data file 'matplotlib\mpl-data\matplotlibrc' due to updated matplotlib config file
Nuitka-Plugins:matplotlib: with backend to use.
Nuitka: Keeping build directory 'mptest.build'.
Nuitka: Successfully created 'mptest.dist\mptest.exe'.
Nuitka: Launching 'mptest.dist\mptest.exe'.
Traceback (most recent call last):
  File "C:\Users\PC_User\Desktop\Python\mptest\MPTEST~1.DIS\mptest.py", line 1, in <module>
  File "C:\Users\PC_User\Desktop\Python\mptest\MPTEST~1.DIS\mediapipe\__init__.py", line 15, in <module mediapipe>
  File "C:\Users\PC_User\Desktop\Python\mptest\MPTEST~1.DIS\mediapipe\python\__init__.py", line 19, in <module mediapipe.python>
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings.calculator_graph'; 'mediapipe.python._framework_bindings' is not a package
```

I tried everything I could think of, including `--include-package-data`, but the result was the same.
If you don't use `--standalone`, the following warning will appear during the build. Because of this, I'm starting to think that maybe Nuitka doesn't support Mediapipe in the first place.
```
Nuitka-Inclusion:WARNING: Cannot include extension module 'mediapipe.python._framework_bindings' unless using at least
Nuitka-Inclusion:WARNING: standalone mode, where they would be copied. In this mode, extension modules are not part of
Nuitka-Inclusion:WARNING: the compiled result, and therefore asking to include them makes no sense.
Nuitka-Inclusion:WARNING: Not allowed to include module 'mediapipe.python._framework_bindings' due to 'Extension modules
Nuitka-Inclusion:WARNING: cannot be inspected.'.
```

Finally, I will list the versions of the things I use. If you know of any good ways to do this, please help.

OS: Windows11 Home
Python: 3.12.1
Nuitka: 2.4.11
Mediapipe: 0.10.14

**Comment by kayhayen** [comment]
Can you try Python3.11, some extension modules have issues loading their sub-packages due to a core change making that hard or near impossible to support. This might be a duplicate of other issues that I don't have handy right now.

**Comment by willwade** [comment]
Interesting this. We’ve had this issue -https://github.com/AceCentre/FaceCommander/issues/82 but in trying to create a minimal example I’m not getting anywhere  https://github.com/willwade/NuitkaBuildProb - it’s the problem in the OP issue of not finding libraries above. I’ll try it all at 3.11 in that demo and see what happens

**Comment by kayhayen** [comment]
I managed to reproduce this one, there is a DLL that is not including, but it seems not to be the root cause, at least I was getting this, which is a different error.

```
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\mediapipe\python\__init__.py", line 17, in <module mediapipe.python>
ImportError: LoadLibraryExW 'C:\Users\kayha\repos\Py2C\MINI~1.DIS\mediapipe\python\_framework_bindings.pyd' failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
```

The DLL failing to load, might be also due to missing package data, trying that now. Your use of `--include-module=mediapipe.python._framework_bindings` seems strange to me, that would be this extension module that fails to load for me and it is being included.

Also I think maybe matplotlib should not get included, I will check out if that's really needed.

**Comment by kayhayen** [comment]
So, their use of matplotlib is in `mediapipe.python.solutions.drawing_utils` which gets imported at startup and only is used in one function of it, that probably is never used. Pretty sad, for this, we could do anti-bloat changes, but I think we need to implement delay-load imports, which are effective only when a module variable is first accessed, and not when the import is made, to break these hard dependencies. That's an implementation idea to take not of, so we can delay load stupid code ourselves. Of course, then we can also make these not auto-follow, and give an error message helping to recognize the need to include matplotlib explicitely if it's wanted. But I don't really want to do a `use_matplotlib` configuration and new anti-bloat items anymore, although matplotlib is probably warranted to be added.

**Comment by kayhayen** [comment]
I confirmed that Python 3.11 doesn't fare any better, checking if on Linux this is also happening.

**Comment by kayhayen** [comment]
So, Nuitka includes a `msvcp140.dll` that conflicts with the one mediapipe expects somehow. Removing that, the binary runs just fine, not sure if the DLL I found and the data files are relevant, they might well be.

**Comment by kayhayen** [comment]
So using `--noinclude-dll=msvcp140.dll` might be used as a workaround I guess.

**Comment by kayhayen** [comment]
So, excluding matplotlib would prevent this, maybe, or maybe excluding shiboken6 (PySide6) would. I think it may be incompatible with the one from matplotlib, but the top level one is from PySide6 shiboken for me. It's also probably why you have a different issue than what I do. Putting DLLs top level that are detected from extension modules, is what causes this. I think for `msvcp140.dll` that might be bad, if it's incompatible with the matplotlib one.

I need to check if removing the matplotlib one is not a better solution.

**Comment by kayhayen** [comment]
So, I managed to resolve the PySide6 (actually shiboken6, and pulled in via matplotlib) with mediapipe. The conflict is not with matplotlib at all, since they took care to rename the DLL, such that it cannot possibly cause this, but for shiboken, this is not done, and as a result, the package mediapipe, which doesn't deploy this DLL itself can end up with one that somehow seems to be incompatible.

With that, Python3.11 works for me now with the example code. I guess, trying 3.12 now to see if we got an issue there, since my error is not the one original reported.

**Comment by kayhayen** [comment]
As I unfortunately already suspected, `mediapipe` is probably like `onnx` creating modules from within an extension module, and that then fails, simply because we don't have access to the current package context anymore in Python3.12 and cannot do it, unless we implement some hacks specific to the package, or use a forked Python that we started, but didn't yet bring to frutition.

**Comment by kayhayen** [comment]
This is the list of sub-modules created by said extension module, and these will end up top level in `sys.modules` with Nuitka, for lack of package context. They are using as `from` imports in `mediapipe.python` which then fail. But an earlier `import mediapipe.python._framework_bindings` and renaming of the list of modules, will probably resolve this.

```
mediapipe.python._framework_bindings.resource_util
mediapipe.python._framework_bindings.image
mediapipe.python._framework_bindings.image_frame
mediapipe.python._framework_bindings.matrix
mediapipe.python._framework_bindings.timestamp
mediapipe.python._framework_bindings.packet
mediapipe.python._framework_bindings._packet_creator
mediapipe.python._framework_bindings._packet_getter
mediapipe.python._framework_bindings.calculator_graph
mediapipe.python._framework_bindings.validated_graph_config
mediapipe.python._framework_bindings.model_ckpt_util
```

We can create an automatic detection of some sorts for these at compile time, and then do some post load code, that moves these modules in `sys.modules` and potentially cleans up their `__package__` value so as to avoid issues with that. This seems very doable, and might be the way to go generally, if these kinds of packages themselves do not fail while producing them.

**Comment by kayhayen** [comment]
So, I managed to create a workaround for 3.12 finally, and released this as a hotfix, so 3.12 works now too.
