### ISSUE TITLE
Nuitka doesn't work with latest sentence_transformers

### ISSUE THREAD

**Issue by pingakshya2008utd** [Nuitka/Nuitka#3176]
Hi @kayhayen ,
I am trying to compile a basic sentence transformer code using Nuitka. The code is given in the sentence-transformer tutorial at :
https://sbert.net/docs/quickstart.html

```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

embeddings = model.encode(sentences)
print(embeddings.shape)
similarities = model.similarity(embeddings, embeddings)
print(similarities)
```

The nuitka command is very basic with no modules and no packges:
python -m nuitka --main=main.py --standalone --onefile --static-libpython=yes --noinclude-unittest-mode=allow --no-pyi-file 

I am getting the following error while running:

(sentence_transformer_env) pingaksh@us01odc-sc4-1-gpu064:/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test % ./main.bin

Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1778, in _get_module
  File "importlib.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/__init__.py", line 15, in <module transformers.models>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert/__init__.py", line 31, in <module transformers.models.albert>
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 2197, in define_import_structure
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1946, in create_import_structure_from_path
FileNotFoundError: [Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/main.py", line 1, in <module>
    from sentence_transformers import SentenceTransformer
    
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/__init__.py", line 10, in <module sentence_transformers>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/cross_encoder/__init__.py", line 3, in <module sentence_transformers.cross_encoder>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/cross_encoder/CrossEncoder.py", line 14, in <module sentence_transformers.cross_encoder.CrossEncoder>
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1766, in __getattr__
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1783, in _get_module
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert'

 "/remote/vg_llm/pingaksh/chroma_cache' is my temp dir which is clean and nothin to do with chromadb. 
Following are my pip installs in my env:
certifi==2024.8.30
charset-normalizer==3.4.0
filelock==3.16.1
fsspec==2024.10.0
huggingface-hub==0.26.2
idna==3.10
Jinja2==3.1.4
joblib==1.4.2
MarkupSafe==3.0.2
mpmath==1.3.0
networkx==3.4.2
Nuitka==2.4.11
numpy==2.1.2
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
ordered-set==4.1.0
packaging==24.1
pillow==11.0.0
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
safetensors==0.4.5
scikit-learn==1.5.2
scipy==1.14.1
sentence-transformers==3.2.1
setuptools==75.2.0
sympy==1.13.1
threadpoolctl==3.5.0
tokenizers==0.20.1
torch==2.5.0
tqdm==4.66.6
transformers==4.46.0
triton==3.1.0
typing_extensions==4.12.2
urllib3==2.2.3
zstandard==0.23.0

Any help will be appreciated.

**Comment by pingakshya2008utd** [comment]
Hi @kayhayen ,
I am trying to compile a basic sentence transformer code using Nuitka. The code is given in the sentence-transformer tutorial at :
https://sbert.net/docs/quickstart.html

`from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

# The sentences to encode
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],`


The nuitka command is very basic with no modules and no packges:
python -m nuitka --main=main.py --standalone --onefile --static-libpython=yes --noinclude-unittest-mode=allow --no-pyi-file 

I am getting the following error while running:

(sentence_transformer_env) pingaksh@us01odc-sc4-1-gpu064:/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test % ./main.bin


Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1778, in _get_module
  File "importlib.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/__init__.py", line 15, in <module transformers.models>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert/__init__.py", line 31, in <module transformers.models.albert>
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 2197, in define_import_structure
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1946, in create_import_structure_from_path
FileNotFoundError: [Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/main.py", line 1, in <module>
    from sentence_transformers import SentenceTransformer
    
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/__init__.py", line 10, in <module sentence_transformers>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/cross_encoder/__init__.py", line 3, in <module sentence_transformers.cross_encoder>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/sentence_transformers/cross_encoder/CrossEncoder.py", line 14, in <module sentence_transformers.cross_encoder.CrossEncoder>
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1766, in __getattr__
  File "/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/utils/import_utils.py", line 1783, in _get_module
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/chroma_cache/onefile_1497776_1730145894_164938/transformers/models/albert'

 "/remote/vg_llm/pingaksh/chroma_cache' is my temp dir which is clean and nothin to do with chromadb. 
Following are my pip installs in my env:
certifi==2024.8.30
charset-normalizer==3.4.0
filelock==3.16.1
fsspec==2024.10.0
huggingface-hub==0.26.2
idna==3.10
Jinja2==3.1.4
joblib==1.4.2
MarkupSafe==3.0.2
mpmath==1.3.0
networkx==3.4.2
Nuitka==2.4.11
numpy==2.1.2
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
ordered-set==4.1.0
packaging==24.1
pillow==11.0.0
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
safetensors==0.4.5
scikit-learn==1.5.2
scipy==1.14.1
sentence-transformers==3.2.1
setuptools==75.2.0
sympy==1.13.1
threadpoolctl==3.5.0
tokenizers==0.20.1
torch==2.5.0
tqdm==4.66.6
transformers==4.46.0
triton==3.1.0
typing_extensions==4.12.2
urllib3==2.2.3
zstandard==0.23.0


Any help will be appreciated.

**Comment by pingakshya2008utd** [comment]
If I do not use the --onefile option, I am getting the following error:
main.dist/main.bin
Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/utils/import_utils.py", line 1778, in _get_module
  File "importlib.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/models/__init__.py", line 15, in <module transformers.models>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/models/albert/__init__.py", line 31, in <module transformers.models.albert>
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/utils/import_utils.py", line 2197, in define_import_structure
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/utils/import_utils.py", line 1946, in create_import_structure_from_path
FileNotFoundError: [Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/models/albert'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/sentence_transformers/__init__.py", line 10, in <module sentence_transformers>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/sentence_transformers/cross_encoder/__init__.py", line 3, in <module sentence_transformers.cross_encoder>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/sentence_transformers/cross_encoder/CrossEncoder.py", line 14, in <module sentence_transformers.cross_encoder.CrossEncoder>
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/utils/import_utils.py", line 1766, in __getattr__
  File "/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/utils/import_utils.py", line 1783, in _get_module
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: '/remote/vg_llm/pingaksh/pycharm/chatsv_code2doc/sentence_transformet_test/main.dist/transformers/models/albert'

**Comment by kayhayen** [comment]
@huyz-git seems very relevant information, finding files to know what to import is a frequent thing we need to workaround for Nuitka, will look at that now.

**Comment by pingakshya2008utd** [comment]
Hi,
I am trying to do RAG using langchain. I used the following libraries:
from langchain.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain.prompts import ChatPromptTemplate
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain

The environment is same as above. But when I run the executable, it shows the following error:
main.dist/main.bin --gen_code --file_name ./data/query.txt
Error: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.

However, sentence-transformer is already present in the environment. Is there an way to overcome this error?

~Pingu

**Comment by kayhayen** [comment]
@pingakshya2008utd bottom posting other issues is a sure fire way to get ignored, please open a new issue with full set of information

**Comment by kayhayen** [comment]
I got newer transformers to work somewhat, but now the various transformers are having requirements for metadata, which they tell me about one by one, so I am in a compiling loop right now.

**Comment by kayhayen** [comment]
It's supposed to work with current factory version, I am checking now if transformers before 4.45 still works, since I made the detection of what needs to be done dynamic. Previously we had a list of models to cover, but that is not tenable.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by pingakshya2008utd** [comment]
Using older version worked for me at the mean time. Dont want to use the factory version as there may be some other issues as mentioned in the website. I am creating a new thread for the other issue.

**Comment by kayhayen** [comment]
This is now part of the current pre-release and will be part of 2.5 release.

**Comment by juan-OY** [comment]
I met the exactly the same issue when packing transformer 4.45.0, any pre-release version for verification?

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.

**Comment by suraj-singh-atx** [comment]
> Hi, I am trying to do RAG using langchain. I used the following libraries: from langchain.embeddings import HuggingFaceEmbeddings from langchain_community.vectorstores import Chroma from langchain.text_splitter import RecursiveCharacterTextSplitter from langchain_community.document_loaders import TextLoader from langchain.prompts import ChatPromptTemplate from langchain.chains.combine_documents import create_stuff_documents_chain from langchain.chains import create_retrieval_chain
> 
> The environment is same as above. But when I run the executable, it shows the following error: main.dist/main.bin --gen_code --file_name ./data/query.txt Error: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
> 
> However, sentence-transformer is already present in the environment. Is there an way to overcome this error?
> 
> ~Pingu

Hi,
Did you open any issue, or found solution to it?
