### ISSUE TITLE
libstdc++.so.6 missing in Onefile

### ISSUE THREAD

**Issue by Simont3** [Nuitka/Nuitka#3195]
Hi!

I updated Nuitka from 1.8.3 to 2.4.11 and found afterwards that **libstdc++.so.6**
was missing in the one file created.

When running the onefile, matplotlib complains about missing that library:

```
 % ../hcpinsight --help
Traceback (most recent call last):
  File "/tmp/onefile_1_1731574878_58469/hcpinsight.py", line 6, in <module>
  File "/tmp/onefile_1_1731574878_58469/hcpinsightlib/__main__.py", line 14, in <module hcpinsightlib.__main__>
  File "/tmp/onefile_1_1731574878_58469/hcpinsightlib/base/tools.py", line 10, in <module hcpinsightlib.base.tools>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/__init__.py", line 131, in <module matplotlib>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/rcsetup.py", line 27, in <module matplotlib.rcsetup>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/colors.py", line 56, in <module matplotlib.colors>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/scale.py", line 22, in <module matplotlib.scale>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/ticker.py", line 138, in <module matplotlib.ticker>
  File "/tmp/onefile_1_1731574878_58469/matplotlib/transforms.py", line 49, in <module matplotlib.transforms>
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onefile_1_1731574878_58469/matplotlib/_path.so)
```

Verifying the compilation-report.xml: I have in 1.8.3:

```
  <included_dll name="libstdc++-496613c0.so.6.0.32" dest_path="libstdc++-496613c0.so.6.0.32" source_path="${sys.prefix}/lib/python3.11/site-packages/contourpy.libs/libstdc++-496613c0.so.6.0.32" package="contourpy" ignored="no" reason="Used by 'contourpy/_contourpy.so'" />
  <included_dll name="libstdc++-496613c0.so.6.0.32" dest_path="libstdc++-496613c0.so.6.0.32" source_path="${sys.prefix}/lib/python3.11/site-packages/kiwisolver.libs/libstdc++-496613c0.so.6.0.32" package="kiwisolver" ignored="yes" reason="Used by 'kiwisolver/_cext.so'" />
  <included_dll name="libstdc++.so.6" dest_path="libstdc++.so.6" source_path="/usr/lib/libstdc++.so.6" package="matplotlib" ignored="no" reason="Used by 'matplotlib/_image.so'" />
```

but in 2.4.11 (as well as in 2.0.2) I have just this:

```
  <included_dll name="libstdc++-496613c0.so.6.0.32" dest_path="libstdc++-496613c0.so.6.0.32" source_path="${sys.prefix}/lib/python3.11/site-packages/contourpy.libs/libstdc++-496613c0.so.6.0.32" package="contourpy" ignored="no" reason="Used by 'contourpy/_contourpy.so'" />
  <included_dll name="libstdc++-496613c0.so.6.0.32" dest_path="libstdc++-496613c0.so.6.0.32" source_path="${sys.prefix}/lib/python3.11/site-packages/kiwisolver.libs/libstdc++-496613c0.so.6.0.32" package="kiwisolver" ignored="yes" reason="Used by 'kiwisolver/_cext.so'" />

```

I'm running Nuitka with Python 3.11 on Alpine Linux 3.20.3

Any help would be very appreciated. Let me know if you need anything else!

Thanks,
Thorsten

**Comment by kayhayen** [comment]
These DLLs are not portable across OSes and therefore are not included in standalone distributions by default anymore, but need to be present on the target system. Examples are e.g. nvidia drivers on target systems conflicting with this, and many more issues with system software used for X11, loading dialogs, etc.

**Comment by Simont3** [comment]
Thank you, Kay!
That makes sense. Sorry for bothering you.

**Comment by kayhayen** [comment]
I cannot say that the docs reflect this well enough, so no offense was taken, this report exists more for lack of docs than anything
