### ISSUE TITLE
[regression] Cannot access local variable 'target_name' where it is not associated with a value (tensorflow)

### ISSUE THREAD

**Issue by Oblynx** [Nuitka/Nuitka#3199]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

```
$ python -m nuitka --version
2.5
Commercial: None
Python: 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 11.4.0]
Flavor: Debian Python
Executable: /home/container_user/workspace/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc 11).
```

- How did you install Nuitka and Python
  - Python: `apt install python3.11-dev`
  - Nuitka: `pip install nuitka==2.5` (no venv)

- Also supply a Short, Self Contained, Correct, Example

Code:
```
$ cat _register_keras_objects.py 
import tensorflow as tf
tf.keras.utils.get_custom_objects()["leaky_relu"] = tf.nn.leaky_relu
```

Compilation:
```
$ python3 -m nuitka --module _register_keras_objects.py 
Nuitka-Options: Used command line options: --module _register_keras_objects.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main module. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.5' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.        
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.          
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 11).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 5 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 5
Traceback (most recent call last):
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/__main__.py", line 206, in <module>
    main()
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/MainControl.py", line 1160, in main
    _main()
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/MainControl.py", line 1034, in _main
    executePostProcessing()
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/PostProcessing.py", line 428, in executePostProcessing
    stubs = stubgen.generate_stub_from_source(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/build/inline_copy/stubgen/stubgen.py", line 276, in generate_stub_from_source
    stub_generator.visit(tree)
  File "/usr/lib/python3.11/ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.11/ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/home/container_user/workspace/.venv/lib/python3.11/site-packages/nuitka/build/inline_copy/stubgen/stubgen.py", line 80, in visit_Assign
    stub = f"{target_name}: {target_type}\n"
              ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'target_name' where it is not associated with a value
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```

- Note if this is a regression

  Last known working Nuitka version: **2.4.11**

**Comment by Oblynx** [comment]
Crash report: [nuitka-crash-report.txt](https://github.com/user-attachments/files/17787438/nuitka-crash-report.txt)

**Comment by kayhayen** [comment]
I will fix this asap, in the mean time, disable the pyi file generation maybe.

**Comment by kayhayen** [comment]
Thanks for the reproducer, I didn't belive it could be so simple. We inlined stubgen, but apparently it's not very ready for prime time yet, so now we allow to disable it and catch its errors and only give a warning for them, and otherwise still create the .pyi file.

**Comment by kayhayen** [comment]
Part of the 2.5.1 release and current staging branches.
