### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getOperationBinaryAddShape'  

### ISSUE THREAD

**Issue by neelkalpa** [Nuitka/Nuitka#3214]
Command: nuitka --onefile --standalone --enable-plugin=pyqt5 --output-dir=dist_app --windows-icon-from-ico=AppLogo.ico App.py --windows-uac-admin

Error:

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:519:
->                     chars[_start : +_end + 1] = reversed(chars[_start : +_end + 1])

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:518:
->                 if _end is not None:

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:512:
->             if run_ch["level"] >= level:

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:509:
->         for run_idx in range(line_start, line_end + 1):

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:509:
->         for run_idx in range(line_start, line_end + 1):

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:506:
->     for level in range(highest_level, lowest_odd_level - 1, -1):

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:506:
->     for level in range(highest_level, lowest_odd_level - 1, -1):

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:497:
-> def reverse_contiguous_sequence(

Problem with statement at C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\bidi\algorithm.py:497:
-> def reverse_contiguous_sequence(

Nuitka: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with       
Nuitka: {'filename':
Nuitka: 'C:\\Users\\Neelkalpa\\Desktop\\Synthify\\Synthify_Windows\\Lib\\site-packages\\bidi\\algorithm.py',
Nuitka: 'module_name': <ModuleName 'bidi.algorithm'>, 'code_flags': ''}>'.      
PASS 1: 99.0%|████████████████████████▋| 3778/3817, bidi.algorithmTraceback (most recent call last):
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\__main__.py", line 206, in <module>
    main()
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\MainControl.py", line 1160, in main
    _main()
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\MainControl.py", line 999, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\MainControl.py", line 257, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\Optimization.py", line 332, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\Optimization.py", line 288, in makeOptimizationPass
    changed, micro_passes = optimizeModule(current_module)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\Optimization.py", line 166, in optimizeModule
    return optimizeCompiledPythonModule(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\Optimization.py", line 82, in optimizeCompiledPythonModule  
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ModuleNodes.py", line 561, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 139, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)       
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\FrameNodes.py", line 184, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 319, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 4881, in computeExpressionRaw        
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1145, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 342, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 478, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 494, in computeFunction
    result = statements_sequence.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\TryNodes.py", line 65, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 139, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)       
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\FrameNodes.py", line 184, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\TryNodes.py", line 65, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\LoopNodes.py", line 312, in computeStatement
    loop_body, break_collections, continue_collections = self._computeLoopBody( 
                                                         ^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\LoopNodes.py", line 210, in _computeLoopBody
    result = loop_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\TryNodes.py", line 65, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\LoopNodes.py", line 312, in computeStatement
    loop_body, break_collections, continue_collections = self._computeLoopBody( 
                                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\LoopNodes.py", line 210, in _computeLoopBody
    result = loop_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 668, in computeStatement
    no_branch = branch_no_collection.computeBranch(branch=no_branch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 992, in computeBranch
    result = branch.computeStatementsSequence(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 653, in computeStatement
    yes_branch = branch_yes_collection.computeBranch(branch=yes_branch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 992, in computeBranch
    result = branch.computeStatementsSequence(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 141, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)  
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\StatementBasesGenerated.py", line 2632, in computeStatement
    result, change_tags, change_desc = self.computeStatementSubExpressions(     
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\NodeBases.py", line 729, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 3958, in computeExpressionRaw        
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 6047, in computeExpressionRaw        
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 7446, in computeExpressionRaw        
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 15875, in computeExpressionRaw       
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)  
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 9990, in computeExpressionRaw        
    return self.computeExpression(trace_collection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\OperatorNodes.py", line 170, in computeExpression
    self.type_shape, self.escape_desc = self._getOperationShape(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\OperatorNodes.py", line 264, in _getOperationShape
    return left_shape.getOperationBinaryAddShape(right_shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\shapes\StandardShapes.py", line 724, in getOperationBinaryAddShape  
    self._collectInitialShape(
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\shapes\StandardShapes.py", line 708, in _collectInitialShape        
    entry, _description = operation(type_shape)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neelkalpa\Desktop\Synthify\Synthify_Windows\Lib\site-packages\nuitka\nodes\shapes\StandardShapes.py", line 725, in <lambda>
    operation=lambda left_shape: left_shape.getOperationBinaryAddShape(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'getOperationBinaryAddShape' 
Nuitka-Reports: Compilation crash report written to file
Nuitka-Reports: 'nuitka-crash-report.xml'. Please include it in your bug report.

(added to zip, because github doesn't allow uploading xmls)

[nuitka-crash-report.zip](https://github.com/user-attachments/files/17878409/nuitka-crash-report.zip)

**Comment by kayhayen** [comment]
This reproduces it:

```
# nuitka-project: --follow-import-to=bidi

import bidi.algorithm
``

**Comment by kayhayen** [comment]
From there, I managed to extract this

```
def reverse_contiguous_sequence():
    _end = None

    for run_idx in something:
        return +_end + 1
```

It seems the `+` unary operator is somehow resolved to something that we cannot derived the binary operation shape from. Probably a none shape rather than an unknown shape there. These operations are not too optimized, and I forget when, but we added optimization for unary shapes somewhat recently.

**Comment by kayhayen** [comment]
So, this indeed a regression that is pretty recent, and released as part of 2.5, this is the commit that it bisects to:

```
commit bdffd6998b70845fbaee5de979b59f91d6f13b2d
Author: Kay Hayen <kay.hayen@gmail.com>
Date:   Sat Sep 21 08:23:11 2024 -0700

    Optimization: More dual types work
    
    * This creates working code for most tests
    
    * New templates for dual types comparisons and binary operations
    
    * Also starting unary operation shape analysis, so we can complete number operations
    
    * Also 3.13 compatibility work for No-GIL
```

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Part of the 2.5.3 hotfix release.
