### ISSUE TITLE
`SystemError: dynamic module not initialized properly` crash with pywinrt packages on Python 3.13

### ISSUE THREAD

**Issue by depthbomb** [Nuitka/Nuitka#3234]
## Nuitka version, full Python version, flavor, OS, etc.
```
2.5.4
Commercial: None
Python: 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
Flavor: CPython Official
GIL: yes
Executable: ~\Documents\Projects\.py\nuitka-winrt-bug-repro\.venv1\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe (cl 14.3).
```

## How did you install Nuitka and Python
Nuitka and pywinrt packages installed via pip into a venv for the project.

## The specific PyPI names and versions
```
Package                  Version Location              Installer
------------------------ ------- --------------------- ---------
winrt-runtime            2.3.0   <omitted for brevity> pip
winrt-Windows.Foundation 2.3.0   <omitted for brevity> pip
```

## Basic reproduction
```py
from winrt.windows.foundation import Uri

uri = Uri('https://google.com')

print(uri.scheme_name)  # expected output: https
```

## Command to compile
```sh
nuitka main.py --output-filename=test --output-dir=build --standalone
```

## Explanation
The reproduction code compiles successfully on both Python 3.12 and 3.13, however the application crashes on version 3.13 with the following output:
```
Traceback (most recent call last):
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\NUITKA~1\build\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\NUITKA~1\build\MAIN~1.DIS\winrt\windows\foundation\__init__.py", line 8, in <module winrt.windows.foundation>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
SystemError: dynamic module 'winrt._winrt_windows_foundation' not initialized properly
```

Running the script directly with Python yields no issues on both versions of Python, only when the compiled application is ran when compiled for Python 3.13. While I can't confirm that it happens with all [pywinrt](https://pypi.org/search/?q=winrt-windows) packages, it has happened with all of the packages I have used so it is safe to assume it happens with all of them.

This was also tested on the develop version of Nuitka as of commit [322f70d](https://github.com/Nuitka/Nuitka/commit/322f70d92ef5c6635addce39b8a48f03203d308b).

**Comment by kayhayen** [comment]
I think you are saying compiled works with 3.12, but not with 3.13, is that correct? Might be an extension module using a loading method we don't do correctly then yet.

**Comment by depthbomb** [comment]
> I think you are saying compiled works with 3.12, but not with 3.13, is that correct?

That is correct, I apologize if I did not word it clearly in the issue.

**Comment by kayhayen** [comment]
No worries, just wanted to make sure I understand it correctly.

**Comment by kaneryu** [comment]
Any update on this? I'm running into this exact same issue right now.

**Comment by kaneryu** [comment]
I found the fix `py2exe` used for reference:
https://github.com/py2exe/py2exe/issues/118

**Comment by kayhayen** [comment]
This works with current Nuitka and 3.12 but not with 3.13, Nuitka handles the extension module loading only different with regards to not calling `_PyImport_FixupExtensionObject` and maybe it's then not having `__file__` although we do that properly too for all I know.

**Comment by kayhayen** [comment]
Adding traces, this is what I get:

```
<module 'winrt._winrt' (C:\Users\kayha\repos\Py2C\MINI3~1.DIS\winrt\_winrt.pyd)>
C:\Users\kayha\repos\Py2C\MINI3~1.DIS\winrt\_winrt.pyd
```

Seems good enough for `__file__` so that's not it, although, this is not the one doing the trouble, checking some more, this is the one:

`import winrt._winrt_windows_foundation` which is all the reproducer needed, it still loads `winrt._winrt` and probably that corrupts `winrt` somehow, so far this only happens when the name collides and is handled, but it would have to be something like that. The module init of `winrt._winrt_windows_foundation` returns NULL with no error set, which is bad.

**Comment by kayhayen** [comment]
When I catch the exception and look at `sys.modules` the winrt module looks healthy still, so it remains unclear what it could possibly the unhappy about. It is being called with no module set, and tasked to create it, and yet returns NULL and doesn't tell us what's going on. We don't get the module. I found that `msvcp140.dll` is part of the PyPI package as the only DLL, but including that at top level or in the package folder near the DLL doesn't do anything, and likely would have failed the extension module DLL load already. Also there is no data files. It might be some implicit import missing, but I had looked at the import tracing, but maybe not correctly.

**Comment by kaneryu** [comment]
Is it possible to implement a fix like this? https://github.com/py2exe/py2exe/commit/0665cf0aba3e45b5cb980a9d0dac372c83e33388

The comment says the issue is that winrt expects a `__file__` attribute, which doesn't exist when being imported from a `.pyd` file. To fix that, they add in a explicit `__file__` attribute by patching winrt as shown in the commit.

Unfortunately, as I'm not well versed in the project, I don't understand this completely, but it appears that these hooks are used when adding the module https://github.com/py2exe/py2exe/blob/1f54a75f2224063f5d15e210ae7a74c36d343bc9/py2exe/dllfinder.py#L270 (the `hook` function and first line of `add_module` function right below it)
I'm assuming that this code is part of the project and is run whenever python tries to import a module, but as I said I'm not sure.

**Comment by kayhayen** [comment]
So, after checking out the code, I noticed a few conditions that could return NULL in the module init without setting an error, and one of them is using `PyState_FindModule` which doesn't set an error. Seems it worked fine with Nuitka until 3.13, but now we need to register with `PyState_AddModule` any extension module imported that does the newer def based import style. 

The programmers there import `win._winrt` and in later code, in typical C++ fashion, they don't have access to the module to get its state, so they find it via a def they have defined, but that's not working anymore. Very unusual method of finding what you imported, so it probably doesn't affect too many other things.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by depthbomb** [comment]
Using the factory version, I'm getting a crash at runtime in an existing project that uses PySide6 both with and without using _pywinrt_ packages:

```
Fatal Python error: PyState_AddModule: module 000001178F7234C0 already added
Python runtime state: initialized

Current thread 0x00000a08 (most recent call first):
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\shiboken6\__init__.py", line 1 in <module shiboken6>
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\PySide6\__init__.py", line 41 in _setupQtDirectories
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\PySide6\__init__.py", line 1 in <module PySide6>
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\src\rc\icons.py", line 1 in <module src.rc.icons>
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\src\__init__.py", line 1 in <module src>
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\reese\DOCUME~1\Projects\PY65C1~1\CAREPA~1\build\SRC~1.DIS\__main__.py", line 1 in <module>

Extension modules: Shiboken, shiboken6.Shiboken (total: 2)
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
```

**Comment by kaneryu** [comment]
This change breaks Shiboken 6:

Minimal Example:
```py
import logging
import os

import shiboken6
# nuitka-project: --mode=standalone

print(os.getcwd())
print(__file__)

print("Starting test script")

logging.basicConfig(level=logging.INFO)

logging.info("This is an info message")
logging.debug("This is a debug message")

shiboken6.Object.mro()
shob = shiboken6.Object()
```

Error:
```
Fatal Python error: PyState_AddModule: module 000001E11B2A0BD0 already added
Python runtime state: initialized

Current thread 0x000090a4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\****\Projects\****\TEST~1.DIS\shiboken6\__init__.py", line 1 in <module shiboken6>
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "C:\Users\****\Projects\****\TEST~1.DIS\test.py", line 1 in <module>

Extension modules: Shiboken, shiboken6.Shiboken (total: 2)
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
```

**Comment by kayhayen** [comment]
Yes, it does, and it seems `shiboken` ends up loading itself and then complaining about it like this. There is #3597 for this new crash, I will have to see if I can salvage this.

**Comment by kaneryu** [comment]
The changes implemented to `factory` since this discussion has seemed to fix this issue.

**Comment by kayhayen** [comment]
Part of a recent hotfix I made.
