### ISSUE TITLE
"SSL: CERTIFICATE_VERIFY_FAILED" When Ran on Another System.

### ISSUE THREAD

**Issue by Pairman** [Nuitka/Nuitka#3240]
Hello. I'm writing a script which sends HTTPS requests. The simplified code is:
```python
# test.py
from urllib.request import Request, urlopen
if __name__ == "__main__":
    with urlopen(Request("https://www.kernel.org/pub/")) as res:
        print(res.status)
```

And I compiled it for a standalone onefile executable with Nuitka in a distrobox container via:
```bash
📦[pairman@ubuntu bw]$ sudo apt install -y python3 python3-dev patchelf gcc upx -y && python3 -m venv venvu && source venvu/bin/activate && pip install nuitka
(venvu) 📦[pairman@ubuntu bw]$ python -m nuitka --version
2.5.4
Commercial: None
Python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Flavor: Debian Python
Executable: ~/Downloads/bw/venvu/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.5
Version C compiler: /usr/bin/gcc (gcc 11).
(venvu) 📦[pairman@ubuntu bw]$ python -m nuitka --onefile --standalone --remove-output --output-filename=test --main=./test.py
...
```

The log: **[nuitka.log](https://github.com/user-attachments/files/18017475/nuitka.log)**

And it runs normally:
```bash
(venvu) 📦[pairman@ubuntu bw]$ ./test.bin
200
```

But if I run it on my host system (Fedora Workstation 41 x86_64, Python 3.13.0) or some of my other environments, it raises SSL error:
```bash
[pairman@pairface bw]$ ./test.bin 
Traceback (most recent call last):
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 1348, in do_open
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 1283, in request
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 1329, in _send_request
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 1278, in endheaders
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 1038, in _send_output
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 976, in send
  File "/tmp/onefile_7545_1733372710_554680/http/client.py", line 1455, in connect
  File "/tmp/onefile_7545_1733372710_554680/ssl.py", line 513, in wrap_socket
  File "/tmp/onefile_7545_1733372710_554680/ssl.py", line 1100, in _create
  File "/tmp/onefile_7545_1733372710_554680/ssl.py", line 1371, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/onefile_7545_1733372710_554680/test.py", line 4, in <module>
    with urlopen(Request("https://www.kernel.org/pub/")) as res:
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 216, in urlopen
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 519, in open
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 536, in _open
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 496, in _call_chain
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 1391, in https_open
  File "/tmp/onefile_7545_1733372710_554680/urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
```

I also tested compiling on one of my servers (Rocky Linux 9.5 x86_64, Python 3.9.19, GCC 11), the binary runs normally on the server, and on the previous Fedora host, etc., but raises the same error on one WSL environment and one Kali Linux environment.

What caused this, or is there any way to fix without disabling the SSL context? Thanks in advance.

**Comment by Pairman** [comment]
Solved: for my former projects I used ```requests``` or ```aiohttp```, which uses their on ca-certs. ```urllib``` doesn't handle this. ```certifi``` should be installed (found [here](https://github.com/Nuitka/Nuitka/issues/1614#issuecomment-1160670324)) and SSL context should be manually created and passed.

**Comment by kayhayen** [comment]
Yes, I got in my "Incoming" list this as an action, it works only if you installed the certifi stuff yourself, which you essentially have to, if you want to use pip, but on other machines it doesn't work. In fact, Nuitka itself doesn't use certifi itself for it to work when it downloads on macOS, giving the same error potentially on naked system.

**Comment by kayhayen** [comment]
Recommend example code:	

```	
	response = (
	    urllib.request.urlopen(
	       ...
	        context=ssl.create_default_context(
		    ssl.Purpose.SERVER_AUTH, cafile=certifi.where(), capath=None
		),
	    )
	    .read()	
	)
```

Using request pulls in certifi, but is more heavyweight. For Nuitka, ideally we like monkey patch `urlopen` and if it gives the exception you see, turns it into a `RuntimeError`, that would be very useful, but I would need help with somebody to make a `urllib` anti-bloat engine source modification, that does exactly that.

**Comment by kayhayen** [comment]
I added a post module load config that monkey patches the function in non-deployment mode and gives an informative error pointing at certifi inclusion and usage.

**Comment by kayhayen** [comment]
This is part of the develop branch and will be part of 4.2 release. Closing for lack of general relevance early.

**Comment by kayhayen** [comment]
Part of the 4.2 release I just made.
