### ISSUE TITLE
Python3.13.1 needs support (was: Early crash with AssertionError: collections.abc)

### ISSUE THREAD

**Issue by SpectrumQT** [Nuitka/Nuitka#3241]
- Nuitka version, full Python version
```
2.6rc6
Commercial: None
Python: 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
Flavor: CPython Official
GIL: yes
Executable: C:\Program Files\Python\3.13\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Note: Same error for 2.5.4

- How did you install Nuitka and Python
  - **2.5.4**
  ```bat
  python -m pip install -U nuitka
  ```
  - **2.6rc6**
  ```bat
  python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
  ```

- `test.py` program code
```py
print('Hello World!')
```

- Nuitka options used
```
Nuitka-Options: Used command line options: --standalone --msvc=latest --output-dir=C:\Test\build C:\Test\test.py
Nuitka: Starting Python compilation with Nuitka '2.6rc6' on Python '3.13' commercial grade 'not installed'.
Traceback (most recent call last):
```

- `nuitka-crash-report.xml` contents
```xml
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.6rc6" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="AssertionError" exception_value="collections.abc">
Traceback (most recent call last):
  File "C:\Users\Spectrum\AppData\Roaming\Python\Python313\site-packages\nuitka\MainControl.py", line 1160, in main
    _main()
    ~~~~~^^
  File "C:\Users\Spectrum\AppData\Roaming\Python\Python313\site-packages\nuitka\MainControl.py", line 999, in _main
    main_module = _createMainModule()
  File "C:\Users\Spectrum\AppData\Roaming\Python\Python313\site-packages\nuitka\MainControl.py", line 146, in _createMainModule
    main_module = buildMainModuleTree(
        source_code=None,
    )
  File "C:\Users\Spectrum\AppData\Roaming\Python\Python313\site-packages\nuitka\tree\Building.py", line 1186, in buildMainModuleTree
    module.setStandardLibraryModules(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        early_module_names=detectEarlyImports(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        stdlib_modules_names=detectStdlibAutoInclusionModules(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Spectrum\AppData\Roaming\Python\Python313\site-packages\nuitka\nodes\ModuleNodes.py", line 961, in setStandardLibraryModules
    assert finding != "not-found", early_module_name
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: collections.abc
</exception>
  <performance>
    <memory_usage name="after_launch" value="42811392" />
  </performance>
  <data_composer blob_size="None" />
  <command_line>
    <option value="--standalone" />
    <option value="--msvc=latest" />
    <option value="--output-dir=C:\Test\build" />
    <option value="C:\Test\test.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="data-files" user_enabled="no" />
    <plugin name="delvewheel" user_enabled="no" />
    <plugin name="dll-files" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gevent" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="glfw" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="kivy" user_enabled="no" />
    <plugin name="matplotlib" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pbr-compat" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="playwright" user_enabled="no" />
    <plugin name="pywebview" user_enabled="no" />
    <plugin name="spacy" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}\python.exe" python_flavor="CPython Official" python_version="3.13.1" os_name="Windows" os_release="10" arch_name="x86_64" filesystem_encoding="utf-8">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.prefix}\DLLs" />
      <path value="${sys.prefix}\Lib" />
      <path value="${sys.prefix}" />
      <path value="~\AppData\Roaming\Python\Python313\site-packages" />
      <path value="~\AppData\Roaming\Python\Python313\site-packages\win32" />
      <path value="~\AppData\Roaming\Python\Python313\site-packages\win32\lib" />
      <path value="~\AppData\Roaming\Python\Python313\site-packages\Pythonwin" />
      <path value="${sys.prefix}\Lib\site-packages" />
      <path value="~\AppData\Roaming\Python\Python313\site-packages\setuptools\_vendor" />
    </search_path>
  </python>
  <output run_filename="${cwd}\build\test.dist\test.exe" />
</nuitka-compilation-report>
```

**Comment by kayhayen** [comment]
That's strange, I distinctly recall doing something for that. The `collections.abc` workaround had to change for 3.13 to work, and it seems 3.13.1 breaks it now.

**Comment by kayhayen** [comment]
There are also those test failures with 3.13.1 in terms of when things are or called:

```
Updating CPython cache by force due to non-matching comparison results.
--- C:\hostedtoolcache\windows\Python\3.13.1\x64\python.exe (stdout)
+++ nuitka (stdout)

@@ -2,10 +2,8 @@

 Getting iterable 3
 Giving iterator now 3
 Using generator <generator object iteratorCreationTiming.<locals>.<genexpr> at 0xxxxxxxxx>
-Giving iterator now 3
 Next of 3 is 0
 Getting iterable 2
-Giving iterator now 2
 Giving iterator now 2
 Next of 2 is 0
 Next of 2 is 1
@@ -15,7 +13,6 @@

 Next of 3 is 1
 Getting iterable 2
 Giving iterator now 2
-Giving iterator now 2
 Next of 2 is 0
 Next of 2 is 1
 Next of 2 is 2
@@ -23,7 +20,6 @@

 Deleting 2
 Next of 3 is 2
 Getting iterable 2
-Giving iterator now 2
 Giving iterator now 2
 Next of 2 is 0
 Next of 2 is 1
Error, results differed (stdout).
Error exit! 1
```

This must be some sort of optimization, where less iterations are now made in some cases with generators, and we don't want to be incompatible there obviously.

**Comment by kayhayen** [comment]
It's actually a kind of regression of CPython 3.13.1, making unnecessary calls:

```
diff -u out12.txt out13.txt 
--- out12.txt   2024-12-05 13:59:32.239167400 +0100
+++ out13.txt   2024-12-05 13:59:27.719785000 +0100
@@ -1,10 +1,12 @@
 Generator expression that demonstrates the timing:
 Getting iterable 3
 Giving iterator now 3
 Using generator <generator object iteratorCreationTiming.<locals>.<genexpr> at 0x0000023D11716420>  
+Giving iterator now 3
 Next of 3 is 0
 Getting iterable 2
 Giving iterator now 2
+Giving iterator now 2
 Next of 2 is 0
 next value is (0, 0)
 Next of 2 is 1
@@ -14,6 +16,7 @@
 Next of 3 is 1
 Getting iterable 2
 Giving iterator now 2
+Giving iterator now 2
 Next of 2 is 0
 Next of 2 is 1
 Next of 2 is 2
@@ -22,6 +25,7 @@
 Next of 3 is 2
 Getting iterable 2
 Giving iterator now 2
+Giving iterator now 2
 Next of 2 is 0
 Next of 2 is 1
 Next of 2 is 2
```

I didn't have the 3.13.0 to compare with, but as can be seen, iterators are called more often, so somebody probably ought to make a bug report to Python there, this is not good and seems pretty basic.

Won't follow that, rather disable this test for 3.13.1 and see if 3.13.2 is equally bad.

**Comment by SpectrumQT** [comment]
Using factory branch with commit [835a632](https://github.com/Nuitka/Nuitka/commit/835a6327cdef50a411103a56911277df3556ccdd) fixed the issue both for mentioned `test.py` and for real project. You have my gratitude!

**Comment by kayhayen** [comment]
Part of the 2.5.6 hotfix I made the other day
