### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 10184: illegal multibyte sequence

### ISSUE THREAD

**Issue by ueyome** [Nuitka/Nuitka#3248]
```
Nuitka: Starting Python compilation with Nuitka '2.5.6' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler:
Nuitka-Scons: ~\AppData\Localuitkauitka\Cache\downloads\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\clang.exe
Nuitka-Scons: (clang.exe 19.1.1).
Nuitka-Scons: Backend linking program with 171 files (no progress information available for this stage).
Traceback (most recent call last):
  File "D:\Python\Lib\site-packagesuitka\__main__.py", line 206, in <module>
    main()
  File "D:\Python\Lib\site-packagesuitka\__main__.py", line 188, in main
    MainControl.main()
  File "D:\Python\Lib\site-packagesuitka\MainControl.py", line 1160, in main
    _main()
  File "D:\Python\Lib\site-packagesuitka\MainControl.py", line 1008, in _main
    result, scons_options = compileTree()
                            ^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packagesuitka\MainControl.py", line 923, in compileTree
    result, scons_options = runSconsBackend()
                            ^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packagesuitka\MainControl.py", line 772, in runSconsBackend
    runScons(
  File "D:\Python\Lib\site-packagesuitka\build\SconsInterface.py", line 404, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "D:\Python\Lib\site-packagesuitka\build\SconsCaching.py", line 345, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packagesuitka\build\SconsCaching.py", line 289, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile, errors="backslashreplace"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packagesuitka\utils\FileOperations.py", line 787, in getFileContentByLine
    return getFileContents(
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packagesuitka\utils\FileOperations.py", line 808, in getFileContents
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 10184: illegal multibyte sequence
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
```

D:\Python\Lib\site-packages\nuitka\build\SconsCaching.py
`for line in getFileContentByLine(ccache_logfile, errors="backslashreplace"):`

Change to it worked
`for line in getFileContentByLine(ccache_logfile, errors="backslashreplace", encoding="latin1"):`

pyfile is UTF-8
Windows is Chinese Simplified

**Comment by kayhayen** [comment]
I think this is a good suggestion. I believe "latin1" cannot have decoding errors. Every character sequence is valid latin1 if I recall that correctly.

**Comment by kayhayen** [comment]
I added this to factory branch and it will be in the next hotfix.
