### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 9737: illegal multibyte sequence

### ISSUE THREAD

**Issue by binorxin** [Nuitka/Nuitka#3253]
Some of the libraries I used:
>os,  pymem,  win32gui,  win32process,  ctypes, sys, time,  io

Nuitka-Memory: Total memory usage before generating C code:: 306.84 MB (321744896 bytes)
Nuitka-Memory: Total memory usage before running scons: 310.81 MB (325910528 bytes)    
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'D:\APP\mingw-w64\mingw64\bin\gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Nuitka-Scons: Backend C compiler: gcc (gcc 14.2.0).
```python
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 923, in compileTree
    result, scons_options = runSconsBackend()
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 772, in runSconsBackend
    runScons(
  File "C:\Python310\lib\site-packages\nuitka\build\SconsInterface.py", line 404, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "C:\Python310\lib\site-packages\nuitka\build\SconsCaching.py", line 345, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
  File "C:\Python310\lib\site-packages\nuitka\build\SconsCaching.py", line 289, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile, errors="backslashreplace"):
  File "C:\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 787, in getFileContentByLine
    return getFileContents(
  File "C:\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 808, in getFileContents
    return f.read()
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 9737: illegal multibyte sequence

> I found that the gbk exists inside the module_usages of nuitka-crash-report

nuitka-crash-report detail:
```xml
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.5.6" nuitka_commercial_version="not installed" completion="exception">
  <exception exception_type="UnicodeDecodeError" exception_value="'gbk' codec can't decode byte 0xab in position 9737: illegal multibyte sequence">
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 1160, in main
    _main()
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 1008, in _main
    result, scons_options = compileTree()
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 923, in compileTree
    result, scons_options = runSconsBackend()
  File "C:\Python310\lib\site-packages\nuitka\MainControl.py", line 772, in runSconsBackend
    runScons(
  File "C:\Python310\lib\site-packages\nuitka\build\SconsInterface.py", line 404, in runScons
    checkCachingSuccess(source_dir or options["source_dir"])
  File "C:\Python310\lib\site-packages\nuitka\build\SconsCaching.py", line 345, in checkCachingSuccess
    stats = _getCcacheStatistics(ccache_logfile)
  File "C:\Python310\lib\site-packages\nuitka\build\SconsCaching.py", line 289, in _getCcacheStatistics
    for line in getFileContentByLine(ccache_logfile, errors="backslashreplace"):
  File "C:\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 787, in getFileContentByLine
    return getFileContents(
  File "C:\Python310\lib\site-packages\nuitka\utils\FileOperations.py", line 808, in getFileContents
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 9737: illegal multibyte sequence
</exception>
  <module name="__future__" kind="UncompiledPythonModule" usage="stdlib" reason="Including as part of the non-excluded parts of standard library." source_path="${sys.prefix}\lib\__future__.py">
    <optimization-time pass="1" time="0.01" micro_passes="5" max_branch_merge="8" merged_total="81" />
    <optimization-time pass="2" time="0.00" />
    <module_usages />
  </module>
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="${cwd}\GM_Go.py">
    <optimization-time pass="1" time="0.34" micro_passes="6" max_branch_merge="18" merged_total="747" />
    <optimization-time pass="2" time="0.06" micro_passes="1" max_branch_merge="15" merged_total="119" />
    <distribution-usages>
      <distribution-usage name="Pymem" />
      <distribution-usage name="pywin32" />
    </distribution-usages>
    <module_usages>
      <module_usage name="os" finding="absolute" line="2" />
      <module_usage name="pymem" finding="absolute" line="3" />
      <module_usage name="win32gui" finding="absolute" line="4" />
      <module_usage name="pymem.exception" finding="absolute" line="5" />
      <module_usage name="win32process" finding="absolute" line="6" />
      <module_usage name="ctypes" finding="absolute" line="7" />
      <module_usage name="sys" finding="absolute" line="8" />
      <module_usage name="time" finding="absolute" line="9" />
      <module_usage name="io" finding="absolute" line="10" />
      <module_usage name="_collections_abc" finding="absolute" line="1" />
      <module_usage name="abc" finding="absolute" line="1" />
      <module_usage name="ast" finding="absolute" line="1" />
      <module_usage name="codecs" finding="absolute" line="1" />
      <module_usage name="collections" finding="absolute" line="1" />
      <module_usage name="collections.abc" finding="absolute" line="1" />
      <module_usage name="contextlib" finding="absolute" line="1" />
      <module_usage name="copyreg" finding="absolute" line="1" />
      <module_usage name="dis" finding="absolute" line="1" />
      <module_usage name="encodings" finding="absolute" line="1" />
      <module_usage name="encodings.aliases" finding="absolute" line="1" />
      <module_usage name="encodings.ascii" finding="absolute" line="1" />
      <module_usage name="encodings.big5" finding="absolute" line="1" />
      <module_usage name="encodings.big5hkscs" finding="absolute" line="1" />
      <module_usage name="encodings.charmap" finding="absolute" line="1" />
      <module_usage name="encodings.cp037" finding="absolute" line="1" />
      <module_usage name="encodings.cp1006" finding="absolute" line="1" />
      <module_usage name="encodings.cp1026" finding="absolute" line="1" />
      <module_usage name="encodings.cp1125" finding="absolute" line="1" />
      <module_usage name="encodings.cp1140" finding="absolute" line="1" />
      <module_usage name="encodings.cp1250" finding="absolute" line="1" />
      <module_usage name="encodings.cp1251" finding="absolute" line="1" />
      <module_usage name="encodings.cp1252" finding="absolute" line="1" />
      <module_usage name="encodings.cp1253" finding="absolute" line="1" />
      <module_usage name="encodings.cp1254" finding="absolute" line="1" />
      <module_usage name="encodings.cp1255" finding="absolute" line="1" />
      <module_usage name="encodings.cp1256" finding="absolute" line="1" />
      <module_usage name="encodings.cp1257" finding="absolute" line="1" />
      <module_usage name="encodings.cp1258" finding="absolute" line="1" />
      <module_usage name="encodings.cp273" finding="absolute" line="1" />
      <module_usage name="encodings.cp424" finding="absolute" line="1" />
      <module_usage name="encodings.cp437" finding="absolute" line="1" />
      <module_usage name="encodings.cp500" finding="absolute" line="1" />
      <module_usage name="encodings.cp720" finding="absolute" line="1" />
      <module_usage name="encodings.cp737" finding="absolute" line="1" />
      <module_usage name="encodings.cp775" finding="absolute" line="1" />
      <module_usage name="encodings.cp850" finding="absolute" line="1" />
      <module_usage name="encodings.cp852" finding="absolute" line="1" />
      <module_usage name="encodings.cp855" finding="absolute" line="1" />
      <module_usage name="encodings.cp856" finding="absolute" line="1" />
      <module_usage name="encodings.cp857" finding="absolute" line="1" />
      <module_usage name="encodings.cp858" finding="absolute" line="1" />
      <module_usage name="encodings.cp860" finding="absolute" line="1" />
      <module_usage name="encodings.cp861" finding="absolute" line="1" />
      <module_usage name="encodings.cp862" finding="absolute" line="1" />
      <module_usage name="encodings.cp863" finding="absolute" line="1" />
      <module_usage name="encodings.cp864" finding="absolute" line="1" />
      <module_usage name="encodings.cp865" finding="absolute" line="1" />
      <module_usage name="encodings.cp866" finding="absolute" line="1" />
      <module_usage name="encodings.cp869" finding="absolute" line="1" />
      <module_usage name="encodings.cp874" finding="absolute" line="1" />
      <module_usage name="encodings.cp875" finding="absolute" line="1" />
      <module_usage name="encodings.cp932" finding="absolute" line="1" />
      <module_usage name="encodings.cp949" finding="absolute" line="1" />
      <module_usage name="encodings.cp950" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.euc_jp" finding="absolute" line="1" />
      <module_usage name="encodings.euc_kr" finding="absolute" line="1" />
      <module_usage name="encodings.gb18030" finding="absolute" line="1" />
      <module_usage name="encodings.gb2312" finding="absolute" line="1" />
      <module_usage name="encodings.gbk" finding="absolute" line="1" />
      <module_usage name="encodings.hp_roman8" finding="absolute" line="1" />
      <module_usage name="encodings.hz" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_2004" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_jp_ext" finding="absolute" line="1" />
      <module_usage name="encodings.iso2022_kr" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_1" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_10" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_11" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_13" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_14" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_15" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_16" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_2" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_3" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_4" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_5" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_6" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_7" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_8" finding="absolute" line="1" />
      <module_usage name="encodings.iso8859_9" finding="absolute" line="1" />
      <module_usage name="encodings.johab" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_r" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_t" finding="absolute" line="1" />
      <module_usage name="encodings.koi8_u" finding="absolute" line="1" />
      <module_usage name="encodings.kz1048" finding="absolute" line="1" />
      <module_usage name="encodings.latin_1" finding="absolute" line="1" />
      <module_usage name="encodings.mac_arabic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_croatian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_cyrillic" finding="absolute" line="1" />
      <module_usage name="encodings.mac_farsi" finding="absolute" line="1" />
      <module_usage name="encodings.mac_greek" finding="absolute" line="1" />
      <module_usage name="encodings.mac_iceland" finding="absolute" line="1" />
      <module_usage name="encodings.mac_latin2" finding="absolute" line="1" />
      <module_usage name="encodings.mac_roman" finding="absolute" line="1" />
      <module_usage name="encodings.mac_romanian" finding="absolute" line="1" />
      <module_usage name="encodings.mac_turkish" finding="absolute" line="1" />
      <module_usage name="encodings.mbcs" finding="absolute" line="1" />
      <module_usage name="encodings.oem" finding="absolute" line="1" />
      <module_usage name="encodings.palmos" finding="absolute" line="1" />
      <module_usage name="encodings.ptcp154" finding="absolute" line="1" />
      <module_usage name="encodings.quopri_codec" finding="absolute" line="1" />
      <module_usage name="encodings.raw_unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jis_2004" finding="absolute" line="1" />
      <module_usage name="encodings.shift_jisx0213" finding="absolute" line="1" />
      <module_usage name="encodings.tis_620" finding="absolute" line="1" />
      <module_usage name="encodings.undefined" finding="absolute" line="1" />
      <module_usage name="encodings.unicode_escape" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_16_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_be" finding="absolute" line="1" />
      <module_usage name="encodings.utf_32_le" finding="absolute" line="1" />
      <module_usage name="encodings.utf_7" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8" finding="absolute" line="1" />
      <module_usage name="encodings.utf_8_sig" finding="absolute" line="1" />
      <module_usage name="encodings.uu_codec" finding="absolute" line="1" />
      <module_usage name="encodings.zlib_codec" finding="absolute" line="1" />
      <module_usage name="enum" finding="absolute" line="1" />
      <module_usage name="functools" finding="absolute" line="1" />
      <module_usage name="genericpath" finding="absolute" line="1" />
      <module_usage name="importlib" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap" finding="absolute" line="1" />
      <module_usage name="importlib._bootstrap_external" finding="absolute" line="1" />
      <module_usage name="importlib.machinery" finding="absolute" line="1" />
      <module_usage name="inspect" finding="absolute" line="1" />
      <module_usage name="io" finding="absolute" line="1" />
      <module_usage name="keyword" finding="absolute" line="1" />
      <module_usage name="linecache" finding="absolute" line="1" />
      <module_usage name="locale" finding="absolute" line="1" />
      <module_usage name="ntpath" finding="absolute" line="1" />
      <module_usage name="opcode" finding="absolute" line="1" />
      <module_usage name="operator" finding="absolute" line="1" />
      <module_usage name="os" finding="absolute" line="1" />
      <module_usage name="quopri" finding="absolute" line="1" />
      <module_usage name="re" finding="absolute" line="1" />
      <module_usage name="reprlib" finding="absolute" line="1" />
      <module_usage name="sre_compile" finding="absolute" line="1" />
      <module_usage name="sre_constants" finding="absolute" line="1" />
      <module_usage name="sre_parse" finding="absolute" line="1" />
      <module_usage name="stat" finding="absolute" line="1" />
      <module_usage name="token" finding="absolute" line="1" />
      <module_usage name="tokenize" finding="absolute" line="1" />
      <module_usage name="types" finding="absolute" line="1" />
      <module_usage name="warnings" finding="absolute" line="1" />
      <module_usage name="__future__" finding="absolute" line="1" />
      <module_usage name="_aix_support" finding="absolute" line="1" />
      <module_usage name="_bootsubprocess" finding="absolute" line="1" />
      <module_usage name="_compat_pickle" finding="absolute" line="1" />
      <module_usage name="_compression" finding="absolute" line="1" />
      <module_usage name="_markupbase" finding="absolute" line="1" />
      <module_usage name="_osx_support" finding="absolute" line="1" />
      <module_usage name="_py_abc" finding="absolute" line="1" />
      <module_usage name="_pyio" finding="absolute" line="1" />
      <module_usage name="_sitebuiltins" finding="absolute" line="1" />
      <module_usage name="_strptime" finding="absolute" line="1" />
      <module_usage name="_threading_local" finding="absolute" line="1" />
      <module_usage name="_weakrefset" finding="absolute" line="1" />
      <module_usage name="base64" finding="absolute" line="1" />
      <module_usage name="binhex" finding="absolute" line="1" />
      <module_usage name="bisect" finding="absolute" line="1" />
      <module_usage name="calendar" finding="absolute" line="1" />
      <module_usage name="cgi" finding="absolute" line="1" />
      <module_usage name="cgitb" finding="absolute" line="1" />
      <module_usage name="chunk" finding="absolute" line="1" />
      <module_usage name="cmd" finding="absolute" line="1" />
      <module_usage name="code" finding="absolute" line="1" />
      <module_usage name="codeop" finding="absolute" line="1" />
      <module_usage name="colorsys" finding="absolute" line="1" />
      <module_usage name="configparser" finding="absolute" line="1" />
      <module_usage name="contextvars" finding="absolute" line="1" />
      <module_usage name="copy" finding="absolute" line="1" />
      <module_usage name="dataclasses" finding="absolute" line="1" />
      <module_usage name="datetime" finding="absolute" line="1" />
      <module_usage name="difflib" finding="absolute" line="1" />
      <module_usage name="encodings.base64_codec" finding="absolute" line="1" />
      <module_usage name="encodings.bz2_codec" finding="absolute" line="1" />
      <module_usage name="encodings.hex_codec" finding="absolute" line="1" />
      <module_usage name="encodings.idna" finding="absolute" line="1" />
      <module_usage name="encodings.punycode" finding="absolute" line="1" />
      <module_usage name="encodings.rot_13" finding="absolute" line="1" />
      <module_usage name="filecmp" finding="absolute" line="1" />
      <module_usage name="fileinput" finding="absolute" line="1" />
      <module_usage name="fnmatch" finding="absolute" line="1" />
      <module_usage name="ftplib" finding="absolute" line="1" />
      <module_usage name="getopt" finding="absolute" line="1" />
      <module_usage name="gettext" finding="absolute" line="1" />
      <module_usage name="glob" finding="absolute" line="1" />
      <module_usage name="graphlib" finding="absolute" line="1" />
      <module_usage name="gzip" finding="absolute" line="1" />
      <module_usage name="heapq" finding="absolute" line="1" />
      <module_usage name="html" finding="absolute" line="1" />
      <module_usage name="html.entities" finding="absolute" line="1" />
      <module_usage name="html.parser" finding="absolute" line="1" />
      <module_usage name="imaplib" finding="absolute" line="1" />
      <module_usage name="imghdr" finding="absolute" line="1" />
      <module_usage name="imp" finding="absolute" line="1" />
      <module_usage name="importlib._abc" finding="absolute" line="1" />
      <module_usage name="importlib._adapters" finding="absolute" line="1" />
      <module_usage name="importlib._common" finding="absolute" line="1" />
      <module_usage name="importlib.abc" finding="absolute" line="1" />
      <module_usage name="importlib.metadata" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._adapters" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._collections" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._functools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._itertools" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._meta" finding="absolute" line="1" />
      <module_usage name="importlib.metadata._text" finding="absolute" line="1" />
      <module_usage name="importlib.readers" finding="absolute" line="1" />
      <module_usage name="importlib.resources" finding="absolute" line="1" />
      <module_usage name="importlib.util" finding="absolute" line="1" />
      <module_usage name="ipaddress" finding="absolute" line="1" />
      <module_usage name="json" finding="absolute" line="1" />
      <module_usage name="json.decoder" finding="absolute" line="1" />
      <module_usage name="json.encoder" finding="absolute" line="1" />
      <module_usage name="json.scanner" finding="absolute" line="1" />
      <module_usage name="mailcap" finding="absolute" line="1" />
      <module_usage name="mimetypes" finding="absolute" line="1" />
      <module_usage name="modulefinder" finding="absolute" line="1" />
      <module_usage name="netrc" finding="absolute" line="1" />
      <module_usage name="nturl2path" finding="absolute" line="1" />
      <module_usage name="numbers" finding="absolute" line="1" />
      <module_usage name="pathlib" finding="absolute" line="1" />
      <module_usage name="pickle" finding="absolute" line="1" />
      <module_usage name="pickletools" finding="absolute" line="1" />
      <module_usage name="pipes" finding="absolute" line="1" />
      <module_usage name="pkgutil" finding="absolute" line="1" />
      <module_usage name="platform" finding="absolute" line="1" />
      <module_usage name="poplib" finding="absolute" line="1" />
      <module_usage name="posixpath" finding="absolute" line="1" />
      <module_usage name="pprint" finding="absolute" line="1" />
      <module_usage name="pstats" finding="absolute" line="1" />
      <module_usage name="pyclbr" finding="absolute" line="1" />
      <module_usage name="rlcompleter" finding="absolute" line="1" />
      <module_usage name="sched" finding="absolute" line="1" />
      <module_usage name="shlex" finding="absolute" line="1" />
      <module_usage name="shutil" finding="absolute" line="1" />
      <module_usage name="signal" finding="absolute" line="1" />
      <module_usage name="sndhdr" finding="absolute" line="1" />
      <module_usage name="socketserver" finding="absolute" line="1" />
      <module_usage name="string" finding="absolute" line="1" />
      <module_usage name="stringprep" finding="absolute" line="1" />
      <module_usage name="struct" finding="absolute" line="1" />
      <module_usage name="symtable" finding="absolute" line="1" />
      <module_usage name="sysconfig" finding="absolute" line="1" />
      <module_usage name="tarfile" finding="absolute" line="1" />
      <module_usage name="threading" finding="absolute" line="1" />
      <module_usage name="timeit" finding="absolute" line="1" />
      <module_usage name="trace" finding="absolute" line="1" />
      <module_usage name="traceback" finding="absolute" line="1" />
      <module_usage name="tracemalloc" finding="absolute" line="1" />
      <module_usage name="typing" finding="absolute" line="1" />
      <module_usage name="unicodedata" finding="absolute" line="1" />
      <module_usage name="uu" finding="absolute" line="1" />
      <module_usage name="weakref" finding="absolute" line="1" />
      <module_usage name="webbrowser" finding="absolute" line="1" />
      <module_usage name="xdrlib" finding="absolute" line="1" />
      <module_usage name="zipfile" finding="absolute" line="1" />
    </module_usages>
  </module>
```

**Comment by kayhayen** [comment]
I guess, that means my previous fix for writing of course needed to be paired with changing the reading part as well, thanks for your report.

**Comment by kayhayen** [comment]
Ah, I might actually have changed only one of 2 places where it's read and the one I changed is when it encounters a specific error, to be able to tell more information, so I was ineffective there.

**Comment by kayhayen** [comment]
Part of the 2.5.7 release I just made.

**Comment by kayhayen** [comment]
Dependency walker is not good at locales, or so I am thinking at least, which is why we decode its output as latin. But like you said, you have a new issue, please make a new one, and try to provide a reproducer that will show this.
