### ISSUE TITLE
PEP 695 related type ordering quirk that results in NameError

### ISSUE THREAD

**Issue by caphrim007** [Nuitka/Nuitka#3267]
I've looked at other issues, and I think this one is different from #3005 and #2930 but is also probably somewhat related. I'm aware that PEP 695 is not fully supported.

I have a codebase which makes use of custom types as seen in PEP 695

* https://peps.python.org/pep-0695/

When we've tried to use Nuitka to produce an artifact from the code, we're seeing it fail. If we re-order the code, it succeeds. Either version (the re-ordered code, and the not-re-ordered code) work when run via the standard python interpreter.

Below is a sample Python file that will illustrate the problem when provided to Nuitka.

```
from __future__ import annotations
from dataclasses import dataclass

type JSON = dict[str, "JSON"] | list["JSON"] | str | int | float | bool | None
type MaybeHTTPResponseJSON = HTTPResponseJSON | HTTPRequestFailure

@dataclass(frozen=True)
class HTTPResponseJSON:
    """An HTTP JSON response."""

    body: JSON

@dataclass(frozen=True)
class HTTPRequestFailure:
    """An HTTP request failure."""

    reason: str

print("hello world")
```

I've bootstrapped my test environment with the following commands

```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install nuitka

Collecting nuitka
  Downloading Nuitka-2.5.7.tar.gz (3.8 MB)
Collecting ordered-set>=4.1.0 (from nuitka)
Collecting zstandard>=0.15 (from nuitka)
Building wheels for collected packages: nuitka
  Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-2.5.7-cp313-cp313-macosx_14_0_arm64.whl size=3436848 
...
Successfully installed nuitka-2.5.7 ordered-set-4.1.0 zstandard-0.23.0
```

My python version is

```
$ python -V
Python 3.12.7
```

When I run Nuitka with the following arguments
```
python -m nuitka --standalone --run scratch.py
```

I get the following output.

```
Nuitka-Options: Used command line options: --standalone --run scratch.py
Nuitka: Starting Python compilation with Nuitka '2.5.7' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 6
Nuitka: Keeping build directory 'scratch.build'.
Nuitka: Created binary that runs on macOS 14.0 (arm64) or higher.
Nuitka: Successfully created 'scratch.dist/scratch.bin'.
Nuitka: Launching 'scratch.dist/scratch.bin'.
Traceback (most recent call last):
  File "/private/tmp/scratch/scratch.dist/scratch.py", line 5, in <module>
NameError: name 'HTTPResponseJSON' is not defined
```

When I run the same file directly via Python, I get the following output.

```
$ python scratch.py
hello world
```

Curiously, if I do a little re-arranging of code, I can get Nuitka to pass.

For example, if I move the `type` lines to the bottom of the file, such as what is shown below

```
from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class HTTPResponseJSON:
    """An HTTP JSON response."""

    body: JSON

@dataclass(frozen=True)
class HTTPRequestFailure:
    """An HTTP request failure."""

    reason: str

type JSON = dict[str, "JSON"] | list["JSON"] | str | int | float | bool | None
type MaybeHTTPResponseJSON = HTTPResponseJSON | HTTPRequestFailure

print("hello world")
```

Nuitka output will be the following

```
Nuitka-Options: Used command line options: --standalone --run scratch.py
Nuitka: Starting Python compilation with Nuitka '2.5.7' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'scratch.build'.
Nuitka: Created binary that runs on macOS 14.0 (arm64) or higher.
Nuitka: Successfully created 'scratch.dist/scratch.bin'.
Nuitka: Launching 'scratch.dist/scratch.bin'.
hello world
```

Which is what the expected output is. Running the modified script through the python interpreter produces identical output (compared to the original script).

I did a spot check with Nuitka installed directly from Github (commit 6264acf20b228020ecbc344a461cd622e68cd111) to see if the issue persisted there, and it appears to.

```
Nuitka-Options: Used command line options: --standalone --run scratch.py
Nuitka: Starting Python compilation with Nuitka '2.6rc8' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 5
Nuitka: Keeping build directory 'scratch.build'.
Nuitka: Created binary that runs on macOS 14.0 (arm64) or higher.
Nuitka: Successfully created 'scratch.dist/scratch.bin'.
Nuitka: Launching 'scratch.dist/scratch.bin'.
Traceback (most recent call last):
  File "/private/tmp/scratch/scratch.dist/scratch.py", line 5, in <module>
NameError: name 'HTTPResponseJSON' is not defined
```

I used two Nuitka version in this report. First, the one that I "usually" install directly from `pip` is

```
$ python -m nuitka --version

2.5.7
Commercial: None
Python: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
Flavor: Homebrew Python
Executable: /private/tmp/scratch/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.6.1
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

Second, the one I installed from Github directly (via `pip install git+https://github.com/Nuitka/Nuitka.git`) is

```
$ python -m nuitka --version

2.6rc8
Commercial: None
Python: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
Flavor: Homebrew Python
Executable: /private/tmp/scratch/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.6.1
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

Both were installed into a venv that I created specifically for this test. No other packages were installed

```
$ pip freeze

Nuitka==2.5.7
ordered-set==4.1.0
zstandard==0.23.0
```

Python was installed via Homebrew for Mac.

The following is the output from `pip list`

```
$ python -m pip list -v

Package     Version Location                                                Installer
----------- ------- ------------------------------------------------------- ---------
Nuitka      2.5.7   /private/tmp/scratch/.venv/lib/python3.12/site-packages pip
ordered-set 4.1.0   /private/tmp/scratch/.venv/lib/python3.12/site-packages pip
pip         24.2    /private/tmp/scratch/.venv/lib/python3.12/site-packages pip
zstandard   0.23.0  /private/tmp/scratch/.venv/lib/python3.12/site-packages pip
```

**Comment by ZeroIntensity** [comment]
Looks like a duplicate of #3469. I'll get to this after we get the `class Something[T]` syntax finished.
