### ISSUE TITLE
Title: RuntimeError: APScheduler modules not found in Nuitka standalone&onefile build

### ISSUE THREAD

**Issue by chilton-dev** [Nuitka/Nuitka#3280]
### Nuitka Version and Environment

```
$ python -m nuitka --version
2.5.8
Commercial: None
Python: 3.9.6 (default, Dec 11 2024, 04:43:12) 
Flavor: pyenv
Executable: ~/.cache/pypoetry/virtualenvs/house-rental-bot-yLMIf0LE-py3.9/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 24.04.1
python -m nuitka --versionVersion C compiler: /usr/bin/gcc (gcc 13).
```
Nuitka was installed via pip inside a Poetry-managed virtual environment. Python was installed using pyenv.

### Problem Description

I am encountering a runtime error when running a standalone Nuitka-built executable that includes apscheduler. The script works as expected when run directly using Python.

### Error message:
```
Traceback (most recent call last):
  File "/tmp/onefile_1183401_1735607435_403686/testbuild.py", line 2, in <module>
    from apscheduler.schedulers.asyncio import AsyncIOScheduler
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/onefile_1183401_1735607435_403686/apscheduler/schedulers/asyncio.py", line 4, in <module apscheduler.schedulers.asyncio>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/onefile_1183401_1735607435_403686/apscheduler/schedulers/base.py", line 61, in <module apscheduler.schedulers.base>
  File "/tmp/onefile_1183401_1735607435_403686/apscheduler/schedulers/base.py", line 87, in BaseScheduler
KeyError: 'apscheduler.triggers'
```

### Steps to Reproduce

1. Install apscheduler via poetry:
```
poetry add apscheduler
poetry install
poetry shell
```
2. Example script (testbuild.py):
```python
import asyncio
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.executors.asyncio import AsyncIOExecutor


async def test_func():
    print("Test function is running!")
    return True

def run_scheduler():
    jobstores = {
        'test_store': MemoryJobStore(),
    }
    executors = {'default': AsyncIOExecutor()}
    scheduler = AsyncIOScheduler(
        jobstores=jobstores,
        executors=executors,
    )

    scheduler.add_job(
        id='test_func',
        func=test_func,
        trigger="cron",
        jobstore='test_store',
        second='*',
    )

    scheduler.start()

async def main():
    print("Scheduler is running...")
    try:
        run_scheduler()
        while True:
            await asyncio.sleep(1)
    except (KeyboardInterrupt, SystemExit):
        print("Shutting down scheduler...")
        scheduler.shutdown()

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except RuntimeError as e:
        print(f"RuntimeError: {e}")
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(main())
```
### Nuitka build command:
```shell
nuitka \
  --standalone \
  testbuild.py
```
### Run the resulting binary:
./testbuild.dist/testbuild.bin

### Expected Behavior

The program should execute as it does when run directly with Python, printing Job executed! per seconds.

### Observed Behavior

The standalone executable crashes with the error:

ModuleNotFoundError: No module named 'apscheduler.triggers'

### Additional Information

1. Running with --onefile produces the same error.
2. Including   --include-package=apscheduler.triggers did not resolve the issue.
3. APScheduler version: 3.10.4
4. Based on the Nuitka build logs, I observed that apscheduler.triggers and related modules were successfully compiled and included in the build.
```
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.base'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.calendarinterval'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.combining'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.cron'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.cron.expressions'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.cron.fields'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.date'.
Nuitka-Inclusion: Included compiled module 'apscheduler.triggers.interval'.
```

**Comment by kayhayen** [comment]
For checking inclusion, you ought to use the --report output, it's much more powerful.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by chiltonwong** [comment]
I've tested the above simplest example and my project on the factory branch, and it works fine. Thanks for your great work and support!

**Comment by kayhayen** [comment]
Part of the 2.6 release I just made.
