### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#348]
I had another asyncio issue with Python 3.6.8 and Nuitka 0.6.2. Something happened, I don't know exactly what, but I think an exception has been raised. However, the exception I catched is the following.

```
Traceback (most recent call last):
File "<<<project_path>>>/concurrent/futures/_base.py" line 324 in _invoke_callbacks [args] [locals]
File "<<<project_path>>>/asyncio/futures.py" line 417 in _call_set_state [args] [locals]
File "<<<project_path>>>/asyncio/base_events.py" line 637 in call_soon_threadsafe [args] [locals]
File "<<<project_path>>>/asyncio/base_events.py" line 377 in _check_closed [args] [locals]
RuntimeError: Event loop is closed
```

I think it is related to Nuitka compilation since this is not the first asyncio exception issue and I don't see how I can get this error. That being said, I am not able to reproduce for the moment and it does not happen very often compared to other asyncio issues. To compile, I am using the following command: `nuitka3 --lto src/main.py --recurse-all --standalone --remove-output`.

I know, without a reproducer, it's very hard to figure out what the real issue is. I will try to reproduce it and give me details here.

**Comment by levesquejf** [comment]
I just had the same issue again. This time, the same code raised a `socket.gaierror` exception. Might be the trigger...

```
Traceback (most recent call last):
  File "<<<project_path>>>/concurrent/futures/_base.py", line 324, in _invoke_callbacks
  File "<<<project_path>>>/asyncio/futures.py", line 417, in _call_set_state
  File "<<<project_path>>>/asyncio/base_events.py", line 637, in call_soon_threadsafe
  File "<<<project_path>>>/asyncio/base_events.py", line 377, in _check_closed
RuntimeError: Event loop is closed

Traceback (most recent call last):
  File "<<<project_path>>>/concurrent/futures/thread.py", line 56, in run
  File "<<<project_path>>>/socket.py", line 745, in getaddrinfo
gaierror: [Errno -3] Temporary failure in name resolution
```
