### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows" in ""

### ISSUE THREAD

**Issue by timclei** [Nuitka/Nuitka#362]
I have been trying to compile a simple PyQt5 test problem under Anaconda Python 2.7. 

The simple test codes were listed here:

Nuitka_test.py:

```
from PyQt5 import QtCore, QtWidgets, QtGui, uic
import sys

import ui_nuitka_test_dialog

class Nuikta_test(QtWidgets.QDialog, ui_nuitka_test_dialog.Ui_Dialog):
    def __init__(self, parent=None):
        super(Nuikta_test, self).__init__(parent)
        self.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    form = Nuikta_test()
    form.show()
    app.exec_()

ui_nuitka_test_dialog.py:
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(579, 395)
        self.UpdateButton = QtWidgets.QPushButton(Dialog)
        self.UpdateButton.setGeometry(QtCore.QRect(20, 140, 75, 23))
        self.UpdateButton.setObjectName("UpdateButton")
        self.Magnitude = QtWidgets.QSpinBox(Dialog)
        self.Magnitude.setGeometry(QtCore.QRect(20, 80, 71, 21))
        self.Magnitude.setObjectName("Magnitude")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label.setObjectName("label")
        self.Magnitude.raise_()
        self.label.raise_()
        self.UpdateButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Magnitude, self.UpdateButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UpdateButton.setText(_translate("Dialog", "Update"))
        self.label.setText(_translate("Dialog", "Magnitude"))

```

Then  I tried to compile using the following commend under the Anaconda prompt:
python -m nuitka --follow-imports Nuitka_test.py

And I got this error when I tried to run the code. Any help is appreciated.

**Comment by BoboTiG** [comment]
Could you add the argument `--plugin-enable=qt-plugins` and retry the compilation?

**Comment by timclei** [comment]
With the argument, I cannot finish the compilation with the following errors. Thanks for the help.

(base) C:\Nuitka_test>python -m nuitka --follow-imports  --plugin-enable=qt-plugins Nuitka_test.py

Nuitka:WARNING:Cannot recurse to import module '..\..\..\..\..\..\ProgramData\Anaconda2\lib\site-packages\PyQt5\uic\port_v3\proxy_base.py' (C:\ProgramData\Anaconda2\lib\site-packages\PyQt5\uic\port_v3\proxy_base.py) because of 'SyntaxError'
Nuitka:WARNING:Unresolved '__import__' call at 'C:\ProgramData\Anaconda2\lib\site-packages\PyQt5\uic\Loader\qobjectcreator.py:69' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\ProgramData\Anaconda2\lib\site-packages\PyQt5\uic\Loader\qobjectcreator.py:115' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\MainControl.py", line 757, in main
    executePostProcessing(getResultFullpath(main_module))
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\PostProcessing.py", line 39, in executePostProcessing
    copyResourcesFromFileToFile(sys.executable, result_filename, RT_MANIFEST)
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\utils\WindowsResources.py", line 151, in copyResourcesFromFileToFile
    update_handle = _openFileWindowsResources(target_filename)
  File "C:\ProgramData\Anaconda2\lib\site-packages\nuitka\utils\WindowsResources.py", line 113, in _openFileWindowsResources
    raise ctypes.WinError()
WindowsError: [Error 2] The system cannot find the file specified.

**Comment by kayhayen** [comment]
That is very strange indeed.  Unfortunately you didn't fill out the issue template, so I would be left with guessing. But it seesm to me, an issue that @JorjMcKie recently found with sys.argv[0] could affect `sys.executable` too. Because that is basically what it is doing there, opening the Python binary that is running.

**Comment by kayhayen** [comment]
Can you make it print the filename in `WindowsResources.py` @timclei as my simple approach failed to give results, I cannot produce a value of `sys.executable` that fails to work.

**Comment by raviv** [comment]
Having similar (I think) issue, compiling a hello world on windows 10, and anaconda.

**Nuitka version**
```
0.6.4
Python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\Raviv\.conda\envs\deepx\python.exe
OS: Windows
Arch: x86_64
```

**Conda version**
```
conda 4.6.11
```

**main.py**
```python
def main():
    print("Hello World!")

if __name__ == "__main__":
    main()
```

**Compilation command**
`python -m nuitka --standalone --show-progress --debugger main.py`

**Result**
```
Nuitka:INFO:PASS 1:
Nuitka:INFO:Initial optimization pass.
Nuitka:INFO:Optimizing module '__main__', 18 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Optimizing module 'site', 20 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'site':
Nuitka:INFO:Optimizing module 'types', 19 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'types':
Nuitka:INFO:Optimizing module 'os', 18 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'os':
Nuitka:INFO:Optimizing module 'select', 17 more modules to go after that.
Nuitka:INFO:Optimizing module 'pyexpat', 16 more modules to go after that.
Nuitka:INFO:Optimizing module '_tkinter', 15 more modules to go after that.
Nuitka:INFO:Optimizing module '_ssl', 14 more modules to go after that.
Nuitka:INFO:Optimizing module '_sqlite3', 13 more modules to go after that.
Nuitka:INFO:Optimizing module '_socket', 12 more modules to go after that.
Nuitka:INFO:Optimizing module '_queue', 11 more modules to go after that.
Nuitka:INFO:Optimizing module '_overlapped', 10 more modules to go after that.
Nuitka:INFO:Optimizing module '_multiprocessing', 9 more modules to go after that.
Nuitka:INFO:Optimizing module '_msi', 8 more modules to go after that.
Nuitka:INFO:Optimizing module '_lzma', 7 more modules to go after that.
Nuitka:INFO:Optimizing module '_hashlib', 6 more modules to go after that.
Nuitka:INFO:Optimizing module '_elementtree', 5 more modules to go after that.
Nuitka:INFO:Optimizing module '_decimal', 4 more modules to go after that.
Nuitka:INFO:Optimizing module '_ctypes', 3 more modules to go after that.
Nuitka:INFO:Optimizing module '_asyncio', 2 more modules to go after that.
Nuitka:INFO:Optimizing module 'unicodedata', 1 more modules to go after that.
Nuitka:INFO:Optimizing module '_bz2', 0 more modules to go after that.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 18 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Optimizing module 'site', 20 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'site':
Nuitka:INFO:Optimizing module 'types', 19 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'types':
Nuitka:INFO:Optimizing module 'os', 18 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'os':
Nuitka:INFO:Optimizing module 'select', 17 more modules to go after that.
Nuitka:INFO:Optimizing module 'pyexpat', 16 more modules to go after that.
Nuitka:INFO:Optimizing module '_tkinter', 15 more modules to go after that.
Nuitka:INFO:Optimizing module '_ssl', 14 more modules to go after that.
Nuitka:INFO:Optimizing module '_sqlite3', 13 more modules to go after that.
Nuitka:INFO:Optimizing module '_socket', 12 more modules to go after that.
Nuitka:INFO:Optimizing module '_queue', 11 more modules to go after that.
Nuitka:INFO:Optimizing module '_overlapped', 10 more modules to go after that.
Nuitka:INFO:Optimizing module '_multiprocessing', 9 more modules to go after that.
Nuitka:INFO:Optimizing module '_msi', 8 more modules to go after that.
Nuitka:INFO:Optimizing module '_lzma', 7 more modules to go after that.
Nuitka:INFO:Optimizing module '_hashlib', 6 more modules to go after that.
Nuitka:INFO:Optimizing module '_elementtree', 5 more modules to go after that.
Nuitka:INFO:Optimizing module '_decimal', 4 more modules to go after that.
Nuitka:INFO:Optimizing module '_ctypes', 3 more modules to go after that.
Nuitka:INFO:Optimizing module '_asyncio', 2 more modules to go after that.
Nuitka:INFO:Optimizing module 'unicodedata', 1 more modules to go after that.
Nuitka:INFO:Optimizing module '_bz2', 0 more modules to go after that.
Nuitka:INFO:PASS 2 ... :
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 18 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Optimizing module 'site', 20 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'site':
Nuitka:INFO:Optimizing module 'types', 19 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'types':
Nuitka:INFO:Optimizing module 'os', 18 more modules to go after that.
Nuitka:INFO:Doing module dependency considerations for 'os':
Nuitka:INFO:Optimizing module 'select', 17 more modules to go after that.
Nuitka:INFO:Optimizing module 'pyexpat', 16 more modules to go after that.
Nuitka:INFO:Optimizing module '_tkinter', 15 more modules to go after that.
Nuitka:INFO:Optimizing module '_ssl', 14 more modules to go after that.
Nuitka:INFO:Optimizing module '_sqlite3', 13 more modules to go after that.
Nuitka:INFO:Optimizing module '_socket', 12 more modules to go after that.
Nuitka:INFO:Optimizing module '_queue', 11 more modules to go after that.
Nuitka:INFO:Optimizing module '_overlapped', 10 more modules to go after that.
Nuitka:INFO:Optimizing module '_multiprocessing', 9 more modules to go after that.
Nuitka:INFO:Optimizing module '_msi', 8 more modules to go after that.
Nuitka:INFO:Optimizing module '_lzma', 7 more modules to go after that.
Nuitka:INFO:Optimizing module '_hashlib', 6 more modules to go after that.
Nuitka:INFO:Optimizing module '_elementtree', 5 more modules to go after that.
Nuitka:INFO:Optimizing module '_decimal', 4 more modules to go after that.
Nuitka:INFO:Optimizing module '_ctypes', 3 more modules to go after that.
Nuitka:INFO:Optimizing module '_asyncio', 2 more modules to go after that.
Nuitka:INFO:Optimizing module 'unicodedata', 1 more modules to go after that.
Nuitka:INFO:Optimizing module '_bz2', 0 more modules to go after that.
Nuitka:INFO:Total memory usage before generating C code: 34.98 MB (36675584 bytes):
Nuitka:INFO:Total memory usage before running scons: 41.44 MB (43454464 bytes):
Traceback (most recent call last):
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\MainControl.py", line 768, in main
    executePostProcessing(getResultFullpath(main_module))
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\PostProcessing.py", line 59, in executePostProcessing
    lang_id=0,
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\utils\WindowsResources.py", line 234, in addResourceToFile
    update_handle = _openFileWindowsResources(target_filename)
  File "C:\Users\Raviv\.conda\envs\deepx\lib\site-packages\nuitka\utils\WindowsResources.py", line 159, in _openFileWindowsResources
    raise ctypes.WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.

```

**Comment by raviv** [comment]
**Update:**
After installing mingw64 and using this option compilation passes.
Note that I had visual studio installed.

**Comment by kayhayen** [comment]
This is a duplicate, Virus scanners have this effect.
