### ISSUE TITLE
tensorflow: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by ShowTsai** [Nuitka/Nuitka#388]
platform:Ubuntu 16.04
python:3.5.2
nuitka:0.6.3.1
I have a file ```te.py```:
```python3
import tensorflow as tf
with tf.Session() as sess:
    print(sess.run(tf.constant('hello tensorflow')))
```
I run the script:
```
python -m nuitka --follow-imports --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings  te.py
```
I run the file ```te``` in folder ```te.dist```, and I get these error:
```
  File "/home/showtsai/te.dist/imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow.py", line 58, in <module tensorflow.python.pywrap_tensorflow>
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module tensorflow.python.pywrap_tensorflow_internal>
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/showtsai/te.dist/te.py", line 1, in <module>
  File "/home/showtsai/te.dist/tensorflow/__init__.py", line 22, in <module tensorflow>
  File "/home/showtsai/te.dist/tensorflow/python/__init__.py", line 49, in <module tensorflow.python>
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow.py", line 74, in <module tensorflow.python.pywrap_tensorflow>
ImportError: Traceback (most recent call last):
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "/home/showtsai/te.dist/imp.py", line 296, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow.py", line 58, in <module tensorflow.python.pywrap_tensorflow>
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module tensorflow.python.pywrap_tensorflow_internal>
  File "/home/showtsai/te.dist/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by JorjMcKie** [comment]
Please refer to #364.
A solution has been developed and is waiting for confirmation on Linux platforms.

**Comment by ShowTsai** [comment]
Thank you for answering.
I added ```TensorflowPlugin.py``` to ```plugins/standard``` in nuitka.
I ran the compilation with arg ```--plugin-enable=tensorflow``` and I got an error:
```
Nuitka:INFO:Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'main_added': False, 'mode': 'compiled', 'filename': 'te.py'}>'.
'tensorflow' plugin did not find path magic.
```
Which source code in tensorflow does function ```onModuleSourceCode``` in ```TensorflowPlugin.py``` check?
Do I need to do something with tensorflow source code?
Thanks.

**Comment by JorjMcKie** [comment]
Well, I have to download that package in one of my Linux installations, obviously ... (sigh).

As a background:
(At least) on Windows, that package **_requires_** the ``site.py`` module and does several patching to the path environment on start. Among other things, tensorflows tries to determine, whether it is used as a PIP-installed package (don't know why this is significant).
And because the path configuration is **very** different in a Nuitka ``dist`` folder, some adjustments must be made to prevent tensorflow from doing certain things.
Fat chance that this is different on non-Windows platforms ...

Btw. please try to use my little tools (``nuitka-hints.py``, ``get-hints.py``, ``hinted-mods.py``), because that will put us in the same starting position.
These tools are able to detect, which imports your script is actually **executing** and will dynamically generate ``--enable-plugin`` and ``--recurse-to`` parameters based on this analysis.
Eg. I noticed your command line is missing the ``scipy`` option in the numpy-plugin invocation. Those tools would be aware of any package that requires any of the standard plugins.

**Comment by JorjMcKie** [comment]
Just installed ``tf_nightly-1.14.1.dev20190517-cp36-cp36m-manylinux1_x86_64.whl`` on my Linux (running in a WSL on Windows), and compiled more or less the same script as you mentioned above.
The is the compile log, created with my mentioned tools:

[tflow-compile-linux.txt](https://github.com/Nuitka/Nuitka/files/3193022/tflow-compile-linux.txt)

The created program worked write out of the box ...

In order to try this out "inofficially", you want to pick stuff from this ZIP. It contains all the tooling and the Nuitka plugin folder used.
[hinting.zip](https://github.com/Nuitka/Nuitka/files/3193213/hinting.zip)

**Comment by ShowTsai** [comment]
Thank you for answering!
I succeed in packing tensorflow by runnung these scripts.
```
python3 get-hints.py te.py
python3 nuitka-hints.py te.py
```
BTW, does it support gpu version of tensorflow?
Does it support other packages like matplotlib and cv2?

**Comment by JorjMcKie** [comment]
Glad to hear this!

In general, this type of approach is aimed to work for every package. This is (and maybe will ever be?) work in progress, because many of those monsters have specialties like hidden imports and some own data files, see below. This will regularly require changes to one or more plugins, or even creating a new one.
To see what already **has** been addressed, look [here](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation).

# Matplotlib:
See #393. Just confirmed there is an issue with missing matplotlib data files. Will need to modify the numpy plugin for this. No big deal.

# tf-gpu, cv2
Just give it a try and report any issue. With some luck, tf-gpu runs with the current `tensorflow` plugin.

**Comment by ShowTsai** [comment]
I got errors when trying another example ```main2.py```:
```python3
import tensorflow.contrib.slim as slim
@slim.add_arg_scope
def fun1(a=0, b=0):
    return (a+b)

with slim.arg_scope([fun1], a=10):
    x = fun1(b=30)
    print(x)
```
here is the log:
```
Traceback (most recent call last):
  File "/home/showtsai/test_tf/main2.dist/main2.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/cloud/__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/python/ops/bigtable_api.py", line 44, in <module>
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/util/loader.py", line 56, in load_op_library
  File "/home/showtsai/test_tf/main2.dist/tensorflow/python/framework/load_library.py", line 61, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: /home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/python/ops/_bigtable.so: cannot open shared object file: No such file or directory
```

**Comment by JorjMcKie** [comment]
Thanks for the example. Let me try to fix this. Because tensorflow is so big, we may run into this type of issue a few more times ...

Von meinem iPhone gesendet

Am 19.05.2019 um 03:21 schrieb ShowTsai <notifications@github.com<mailto:notifications@github.com>>:


I got errors when trying another example main2.py:

import tensorflow.contrib.slim as slim
@slim.add_arg_scope
def fun1(a=0, b=0):
    return (a+b)

with slim.arg_scope([fun1], a=10):
    x = fun1(b=30)
    print(x)

here is the log:

Traceback (most recent call last):
  File "/home/showtsai/test_tf/main2.dist/main2.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/cloud/__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/python/ops/bigtable_api.py", line 44, in <module>
  File "/home/showtsai/test_tf/main2.dist/tensorflow/contrib/util/loader.py", line 56, in load_op_library
  File "/home/showtsai/test_tf/main2.dist/tensorflow/python/framework/load_library.py", line 61, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: /home/showtsai/test_tf/main2.dist/tensorflow/contrib/bigtable/python/ops/_bigtable.so: cannot open shared object file: No such file or directory

**Comment by ShowTsai** [comment]
Hello, here's a new example with errors.
```python3
import tensorflow as tf
import tensorflow.contrib.slim as slim
from tensorflow.contrib.slim.python.slim.nets import resnet_utils

_image = tf.placeholder(tf.float32, shape=[1, None, None, 3])
print('net = resnet_utils')
net = resnet_utils.conv2d_same(_image, 64, 7, stride=2, scope='conv1')

print('net = tf.pads')
net = tf.pad(net, [[0, 0], [1, 1], [1, 1], [0, 0]])

print('net = slim.max_pool2d')
net = slim.max_pool2d(net, [3, 3], stride=2, padding='VALID', scope='pool1')
```

log:
>https://pastebin.com/MZWEkdY4

**Comment by JorjMcKie** [comment]
Thanks for this new example. Ooygooy - this starts looking more complex now.

**Comment by JorjMcKie** [comment]
This also happens under Windows.
Incredibly, certain functions in Tensorflow expect that **_tensorflow source code is present_** during execution!
Of course, this is not the case here. I tried and manually copied the respective source folder into the ``dist`` (at several different places) without success.
The error messages (actually more warnings type) also suggest to wrap the functions:
> If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert.

Maybe you know how to do that. If yes, I could then try to make this happen automatically.

**Comment by zeiler** [comment]
Yup I found the same thing with tf.contrib... It does a ton of dynamic loading. They are also deprecating tf.contrib in tensorflow 2.0 in our codebase I ripped out every use of it which killed two birds: 1) got Nuitka to compile and run well and 2) prepared us for 2.0.

**Comment by JorjMcKie** [comment]
@zeiler - can you share your solution?
Or the recipe to achieve the solution?
We may then publish something like: "... tensorflow version x.x.x or supported by Nuitka standalone under the following conditions ...".

**Comment by zeiler** [comment]
All I did was "I ripped out every use of it" in our codebase. So I completely avoided using tf.contrib.  There was error after error trying to use it so I gave up and refactored our code.

You can use the parge of slim that we were using like arg_scope for example by copying some of the files out and just fixing the imports up and continuing to copy tf.contrib files until there are no imports of tf.contrib. it's not a solution for nuitka, it's more to get nuitka to not have to deal with tf.contrib which is going away anyways.

**Comment by JorjMcKie** [comment]
Ah, ok I see.
If I am getting you right, then the whole approach works via modifying the package itself - apart from also massaging the app code.

Well, I am not sure what the best way is to proceed for Nuitka. I feel it cannot be anything like "... if you rewrite your code and also massively modify the tf package, then it will work". And I hear you say, that you agree with this.

On the one hand, a clean compile and an executable code is possible (specifically by using this hinting approach), and on the other hand the package contains parts which require Python source code be present to be parsed by the package during execution time.
Actually I would not mind respecting this and include those required sources. My problem is that I have not enough tensorflow knowledge to identify all those sources and I do not know, whether their presence in the app's ``dist`` folder would be sufficient.

The hint in the error messages, suggesting to use ``tf.autograph.do_not_convert``, does not work because ``tf.autograph`` has no such attribute. Maybe you have an advice here.

If this could be resolved, I am fairly certain I could find a way to automatically adjust the app's source accordingly during compilation, via the ``tensorflow`` plugin.

**Comment by zeiler** [comment]
hmm interesting. I haven't used tf.autograph but from here https://www.tensorflow.org/guide/autograph it also seems to be using tf.contrib. In the __init__.py's throughout tf.contrib there are lots of lazy loading and weird module imports that didn't seem conventional. 

This autograph stuff seems like functionality that tensorflow 2.0 is designed from ground up to be good at. They are doing that likely without autograph module because they are completely removing tf.contrib in 2.0. it's already in alpha and releasing this year so we might just have to not worry about tf.contrib soon.

**Comment by ShowTsai** [comment]
So,there's no probable solution so far, right?

**Comment by JorjMcKie** [comment]
The behaviour of tf 2.0.0-alpha seems fairly different. I have installed tf 2.0 alpha, but nor yet tried to run your script with it, @ShowTsai. It has to be converted to that version 2.0 first ...

But I'll try that today.

As I wrote some posts ago: everything depends on whether I am able to find a "dynamic patch" of the source that does this ``do_not_convert`` thing.

**Comment by JorjMcKie** [comment]
just tried to use ``tf_upgrade_v2`` for the upgrade to version 2: **it does not work!**
So, @ShowTsai, it would be great if you could find a simple example that can be used under v2 would be great!

**Comment by kayhayen** [comment]
Closing for lack of feedback
