### ISSUE TITLE
non-standalone hinted-compilation infinite loop

### ISSUE THREAD

**Issue by drzraf** [Nuitka/Nuitka#404]
Using nuitka 0.6.3.1, from pip and Python 3.7
I try to compile the following (using `python-iproute2`)
```python
# test.py
from pyroute2.netlink.exceptions import NetlinkError # using pyroute2 >= 0.5.3
from pyroute2.ipset import IPSet as pyroute2_ipset, _IPSetError
from socket import AF_INET
if __name__ == '__main__':
    ipset = pyroute2_ipset()
    ipset.destroy("test")
    ipset.create("test", stype="hash:net", family=AF_INET)
    ipset.add("test", "99.99.99.99/32", etype="net")
```

## Regular all-in-one binary (not standalone) compilation (working)

* `$ nuitka3  --run --recurse-none --recurse-none --include-module=pyroute2 --include-module=pkg_resources -o test test.py`

Notes:
* Run successfully using `sudo` (needed for `ipset`)
* binary weights 9.4 MB

## Hinted-compilation without standalone (fails)
`$ python3 get-hints.py test.py && nuitka3 --run --recurse-none --experimental=use_pefile --user-plugin=hinted-mods.py=test-3.7.3-linux-64.json test.py`

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
[...]
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Notes:
* Binary weights 23 MB
* Not using `nuitka-hints.py` which forces `--standalone`
* `$ jq -r '.files|join(",")' test-3.7.3-linux-64.json`
```
__future__,_bz2,_collections_abc,_compat_pickle,_compression,_ctypes,_hashlib,_json,_lzma,_opcode,_queue,_sqlite3,_uuid,_weakrefset,abc,base64,bdb,bisect,bz2,calendar,cmd,code,codecs,codeop,collections,collections.abc,contextlib,copy,copyreg,ctypes,ctypes._endian,datetime,dis,distutils.version,email,email._parseaddr,email._policybase,email.charset,email.encoders,email.errors,email.feedparser,email.utils,encodings,enum,fnmatch,functools,genericpath,getpass,glob,hashlib,heapq,importlib,inspect,io,json,json.decoder,json.encoder,linecache,locale,logging,lzma,multiprocessing,ntpath,opcode,operator,os,pdb,pickle,pkg_resources,pkg_resources._vendor.packaging.__about__,pkg_resources._vendor.packaging._compat,pkg_resources._vendor.packaging._structures,pkg_resources._vendor.packaging.markers,pkg_resources._vendor.packaging.specifiers,pkg_resources._vendor.packaging.version,pkg_resources._vendor.pyparsing,pkg_resources.extern,pkgutil,platform,plistlib,posixpath,pprint,pyroute2,pyroute2.cli,pyroute2.cli.console,pyroute2.cli.parser,pyroute2.common,pyroute2.config,pyroute2.conntrack,pyroute2.devlink,pyroute2.ipdb,pyroute2.ipdb.exceptions,pyroute2.ipdb.linkedset,pyroute2.ipdb.main,pyroute2.ipdb.routes,pyroute2.ipdb.transactional,pyroute2.ipdb.utils,pyroute2.iproute,pyroute2.iproute.linux,pyroute2.ipset,pyroute2.iwutil,pyroute2.ndb,pyroute2.ndb.address,pyroute2.ndb.interface,pyroute2.ndb.main,pyroute2.ndb.neighbour,pyroute2.ndb.query,pyroute2.ndb.report,pyroute2.ndb.route,pyroute2.ndb.rtnl_object,pyroute2.netlink,pyroute2.netlink.devlink,pyroute2.netlink.diag,pyroute2.netlink.event,pyroute2.netlink.event.acpi_event,pyroute2.netlink.event.dquot,pyroute2.netlink.exceptions,pyroute2.netlink.generic,pyroute2.netlink.ipq,pyroute2.netlink.nfnetlink,pyroute2.netlink.nfnetlink.ipset,pyroute2.netlink.nfnetlink.nfctsocket,pyroute2.netlink.nfnetlink.nftsocket,pyroute2.netlink.nl80211,pyroute2.netlink.nlsocket,pyroute2.netlink.rtnl,pyroute2.netlink.rtnl.fibmsg,pyroute2.netlink.rtnl.ifaddrmsg,pyroute2.netlink.rtnl.ifinfmsg,pyroute2.netlink.rtnl.ifinfmsg.plugins,pyroute2.netlink.rtnl.ifinfmsg.plugins.vlan,pyroute2.netlink.rtnl.ifinfmsg.proxy,pyroute2.netlink.rtnl.iprsocket,pyroute2.netlink.rtnl.iw_event,pyroute2.netlink.rtnl.marshal,pyroute2.netlink.rtnl.ndmsg,pyroute2.netlink.rtnl.ndtmsg,pyroute2.netlink.rtnl.nsidmsg,pyroute2.netlink.rtnl.p2pmsg,pyroute2.netlink.rtnl.req,pyroute2.netlink.rtnl.riprsocket,pyroute2.netlink.rtnl.rtgenmsg,pyroute2.netlink.rtnl.rtmsg,pyroute2.netlink.rtnl.tcmsg,pyroute2.netlink.rtnl.tcmsg.act_police,pyroute2.netlink.rtnl.tcmsg.common,pyroute2.netlink.rtnl.tcmsg.common_act,pyroute2.netlink.rtnl.tcmsg.common_ematch,pyroute2.netlink.taskstats,pyroute2.netns,pyroute2.netns.nslink,pyroute2.netns.process,pyroute2.netns.process.proxy,pyroute2.nftables.main,pyroute2.protocols,pyroute2.proxy,pyroute2.remote,queue,quopri,random,re,readline,selectors,shlex,shutil,signal,socket,sqlite3,sqlite3.dbapi2,sre_constants,stat,string,struct,subprocess,sysconfig,tempfile,termios,textwrap,threading,token,tokenize,traceback,types,urllib,uuid,warnings,weakref,xml.parsers.expat,zipfile
```
* Some `strace` of the above infinite loop:
```
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
openat(AT_FDCWD, "<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python37.zip/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.7/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.7/lib-dynload/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
openat(AT_FDCWD, "<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python37.zip/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.7/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python3.7/lib-dynload/<frozen importlib._bootstrap>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by JorjMcKie** [comment]
I just installed pyroute2 in my Windows and Linux envrionments (Python3 each).
Here is the log from the Linux runs with get-hints.py, hinted compilation and test execution.
The latter fails chattering b/o some incompatible protocol, but **does not loop**.
[pyroute-log.txt](https://github.com/Nuitka/Nuitka/files/3244714/pyroute-log.txt)
Same thing on Windows.

**Comment by drzraf** [comment]
My case is slightly different since I don't use `nuitka-hints.py` because I don't want `--standalone` because:
1. destination machine does have Python installed
2. resulting binary would be ~110 MB instead of ~20 MB
