### ISSUE TITLE
SameFileError

### ISSUE THREAD

**Issue by giodegas** [Nuitka/Nuitka#432]
* Error message:

    Traceback (most recent call last):
      File "/home/user/.env/lib/python3.7/site-packages/nuitka/__main__.py", line 184, in <module>
        main()
      File "/home/user/.env/lib/python3.7/site-packages/nuitka/__main__.py", line 177, in main
        MainControl.main()
      File "/home/user/.env/lib/python3.7/site-packages/nuitka/MainControl.py", line 774, in main
        standalone_entry_points=standalone_entry_points,
      File "/home/user/.env/lib/python3.7/site-packages/nuitka/freezer/Standalone.py", line 1563, in copyUsedDLLs
        shutil.copyfile(dll_filename, target_path)
      File "/usr/lib/python3.7/shutil.py", line 104, in copyfile
        raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
    shutil.SameFileError: '/home/user/Documents/dev/myApp/src/myTest.dist/libpython3.7m.so.1.0' and 'MyTest.dist/libpython3.7m.so.1.0' are the same file    

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

   python -m nuitka --version

    0.6.3.1
    Python: 3.7.3 (default, Apr  3 2019, 05:39:12) 
    Executable: /home/user/.env/bin/python
    OS: Linux
    Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

    pip3 install nuitka

**Comment by giodegas** [comment]
actually just doing

    rm myTest.dist/*

solved the issue
