### ISSUE TITLE
python-dateutil nuitka wheel pytest errors

### ISSUE THREAD

**Issue by tommyli3318** [Nuitka/Nuitka#435]
Platform: Windows, python 3.7.0 x32
Nuitka commit 41e39db80a2805712ac078853389a55ce6ed7492
Urllib3 commit 40924bd0392308914b01815f56d311c8478217b8

Steps to reproduce:

```
git clone https://github.com/dateutil/dateutil.git
python -m pip install -r requirements-dev.txt
python setup.py bdist_nuitka
python -m pip install dist/python_dateutil-2.8.1.dev75+g40924bd-cp37-cp37m-win32.whl
python -m pytest --disable-warnings
```

Python-dateutil normal pytest runs correctly and gives `1977 passed, 76 skipped, 21 xfailed in 7.82 seconds`. However, the nuitka-wheel dateutil raises an Unknown pytest.mark.no_cover error. Their documentation for this error is non-existent.

full error traceback of nuitka-wheel pytest:
```
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\Tommy\pipenv-testing\dateutil-testing\dateutil, inifile: setup.cfg
collected 1502 items / 4 errors / 1498 selected
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\_pytest\main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\_pytest\main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\_pytest\main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\_pytest\main.py", line 498, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-testing\dateutil\dateutil\test\conftest.py", line 20, in pytest_collection_modifyitems
INTERNALERROR>     item.add_marker(pytest.mark.no_cover)
INTERNALERROR>   File "C:\Users\Tommy\pipenv-testing\dateutil-env\lib\site-packages\_pytest\mark\structures.py", line 337, in __getattr__
INTERNALERROR>     PytestUnknownMarkWarning,
INTERNALERROR> _pytest.warning_types.PytestUnknownMarkWarning: Unknown pytest.mark.no_cover - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html

=========================== 4 error in 0.86 seconds ===========================
(dateutil-env)
```

**Comment by tommyli3318** [comment]
It seems like the error was just an issue on my part with the pytest not being able to recognize the path of `lib\site-packages\dateutil`. Closing now
