### ISSUE TITLE
Nuitka vs Numba on fibonacci

### ISSUE THREAD

**Issue by vprelovac** [Nuitka/Nuitka#437]
Noticed very big difference between nuitka and numba on a simple fibonacci benchmark. Using latest stable of nuitka, numba and python 3.7.3 on MacBook Air. 

Curious for feedback. 

Numba:
**real	0m0.702s**

Nuitka:
**real	0m2.288s**

where nuitka compiled this code
fib.py:
def fib(n):
  if n <= 1: return 1
  return fib(n - 1) + fib(n - 2) 

print(fib(35))

and numba used this code:

from numba import jit

@jit(nopython=True)
def fib(n):
    if n <= 1:  return 1
    return fib(n-1) + fib(n-2)

print(fib(35))

**Comment by kayhayen** [comment]
Nuitka lacks a lot of optimization to make this worth while, most seriously tail end recursion, which will make it raise `RecursionError` for too large values, much like CPython will.

My work to specialize types, will also not work, without knowing it. Once we have "profile guided optimization" of types though, and ideally also tail end recursion (turn recursive function calls into looping), then it will be better. But that will be a while. Until then, operations like "unknown - 1" could start to be making the assumption, that it's done with one of the few types that supports this (`int`, `long`, `float`) and be faster due to that. But for the call of itself, the C integer type will be converted to an object, and then back to int, and that is never going to fast.

Also I suspect, your measurement method is too gracious for Nuitka, because startup time of the interpreter is likely included, and could easily be 0.7s for both.

**Comment by kayhayen** [comment]
What I can, and will do, is making up some ideas about how tail loop recursion optimization could be done in Nuitka, and add this to the construct performance tests, and make sure that specialization of `-`, i.e. `BINARY_OPERATION_SUB_OBJECT_CLONG` will be very fast with this. But right now C types are only used for whole variables, not expressions, so something else is missing there.

**Comment by vprelovac** [comment]
@kayhayen Thanks for the thoughtful feedback.

Did some more tests (with fib(42)) to get a full picture

python3 157.47s
nuitka 66.05s
numba  3.74s
---
go 1.97s

I tried compiling numba code with nuitka. It compiled well but got the error (below) at execution.

You mention previously adding pythran was on your roadmap. I think instead of trying to match everything other packages do, simply support numba. I think nuitka+numba would reach go performance. 



Traceback (most recent call last):
  File "/Users/vprelovac/dev/fibnb.py", line 11, in <module>
    print(fib(42))
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 391, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 1067, in translate_stage
    return interp.interpret(bytecode)
  File "/usr/local/lib/python3.7/site-packages/numba/interpreter.py", line 97, in interpret
    self.cfa.run()
  File "/usr/local/lib/python3.7/site-packages/numba/controlflow.py", line 537, in run
    graph.set_entry_point(min(self.blocks))
ValueError: Failed in object mode pipeline (step: analyzing bytecode)
min() arg is an empty sequence

**Comment by kayhayen** [comment]
I am surprised that Numba is not closer or faster than Go, but that is really of no interest to me, as I have little idea what those 2 do internally.

As far as combining of Nuitka and Numba goes. Nuitka has no bytecode in its function unlike CPython interpreter. The code object contains an empty bytes sequence. Therefore it totally doesn't represent what the function does. Cannot do it. Numba does therefore not fit into Nuitka. Not at all, as there is no interface to talk to.

For Nuitka and Pythran, we are talking of their NumPy acceleration library part, that will work nicely together, as it only provides tools to make faster binary code. That one has an interface.

If you are interested, and I would be, can you try this one:

https://en.wikipedia.org/wiki/Stackless_Python

They do indeed do tail call recursion optimization. At least that is what one their principle makers told me long ago at a EuroPython, and that should do wonders. I would expect it to be faster than Nuitka for that reason alone, definitely faster than CPython.

Yours,
Kay

**Comment by kayhayen** [comment]
Recognizing tail end recursion, and changing a function to use loops instead of function calls needs somebody to work on it, in principle it's not hard to make, once we reliably know that a function calls itself and exits from that.
