### ISSUE TITLE
Standalone Build Error with PyQT

### ISSUE THREAD

**Issue by jss-cmyk** [Nuitka/Nuitka#457]
MacOSX10.13.6 64bit
build without --standalone option:
OK

build with --standalone option:

directly open:
Traceback (most recent call last):
  File "/Users/xxxx/Projects/dpt-installer-nuitka/dpt_installer.dist/dpt_installer.py", line 17, in <module>
ImportError: dlopen(/Users/xxxx/Projects/dpt-installer-nuitka/dpt_installer.dist/PyQt5/QtCore.so, 2): Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore
  Referenced from: /Users/xxx/Projects/dpt-installer-nuitka/dpt_installer.dist/PyQt5/QtCore.so
  Reason: image not found

open through command line: 
Traceback (most recent call last):
  File "/Users/xxxx/Projects/dpt-installer-nuitka/dpt_installer.dist/./dpt_installer.py", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 10, in <module>
    import struct
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ImportError

**Comment by jss-cmyk** [comment]
So if I do wanna ship the binary on MacOS platform, can I distribute the none standalone binary with other libs together?

**Comment by jss-cmyk** [comment]
Again， If I compile with PyCryptodome only, still throughs error:
File "/Users/xxxxx/Projects/dpt-installer-nuitka/main.dist/Crypto/Util/_raw_api.py", line 300, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Hash._SHA224': Trying '_SHA224.cpython-37m-darwin.so': dlopen(/Users/xxxxx/Projects/dpt-installer-nuitka/main.dist/Crypto/Util/../Hash/_SHA224.cpython-37m-darwin.so, 6): image not found, Trying '_SHA224.abi3.so': dlopen(/Users/xxxx/Projects/dpt-installer-nuitka/main.dist/Crypto/Util/../Hash/_SHA224.abi3.so, 6): image not found, Trying '_SHA224.so': dlopen(/Users/xxxxx/Projects/dpt-installer-nuitka/main.dist/Crypto/Util/../Hash/_SHA224.so, 6): image not found

**Comment by kayhayen** [comment]
I think this issue appeared on Travis too, and actually was an error that affects Linux too, but never showed. This should be solved in 0.6.5 which was just released.
