### ISSUE TITLE
Standalone distribution doesn't allow using module mode, doesn't include data files for implicit dependencies

### ISSUE THREAD

**Issue by golyalpha** [Nuitka/Nuitka#493]
See #492 for environment details

Nuitka command line:
```
poetry run python -m nuitka --standalone --recurse-all --python-flag=no_site --show-progress --show-scons blender_renderfarm
```

```
> .\blender_renderfarm.exe render
Traceback (most recent call last):
  File "D:\git\blender-renderfarm\blender_renderfarm.dist\__main__.py", line 14, in <module>
  File "D:\git\blender-renderfarm\blender_renderfarm.dist\fire\core.py", line 138, in Fire
  File "D:\git\blender-renderfarm\blender_renderfarm.dist\fire\core.py", line 466, in _Fire
  File "D:\git\blender-renderfarm\blender_renderfarm.dist\fire\core.py", line 675, in _CallAndUpdateTrace
  File "D:\git\blender-renderfarm\blender_renderfarm.dist\__main__.py", line 6, in render
ImportError: cannot import name 'render' from '__main__' (D:\git\blender-renderfarm\blender_renderfarm.dist\__main__.py)
```

Currently bypassing this with try/except on the imports, but maybe Nuitka should compile the executable for it to work the same way as if the module was ran with `python -m`

**Comment by kayhayen** [comment]
Can you provide the source code of that `__main__`, so I can understand what this is about?

**Comment by golyalpha** [comment]
```py
import fire


class Application():
    def render(self):
        try:
            from . import render
        except ImportError:
            from blender_renderfarm import render
        render()
    
    def benchmark(self):
        try:
            from . import construct_farmspec
        except ImportError:
            from blender_renderfarm import construct_farmspec
        construct_farmspec()


fire.Fire(Application)
```
This is the one that doesn't throw the error.

**Comment by kayhayen** [comment]
That's not supposed to work, is it?

```
python t
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/home/hayen/repos/Py2C/t/__main__.py", line 1, in <module>
    from . import x
ValueError: Attempted relative import in non-package
```

```
python3 t
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "t/__main__.py", line 1, in <module>
    from . import x
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by kayhayen** [comment]
Oh, wait, with 3.6 it is indeed different, seems Python 3.6 changed that.

**Comment by golyalpha** [comment]
@kayhayen Well, I do launch my projects as a module (-m switch), maybe assume that if main is provided as a directory instead of a file, or allow people to tell nuitka to treat the project that way?

**Comment by kayhayen** [comment]
Or maybe, just maybe ;-), be compatible to what CPython does.

**Comment by kayhayen** [comment]
Well, I can't really make it work as a package, it only works for "." imports to refer to itself?!

```
for_import = "something"
from . import for_import as value
print(value)
```

This is what appears to work for 3.6 or higher, however useful it is. Is your usage like that?

**Comment by golyalpha** [comment]
Not really, I'm importing functions from `__init__.py` into `__main__.py` both of which are in `blender_renderfarm`.

If I try to run my package like `py blender_renderfarm` it crashes:
```
Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dell\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "blender_renderfarm\__main__.py", line 23, in <module>
    fire.Fire(Application, "render")
  File "C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\Dell\AppData\Local\pypoetry\Cache\virtualenvs\blender-renderfarm-py3.7\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "blender_renderfarm\__main__.py", line 8, in render
    from . import render
ImportError: attempted relative import with no known parent package
```

So, in a way, Nuitka kinda does what it should... My issue is more with the fact that there is no way to tell Nuitka "hey, this is actually meant to be run as a module", like there is with Python (the `-m` switch)

**Comment by kayhayen** [comment]
OK, I am getting it.

To achieve that, compile your code to a module and then if you still want standalone, create a small binary that runs it, and see standalone including your extension module just fine. However, we do not use the `.pyi` files e.g. to trigger the lib2to3 addition then.

So for now, this is unsupported, but I am open to adding it. With time, this is probably going to evolve.

Yours,
Kay

**Comment by jayvdb** [comment]
fwiw, I created https://github.com/Nuitka/Nuitka/issues/523 which appears to be fairly similar.

About data of implicit dependencies, I think it is very risky to exclude them by default.  Ideally the output shows which data files are being included , and there is a extra set of flags to specify which deps can be stripped of their data.  Extra fine tuning (e.g. rules like keep only one file from subdep_x) should probably be done after nuitka has finished.

**Comment by kayhayen** [comment]
Nuitka has gained support for building wheels with setuptools, and it can include files inside the compilation result itself, consider https://nuitka.net/pages/commercial.html and https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels which will both solve this.
