### ISSUE TITLE
Test runner fails opening files in ascii

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#494]
```console
[ 1749s] Comparing output of 'ShlibUsing.py' using '/usr/bin/python3' with flags silent, expect_success, standalone, remove_output ...
[ 1767s] Traceback (most recent call last):
[ 1767s]   File "./tests/standalone/run_all.py", line 610, in <module>
[ 1767s]     main()
[ 1767s]   File "./tests/standalone/run_all.py", line 140, in main
[ 1767s]     requirements_met, error_message = checkRequirements(filename)
[ 1767s]   File "./tests/standalone/run_all.py", line 73, in checkRequirements
[ 1767s]     for line in getFileContentByLine(filename):
[ 1767s]   File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1565768581.a1f8026e/nuitka/utils/FileOperations.py", line 280, in getFileContentByLine
[ 1767s]     return getFileContents(filename, mode).splitlines()
[ 1767s]   File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1565768581.a1f8026e/nuitka/utils/FileOperations.py", line 286, in getFileContents
[ 1767s]     return f.read()
[ 1767s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[ 1767s]     return codecs.ascii_decode(input, self.errors)[0]
[ 1767s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 50: ordinal not in range(128)
```

**Comment by kayhayen** [comment]
Oh yes, there is one test case which has an encoding, and we do have to use the function that handles these things, rather than a mere file reader, to get at the source code. I will fix it.

**Comment by kayhayen** [comment]
Part of the latest pre-release.

**Comment by jayvdb** [comment]
Confirmed fixed.

**Comment by kayhayen** [comment]
The release 0.6.8 was just made and contains the correction.
