### ISSUE TITLE
Cannot compile script with nuitka that includes Gevent

### ISSUE THREAD

**Issue by DivineSentry** [Nuitka/Nuitka#508]
Using Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Using Gevent ( Have tried both 1.4.0 & 1.5a1 with the same result)
==================
using this command nuitka --remove-output --plugin-enable=tk-inter --plugin-enable=gevent --follow-imports --plugin-enable=pylint-warnings --show-progress --show-scons --mingw64 script.py
==================
Problem with statement at C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\__init__.py:1:
-> # Copyright (c) 2009-2012 Denis Bilenko. See LICENSE for details.

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'C:\\Users\\win1\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\gevent\\__init__.py', 'package': None, 'name': 'gevent'}>'.
Traceback (most recent call last):
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 561, in optimize
    finished = makeOptimizationPass(initial_pass=False)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 514, in computeModule
    trace_collection=self.trace_collection
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 549, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\nodes\AssignNodes.py", line 261, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "C:\Users\win1\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 525, in onExpression
    parent = expression.parent
AttributeError: parent

**Comment by kayhayen** [comment]
I believe this might be issue #500 and fixed with develop, can you check it out?

**Comment by DivineSentry** [comment]
developer version fixed the issue, thank you!
