### ISSUE TITLE
Standalone includes hardcoded external modules meaning executable can't be shared

### ISSUE THREAD

**Issue by brendanator** [Nuitka/Nuitka#516]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
$ python -m nuitka --version
0.6.5
Python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
Executable: /Users/brendan/.local/share/virtualenvs/test/bin/python
OS: Darwin
Arch: x86_64

$ uname -a
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
    - Python from https://www.python.org
    - nuitka with pipenv

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

```
$ cat main.py
import random

$ python -m nuitka --standalone main.py

$ ./main.dist/main

$ sudo mv /Library/Frameworks/Python.framework/Versions/3.7 /Library/Frameworks/Python.framework/Versions/3.6

$ ./main.dist/main
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/tmp/example/main.dist/./hashlib.py", line 244, in <module>
  File "/tmp/example/main.dist/./hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/tmp/example/main.dist/./main.py", line 1, in <module>
  File "/tmp/example/main.dist/./random.py", line 46, in <module>
ImportError: cannot import name 'sha512' from 'hashlib' (/tmp/example/main.dist/./hashlib.py)

$ otool -l main.dist/*.so | grep ' name' | sort | uniq
         name /Library/Frameworks/Python.framework/Versions/3.7/lib/libpanelw.5.dylib (offset 24)
         name /Library/Frameworks/Python.framework/Versions/3.7/lib/libssl.1.1.dylib (offset 24)
         name /Library/Frameworks/Python.framework/Versions/3.7/lib/libtcl8.6.dylib (offset 24)
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
         name /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (offset 24)
         name /usr/lib/libSystem.B.dylib (offset 24)
         name /usr/lib/libbz2.1.0.dylib (offset 24)
         name /usr/lib/libedit.3.dylib (offset 24)
         name /usr/lib/libz.1.dylib (offset 24)
         name @executable_path/libcrypto.1.1.dylib (offset 24)
         name @executable_path/libncursesw.5.dylib (offset 24)
         name @executable_path/libtk8.6.dylib (offset 24)
```
i have encountered this exact problem when building a standalone executable using Python 3.7.4 and distributing to someone who doesn't have Python 3.7 installed. Clearly the `/Library/Frameworks/Python.framework/Versions/3.7` path makes it non-portable and need replacing with `@executable_path/...` versions. I don't know about the other hardcoded paths, are these reliably available on different mac versions?

In my actually application the following path is also in the above list:
```
         name /usr/lib/libffi.dylib (offset 24)
```

**Comment by brendanator** [comment]
Linux looks to be more reliable:
```
$ docker run -it python:3.7.4 /bin/bash
root@887a5244cd8d:/# pip install nuitka
Collecting nuitka
  Downloading https://files.pythonhosted.org/packages/a5/a3/513958a1d8bc74ac5072e288f22beae70122120996ae817d7d3fc7f6cff7/Nuitka-0.6.5.tar.gz (2.2MB)
     |████████████████████████████████| 2.2MB 1.5MB/s
Building wheels for collected packages: nuitka
  Building wheel for nuitka (setup.py) ... done
  Created wheel for nuitka: filename=Nuitka-0.6.5-cp37-none-any.whl size=2040442 sha256=2d84a10a6d282cfc2444a071efe47d4a58ca2071603fde885ccd9b18fcbfdeb5
  Stored in directory: /root/.cache/pip/wheels/c3/a9/0f/3d91f1d18c6e036b48a2ff86a8b740615c5336f7484fb15937
Successfully built nuitka
Installing collected packages: nuitka
Successfully installed nuitka-0.6.5
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@887a5244cd8d:/# echo import random > main.py
root@887a5244cd8d:/# python -m nuitka --standalone main.py
root@887a5244cd8d:/# main.dist/main
root@887a5244cd8d:/# ldd main.dist/*.so | grep 0x | cut -f1 -d'(' | sort | uniq
        /lib64/ld-linux-x86-64.so.2
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6
        libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1
        libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1
        libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
        libdb-5.3.so => /usr/lib/x86_64-linux-gnu/libdb-5.3.so
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
        libgdbm.so.6 => /usr/lib/x86_64-linux-gnu/libgdbm.so.6
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
        libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6
        libpanelw.so.6 => /usr/lib/x86_64-linux-gnu/libpanelw.so.6
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        libpython3.7m.so.1.0 => /usr/local/lib/libpython3.7m.so.1.0
        libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
        libtcl8.6.so => /usr/lib/x86_64-linux-gnu/libtcl8.6.so
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6
        libtk8.6.so => /usr/lib/x86_64-linux-gnu/libtk8.6.so
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
        linux-vdso.so.1
root@887a5244cd8d:/# mv /usr/local/lib/ /tmp
root@887a5244cd8d:/# mv /usr/lib/x86_64-linux-gnu/ /tmp
root@887a5244cd8d:/# main.dist/main

**Comment by brendanator** [comment]
Windows only references system32 and the distribution directory

**Comment by jayvdb** [comment]
The fact it is including Python 3.7 components is likely to be a macOS specific problem, and maybe specific to only a few variables in your macOS system.  The Travis CI config here is testing macOS.

I have had numerous similar problems on openSUSE, because its layout of system libraries is slightly different to Ubuntu, especially with regards to tk, ssl, etc., and i586 vs x86_64, and other arch that openSUSE supports.  The team here have been helpful at resolving the issues I created.

What you might like to try is installing anaconda on macOS, and use Nuitka with its Python.  There are a few code paths which are optimised for anaconda's Python, so it may help you as an interim solution.

**Comment by brendanator** [comment]
Thanks for the suggestion @jayvdb. I've tried again using conda python, and it fails to run again
```
$ ./main
dyld: Library not loaded: @rpath/libpython3.7m.dylib
  Referenced from: /private/tmp/main/main.dist/./main
  Reason: image not found
[1]    45205 abort      ./main
```

The output of otool shows many required runtime libraries which aren't available
```
$ otool -l * | grep ' name' | sort | uniq
         name /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (offset 24)
         name /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (offset 24)
         name /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (offset 24)
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
         name /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (offset 24)
         name /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (offset 24)
         name /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (offset 24)
         name /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (offset 24)
         name /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (offset 24)
         name /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (offset 24)
         name /usr/lib/dyld (offset 12)
         name /usr/lib/libSystem.B.dylib (offset 24)
         name /usr/lib/libobjc.A.dylib (offset 24)
         name @rpath/libcrypto.1.1.dylib (offset 24)
         name @rpath/libffi.6.dylib (offset 24)
         name @rpath/liblzma.5.dylib (offset 24)
         name @rpath/libncursesw.6.dylib (offset 24)
         name @rpath/libpanelw.6.dylib (offset 24)
         name @rpath/libpython3.7m.dylib (offset 24)
         name @rpath/libreadline.7.dylib (offset 24)
         name @rpath/libsqlite3.0.dylib (offset 24)
         name @rpath/libssl.1.1.dylib (offset 24)
         name @rpath/libtcl8.6.dylib (offset 24)
         name @rpath/libtinfow.6.dylib (offset 24)
         name @rpath/libtk8.6.dylib (offset 24)
         name @rpath/libz.1.dylib (offset 24)
         name @rpath/libpython3.7m.dylib (offset 24)
```

However I was able to hack it by copying in all the rpath libraries and adding the @executable_path to the executable rpaths 
```
$ otool -l * | grep @rpath | sort | uniq | grep -o 'lib[^ ]*' | xargs -I{} cp $CONDA/lib/{} .
$ install_name_tool -add_rpath @executable_path/. main
$ ./main
```

I'll leave this open as the underlying issue is still there

**Comment by MarSoft** [comment]
Have the same problem here. Using Python from Xcode I think (`/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework`); running `nuitka --standalone hello_world.py` results in executable without `LC_RPATH` command and hence `Python3.framework` is not copied to the `dist` directory.
Looked at the logic implemented in #499 and found that it checks for `{sys.prefix}/conda-meta` which obviously does not exist in my case.
So I think there are two more correct solutions.
1. Check if the binary has `LC_DYLIB` commands with `@rpath/...` path but no `LC_RPATH` command and in such case inject `LC_RPATH`
2. Add corresponding linker flags to make sure it will add `rpath` command in the first place. In my case, linker is `ld` and corresponding flag is `-rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks`. Next, `ld` is called by `clang -o /path/to/project.dist/project -Wno-deprecated-declarations -headerpad_max_install_names @"./@link_input.txt" -L/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib -lm -lpython3.7m -v`. We should add the following to this command: `-Xlinker -rpath -Xlinker /Applications/Xcode.app/Contents/Developer/Library/Frameworks`.
I am still digging to find out the next step.

**Comment by tiwatsuka** [comment]
I encountered the same problem.

 I'm using Python which is installed from Command Line Tools and the path of it is  `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework`. When building with standalone option, generated binary has `LC_LOAD_DYLIB` with `@rpath/Python3.framework/Versions/3.8/Python3` but does not have `LC_RPATH`. Thus, it cannot be executed.

I finally solved this problem by inserting `env.Append(LINKFLAGS=["-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"])` to `nuitka/build/SingleExe.scons` ( which is renamed to `Backend.scons` on main branch ).  Now I can get executable binary by building with standalone option. I don't know whether this is general solution, the following snippet might help some people who are in trouble.
```python
if "darwin" in sys.platform and "/Python3.framework" in python_prefix:
    rpath = python_prefix[:python_prefix.find("/Python3.framework")]
    env.Append(LINKFLAGS=["-Wl,-rpath,"+rpath])
```

**Comment by jayvdb** [comment]
@tiwatsuka that looks good, and a general enough solution to help a lot of people.

**Comment by kayhayen** [comment]
Unfortunately I have no access to macOS. Basically in nuitka.freezer.Standalone there is code specific to macOS that should resolve the rpaths and apparently it may not be general enough. There is no way I can do it right now, and therefore I need your PRs.

I believe @tiwatsuka you are encoutering a problem from using a non-standard Python, or the same issue, I don't quite understand honestly.

**Comment by kayhayen** [comment]
I have since gained possession of a mac and the support for standalone should be perfect now.
