### ISSUE TITLE
Problems importing skimage

### ISSUE THREAD

**Issue by JohanMollevik** [Nuitka/Nuitka#517]
* Please check out if the develop version of Nuitka works better for you.

Tested using jorj branch as of 2019-09-20

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
  > python -m nuitka --version                                                         
0.6.6rc6
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Program Files\Python37\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Nuitka from git using setup.py
Python using official installer

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

minimal example

```
#!/bin/python3

from skimage.feature import register_translation
from skimage.filters import roberts, sobel, scharr, prewitt

print("end of file")
```

When importing skimage nuitka errors out with the following error

```
PS C:\Users\jmollevi\Desktop\Test> .\skimage-test.dist\skimage-test.exe
Traceback (most recent call last):
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage-test.py", line 3, in <module>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\__init__.py", line 135, in <module skimage>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\data\__init__.py", line 16, in <module skimage.data>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\data\_binary_blobs.py", line 2, in <module skimage.data._binary_blobs>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\filters\__init__.py", line 3, in <module skimage.filters>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\filters\edges.py", line 17, in <module skimage.filters.edges>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\restoration\__init__.py", line 7, in <module skimage.restoration>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\skimage\restoration\_denoise.py", line 8, in <module skimage.restoration._denoise>
  File "C:\Users\jmollevi\Desktop\Test\skimage-test.dist\pywt\__init__.py", line 16, in <module pywt>
  File "pywt\_extensions\_pywt.pyx", line 1, in init pywt._extensions._pywt
ModuleNotFoundError: No module named 'pywt._extensions._cwt'
PS C:\Users\jmollevi\Desktop\Test>
```

Compiled using hinted compilation

```
python get-hints.py skimage-test.py
python nuitka-hints.py skimage-test.py
.\skimage-test.dist\skimage-test.exe
```

**Comment by JorjMcKie** [comment]
More changes to the same two plugins ``DataFileCollector.py`` and ``ImplicitImports.py``.
With this changes your mini-script worked flawlessly ,,,
Uploaded both to the ``jorj`` branch again.

**Comment by JohanMollevik** [comment]
This commit solved the issue, on to the next bug
