### ISSUE TITLE
openSUSE factory Python 2 failure in test_bsddb3.py

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#519]
After bypassing https://github.com/Nuitka/Nuitka/issues/375, all openSUSE platforms are failing with this minor diff:

```console
[ 3163s] Comparing output of 'test/test_bsddb3.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
[ 3285s] --- /usr/bin/python2 (stderr)
[ 3285s] +++ nuitka (stderr)
[ 3285s] 
[ 3285s] @@ -1,3 +1,3 @@
[ 3285s] 
[ 3285s]  Berkeley DB 4.8.30: (December 20, 2018)
[ 3285s] -Test path prefix:  /tmp/z-test_bsddb3-10848
[ 3285s] +Test path prefix:  /tmp/z-test_bsddb3-11005
[ 3285s]  
[ 3285s] Error, outputs differed.
[ 3285s] Error exit! 1
```

However the Intel platforms are failing with
```py
[  573s] Running the CPython 2.7 tests with options '--debug' with python2.7:
[  573s] Run '/usr/bin/python2 ./tests/CPython27/run_all.py search' in '/home/abuild/rpmbuild/BUILD/Nuitka-0.6.5.1568975414.e336d005'.
[  573s] Using concrete python 2.7.16 on x86_64
[  573s] Comparing output of 'test/test_MimeWriter.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
....
[ 1045s] Comparing output of 'test/test_bsddb3.py' using '/usr/bin/python2' with flags silent, remove_output, binary_python_path, recurse_none, original_file, cpython_cache ...
[ 1103s] --- /usr/bin/python2 (stderr)
[ 1103s] +++ nuitka (stderr)
[ 1103s] 
[ 1103s] @@ -1,3 +1,27 @@
[ 1103s] 
[ 1103s]  Berkeley DB 4.8.30: (December 20, 2018)
[ 1103s] -Test path prefix:  /tmp/z-test_bsddb3-9325
[ 1103s] +Test path prefix:  /tmp/z-test_bsddb3-9466
[ 1103s] +Exception in thread reader 1:
[ 1103s] +Traceback (most recent call last):
[ 1103s] +  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
[ 1103s] +    self.run()
[ 1103s] +  File "/usr/lib64/python2.7/threading.py", line 754, in run
[ 1103s] +    self.__target(*self.__args, **self.__kwargs)
[ 1103s] +  File "/usr/lib64/python2.7/bsddb/test/test_thread.py", line 292, in readerThread
[ 1103s] +    rec = dbutils.DeadlockWrap(c.next, max_retries=10)
[ 1103s] +  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
[ 1103s] +    return function(*_args, **_kwargs)
[ 1103s] +DBLockDeadlockError: (-30994, 'DB_LOCK_DEADLOCK: Locker killed to resolve a deadlock')
[ 1103s]  
[ 1103s] +Exception in thread reader 3:
[ 1103s] +Traceback (most recent call last):
[ 1103s] +  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
[ 1103s] +    self.run()
[ 1103s] +  File "/usr/lib64/python2.7/threading.py", line 754, in run
[ 1103s] +    self.__target(*self.__args, **self.__kwargs)
[ 1103s] +  File "/usr/lib64/python2.7/bsddb/test/test_thread.py", line 292, in readerThread
[ 1103s] +    rec = dbutils.DeadlockWrap(c.next, max_retries=10)
[ 1103s] +  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
[ 1103s] +    return function(*_args, **_kwargs)
[ 1103s] +DBLockDeadlockError: (-30994, 'DB_LOCK_DEADLOCK: Locker killed to resolve a deadlock')
[ 1103s] +
[ 1103s] +
[ 1103s] Error, outputs differed.
[ 1103s] Error exit! 1
```

Config at

https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-Nuitka-factory

**Comment by kayhayen** [comment]
Let me remove this test case, it's not really using Nuitka at all and has a bunch of things that would have to be removed, leaving no actual code to be compiled.
