### ISSUE TITLE
Problems importing statsmodels

### ISSUE THREAD

**Issue by JohanMollevik** [Nuitka/Nuitka#529]
* Please check out if the develop version of Nuitka works better for you.

Tested using jorj branch as of 2019-09-23

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
> python -m nuitka --version                                                         
0.6.6rc5
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Program Files\Python37\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Nuitka from git using setup.py
Python using official installer

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

minimal example

```
#!/bin/python3

import statsmodels.api as sm
from statsmodels.nonparametric.kde import KDEUnivariate

print("end of file")
```

When importing statsmodels nuitka errors out with the following error

```
PS C:\Users\jmollevi\Desktop\Test> .\statsmodels-test.dist\statsmodels-test.exe
Traceback (most recent call last):
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels-test.py", line 3, in <module>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\api.py", line 9, in <module statsmodels.api>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\regression\recursive_ls.py", line 14, in <module statsmodels.regression.recursive_ls>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\tsa\statespace\mlemodel.py", line 31, in <module statsmodels.tsa.statespace.mlemodel>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\tsa\statespace\simulation_smoother.py", line 10, in <module statsmodels.tsa.statespace.simulation_smoother>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\tsa\statespace\kalman_smoother.py", line 11, in <module statsmodels.tsa.statespace.kalman_smoother>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\tsa\statespace\representation.py", line 10, in <module statsmodels.tsa.statespace.representation>
  File "C:\Users\jmollevi\Desktop\Test\statsmodels-test.dist\statsmodels\tsa\statespace\tools.py", line 16, in <module statsmodels.tsa.statespace.tools>
  File "statsmodels\tsa\statespace\_kalman_filter.pyx", line 1, in init statsmodels.tsa.statespace._kalman_filter
ModuleNotFoundError: No module named 'statsmodels.tsa.statespace._filters'
PS C:\Users\jmollevi\Desktop\Test>
```
Compiled using hinted compilation

python get-hints.py statsmodels-test.py
python nuitka-hints.py statsmodels-test.py
.\statsmodels-test.dist\statsmodels-test.exe

**Comment by JorjMcKie** [comment]
Just uploaded an updated ``ImplicitImports.py`` to the ``jorj`` branch, which successfully compiles and runs your example,

Onward to the next bug ...

**Comment by JohanMollevik** [comment]
That fixed it, thanks

**Comment by kayhayen** [comment]
Seems we forgot to close this.
