### ISSUE TITLE
Twisted build_with_Nuitka fails to find twisted.news

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#531]
Adding `build_with_nuitka=True` to Twisted 19.7.0 setup.py results in `Error, failed to locate package 'twisted.news'.`

```console
[  201s] Nuitka:WARNING:Recursed to module 'styles' at '/home/abuild/rpmbuild/BUILD/Twisted-19.7.0/build/lib.linux-i686-3.7/twisted/persisted/styles.py' twice.
[  201s] Nuitka:WARNING:Recursed to package 'test' at '/home/abuild/rpmbuild/BUILD/Twisted-19.7.0/build/lib.linux-i686-3.7/twisted/persisted/test' twice.
[  201s] Nuitka:WARNING:Recursed to module 'test_styles' at '/home/abuild/rpmbuild/BUILD/Twisted-19.7.0/build/lib.linux-i686-3.7/twisted/persisted/test/test_styles.py' twice.
[  201s] Error, failed to locate package 'twisted.news'.
[  206s] Traceback (most recent call last):
[  206s]   File "setup.py", line 20, in <module>
[  206s]     setuptools.setup(build_with_nuitka=True,**_setup["getSetupArgs"]())
[  206s]   File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
[  206s]     return distutils.core.setup(**attrs)
[  206s]   File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
[  206s]     dist.run_commands()
[  206s]   File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
[  206s]     self.run_command(cmd)
[  206s]   File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
[  206s]     cmd_obj.run()
[  206s]   File "/usr/lib/python3.7/site-packages/nuitka/distutils/bdist_nuitka.py", line 59, in run
[  206s]     self._build(os.path.abspath(self.build_lib))
[  206s]   File "/usr/lib/python3.7/site-packages/nuitka/distutils/bdist_nuitka.py", line 138, in _build
[  206s]     subprocess.check_call(command, cwd=build_lib)
[  206s]   File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
[  206s]     raise CalledProcessError(retcode, cmd)
[  206s] subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'nuitka', '--module', '--plugin-enable=pylint-warnings', '--output-dir=/home/abuild/rpmbuild/BUILD/Twisted-19.7.0/build/lib.linux-i686-3.7', '--show-modules', '--remove-output', '--include-package=twisted', '--include-package=twisted.names', '--include-package=twisted._threads', '--include-package=twisted.trial', '--include-package=twisted.pair', '--include-package=twisted.positioning', '--include-package=twisted.cred', '--include-package=twisted.web', '--include-package=twisted.runner', '--include-package=twisted.python', '--include-package=twisted.application', '--include-package=twisted.protocols', '--include-package=twisted.mail', '--include-package=twisted.internet', '--include-package=twisted.words', '--include-package=twisted.logger', '--include-package=twisted.spread', '--include-package=twisted.persisted', '--include-package=twisted.news', '--include-package=twisted.conch', '--include-package=twisted.tap', '--include-package=twisted.plugins', '--include-package=twisted.test', '--include-package=twisted.enterprise', '--include-package=twisted.scripts', '--include-package=twisted.names.test', '--include-package=twisted._threads.test', '--include-package=twisted.trial.test', '--include-package=twisted.trial._dist', '--include-package=twisted.trial._dist.test', '--include-package=twisted.pair.test', '--include-package=twisted.positioning.test', '--include-package=twisted.cred.test', '--include-package=twisted.web._auth', '--include-package=twisted.web.test', '--include-package=twisted.runner.test', '--include-package=twisted.python.test', '--include-package=twisted.application.runner', '--include-package=twisted.application.twist', '--include-package=twisted.application.test', '--include-package=twisted.application.runner.test', '--include-package=twisted.application.twist.test', '--include-package=twisted.protocols.haproxy', '--include-package=twisted.protocols.test', '--include-package=twisted.protocols.haproxy.test', '--include-package=twisted.mail.test', '--include-package=twisted.mail.scripts', '--include-package=twisted.internet.iocpreactor', '--include-package=twisted.internet.test', '--include-package=twisted.words.xish', '--include-package=twisted.words.protocols', '--include-package=twisted.words.test', '--include-package=twisted.words.im', '--include-package=twisted.words.protocols.jabber', '--include-package=twisted.logger.test', '--include-package=twisted.spread.test', '--include-package=twisted.persisted.test', '--include-package=twisted.news.test', '--include-package=twisted.conch.openssh_compat', '--include-package=twisted.conch.ui', '--include-package=twisted.conch.ssh', '--include-package=twisted.conch.insults', '--include-package=twisted.conch.test', '--include-package=twisted.conch.client', '--include-package=twisted.conch.scripts', '--include-package=twisted.scripts.test', '/home/abuild/rpmbuild/BUILD/Twisted-19.7.0/build/lib.linux-i686-3.7/twisted']' returned non-zero exit status 1.
```

**Comment by KevinRodriguez777** [comment]
whatever `twisted.news` was, it was removed a while ago https://github.com/twisted/twisted/pull/1234 , and is not supported on python3
