### ISSUE TITLE
Error while using module created using Nuitka from python package using numpy.

### ISSUE THREAD

**Issue by adipandas** [Nuitka/Nuitka#549]
* I am trying to create a standalone module using a simple package I created.
Following is the file structure I have:

```
/home/user/nuitka_demo/NumpyProject/
    -- ./test.py
    -- ./firstPack/
        -- ./__init__.py
        -- ./firstpack.py
```

* Content of the files:
```
# __init__.py
from firstPack.firstpack import MyVector
```

```
# firstpack.py
import numpy as np

class MyVector:
    def __init__(self, vector_as_list):
        self.vector = vector_as_list

    def vectorize(self):
        return np.array(self.vector)

    def scale(self, scale_factor):
        return scale_factor*self.vectorize()
```

```
# test.py
import firstPack
from firstPack import MyVector
vec = MyVector([1,2,3])
print(vec.vectorize())
print(vec.scale(3))
```

* I am using the following command to create the module from the folder `/home/user/nuitka_demo/NumpyProject/`
```
python -m nuitka --module firstPack --plugin-enable=numpy --follow-imports --include-package=firstPack --include-plugin-directory=/home/user/anaconda3/envs/nuitka_env/lib/python3.6/site-packages/numpy/core --include-plugin-directory=/home/user/anaconda3/envs/nuitka_env/lib/python3.6/site-packages/numpy/lib 
```

* When I run this command in terminal I am getting the following warning:
```
Nuitka:WARNING:Recursed to package 'firstPack' at /home/user/nuitka_demo/NumpyProject/firstPack' twice.
```

* When I try to use the firstPack.so module created, I get the following error:
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import firstPack
  File "/home/user/nuitka_demo/NumpyProject/firstPack/__init__.py", line 1, in <module firstPack>
  File "/home/user/nuitka_demo/NumpyProject/firstPack/firstpack.py", line 1, in <module firstPack.firstpack>
  File "/home/user/nuitka_demo/NumpyProject/numpy/__init__.py", line 142, in <module numpy>
  File "/home/user/nuitka_demo/NumpyProject/numpy/core/__init__.py", line 3, in <module numpy.core>

``` 

* Details:
```
$python -m nuitka --version
0.6.5
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
Executable: /home/user/anaconda3/envs/nuitka_env/bin/python
OS: Linux
Arch: x86_64
```

* I installed Nuitka using `pip install Nuitka`

* I tried the hello world example of Nuitka. It worked for me. There was no issue.

It will be great if someone can point me in the right direction. I am not sure what is it that I am missing and how to resolve this issue.

Thank you in advance.

**Comment by adipandas** [comment]
Okay, I got to a point where I create a module something like `firstPack.so` using `nuitka`, and in my `test.py` module, I import module after importing `numpy`. Then the code is working. I have shared the updated code below.

```
# test.py
import numpy as np
import firstPack
from firstPack import MyVector
vec = MyVector([1,2,3])
print(vec.vectorize())
print(vec.scale(3))
```

Does this mean I cannot create a single module `firstPack.so` which will include `numpy` internally? Will have to mention `numpy` as a dependency always for this module?

Please let me know if I am missing something or any more information is required.
