### ISSUE TITLE
Staticly linked _ctypes breaks standalone use of ctypes

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#550]
I have a static CPython with _ctypes compiled in, so it doesnt have a `__file__` which I suspect is the problem.

```console
[   77s] + python3 -c 'import _ctypes; print(_ctypes.__file__)'
[   77s] Traceback (most recent call last):
[   77s]   File "<string>", line 1, in <module>
[   77s] AttributeError: module '_ctypes' has no attribute '__file__'
```

Normally that would print something like `/usr/lib64/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so`

Building a standalone which needs ctypes then fails with a sys.exit, but here is the backtrace if the `sys.exit` is replaced with `raise RuntimeError` (which helps newbie me, but probably doesnt help core devs who already know the possible code paths).

```
[  195s] Traceback (most recent call last):
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/__main__.py", line 183, in <module>
[  195s]     main()
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/__main__.py", line 176, in main
[  195s]     MainControl.main()
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/MainControl.py", line 766, in main
[  195s]     main_module = createNodeTree(filename=filename)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/MainControl.py", line 141, in createNodeTree
[  195s]     Optimization.optimize(main_module.getOutputFilename())
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 616, in optimize
[  195s]     makeOptimizationPass(initial_pass=True)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 530, in makeOptimizationPass
[  195s]     changed = optimizeModule(current_module)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 168, in optimizeModule
[  195s]     changed = optimizeCompiledPythonModule(module)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 127, in optimizeCompiledPythonModule
[  195s]     Plugins.considerImplicitImports(module=module, signal_change=signalChange)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 128, in considerImplicitImports
[  195s]     plugin.considerImplicitImports(module, signal_change)
[  195s]   File "/usr/lib/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 184, in considerImplicitImports
[  195s]     % (full_name, module.getFullName())
```

**Comment by jayvdb** [comment]
I worked around this by removing the check (`if required:`), which I guess should be replaced with `if required and not some_is_whitelisted_check():`

**Comment by kayhayen** [comment]
https://github.com/Nuitka/Nuitka/blob/0ff702e065b1b53231ba0cae451385a3da0fe766/nuitka/plugins/standard/ImplicitImports.py#L245

Here, Nuitka requests that it must be found. I guess the real issue though is that being built-in is not considered found.

**Comment by ceztko** [comment]
I'm possibly having a similar issue trying to use a standalone python distribution 3.8 built with this tool[1]. Trying to run nuitka on a script using tensorflow ends with this error:

```
Traceback (most recent call last):
  File "/home/ceztko/projects/current/vision-ml-libs/facerecon/test_feature.dist/test_feature.py", line 1, in <module>
  File "/home/ceztko/projects/current/vision-ml-libs/facerecon/test_feature.dist/embedder.py", line 3, in <module embedder>
  File "/home/ceztko/projects/current/vision-ml-libs/facerecon/test_feature.dist/tensorflow/__init__.py", line 41, in <module tensorflow>
  File "/home/ceztko/projects/current/vision-ml-libs/facerecon/test_feature.dist/tensorflow/python/__init__.py", line 28, in <module tensorflow.python>
  File "/home/ceztko/projects/current/vision-ml-libs/facerecon/test_feature.dist/ctypes/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named '_ctypes'
```

The nuitka command line I used is:
```
nuitka --standalone --plugin-enable=pylint-warnings --plugin-enable=tensorflow --plugin-enable=numpy --plugin-disable=torch test_feature.py
```

I'm now trying to build a 3.9 distribution with the same tool, hoping it makes a difference. Can you recommend a workaround for such issue in general?

[1] https://github.com/indygreg/python-build-standalone
