### ISSUE TITLE
Question regarding the current status of making PySide2 work with Nuitka.

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#558]
Hi,

I have already read many posts regarding PySide2 not working with Nuitka. My question is more about the current limitations, if I don't need to compile all my code. Please note that I am not an experienced programmer, but currently learning as fast as I can, so I may miss something obvious to you.

I have done a test and I was able to successfully compile and run a [small PySide2 example](https://github.com/pyside/pyside2-examples/blob/dev/examples/tutorial/t12.py). The Qt window opens but some items are missing or behave differently (the input widgets are connected to each other, while they are not when running by CPython). To do that I used --nofollow-import-to=PySide2, and I manually copied the PySide2 and shiboken folders to my root, along with the platforms folder for Qt binaries.

I have then compiled a smaller script that imports the .pyc version of the example, and everything seems to work as expected. So, to my understanding, I can use Noitka even if I have PySide2 dependencies, as long as I don't compile any code using PySide2.

Question: will Nuitka to be compatible with PySide2 in the future? Is it a dead-end or is it planned for later? 

Thanks.

**Comment by math-artist** [comment]
I tried to add the --include-plugin-directory option for vtk modules, and got an assertion error
```
0.6.6rc7
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\Mak\Anaconda3\envs\fresh\python.exe
OS: Windows
Arch: x86_64
VTK: 8.2.0
```

```
Problem with statement at C:\Users\Mak\Anaconda3\envs\fresh\Lib\site-packages\vtkmodules\util\vtkVariant.py:5:
-> from .. import vtkCommonCore

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\Mak\\Anaconda3\\envs\\fresh\\Lib\\site-packages\\vtkmodules\\util\\vtkVariant.py', 'module_name': <Modul
eName vtkmodules.util.vtkVariant>}>'.
Traceback (most recent call last):
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\__main__.py", line 184, in <module>
    main()
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\__main__.py", line 177, in main
    MainControl.main()
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\MainControl.py", line 766, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\Optimization.py", line 616, in optimize
    makeOptimizationPass(initial_pass=True)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\Optimization.py", line 530, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\Optimization.py", line 168, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 500, in computeModule
    trace_collection=self.trace_collection
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\StatementNodes.py", line 164, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 550, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\AssignNodes.py", line 259, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1111, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 531, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ImportNodes.py", line 403, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ImportNodes.py", line 277, in _attemptRecursion
    module_package=module_package,
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ImportNodes.py", line 208, in _consider
    reason=reason,
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\importing\Recursion.py", line 167, in recurseTo
    reason=reason,
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\importing\Recursion.py", line 83, in _recurseTo
    is_shlib=module_kind == "shlib",
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\tree\Building.py", line 944, in decideModuleTree
    source_ref=source_ref,
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 588, in __init__
    source_ref=source_ref,
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 264, in __init__
    setLocalsDictType(self.module_dict_name, "module_dict")
  File "C:\Users\Mak\Anaconda3\envs\fresh\lib\site-packages\nuitka\nodes\LocalsScopes.py", line 31, in setLocalsDictType
    assert locals_dict_name not in locals_dict_handles, locals_dict_name
AssertionError: globals_vtkmodules
```

This is the code inside vtkCommonCore:
```
from __future__ import absolute_import

try:
    # use relative import for installed modules
    from .vtkCommonCorePython import *
except ImportError:
    # during build and testing, the modules will be elsewhere,
    # e.g. in lib directory or Release/Debug config directories
    from vtkCommonCorePython import *
```

I don't really know what this means, I have found 2 closed issues with the same error, but the code doesn't have similarities. I also found this post with the [same error for PythonOCC](https://www.freelists.org/post/nuitka-dev/Nuitka-is-not-including-PythonOCC-even-when-explicitly-told-to),  which I also use to import CAD models, but I didn't test it yet. So, I may get it again.

**Comment by JorjMcKie** [comment]
@math-artist - Trying to support you:
What do I need to install (related to vtk or otherwise) to reproduce your issue? On PyPI I see several vtk releated entries, so please point me to the right one.

**Comment by math-artist** [comment]
I used anaconda:
```
conda install -c conda-forge vtk
```
should default to 8.2.0 and install vtk with the Python wrappers

**Comment by math-artist** [comment]
This is the script example that I used for the previous test.

```
import vtk
colors = vtk.vtkNamedColors()
NUMBER_OF_SPHERES = 10


class MouseInteractorHighLightActor(vtk.vtkInteractorStyleTrackballCamera):

    def __init__(self, parent=None):
        self.AddObserver("LeftButtonPressEvent", self.leftButtonPressEvent)

        self.LastPickedActor = None
        self.LastPickedProperty = vtk.vtkProperty()

    def leftButtonPressEvent(self, obj, event):
        clickPos = self.GetInteractor().GetEventPosition()

        picker = vtk.vtkPropPicker()
        picker.Pick(clickPos[0], clickPos[1], 0, self.GetDefaultRenderer())

        # get the new
        self.NewPickedActor = picker.GetActor()

        # If something was selected
        if self.NewPickedActor:
            # If we picked something before, reset its property
            if self.LastPickedActor:
                self.LastPickedActor.GetProperty().DeepCopy(self.LastPickedProperty)

            # Save the property of the picked actor so that we can
            # restore it next time
            self.LastPickedProperty.DeepCopy(self.NewPickedActor.GetProperty())
            # Highlight the picked actor by changing its properties
            self.NewPickedActor.GetProperty().SetColor(colors.GetColor3d('Red'))
            self.NewPickedActor.GetProperty().SetDiffuse(1.0)
            self.NewPickedActor.GetProperty().SetSpecular(0.0)

            # save the last picked actor
            self.LastPickedActor = self.NewPickedActor

        self.OnLeftButtonDown()
        return


def main():
    # A renderer and render window
    renderer = vtk.vtkRenderer()
    renderer.SetBackground(colors.GetColor3d('SteelBlue'))

    renwin = vtk.vtkRenderWindow()
    renwin.AddRenderer(renderer)

    # An interactor
    interactor = vtk.vtkRenderWindowInteractor()
    interactor.SetRenderWindow(renwin)

    # add the custom style
    style = MouseInteractorHighLightActor()
    style.SetDefaultRenderer(renderer)
    interactor.SetInteractorStyle(style)

    # Add spheres to play with
    for i in range(NUMBER_OF_SPHERES):
        source = vtk.vtkSphereSource()

        # random position and radius
        x = vtk.vtkMath.Random(-5, 5)
        y = vtk.vtkMath.Random(-5, 5)
        z = vtk.vtkMath.Random(-5, 5)
        radius = vtk.vtkMath.Random(.5, 1.0)

        source.SetRadius(radius)
        source.SetCenter(x, y, z)
        source.SetPhiResolution(11)
        source.SetThetaResolution(21)

        mapper = vtk.vtkPolyDataMapper()
        mapper.SetInputConnection(source.GetOutputPort())
        actor = vtk.vtkActor()
        actor.SetMapper(mapper)

        r = vtk.vtkMath.Random(.4, 1.0)
        g = vtk.vtkMath.Random(.4, 1.0)
        b = vtk.vtkMath.Random(.4, 1.0)
        actor.GetProperty().SetDiffuseColor(r, g, b)
        actor.GetProperty().SetDiffuse(.8)
        actor.GetProperty().SetSpecular(.5)
        actor.GetProperty().SetSpecularColor(1.0, 1.0, 1.0)
        actor.GetProperty().SetSpecularPower(30.0)

        renderer.AddActor(actor)

    # Start
    interactor.Initialize()
    renwin.Render()
    interactor.Start()


if __name__ == '__main__':
    main()
```

**Comment by math-artist** [comment]
I swapped `--include-plugin-directory=VTKMODULES_PATH` for `--include-package=vtkmodules` and I was able to compile, but I have this error while running the .exe:

```Traceback (most recent call last):
  File "H:\OneDrive\FRAS\Dev\REFC\tests\evtk.dist\evtk.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "H:\OneDrive\FRAS\Dev\REFC\tests\evtk.dist\vtk.py", line 32, in <module vtk>
AttributeError: type object 'nuitka_module_loader' has no attribute 'exec_module'
```
This file is in the root of my /site-packages/ folder and uses importlib to import modules:
```
    import importlib.util
    # import vtkmodules.all
    all_spec = importlib.util.find_spec('vtkmodules.all')
    all_m = importlib.util.module_from_spec(all_spec)
    all_spec.loader.exec_module(all_m)
```
I have no experience with importlib so I don't know what's going on here.

**Comment by JorjMcKie** [comment]
My findings so far:

Installing vtk via pip in a vanilla Python 3.7 64bit environment (i.e. no conda) leads to vtk version 8.1.2. In this case, nuitka standalone compile works out of the box and leads to a **_working executable_** for your script. No changes of any sort required, not to Nuitka, nothing.

Installing vtk via conda, leads to vtk version 8.2.0, which unfortunately has a completely different internal structure:
* all vtk modules are now contained in ``lib/site-packages/vtkmodules``
* there is a ``vtk.py`` in ``lib/site-packages`` directory, which does a load of folder lookups and subsequent module loading. This module is the one behaving differently when compiled with Nuitka.

I will investigate  a little more and will get back to you.

**Comment by math-artist** [comment]
Thanks for your help. It is greatly appreciated.
I managed to hack my way into getting a working executable by ditching vtk.py and replace the import for `import vtkmodules.all as vtk` in my example. It works for a simple example, at least. Considering that I am using other Python projects with vtk dependencies, this won't do it, but at least we narrowed the problem to that import,ib usage. I also found that the line 
`all_spec = importlib.util.find_spec('vtkmodules.all')`
 doesn't return a spec. It probably cannot find the 'vtkmodules.all' argument.

**Comment by JorjMcKie** [comment]
@math-artist, @kayhayen 
I modified ``vtk.py``, the package loader for vtk version 8.2.0 to display some characteristics. Here is the output. The vtkmodules issue of @math-artist have been removed by including a respective implicit import, so this one is out of the way.

```
(base) D:\Jorj\Desktop\Develop\nuitka-conda>python vtk-test.py
dir(all_spec.loader): --------------------------------------------------
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__',
 '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__',
 '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__',
 '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__',
 '_cache_bytecode', 'contents', 'create_module', 'exec_module', 'get_code', 'get_data',
 'get_filename', 'get_resource_reader', 'get_source', 'is_package', 'is_resource',
 'load_module', 'name', 'open_resource', 'path', 'path_mtime', 'path_stats',
 'resource_path', 'set_data', 'source_to_code']

(base) D:\Jorj\Desktop\Develop\nuitka-conda>python -m nuitka --standalone vtk-test.py

(base) D:\Jorj\Desktop\Develop\nuitka-conda>cd vtk-test.dist

(base) D:\Jorj\Desktop\Develop\nuitka-conda\vtk-test.dist>vtk-test
dir(all_spec.loader): --------------------------------------------------
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__',
 '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__',
 '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
 '__sizeof__', '__str__', '__subclasshook__', 'find_module', 'find_spec', 'get_data',
 'is_package', 'iter_modules', 'load_module', 'module_repr']
Traceback (most recent call last):
  File "D:\Jorj\Desktop\Develop\nuitka-conda\vtk-test.dist\vtk-test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Jorj\Desktop\Develop\nuitka-conda\vtk-test.dist\vtk.py", line 35, in <module vtk>
AttributeError: type object 'nuitka_module_loader' has no attribute 'exec_module'

(base) D:\Jorj\Desktop\Develop\nuitka-conda\vtk-test.dist>
```

The failing object ``all_spec.loader`` is a member of ``all_spec`` defined in ``vtk.py`` like follows. As can be seen it becomes a completely different animal after compilation.
@kayhayen - any clue how to attack this further? Of course, a dynamic source code change of vtk.py via plugin would always be an option ... 🤔

```python
    # import vtkmodules.all
    all_spec = importlib.util.find_spec("vtkmodules.all")
    print("dir(all_spec.loader):", "-" * 50)  # debugging inserted by JM
    print(dir(all_spec.loader))  # debugging inserted by JM
    all_m = importlib.util.module_from_spec(all_spec)
    all_spec.loader.exec_module(all_m)
    ...
```

**Comment by JorjMcKie** [comment]
> I managed to hack my way into getting a working executable by ditching vtk.py and replace the import for `import vtkmodules.all as vtk` in my example. It works for a simple example, at least. Considering that I am using other Python projects with vtk dependencies, this won't do it, but at least we narrowed the problem to that importlib usage. I also found that the line
> `all_spec = importlib.util.find_spec('vtkmodules.all')`
> doesn't return a spec. It probably cannot find the module with the 'vtkmodules.all' argument.

Yes, exactly this is the point I was aiming at in my last comment to @kayhayen : I could write a plugin for vtk, which looks out for encountering ``import vtk`` statements. In this case, the plugin replaces those with your import statement - everything dynamically on the fly.
But, of course, only if the vtk version is high enough!

**Comment by math-artist** [comment]
Yes, and it also needs to import vtkmodules, to allow import of other modules not in vtkmodules.all (for example, QVTKRenderWindowInteractor). 
My guess is that the goal of vtk.py is get access to all the functions and classes of modules and submodules directly by doing `vtk.`

**Comment by JorjMcKie** [comment]
Allright then, so how would the correct import statement(s) have to look like in order to achieve the same effect?
I can start experimenting a little with a suitable plugin ...

**Comment by math-artist** [comment]
I don't know, I am still learning Python.
What I know is that the goal of the file is to get something with this logical:
`import vtkmodules and vtkmodules.all as vtk`

I am trying a few things now. the line 
`from vt.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor`
needs to work.

**Comment by JorjMcKie** [comment]
> I am trying a few things now. the line
from vt.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
needs to work.

I think you meant ``from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor``.
To me a solution might look like
```python
import vtmodules as vtk
vtk.all()
```

**Comment by math-artist** [comment]
I changed the __init__.py file in the vtkmodules root by adding this line:
`from vtkmodules.all import *`
Now, vtkmodules behaves like vtk and we can do
`import vtkmodules as vtk`

**Comment by math-artist** [comment]
> I think you meant from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

Yes, I was playing around trying import from a custom name

**Comment by JorjMcKie** [comment]
excellent - let me try developing a plugin which does these things. You can try it out, and we later include it in the Nuitka standard plugins.

**Comment by JorjMcKie** [comment]
[vtkmod.zip](https://github.com/Nuitka/Nuitka/files/3769634/vtkmod.zip)

Here is the promised user plugin. Also included a short description on how to use it. If you and I made no errors, your vtk modules should get compiled in standalone mode 😉

**Comment by math-artist** [comment]
```
File "H:\OneDrive\tests\vtk-nuitka\pvtest.dist\vtk.py", line 32, in <module vtk>
AttributeError: type object 'nuitka_module_loader' has no attribute 'exec_module'
```

@JorjMcKie -  I got the same error, maybe because the failing code inside vtk.py must be removed to avoid calling importlib, or because replacing `import vtk` for `import vtkmodules as vtk` still calls vtk.py somewhere.

Also, when looking at the plugin, it may not deal with `from vtk.*` statements. I am currently testing with new changes to the user plug-in.

**Comment by math-artist** [comment]
I have modded the plug-in and it does a better job, but now I have the same error, but narrowed it to these call from nuitka-hints:
```
Nuitka:WARNING:Not recursing to unused 'vtkmodules.qt.QVTKRenderWindowInteractor'.
Nuitka:WARNING:Not recursing to unused 'vtkmodules.util.numpy_support'.
```
I decided to make a small script with a [PyVista](https://github.com/pyvista/pyvista) dependency to test the robustness of the VTK plug-in.

nuitka-hints detected these 2 as unused, but they are used. One is a direct import:
`import vtk.util.numpy_support as nps`
the other is used during subclassing:
```
try:
    from PyQt5.QtCore import pyqtSignal, pyqtSlot, QObject, QTimer
    from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
... some code
class QtInteractor(QVTKRenderWindowInteractor, BasePlotter):
...
```
To reproduce:
`conda install pyvista`
`conda install pyqt`
This should also install Numpy and a few other modules.

This is the code for the new plug-in:
```
from logging import info
from nuitka.plugins.PluginBase import NuitkaPluginBase


class VTKPlugin(NuitkaPluginBase):

    plugin_name = __file__
    plugin_desc = "Required by the vtk package version 8.2.0+"

    def onModuleSourceCode(self, module_name, source_code):
        """ Insert an import statement to vtkmodules.__init__.py

        """
        source_lines = source_code.splitlines()
        if module_name == "vtkmodules":
            text = "from vtkmodules.all import *"
            source_lines.append(text)
            info(self.plugin_name + " inserted import of vtkmodules.all")
            return "\n".join(source_lines)
        for i, line in enumerate(source_lines):
            if "import vtk" in line:
                if line.endswith("import vtk"):
                    source_lines[i] = "import vtkmodules as vtk"
                elif "import vtk " in line:
                    source_lines[i].replace("import vtk as", "import vtkmodules as")
                    source_lines[i].replace("import vtk ", "import vtkmodules as vtk")
                elif "import vtk." in line:
                    source_lines[i].replace("import vtk.", "import vtkmodules.")
            elif "from vtk" in line:
                source_lines[i].replace("from vtk.", "from vtkmodules.")
                source_lines[i].replace("from vtk ", "from vtkmodules ")
        return "\n".join(source_lines)
```

And finally, the script to compile (direct example from pyvista):
```
import sys

from PyQt5 import Qt
import numpy as np

import pyvista as pv


class MainWindow(Qt.QMainWindow):

    def __init__(self, parent=None, show=True):
        Qt.QMainWindow.__init__(self, parent)

        # create the frame
        self.frame = Qt.QFrame()
        vlayout = Qt.QVBoxLayout()

        # add the pyvista interactor object
        self.vtk_widget = pv.QtInteractor(self.frame)
        vlayout.addWidget(self.vtk_widget)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        # simple menu to demo functions
        mainMenu = self.menuBar()
        fileMenu = mainMenu.addMenu('File')
        exitButton = Qt.QAction('Exit', self)
        exitButton.setShortcut('Ctrl+Q')
        exitButton.triggered.connect(self.close)
        fileMenu.addAction(exitButton)

        # allow adding a sphere
        meshMenu = mainMenu.addMenu('Mesh')
        self.add_sphere_action = Qt.QAction('Add Sphere', self)
        self.add_sphere_action.triggered.connect(self.add_sphere)
        meshMenu.addAction(self.add_sphere_action)

        if show:
            self.show()

    def add_sphere(self):
        """ add a sphere to the pyqt frame """
        sphere = pv.Sphere()
        self.vtk_widget.add_mesh(sphere)
        self.vtk_widget.reset_camera()


if __name__ == '__main__':
    app = Qt.QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
```

**Comment by JorjMcKie** [comment]
Ok, I see.
And what is your current status with all this? Do your scripts work?
For also supporting numpy, Qt and what not, of course additional plugins are required.
These should be detected and auto-included by hinted compilation.

**Comment by JorjMcKie** [comment]
We may need to add more implicit imports for vtk, and / or modify the vtkmod.py a bit more to be more relaxed with additional vtk components - this depends on messages you see during the compile ...

**Comment by math-artist** [comment]
Fundamental mistake found with wrong usage of .replace. Compiling now...

**Comment by math-artist** [comment]
```
(nuitka) H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist>pvtest
Traceback (most recent call last):
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pvtest.py", line 6, in <module>
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pyvista\__init__.py", line 3, in <module pyvista>
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pyvista\plotting\__init__.py", line 4, in <module pyvista.plotting>
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pyvista\plotting\helpers.py", line 7, in <module pyvista.plotting.helpers>
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pyvista\utilities\__init__.py", line 8, in <module pyvista.utilities>
  File "H:\OneDrive\FRAS\Dev\REFC\tests\vtk-nuitka\pvtest.dist\pyvista\utilities\utilities.py", line 12, in <module pyvista.utilities.utilities>
ModuleNotFoundError: No module named 'vtkmodules.util.numpy_support'
```
How do you force the use of modules with nuitka-hints? I have tried the options --include-plugin-directory, --include-plugin-files without success.

**Comment by math-artist** [comment]
What is the difference between the first and second item in the json calls?
I can see in hinted-mods.py that you only make use of the firts one, and you check if it is contained in files.
I have calls like this:
["vtk.util.numpy_support", "vtkmodules.util.numpy_support"]
then there is a check to see if the first item is in files. It contains the second item refering to vtkmodules... but not the first item. Would it make sense to make a check for that second item?

**Comment by JorjMcKie** [comment]
Uff, this is more tricky than I expected. Here is my new version of the user plugin vtkmod.py and of the ImplicitImports.py.
I ended up following this appoach:
1. Add several implicit imports for vtk. The rest is implemented in vtkmod.py.
2. Append your import statement to the __init__.py of vtkmodules.
3. Completely replace the vtk.py module by a small number of statements.
4. Points 2 and 3 take care of everything imported from vtkmodules root folder.
5. Replace every reference to ``vtk.<subfolder>`` by ``vtkmodules.<subfolder>`` everywhere outside of the vtkmodules package itself. ``<subfolder>`` are subfolders like ``qt``, ``gtk``, etc.

With the above I generated a working exe of your pyvista example.
Please also try it out and let me know where the next issues are popping up ...
[vtkmod.zip](https://github.com/Nuitka/Nuitka/files/3775007/vtkmod.zip)

**Comment by JorjMcKie** [comment]
> What is the difference between the first and second item in the json calls?
> I can see in hinted-mods.py that you only make use of the firts one, and you check if it is contained in files.
> I have calls like this:
> ["vtk.util.numpy_support", "vtkmodules.util.numpy_support"]
> then there is a check to see if the first item is in files. It contains the second item refering to vtkmodules... but not the first item. Would it make sense to make a check for that second item?

The basic motivation for hinted compilation is to restrict stuff becoming part of the ``dist`` to a minimum. So the policy is: "entry prohibited without explicit permission" if you will.
Therefore the ``--recurse-none``. The members of the ``files`` item of the JSON dictionary are all included via ``--recurse-to=...``.
The items of the ``calls`` key are used as follows:
* When Nuitka asks if a module may be included, then this is checked against the ``item[0]``. That check is actually a bit more complex as you may have noticed. E.g. all other loaded plugins (among them ``ImplicitImports.py``) are also asked before something is actually dropped. If a plugin votes for keeping a module, you will see an appropriate "keep" message (but not if voted by implicit imports).
* ``item[1]`` of the ``calls`` members are not used at all at this point of time. They are the same as the ``files`` entries. Their meaning is "the import of item[0] points to item[1]". I just didn't bother deleting them again ...

**Comment by math-artist** [comment]
I was able to compile VTK and pyvista with your last plugin. Great job!!!
I will certainly test it more in the coming weeks.
Thank you for the time you spent on this to make this work!

**Comment by JorjMcKie** [comment]
You are very welcome, I am glad it works.

The question is: should I turn this user plugin into a new standard plugin now? This would make it reachable via (example) ``--enable-plugin=vtkmodules``.
Together with some minor adjustments to hinted compilation, this would lead to a fully automated invocation of the plugin logic whenever the ``hinted-mods.py`` determines that ``vtkmodules`` is being used by some app.
Or wait a bit longer until you drop me a note that some level of confidence is achieved ...

**Comment by math-artist** [comment]
@JorjMcKie 
I am now working on compiling the real project, and because of a few strange issues that I had, I chose to update all files to their latest version, including your latest versions of ImplicitImports.py and DataFileCollectorPlugin.py (from your recommendation in another issue).

Now, the previous vtk example that was running fine fails at runtime. I get:
`ModuleNotFoundError: No module named 'vtk'` again.
I have compared my older ImplicitImports.py with the latest and both are equivalent for the vtk section. I am using the same vtkmod.py plugin.

The main reason why I updated is because a line that worked fine in my pyvista example failed in my program at runtime.
`from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor` was not able to find QVTKRenderWindowInteractor in my project, but it was ok in the pyvista test, which calls the import the exact same way. Then I tried to change the import order and add other imports to reflect exactly the pyvista file that was working and I got a few segmentation faults at random numpy and pandas modules. In fact, I just ran the exact same command twice in a row by mistake without changing anything and it compiled the first time but I got a seg fault the second time.

Could you check on your side if the vtk example that you ran still works with the new changes that you have done? Thanks! And if you know what I am doing wrong to get all these seg faults, it would be greatly appreciated.

**Comment by math-artist** [comment]
I was able to solve that problem with a rollback of the previous versions and multiple trials and errors.

I'd like to learn how to fish. Is there a cheat sheet to solve the common problems? I still have issues (smaller ones) and I would really like to learn why what I did worked and why the code I had earlier didn't work.

import order:

It seems that it does matter for Nuitka (or maybe only the hinted compilation) while it doesn't for CPython.  I have added a considerable amount of unused PyQt5 imports before
`from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor`
and for some reason it works. Why?

**Comment by JorjMcKie** [comment]
I am not sure about PyQt myself I must confess.
What I know is that the respctive plugin has a number of options which control the subset of Qt modules to include.
When I tested your material, I found that those previous problems had nothing to do with Qt however ... except, that I had to declare several implicit imports as optional in ``ImplicitImports.py``.
This PyQt monster obviously comes in so many different configurations that you never can be certain to have enumerated them all.

Actually you should no longer need the user plugin I wrote for you: @kayhayen is preparing a new release (or has already done that) which contains all the modifications contained in that user module.
Just please make sure you are using that newest version.

Why is this so error prone in your case? Well, the main reason is that the internal architecture of vtk has changed significantly for the current version. In earlier times, there was a real package ``vtk`` - now there is one called ``vtkmodules``, and some ``vtk.py`` script in the ``site-packages`` root is emulating a backwards-compatible situation for older application code, which still does an ``import vtk``.

So I'm afraid there is not much to learn here. The trick is just to configure the plugins so that they can cope with both situations.

**Comment by math-artist** [comment]
ok, thanks @JorjMcKie. This issue is solved for now.

 I have for the first time a running app of my project, and so far I found only one small remaining bug regarding matplotlib. I will open another thread to keep that one clean.

**Comment by math-artist** [comment]
I don't want to double post but I should have posted the information in this thread, since it is the same issue. 
https://github.com/Nuitka/NUITKA-Utilities/issues/44
Additional files are available to reproduce the issue in that thread.

The vtk plugin is not official, but it was working fine in November 2019 on the latest Nuitka dev version to make hinted compilation possible with both vtk and pyvista. It would be very nice to have it official and support those projects.

I am currently trying to make it work now with the latest official version of Nuitka and hinted compilation, but the same plugin is not working anymore. 

I suspect a change in how nuitka-hints is handling the filtering of module names in the json file, because the plugin is supposed to replace the source code in vtk.py, but it never does. When importing `import vtk`, vtk imports vtkmodules, then does this:     `all_m.__path__ = vtkmodules_m.__path__`.

The problem now is that even after running the vtk example containing the line `import vtk`, there is no reference to vtk in the json, only to vtkmodules. So it doesn't include the file vtk.py as source code and can't modify it.

Does anyone know how this issue could be solved?

**Comment by math-artist** [comment]
Update: I found the commit and line causing the issue: 

https://github.com/Nuitka/NUITKA-Utilities/issues/44#issuecomment-659002076

Anybody can help at this stage? It is a bit over my head and I don't want to break something.
