### ISSUE TITLE
Issue with Trio and Nuitka

### ISSUE THREAD

**Issue by ItWasAllIntended** [Nuitka/Nuitka#561]
Nuitka appears to be incompatible with the latest version of Trio. As far as I can tell, this is unrelated to #410. This happens with all Trio programs I've tested, the simplest being:
```py
import trio

async def main():
    print("Hello")

trio.run(main)
```
This runs without issue regularly but produces the traceback
```Traceback (most recent call last):
  File "C:\Users\sethw\PycharmProjects\PyCom\venv\lib\site-packages\trio\_core\_run.py", line 1769, in run
    run_impl(runner, async_fn, args)
  File "C:\Users\sethw\PycharmProjects\PyCom\venv\lib\site-packages\trio\_core\_run.py", line 1803, in run_impl
    runner.init_task = runner.spawn_impl(
  File "C:\Users\sethw\PycharmProjects\PyCom\venv\lib\site-packages\trio\_core\_run.py", line 1351, in spawn_impl
    coro.cr_frame.f_locals.setdefault(
AttributeError: 'NoneType' object has no attribute 'f_locals'
```
I've tested this on Python 3.7 & 3.8 and the latest Nuitka from PyPi & an install from the `factory` branch, all of which produce the same traceback

**Comment by JorjMcKie** [comment]
@kayhayen - I am not looking into this more closely.

The reason why this does not yet work is here:

```
def f(x):
    print(x)


async def make(f):
    return await f


af = make(f)

print("af.frame =", af.cr_frame)
```
Running this interpreted yields
```
af.frame = <frame at 0x00000241463E2A28, file 'test.py', line 5, code make>
sys:1: RuntimeWarning: coroutine 'make' was never awaited
```

Whereas in standalone we get:
```
af.frame = None
```
This makes trio fail.

**Comment by kayhayen** [comment]
Nuitka delays frame creation until usage. There may not ever be a usage after all. Therefore it is `None`. We could in theory become good enough to create it once its looked at though. That is of dubious help though.

Next the usage of `.setdefaults` on `f_locals` which might be a write (not seeing what value though) is not going to impress it a lot either. We could have a look at the source code, and what it tries to do there, and possibly engage with upstream there. If it expects to have an impact on program behavior that will be bad.

Integrating with a locals dictionary is not going to fly well. But I am also confused, because I think that Python3 should not be using that locals dictionary in the normal case when written to, but maybe I misremember, so maybe it's nothing but unnecessary to do any write.

**Comment by JorjMcKie** [comment]
I just made the reference to cr_frame conditional at just 3 places, which is, I put the references inside a try-except clause.
Then that super simple example from @ItWasAllIntended works.
I don't know how far this is going to take us.

For further check, @ItWasAllIntended would you have something you would like seeing working?

**Comment by arkanoid87** [comment]
I'm stuck on the same error with trio master HEAD and nuitka develop HEAD on my project using Python 3.7.4 in venv and same minimal code

```
import trio

async def main():
    print("Hello")

trio.run(main)
```

**Comment by ItWasAllIntended** [comment]
> For further check, @ItWasAllIntended would you have something you would like seeing working?
Sorry for the late reply. Github notifications seems to have failed me. As for what you asked, as all usage of Trio doesn't seem to work with Nuitka I'd like to see it fixed :P
Obviously, the fix for this issue seems to raise some other problems and I appreciate the effort put into this project and hopefully this fix.
It may be worth communication with the maintainer of Trio to see if you could sidestep the issue in any way? Anyhow, thanks for the support

**Comment by remdragon** [comment]
I am also experiencing this issue.

Python 3.8.5
Nuitka 0.6.10rc3
Trio 0.16.0

https://github.com/python-trio/trio/issues/1752

**Comment by oremanj** [comment]
Trio developer here -- please feel free to file issues on our tracker when you run into something we're doing that's confusing, as I didn't learn about the Nuitka integration challenges until just now.

@kayhayen 

> Next the usage of .setdefaults on f_locals which might be a write (not seeing what value though) is not going to impress it a lot either. We could have a look at the source code, and what it tries to do there, and possibly engage with upstream there. If it expects to have an impact on program behavior that will be bad.
>
> Integrating with a locals dictionary is not going to fly well. But I am also confused, because I think that Python3 should not be using that locals dictionary in the normal case when written to, but maybe I misremember, so maybe it's nothing but unnecessary to do any write.

We're using the locals dictionary as a place to stash some information about whether a frame can safely be interrupted by KeyboardInterrupt at any point, or whether it needs to be delayed because we're in the middle of some sensitive operation. Trio installs a SIGINT handler that looks at these `f_locals` entries on the stack and decides how to respond to the SIGINT accordingly. See https://vorpus.org/blog/control-c-handling-in-python-and-trio/ for more details. Of course writing to `f_locals` doesn't change the values that will be read from local variables in most cases, but here it doesn't need to -- `f_locals` is used because it's (AFAICT) the only place to store any kind of custom state on a frame object, and the frame objects are the only thing the signal handler has access to in making its decision about how to handle KeyboardInterrupt.

**Comment by kayhayen** [comment]
@oremanj sorry for the delay in responding, I had more severe issues with Nuitka to deal with, but now I am getting to this one as well.

Let me try and state what you said or rather, what I understood. That will help to clarify.

a) So generator objects and frames do not allow storage outside of themselves. I checked that coroutine objects wouldn't do that, and that's correct.
b) Therefore you extend it with an attribute, that you also want to look up if it's there.
c) You do that with the frame locals, which is relatively harmless to use. Extra elements are readily ignored in CPython.
c) In CPython this access to `.f_locals` on the frame causes a new dictionary to be allocated, just to look at it. Bad for performance.
d) You only (?) do that check though, when CTRLC-C is pressed, so it doesn't really matter. But what triggers the `setdefault` then, I would think you only do stuff when there is sensitive code running.
e) I have doubts if the reproducer is not too simple for the above to be all true, but maybe `trio.run` does stuff it considers itself to be uninteruptible? Which would be OK by me of course.

Can you confirm or deny these?

**Comment by kayhayen** [comment]
In trio, checking the `setdefault`, I found this code:

```
        if not hasattr(coro, "cr_frame"):
            # This async function is implemented in C or Cython
            async def python_wrapper(orig_coro):
                return await orig_coro

            coro = python_wrapper(coro)
```

Now, that is of course a easy cop out, I understand this injects a wrapping function. Unfortunately Nuitka will compile it, and then it will fail to your code. It's really time for Nuitka to learn how to annotate functions that it should keep as standard functions with bytecode. Using ```exec()``` around it (and having it as a global variable while at it, as creating a local function that uses no context is wasting time) would make it work right now, but not if  it becomes statically optimized in the future of Nuitka.

What's your thought on that?

**Comment by kayhayen** [comment]
@oremanj you never responded to my question, do you see a way to handle Nuitka compiled functions better?

**Comment by oremanj** [comment]
Sorry for the delay, thanks for the ping!

(a-c) are correct.

(d): We set the state in the root function of every new task. In general, user tasks are interruptible at any bytecode position (so you can interrupt an infinite loop, which provides better developer experience) while Trio internal tasks are only interruptible at specified points (so that it's easier for them to maintain their invariants).

(e) A simple call to `trio.run()` will create at least one of both kinds of tasks and will thus involve an `f_locals` assignment.

Trio would probably be happy to apply a Nuitka-specific workaround (to keep the wrapper/trampoline function in Python) if there's a way to do it without importing Nuitka. We're also hoping at some point to move away from `f_locals` and towards a model where interruptibility state is associated with code object identities. Maybe that will also be a problem for Nuitka, if compiled functions don't have code objects? But at least that's just a reference rather than a whole dictionary you have to materialize.

**Comment by kayhayen** [comment]
@oremanj Nuitka has code objects, but the bytecode attribute is empty, but they have names, etc. and are unqiue for given source locations. The delayed creation of frames is still a problem though. I guess, at the core, you would be fine, if Nuitka would create a frame object, once `cr_frame` is accessed. Also, code objects don't identify generator instances, so maybe that plan has no merrits then?

Right now, the C code of the compiled generator, function, coroutine, etc. owns the frame object, and there is I think only one instance, where it's created by the code that owns them, namely when a non-started generator wants to throw a traceback.

This is from there:
```
        if (exception_tb == NULL) {
            // TODO: Our compiled objects really need a way to store common
            // stuff in a "shared" part across all instances, and outside of
            // run time, so we could reuse this.
            struct Nuitka_FrameObject *frame = MAKE_FUNCTION_FRAME(generator->m_code_object, generator->m_module, 0);
            exception_tb = MAKE_TRACEBACK(frame, generator->m_code_object->co_firstlineno);
            Py_DECREF(frame);
        }
```

So, given a refactoring of Nuitka, where the except frame and an initial frame would blend into another would make Trio work if it doesn't discriminate against compiled frames, which it doesn't I believe. So if this changed:

```
static PyObject *Nuitka_Coroutine_get_frame(struct Nuitka_CoroutineObject *coroutine) {
    CHECK_OBJECT(coroutine);
    CHECK_OBJECT_X(coroutine->m_frame);

    if (coroutine->m_frame) {
        Py_INCREF(coroutine->m_frame);
        return (PyObject *)coroutine->m_frame;
    } else {
        Py_INCREF(Py_None);
        return Py_None;
    }
}
```

and contained similar code that avoids a `None` return, things would look nice. Nuitka attaches C types to frames, I need to check how delicate this will be to change, but it may be relatively simple actually.

**Comment by sethwheway** [comment]
i can confirm this is still an issue with the latest nuitka, trio and python 3.9.6

**Comment by kayhayen** [comment]
I don't have the time to focus on this right now unless somebody commercial needs it, this is not happening in the near future.

**Comment by JamesOldfield** [comment]
As I just noted over on python-trio/trio#1752, it is possible to use Trio and Nuitka togetherr by hacking just a few lines of code in Trio. It does disable Trio's careful handling of `KeyboardInterupt` though, which could be a problem in some applications.

It would be possible to make a Nuitka plugin to address this but I think it would be very fragile to small changes to the Trio source code, because one of the changes is to comment out a single line of code within a Trio function.

So for those (inlcuding me) that can do without Trio's careful `KeyboardInterupt`, and stomach a little hacking whenever Trio is updated, this issue is possible to work around.

**Comment by kayhayen** [comment]
@JamesOldfield I would love to see such a plugin be created, just make the PR... you can use the anti-bloat engine if you want, should make things relatively easy, and I could add something that makes it fail it replacement fails.

**Comment by kayhayen** [comment]
Support for newest trio and the plugin migration to yaml is part of the hotfix release 1.7.4 that I just made.
