### ISSUE TITLE
ModuleNotFoundError skimage.util.compare

### ISSUE THREAD

**Issue by cubic-inf** [Nuitka/Nuitka#567]
0.6.6rc7
Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\Username\AppData\Local\Continuum\anaconda3\python.exe
OS: Windows
Arch: x86_64

Development version of Nuitka installed using pip; everything else through conda.

This is a continuation from https://github.com/Nuitka/Nuitka/issues/565. 

Script, test_skimage.py:
```
# -*- coding: utf-8 -*-

import skimage.io

# skimage.io.use_plugin('pil', 'imread')
image = skimage.io.imread("C:/Users/Username/Desktop/folder/hsv-compose.ico")

print(image)
```

Compile:
```
>python nuitka-hints.py test_skimage.py
NUITKA is compiling 'test_skimage.py' with these options:
 --standalone
 --remove-output
 --recurse-none

Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--enable-plugin=numpy=matplotlib,scipy
Nuitka:INFO:--enable-plugin=multiprocessing
Nuitka:INFO:--recurse-to for 754 imported modules.
Nuitka:INFO:
Nuitka:INFO:Injecting plug-in based pre load code for module 'multiprocessing':
Nuitka:INFO:    Monkey patching "multiprocessing" load environment.
Nuitka:INFO:Injecting plug-in based post load code for module 'multiprocessing':
Nuitka:INFO:    Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO:drop site
Nuitka:INFO:keep multiprocessing (plugin 'multiprocessing')
Nuitka:INFO:keep multiprocessing.reduction (plugin 'multiprocessing')
Nuitka:INFO:drop skimage.util.compare (in skimage.util)
Nuitka:INFO:drop skimage.exposure.histogram_matching (in skimage.exposure)
Nuitka:INFO:drop psutil
Nuitka:INFO:drop skimage.feature (in skimage)
Nuitka:INFO:drop skimage.filters._multiotsu (in skimage.filters)
Nuitka:INFO:drop matplotlib.pyplot (in matplotlib)
Nuitka:INFO:drop matplotlib.style.core (in matplotlib.style)
Nuitka:INFO:drop IPython
Nuitka:INFO:drop IPython.core (in IPython)
Nuitka:INFO:drop matplotlib.figure (in matplotlib)
Nuitka:INFO:drop matplotlib._png (in matplotlib)
Nuitka:INFO:drop matplotlib.patheffects (in matplotlib)
Nuitka:INFO:drop dummy_threading
Nuitka:INFO:drop pdb
Nuitka:INFO:drop matplotlib.projections (in matplotlib)
Nuitka:INFO:drop PIL.PyAccess (in PIL)
Nuitka:INFO:drop PIL.ImageFilter (in PIL)
Nuitka:INFO:drop PIL.ImageQt (in PIL)
Nuitka:INFO:drop PIL.ImageShow (in PIL)
Nuitka:INFO:drop colorsys
Nuitka:INFO:drop _cffi_backend
Nuitka:INFO:drop cffi.cparser (in cffi)
Nuitka:INFO:drop cffi.verifier (in cffi)
Nuitka:INFO:drop sysconfig
Nuitka:INFO:drop cffi.pkgconfig (in cffi)
Nuitka:INFO:drop distutils.dir_util (in distutils)
Nuitka:INFO:drop cffi.recompiler (in cffi)
Nuitka:INFO:drop distutils.sysconfig (in distutils)
Nuitka:INFO:drop distutils.fancy_getopt (in distutils)
Nuitka:INFO:drop distutils.errors (in distutils)
Nuitka:INFO:drop distutils.util (in distutils)
Nuitka:INFO:drop distutils.dist (in distutils)
Nuitka:INFO:drop distutils.core (in distutils)
Nuitka:INFO:drop setuptools
Nuitka:INFO:drop setuptools.command (in setuptools)
Nuitka:INFO:drop setuptools.command.egg_info (in setuptools.command)
Nuitka:INFO:drop setuptools.command.develop (in setuptools.command)
Nuitka:INFO:drop distutils.ccompiler (in distutils)
Nuitka:INFO:drop setuptools.command.bdist_rpm (in setuptools.command)
Nuitka:INFO:drop distutils.command.bdist_rpm (in distutils.command)
Nuitka:INFO:drop setuptools.command.install (in setuptools.command)
Nuitka:INFO:drop distutils.command.install (in distutils.command)
Nuitka:INFO:drop distutils.file_util (in distutils)
Nuitka:INFO:drop distutils.command.install_headers (in distutils.command)
Nuitka:INFO:drop distutils.command.install_data (in distutils.command)
Nuitka:INFO:drop setuptools.command.sdist (in setuptools.command)
Nuitka:INFO:drop distutils.command.sdist (in distutils.command)
Nuitka:INFO:drop distutils.command.build_scripts (in distutils.command)
Nuitka:INFO:drop shlex
Nuitka:INFO:drop distutils.command (in distutils)
Nuitka:INFO:drop distutils.dep_util (in distutils)
Nuitka:INFO:drop unittest
Nuitka:INFO:drop doctest
Nuitka:INFO:drop unittest.case (in unittest)
Nuitka:INFO:drop win32pdh
Nuitka:INFO:drop _decimal
Nuitka:INFO:drop _pydecimal
Nuitka:INFO:drop imp
Nuitka:INFO:drop pydoc
Nuitka:INFO:drop optparse
Nuitka:INFO:drop fileinput
Nuitka:INFO:drop distutils.command.build_clib (in distutils.command)
Nuitka:INFO:drop distutils.command.build_ext (in distutils.command)
Nuitka:INFO:drop distutils.command.build_py (in distutils.command)
Nuitka:INFO:drop distutils.command.build (in distutils.command)
Nuitka:INFO:drop distutils.command.config (in distutils.command)
Nuitka:INFO:drop distutils.cygwinccompiler (in distutils)
Nuitka:INFO:drop distutils.unixccompiler (in distutils)
Nuitka:INFO:drop distutils.msvccompiler (in distutils)
Nuitka:INFO:drop distutils.extension (in distutils)
Nuitka:INFO:drop pipes
Nuitka:INFO:drop curses
Nuitka:INFO:drop distutils.log (in distutils)
Nuitka:INFO:keep multiprocessing.pool (plugin 'multiprocessing')
Nuitka:INFO:drop matplotlib.hatch (in matplotlib)
Nuitka:INFO:drop matplotlib.backends (in matplotlib)
Nuitka:INFO:keep scipy.sparse.csgraph._validation (plugin 'numpy')
Nuitka:INFO:drop scipy.sparse.spfuncs (in scipy.sparse)
Nuitka:INFO:drop skimage.metrics._structural_similarity (in skimage.metrics)
Nuitka:INFO:drop skimage.metrics.simple_metrics (in skimage.metrics)
Nuitka:INFO:drop skimage.morphology.convex_hull (in skimage.morphology)
Nuitka:INFO:drop scipy.constants (in scipy)
Nuitka:INFO:drop skimage._shared.fft (in skimage._shared)
Nuitka:INFO:drop skimage.feature.peak (in skimage.feature)
Nuitka:INFO:drop _collections_abc
Nuitka:INFO:drop tornado
Nuitka:INFO:drop dask.dot (in dask)
Nuitka:INFO:drop pandas
Nuitka:INFO:drop cloudpickle.cloudpickle_fast (in cloudpickle)
Nuitka:INFO:drop dask.dataframe.io.demo (in dask.dataframe.io)
Nuitka:INFO:drop dask.bag (in dask)
Nuitka:INFO:drop scipy.linalg._matfuncs_inv_ssq (in scipy.linalg)
Nuitka:INFO:drop dask.array.svg (in dask.array)
Nuitka:INFO:drop dask.dataframe (in dask)
Nuitka:INFO:drop dask.bytes.core (in dask.bytes)
Nuitka:INFO:drop h5py
Nuitka:INFO:drop backports
Nuitka:INFO:drop tkinter
Nuitka:INFO:drop _tkinter
Nuitka:INFO:drop qtpy.QtWidgets (in qtpy)
Nuitka:INFO:drop qtpy.QtGui (in qtpy)
Nuitka:INFO:drop qtpy
Nuitka:INFO:drop skimage.io._plugins.skivi (in skimage.io._plugins)
Nuitka:INFO:keep mpl_toolkits.axes_grid1 (plugin 'numpy')
Nuitka:INFO:keep mpl_toolkits.axes_grid1.axes_size (plugin 'numpy')
Nuitka:INFO:keep mpl_toolkits.axes_grid1.axes_divider (plugin 'numpy')
Nuitka:INFO:keep mpl_toolkits.axes_grid1.axes_grid (plugin 'numpy')
Nuitka:INFO:keep mpl_toolkits.axes_grid1.parasite_axes (plugin 'numpy')
Nuitka:INFO:keep mpl_toolkits.axes_grid1.mpl_axes (plugin 'numpy')
Nuitka:INFO:drop dateutil.zoneinfo (in dateutil)
Nuitka:INFO:drop dateutil.easter (in dateutil)
Nuitka:INFO:drop matplotlib._tri (in matplotlib)
Nuitka:INFO:drop matplotlib._qhull (in matplotlib)
Nuitka:INFO:drop matplotlib._contour (in matplotlib)
Nuitka:INFO:keep matplotlib.backends.backend_agg (plugin 'numpy')
Nuitka:INFO:drop matplotlib.backends._backend_agg (in matplotlib.backends)
Nuitka:INFO:drop matplotlib.backends._tkagg (in matplotlib.backends)
Nuitka:INFO:drop matplotlib.backends.backend_tkagg (in matplotlib.backends)
Nuitka:INFO:keep mpl_toolkits.axes_grid1.colorbar (plugin 'numpy')
Nuitka:INFO:drop PIL.ImageTk (in PIL)
Nuitka:INFO:drop distutils.spawn (in distutils)
Nuitka:INFO:drop imageio.plugins._swf (in imageio.plugins)
Nuitka:INFO:drop imageio.plugins._dicom (in imageio.plugins)
Nuitka:INFO:drop imageio.plugins._bsdf (in imageio.plugins)
Nuitka:INFO:drop PIL.ImageGrab (in PIL)
Nuitka:INFO:drop PIL.ExifTags (in PIL)
Nuitka:INFO:drop concurrent.futures (in concurrent)
Nuitka:INFO:drop imageio.plugins._tifffile (in imageio.plugins)
Nuitka:INFO:keep multiprocessing.spawn (plugin 'multiprocessing')
Nuitka:WARNING:Not recursing to unused '__future__'.
Nuitka:WARNING:Not recursing to unused '_bootlocale'.
Nuitka:WARNING:Not recursing to unused '_compat_pickle'.
Nuitka:WARNING:Not recursing to unused '_compression'.
Nuitka:WARNING:Not recursing to unused '_weakrefset'.
Nuitka:WARNING:Not recursing to unused 'argparse'.
Nuitka:WARNING:Not recursing to unused 'ctypes._endian'.
Nuitka:WARNING:Not recursing to unused 'email'.
Nuitka:WARNING:Not recursing to unused 'email._encoded_words'.
Nuitka:WARNING:Not recursing to unused 'email._parseaddr'.
Nuitka:WARNING:Not recursing to unused 'email._policybase'.
Nuitka:WARNING:Not recursing to unused 'email.charset'.
Nuitka:WARNING:Not recursing to unused 'email.encoders'.
Nuitka:WARNING:Not recursing to unused 'email.errors'.
Nuitka:WARNING:Not recursing to unused 'email.feedparser'.
Nuitka:WARNING:Not recursing to unused 'email.iterators'.
Nuitka:WARNING:Not recursing to unused 'email.utils'.
Nuitka:WARNING:Not recursing to unused 'encodings'.
Nuitka:WARNING:Not recursing to unused 'encodings.raw_unicode_escape'.
Nuitka:WARNING:Not recursing to unused 'genericpath'.
Nuitka:WARNING:Not recursing to unused 'gettext'.
Nuitka:WARNING:Not recursing to unused 'http'.
Nuitka:WARNING:Not recursing to unused 'json.decoder'.
Nuitka:WARNING:Not recursing to unused 'json.encoder'.
Nuitka:WARNING:Not recursing to unused 'linecache'.
Nuitka:WARNING:Not recursing to unused 'nturl2path'.
Nuitka:WARNING:Not recursing to unused 'posixpath'.
Nuitka:WARNING:Not recursing to unused 'quopri'.
Nuitka:WARNING:Not recursing to unused 'selectors'.
Nuitka:WARNING:Not recursing to unused 'skimage._shared._geometry'.
Nuitka:WARNING:Not recursing to unused 'skimage.draw'.
Nuitka:WARNING:Not recursing to unused 'skimage.draw._draw'.
Nuitka:WARNING:Not recursing to unused 'skimage.draw._random_shapes'.
Nuitka:WARNING:Not recursing to unused 'skimage.draw.draw'.
Nuitka:WARNING:Not recursing to unused 'skimage.draw.draw3d'.
Nuitka:WARNING:Not recursing to unused 'skimage.transform.seam_carving'.
Nuitka:WARNING:Not recursing to unused 'ssl'.
Nuitka:WARNING:Not recursing to unused 'stat'.
Nuitka:WARNING:Not recursing to unused 'token'.
Nuitka:WARNING:Not recursing to unused 'urllib.response'.
Nuitka:WARNING:Not recursing to unused 'uu'.
Nuitka:WARNING:Not recursing to unused 'xml.etree.ElementTree'.

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:\Users\Username\AppData\Local\Continuum\anaconda3\lib\site-packages\nuitka\build\SingleExe.scons", line 506, in createEnvironment
Nuitka:INFO:Copied 43 files from 'numpy' installation.
Nuitka:INFO:Compile time 28 minutes.
```

I copy dask/dask.yaml then run the program:
```
Traceback (most recent call last):
  File "C:\Users\Username\Desktop\folder\test_skimage.dist\test_skimage.py", line 3, in <module>
  File "C:\Users\Username\Desktop\folder\test_skimage.dist\skimage\__init__.py", line 125, in <module skimage>
  File "C:\Users\Username\Desktop\folder\test_skimage.dist\skimage\util\__init__.py", line 9, in <module skimage.util>
ModuleNotFoundError: No module named 'skimage.util.compare'
```
I wonder if I should do something with `--include-plugin-files=`, but I don't know how it works.

Edit note: 
I now attempted this using an absolute directory, since it wasn't matching the file otherwise
`python nuitka-hints.py --include-plugin-files=C:\Users\Username\AppData\Local\Continuum\anaconda3\lib\site-packages\skimage\util\compare.py test_skimage.py`
It didn't work though.

**Comment by JorjMcKie** [comment]
> I wonder if I should do something with --include-plugin-files=, but I don't know how it works.

I think the solution simply should be including ``dask.yaml`` in the data copy plugin ...
currently testing this

**Comment by JorjMcKie** [comment]
Here is a new version of ``DataFileCollectorPlugin.py``. As before to copied over in folder ``... \site-packages\nuitka\plugins\standard``:
[DataFileCollectorPlugin.zip](https://github.com/Nuitka/Nuitka/files/3814020/DataFileCollectorPlugin.zip)

With this modification, file ``dask.yaml`` will automatically land in the ``.dist`` folder of your compilation.

**Comment by cubic-inf** [comment]
You're doing a lot. This is great!
This has solved the dask.yaml issue for me, but the skimage.util.compare problem persists.

**Comment by JorjMcKie** [comment]
The problem is: there is no such thing as ``skimage.util.compare``! So I have a hard time looking around from where this guy should be loaded.
Can you find out - maybe via inspecting ``globals()`` ...?

**Comment by cubic-inf** [comment]
How do I do that?

I can do this in the interpreter:
```
IN [97]: skimage.util.compare
Out[97]: <module 'skimage.util.compare' from 'C:\\Users\\Username\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\skimage\\util\\compare.py'>
```

**Comment by JorjMcKie** [comment]
just found out, that this is another difference between skimage on vanilla Python and on conda:

On vanilla Python 3.7 I have scikit-image v0.16.2, on conda it is v0.15.0. Conda does not have skimage.util.compare, whereas the v0.16.2 has it.

So the real question is: what is your version?

I could just "blindly" add implicit imports for all modules I can find under ``skimage.util`` and hope for the best ...

**Comment by cubic-inf** [comment]
scikit-image 0.16.2
conda 4.7.12

**Comment by cubic-inf** [comment]
Ok, it's using 16.2 when I import.
>>> import skimage
>>> print(skimage.__version__)
0.16.2

**Comment by JorjMcKie** [comment]
Can you please send me the script you are using? Preferably, just a "skeleton" containing only the import statements? So I can simulate this here and see if my implicit imports work.

**Comment by cubic-inf** [comment]
I used `conda install --force-reinstall -c conda-forge scikit-image` and the import would just be `import skimage`. Not sure if I know what you are wanting.

**Comment by cubic-inf** [comment]
The one I compile uses `import skimage.io` if that makes a difference.

**Comment by JorjMcKie** [comment]
> and the import would just be import skimage. Not sure if I know what you are wanting.

``import skimage`` - that's it?

**Comment by cubic-inf** [comment]
Yep

**Comment by kayhayen** [comment]
Using `--recurse-none` is a typical problem of people not knowing what they do. New Nuitka warns about this, and I verified sklearn compiles indeed with current Nuitka, and sharpened what `--enable-plugin=anti-bloat` does on the way, but I suspect tis report was never valid. Due to large compile times I only now care about these, as they become sort of manageable.

However, this still includes many things for me, web interfaces seem all included, dask, and many more, which one day plugins should avoid, but there are packages that abstract them all and cause nuitka to include all. For PySide/PyQt that's solved, but others will be needed too.
