### ISSUE TITLE
nuitka and pendulum not working when using --standalone

### ISSUE THREAD

**Issue by benoitscherrer** [Nuitka/Nuitka#568]
Hi,
This is my version of nuitka:
```
0.6.5
Python: 3.6.8 (default, Aug  7 2019, 17:28:10) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

Using python 3.6.8 from a CentOS package (not pyenv)

This is a 2-lines python program to reproduce the error:

```
sh-4.2# more test.py 
import pendulum
print(pendulum.now().isoformat())
```

The python script works:
```
sh-4.2# python3 test.py 
2019-11-08T20:40:45.336649+00:00
```

Things **do work** when using just `--follow-imports`
```
python3 -m nuitka --remove-output --follow-imports --include-package pendulum.locales  test.py
[...]
sh-4.2# ls -lh
-rwxr-xr-x 1 root root 5.1M Nov  8 20:42 test.bin
-rw-r--r-- 1 root root   51 Nov  8 20:40 test.py
sh-4.2# ./test.bin 
2019-11-08T20:43:29.119512+00:00
```

But when using  `--standalone`, the created binary can t load:
```
sh-4.2# python3 -m nuitka --remove-output --follow-imports --standalone --include-package pendulum.locales  test.py
[...]
sh-4.2# ls ./test.dist/
_asyncio.so	    _codecs_kr.so     _dbm.so	       _lzma.so		    _socket.so	 grp.so		  libgdbm.so.4	       libncursesw.so.5      libstdc++.so.6  readline.so
_bisect.so	    _codecs_tw.so     _decimal.so      _multibytecodec.so   _sqlite3.so  libbz2.so.1	  libgdbm_compat.so.4  libpanelw.so.5	     libtinfo.so.5   select.so
_blake2.so	    _crypt.so	      _elementtree.so  _multiprocessing.so  _ssl.so	 libcom_err.so.2  libgssapi_krb5.so.2  libpcre.so.1	     libuuid.so.1    termios.so
_bz2.so		    _csv.so	      _gdbm.so	       _opcode.so	    _struct.so	 libcrypto.so.10  libk5crypto.so.3     libpython3.6m.so.1.0  libz.so.1	     test
_codecs_cn.so	    _ctypes.so	      _hashlib.so      _pickle.so	    array.so	 libexpat.so.1	  libkeyutils.so.1     libreadline.so.6      math.so	     unicodedata.so
_codecs_hk.so	    _curses.so	      _heapq.so        _posixsubprocess.so  audioop.so	 libffi.so.6	  libkrb5.so.3	       libselinux.so.1	     mmap.so	     zlib.so
_codecs_iso2022.so  _curses_panel.so  _json.so	       _random.so	    binascii.so  libfreebl3.so	  libkrb5support.so.0  libsqlite3.so.0	     pendulum
_codecs_jp.so	    _datetime.so      _lsprof.so       _sha3.so		    fcntl.so	 libgcc_s.so.1	  liblzma.so.5	       libssl.so.10	     pyexpat.so

sh-4.2# ./test.dist/test 
Traceback (most recent call last):
  File "/quantivly/test.dist/test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/quantivly/test.dist/pendulum/__init__.py", line 9, in <module pendulum>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/quantivly/test.dist/pendulum/datetime.py", line 11, in <module pendulum.datetime>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/quantivly/test.dist/pendulum/date.py", line 10, in <module pendulum.date>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/quantivly/test.dist/pendulum/helpers.py", line 43, in <module pendulum.helpers>
  File "/quantivly/test.dist/pendulum/formatting/difference_formatter.py", line 12, in __init__
  File "/quantivly/test.dist/pendulum/locales/locale.py", line 38, in load
ValueError: Locale [en] does not exist.
```
Any way to fix that?

looks like pyinstaller also had trouble with pendulum in the past 
https://github.com/pyinstaller/pyinstaller/issues/3528

but i can t make nuitka work

thanks!

**Comment by JorjMcKie** [comment]
Supporting pendulum requires a few changes to Nuitka plugins:

1. Timezone data for ``pytz`` and ``pytzdata`` must be copied as data files to the script's ``.dist`` folder. Good to have that now!
2. ``pendulum`` itself insists on **_finding_** certain folders (which contain Python source only) at runtime. So those must be copied just like data files - which is unfortunate, but no killer.

I uploaded these changes to the Nuitka's ``jorj`` branch, which you can download as your new Nuitka version. You would end up having Nuitka v0.6.6rc7.

I also updated [hinted compilation](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation) scripts to support these changes.

**Comment by JorjMcKie** [comment]
If you are unsure how to replace your Nuitka installation with something like the ``jorj`` branch, I can also send you a ZIP for the changed plugins, which you can use to replace your existing ones - drop a post here.

**Comment by JorjMcKie** [comment]
@benoitscherrer - any feedback?
This should be resolved by now ...

**Comment by benoitscherrer** [comment]
Hi Jorj,

So sorry for the late reply. I got caught into something else and didn't
come back to this.

Do you have an approximative idea of the time frame for this to be in the
main branch?
Until then yes the zip would be really helpful.

Thanks so much
Best
Benoit

**Comment by kayhayen** [comment]
It is in 0.6.6 release whatever it is. So I am closing this for now, re-open as necessary
