### ISSUE TITLE
issue running hinted compile on Raspberry Pi

### ISSUE THREAD

**Issue by nanowiz** [Nuitka/Nuitka#590]
**I am trying to compile a Python program in Nuitka on my Raspberry Pi 4. I got this error...**
------------------------------------------------------------------------------------------------------------
pi@APFMRPi:~/TestCodes $ python3 get-hints.py APFM.py

_... Various printout from my program ..._

No result matches 5, , ['_OS_X_API']
No result matches 4, core, ['set_keyring', 'get_keyring', 'set_password', 'get_password', 'delete_password', 'get_credential']
No result matches 3, keyring, None
No result matches 2, yagmail.password, ['register']
No result matches 2, transforms, ['Bbox']
Call cleaning has removed 526 items.

pi@APFMRPi:~/TestCodes $ python3 nuitka-hints.py APFM.py
NUITKA v0.6.1.1 on Python 3.7.3 (linux) is compiling 'APFM.py' with these options:
 --standalone
 --remove-output
 --recurse-none

Error, cannot find 'hinted-mods.py=APFM-37-linux-32.json'.

------------------------------------------------------------------------------------------------------------
**Based on advice from  Nuitka-chat/Community, I tried installing Nuitka version 0.6.5, but the install says 0.6.1.1 is the latest. Presume that is the case for my platform.
I did try compiling the HelloWorld example after I first installed Nuitka and it worked fine. But when I try it again now, I get the same error as my APFM program. The directory lists afterwards shows tha the relevant files present in the folder.**
------------------------------------------------------------------------------------------------
pi@APFMRPi:../HelloWorld $ python -m nuitka --version
0.6.1.1
Python: 2.7.16 (default, Apr  6 2019, 01:42:57) 
Executable: /usr/bin/python
OS: Linux
Arch: armv7l
pi@APFMRPi:../HelloWorld $ python3 get-hints.py HelloWorld.py
Talk Hello World
Call cleaning has removed 0 items.
pi@APFMRPi:~/HelloWorld $ python3 nuitka-hints.py HelloWorld.py
NUITKA v0.6.1.1 on Python 3.7.3 (linux) is compiling 'HelloWorld.py' with these options:
 --standalone
 --remove-output
 --recurse-none
 
Error, cannot find 'hinted-mods.py=HelloWorld-37-linux-32.json'.

pi@APFMRPi:~/HelloWorld $ ls
get-hints.py  HelloWorld-37-linux-32.json  HelloWorld.py  hinted-mods.py  nuitka-hints.py

-------------------------------------------------------------
**Any advise on how to fix this would be greatly appreciated.**

**Comment by nanowiz** [comment]
**It was suggested that I uninstall Nuitka and reinstall. Now I am running in to trouble uninstalling. Using pip uninstall, I get permission errors. Using sudo pip uninstall, it cannot find the package. Here is the screen dump...**
pi@APFMRPi:~ $ pip uninstall nuitka
Uninstalling Nuitka-0.6.1.1:
  Would remove:
    /usr/bin/nuitka3
    /usr/bin/nuitka3-run
    /usr/lib/python3/dist-packages/Nuitka-0.6.1.1.egg-info
    /usr/lib/python3/dist-packages/nuitka
Proceed (y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/bin/nuitka3' -> '/tmp/pip-uninstall-prv9pwve/nuitka3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/uninstall.py", line 79, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 755, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 394, in remove
    moved.stash(path)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 283, in stash
    renames(path, new_path)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 338, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.7/shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/bin/nuitka3'
pi@APFMRPi:~ $ sudo pip uninstall nuitka
Not uninstalling nuitka at /usr/lib/python2.7/dist-packages, outside environment /usr
Can't uninstall 'Nuitka'. No files were found to uninstall.

**Comment by nanowiz** [comment]
This issue has been resolved by using the latest develop version 0.6.6 of Nuitka and python3.7.
