### ISSUE TITLE
Standalone Support for matplotlib

### ISSUE THREAD

**Issue by JorjMcKie** [Nuitka/Nuitka#598]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
D:\Jorj\Desktop>python -m nuitka --version
0.6.7rc1
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

D:\Jorj\Desktop>wsl -e python3.6 -m nuitka --version
0.6.7rc1
Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
Executable: /usr/bin/python3.6
OS: Linux
Arch: x86_64

D:\Jorj\Desktop>python -m pip show matplotlib
Name: matplotlib
Version: 3.1.2
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires: pyparsing, numpy, python-dateutil, kiwisolver, cycler
Required-by: scikit-image

D:\Jorj\Desktop>wsl -e python3.6 -m pip show matplotlib
Name: matplotlib
Version: 3.1.2
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/lib/python3.6/dist-packages
Requires: pyparsing, python-dateutil, kiwisolver, cycler, numpy
Required-by: scikit-image

D:\Jorj\Desktop>
```
But probably applies universally

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

From source, no venv.

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

A standalone compile of the following one-liner ...

```python
from matplotlib import pyplot as plt
```
...  leads to this import error:
```
D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist>vanilla
Traceback (most recent call last):
...
  File "D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist\matplotlib\__init__.py", line 832, in __getitem__
  File "D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist\matplotlib\pyplot.py", line 2349, in <module matplotlib.pyplot>
  File "D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist\matplotlib\__init__.py", line 832, in __getitem__
ImportError: cannot import name 'pyplot' from 'matplotlib' (D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist\matplotlib\__init__.py)

D:\Jorj\Desktop\Develop\nuitka\mpl-test\vanilla-win32.dist>
```
The above is independent from whether using straight standalone compile or hinted compilation.

Please note the apparent loop in the backtrace above!

Everything works fine if at least one of the following conditions is true:
* Config file ``matplotlibrc`` in folder ``mpl-data`` contains a backend definition like ``backend: TkAgg`` (other choices include "Qt5Agg", "WxAgg", etc.)
* ``os.environ["MPLBACKEND"]`` contains a valid backend string
* Using ``matplotlib.use("TkAgg")`` with a valid backend string argument is executed **before** importing pyplot.

There is a **difference** in the ``matplotlibrc`` file for **Windows** versus **Linux** or **OSX**. Windows is delivered with the default ``backend: TkAgg``, on other platforms there is no such default.

**So, everything is fine, if the backend is defined as a valid string value _before importing pyplot_. The error is not platform-dependent.**

If the default backend is not filled with a string value, Nuitka will reproducably lead to the above error when accessing the dictionary value ``matlotlib.rcParams["backend"]``. In that case the value is not a string, but a a list ``[object(), func]`` with a validation function ``func``.

``matlotlib.rcParams`` is not a standard dictionary but an instance of ``class RcParams(MutableMapping, dict)``.

For a shortcut fix, I am testing the following change to the ``numpy`` plugin (which also handles matplotlib):
Depending on which of the following conditions are met, a corresponding backend definition is placed in the ``matplotlibrc`` config file. The checks are executed top to bottom, and the first match will be used:

 package | backend | comment 
 -------- | ------- | --------- |
| darwin | MacOSX | OSX platform check! |
| PyQt5 | Qt5Agg | |
| PyQt4 | Qt4Agg | |
| gi | Gtk3Agg | |
| tkinter | TkAgg | |
| wx | WxAgg | |
| - | Agg | |

The above only happens, if there is no previous backend definition in that file

**Comment by JorjMcKie** [comment]
Should have thought of this earlier:

As a simple circumvention of the error explained above, I am now determining the default backend **_actually used_** at compile time. This value string is now put in the config file version of ``matplotlibrc``, which becomes part of the ``dist`` folder.

There is no longer the need to simulate the scan for vaild backend candidates in Nuitka as explained above.
