### ISSUE TITLE
Parser error on PySide .pyi files

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#611]
>  python -m nuitka --version
```
$ python3 -m nuitka --version
0.6.7
Python: 3.7.5 (default, Oct 17 2019, 12:09:47) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

>How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,

sudo pip3 install nuitka

> If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

https://github.com/belonesox/wtf-pyside-nuitka 

```python
from PySide2.QtWidgets import QApplication

if __name__ == "__main__":
    print("Hello!")
```

build 
```
python3 -m nuitka --standalone  wtf.py --plugin-enable=numpy --plugin-enable=qt-plugins
```

got:
```
$ ./build.sh
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/nuitka/__main__.py", line 182, in <module>
    main()
  File "/usr/local/lib64/python3.7/site-packages/nuitka/__main__.py", line 175, in main
    MainControl.main()
  File "/usr/local/lib64/python3.7/site-packages/nuitka/MainControl.py", line 736, in main
    main_module = createNodeTree(filename=filename)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/MainControl.py", line 142, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/usr/local/lib64/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 616, in optimize
    makeOptimizationPass(initial_pass=True)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 530, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 165, in optimizeModule
    optimizeShlibModule(module)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 160, in optimizeShlibModule
    Plugins.considerImplicitImports(module=module, signal_change=signalChange)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/plugins/Plugins.py", line 141, in considerImplicitImports
    plugin.considerImplicitImports(module, signal_change)
  File "/usr/local/lib64/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 173, in considerImplicitImports
    for full_name, required in self.getImplicitImports(module):
  File "/usr/local/lib64/python3.7/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 1195, in getImplicitImports
    for used_module in module.getUsedModules():
  File "/usr/local/lib64/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 899, in getUsedModules
    self._readPyPIFile()
  File "/usr/local/lib64/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 878, in _readPyPIFile
    assert imported.endswith(")")
AssertionError
```

What can be wrong?

**Comment by kayhayen** [comment]
I would like you to send us the .pyi file that is causing this, since it would most probably indicate a shortcoming of Nuitka. 

However PySide is unsupported in Nuitka due to unwillingness to accept necessary changes. It is actually unique in that. Please use PyQt5 instead. There are plenty of issues here already which document that.

Yours,
Kay

**Comment by belonesox** [comment]
Sorry, cannot get what ".pyi" file I should sent so I pack all my PySide2 "pyi" files
[pyside2-pyi.zip](https://github.com/Nuitka/Nuitka/files/4155941/pyside2-pyi.zip)

**Comment by kayhayen** [comment]
So on the factory branch, there is fixed code that handles that part. Unfortunately PySide remains unsupported due to their lack of willingness to accept patches from us. So I have to close this.
