### ISSUE TITLE
PIL import error

### ISSUE THREAD

**Issue by pokemonchw** [Nuitka/Nuitka#625]
$ python3 -m nuitka --version
0.6.7
Python: 3.8.1 (default, Jan 22 2020, 06:38:00) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64

Installed via yaourt.

When I try to compile
It warned me:
`Nuitka:WARNING:Unresolved '__import__' call at '/usr/lib/python3.8/site-packages/PIL/Image.py:427' may require use of '--include-plugin-directory' or '--include-plugin-files'.`

It looks like [issues214](https://github.com/Nuitka/Nuitka/issues/214)
So I ignored it
But when I run it
I get back this big error message:

`
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "/home/byayoi/workspace/dieloli/script/Core/MainFrame.py", line 156, in read_queue
    from script.Core import EraImage
  File "/home/byayoi/workspace/dieloli/script/Core/EraImage.py", line 3, in <module script.Core.EraImage>
    from PIL.ImageTk import PhotoImage
  File "/usr/lib/python3.8/site-packages/PIL/ImageTk.py", line 31, in <module PIL.ImageTk>
    from . import Image
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 90, in <module PIL.Image>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py)
`

Finally, I found _imaging.cpython-38-x86_64-linux-gnu.so in /usr/lib/python3.8/site-packages/PIL

**Comment by JorjMcKie** [comment]
The following script compiles and runs successfully with the following configuration.
So something there is some disorder in your configuration. I am unsure whether Python 3.8 is already supported by nuitka.

```
python3.6 -m pip show nuitka pillow
Name: Nuitka
Version: 0.6.7
Summary: Python compiler with full language support and CPython compatibility
Home-page: http://nuitka.net
Author: Kay Hayen
Author-email: Kay.Hayen@gmail.com
License: Apache License, Version 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires:
Required-by:
---
Name: Pillow
Version: 7.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: /usr/local/lib/python3.6/dist-packages
Requires:
Required-by:
jorj@jorj-new:/mnt/d/Jorj/desktop$
```

Script:

```python
# -*- coding: utf-8 -*-
from __future__ import print_function
import os, sys, time
import base64

infile64 = base64.b64decode(
    b"iVBORw0KGgoAAAANSUhEUgAAAMYAAADHCAYAAABCxyz4AAAABGdBTUEAALGPC/xhBQAAAA"
    b"FzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpR"
    b"PAAAAAlwSFlzAAAASAAAAEgARslrPgAAAAZiS0dEAAAAAAAA+UO7fwAAEFlJREFUeNrt3d"
    b"tvHPUVB/Dvb3Z218aOA3EolwIlwcSAjUoBcW0heYC0aUDxpZHaqhfeEDz2oY9UqFVbqbcn"
    b"+gdUVasAwYFWiJZbhVqomoe2YGzHBBKqAkpMbKAhTuyd0wdvEnt37jvntzuT75EQsfcyP+"
    b"/+PnvOmZn9jUHCmJmZ2eg4znYAWwEMAdgMoAJgHQAXjDXx9oKH/R/UUj9eZM1Pa/9d/9Ex"
    b"wNeurTY9tsc9jK7SkbBn93ne0z9KyP3PxsnahfhfbaBTXm4PwEcAlgC8Y4yZAvByqVR6bt"
    b"OmTR8keSI33psj5uDBg9tF5GEA2wGUOeXjxfyiYHLOS4lCmoRIAwqBoOwY38ef576L9eXJ"
    b"CHF+2CQYT8Ptn2Cwk2A4AC6o//szInIrgO8uLy/XZmdnXwDw2MDAwDPGGK9lGNPT0ze/9d"
    b"ZbvxaRmznN7UVcFL73j52GWkNxZkRJtt2eKAG4F8C9s7Ozb8zMzDw0ODj4SpSwoDfGmZmZ"
    b"+YHjOK8RRQejkMRPnimK5ANoewwbY/4yOzv7s/3795cTwZicnOydnZ19xhjzSF0bo6NRCF"
    b"EkCyMi3+vr6/vz4cOHL4hVSk1OTva6rvuCiNzCaZrxRFdCIWJ8t+P3fJmikJVt5KCUCoq7"
    b"FxcXX5mcnLxraGjoWGDGEJGS67p7ABBFTjJFrDmphKIgMeS67sTk5GQlEMaBAwceBfAVTt"
    b"O8oZA2oSiMji+5rvsLXxhTU1M3Afg+p2mRUMACisLgeGhqamrrGhgiYhzHeYyNdj5RhJdT"
    b"RBG3IXcc5zERKZ1pvqenp3caY9hXWGy+s0UR1ADbQZHj5rsxrj1w4MA3APzGAQBjzEOcwn"
    b"nNFLG6b71MIYXKGvA872EAcN58881LANzD6ZpjFEIUmdVTxtw6NTW1xXEc58vsLfKOQogi"
    b"Wxw7XAB3SIH/yHMBhSDgAJ8nyihyc65U0rjTEZHrOW3zjCL2KFRQFDSudwBcyamriGKtEB"
    b"0U0k4UhQRypQNgPaevlbShiEKIItuoOgC6OGuJIjWKgvanLhtvZROep45CJKwB1kWR87Nr"
    b"A8Ph1LXVZ+ihiCxpmCkIo2NpEAVLKUZQNaOHIrKUUkFR2OMYzBj2bBQTRVH3TBFGYVGAKA"
    b"iDKIiCMHLbY+ihkOgBaKCQ4gJh861twhN1FOIhZJUQfRRsvhnpCyqtTBG6YAczBWF0Mou2"
    b"oIAFFGy+GRk1GjooEpwvRRTsMTojW4g+isBzpfRRiHjsMRitllNKKGJkKp1MIYVNHIRRCB"
    b"QSdxAKKHjkm9Fif6GGQoiCMIiCKNh8F8mGJgoJOMDnWUHB5pvRmSjiNt+Zo2ApxWi9mNJD"
    b"IQlGkTkKNt8Momh+bEGTBnsMbRgiFlBIjMUQ9DIFewxGS3lDC0Xwp7YyigJ/phJGAVCEn0"
    b"ioVD7xOAaj9XJKG4XYRXEONN/sMawkDH0U4Zczznrvk6zpbYo4h1zOXMuNuEamiPWlDGYK"
    b"llLnHIoY3/lWQ8HjGIwORSGaKHDuoSAMWy2GNgpRRHEOfheDzbfVbKGIwoQ0wFrlE1cJYW"
    b"SSN9QyhUSkK4XyiauEMPKAQuKMIdPyqfh9BkspC6WUOgpJsLBzRuXT6tt5HIORUebIFgVM"
    b"BiiQDsV5pfdwRfezIduWiJ0CCR/T+FrFvj3iMQ2vLWHkHQUk9vY1yqeqOYZq5RhaX80wo4"
    b"tkSjZ73wjDnovORJGyfIqcpDlGwea7IChCa3yF8qnoKNh829ehg8JErHae9d6ngqNgKVUE"
    b"FFHbZvmU6kOBpZRFIHoo4gJh+RQ3UxJGAVCI+mnn5xYK9hg2SIgFFCbGaucsnxJ9KDBj6H"
    b"cYFjKFxO5xiCLeYwnDigxlFEnWliKKWI8lDIt7pqyjEPYUac8wJgx7LtRQxFu7lihiP1bY"
    b"fFuspjRRJFztnCgix8qMYbPRUEIR89KtRJHgvDHCKDQKEEUKFMwYVm1oohCiyBAFIOwx1E"
    b"3UT+TTRCFR3+AjisRjZcawlzDUUDBTZIuCMAqDIupgBlEkGithWJVBFDlBAfA4hoUew1NH"
    b"Ed5jEEWaxamZMdpQTmWNInbWIIpYKAijDeWUXRQgihQoCMOuDD0UQhRZX9uDMKz2G0SRBx"
    b"RsvguEwu99PPTJVhz6+K5zKiNnFVwlJOcoVo6pm4DtGgAlvgEpgqWU1Q8zDRQqH5iEwZfA"
    b"nhA9FJSReSnFHsNGGaWLQmDA95E9Rq5iQ7dpWhAhWxRATQRPT38aprPpGh3RvVDDOP2yU1"
    b"MlJ8ElZMN4/JOd+JaizZfHEf/NiYRUsf57yZpWcan/z7z66qv8qFGO6Q9r2Dt9EjUvexTw"
    b"mxAikSikAUjwlWWDtrnq5yQLwq1BIWvpCCLH4FdCSpLXIHCba9f/Yo9hIa7pL2FksIqSIY"
    b"o8oOAXlazicLBrsIK9MyfheUTRySgAwO2pzMMtLaXay5LuLqKzraT3lVbH5P+440sbsex1"
    b"+d772o0ljKKKvdMn4QlRdCoKEcB8dOgn0td1NOmulpDJEbYbUVq8X8BtkeMSa+NfrJ2Pyb"
    b"n7cKrWE/jyvXl0uY6DKDoRRbpVQogi9H5dpXkMbXwaldLxwJfwugtdjFxThWOIohNRAICT"
    b"qMcgilj36yot4Lr+fSg7x1dWO/f577qNKw05iKLjUCS7cAxRJLpft7uAof59qJQ+Dc0c9w"
    b"9WYYwhig5CIbFLKaJIdb/TOMpOMI7PX+TivqsrMMYQRYegiHccgyhaGn+3O4/hjStlVVDc"
    b"cHEZO+s4iKL9KKJhEEUm4+92j2Fo4x9QdhYDX+ovXFLGfVuqMGvOICGKdqCAhJVSRJHp+M"
    b"9z53Bd/wRccyKwIb/hIhdfvbq68u0KomgbiuCMQRQq4+9x5+o9R3DmuPGS8lkcRNEWFOIL"
    b"gyhUx99TnsNQ/wTcEBw3XVrBzsFuGKJoC4rmUooorIy/pzyH4f4JuM6J0MyxfaCLKGyjaG"
    b"q+icLq+HvKRzHcvw+lkJ7jls+WsX2gShQ2UazpMYiiLeNfwRFeVt12WRXbr+4mCgvl0+rn"
    b"doiivePvLR/FcP9TETgqK2UVUaiWT/AtpYiibePvLc/VcZwMxHH75VXcO9BNFIrlkw8Mom"
    b"j3+E9njpJZDOw5br+8gnuv6iYKpfIpIGMQRbvH31s+gqH+fSiZU4GZ444rqrjnqi6iUCif"
    b"QmAQRbvH31f5AMP9E6E47vxcF7Zt7iaKjMun8B6DKNo+/r7K+5E4tm7qwtZNXUSRYfkU3G"
    b"MQRceMPw6ObZu7cfembqLIqHxaA+P0pbCIovPG31d5D8P9E3BwMrAh37a5awUHUbRcPq0O"
    b"M3/wh3J+9xxRdPD4Pz51CV6fG0FNyr5vogiwsOg1rveHVB+VaR8oSR6R0ZJNEn1j2i25zB"
    b"SdP/6+ynsY3vAU3jjmj8MY4IJurp2XZThEkY/xr6/+t36cY4mz1kK4RJGf8a+vrOB4fW5X"
    b"YFnFyCbM6//4vVTcEykLuSQXLpF4vxe0NpY045AMnqMel/a8gd7KnCrq947fgNmFbZy9mh"
    b"njw+MX81XIMDZ0HUYv5lQzXdjCCozMegxG9mGp/GPoZQyudp5PFHzfmDHyj0RtRwFDLWN8"
    b"WnNQE5O62Uz+JklrvXrCDcdb7T/5THMMsK5iiKKoMF482of3F4N3/Z1J2WcO28vZQ+9NVw"
    b"VqOE3A5xQBEb9yoPnijWefv+G0hobnXH2/+jBDnt/vq6Frtx16v7MbwIZuBw/eWCWKosII"
    b"/bQlCl8Up58/tM5XPs7CHqNNPQZRhKOIrt+0Dz4yrMMgihgognC044g8Qx8GUcRDIbF3Ch"
    b"BF7mEQRRIUcSYoUeS++SaKZCjE8+81Vo9FC0Vk48/IJmMQRcJMIVFHY7QzBVGowyCKnKFg"
    b"prDYYxBFchRxj8wTRT57DPE8okiFIqzO10fBHkO7lCKKVCji7ZDS/uYgQ7GUIorkmSJigh"
    b"JFAWAQRQ5REIh6j9H4JhFF3L85qM63g4I9ho29UkSRGEW8YKbIOQyiSIZC4u+uJYr8Nt9E"
    b"kRxFuoN8GaFgGWVhdy1REAXDr/kmilQoJOZJhAooeBKhtd21RJEURbIVGpkp8ldKEUUqFJ"
    b"Hz1NpauAy15pso0qAQoih0j0EUKVGYiDpfFwV7DCulFFEkzRTtRMHMYSFjbOldxMVVp+lF"
    b"l6AlW/x2VzZeby2gQZWA84ia55j4rDEmPkNZ/Ttz5pP86KfA7LynjMIQRaFhrDuZ4+Eb35"
    b"/fmPMwO6+dKWJ339mjoA19GEWsVaV+LWdNFCIm+otKaih4HMPCXqkCRqJjM2lQtDNTEARh"
    b"ZKBDD0Wcb/ERBWF0pAuiYLDHaJhSiijqpVrguVLKKHiuFDNG+nShiiLk+xhWL3nMIIxUNi"
    b"yjCJzAREEYnVRMqaKQNqIgEMJIy0IRRbqsQRRsvtscnifqKES8BOdLZY+CzTczRutZI/NM"
    b"EZUxFFFw1y1hdDIKIQrCyGvzrYuilYN8RMEeo6goJOKLSsoo2GMwY6SkoYkiYgkdZgrC6N"
    b"B8oY9C2oWCSAijZR2aKBJ+UYko2GO03UT9OIYuChOy4JouiuhjKAxmjKAOQzlTJF7xPLNM"
    b"QRCEkUGnoYdC2oeCNgijJRpEwSAMuyikrSiog8136uZbEYWELbpmBwWbb2aMFhtwHRTZXa"
    b"CSmYIwCoQi0RI6REEYncHCBgppEwoCYY/RKg9NFBKnztdDwR6DGaMFF3ookuQtZgrC6KQu"
    b"QxVFugtUZoSC2YIwWm001FBIokEQBXuMDjDhiQUUEm8xBAUUXImQGSODUkoHRazFENQyBV"
    b"EQRvrOWzFTEMW5AKNWZBx6KLI68k0UndpjHAfQVygSoo9CAo5jiCdWULDH0J1CDoAjBc0X"
    b"qigiSyk1FARhIT50AMwQRfrLKccZCVHkLmYcEfl7cfsLomAkD2PMa46IvFRMF7oo0h35Jo"
    b"o8RK1We9kdGRn568TExCEAVxavntJDEe8gmx4KNt96/cXy8vKfHGOMAPhdYdtvjUyRZF0p"
    b"Zoq8lVGP7969+5RTnzC/AnC8cDQUUQhRFDGWROSnQP3I9+jo6BEAPyKKBChEiKJ42eLnIy"
    b"MjhwDAPf3LhYWFX65fv/47AAbz/geuvaKSHorAOl8ZBU8iVEHxbqVS+fHpn8+cK/XAAw8s"
    b"ep63G8CJ4vQXNjOFHRQMnRLKGPP1HTt2fNwEAwDGx8f/LSL3AziZ/1KqDShAFDmMZWPM7l"
    b"27dv1t9S+bzq4dGxt7HsC3AJwqQuYgCkZI1IwxD46MjEw03uD63Xt0dPTxJ598ch4ru3E3"
    b"EkX8YwmB605ljII9RsvxEYBvj46OPu13Y+D3McbGxp4vlUo3AvhjrvdKWcsUYKbIT7xYq9"
    b"VuHhsbezroDm7Yo3ft2vUfADufeOKJ7caYRwHckqsGvC0oQBSdG/8yxjwyOjq6L+qObpxn"
    b"Gx8ffw7Ac3v37v2i53nfNMbsBHAZURBFDuJ9Y8yzAH47MjLyUv1Mj8gwabe2Z8+eAdd1hw"
    b"BsBlDppFfi7fmlC6ePLA2c/Y0H8YLxNN3k85vG6HJLJ+7Z0vvPxt9fs+HV4XXVhf44z5E2"
    b"Plnqn5ueu22Sc94/PM9bMsa8IyJT4+Pj02me4/+G9mDCFP4AegAAACV0RVh0ZGF0ZTpjcm"
    b"VhdGUAMjAxMy0wOC0wOFQxMDozNDoyMyswMjowMO1xgiMAAAAldEVYdGRhdGU6bW9kaWZ5"
    b"ADIwMTMtMDgtMDhUMTA6MzQ6MjMrMDI6MDCcLDqfAAAAAElFTkSuQmCC"
)

import PySimpleGUI as sg

img = sg.Image(data=infile64)
layout = [[img]]
form = sg.FlexForm("Show embedded PNG", layout, finalize=True)
event, values = form.Read(timeout=500)
form.Close()
print("sys.executable:", sys.executable)
print("sys.base_prefix:", sys.base_prefix)
print("sys.base_exec_prefix:", sys.base_exec_prefix)
print("sys.exec_prefix:", sys.exec_prefix)
print("sys.prefix:", sys.prefix)
print("sys.frozen:", hasattr(sys, "frozen"))
print("__file__:", __file__)
print("__name__:", __name__)
compiled = globals().get("__compiled__", False)
if compiled:
    print(
        "Running compiled (Nuitka v%i.%i.%i-%s)"
        % (compiled.major, compiled.minor, compiled.micro, compiled.releaselevel)
    )
else:
    print("Running interpreted")

**Comment by kayhayen** [comment]
This might be the same issue as in a couple of other cases, where the import of the name is not resolved, but on another level. My fix only works if it's already included, but maybe it wouldn't be recursed to. But that isn't done at all yet, not for level 0, and not for levels > 0.

I guess, I really have to add test coverage to this.

**Comment by JorjMcKie** [comment]
Sorry, I included the wrong reproducer script, this is the intended one:

```python
# -*- coding: utf-8 -*-
from __future__ import print_function
import os, sys, time
import base64, io
import tkinter as tk
from PIL import Image, ImageTk

infile64 = base64.b64decode(
    ... same data as above ...
)

root = tk.Tk()
tkimg = ImageTk.PhotoImage(data=infile64)
```

This compiles and runs under Python 3.6 (Linux), Python 3.7 (Windows) and Python 3.8 (Windows).
I didn't reproduce under Linux / Python 3.8, but I suspect it would work also.
@pokemonchw  - can you please provide your compile command line?

**Comment by pokemonchw** [comment]
I have forgotten the previous compile command line
When I try again today

```
python -m nuitka ./Game.py --follow-imports --include-plugin-directory=/home/byayoi/.local/lib/python3.8/site-packages/numpy --include-plugin-directory=/usr/lib/python3.8/site-packages/PIL/
```

I gave up because of lack of memory

When I try

```
python -m nuitka ./Game.py --follow-imports --nofollow-import-to=PIL
```

It works well
