### ISSUE TITLE
Standalone Binary does not work with Jira Library

### ISSUE THREAD

**Issue by schuppentier** [Nuitka/Nuitka#653]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
  python -m nuitka --version
  ```
  0.6.7
  Python: 3.8.2 (default, Feb 26 2020, 22:21:03) 
  Executable: /usr/bin/python
  OS: Linux
  Arch: x86_64
  ```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
  * Arch Linux, installed globally via pacman

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.
  * Hello World works

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.
  ```
  from jira import JIRA, Issue

  jira = JIRA("https://jira.atlassian.com")
  issue = jira.issue("JRASERVER-1391")
  print(issue.fields.summary)
  ```
  `nuitka3 --show-progress --show-scons --standalone --include-package="jira" --show-modules main.py`

  This example should print the summary of [this Jira issue](https://jira.atlassian.com/browse/JRASERVER-1391). Instead it prints the following Error:
  ```
  Traceback (most recent call last):
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pbr/version.py", line 442, in _get_version_from_pkg_resources
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pkg_resources/__init__.py", line 358, in get_provider
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pkg_resources/__init__.py", line 901, in require
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pkg_resources/__init__.py", line 787, in resolve
  pkg_resources.DistributionNotFound: The 'jira' distribution was not found and is required by the application
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/main.py", line 1, in <module>
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/jira/__init__.py", line 6, in <module jira>
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pbr/version.py", line 462, in semantic_version
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pbr/version.py", line 448, in _get_version_from_pkg_resources
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/pbr/packaging.py", line 43, in <module pbr.packaging>
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/setuptools/__init__.py", line 228, in <module>
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/setuptools/monkey.py", line 101, in patch_all
    File "/home/dstengele/PyCharmProjects/jira_example/main.dist/setuptools/monkey.py", line 138, in patch_for_msvc_specialized_compiler
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ModuleNotFoundError: No module named 'setuptools.msvc'
  ```

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.
  * This is the first time, I tried this with Nuitka.

**Comment by kayhayen** [comment]
I believe, this might be an issue of `pbr` and/or `setuptools`, and that `setuptools.monkey` needs a implicit dependency on 'setuptools.msvc` simply. What do you think @JorjMcKie ? Or is this only the symptom of the first one, not sure, but if seems prudent to add it. Since it's an unworthy namespace, there is no big deal adding it I suppose.

**Comment by flamas-78** [comment]
Same issue for me.

**Comment by kayhayen** [comment]
This was never about the jira library I suppose, works these days.
