### ISSUE TITLE
Nuitka and numpy-scipy-pyqt5-pyexcel

### ISSUE THREAD

**Issue by Alexey-Krapivnitsky** [Nuitka/Nuitka#670]
I am a novice Python developer and am trying to compile my first serious program using Nuitka. That's what I get:
 
F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project>nuitka --follow-imports --plugin-enable=qt-plugins --plugin-enable=numpy --include-plugin-directory=C:\Python37\lib\site-packages\lml --include-plugin-directory=C:\Python37\lib\site-packages\numpy\core --include-plugin-directory=C:\Python37\lib\site-packages\numpy\lib --include-plugin-directory=C:\Python37\lib\site-packages\scipy\_lib --include-plugin-directory=C:\Python37\lib\site-packages\scipy\optimize --mingw64 rations_all_in_one.pyw
Problem with statement at C:\Python37\lib\site-packages\numpy\lib\npyio.py:14:
-> from . import format
 
Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Python37\\lib\\site-packages\\numpy\\lib\\npyio.py', 'module_name': <ModuleName lib.npyio>}>'.
Traceback (most recent call last):
File "C:\Python37\lib\site-packages\nuitka\__main__.py", line 182, in <module>
main()
File "C:\Python37\lib\site-packages\nuitka\__main__.py", line 175, in main
MainControl.main()
File "C:\Python37\lib\site-packages\nuitka\MainControl.py", line 736, in main
main_module = createNodeTree(filename=filename)
File "C:\Python37\lib\site-packages\nuitka\MainControl.py", line 142, in createNodeTree
Optimization.optimize(main_module.getOutputFilename())
File "C:\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 616, in optimize
makeOptimizationPass(initial_pass=True)
File "C:\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 530, in makeOptimizationPass
changed = optimizeModule(current_module)
File "C:\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 168, in optimizeModule
changed = optimizeCompiledPythonModule(module)
File "C:\Python37\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
module.computeModule()
File "C:\Python37\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 500, in computeModule
trace_collection=self.trace_collection
File "C:\Python37\lib\site-packages\nuitka\nodes\StatementNodes.py", line 164, in computeStatementsSequence
new_statement = statement.computeStatementsSequence(trace_collection)
File "C:\Python37\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
new_statement = trace_collection.onStatement(statement=statement)
File "C:\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 550, in onStatement
new_statement, change_tags, change_desc = statement.computeStatement(self)
File "C:\Python37\lib\site-packages\nuitka\nodes\AssignNodes.py", line 259, in computeStatement
trace_collection.onExpression(self.getAssignSource())
File "C:\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 531, in onExpression
r = expression.computeExpressionRaw(trace_collection=self)
File "C:\Python37\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1111, in computeExpressionRaw
expression = trace_collection.onExpression(expression=sub_expression)
File "C:\Python37\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 531, in onExpression
r = expression.computeExpressionRaw(trace_collection=self)
File "C:\Python37\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
return self.computeExpression(trace_collection=trace_collection)
File "C:\Python37\lib\site-packages\nuitka\nodes\ImportNodes.py", line 403, in computeExpression
trace_collection=trace_collection, module_name=imported_module_name
File "C:\Python37\lib\site-packages\nuitka\nodes\ImportNodes.py", line 277, in _attemptRecursion
module_package=module_package,
File "C:\Python37\lib\site-packages\nuitka\nodes\ImportNodes.py", line 208, in _consider
reason=reason,
File "C:\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 167, in recurseTo
reason=reason,
File "C:\Python37\lib\site-packages\nuitka\importing\Recursion.py", line 83, in _recurseTo
is_shlib=module_kind == "shlib",
File "C:\Python37\lib\site-packages\nuitka\tree\Building.py", line 939, in decideModuleTree
module_name=module_name, is_top=is_top, module_relpath=filename
File "C:\Python37\lib\site-packages\nuitka\tree\ReformulationNamespacePackages.py", line 167, in createNamespacePackage
source_ref=source_ref,
File "C:\Python37\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 588, in __init__
source_ref=source_ref,
File "C:\Python37\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 264, in __init__
setLocalsDictType(self.module_dict_name, "module_dict")
File "C:\Python37\lib\site-packages\nuitka\nodes\LocalsScopes.py", line 31, in setLocalsDictType
assert locals_dict_name not in locals_dict_handles, locals_dict_name
AssertionError: globals_lib
 
Tell me what I'm doing wrong and how to fix this annoying error.
 
PS I've been Suffering for a week))))

**Comment by Alexey-Krapivnitsky** [comment]
Next I fixed the compilation process:
F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project>nuitka --follow-imports --plugin-enable=qt-plugins --plugin-enable=numpy --include-plugin-directory=C:\Python37\lib\site-packages\lml --include-plugin-directory=C:\Python37\lib\site-packages\scipy\_lib --include-plugin-directory=C:\Python37\lib\site-packages\scipy\optimize --mingw64 rations_all_in_one.pyw
Nuitka:INFO:Injecting plug-in based pre load code for module 'PyQt5':
Nuitka:INFO:    Adding dist folder to 'PATH' environment variable.
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.

F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project>

And everything seems to be fine, but when you run the exe file, it outputs the following:
F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project>rations_all_in_one.exe
Traceback (most recent call last):
  File "F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project\rations_all_in_one.pyw", line 4, in <module>
    import pyexcel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\__init__.py", line 12, in <module pyexcel>
    from .book import Book
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\book.py", line 11, in <module pyexcel.book>
    from pyexcel.sheet import Sheet
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\sheet.py", line 14, in <module pyexcel.sheet>
    from pyexcel.internal.sheets.row import Row as NamedRow
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\internal\__init__.py", line 12, in <module pyexcel.internal>
    from pyexcel.internal.source_plugin import SOURCE  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\internal\source_plugin.py", line 17, in <module pyexcel.internal.source_plugin>
    import pyexcel_io.constants as io_constants
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel_io\__init__.py", line 27, in <module pyexcel_io>
    plugins.load_plugins(
  File "C:\Python37\lib\site-packages\pyexcel_io\plugins.py", line 137, in load_plugins
    scan_plugins_regex(
  File "C:\Python37\lib\site-packages\lml\loader.py", line 130, in scan_plugins_regex
    for module_name in all_modules:
  File "C:\Python37\lib\site-packages\lml\loader.py", line 116, in <genexpr>
    module_info[1]
  File "C:\Python37\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Python37\lib\pkgutil.py", line 140, in iter_importer_modules
    return importer.iter_modules(prefix)
TypeError: descriptor 'iter_modules' requires a 'nuitka_module_loader' object but received a 'str'

**Comment by kayhayen** [comment]
The issue template has a point. Please try again, following it. I am not going guess. Do not use `--include-plugin-directory` option, it is not what you think.
