### ISSUE TITLE
Nuitka and numpy-scipy-pyqt5-pyexcel

### ISSUE THREAD

**Issue by Alexey-Krapivnitsky** [Nuitka/Nuitka#671]
I am re-publishing my question with the publication requirements in mind.

nuitka --version 0.6.7
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86

nuitka is installed using pip
and according to the author's recommendation, I don't use the `--include-plugin-directory` option.
now I do the following:
```
nuitka 
--follow-imports 
--plugin-enable=qt-plugins 
--plugin-enable=numpy 
--plugin-enable=pylint-warnings 
--mingw64 
rations_all_in_one.pyw
```
This leads to the following warnings:
```
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\lml\utils.py:51' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\lml\utils.py:64' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\numpy\core\function_base.py:506' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\numpy\lib\utils.py:393' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\numpy\lib\utils.py:887' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python37\lib\site-packages\numpy\lib\utils.py:945' may require use of '--include-plugin-directory' or '--include-plugin-files'.
```
And my compiled exe file still causes errors on startup
```
Traceback (most recent call last):
  File "F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project\rations_all_in_one.pyw", line 4, in <module>
    import pyexcel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\__init__.py", line 12, in <module pyexcel>
    from .book import Book
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\book.py", line 11, in <module pyexcel.book>
    from pyexcel.sheet import Sheet
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\sheet.py", line 14, in <module pyexcel.sheet>
    from pyexcel.internal.sheets.row import Row as NamedRow
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\internal\__init__.py", line 12, in <module pyexcel.internal>
    from pyexcel.internal.source_plugin import SOURCE  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel\internal\source_plugin.py", line 17, in <module pyexcel.internal.source_plugin>
    import pyexcel_io.constants as io_constants
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\pyexcel_io\__init__.py", line 27, in <module pyexcel_io>
    plugins.load_plugins(
  File "C:\Python37\lib\site-packages\pyexcel_io\plugins.py", line 137, in load_plugins
    scan_plugins_regex(
  File "C:\Python37\lib\site-packages\lml\loader.py", line 130, in scan_plugins_regex
    for module_name in all_modules:
  File "C:\Python37\lib\site-packages\lml\loader.py", line 116, in <genexpr>
    module_info[1]
  File "C:\Python37\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "C:\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Python37\lib\pkgutil.py", line 140, in iter_importer_modules
    return importer.iter_modules(prefix)
TypeError: descriptor 'iter_modules' requires a 'nuitka_module_loader' object but received a 'str'
```

**Comment by kayhayen** [comment]
I strongly suspect, you didn't do this point:

* Please check out if the develop version of Nuitka works better for you.

I believe this was alredy fixed on develop, but I might be wrong.

**Comment by Alexey-Krapivnitsky** [comment]
would you be so kind as to give me a link to the develop version

**Comment by Alexey-Krapivnitsky** [comment]
I installed the develop version:
`nuitka --version
0.6.8rc5
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86`
 But it didn't eliminate the errors, they remained the same. The compilation seems to be completed successfully:
`F:\ПРОГРАММЫ\Девелоп\Sterns\sterns_project>nuitka --follow-imports --plugin-enable=qt-plugins --plugin-enable=numpy --plugin-enable=pylint-warnings --mingw64 rations_all_in_one.pyw
Nuitka-Plugins:INFO: Injecting plug-in based pre load code for module 'PyQt5':
Nuitka-Plugins:INFO:     Adding dist folder to 'PATH' environment variable.`
 but when you run the exe file, the same error occurs as in my first post:
`TypeError: descriptor 'iter_modules' requires a 'nuitka_module_loader' object but received a 'str'`

**Comment by kayhayen** [comment]
I guess, you can strip code code down to imports, and `pyexcel_io` will already do it. Your options indicate that you use plugins that only make sense for standalone mode, yet it's not on the command line, but that's only an aside.

I managed to reproduce this now, and will look into it. Thanks for the report!

**Comment by kayhayen** [comment]
The feature missing of the Nuitka loader was implemented a while ago.
