### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by gauthierbuttez** [Nuitka/Nuitka#683]
Hi,

I have an issue after compiling my code with Nuitka. This error message is displayed when I execute my 'exe':

```
Traceback (most recent call last):
  File "E:\DropboxBACKUP14112018\Cff\Python\PhoneBot_with_lock\phonebot.dist\phonebot.py", line 654, in <module>
  File "E:\DropboxBACKUP14112018\Cff\Python\PhoneBot_with_lock\phonebot.dist\phonebot.py", line 555, in main
  File "E:\DropboxBACKUP14112018\Cff\Python\PhoneBot_with_lock\phonebot.dist\mymodules.py", line 997, in give_systemPort_to_smartphones
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

So I check on this line 887 in my python source code file mymodules.py and I can see these lines:

```

997>>>max_systemPort = max(list_systemPort)
998>>>if max_systemPort < 4724:
```
As you can see, there is not '>' operator symbol but there is the '<'. So I don't understand this message.

So I isolated I compile separately with Nuikta this mymodules.py file to reproduce the error. And guess what, there was no error message with the exact same code!!!

Could you please guide me to debug this issue?

It starts to be extremely difficult to fix this kind of issue in the code if the error messages are not referring to the correct lines of code or even files.

By curiosity, I had a look in the "c" version of mymodules.py, and there is nothing I can do. There are thousands of lines of C code. I can't understand anything.

**Comment by gauthierbuttez** [comment]
Sorry, it was my code. It was getting the values from a sqlite3 table which was not string. My apologies.
