### ISSUE TITLE
Windows: Dependency walker output can cause UnicodeDecodeError on Python3

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#716]
```
C:\Python37x86\nuitkatest>"../python" -m nuitka --python-flag=no_site --standalone --mingw64 test.py

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\PYTHON~2\lib\SITE-P~1\nuitka\build\SINGLE~1.SCO", line 1864, in <module>
Traceback (most recent call last):
  File "C:\Python37x86\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\Python37x86\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\Python37x86\lib\site-packages\nuitka\MainControl.py", line 778, in main
    standalone_entry_points=standalone_entry_points,
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 1396, in copyUsedDLLs
    and not Options.getWindowsDependencyTool() == "depends.exe",
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 1290, in detectUsedDLLs
    package_name,
  File "C:\Python37x86\lib\site-packages\nuitka\utils\ThreadedExecutor.py", line 65, in submit
    self.results.append(function(*args))
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 1256, in addDLLInfo
    update_cache=update_cache,
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 1231, in detectBinaryDLLs
    update_cache=update_cache,
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 1040, in detectBinaryPathDLLsWindowsDependencyWalker
    _parseDependsExeOutput(output_filename, result)
  File "C:\Python37x86\lib\site-packages\nuitka\freezer\Standalone.py", line 878, in _parseDependsExeOutput
    _parseDependsExeOutput2(getFileContentByLine(filename), result)
  File "C:\Python37x86\lib\site-packages\nuitka\utils\FileOperations.py", line 300, in getFileContentByLine
    return getFileContents(filename, mode).splitlines()
  File "C:\Python37x86\lib\site-packages\nuitka\utils\FileOperations.py", line 306, in getFileContents
    return f.read()
  File "C:\Python37x86\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 486: character maps to <undefined>

C:\Python37x86\nuitkatest>"../python" -m nuitka --version
0.6.8.1
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Python37x86\python.exe
OS: Windows
Arch: x86

C:\Python37x86\nuitkatest>gcc --version
gcc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


C:\Python37x86\nuitkatest>
```

**Comment by byehack** [comment]
i edited this:
https://github.com/Nuitka/Nuitka/blob/f664e40f502c5f2de70e047f15deeaa57d4b4b6e/nuitka/utils/FileOperations.py#L303
 
to:
```python
def getFileContents(filename, mode="r"):
    with withFileLock("reading file %s" % filename):
        with open(filename, mode, encoding="ISO-8859-1") as f:
            return f.read()
```

and it fixed!

**Comment by kayhayen** [comment]
As an side, I hate that Scons warning you have there too. Nuitka falls back to gcc when no MSVC is installed, as it should to, no need to talk about it.

**Comment by kayhayen** [comment]
The `getFileContents` function is used in a couple of places, where the encoding might be different. On Windows cp1252 and latin1 which is what works for you are both there, but not necessarily used by applications, system language is not respected there. Most notable example is MSVC compiler from Microsoft, that depending on language pack active outputs in whatever encoding that should have.

It is indeed very likely that "latin1" is what `depends.exe` is doing there, and we need to pass an encoding parameter, to cover our ground.

**Comment by kayhayen** [comment]
I added something to the factory branch that should solve this universally:

https://nuitka.net/doc/factory.html

**Comment by byehack** [comment]
yes it worked successfully!
here is the log:
```
C:\Python37x86\nuitkatest>"../python" -m pip uninstall nuitka
Uninstalling Nuitka-0.6.8.1:
  Would remove:
    c:\python37x86\lib\site-packages\nuitka-0.6.8.1-py3.7.egg-info
    c:\python37x86\lib\site-packages\nuitka\*
    c:\python37x86\scripts\nuitka-run.bat
    c:\python37x86\scripts\nuitka.bat
    c:\python37x86\scripts\nuitka3-run-script.py
    c:\python37x86\scripts\nuitka3-run.exe
    c:\python37x86\scripts\nuitka3-run.exe.manifest
    c:\python37x86\scripts\nuitka3-script.py
    c:\python37x86\scripts\nuitka3.exe
    c:\python37x86\scripts\nuitka3.exe.manifest
Proceed (y/n)? y
  Successfully uninstalled Nuitka-0.6.8.1

C:\Python37x86\nuitkatest>"../python" -m pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
Collecting https://github.com/Nuitka/Nuitka/archive/factory.zip
  Downloading https://github.com/Nuitka/Nuitka/archive/factory.zip
     | 16.9MB 211kB/s
Installing collected packages: Nuitka
  Running setup.py install for Nuitka ... done
Successfully installed Nuitka-0.6.9rc2
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python37x86\nuitkatest>"../python" -m nuitka --python-flag=no_site --standalone --mingw64 test2.py

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\PYTHON~2\lib\SITE-P~1\nuitka\build\SINGLE~1.SCO", line 1853, in <module>

C:\Python37x86\nuitkatest>
```

**Comment by kayhayen** [comment]
I am keeping issues open until they are in stable releases, this is intended for 0.6.8.3 if it proves harmless enough. As for the no MSVC message, I will try and fight the MSVC init being done when we are in `--mingw` mode, that must seriously harm performance, even in my CI where it is available, but some jobs are not supposed to use it.

**Comment by kayhayen** [comment]
This was release as part of 0.6.8.3 hotfix.
