### ISSUE TITLE
Python2: Slice nodes didn't annotate their exception exit

### ISSUE THREAD

**Issue by brodders61** [Nuitka/Nuitka#729]
Hi, new to nuitka and using Anaconda 2.7 on Windows 8.1 64bit.

Used conda to install gcc, nuitka as per installation instructions.

hello.py works OK. But, my big sprawling still-learning-python mess of about 6000 loc from 6 years ago throws a NuitkaOptimizationError.

Looks as if something like this was reported in 2018....

Here is my versions:

gcc (Rev5, Built by MSYS2 project) 5.3.0
nuitka --version
0.6.8.3
Python: 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)]
Executable: C:\local\Anaconda2\python.exe
OS: Windows
Arch: x86_64

error report:

python -m nuitka --follow-imports Pyfo!.py
Problem with statement at Pyfo!.py:3314:
->                     try:

Problem with statement at Pyfo!.py:3301:
->                 if ':' in Ncount_str:

Problem with statement at Pyfo!.py:3269:
->             if s[0:10] == '#widthfile': # chop width of file to N places L => R only

Problem with statement at Pyfo!.py:1723:
->         if s == '':

Problem with statement at Pyfo!.py:1436:
->     while keep_looping:

Problem with statement at Pyfo!.py:1150:
-> def main():

Problem with statement at Pyfo!.py:1150:
-> def main():

Nuitka:INFO:Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'mode': 'compiled', 'main_added': False, 'filename': 'Pyfo!.py'}>'.
Traceback (most recent call last):
  File "C:\local\Anaconda2\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "C:\local\Anaconda2\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "C:\local\Anaconda2\lib\site-packages\nuitka\MainControl.py", line 739, in main
    main_module = createNodeTree(filename=filename)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\MainControl.py", line 142, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\Optimization.py", line 619, in optimize
    makeOptimizationPass(initial_pass=True)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\Optimization.py", line 531, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\Optimization.py", line 168, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 503, in computeModule
    trace_collection=self.trace_collection
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\AssignNodes.py", line 281, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 543, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1041, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 543, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 921, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 419, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 435, in computeFunction
    trace_collection=trace_collection
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\LoopNodes.py", line 231, in computeStatement
    trace_collection
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\LoopNodes.py", line 173, in _computeLoopBody
    trace_collection=trace_collection
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 595, in computeStatement
    branch_no_collection.computeBranch(branch=no_branch)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 754, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 578, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 754, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 578, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 754, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\local\Anaconda2\lib\site-packages\nuitka\nodes\TryNodes.py", line 157, in computeStatement
    statement,
nuitka.Errors.NuitkaOptimizationError:
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementAssignmentVariable" line="3315" owner="__main__$$$function_1_main" is_temp="False" var_type="object" variable_name="line">
      <role name="source">
        <node kind="ExpressionSliceLookup" line="3315">
          <role name="expression">
            <node kind="ExpressionConstantStrRef" line="3315" user_provided="True" constant="'some_text'"/>
          </role>
          <role name="lower">
            <node kind="ExpressionVariableRef" line="3315" owner="__main__$$$function_1_main" variable_name="Nleft"/>
          </role>
          <role name="upper">
            <node kind="ExpressionVariableRef" line="3315" owner="__main__$$$function_1_main" variable_name="Nright"/>
          </role>
        </node>
      </role>
    </node>

**Comment by kayhayen** [comment]
Nuitka caught itself making a mistake there. And the XML output is sufficient for me to know why. Normally I also ask for minimal source reproducer, but this time I can live without.

**Comment by kayhayen** [comment]
I am putting a fix through my internal CI first, this is likely to become part of a next hotfix 0.6.8.4, and is on factory right now:

https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is part of the 0.6.8.4 release I just made.
