### ISSUE TITLE
Dask appears to be unsupported by Nuitka "Cannot convert compiled_frame to frame"

### ISSUE THREAD

**Issue by KishanKishore** [Nuitka/Nuitka#730]
I am facing a problem when running a celery task (which has been obfuscated with nuitka). Here is the information regarding versions and installations:

```
pip install nuitka
```
```
pip freeze | grep Nuitka
Nuitka==0.6.8.2
```
```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
```
```
celery -A project worker -l info --pool=gevent --concurrency=1 --maxtasksperchild=10
```
This is running inside a docker container. I am using a gevent execution pool in celery.

The error occurs when the following line is executed
```
df.compute()
```
where df is a dask dataframe.

This is the stack trace of the error that I am getting. Please note that I had to remove some initial lines of the stack trace which contained code/file names that I cannot share here. 

```
File "venvs/lib/python3.6/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "venvs/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "venvs/lib/python3.6/site-packages/dask/threaded.py", line 69, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
  File "venvs/lib/python3.6/site-packages/gevent/thread.py", line 54, in start_new_thread
    greenlet = Greenlet.spawn(function, *args)
  File "src/gevent/greenlet.py", line 588, in gevent._greenlet.Greenlet.spawn
  File "src/gevent/greenlet.py", line 258, in gevent._greenlet.Greenlet.__init__
  File "src/gevent/greenlet.py", line 150, in gevent._greenlet._extract_stack
TypeError: Cannot convert compiled_frame to frame
Traceback (most recent call last):
  File "venvs/lib/python3.6/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "venvs/lib/python3.6/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "pov/luigi_tasks/preview_data_loader.py", line 55, in run
    self.include_historical_data)
  File "pov/luigi_tasks/clean_data_loader.py", line 107, in load_parquet_data
    df = parquet_loader.run(start_time=start_time, end_time=end_time)
  File "venvs/lib/python3.6/site-packages/deming/parquet/parquet_loader.py", line 314, in run
  File "venvs/lib/python3.6/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "venvs/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "venvs/lib/python3.6/site-packages/dask/threaded.py", line 69, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
  File "venvs/lib/python3.6/site-packages/gevent/thread.py", line 54, in start_new_thread
    greenlet = Greenlet.spawn(function, *args)
  File "src/gevent/greenlet.py", line 588, in gevent._greenlet.Greenlet.spawn
  File "src/gevent/greenlet.py", line 258, in gevent._greenlet.Greenlet.__init__
  File "src/gevent/greenlet.py", line 150, in gevent._greenlet._extract_stack
TypeError: Cannot convert compiled_frame to frame
```
I can provide any more details that are required.

**Comment by kayhayen** [comment]
If you can get it more minimal, it would be nice. 

It seems dask has an opinion about frames, probably for whatever method it wants to use, to transfer to new threads, processes, etc.

Maybe if you could simply use a dask example from https://dask.org/ and let me know if that reproduces the issue. I am definitely more like to work on things, where it's easy to get at the point, rather than guessing around what might reproduce and what not.

**Comment by KishanKishore** [comment]
I have been able to reproduce this with the following example. Hopefully this will be useful:
I am doing this on Mac OS Catalina 10.15.3 with python version 3.6.5

```
pip install celery==4.2.0 nuitka==0.6.8.3  dask==2.6.0 gevent==1.4.0 redis==3.2.0
```
I have 2 files. The first one is named a.py
```
import dask
import dask.dataframe as dd
from celery.decorators import task
from celery import Celery

app = Celery(
    'a'
    ,broker= 'redis://localhost/0'
)

app.conf.update(
    CELERY_RESULT_BACKEND = 'redis://localhost/1'
)

@task(name="compute_task")
def compute_task():
    print("Inside the function")
    df = dask.datasets.timeseries()
    value = df['x'].sum().compute()
    print(value)
```
 The second is named b.py
```
from a import compute_task

if __name__ == '__main__':
        compute_task.delay()
```

Obfuscate a.py with the following command:
```
python -m nuitka --module --plugin-enable=pylint-warnings --python-flag=-OO --remove-output --lto --output-dir={YOUR_OUTPUT_DIR}  a.py
```
Start celery with the following command:
```
celery -A a worker --loglevel=info --pool=gevent
```
Delete the a.py file (or move it to a different directory). b.py should be using a.so and a.pyi files. Run the  b.py file:

```
python b.py
```
This will produce the following error (removed initial lines as I can't post them here):
```
File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
  File "/Users/kishan/Documents/Configuration/venvs/contexalyze/lib/python3.6/site-packages/gevent/thread.py", line 54, in start_new_thread
    greenlet = Greenlet.spawn(function, *args)
  File "src/gevent/greenlet.py", line 588, in gevent._greenlet.Greenlet.spawn
  File "src/gevent/greenlet.py", line 258, in gevent._greenlet.Greenlet.__init__
  File "src/gevent/greenlet.py", line 150, in gevent._greenlet._extract_stack
TypeError: Cannot convert compiled_frame to frame
```

**Comment by kayhayen** [comment]
Ok, I managed to look at the source, and this is from a Cython compilation of the standard Python modules . It makes type checks without a point. I am pretty sure it's an invalid check right there. Probably it applies optimization for known frame type, and cannot bare anything else. I saw that from a C file also included.

I should take note that Cython gives these garbage filenames in tracebacks that are probably from where it got created. I was at first thinking, maybe you have a non-standard version.

Luckily, this coincides with me added `--prefer-source-code` to Nuitka develop version. It will ask you, now about this and compile things with Nuitka instead. Unlike you suggest in your instructions, deleting Python file is not needed, because extension modules are preferred when found in the same place. Nuitka with this switch will not do that though and should be able to overcome this.

You will have to `--include-module=gevent.greenlet` to get that. If you include a module, Nuitka will prefer the included one over ones from `sys.path`. Please report back after using that. Another way might be to delete the Cython generated `.pyd` and work with the Python file, that will only be slower.

At this time I am uncertain how Nuitka stacks up for performance. It normally should be as good or better than Cython, but I don't have much coverage for statements. It's probably a lot slower in some cases still. But Nuitka's C types are getting there, so hopefully we can eventually get people to switch there. The frame access acceleration is e.g. something Nuitka won't do. Maybe it has more tricks, unsure.

I wasn't yet able to follow your instructions, probably because I was also renaming `a` and `b` while doing it. But without using Cython, the error should be impossible to occur, but now I am also convinced to have the solution already.

**Comment by KishanKishore** [comment]
I installed the develop version of nuitka. ```pip freeze | grep Nuitka``` returns ``` Nuitka==0.6.9rc4```. After that I used the following command to obfuscate ```a.py``` (the same file that I mentioned above):
```
python -m nuitka --module --plugin-enable=pylint-warnings --python-flag=-OO --remove-output --lto --prefer-source-code --include-module=gevent.greenlet --output-dir=.  a.py
```
The .so file now generated has a different name than the one generated with the Nutika stable version. The name is:
```
a.cpython-36m-darwin.so
```

After this, I ran the ```b.py``` file but I still see the same error. Am I mistaken in using the command or doing something else incorrectly?

**Comment by kayhayen** [comment]
My best guess is that you didn't remove the old one. Indeed Nuitka creates the more specific files, but they have lower priority than the just `.so`, otherwise I would be confused, as the error would have to come from Cython compilation, and that should no longer be the case.

**Comment by KishanKishore** [comment]
@kayhayen I can repeat the experiment by creating a new folder, move all the files (a.py and b.py) there and then compile with the new command that you suggested and report back to you. 

Can you kindly confirm if the command that I am using is correct?

**Comment by XUWeijiang** [comment]
Any progress? I am stuck on this bug.

**Comment by KishanKishore** [comment]
> Any progress? I am stuck on this bug.

No progress. Did you try the commands that are given there?

**Comment by XUWeijiang** [comment]
> > Any progress? I am stuck on this bug.
> 
> No progress. Did you try the commands that are given there?

I have tried, but not worked. 

My scenario is Flask + gunicorn + gevent + pymongo, and the error message is exactly the same with yours (except the thread pool is created by pymongo).

**Comment by kayhayen** [comment]
Nuitka now asks to recompile modules if source is available, which is frequently is, but not on all systems, but that's the best we can do for now.

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
