### ISSUE TITLE
Question: way to solve problems with compiling a full-blown PyQt5 desktop GUI app

### ISSUE THREAD

**Issue by laszloszolnoki** [Nuitka/Nuitka#743]
Hello,
I just learned about Nuitka today and am wondering if it can be a good replacement for normal CPython frozen with pyinstaller (which works by the way) in order to distribute the app to my users as Windows executable.
I'm not sure if I am trying to compile it the right way.
It is important for me to use 32-bit architecture because one of the DBs that need to be used only has a 32-bit ODBC driver.
Below is what I am trying to achieve and what I did and what kind of errors I experienced. Any help is appreciated.
---------------------------------
Application to be compiled: full-blown desktop GUI app (PyQt5)
---------------------------------
imports:
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.Qt import QStandardItemModel, QStandardItem
import base64
import pkg_resources.py2_warn # this is needed because pyinstaller gimmicks
import time
import pandas as pd
import pyodbc
from jinja2 import Environment, FileSystemLoader
import os
import traceback
import sqlite3
import zlib
import openpyxl # this is needed because pyinstaller gimmicks
import re
-------------------------------------------
nuitka --version
0.6.8.3 Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10)
[MSC v.1900 32 bit (Intel)] Executable: C:\Users\lszolnok\dbdict\Scripts\python.exe OS: Windows Arch: x86 
-------------------------------------------
Compiler:
MinGW64 32-bit
gcc --version
gcc (i686-win32-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
------------------------------------------
Run as:
(dbdict) C:\Users\lszolnok\Documents\GitHub\dbdict>python -m nuitka --follow-imports DBDict_test.py 
-----------------------------------------
Errors:
Problem with <Node 'STATEMENT_ASSIGNMENT_VARIABLE' with {'variable': <LocalVariable 'new_style' of 'convert'>}>
at C:\Users\lszolnok\dbdict\lib\site-packages\pandas\core\internals\blocks.py:2816 Problem with <Node 'STATEMENT_LOOP'>
at C:\Users\lszolnok\dbdict\lib\site-packages\pandas\core\internals\blocks.py:2815 Problem with <Node 'STATEMENT_TRY'>
at C:\Users\lszolnok\dbdict\lib\site-packages\pandas\core\internals\blocks.py:2815 Problem with <Node 'STATEMENT_TRY'>
at C:\Users\lszolnok\dbdict\lib\site-packages\pandas\core\internals\blocks.py:2802
Nuitka:WARNING: Problem creating function code 'pandas$core$internals$blocks$$$function_154_convert'.
Nuitka:WARNING: Problem creating code for module <Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\lszolnok\\dbdict\\lib\\site-packages\\pandas\\core\\internals\\blocks.py', 'module_name': <ModuleName pandas.core.internals.blocks>}>.
Traceback (most recent call last):
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\__main__.py", line 195, in <module> main()
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\__main__.py", line 188, in main MainControl.main()
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\MainControl.py", line 749, in main result, options = compileTree(main_module=main_module)
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\MainControl.py", line 648, in compileTree makeSourceDirectory(main_module=main_module)
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\MainControl.py", line 351, in makeSourceDirectory module_name=module.getFullName(),
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeGeneration.py", line 431, in prepareModuleCode function_body=function_body, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeGeneration.py", line 366, in generateFunctionBodyCode cross_module=function_body.isCrossModuleUsed()
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\FunctionCodes.py", line 572, in getFunctionCode needs_exception_exit=needs_exception_exit,
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\FunctionCodes.py", line 609, in _getFunctionCode context=context,
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 223, in generateStatementSequenceCode statement_sequence=statement_sequence, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 212, in _generateStatementSequenceCode statement=statement, emit=statement_emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 172, in generateStatementCode statement=statement, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\TryCodes.py", line 87, in generateTryCode statement_sequence=tried_block, emit=emit, allow_none=False, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 223, in generateStatementSequenceCode statement_sequence=statement_sequence, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 207, in _generateStatementSequenceCode statement_sequence=statement, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\FrameCodes.py", line 128, in generateStatementsFrameCode statement_sequence=statement_sequence, emit=local_emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 212, in _generateStatementSequenceCode statement=statement, emit=statement_emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 172, in generateStatementCode statement=statement, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\TryCodes.py", line 87, in generateTryCode statement_sequence=tried_block, emit=emit, allow_none=False, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 223, in generateStatementSequenceCode statement_sequence=statement_sequence, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 212, in _generateStatementSequenceCode statement=statement, emit=statement_emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 172, in generateStatementCode statement=statement, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\LoopCodes.py", line 71, in generateLoopCode context=context,
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 223, in generateStatementSequenceCode statement_sequence=statement_sequence, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 212, in _generateStatementSequenceCode statement=statement, emit=statement_emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\CodeHelpers.py", line 172, in generateStatementCode statement=statement, emit=emit, context=context
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\VariableCodes.py", line 86, in generateAssignmentVariableCode context=context,
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\VariableCodes.py", line 368, in getVariableAssignmentCode context=context,
File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka\codegen\c_types\CTypeNuitkaBools.py", line 37, in emitVariableAssignCode assert not in_place AssertionError
-------------------------------------------------------EOF

**Comment by kayhayen** [comment]
The error you got happened to already have a fix on its way to release, it's in 0.6.8.4 which I just put out moments ago. That was a regression. Hopefully it will just work for you now.

**Comment by kayhayen** [comment]
Just to add a bit of information, this was reported by email from my Debian sponsor and wasn't on Github, when an in-place operation on a boolean was to be executed, the code generation didn't know what to do, and asserted against that. Now optimization lowers these kinds of operations to normal operations, as there is no different between e.g. `a ^= b` and `a = a ^ b`, and code generation is again not seeing in-place assignments for that C type.

These are symptoms of Nuitka code analysis, esp. for loops having improved, while the C types code generations are still in their infancy.

**Comment by laszloszolnoki** [comment]
Thanks for the quick response, I installed Nuitka 0.6.8.4
and ran the following:

python -m nuitka --follow-imports --show-progress --enable-plugin=qt-plugins --enable-plugin=numpy DBDict_test.py 

Output:
...
Nuitka:INFO:Optimizing module '_virtualenv', 0 more modules to go after that.                                           Nuitka:INFO:Doing module local optimizations for '_virtualenv'.                                                         Nuitka:INFO: Total memory usage before generating C code: 399.23 MB (418627584 bytes):                                  Nuitka:INFO: Total memory usage before running scons: 407.13 MB (426909696 bytes):                                      Traceback (most recent call last):                                                                                        File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\__main__.py", line 195, in <module>      main()                                                                                                                File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\__main__.py", line 188, in main          MainControl.main()                                                                                                    File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\MainControl.py", line 761, in main       executePostProcessing(OutputDirectories.getResultFullpath())                                                          File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\PostProcessing.py", line 72, in executePostProcessing                                                                                                            lang_id=0,                                                                                                            File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\utils\WindowsResources.py", line 247, in addResourceToFile                                                                                                       _closeFileWindowsResources(update_handle)                                                                             File "C:\Users\lszolnok\dbdict\lib\site-packages\nuitka-0.6.8.4-py3.6.egg\nuitka\utils\WindowsResources.py", line 165, in _closeFileWindowsResources                                                                                              raise ctypes.WinError()                                                                                             OSError: [WinError 110] The system cannot open the device or file specified.

**Comment by kayhayen** [comment]
This is a known issue I think, it's seen sporadically, even in my CI. I suspect that Virus checkers hold a lock on the program. Windows Defender can whitelist directories, that can help. If this is 100% reproducible, make it a new issue, and I can add debugging.

**Comment by laszloszolnoki** [comment]
Thanks for the prompt feedback!
Hmmm..maybe I'm a step closer to the solution.
After having disabled the Windows Defender Firewall (I'm using a Windows 10 Pro 64-bit Virtual Machine on Azure, Intel Xeon Platinum 8171M /v/CPU if it adds anything), the program compiled without errors. Nuitka produced an exe file in the project directory, which doesn't run:

(dbdict) C:\Users\lszolnok\Documents\GitHub\dbdict>DBDict_test.exe                                                      Traceback (most recent call last):                                                                                        File "C:\Users\lszolnok\Documents\GitHub\dbdict\DBDict_test.py", line 6, in <module>                                      from PyQt5 import QtCore, QtGui, QtWidgets, uic                                                                       File "<frozen importlib._bootstrap>", line 961, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 655, in _load_unlocked                                                       File "C:\Users\lszolnok\dbdict\lib\site-packages\PyQt5\__init__.py-preLoad", line 3, in <module PyQt5-preLoad>        NameError: name '__nuitka_binary_dir' is not defined

**Comment by kayhayen** [comment]
Looks to me as if you are not using --standalone, yet use a plugin that expects it to be used. This may be sort of a regression from recent plugin changes, now you can load any plugin, previously it had to be relevant.
