### ISSUE TITLE
Very long compile times for pytorch standalone build

### ISSUE THREAD

**Issue by melandur** [Nuitka/Nuitka#754]
Encountered the same infinite loop error #701  on windows.
Without the --standalone flag everything works as expected.
Tested my setup with other libraries like numpy, matplotlib, qt and they did just fine.

### Version
Nuitka 0.6.8.4
Python: 3.7.6 (default, Jan 8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Miniconda3\envs\d\python.exe
OS: Windows
Arch: x86_64

### Cmd
python -m nuitka --standalone --plugin-enable=torch --mingw64 main.py

### Code (https://github.com/jcjohnson/pytorch-examples)
    import torch

    if __name__ == '__main__':
        device = torch.device('cpu')
        # device = torch.device('cuda') # Uncomment this to run on GPU

        # N is batch size; D_in is input dimension;
        # H is hidden dimension; D_out is output dimension.
        N, D_in, H, D_out = 64, 1000, 100, 10

        # Create random input and output data
        x = torch.randn(N, D_in, device=device)
        y = torch.randn(N, D_out, device=device)

        # Randomly initialize weights
        w1 = torch.randn(D_in, H, device=device)
        w2 = torch.randn(H, D_out, device=device)

        learning_rate = 1e-6
        for t in range(500):
          # Forward pass: compute predicted y
          h = x.mm(w1)
          h_relu = h.clamp(min=0)
          y_pred = h_relu.mm(w2)

          # Compute and print loss; loss is a scalar, and is stored in a PyTorch Tensor
          # of shape (); we can get its value as a Python number with loss.item().
          loss = (y_pred - y).pow(2).sum()
          print(t, loss.item())

          # Backprop to compute gradients of w1 and w2 with respect to loss
          grad_y_pred = 2.0 * (y_pred - y)
          grad_w2 = h_relu.t().mm(grad_y_pred)
          grad_h_relu = grad_y_pred.mm(w2.t())
          grad_h = grad_h_relu.clone()
          grad_h[h < 0] = 0
          grad_w1 = x.t().mm(grad_h)

         # Update weights using gradient descent
          w1 -= learning_rate * grad_w1
          w2 -= learning_rate * grad_w2

**Comment by melandur** [comment]
Was able to finish the compilation (on linux, windows not tested yet) by by using numpy and recurse:

python -m nuitka --standalone --recurse-all --enable-plugin=numpy --plugin-enable=torch --follow-imports main.py

### New Error
My main is called test_pytorch.py
Seems like the there are still dependencies in the anaconda env.
Is there a way to include packages on the env sitepackage level into the compilation?

## Error Log
Traceback (most recent call last):
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/_utils_internal.py", line 46, in get_source_lines_and_file
  File "/home/melandur/anaconda3/envs/deepbratumia/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/melandur/anaconda3/envs/deepbratumia/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/test_pytorch.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/__init__.py", line 367, in <module torch>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/distributions/__init__.py", line 112, in <module torch.distributions>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/distributions/von_mises.py", line 54, in <module torch.distributions.von_mises>
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/jit/__init__.py", line 1287, in script
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/jit/frontend.py", line 164, in get_jit_def
  File "/home/melandur/Desktop/DeepBratumIA_0/test_pytorch.dist/torch/_utils_internal.py", line 53, in get_source_lines_and_file
OSError: Can't get source for <compiled_function _rejection_sample at 0x7fd06363cd70>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code

**Comment by kayhayen** [comment]
I am not sure how useful it is at all to compile things done by torch, as it seems to be its own compiler.

That said, future version of Nuitka will include the source code in dist folders, so this would work in a sense, but right now that's not supported. Once I finish my constants branch for standalone, I can look at this surely, why it takes so long to compile in C, if it still does, I expect it not to, but there might be scalability problems I don't know about.

**Comment by melandur** [comment]
## Update for Windows
Same example, the compiling finishes but the torch folder is missing in the compiled .dist. Created torch folder and placed the missing torch files in there. Got stuck with an numpy related error. I tried numpy version 1.19.0 and 1.18.0 without any success. Compiling pure numpy code works as expected.

### CMD
python -m nuitka --standalone --recurse-all --follow-imports --plugin-enable=torch --plugin-enable=numpy --mingw64 main.py
    
### Error Log
Traceback (most recent call last):
  File "C:\Users\CorePy\Desktop\DEEPBR~1\TEST_P~1.DIS\test_pytorch.py", line 1, in <module>
  File "C:\Users\CorePy\Desktop\DeepBratumIA_0\test_pytorch.dist\torch\__init__.py", line 136, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

### Environment
nuitka                    0.6.8.4                  pypi_0    pypi
numpy                     1.18.0                   pypi_0    pypi
python                    3.7.4                h5263a28_0
torch                     1.5.1+cu101              pypi_0    pypi
torchvision               0.6.1+cu101              pypi_0    pypi

I don't expect to get an answer on this one, only for the reason to draw a bigger picture.

**Comment by zlyxm** [comment]
hi
      I found that Nuitka plus ' --plugin-enable=torch' will loop infinitely
```
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'numpy.distutils.command.install_headers', 75 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.command.install_headers'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'distutils.command.install_headers', 75 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'distutils.command.install_headers':
Nuitka-Progress:INFO: Optimizing module 'numpy.distutils.command.install_data', 74 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.command.install_data'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'distutils.command.install_data', 74 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'distutils.command.install_data':
Nuitka-Progress:INFO: Optimizing module 'numpy.distutils.command.sdist', 73 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.command.sdist'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'numpy.distutils.command.build_scripts', 72 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.command.build_scripts'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Finished with the module.
Nuitka-Progress:INFO: Optimizing module 'distutils.command.build_scripts', 72 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'distutils.command.build_scripts':
Nuitka-Progress:INFO: Optimizing module 'numpy.distutils.command.build_src', 71 more modules to go after that.
Nuitka-Progress:INFO: Doing module local optimizations for 'numpy.distutils.command.build_src'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
```

**Comment by kayhayen** [comment]
That numpy error has been fixed in 0.6.10.x already.

**Comment by gitabtion** [comment]
Hi, I have the same problem, it spend very long time to compile pytorch code (standalone, about 30 minutes). and get error ``TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code`` by run the binary file.

## version
torch=1.5.1
nuitka=0.6.11.5
transformers=3.3.0
numpy=1.19.4
python=3.6.9
OS: CentOS7
Arch: x86_64

**Comment by melandur** [comment]
@gitabtion
I presume you already used the   '--plugin-enable=torch ' and '--plugin-enable=numpy ' flags. 
Therefore, you could try to exclude the pytorch library from the compiling process and copy the torch folder manually to the binary main.dist folder.
 '--nofollow-import-to=torch' will exclude pytorch (you will find the torch folder in your local env)

**Comment by gitabtion** [comment]
@melandur 
Thanks! That problem was solved by your way, but I got a new problem.
```
  File "/home/yyuser/nlp/codes/dev/AlgorithmUtils/run.dist/algorithm_utils/models/modeling_recognizer.py", line 9, in <module algorithm_utils.models.modeling_recognizer>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/yyuser/nlp/codes/dev/AlgorithmUtils/run.dist/transformers/__init__.py", line 124, in <module transformers>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/yyuser/nlp/codes/dev/AlgorithmUtils/run.dist/transformers/pipelines.py", line 37, in <module transformers.pipelines>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/yyuser/nlp/codes/dev/AlgorithmUtils/run.dist/transformers/tokenization_auto.py", line 72, in <module transformers.tokenization_auto>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/yyuser/nlp/codes/dev/AlgorithmUtils/run.dist/transformers/tokenization_longformer.py", line 44, in <module transformers.tokenization_longformer>
SystemError: /tmp/build/80754af9/python_1564510748219/work/Objects/dictobject.c:1561: bad argument to internal function
```

**Comment by kayhayen** [comment]
Manual copying is not supported, I am not considering any of that.

**Comment by bulingda** [comment]
I might have a similar problem but how do I solve this?
`Traceback (most recent call last):
  File "/tmp/.mount_main1.W8TBXX/torch/_utils_internal.py", line 46, in get_source_lines_and_file
  File "/tmp/.mount_main1.W8TBXX/inspect.py", line 955, in getsourcelines
  File "/tmp/.mount_main1.W8TBXX/inspect.py", line 786, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_main1.W8TBXX/main.py", line 23, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/.mount_main1.W8TBXX/torch/__init__.py", line 367, in <module torch>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/.mount_main1.W8TBXX/torch/distributions/__init__.py", line 112, in <module torch.distributions>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/tmp/.mount_main1.W8TBXX/torch/distributions/von_mises.py", line 54, in <module torch.distributions.von_mises>
  File "/tmp/.mount_main1.W8TBXX/torch/jit/__init__.py", line 1287, in script
  File "/tmp/.mount_main1.W8TBXX/torch/jit/frontend.py", line 164, in get_jit_def
  File "/tmp/.mount_main1.W8TBXX/torch/_utils_internal.py", line 53, in get_source_lines_and_file
OSError: Can't get source for <compiled_function _rejection_sample at 0x7f5227fabaa0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code
`

**Comment by melandur** [comment]
I guess the first step would be to provide more info, for example (grabbed from nuitka new issue template):

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
* python -m nuitka --version
* How did you install Nuitka and Python
*  Did you use pip, anaconda, deb, rpm, from source, in a virtualenv or not,
  this is very important usually.
* The specific PyPI names and versions
* Some code example to recreate the error

**Comment by bulingda** [comment]
> I guess the first step would be to provide more info, for example (grabbed from nuitka new issue template):
> 
> * Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
> * python -m nuitka --version
> * How did you install Nuitka and Python
> * Did you use pip, anaconda, deb, rpm, from source, in a virtualenv or not,
>   this is very important usually.
> * The specific PyPI names and versions
> * Some code example to recreate the error

1.Nuitka version
```
0.6.17.5
Commercial: None
Python: 3.7.8 (default, Nov  1 2021, 16:43:48) 
Executable: /usr/local/bin/python3
OS: Linux
Arch: x86_64
```
2.Installation method
`python -m pip install nuitka`
3.I'm not using a virtual environment

**Comment by kayhayen** [comment]
I have done a lot of anti-bloat work for torch and latest Torch is supposed to work with the plugin activated on 0.8.1
