### ISSUE TITLE
Nuitka compilation stuck module dropbox

### ISSUE THREAD

**Issue by BlackRouter** [Nuitka/Nuitka#763]
```
0.6.8.4
Python: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
Executable: D:\Project\Moeinsoft\MoeinBackup\venv36\Scripts\python.exe
OS: Windows
Arch: x86
Compiler: MSVC x86
```

i use dropbox module in my project and i use this switch for compilation:

`nuitka test.py --recurse-all --standalone --show-progress`

`pip install dropbox`

stuck at : `Nuitka:INFO:Doing module local optimizations for 'dropbox.team_log'.`

![2020-06-25_121047](https://user-images.githubusercontent.com/15177510/85678135-6f539e00-b6dd-11ea-8800-222bbbba449a.jpg)

**Comment by kayhayen** [comment]
There is no minimal reproducer though. If there was, I would look into it.

**Comment by BlackRouter** [comment]
```
Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'D:\\Project\\Moeinsoft\\MoeinBackup\\venv36\\lib\\site-packages\\dropbox\\team_log.py', 'module_name': <ModuleName dropbox.team_log>}>'.
Traceback (most recent call last):
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\__main__.py", line 195, in <module>
    main()
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\__main__.py", line 188, in main
    MainControl.main()
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\MainControl.py", line 739, in main
    main_module = createNodeTree(filename=filename)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\MainControl.py", line 142, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\Optimization.py", line 619, in optimize
    makeOptimizationPass(initial_pass=True)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\Optimization.py", line 531, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\Optimization.py", line 168, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 503, in computeModule
    trace_collection=self.trace_collection
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\AssignNodes.py", line 281, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 543, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\OutlineNodes.py", line 225, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 562, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\nodes\TryNodes.py", line 165, in computeStatement
    collection_exception_handling.mergeMultipleBranches(exception_collections)
  File "D:\Project\Moeinsoft\MoeinBackup\venv36\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 631, in mergeMultipleBranches
    variable_versions[variable].add(version)
KeyboardInterrupt
Terminate batch job (Y/N)? y
```

**Comment by kayhayen** [comment]
Why the close?

**Comment by IETTCQV** [comment]
I have the same problem

**Comment by kayhayen** [comment]
@IETTCQV please open a new issue with proper information
