### ISSUE TITLE
hinted compilation exits with error

### ISSUE THREAD

**Issue by eyeing** [Nuitka/Nuitka#773]
Hi:

  I've been experimenting with different versions of nuitka in order to make sure this hasn't already been fixed. I'm working on isolating the error, i can probably isolate it into a small testcase. For now, I'll post the problem i'm facing; it is generated through hinted_compilation:

**bash-4.2$ nuitka3 --version
0.6.8.4
Python: 3.8.2 (default, Jun 16 2020, 17:24:50) 
Executable: /vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/bin/python3.8
OS: Linux
Arch: x86_64
**
bash-4.2$ python3 nuitka-hints.py myfile
...
Nuitka:WARNING: Not recursing to unused 'xml.parsers.expat'.
Nuitka:WARNING: Problem creating function code 'sortedcontainers$sortedlist$$$function_16__build_index'.
Nuitka:WARNING: Problem creating code for module <Node 'COMPILED_PYTHON_MODULE' with {'filename': '/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/sortedcontainers/sortedlist.py', 'module_name': <ModuleName sortedcontainers.sortedlist>}>.
Traceback (most recent call last):
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/__main__.py", line 195, in <module>
    main()
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/MainControl.py", line 749, in main
    result, options = compileTree(main_module=main_module)
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/MainControl.py", line 648, in compileTree
    makeSourceDirectory(main_module=main_module)
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/MainControl.py", line 348, in makeSourceDirectory
    prepared_modules[c_filename] = CodeGeneration.prepareModuleCode(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/CodeGeneration.py", line 430, in prepareModuleCode
    function_code, function_context = generateFunctionBodyCode(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/CodeGeneration.py", line 355, in generateFunctionBodyCode
    function_code = getFunctionCode(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/FunctionCodes.py", line 562, in getFunctionCode
    return _getFunctionCode(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/FunctionCodes.py", line 595, in _getFunctionCode
    setupFunctionLocalVariables(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/FunctionCodes.py", line 486, in setupFunctionLocalVariables
    variable_code_name, variable_c_type = decideLocalVariableCodeType(
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/VariableCodes.py", line 260, in decideLocalVariableCodeType
    c_type = getPickedCType(variable, context)
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/codegen/VariableCodes.py", line 200, in getPickedCType
    shapes = variable.getTypeShapes()
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/Variables.py", line 273, in getTypeShapes
    trace.getTypeShape().emitAlternatives(result.add)
  File "/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/nuitka/nodes/shapes/StandardShapes.py", line 904, in emitAlternatives
    type_shape.emitAlternatives(emit)
TypeError: emitAlternatives() missing 1 required positional argument: 'emit'

**Comment by kayhayen** [comment]
This file is likely all it takes: `/vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/lib/python3.8/site-packages/sortedcontainers/sortedlist.py`

**Comment by eyeing** [comment]
[nuitka_773.zip](https://github.com/Nuitka/Nuitka/files/4888062/nuitka_773.zip)

Sorry for the delay, please see the included package:
dask_test.py has the minimal code
toy.csv is the loaded data by the code
run_hinted has the exact commands to reproduce the error

3 other files related to hinted compilation to complete the package.

**Comment by manukgitn** [comment]
Hello,
Got  similar problem when using SortedDict (from sortedcontainers ): 

python -m nuitka  --version
0.6.8.4
Python: 3.7.4 (default, Dec 17 2019, 05:32:05) 
Executable: /home/manuk/.virtualenvs/fin_p_3.7/bin/python
OS: Linux
Arch: x86_64

 python -m nuitka  --verbose --follow-imports toy.py
....

Nuitka:WARNING: Problem creating function code 'sortedcontainers$sortedlist$$$function_16__build_index'.
Nuitka:WARNING: Problem creating code for module <Node 'COMPILED_PYTHON_MODULE' with {'filename': '/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/sortedcontainers/sortedlist.py', 'module_name': <ModuleName sortedcontainers.sortedlist>}>.
Traceback (most recent call last):
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 195, in <module>
    main()
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 749, in main
    result, options = compileTree(main_module=main_module)
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 648, in compileTree
    makeSourceDirectory(main_module=main_module)
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 351, in makeSourceDirectory
    module_name=module.getFullName(),
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/CodeGeneration.py", line 431, in prepareModuleCode
    function_body=function_body, context=context
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/CodeGeneration.py", line 366, in generateFunctionBodyCode
    cross_module=function_body.isCrossModuleUsed()
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/FunctionCodes.py", line 572, in getFunctionCode
    needs_exception_exit=needs_exception_exit,
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/FunctionCodes.py", line 600, in _getFunctionCode
    temp_variables=temp_variables,
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/FunctionCodes.py", line 487, in setupFunctionLocalVariables
    context=context, variable=variable
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/VariableCodes.py", line 260, in decideLocalVariableCodeType
    c_type = getPickedCType(variable, context)
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/codegen/VariableCodes.py", line 200, in getPickedCType
    shapes = variable.getTypeShapes()
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/Variables.py", line 273, in getTypeShapes
    trace.getTypeShape().emitAlternatives(result.add)
  File "/home/manuk/.virtualenvs/fin_p_3.7/lib/python3.7/site-packages/nuitka/nodes/shapes/StandardShapes.py", line 904, in emitAlternatives
    type_shape.emitAlternatives(emit)
TypeError: emitAlternatives() missing 1 required positional argument: 'emit'


Reproducible small example attached:
[toy.zip](https://github.com/Nuitka/Nuitka/files/4913782/toy.zip)

**Comment by kayhayen** [comment]
I managed to reproduce this with the toy test case. It's good in that it used no hinted compilation. I think this might be easy, I will look into it.

**Comment by kayhayen** [comment]
The fix is on factory http://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This might become a hotfix if there is another one for 0.6.8 or go straight for 0.6.9, not sure yet.

**Comment by manukgitn** [comment]
Checked on toy.py.
Binary has been created and run successful.
Thank you.

**Comment by eyeing** [comment]
Hi:

  Would it be possible to get this into 0.6.9? I want to push this through the pipeline that would include the pypi versions.

**Comment by eyeing** [comment]
btw, thank you manukgitn for uploading a better testcase and kay for coming up with a solution.

**Comment by kayhayen** [comment]
This is part of the latest pre-release.

**Comment by eyeing** [comment]
Thank you! testing.

**Comment by eyeing** [comment]
Sorry for the delay; this is verified to be fixed in develop.

**Comment by kayhayen** [comment]
This is in the 0.6.9 release
