### ISSUE TITLE
windows win32com: ModuleNotFoundError: No module named 'win32com.gen_py.00020905-0000-0000-C000-000000000046x0x8x7'

### ISSUE THREAD

**Issue by retsyo** [Nuitka/Nuitka#787]
I installed `Nuitka-0.6.9rc5.tar.gz` on my `Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32` via `python setup.py install`

The following code can run as expected with `python testMSOffice.py`

```
import win32com, sys, string, win32api, traceback
import win32com.client.dynamic
from win32com.test.util import CheckClean
import pythoncom
from win32com.client import gencache
from pywintypes import Unicode

word = win32com.client.gencache.EnsureDispatch("Word.Application")

def TestWord8(word):
    word.Visible = 1
    doc = word.Documents.Add()
    wrange = doc.Range()
    for i in range(10):
        wrange.InsertAfter("Hello from Python %d\n" % i)
    paras = doc.Paragraphs
    doc.SaveAs('r:/xxx.docx')
    doc.Close(SaveChanges = 0)
    word.Quit()
    win32api.Sleep(1000) # Wait for word to close, else we
    # may get OA error.

TestWord8(word)

pythoncom.CoUninitialize()
```

then I open x64 Native Tools Command Prompt for Microsoft Visual Studio 2019 Community, and do

```
python -m nuitka --standalone --windows-dependency-tool=pefile testMSOffice.py
```

The processing log is

```bash
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "L:\prg\py\ANACON~1\lib\SITE-P~1\NUITKA~1.EGG\nuitka\build\SINGLE~1.SCO", line 535, in createEnvironment

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "L:\prg\py\ANACON~1\lib\SITE-P~1\NUITKA~1.EGG\nuitka\build\SINGLE~1.SCO", line 1857, in <module>

```

Then I run the build `testMSOffice.exe`

```bash
cd testMSOffice.dist
testMSOffice.exe
```

the log is

```bash
Traceback (most recent call last):
  File "r:\test\testMSOffice.dist\testMSOffice.py", line 8, in <module>
  File "r:\test\testMSOffice.dist\win32com\client\gencache.py", line 534, in EnsureDispatch
  File "r:\test\testMSOffice.dist\win32com\client\gencache.py", line 518, in EnsureModule
  File "r:\test\testMSOffice.dist\win32com\client\gencache.py", line 287, in MakeModuleForTypelib
  File "r:\test\testMSOffice.dist\win32com\client\makepy.py", line 286, in GenerateFromTypeLibSpec
  File "r:\test\testMSOffice.dist\win32com\client\gencache.py", line 548, in AddModuleToCache
  File "r:\test\testMSOffice.dist\win32com\client\gencache.py", line 627, in _GetModule
ModuleNotFoundError: No module named 'win32com.gen_py.00020905-0000-0000-C000-000000000046x0x8x7'
```

but in fact, `gen_py` directory and sub-module( for example `00020905-0000-0000-C000-000000000046x0x8x7`) are created by `win32com` during running, which we can't make them as pre-defined name/module.

So any hints? Thanks

**Comment by hcam93** [comment]
Did you ever solve this problem? I am having the same issue

**Comment by kayhayen** [comment]
I would need a reproducer that doesn*t involve a COM compenent I don*t have. Any suggestions what to use for `EnsureDispatch` that is on Windows 10 right after install?

**Comment by kayhayen** [comment]
Closing for lack of feedback. Please open a new issue with reproducers that work for me.
