### ISSUE TITLE
scikit-learn standalone ctypes module

### ISSUE THREAD

**Issue by ryancinsight** [Nuitka/Nuitka#815]
0.6.9rc6
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
Executable: E:\winpytest\WPy64-3760\python-3.7.6.amd64\python.exe
OS: Windows
Arch: x86_64

I installed python using winpython:
http://winpython.sourceforge.net/
and used pip install to get the newest prerelease from GitHub. I used this because I had the same issue as someone else with the released version but I am blanking on what it was I will look through issues and update.

There were no issues when I ran standalone on hello.py. I had associated my issue with scikit-learn and tried to create a simple test modifying hello.py. Scikit-learn version 0.22.1:
```
from sklearn.decomposition import PCA


def talk(message):
    return "Talk " + message

def main():
    print( talk("Hello World"))

if __name__ == "__main__":
    main()
    a=PCA()
```

What I ran, I used numpy plugin just in case:
python -m nuitka hello.py  --mingw64 --standalone --show-progress --show-scons --follow-imports --plugin-enable=numpy

Everything compiles fine, However when I run it I get:
E:\winpytest\WPy64-3760\notebooks>"E:\winpytest\WPy64-3760\notebooks\hello.dist\hello.exe"
Traceback (most recent call last):
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\hello.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\sklearn\__init__.py", line 80, in <module sklearn>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\sklearn\_distributor_init.py", line 18, in <module sklearn._distributor_init>
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\ctypes\__init__.py", line 364, in __init__
OSError: [WinError 126] The specified module could not be found

Based on another error someone reported and fixed by adding specific folder I tried this as well and got:
E:\winpytest\WPy64-3760\notebooks>"E:\winpytest\WPy64-3760\notebooks\hello.dist\hello.exe"
Traceback (most recent call last):
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\hello.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\sklearn\__init__.py", line 80, in <module sklearn>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\sklearn\_distributor_init.py", line 18, in <module sklearn._distributor_init>
  File "E:\winpytest\WPy64-3760\notebooks\hello.dist\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found"

_dlopen is just "from _ctypes import LoadLibrary as _dlopen" which _ctypes is indeed being shown in my dist folder so I am at a loss at this point.

**Comment by kayhayen** [comment]
Adding folders is murking the waters. I am not sure how well WinPython works with Nuitka.

**Comment by kayhayen** [comment]
I was getting this one with CPython:

```
File "C:\Users\kayha\repos\Py2C\MINILE~1.DIS\ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'C:\Users\kayha\repos\Py2C\MINILE~1.DIS\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

So far, we do not copy and DLLs specifically for sklearn, seems that is no longer correct.

**Comment by kayhayen** [comment]
Ah, my bad, I shortened the traceback too much, this is the code that uses ctypes there:

```
if os.name == 'nt':
    # Pre-load the DLL stored in sklearn/.libs by convention.
    dll_path = op.join(op.dirname(__file__), '.libs', 'vcomp140.dll')
    WinDLL(op.abspath(dll_path))

```

Adding that as a DLL dependency will be very possible.

**Comment by kayhayen** [comment]
It seems there was an `extra-dlls` folder previously, I think I recall seeing it once myself. That got renamed to to `.libs` apparently, as that one is empty.

While messing with this area of the plugin system, I wonder if it's not time to shift the copying of files out of the plugins, while then making them repeat what they did. Also it seems we went to the effort of lowering the DLL structure to top level, which may not work with this code anymore. This might be a bit breaking, but as it is now, the code is hard to read.

**Comment by kayhayen** [comment]
This has been fixed a long time ago I believe. The example is even one I regularily check.
