### ISSUE TITLE
erro scipy.interpolate

### ISSUE THREAD

**Issue by paulobionica** [Nuitka/Nuitka#817]
I use this command: 
`python -m nuitka --standalone --enable-plugin=numpy  --include-module=scipy.interpolate.interp1d --plugin-enable=pylint-warnings  --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse main.py`

output: 
Nuitka:WARNING: Not recursing to unused 'scipy.interpolate'.
Nuitka-Plugins:INFO: numpy: Copied 1 file from 'numpy' installation.

execution error:

Traceback (most recent call last):
  File "D:\Bionica\Repositorios\asyncserver\main.dist\main.py", line 34, in <module>
  File "D:\Bionica\Repositorios\asyncserver\main.dist\user_interface.py", line 11, in <module user_interface>
  File "D:\Bionica\Repositorios\asyncserver\main.dist\signalrs.py", line 8, in <module signalrs>
ModuleNotFoundError: No module named 'scipy'

**Comment by kayhayen** [comment]
This would need a minimal reproducer, it currently has not even any code attached.

**Comment by paulobionica** [comment]
```
import logging
from enum import IntEnum, auto
import asyncio
import numpy as np
from scipy.interpolate import interp1d


class State(IntEnum):
    """State definition to be used in state machines.
    """
    NOT_INITIALIZED = auto()
    TIMEOUT = auto()
    INITIALIZING = auto()
    PAUSE = auto()
    READY = auto()
    RUNNING = auto()


class SignalRS():

    _class_state = State.NOT_INITIALIZED
    _signals = list()
    _interpolation_period = float()
    _next_call_time = float()
    _group_time = np.array([], float)
    _group_time_min = float()
    _group_time_max = float()
    _counter = 0

    _loop = asyncio.AbstractEventLoop
    _samples_per_set = int()
    _sets_per_group = int()
    _round_digits = int()
    _sample_period = float()
    _signals_output = asyncio.Queue(maxsize=1024*64)
    _global_timeout = float()

    def __init__(self, name, source, timeout, unit=None,
                 interpolation_kind='nearest'):
        if self._class_state == State.NOT_INITIALIZED:
            raise AttributeError
        self._name = name
        self._source = source
        self._timeout = timeout
        self._unit = unit
        self._interpolation_kind = interpolation_kind
        self._signal_state = State.NOT_INITIALIZED
        self._non_empty_input_counter = 0
        self._time_offset = float()
        self._input = np.array(([], []), dtype=float).T
        self._result = np.array(([], []), dtype=float).T
        self._signals.append(self)
        self._logger = logging.getLogger(__name__)

    def _interpolate(self):
        self._assure_class_initialization()
        number_of_new_samples = self._source.qsize()
        if number_of_new_samples > 0:
            new_samples = np.empty((number_of_new_samples, 2), dtype=float)
            for i in range(number_of_new_samples):
                new_samples[i, :] = self._source.get_nowait()
                self._source.task_done()
            new_samples[:, 0] -= self._time_offset
            self._input = np.vstack((self._input, new_samples))
            self._non_empty_input_counter += 1
            if self._non_empty_input_counter > 1:
                if len(self._input) > 1:
                    input_time_min = self._input[0, 0]
                    input_time_max = self._input[-1, 0]
                    # Get all the input points and make them equidistant.
                    equally_spaced_input_time = np.linspace(
                        input_time_min,
                        input_time_max,
                        self._input.shape[0]
                    ).round(self._round_digits)
                    function = interp1d(
                        equally_spaced_input_time,
                        self._input[:, 1],
                        kind=self._interpolation_kind
                    )
                    mask = np.logical_and(
                        self._group_time >= input_time_min,
                        self._group_time <= input_time_max,
                    )
                    interpolation_time = self._group_time[mask]
                    amplitude = function(interpolation_time)
                    result = np.c_[interpolation_time, amplitude]
                    if self._non_empty_input_counter == 2:
                        self._result = result
                    else:
                        self._result = self._merge(self._result, result)
                        mask = self._input[:, 0] >= self._group_time_min
                        self._input = self._input[mask]
                    # if len(self._result) > 0:
                    #     mask = self._result[:, 0] < self._group_time_min
                    #     mask = np.c_[mask, mask]
                    #     if np.any(mask):
                    #         out = self._result[mask].reshape(-1, 2)
                    #         for point in out:
                    #             self._signals_output.put_nowait(tuple(point))
                    #     self._result = self._result[
                    #         np.logical_not(mask)
                    #     ].reshape(-1, 2)

        else:
            pass  # Now new data. TODO: Need to detect timeout.

    def _merge(self, first, last, method='mean'):
        # The method attribute will be used in future versions to allow
        # different merging strategies.
        self._assure_class_initialization()
        if len(first) == 0 and len(last) > 0:
            return last
        elif len(first) > 0 and len(last) == 0:
            return first
        elif len(first) == 0 and len(last) == 0:
            return first
        # self._logger.info(f'first:\n{first}')
        # self._logger.info(f'last:\n{last}')
        while first[:, 0].min() > last[:, 0].min():
            # This case must not occur, but it's treated here for resilience
            # purpose only.
            last = last[1:]
            if last.shape[0] == 0:
                return first
        _, first_ind, last_ind = np.intersect1d(
            first[:, 0].astype(dtype=float).round(self._round_digits),
            last[:, 0].astype(dtype=float).round(self._round_digits),
            assume_unique=True,
            return_indices=True
        )
        result = np.array(([], []), dtype=float).T
        if first_ind.shape[0] > 0:
            result = first[0:first_ind[0], :]
            result = np.vstack((
                result,
                (first[first_ind, :] + last[last_ind, :]) / 2.0,
            ))
            if last_ind[-1] < last.shape[0]:
                result = np.vstack((
                    result,
                    last[last_ind[-1] + 1:, :]
                ))
        else:
            # If the program enters here, it means that there's no
            # intersection. This case must not occur, but it's treated here for
            # resilience purpose only.
            gap = int((last[0, 0] - first[-1, 0]) / self._sample_period)
            if gap > 1:
                time_gap_fill = np.linspace(
                    first[-1, 0] + self._sample_period,
                    last[0, 0],
                    gap - 1,
                    endpoint=False,
                ).round(self._round_digits)
                gap_fill_amplitude = np.linspace(
                    first[-1, 1],
                    last[0, 0],
                    gap + 1,
                    endpoint=True,
                )
                # self._logger.info(f'time_gap_fill: {time_gap_fill}')
                result = np.vstack((
                    first,
                    np.c_[time_gap_fill, gap_fill_amplitude[1:-1]],
                    last,
                ))
            else:
                result = np.vstack((
                    first,
                    last,
                ))
        return result

    @classmethod
    def setup(cls, loop, samples_per_set, sets_per_group, round_digits,
              sample_period, timeout):
        """Initializes the class.

        The setup method must be called before instantiating any object. It
        defines the output dataframe sample rate, how often the interpolation
        is calculated and how much intersection is used to avoid discontinuity
        and than avoidind the use of extrapolation.

        Parameters
        ----------
        loop : asyncio.AbstractEventLoop
            Use the given event loop to schedule the periodic interpolation
            calculation. The calculation period, in seconds, is given by the
            product of samples_per_set and sample_period.
        samples_per_set : int
            Defines how many samples are used at each calculation cycle.
        sets_per_group : int
            Number of sets used to calculate each interpolation. More groups
            implies in a longer intersection, but at more computational cost.
        round_digits : int
            Number decimal places used to round the times values.
        sample_period : float
            Defines the output sample rate and, when multiplied by the
            samples_per_set, gives the interpolation calculation rate.
        signals_output : asyncio.Queue
            Each enqueued output is a tuple (time, out1, out2, ...) where time
            is given in seconds, rounded to round_digits decimal places, and
            out1, out2, ... are the amplitudes of the registered signals.
        timeout : float
            Timeout limit in seconds.

        Raises
        ------
        AttributeError
            If the class has been already initialized.
        """
        if cls._class_state != State.NOT_INITIALIZED:
            raise AttributeError
        cls._loop = loop
        cls._samples_per_set = int(samples_per_set)
        cls._sets_per_group = int(sets_per_group)
        cls._round_digits = int(round_digits)
        cls._sample_period = round(sample_period, round_digits)
        cls._signals_output = asyncio.Queue(maxsize=1024*512)
        cls._global_timeout = timeout

        cls._class_state = State.INITIALIZING
        cls._interpolation_period = round(
            sample_period * samples_per_set,
            round_digits
        )
        cls._next_call_time = round(loop.time(), round_digits)

    @classmethod
    def _assure_class_initialization(cls):
        if cls._class_state != State.RUNNING:
            raise AttributeError

    @classmethod
    def reset_signals(cls):
        """Must be called after instantiation of all input signal.
        """
        if cls._class_state != State.INITIALIZING:
            raise AttributeError
        for signal in cls._signals:
            if signal._source.qsize() > 0:
                signal._source.queue.clear()
        cls._group_time = np.linspace(
            0,
            (cls._samples_per_set - 1) * cls._sample_period,
            cls._samples_per_set,
        ).round(cls._round_digits)
        cls._group_time_min = cls._group_time.min()
        cls._group_time_max = cls._group_time.max()
        cls._next_call_time = round(
            cls._next_call_time + cls._interpolation_period,
            cls._round_digits
        )
        cls._loop.call_at(cls._next_call_time, cls._recurrent)
        cls._class_state = State.RUNNING

    @classmethod
    def _recurrent(cls):
        """Periodically calculate the interpolation of all signals.
        """
        if cls._class_state == State.RUNNING:
            for signal in cls._signals:
                if signal._signal_state == State.RUNNING:
                    signal._interpolate()
                elif signal._signal_state == State.NOT_INITIALIZED:
                    number_of_new_samples = signal._source.qsize()
                    if number_of_new_samples > 0:
                        signal._input = np.empty((number_of_new_samples, 2),
                                                 dtype=float)
                        for i in range(number_of_new_samples):
                            # signal._input[i, :] = np.array(
                            #     signal._source.get_nowait(),
                            #     dtype=float).reshape(-1, 2)
                            signal._input[i, :] = np.reshape(
                                signal._source.get_nowait(), (-1, 2))
                            signal._source.task_done()
                            # TODO: Think if it's needed to keep original times
                            # and group times together.
                        signal._time_offset = (
                            signal._input[-1, 0]
                            - cls._group_time_max
                        )
                        signal._input[:, 0] -= signal._time_offset
                        mask = signal._input[:, 0] >= 0
                        signal._input = signal._input[mask]
                        signal._non_empty_input_counter += 1
                        signal._signal_state = State.RUNNING
            cls._next()
            cls._next_call_time = round(
                cls._next_call_time + cls._interpolation_period,
                cls._round_digits
            )
            cls._loop.call_at(cls._next_call_time, cls._recurrent)
        elif cls._class_state == State.NOT_INITIALIZED:
            raise AttributeError
        # elif cls._class_state == State.TIMEOUT:
        #     pass
        # elif cls._class_state == State.INITIALIZING:
        #     pass
        # elif cls._class_state == State.PAUSE:
        #     pass
        # elif cls._class_state == State.READY:
        #     pass

    @classmethod
    def _next(cls):
        """Iterates the interpolation machine state.

        The output is updated here too.

        Raises
        ------
        AttributeError
            If the class has not been initialized yet.
        """
        cls._assure_class_initialization()

        if cls._counter > 1:
            output_counter = cls._counter - 2
            output_time = np.linspace(
                output_counter * cls._samples_per_set
                * cls._sample_period,
                ((output_counter + 1) * cls._samples_per_set - 1)
                * cls._sample_period,
                cls._samples_per_set,
            ).round(cls._round_digits)
            for line in range(output_time.size):
                output_line = np.empty((len(cls._signals) + 1),)
                output_line[0] = output_time[line]
                for column in range(len(cls._signals)):
                    idx = np.argwhere(
                        cls._signals[column]._result[:, 0] == output_line[0]
                    ).flatten()
                    col_value = np.nan
                    if idx.size > 0:
                        col_value = cls._signals[column]._result[idx[0], 1]
                    output_line[column + 1] = col_value
                cls._signals_output.put_nowait(tuple(output_line))
            for signal in cls._signals:
                mask = signal._result[:, 0] > output_time[-1]
                signal._result = signal._result[mask]
        cls._group_time = np.linspace(
            (cls._counter * cls._samples_per_set * cls._sample_period),
            (
                (cls._counter + cls._sets_per_group) * cls._samples_per_set - 1
            ) * cls._sample_period,
            cls._samples_per_set * cls._sets_per_group,
        ).round(cls._round_digits)
        cls._group_time_min = cls._group_time.min()
        cls._group_time_max = cls._group_time.max()
        cls._counter += 1

        cls.after_next()

    @classmethod
    def after_next(cls):
        """Abstract method called at the end of the _next method.
        """

    @classmethod
    def get_header(cls):
        sig_label = str()
        header = list()
        header.append('Time (s)')
        for sig in cls._signals:
            sig_label = str(sig._name)
            if sig._unit is not None:
                sig_label += ' (' + str(sig._unit) + ')'
            header.append(sig_label)
        return header
`
```

**Comment by kayhayen** [comment]
Half of your options should give warnings, all of ` --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse` is just garbage. Plus I wonder, what makes people think that reports with --experimental are worth it.
