### ISSUE TITLE
Tests fails in Options.py

### ISSUE THREAD

**Issue by DanySpin97** [Nuitka/Nuitka#818]
Python version: 3.7.6
Platform: Linux

By running tests on latest commit of the develop branch via:

```
python3.7 -B setup.py test
```

I get the following stack trace:

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating Nuitka.egg-info
writing Nuitka.egg-info/PKG-INFO
writing dependency_links to Nuitka.egg-info/dependency_links.txt
writing entry points to Nuitka.egg-info/entry_points.txt
writing top-level names to Nuitka.egg-info/top_level.txt
writing manifest file 'Nuitka.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.pdf'
warning: no files found matching 'Changelog.pdf'
warning: no files found matching 'Developer_Manual.pdf'
warning: no files found matching 'doc/*.1'
writing manifest file 'Nuitka.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 313, in <module>
    "nuitka%s-run = nuitka.__main__:main" % binary_suffix,
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/Nuitka/nuitka/tree/VariableClosure.py", line 32, in <module>
    from nuitka.nodes.FunctionNodes import MaybeLocalVariableUsage
  File "/tmp/Nuitka/nuitka/nodes/FunctionNodes.py", line 40, in <module>
    from nuitka.tree.TreeHelpers import makeDictCreationOrConstant2
  File "/tmp/Nuitka/nuitka/tree/TreeHelpers.py", line 36, in <module>
    from nuitka.nodes.DictionaryNodes import (
  File "/tmp/Nuitka/nuitka/nodes/DictionaryNodes.py", line 46, in <module>
    from .TypeNodes import ExpressionBuiltinType1
  File "/tmp/Nuitka/nuitka/nodes/TypeNodes.py", line 29, in <module>
    from .BuiltinRefNodes import (
  File "/tmp/Nuitka/nuitka/nodes/BuiltinRefNodes.py", line 83, in <module>
    _debug_value = "no_asserts" not in getPythonFlags()
  File "/tmp/Nuitka/nuitka/Options.py", line 542, in getPythonFlags
    for parts in options.python_flags:
AttributeError: 'NoneType' object has no attribute 'python_flags'
```

**Comment by kayhayen** [comment]
There are no tests run this way, however I have fixed the import errors and attribute errors for options, as these are certainly weaknesses of the code.

I am now considering, how to make the test target run our actual tests.

**Comment by kayhayen** [comment]
I didn't quite figure out how to do that last point, and I don't care as much, as RPM build and Debian builds have their own stuff for that, as does CI. I am closing the issue, because I consider it unimportant enough, the code changes are going to land on factory branch soon.
