### ISSUE TITLE
llvmlite / numba cannot be built due to embedded .so file

### ISSUE THREAD

**Issue by eyeing** [Nuitka/Nuitka#824]
nuitka: 0.6.8.4

llvmlite installation comes with a pre-built .so file. Here is the error signature - 

Traceback (most recent call last):
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/ds7_inference_module.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/basics.py", line 3, in <module basics>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/numba/__init__.py", line 14, in <module numba>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/numba/core/config.py", line 16, in <module numba.core.config>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/llvmlite/binding/__init__.py", line 4, in <module llvmlite.binding>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/llvmlite/binding/dylib.py", line 3, in <module llvmlite.binding.dylib>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/project/Jupiter_builds/engineering/ApexEngineeringBuild_ayeung_1598476794.5659375/ds7_inference_module.dist/llvmlite/binding/ffi.py", line 153, in <module llvmlite.binding.ffi>
OSError: Could not load shared object file: libllvmlite.so

If I look into the llvmlite installation directory, the .so file is in the binding directory:
bash-4.2$ ls x86_64/lib/python3.8/site-packages/llvmlite/binding/*.so
libllvmlite.so

Any packages that imports llvmlite (most notably numba) or code that directly uses llvmlite is affected. I'm going to install llvm and try to rebuild llvmlite with the source-code as a potential workaround.

If a testcase is needed for testing, I can try to isolate a simple one.

**Comment by kayhayen** [comment]
Needless to say, a test case is always needed.

**Comment by belonesox** [comment]
> Needless to say, a test case is always needed.

https://github.com/belonesox/nuitka-numba

pipenv based minimal sample.

* Run 0-build.sh to build

Then…
```
[root@stasbox64gb nuitka-numba]# ./1-run-without-llvmlite-so.sh 
Traceback (most recent call last):
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numbar.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/__init__.py", line 19, in <module numba>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/config.py", line 16, in <module numba.core.config>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/llvmlite/binding/__init__.py", line 4, in <module llvmlite.binding>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/llvmlite/binding/dylib.py", line 3, in <module llvmlite.binding.dylib>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/llvmlite/binding/ffi.py", line 153, in <module llvmlite.binding.ffi>
OSError: Could not load shared object file: libllvmlite.so
```

If we copy libllvmlite.so to dist-dir:

```
[stas@stasbox64gb nuitka-numba]$ ./2-run-with-llvmlite-so.sh 
Traceback (most recent call last):
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numbar.py", line 13, in <module>
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/dispatcher.py", line 366, in _compile_for_args
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/dispatcher.py", line 857, in compile
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/dispatcher.py", line 77, in compile
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/dispatcher.py", line 91, in _compile_cached
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/dispatcher.py", line 104, in _compile_core
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/compiler.py", line 602, in compile_extra
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/compiler.py", line 348, in compile_extra
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/untyped_passes.py", line 64, in run_pass
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/bytecode.py", line 204, in __init__
  File "/home/stas/projects/nuitkas/wtf/nuitka-numba/numbar.dist/numba/core/bytecode.py", line 226, in _compute_lineno
KeyError: 2
```

So is it possible to use numba from nuitka compiled projects?

**Comment by belonesox** [comment]
Is the isssue still "need_example"?

**Comment by kayhayen** [comment]
@belonesox I missed your example, sorry, that'a a good one.

The solution is a bit inolved, because I doubt there is a way for this to work without including source code, something I wanted to add to standalone mode for a while. Including only the to be jitted source may also be an option. And of course, my favorite options would be to replace with a Nuitka jit, but we are not good enough yet to do that. I will try to work on all these 3 things as time permits, but it's not a priority. Consider https://nuitka.net/pages/commercial.html if you want, but I will get eventually there without as well.

**Comment by kayhayen** [comment]
It seems numba will not use source code, but bytecode, as I am getting the same callstack in accelerated mode (where `__file__` would allow loading the source code), so this could be attacked by making `inspect.getsource` work with compiled functions and then compiling the bytecode, or including bytecode for compiled functions through e.g. a decorator.

The later fits into ideas where functions would be specialized for some times determined at compile time, and fallbacks exist for cases where we just give up.

Strange it's "nopython", apparently that still works with the NumPy objects. I guess it's not too strict.

**Comment by kayhayen** [comment]
I got the example. This will wait until PGO for Nuitka is implemented, where we will want to allow unused functions to be compiled as bytecode only and from there, we can add source code too. But there won't be a special push for this at this time, but with PGO infrastructure, tracing `inspect.getsource` usage will be relatively easy, to the point where they can be hard coded in the final binary, even without making it go to a source file.

**Comment by qjuppet** [comment]
Hello, I'm having the same issue with nuitka 0.6.18.2: OSError: Could not load shared object file: llvmlite.dll

Is there any workaround or should we wait for a new release?

**Comment by szandara** [comment]
Is there a workaround for this? Is there a way I can import this manually into the distribution directory to unlock the situation?

I was able to build my code but it fails at runtime with the following stack.
I have obfuscated the code imports.

```
Traceback (most recent call last):
  File "/***/***/***.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 33, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 25, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 7, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 12, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 5, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***.py", line 2, in <module *****************>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File /***/***/***/numba/__init__.py", line 19, in <module numba>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***/core/config.py", line 16, in <module numba.core.config>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***/binding/__init__.py", line 4, in <module llvmlite.binding>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***/llvmlite/binding/dylib.py", line 3, in <module llvmlite.binding.dylib>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/***/***/***/llvmlite/binding/ffi.py", line 191, in <module llvmlite.binding.ffi>
OSError: Could not load shared object file: libllvmlite.so
```

**Comment by szandara** [comment]
As a workaround, for all those blocked. What worked for me was to pre-compile all numba files manually. For us it was ok because all numba code was concentrated in a single file.

```
import numpy as np
from numba.pycc import CC

cc = CC("numba_extensions")

@njit
@cc.export("stuff", "f8(f8[:], f8[:])")
def calc_iou(a1, b2):
    pass


if __name__ == "__main__":
    cc.compile()
```

If you run 
```
python test.py
```

where test.py is your numba file. Then Nuitka will just avoid following that import and instead import the code in that file as a library.so

Then I simply ran

```
python -m nuitka --standalon --follow-imports test_application.py
```

And all just worked. On a bad side, you will make some of your code modules and path visible.

**Comment by rhjvanworkum** [comment]
Hey, is there any update on this. I tried all the solutions given here but I still get the same error.
`OSError: Could not load shared object file: llvmlite.dll`
Is there any other workaround I could try? 
Thanks

**Comment by shangdibufashi** [comment]
> As a workaround, for all those blocked. What worked for me was to pre-compile all numba files manually. For us it was ok because all numba code was concentrated in a single file.
> 
> ```
> import numpy as np
> from numba.pycc import CC
> 
> cc = CC("numba_extensions")
> 
> @njit
> @cc.export("stuff", "f8(f8[:], f8[:])")
> def calc_iou(a1, b2):
>     pass
> 
> 
> if __name__ == "__main__":
>     cc.compile()
> ```
> 
> If you run
> 
> ```
> python test.py
> ```
> 
> where test.py is your numba file. Then Nuitka will just avoid following that import and instead import the code in that file as a library.so
> 
> Then I simply ran
> 
> ```
> python -m nuitka --standalon --follow-imports test_application.py
> ```
> 
> And all just worked. On a bad side, you will make some of your code modules and path visible.

helped me a lot! thank you very much!

**Comment by kayhayen** [comment]
Seems like something a Nuitka plugin could do as well, if somebody were to attempt and create that.

**Comment by muneebkq** [comment]
any update on this?

**Comment by kayhayen** [comment]
We are going to add support for `numba.stencil` JIT from bytecode at some point, not sure when or if this function will be added, the infrastructure is there now, but 3.12 support and 2.3 release have priority, and then this depends really on how easy those things become to add. Since numba has many JIT related methods, I might want to make it easier to add things. For `tensorflow.function` it was only one thing, but this seems to be a lot more things.

**Comment by muneebkq** [comment]
when created standalone build i get the missing OSError 
`Traceback (most recent call last):
  File "/home/muneeb/cryptlex/nautika/hello.dist/hello.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/muneeb/cryptlex/nautika/hello.dist/cryptlex/__init__.py", line 1, in <module cryptlex>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/muneeb/cryptlex/nautika/hello.dist/cryptlex/lexactivator/__init__.py", line 1, in <module cryptlex.lexactivator>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/muneeb/cryptlex/nautika/hello.dist/cryptlex/lexactivator/lexactivator.py", line 3, in <module cryptlex.lexactivator.lexactivator>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/muneeb/cryptlex/nautika/hello.dist/cryptlex/lexactivator/lexactivator_native.py", line 108, in <module cryptlex.lexactivator.lexactivator_native>
  File "/home/muneeb/cryptlex/nautika/hello.dist/cryptlex/lexactivator/lexactivator_native.py", line 73, in load_library
  File "/home/muneeb/cryptlex/nautika/hello.dist/ctypes/__init__.py", line 460, in LoadLibrary
  File "/home/muneeb/cryptlex/nautika/hello.dist/ctypes/__init__.py", line 379, in __init__
OSError: /home/muneeb/cryptlex/nautika/hello.dist/cryptlex/lexactivator/libs/linux/gcc/x86_64/libLexActivator.so: cannot open shared object file: No such file or directory`

i tried to create a yml file which will look for this dll incase it skip that is currently present site_packages of python. still facing issue and also tried to copy the Dll in the directory where this pyhton script is present as pass that to `relative_path`
