### ISSUE TITLE
0.6.9rc7 Issue with matplotlib savefig to pdf: ModuleNotFoundError: No module named 'matplotlib.backends.backend_pdf'

### ISSUE THREAD

**Issue by LamerLink** [Nuitka/Nuitka#827]
I apologise in advance if I omitted any crucial details or, to the contrary,  was long-winded anywhere. I tried to include all relevant information to my process.

**Background Info**
Version Info:
0.6.9rc7
Python: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
Executable: C:\Users\mev\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

Nuitka was installed through pip via github.
Other scripts compile fine.
I can try to trim down a section into an example if it would help.

**Description of issue**
I am compiling a fairly large project. It uses numpy, pandas, matplotlib, selenium and more.

I originally was using the latest stable build when I encountered the issue with pandas described under #616 and switched to 0.6.9rc7.

I tried both of these commands:
- `python -m nuitka --enable-plugin=numpy --enable-plugin=tk-inter --standalone --show-progress --show-scons s_generator.py`
- `python -m nuitka --enable-plugin=numpy --enable-plugin=tk-inter --standalone --recurse-all --show-progress --show-scons s_generator.py`

Compilation succeeded and my script was running until it tried to create and save the first matplotlib chart. Then I recieved the following error:
```
Traceback (most recent call last):
  File "Z:\s_g\__source__\s_generator.dist\s_generator.py", line 391, in <module>
  File "Z:\s_g\__source__\s_generator.dist\s_generator.py", line 173, in create_all
  File "Z:\s_g\__source__\s_generator.dist\s_charts.py", line 280, in __init__
  File "Z:\s_g\__source__\s_generator.dist\s_charts.py", line 393, in _create
  File "Z:\s_g\__source__\s_generator.dist\s_charts.py", line 138, in _finish
  File "Z:\s_g\__source__\s_generator.dist\matplotlib\pyplot.py", line 723, in savefig
  File "Z:\s_g\__source__\s_generator.dist\matplotlib\figure.py", line 2203, in savefig
  File "Z:\s_g\__source__\s_generator.dist\matplotlib\backend_bases.py", line 2059, in print_figure
  File "Z:\s_g\__source__\s_generator.dist\matplotlib\backend_bases.py", line 1993, in _get_output_canvas
  File "Z:\s_g\__source__\s_generator.dist\matplotlib\backend_bases.py", line 126, in get_registered_canvas_class
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matplotlib.backends.backend_pdf'
```

**(Note: the next part outlines issues I faced trying hinted compilation, which ultimately resulted in the same ModuleNotFoundError. Skip to the last paragraph if this is not of interest).**

At this point I thought I'd try hinted compilation instead. I downloaded the `nuitkta-utilities` scripts but ran into some new issues there.

The `get-hints.py` script failed to import `getSharedLibrarySuffix` from `nuitka.utils.Utils` so I simply pasted the below in `Utils.py`.
```
def getSharedLibrarySuffix():
    import imp

    result = None

    for suffix, _mode, module_type in imp.get_suffixes():
        if module_type != imp.C_EXTENSION:
            continue

        if result is None or len(suffix) < len(result):
            result = suffix

    return result
```
Then it would freeze after the script it was examining (`s_generator.py`) finished. I ran it a few times, left it for over an hour even once and it still wouldn't finish. Luckily, it was outputting the log file(s) so I just adapted it into another script to finish (`hint-log-to-json.py` included in [modified-nuitka-hinted-comp.zip](https://github.com/Nuitka/Nuitka/files/5147439/modified-nuitka-hinted-comp.zip) here).

Then I was getting an issue with `hinted-mods.py` regarding plugins:
```
Nuitka-Plugins:INFO: hinted-mods: 'hinted-mods' is adding the following options:
Nuitka-Plugins:INFO: hinted-mods: Enabling Nuitka plugin 'numpy' as needed.
Traceback (most recent call last):
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 193, in <module>
    main()
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 158, in main
    activatePlugins()
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 588, in activatePlugins
    _addActivePlugin(plugin_class, args=True)
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
  File "Z:\s_g\__source__\hinted-mods.py", line 285, in __init__
    lateActivatePlugin(plugin_name, option_values)
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 600, in lateActivatePlugin
    _addActivePlugin(getPluginClass(plugin_name), args=True, force=True)
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 70, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
TypeError: __init__() got an unexpected keyword argument 'matplotlib'
```
For this I just commented out the `lateActivatePlugin(plugin_name, option_values)` and had it print the plugins and parameters, so I could ensure I'd passed them in myself. (This change is also shown in `hinted-mods.py` in [modified-nuitka-hinted-comp.zip](https://github.com/Nuitka/Nuitka/files/5147439/modified-nuitka-hinted-comp.zip)).

It listed the following plugins when I ran it:
```
numpy {'matplotlib': True, 'scipy': False}
tk-inter {}
Did you enable the above plugins (if any) manually?
```

My command with `nuitka-hints.py` was similar since I was specifying the plugins:
`python nuitka-hints.py --enable-plugin=numpy --enable-plugin=tk-inter --show-progress --show-scons s_generator.py`

Again it did compile successfully. I will say I got an exception, pasted below even though I don't believe it is necessarily relevant here.
```
Traceback (most recent call last):
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 193, in <module>
    main()
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 186, in main
    MainControl.main()
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 774, in main
    Plugins.onStandaloneDistributionFinished(dist_dir)
  File "C:\Users\mev\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\plugins\Plugins.py", line 207, in onStandaloneDistributionFinished
    plugin.onStandaloneDistributionFinished(dist_dir)
  File "Z:\s_g\__source__\hinted-mods.py", line 435, in onStandaloneDistributionFinished
    self.timer.end()
AttributeError: 'StopWatch' object has no attribute 'delta'
```

Unfortunately, after running the executable I got the same `ModuleNotFoundError: No module named 'matplotlib.backends.backend_pdf'` error. I'm guessing that since the error is the same I either messed up the hinted compilation or hinted compilation isn't needed. 

I have seen some posts such as #393 refer to adding `--enable-plugin=numpy=matplotlib` but it seems this option is depreciated. I only see a `--noinclude-matplotlib` option regarding matplotlib which implies to me that the behaviour has changed and it is included with the numpy plugin by default now? This leads me to believe that perhaps I'm facing an unrelated issue.

**Comment by LamerLink** [comment]
Workaround

I wish I had thought of this 18 hours ago but explicitly importing the backend in my script (`import matplotlib.backends.backend_pdf`) resolved this.

I am fine with this as a solution but I'll leave you to close this ticket or look into depending on if you deem this behaviour to be a needed improvement (and the potential issues with `nuitka-utilities.hinted-compilation`).

**Comment by Fat83dotcom** [comment]
This solution runs for me, eternally thankful
