### ISSUE TITLE
Pandas ImportError: cannot import name 'lib' from 'pandas.libs'

### ISSUE THREAD

**Issue by bekatd** [Nuitka/Nuitka#831]
System info:
- 0.6.8.4
- Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
- OS: Windows 10
- Arch: x86_64

I just built my code into exe successfully using Nuitka, but when I ran it I got this error message and don't know what to do. Is it bug or related to Nuitka at all, but I need some direction to resolve this issue.

Traceback:
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\__init__.py", line 30, in <module pandas>
>     from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
> ImportError: cannot import name 'lib' from 'pandas._libs' (C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\_libs\__init__.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\src\app.py", line 5, in <module>
>     from main import noname
>   File "C:\Users\user\Desktop\src\main.py", line 5, in <module main>
>     import xarray as xr
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xarray\__init__.py", line 3, in <module xarray>
>     from . import testing, tutorial, ufuncs
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\xarray\testing.py", line 6, in <module xarray.testing>
>     import pandas as pd
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\__init__.py", line 38, in <module pandas>
>     ) from e
> ImportError: C extension: 'lib' from 'pandas._libs' (C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\_libs\__init__.py) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**Comment by bekatd** [comment]
Tried to build with `python -m nuitka --standalone --windows-dependency-tool=pefile --experimental=use_pefile_recurse --show-progress --show-scons app.py` 

during building process (after 30 minutes) got this error:

> scons: done building targets.
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 195, in <module>
>     main()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 188, in main
>     MainControl.main()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 761, in main
>     executePostProcessing(OutputDirectories.getResultFullpath())
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\PostProcessing.py", line 72, in executePostProcessing
>     lang_id=0,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\utils\WindowsResources.py", line 247, in addResourceToFile
>     _closeFileWindowsResources(update_handle)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\utils\WindowsResources.py", line 165, in _closeFileWindowsResources
>     raise ctypes.WinError()
> OSError: [WinError 110] The system cannot open the device or file specified.

**Comment by kayhayen** [comment]
This is solved in the 0.6.9 release, and was on develop for a while.

**Comment by bekatd** [comment]
> This is solved in the 0.6.9 release, and was on develop for a while.

I tried with developer version too but without any success

**Comment by bekatd** [comment]
> 
> 
> This is solved in the 0.6.9 release, and was on develop for a while.

I believe this issue is not resolved in version 0.6.9 as well as.

I just installed 0.6.9 version again:

- 0.6.9
- Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
- Executable: C:\Users\wol\AppData\Local\Programs\Python\Python37\python.exe
- OS: Windows
- Arch: x86_64

nuitka version installed from website:
https://i.imgur.com/x3IfTni.png

I ran following command: `python -m nuitka --standalone --show-progress --show-scons --enable-plugin=numpy app.py`

Resulting executable file gives bellow error, I even tried to manually copy `base.pyd` file from the pandas directory but still same traceback:
```
C:\Users\wol\Desktop\src>C:\Users\wol\Desktop\src\app.dist\app.exe
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "C:\Users\wol\Desktop\src\APP~1.DIS\pandas\__init__.py", line 30, in <module pandas>
  File "C:\Users\wol\Desktop\src\APP~1.DIS\pandas\_libs\__init__.py", line 13, in <module pandas._libs>
  File "pandas\_libs\hashtable.pxd", line 8, in init pandas._libs.interval
  File "pandas\_libs\missing.pxd", line 11, in init pandas._libs.hashtable
  File "pandas\_libs\tslibs\nattype.pxd", line 9, in init pandas._libs.missing
  File "C:\Users\wol\Desktop\src\APP~1.DIS\pandas\_libs\tslibs\__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas\_libs\tslibs\base.pxd", line 4, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wol\Desktop\src\APP~1.DIS\app.py", line 6, in <module>
  File "C:\Users\wol\Desktop\src\APP~1.DIS\main.py", line 5, in <module main>
  File "C:\Users\wol\Desktop\src\APP~1.DIS\xarray\__init__.py", line 3, in <module xarray>
  File "C:\Users\wol\Desktop\src\APP~1.DIS\xarray\testing.py", line 6, in <module xarray.testing>
  File "C:\Users\wol\Desktop\src\APP~1.DIS\pandas\__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'pandas._libs.tslibs.base' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

Would appreciate any direction.

And big thanks for creating such a great tool.

**Comment by bekatd** [comment]
Minimum reproducible example:

example.py:
```
import pandas as pd

def main():
    inp = input('enter')

if __name__ == '__main__':
    main()

```
command:
`python -m nuitka --mingw64 --standalone --show-progress --show-scons --enable-plugin=numpy example.py`

result after running generated `.exe` file:
```
Traceback (most recent call last):
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\__init__.py", line 30, in <module pandas>
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\_libs\__init__.py", line 13, in <module pandas._libs>
  File "pandas\_libs\hashtable.pxd", line 8, in init pandas._libs.interval
  File "pandas\_libs\missing.pxd", line 11, in init pandas._libs.hashtable
  File "pandas\_libs\tslibs\nattype.pxd", line 9, in init pandas._libs.missing
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\_libs\tslibs\__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas\_libs\tslibs\base.pxd", line 4, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\example.py", line 1, in <module>
  File "C:\Users\wol\Desktop\example\193CB~1.DIS\pandas\__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'pandas._libs.tslibs.base' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

**Comment by derrickberg-dev** [comment]
Seeing the same problem with 0.6.9.2
```

Traceback (most recent call last):
  File "C:\Users\myusername\DOCUME~1\vscode\HOST-L~1\exetest\HOSTLO~1.DIS\pandas\__init__.py", line 30, in <module pandas>
  File "C:\Users\myusername\DOCUME~1\vscode\HOST-L~1\exetest\HOSTLO~1.DIS\pandas\_libs\__init__.py", line 13, in <module pandas._libs>
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "C:\Users\myusername\DOCUME~1\vscode\HOST-L~1\exetest\HOSTLO~1.DIS\pandas\_libs\tslibs\__init__.py", line 30, in <module pandas._libs.tslibs>
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\myusername\DOCUME~1\vscode\HOST-L~1\exetest\HOSTLO~1.DIS\HostLocatorV2.py", line 3, in <module>
  File "C:\Users\myusername\DOCUME~1\vscode\HOST-L~1\exetest\HOSTLO~1.DIS\pandas\__init__.py", line 38, in <module pandas>
ImportError: C extension: No module named 'pandas._libs.tslibs.base' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

**Comment by bekatd** [comment]
You can resolve it easily by explicitly importing missing library. in our case its:
`import pandas._libs.tslibs.base`
anywhere in source file
