### ISSUE TITLE
Major problem with pandas library

### ISSUE THREAD

**Issue by bekatd** [Nuitka/Nuitka#834]
Here is traceback and screenshot of the nuirtka generated standalone executable, I am experiencing with pandas library if its participating in the program I am trying to NUITKA

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\src\APP~1.DIS\app.py", line 5, in <module>
  File "C:\Users\user\Desktop\src\APP~1.DIS\main.py", line 5, in <module main>
  File "C:\Users\user\Desktop\src\APP~1.DIS\xarray\__init__.py", line 3, in <module xarray>
  File "C:\Users\user\Desktop\src\APP~1.DIS\xarray\testing.py", line 6, in <module xarray.testing>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\__init__.py", line 52, in <module pandas>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\api.py", line 29, in <module pandas.core.api>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\__init__.py", line 1, in <module pandas.core.groupby>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\generic.py", line 69, in <module pandas.core.groupby.generic>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\groupby.py", line 64, in <module pandas.core.groupby.groupby>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\ops.py", line 47, in <module pandas.core.groupby.ops>
  File "C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\grouper.py", line 27, in <module pandas.core.groupby.grouper>
ImportError: cannot import name 'ops' from 'pandas.core.groupby' (C:\Users\user\Desktop\src\APP~1.DIS\pandas\core\groupby\__init__.py)
```
![image](https://i.imgur.com/EUwn7MH.png)

I dont even know from where to start, please let me know what type of info will be helpfull to debug

**Comment by kayhayen** [comment]
I don't need screeshots, I need the issue template filled out.
