### ISSUE TITLE
Potentially incorrect arguments for logger.info function in Recursion.py

### ISSUE THREAD

**Issue by Taiwanchaoh** [Nuitka/Nuitka#838]
If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```bash
0.6.9.1
Python: 3.7.2 (default, Jan 11 2019, 18:52:21) 
Executable: /home/ubuntu/archiconda3/envs/build/bin/python
OS: Linux
Arch: aarch64
```

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

I used *Archiconda With just conda-forge* to install the python.

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

My intension is to build a binary version of my proprietary modules for my collaborators. Hence, I already setup a setup.py file. And, I used the following command to create the binary distribution.

```bash
python setup.py bdist_nuitka
```

And, the output is as follows:

```python
Traceback (most recent call last):
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/__main__.py", line 196, in <module>
    main()
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/__main__.py", line 189, in main
    MainControl.main()
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/MainControl.py", line 723, in main
    main_module = createNodeTree(filename=filename)
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/MainControl.py", line 126, in createNodeTree
    plugin_filename=package_directory, module_package=package_package
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 368, in checkPluginPath
    checkPluginSinglePath(plugin_filename, module_package)
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 337, in checkPluginSinglePath
    recursion_logger.info("Package directory %s", package_dir)
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/Tracing.py", line 183, in info
    self.my_print(message, style=style)
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/Tracing.py", line 170, in my_print
    my_print(message, **kwargs)
  File "/home/ubuntu/archiconda3/envs/build/lib/python3.7/site-packages/nuitka/Tracing.py", line 141, in my_print
    "%r is an invalid value for keyword argument style" % style
ValueError: '/home/ubuntu/xxx/utils/build/lib/xxx' is an invalid value for keyword argument style
```

I dig into the source code and found that line 337 in ```./importing/Recursion.py``` is 
```python
recursion_logger.info("Package directory %s", package_dir)
```

I believe that this is a small bug. I guess your original intension should be as follows:
```python
recursion_logger.info("Package directory %s" % package_dir)
```

After I implemented this update, Nuitka works perfectly. Please review this issue at your convenience, and thank you for this awesome work.

**Comment by kayhayen** [comment]
I did a regexp search for these, and there seem to be even more cases. I will check if this can be in 0.6.9.2, but I will probably wait if something more important pops up to be included as well.

**Comment by bingoko** [comment]
Use the previous version, it would work. I had the same issue after upgrading Nuitka.

**Comment by kayhayen** [comment]
This has been fixed on factory for a while, and will soon appear in 0.6.9.2

**Comment by kayhayen** [comment]
Part of 0.6.9.2 hotfix
