### ISSUE TITLE
can't packing loguru

### ISSUE THREAD

**Issue by ctlddey** [Nuitka/Nuitka#840]
main.py:

> import loguru

when run exe:
Traceback (most recent call last):
  File "D:\Personal\Desktop\apps\CS\o\main.dist\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Personal\Desktop\apps\CS\o\main.dist\loguru\__init__.py", line 20, in <module loguru>
  File "D:\Personal\Desktop\apps\CS\o\main.dist\loguru\_logger.py", line 930, in add
  File "D:\Personal\Desktop\apps\CS\o\main.dist\loguru\_better_exceptions.py", line 133, in __init__
  File "D:\Personal\Desktop\apps\CS\o\main.dist\loguru\_better_exceptions.py", line 142, in _get_lib_dirs
  File "D:\Personal\Desktop\apps\CS\o\main.dist\loguru\_better_exceptions.py", line 142, in <setcontraction>
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 513, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 503, in get_paths
    return _expand_vars(scheme, vars)
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 549, in get_config_vars
    _init_non_posix(_CONFIG_VARS)
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 435, in _init_non_posix
    vars['BINDIR'] = os.path.dirname(_safe_realpath(sys.executable))
  File "D:\Personal\Desktop\apps\CS\o\main.dist\sysconfig.py", line 102, in _safe_realpath
    return realpath(path)
  File "D:\Personal\Desktop\apps\CS\o\main.dist\ntpath.py", line 526, in abspath
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

**Comment by kayhayen** [comment]
Nuitka provides `None` for `sys.executable` for a while now. It seems `sysconfig` should then be handling that. It's shame you didn't fill out the issue template, otherwise it would be actionable.

**Comment by Slyfoxy** [comment]
Hi, @kayhayen ! 

I found a similar problem with loguru. Here is a missing example.

Environment:
```bash
(venv) PS F:\Projects\test_loguru> python -m nuitka --version
0.6.10rc3
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Executable: F:\Projects\test_loguru\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```

```toml
# pyproject.toml
# develop branch, installed by `poetry install`
[tool.poetry]
name = "test-loguru"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8"

nuitka = { git = "https://github.com/Nuitka/Nuitka", rev="dd621ca1"}
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

```

Example:
```python
# main.py
from loguru import logger

logger.info("info")
```

Compile command with output:
```bash
(venv) PS F:\Projects\test_loguru> python -m nuitka --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --follow-imports --mingw64 --standalone  .\main.py
Nuitka-Scons:WARNING: Didn't find ccache for C level caching, follow Nuitka user manual description.
Nuitka-Scons:WARNING: You are not using ccache.
```

Traceback:
```bash
(venv) PS F:\Projects\test_loguru> .\main.dist\main.exe
Traceback (most recent call last):
  File "F:\Projects\test_loguru\main.dist\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked    
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "F:\Projects\test_loguru\main.dist\loguru\__init__.py", line 20, in <module loguru>
  File "F:\Projects\test_loguru\main.dist\loguru\_logger.py", line 930, in add  
  File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 133, in __init__
  File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 142, in _get_lib_dirs
  File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 142, in <setcontraction>
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 513, in get_path  
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 503, in get_paths 
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 172, in _expand_vars
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 549, in get_config_vars
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 435, in _init_non_posix
  File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 102, in _safe_realpath
  File "F:\Projects\test_loguru\main.dist\ntpath.py", line 626, in realpath     
  File "F:\Projects\test_loguru\main.dist\ntpath.py", line 452, in normpath     
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ctlddey** [comment]
> Hi, @kayhayen !
> 
> I found a similar problem with loguru. Here is a missing example.
> 
> Environment:
> 
> ```shell
> (venv) PS F:\Projects\test_loguru> python -m nuitka --version
> 0.6.10rc3
> Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
> Executable: F:\Projects\test_loguru\venv\Scripts\python.exe
> OS: Windows
> Arch: x86_64
> ```
> 
> ```toml
> # pyproject.toml
> # develop branch, installed by `poetry install`
> [tool.poetry]
> name = "test-loguru"
> version = "0.0.1"
> description = ""
> authors = []
> 
> [tool.poetry.dependencies]
> python = "~3.8"
> 
> nuitka = { git = "https://github.com/Nuitka/Nuitka", rev="dd621ca1"}
> loguru = "^0.5.3"
> 
> [tool.poetry.dev-dependencies]
> 
> [build-system]
> requires = ["poetry>=1.0"]
> build-backend = "poetry.masonry.api"
> ```
> 
> Example:
> 
> ```python
> # main.py
> from loguru import logger
> 
> logger.info("info")
> ```
> 
> Compile command with output:
> 
> ```shell
> (venv) PS F:\Projects\test_loguru> python -m nuitka --windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --follow-imports --mingw64 --standalone  .\main.py
> Nuitka-Scons:WARNING: Didn't find ccache for C level caching, follow Nuitka user manual description.
> Nuitka-Scons:WARNING: You are not using ccache.
> ```
> 
> Traceback:
> 
> ```shell
> (venv) PS F:\Projects\test_loguru> .\main.dist\main.exe
> Traceback (most recent call last):
>   File "F:\Projects\test_loguru\main.dist\main.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked    
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "F:\Projects\test_loguru\main.dist\loguru\__init__.py", line 20, in <module loguru>
>   File "F:\Projects\test_loguru\main.dist\loguru\_logger.py", line 930, in add  
>   File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 133, in __init__
>   File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 142, in _get_lib_dirs
>   File "F:\Projects\test_loguru\main.dist\loguru\_better_exceptions.py", line 142, in <setcontraction>
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 513, in get_path  
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 503, in get_paths 
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 172, in _expand_vars
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 549, in get_config_vars
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 435, in _init_non_posix
>   File "F:\Projects\test_loguru\main.dist\sysconfig.py", line 102, in _safe_realpath
>   File "F:\Projects\test_loguru\main.dist\ntpath.py", line 626, in realpath     
>   File "F:\Projects\test_loguru\main.dist\ntpath.py", line 452, in normpath     
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```

I've solved it，you can modify “_better_exceptions.py” in .dist folder/loguru(copy loguru from site-packages to dist folder)
    @staticmethod
    def _get_lib_dirs():
        # schemes = sysconfig.get_scheme_names()
        # names = ["stdlib", "platstdlib", "platlib", "purelib"]
        # paths = {sysconfig.get_path(name, scheme) for scheme in schemes for name in names}
        # return [os.path.abspath(path).lower() + os.sep for path in paths if path in sys.path]
        return os.path.dirname(os.path.realpath(sys.argv[0]))

**Comment by kayhayen** [comment]
So, this might be what I just published as a hotfix, I believe that `sysconfig` breakage can also come from it being `None` in standaline mode. That also broke PyQt5, nobody checks for that allowed value. Now it is no more, so this ought to just work with 0.6.9.4 hotfix that I just released.
