### ISSUE TITLE
The passlib module has an implicit dependency on 'passlib.handlers' package, plugin needed

### ISSUE THREAD

**Issue by aunali1** [Nuitka/Nuitka#842]
After successfully compiling Odoo, I am getting an obscure runtime error:
```
Traceback (most recent call last):
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo-bin", line 5, in <module>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/__init__.py", line 113, in <module odoo>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/modules/__init__.py", line 8, in <module odoo.modules>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/modules/graph.py", line 10, in <module odoo.modules.graph>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/tools/__init__.py", line 8, in <module odoo.tools>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/tools/cloc.py", line 10, in <module odoo.tools.cloc>
  File "/home/aunali/Development/odoo/odoo-bin.dist/odoo/tools/config.py", line 22, in <module odoo.tools.config>
  File "/home/aunali/Development/odoo/odoo-bin.dist/passlib/context.py", line 1401, in __init__
  File "/home/aunali/Development/odoo/odoo-bin.dist/passlib/context.py", line 1592, in load
  File "/home/aunali/Development/odoo/odoo-bin.dist/passlib/context.py", line 634, in __init__
  File "/home/aunali/Development/odoo/odoo-bin.dist/passlib/context.py", line 652, in _init_scheme_list
  File "/home/aunali/Development/odoo/odoo-bin.dist/passlib/registry.py", line 350, in get_crypt_handler
ModuleNotFoundError: No module named 'passlib.handlers'
```

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
```
0.6.10rc2
Python: 3.8.6 (default, Sep 24 2020, 10:29:27)
Executable: /home/aunali/Development/venv/bin/python
OS: Linux
Arch: x86_64
```
Additionally, host distro is Clear Linux.

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Created a virtualenv, cloned develop branch as of 052b215, ran `python setup.py install`.

I compiled odoo from 13.0 branch, commit [a330ee0](https://github.com/odoo/odoo/commit/a330ee098427bbc4f5e82183777f772fba8dc19b), with the following:
```
python -m nuitka --verbose --follow-imports --enable-plugin=gevent --plugin-enable=numpy --plugin-enable=pylint-warnings --standalone odoo-bin
```

**Comment by kayhayen** [comment]
Looking at passlib, it seems you need to do `--include-package=passlib.handlers` and that it's impossible to tell which ones are to be used. I am going to release a version of Nuitka that does that automatically soon, but let me know, if that helps you, because I am not really too interested in testing that out. I guess, the submodules of that package could be made an option of the plugin, so no unused code needs to be included.

**Comment by kayhayen** [comment]
I would need feedback on if my suggestion worked.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
