### ISSUE TITLE
 ModuleNotFoundError: No module named 'shiboken2.shiboken2'

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#844]
0.6.9.1
Python: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

1. I updated nuitka 0.6.3 to 0.6.9.1 now
```
Python36\python -m pip install --upgrade nuitka
Collecting nuitka
  Downloading Nuitka-0.6.9.1.tar.gz (2.4 MB)
     |████████████████████████████████| 2.4 MB 656 kB/s
Building wheels for collected packages: nuitka
  Building wheel for nuitka (setup.py) ... done
  Created wheel for nuitka: filename=Nuitka-0.6.9.1-py3-none-any.whl size=2310078 sha256=a3daee101a09ce97ac1092737155d55b1e2bde1935ef37d10b2a5316c05a6c07
  Stored in directory: c:\users\ManPyhon\appdata\local\pip\cache\wheels\14\ee\58\4b35ebe42a2e700349c76fdcbe3fe5b7f7c1c14d5665b21332
Successfully built nuitka
Installing collected packages: nuitka
  Attempting uninstall: nuitka
    Found existing installation: Nuitka 0.6.3
    Uninstalling Nuitka-0.6.3:
      Successfully uninstalled Nuitka-0.6.3
Successfully installed nuitka-0.6.9.1
```
2. After this I have error when runin compiled main.exe
```
"E:\appa\Python36\main.exe"
PySide2/__init__.py: Unable to import shiboken2 from E:\appa\Python36, E:\appa\Python36\python36.zip, E:\Python36\DLLs, ...
Traceback (most recent call last):
  File "E:\appa\Python36\main.pyw", line 3, in <module>
    from PySide2.QtWidgets import QApplication, QMessageBox
  File "E:\Python36\lib\site-packages\PySide2\__init__.py", line 107, in <module PySide2>
    _setupQtDirectories()
  File "E:\Python36\lib\site-packages\PySide2\__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "E:\Python36\lib\site-packages\shiboken2\__init__.py", line 27, in <module shiboken2>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
```

With nuitka 0.6.3 compilation was ok.

This touching configs like:
```
Python36\python -m nuitka --follow-imports --windows-dependency-tool=pefile --experimental=use_pefile_recurse main.pyw
```

**Comment by ManPython** [comment]
`python -m nuitka --recurse-all main.pyw` this same
`python -m nuitka --exe main.pyw` working, but need some part of code if .exe is not in this same dir, eg.

```
\main.pyw", line 5, in <module>
ModuleNotFoundError: No module named 'Model'
```

**Comment by kayhayen** [comment]
That's strange, in the Qt bug tracker there seemed to be people who got PySide2 and shiboken to work, and never came across this issue.

**Comment by RESP3CT88** [comment]
I have the same error when running:

python3 -m nuitka --follow-imports --show-progress main.py

**Comment by sausix** [comment]
Any progress?

I'm expecting the same result but running on Linux:

```
...
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.bin'.
```

```
as@station2:~/projectdir$ ./main.bin
PySide2/__init__.py: Unable to import shiboken2 from /home/as/projectdir, /usr/lib/python39.zip, /usr/lib/python3.9, /usr/lib/python3.9/lib-dynload, /home/as/.local/lib/python3.9/site-packages, /usr/lib/python3.9/site-packages
Traceback (most recent call last):
  File "/home/as/projectdir/main.py", line 10, in <module>
    from PySide2.QtCore import qInstallMessageHandler
  File "/home/as/projectdir/PySide2/__init__.py", line 107, in <module PySide2>
  File "/home/as/projectdir/PySide2/__init__.py", line 58, in _setupQtDirectories
  File "/home/as/projectdir/shiboken2/__init__.py", line 27, in <module shiboken2>
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
```

On the host this module exists of course.
```
as@station2:~/projectdir$ python
Python 3.9.5 (default, May 12 2021, 17:14:51) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shiboken2.shiboken2
>>> shiboken2.shiboken2
<module 'shiboken2.shiboken2' from '/home/as/.local/lib/python3.9/site-packages/shiboken2/shiboken2.abi3.so'>
>>>
```

Affects PySide2 5.15.1 and 5.15.2.
I will now dig into this problem.

**Comment by kayhayen** [comment]
Can you try out the factory branch: https://nuitka.net/doc/factory.html and make a new issue with proper issue template, as the original report and your new comment are doing different things.

**Comment by kayhayen** [comment]
Marking as invalid, as this was never reproduced, hoping for a more complete report.
