### ISSUE TITLE
Crash on code with getattr, hasattr, or setattr in tried code

### ISSUE THREAD

**Issue by jgkeizer** [Nuitka/Nuitka#847]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  0.6.9.1
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\z3435374\Anaconda3\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

anaconda
conda install nuitka

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

"hello world" works

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

import numpy as np
import deepdish as dd
dd.io.save('c:\\Quokka_dev\\test2.dat',{'metadata': 'joris'})

output:

Nuitka-Recursion:INFO: Should decide '--prefer-source-code' vs. '--no-prefer-source-code', using existing 'diff' extension module by default. Candidates were: ImportScanFinding(found_in='C:\\Users\\z3435374\\Anaconda3\\lib\\site-packages\\lxml\\html', priority=1, full_path='C:\\Users\\z3435374\\Anaconda3\\lib\\site-packages\\lxml\\html\\diff.cp38-win_amd64.pyd', search_order=0) <-> ImportScanFinding(found_in='C:\\Users\\z3435374\\Anaconda3\\lib\\site-packages\\lxml\\html', priority=2, full_path='C:\\Users\\z3435374\\Anaconda3\\lib\\site-packages\\lxml\\html\\diff.py', search_order=0).
Problem with statement at C:\Users\z3435374\Anaconda3\lib\site-packages\astropy\utils\data_info.py:378:
->     info_summary_stats = staticmethod(

Problem with statement at C:\Users\z3435374\Anaconda3\lib\site-packages\astropy\utils\data_info.py:254:
-> class DataInfo(metaclass=DataInfoMeta):

Problem with statement at C:\Users\z3435374\Anaconda3\lib\site-packages\astropy\utils\data_info.py:254:
-> class DataInfo(metaclass=DataInfoMeta):

Problem with statement at C:\Users\z3435374\Anaconda3\lib\site-packages\astropy\utils\data_info.py:254:
-> class DataInfo(metaclass=DataInfoMeta):

Problem with statement at C:\Users\z3435374\Anaconda3\lib\site-packages\astropy\utils\data_info.py:254:
-> class DataInfo(metaclass=DataInfoMeta):

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\z3435374\\Anaconda3\\lib\\site-packages\\astropy\\utils\\data_info.py', 'module_name': <ModuleName astropy.utils.data_info>}>'.
Traceback (most recent call last):
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\Builtins.py", line 229, in wrapper
    return f(*args, **new_kw)
TypeError: __init__() got an unexpected keyword argument 'expression'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\__main__.py", line 196, in <module>
    main()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\__main__.py", line 189, in main
    MainControl.main()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\MainControl.py", line 723, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\MainControl.py", line 146, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 615, in optimize
    finished = makeOptimizationPass(initial_pass=False)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 524, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 167, in optimizeModule    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 99, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 497, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\FrameNodes.py", line 180, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 510, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 510, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\AssignNodes.py", line 277, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 491, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\OutlineNodes.py", line 227, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 510, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 510, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\FrameNodes.py", line 180, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 510, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\LocalsDictNodes.py", line 394, in computeStatement
    result, change_tags, change_desc = self.computeStatementSubExpressions(
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 847, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression=expression)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 491, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1061, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\CallNodes.py", line 91, in computeExpression
    return self.getCalled().computeExpressionCall(
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\LocalsDictNodes.py", line 152, in computeExpressionCall
    call_node_clone = call_node.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1257, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1257, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1257, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1257, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1259, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1032, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in getCloneArgs
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 1030, in <genexpr>
    values[key] = tuple(v.makeClone() for v in value)
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 113, in makeClone
    result = self.__class__(source_ref=self.source_ref, **self.getCloneArgs())
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 665, in getCloneArgs
    values[key] = value.makeClone()
  File "C:\Users\z3435374\Anaconda3\lib\site-packages\nuitka\nodes\NodeBases.py", line 115, in makeClone
    raise NuitkaNodeError("Problem cloning node", self, e)
nuitka.Errors.NuitkaNodeError:
Problem cloning node

    <node kind="ExpressionBuiltinGetattr" line="380">
      <role name="expression">
        <node kind="ExpressionVariableRef" line="380" variable_name="np" owner="astropy$utils$data_info"/>
      </role>
      <role name="name">
        <node kind="ExpressionOperationBinaryAdd" line="380">
          <role name="left">
            <node kind="ExpressionConstantStrRef" line="380" constant="'nan'" user_provided="True"/>
          </role>
          <role name="right">
            <node kind="ExpressionVariableRef" line="380" variable_name="stat" owner="astropy$utils$data_info$$$outline__2_listcomp"/>
          </role>
        </node>
      </role>
      <role name="default" type="none"/>
    </node>

__init__() got an unexpected keyword argument 'expression'

The above information should be included in a bug report.

**Comment by kayhayen** [comment]
I fixed this for factory branch, try this: http://nuitka.net/doc/factory.html

**Comment by jgkeizer** [comment]
Thank you Kay, much appreciated! You’re doing great work with the Nuitka project.

**Comment by kayhayen** [comment]
This was released in 0.6.9.2 already.
