### ISSUE TITLE
matplotlib pyplot crashing on doc string

### ISSUE THREAD

**Issue by ma6254** [Nuitka/Nuitka#852]
## report error

build is ok
but runtime error:
```
PS C:\soft\aa> .\release\main.dist\main.exe

Traceback (most recent call last):
  File "C:\soft\aa\release\MAIN~1.DIS\main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\soft\aa\release\MAIN~1.DIS\matplotlib\__init__.py", line 107, in <module matplotlib>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\soft\aa\release\MAIN~1.DIS\matplotlib\rcsetup.py", line 29, in <module matplotlib.rcsetup>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\soft\aa\release\MAIN~1.DIS\matplotlib\colors.py", line 1169, in <module matplotlib.colors>
  File "C:\soft\aa\release\MAIN~1.DIS\matplotlib\cbook\deprecation.py", line 236, in deprecate
  File "C:\soft\aa\release\MAIN~1.DIS\inspect.py", line 631, in cleandoc
AttributeError: 'ellipsis' object has no attribute 'expandtabs'
PS C:\soft\aa>
```

## Environment

```
gcc.exe (Rev3, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO 
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Python 3.8.2
pip 20.2.3 from c:\users\mjc\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
```

## python code

```python
import math

from matplotlib import pyplot as plt

x = []
y = []
for k in range(100):
    x.append(k)
    y.append(math.sin(0.5*k))


plt.title("Matplotlib demo")
plt.xlabel("x axis caption")
plt.ylabel("y axis caption")
plt.plot(x, y)
plt.show()

```

## build command

```
# Environment configuration
$Env:PATH += ";C:\MinGW64\bin"
gcc --version
python -V
pip -V


python -m nuitka `
    --mingw64 `
    --show-progress `
    --output-dir=release `
    --plugin-enable=numpy `
    --plugin-enable=qt-plugins `
    --standalone `
    main.py
```

**Comment by kayhayen** [comment]
Released as part of 0.6.10
