### ISSUE TITLE
Nuitka (in v0.6.9.2) seems not yet compatible with Cpython v3.9.0

### ISSUE THREAD

**Issue by Alpengreis** [Nuitka/Nuitka#854]
Hello

Maybe you know this already and it's certainly NOT a accusation or something like that!

However, it seems that Nuitka (tested in v0.6.9.2 is not yet compatible with the new Cpython release 3.9.0.

I received the following messages:

![nuitka_py3 9 0-problem](https://user-images.githubusercontent.com/11355601/95486884-e282d680-0993-11eb-96fe-20085f94c8f0.png)

As text (not as code because newline chars):

"d:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\Scripts\python.exe" -m nuitka --pl
ugin-enable=tk-inter --standalone --windows-disable-console --windows-dependency-tool=pefile --experimental=use_pefile_r
ecurse --experimental=use_pefile_fullrecurse "src\program\frames_pack_gui.pyw"
Traceback (most recent call last):
  File "D:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\lib\site-packages\nuitka\__main__.py", line 196, in <mod                                                                                  ule>
    main()
  File "D:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\lib\site-packages\nuitka\__main__.py", line 143, in main
    Tracing.general.warning(
  File "D:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\lib\site-packages\nuitka\Tracing.py", line 176, in warni                                                                                  ng
    self.my_print(message, style=style, file=sys.stderr)
  File "D:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\lib\site-packages\nuitka\Tracing.py", line 170, in my_pr                                                                                  int
    my_print(message, **kwargs)
  File "D:\_D-Alpen\Multimedia\PC\Python\Projects\.venv\py3.9.0\lib\site-packages\nuitka\Tracing.py", line 140, in my_pr                                                                                  int
    raise ValueError(
ValueError: '3.9' is an invalid value for keyword argument style

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version
  0.6.9.2
  Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
  Executable: C:\Program Files\Python39\python.exe
  OS: Windows
  Arch: x86_64

  Microsoft Windows 10 Pro x64 [19041.508] [2004] [de-CH]

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
  ~~pip install -U nuitka~~
  pip install nuitka
  --> within restricted account, so it was an user installation

PS: The same command with Cpython 3.8.6 runs.

Edit: added text data and made some correction.

**Comment by kayhayen** [comment]
I wonder, how this could be determine without raising an issue. 

But seriously, it's not supported yet. 

Yours,
Kay

**Comment by Alpengreis** [comment]
Sorry, I am still a newbie with Python and Nuitka and tought you had perhaps experimented with the Python 3.9 release candidates and it should run already with the release ...

Now I know, it needs time and I must have patience!

Kind regards and thank you.

**Comment by kayhayen** [comment]
That said, Nuitka trying to warn about, seems to have regressed into a crash, going to address that and trying to get it working for hello world code.

**Comment by kayhayen** [comment]
So that's a in a hotfix, and develop can be used instead of a 3.8 on develop largely.
