### ISSUE TITLE
I had finsh , but when I try to open the app it's notice me like this "expected str, bytes or os.PathLike object, not NoneType", what I shold do ?

### ISSUE THREAD

**Issue by liminghu91** [Nuitka/Nuitka#858]
PS E:\崇德（打包）\Chong_De.dist> E:\崇德（打包）\Chong_De.dist\Chong_De.exe
Traceback (most recent call last):
  File "E:\崇德（打包）\Chong_De.dist\Chong_De.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "E:\崇德（打包）\Chong_De.dist\PyQt5\__init__.py", line 49, in <module PyQt5>
  File "E:\崇德（打包）\Chong_De.dist\PyQt5\__init__.py", line 28, in find_qt
  File "E:\崇德（打包）\Chong_De.dist\ntpath.py", line 243, in dirname
  File "E:\崇德（打包）\Chong_De.dist\ntpath.py", line 205, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by kayhayen** [comment]
This got recently fixed, even as a hotifx for 0.6.9.4 and shouldn't be the issue anymore. The `sys.executable` was set to None for standalone, because it's not a python, but large amounts of code depend on it. Your issue was valid when you opened it, but other things lead me to fix it too. PyQt5 is not usable without the old bug.
