### ISSUE TITLE
--onefile experimental feature feedback

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#880]
On lastest nuitka factory 0.6.10rc8:

```
C:\GIT\ONEFILETEST\PythonSRC>c:\Python38-64\python.exe -m nuitka --standalone --enable-plugin=multiprocessing --include-package=urllib3 --windows-product-version=3.6.0.0 --windows-company-name="Zoidberg Inc" --onefile SomeProject.py
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Nuitka-Scons:INFO: Compiled 351 C files using clcache.
Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache hit': 350
Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache miss': 1
Nuitka:WARNING: Onefile mode is experimental on 'Windows'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Traceback (most recent call last):
  File "c:\Python38-64\lib\site-packages\nuitka\__main__.py", line 196, in <module>
    main()
  File "c:\Python38-64\lib\site-packages\nuitka\__main__.py", line 189, in main
    MainControl.main()
  File "c:\Python38-64\lib\site-packages\nuitka\MainControl.py", line 776, in main
    packDistFolderToOnefile(dist_dir, binary_filename)
  File "c:\Python38-64\lib\site-packages\nuitka\freezer\Onefile.py", line 56, in packDistFolderToOnefile
    packDistFolderToOnefileWindows(dist_dir)
  File "c:\Python38-64\lib\site-packages\nuitka\freezer\Onefile.py", line 295, in packDistFolderToOnefileWindows
    _runOnefileScons(quiet=not Options.isShowScons())
  File "c:\Python38-64\lib\site-packages\nuitka\freezer\Onefile.py", line 262, in _runOnefileScons
    result = SconsInterface.runScons(
  File "c:\Python38-64\lib\site-packages\nuitka\build\SconsInterface.py", line 275, in runScons
    scons_command = _buildSconsCommand(
  File "c:\Python38-64\lib\site-packages\nuitka\build\SconsInterface.py", line 223, in _buildSconsCommand
    getExternalUsePath(os.path.join(getSconsDataPath(), scons_filename)),
  File "c:\Python38-64\lib\site-packages\nuitka\utils\FileOperations.py", line 490, in getExternalUsePath
    filename = getWindowsShortPathName(filename)
  File "c:\Python38-64\lib\site-packages\nuitka\utils\FileOperations.py", line 460, in getWindowsShortPathName
    raise WindowsError(
FileNotFoundError: [Errno 2] Le fichier spécifié est introuvable.
```

**Comment by kayhayen** [comment]
Yup, it's missing from installation, going to fix that up.

**Comment by kayhayen** [comment]
Please retry.

**Comment by deajan** [comment]
Retried:

```
C:\GIT\ONEFILETEST\PythonSRC>c:\Python38-64\python.exe -m nuitka --standalone --enable-plugin=multiprocessing --include-package=urllib3 --windows-product-version=3.6.0.0 --windows-company-name="Zoidberg Inc" --onefile SomeProject.py
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Nuitka-Scons:INFO: Compiled 351 C files using clcache.
Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache hit': 349
Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache miss': 2
Nuitka:WARNING: Onefile mode is experimental on 'Windows'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
clÿ: Ligne de commande warning D9002ÿ: option '/ML' inconnue ignor‚e
Nuitka-Scons:INFO: Compiled 1 C files using clcache.
Nuitka-Scons:INFO: Cached C files (using clcache) with result 'cache miss': 1
Nuitka:INFO: Sucessfully created 'SomeProject.exe'
```

Got some strange error about unknown /ML option.
My compiler is VC 2015.

When executing the compiled executable, I get
```
Assertion failed: target_file != INVALID_HANDLE_VALUE, file static_src\WindowsOnefile.cpp, line 253
```

**Comment by kayhayen** [comment]
Hm, probably a `CreateDirectory` missing there, no subfolders will work yet.

**Comment by kayhayen** [comment]
I added the directory stuff, also changed filename encoding to UTF16 while doing, thinking that would be it, it but didn't push yet, because I am having all sorts of funny things happening now, on Python2 I have e.g. observed things that were reported, namely that the created file wasn't possible to open for assertions, that it opened for appending with a file position of 0, and other ugly stuff. With 3.8 it mostly works. But with 2.7, if I seek to end of file, and write there, I end up with a file end where my offset is not correct. 

Not sure if that's scons, virus checkers, or what. But when scons finishes, it seems the binary might not yet really be there, but the linker writes are still being performed or what. Occasionally people report that attaching the constants resource fails with that kind of error.

It's funny though, since for 3.8 and 2.7, the onefile binary doesn't care, so the Python version is only different for Scons, the scons code is identical right now for these. So something about `subprocess` or `scons` might be at fault.

**Comment by kayhayen** [comment]
Ok, adding resources after adding the payload was maybe a bad idea. With 2.7 there is a manifest resource, that will be copied, however, me was thinking there would be a version resource for both, and there is, but it wasn't causing any (obvious) issue with 3.8 at least, which is strange. So I now reverted the order of adding them, and that seems to help.

**Comment by kayhayen** [comment]
Ok, pushed an update, that seems to work for Python2 as well. Still need to seek after open, which is strange, but maybe it's just a platform difference, and not indicative of a bug. The smaller binary might show a race condition that needs to be dealt with, but for now it's at least better, and the Qt test case worked, creating subfolders correctly it seems, so your case might work now.
