### ISSUE TITLE
0.6.10rc9 regression: assertion error in `generateStatementCode`

### ISSUE THREAD

**Issue by ambv** [Nuitka/Nuitka#893]
I installed the version from the `develop` branch trying to work around #870. While 0.6.9.6 compiles my program just fine, 0.6.10rc9 (develop branch at time of writing) crashes with `AssertionError: [<VariableDeclaration PyObject * tmp_tuple_element_1 = None>]`.

<details>
<summary>Click the arrow to see full traceback</summary>
<pre>
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Problem with <Node 'STATEMENT_RAISE_EXCEPTION'> at internal:1
Problem with <Node 'STATEMENT_CONDITIONAL'> at internal:1
Problem with <Node 'STATEMENT_TRY'> at internal:1
Problem with <Node 'STATEMENT_CONDITIONAL'> at internal:1
Problem with <Node 'STATEMENT_TRY'> at internal:1
Nuitka:WARNING: Problem creating function code '__main__$$$function_2_complex_call_helper_keywords_star_dict'.
Traceback (most recent call last):
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/__main__.py", line 196, in <module>
    main()
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/__main__.py", line 189, in main
    MainControl.main()
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/MainControl.py", line 698, in main
    result, options = compileTree(main_module=main_module)
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/MainControl.py", line 586, in compileTree
    makeSourceDirectory(main_module=main_module)
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/MainControl.py", line 303, in makeSourceDirectory
    source_code = CodeGeneration.generateModuleCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeGeneration.py", line 438, in generateModuleCode
    function_code, function_decl = generateFunctionBodyCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeGeneration.py", line 382, in generateFunctionBodyCode
    function_code = getFunctionCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/FunctionCodes.py", line 601, in getFunctionCode
    return _getFunctionCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/FunctionCodes.py", line 642, in _getFunctionCode
    generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 230, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 219, in _generateStatementSequenceCode
    generateStatementCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 179, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/TryCodes.py", line 86, in generateTryCode
    generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 230, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 219, in _generateStatementSequenceCode
    generateStatementCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 179, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/BranchCodes.py", line 52, in generateBranchCode
    generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 230, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 219, in _generateStatementSequenceCode
    generateStatementCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 179, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/TryCodes.py", line 185, in generateTryCode
    generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 230, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 219, in _generateStatementSequenceCode
    generateStatementCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 179, in generateStatementCode
    statement_dispatch_dict[statement.kind](
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/BranchCodes.py", line 52, in generateBranchCode
    generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 230, in generateStatementSequenceCode
    _generateStatementSequenceCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 219, in _generateStatementSequenceCode
    generateStatementCode(
  File "/Users/ambv/.venvs/aiotone/lib/python3.8/site-packages/nuitka/codegen/CodeHelpers.py", line 184, in generateStatementCode
    assert not context.getCleanupTempnames(), context.getCleanupTempnames()
AssertionError: [< VariableDeclaration PyObject * tmp_tuple_element_1 = None >]
</pre>
</details>

### Other information
```
$ python -m nuitka --version
0.6.10rc9
Python: 3.8.6 (default, Oct 27 2020, 08:57:44)
Executable: /Users/ambv/.venvs/aiotone/bin/python
OS: Darwin (macOS 10.15.7)
Arch: x86_64
```

Nuitka installed with `pip install`, using clang with no ccache. Version 0.6.9.6 compiles the same program fine.

**Comment by ambv** [comment]
You can try to reproduce by:
- cloning https://github.com/ambv/aiotone/
- creating and activating a new Python 3.8 virtualenv
- installing the project and its deps:
   ```
   (aiotone)$ poetry install
   ```
- creating a one-liner script in the root directory of the project:
   ```
   (aiotone)$ echo "from aiotone.fmsynth import main; main()" >fm2.py
   ```
- trying to compile it:
   ```
   (aiotone)$ python -m nuitka --follow-imports --recurse-not-to=numpy --recurse-not-to=rtmidi fm2.py
   ```

**Comment by ambv** [comment]
Oh, and almost forgot to thank you, @kayhayen, for starting and persevering. The compiler is indeed much more compatible with CPython and while it doesn't yet provide drastic efficiency gains, it does push the program enough for me to make it fast enough to generate polyphonic real-time audio.

**Comment by kayhayen** [comment]
Should be better now, seems I messed up with last minute improvements before release of 0.6.10
