### ISSUE TITLE
Problem with multiprocessing plugin on Windows

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#894]
```
0.6.11rc1
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38-32\python.exe
OS: Windows
Arch: x86
```

Input:

` -m nuitka --mingw64 --windows-uac-admin --assume-yes-for-downloads --windows-icon-from-ico=E:\TEST\TEST\test.ico --output-dir=E:\TEST\TEST\Current_build --standalone --plugin-enable=multiprocessing  --plugin-enable=numpy --recurse-all  "E:\TEST\TEST\test.py"`

Output:

```
Problem with statement at internal:1:
->
Problem with statement at internal:1:
->
Problem with statement at internal:1:
->
Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:466:
->              return self._get_good_object_(

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:465:
->      def _ApplyTypes_(self, dispid, wFlags, retType, argTypes, user, resultCLSID, *args):

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:465:
->      def _ApplyTypes_(self, dispid, wFlags, retType, argTypes, user, resultCLSID, *args):

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:428:
-> class DispatchBaseClass:

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:428:
-> class DispatchBaseClass:

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:428:
-> class DispatchBaseClass:

Problem with statement at C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py:428:
-> class DispatchBaseClass:

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'C:\\Users\\andre\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\win32com\\client\\__init__.py', 'module_name': <ModuleName win32com.client>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\__main__.py", line 197, in <module>
    main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\__main__.py", line 190, in main
    MainControl.main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\MainControl.py", line 688, in main
    main_module = createNodeTree(filename=filename)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\MainControl.py", line 146, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\Optimization.py", line 653, in optimize
    finished = makeOptimizationPass()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\Optimization.py", line 537, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\Optimization.py", line 185, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\Optimization.py", line 106, in optimizeCompiledPythonModule
    module.computeModule()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 508, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\AssignNodes.py", line 278, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\OutlineNodes.py", line 227, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\LocalsDictNodes.py", line 396, in computeStatement
    result, change_tags, change_desc = self.computeStatementSubExpressions(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\NodeBases.py", line 849, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression=expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 953, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 433, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 448, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ReturnNodes.py", line 52, in computeStatement
    expression = trace_collection.onExpression(self.getExpression())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1130, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 953, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 433, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 448, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 578, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 729, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 595, in computeStatement
    branch_no_collection.computeBranch(branch=no_branch)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 729, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 506, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExceptionNodes.py", line 87, in computeStatement
    exception_type = trace_collection.onExpression(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1130, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1130, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 487, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 950, in computeExpressionRaw
    needs_visit = owning_module.addUsedFunction(function_body)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 447, in addUsedFunction
    assert function_body in self.getFunctions()
AssertionError
```

Everything worked on version 0.6.10rc9.

**Comment by Pro100rus32** [comment]
64bit python:

Output:

```
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\andre\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-9.0.0-r3\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running 'C:\\Users\\andre\\AppData\\Local\\Nuitka\\Nuitka\\ccache\\v3.7.12\\ccache.exe gcc.exe -o "module.numpy.ma.core.o" -c -std=c11 -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=165 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -IC:\\Users\\andre\\AppData\\Local\\Programs\\Python\\Python38\\include -I. -IC:\\Users\\andre\\AppData\\Local\\Programs\\Python\\Python38\\lib\\SITE-P~1\\nuitka\\build\\include -IC:\\Users\\andre\\AppData\\Local\\Programs\\Python\\Python38\\lib\\SITE-P~1\\nuitka\\build\\static_src "module.numpy.ma.core.c"' took 75.42 seconds
Nuitka-Scons:INFO: Compiled 264 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 264
Nuitka:INFO: Sucessfully created 'E:\\test\\Build\\Current_build\\test.dist\\test.exe'.
```

**Comment by Pro100rus32** [comment]
0.6.10 stable, doesn't work either.

**Comment by kayhayen** [comment]
Factory is not supported, do not use it for bug reports, unless requested so.

**Comment by kayhayen** [comment]
Closing, as "doesn't work either" without example code doesn't cut it, although I can believe there is a real issue behind this, I need to know more.

**Comment by Pro100rus32** [comment]
**Main.py**

```
from Test import *
if __name__=="__main__":
    import multiprocessing
    p_out, p_in = multiprocessing.Pipe()
    p1 = multiprocessing.Process(target=test1, args=(p_in,))
    p2 = multiprocessing.Process(target=test2, args=(p_out,))
    p3 = multiprocessing.Process(target=menu)
    p2.start()
    p1.start()
    p3.start()
    def test1bind():
        print("F pressed")
        global p1
        global p2
        if p1.is_alive():
            p1.terminate()
            p2.terminate()
        else:
            p1 = multiprocessing.Process(target=test1, args=(p_in,))
            p2 = multiprocessing.Process(target=test2, args=(p_out,))
            p1.start()
            p2.start()

    def test2bind():
        print("G pressed")
        global p1
        global p2
        p1.terminate()
        p2.terminate()
        p1 = multiprocessing.Process(target=test1, args=(p_in,))
        p2 = multiprocessing.Process(target=test2, args=(p_out,))
        p1.start()
        p2.start()

    import keyboard
    keyboard.add_hotkey("F", test1bind)
    keyboard.add_hotkey("G", test2bind)
```

**Test.py**

```
from time import sleep

def test1(p_in):
    from time import sleep
    test = 0
    while True:
        sleep(0.1)
        test = test + 1
        p_in.send(test)

def test2(p_out):
    from time import sleep
    while True:
        img = p_out.recv()
        print(img)

def menu():
    sleep(99999)
```

**Comment by Pro100rus32** [comment]
This line always changes, depending on the use of different libraries:
`Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'C:\\Users\\andre\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keyboard\\__init__.py', 'module_name': <ModuleName keyboard>, 'code_flags': ''}>'.`

**Comment by kayhayen** [comment]
Didn't reproduce it on Linux just now, and as it's a compile time problem, I don't think it matters. At run time I had this:

```
Main.dist/keyboard/_nixkeyboard.py:110: UserWarning: Failed to create a device file using `uinput` module. Sending of events may be limited or unavailable depending on plugged-in devices.
Traceback (most recent call last):
  File "/home/hayen/repos/Py2C/Main.dist/Main.py", line 36, in <module>
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/__init__.py", line 639, in add_hotkey
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/_generic.py", line 35, in start_if_necessary
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/__init__.py", line 196, in init
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/_nixkeyboard.py", line 113, in init
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/_nixkeyboard.py", line 110, in build_device
  File "/home/hayen/repos/Py2C/Main.dist/keyboard/_nixcommon.py", line 168, in aggregate_devices
```

**Comment by kayhayen** [comment]
Interestingly, on Windows, I did reproduce it. That's unusual, but apparently factual.

**Comment by kayhayen** [comment]
Seems the multiprocessing plugin is causing it, which limits the issue to Windows. Probably as old as 0.6.9 and has to do with the demise of the `__internal__` module contents now living in `__main__`.

**Comment by kayhayen** [comment]
So, the multiprocessing module injects the slave module used for multiprocessing during the operation of `__main__` itself, where things may not yet be all that good. It's using the `onModuleEncounter` which is probably a bad idea. I guess it ought to do that only after it's finished with the `__main__` module and not in the middle of it.

**Comment by kayhayen** [comment]
I added a better interface to the plugin to add itself after the initial root module set is established, to contribute itself, eliminating a race there. The code is on factory and seems to work better.

Not sure really how this got triggered. I think, Nuitka is not normally switching modules in optimization, but with this code it did, and that might have been all there is to it.

This is of course going into a first hotfix once I do it.

**Comment by Pro100rus32** [comment]
thanks, it's working)

**Comment by kayhayen** [comment]
We keep issues open for as long as the stable version is affected.

**Comment by kayhayen** [comment]
This was in 0.6.10.1 hotfix already.
