### ISSUE TITLE
ImportError: numpy.core.multiarray | Error

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#895]
`0.6.10rc9 on 64bit`

input:
`-m nuitka --mingw64 --windows-uac-admin --assume-yes-for-downloads --windows-icon-from-ico=E:\TEST\TEST\test.ico --output-dir=E:\TEST\TEST\Current_build --standalone --plugin-enable=multiprocessing --plugin-enable=numpy --recurse-all "E:\TEST\TEST\test.py"`

Еrror when starting the program:
```
Original error was:

Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\numpy\core__init.py", line 22, in <module numpy.core>
  File "E:\1NAIM\Build\Current_build\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "E:\1NAIM\Build\Current_build\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\numpy__init.py", line 140, in <module numpy>
  File "E:\1NAIM\Build\Current_build\numpy\core__init.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "E:\1NAIM\Build\Current_build\NAIMexe.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was:

Process Process-13:
Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\multiprocessing\process.py", line 315, in _bootstrap
  File "E:\1NAIM\Build\Current_build\multiprocessing\process.py", line 108, in run
  File "E:\1NAIM\Build\Current_build\Preloading.py", line 135, in Det
  File "E:\1NAIM\Build\Current_build\cv2__init.py", line 5, in <module cv2>
ImportError: numpy.core.multiarray failed to import
```

input:
```
import os
print("PYTHONPATH:", os.environ.get('PYTHONPATH'))
print("PATH:", os.environ.get('PATH'))
```

Output:

```
PYTHONPATH: None
PATH: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\MinGW64\mingw64\bin;;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\andre\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\andre\AppData\Local\Programs\Python\Python38\;C:\Users\andre\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\andre\AppData\Local\Programs\Python\Python38-32\;C:\MinGW64\mingw64\bin\gcc.exe;C:\Users\andre\AppData\Local\Microsoft\WindowsApps;C:\Users\andre\AppData\Local\atom\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\bin;;C:\Users\andre\AppData\Local\GitHubDesktop\bin;C:\Users\andre\AppData\Local\Microsoft\WindowsApps;
```

I have python 32bit, and 64 bit (3.8.6), I use 64bit*

on 32bit python everything works!

**Comment by Pro100rus32** [comment]
If I update numpy to version 1.19.4 then I get the same error and in IDLE.

**Comment by kayhayen** [comment]
The numpy output is only guess work on their part of course. You didn't provide a minimal reproducer unfortunately.

**Comment by Pro100rus32** [comment]
It looks like this problem was in the numpy library, they released a fix under version 1.20.0rc1

**Comment by Pro100rus32** [comment]
I'm sorry, this problem seems to remain.
I just add the import of the numpy library and I get the error:

`import numpy as np #i have err`

**Main.py**

```
from Test import *
import numpy as np
if __name__=="__main__":
    import multiprocessing
    p_out, p_in = multiprocessing.Pipe()
    p1 = multiprocessing.Process(target=test1, args=(p_in,))
    p2 = multiprocessing.Process(target=test2, args=(p_out,))
    p3 = multiprocessing.Process(target=menu)
    p2.start()
    p1.start()
    p3.start()
    def test1bind():
        print("F pressed")
        global p1
        global p2
        if p1.is_alive():
            p1.terminate()
            p2.terminate()
        else:
            p1 = multiprocessing.Process(target=test1, args=(p_in,))
            p2 = multiprocessing.Process(target=test2, args=(p_out,))
            p1.start()
            p2.start()

    def test2bind():
        print("G pressed")
        global p1
        global p2
        p1.terminate()
        p2.terminate()
        p1 = multiprocessing.Process(target=test1, args=(p_in,))
        p2 = multiprocessing.Process(target=test2, args=(p_out,))
        p1.start()
        p2.start()

    import keyboard
    keyboard.add_hotkey("F", test1bind)
    keyboard.add_hotkey("G", test2bind)
```


Test.py

```
from time import sleep

def test1(p_in):
    from time import sleep
    test = 0
    while True:
        sleep(0.1)
        test = test + 1
        p_in.send(test)

def test2(p_out):
    from time import sleep
    while True:
        img = p_out.recv()
        print(img)

def menu():
    sleep(99999)
```

Output:

```
Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\Main.dist\Main.py", line 2, in <module>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\__init__.py", line 145, in <module numpy>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "E:\1NAIM\Build\Current_build\Main.dist\python.exe"
  * The NumPy version is: "1.20.0rc1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was:


C:\Users\andre>
```

**Comment by kayhayen** [comment]
I don't think I want to care about pre-release versions of Numpy just yet. Use their stable release, or help yourself. This is just for my sanity. I will look into it, once it's reported against stable releases. But they might still be figuring out these things for themselves.

**Comment by Pro100rus32** [comment]
> I don't think I want to care about pre-release versions of Numpy just yet. Use their stable release, or help yourself. This is just for my sanity. I will look into it, once it's reported against stable releases. But they might still be figuring out these things for themselves.

This works in the stable version of numpy as well. Just build the application in 64bit

**Comment by Pro100rus32** [comment]
What do I need to do to make you notice the problem?
