### ISSUE TITLE
methodtools and wirerope compatibility issue

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#896]
Hi,

I recently added the methodtools library to use lru_cache on class methods instead of just functions. It is supposed to behave exactly like lru_cache, but on methods.

methodtools has a dependency with wirerope, which is causing an issue after compile. This happens at the line where I call `@lru_cache`

```
python 3.7.6
Windows 7 with conda
Nuitka 0.6.8.4
using nuitka-hints with mingw64
```

Stripped example of how it is used:

```
from methodtools import lru_cache
class MyClass(object):
    """
    Abstract class
    """
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @lru_cache(maxsize=2)
    def my_method(self, measurements):
        return self._data_representation(measurements)

    def _data_representation(self, measurement):
        pass
```

```
Traceback (most recent call last):
  File "D:\REFC\PRO\cor.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\REFC\PRO\CorMod\__init__.py", line 3, in <module CorMod>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\REFC\PRO\CorMod\CorModMain.py", line 6, in <module CorMod.CorModMain>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\REFC\PRO\fr\Sequence.py", line 8, in <module fr.Sequence>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\REFC\PRO\fr\Analysis.py", line 673, in <module fr.Analysis>
  File "D:\REFC\PRO\fr\Analysis.py", line 702, in ResultItem
  File "D:\REFC\PRO\wirerope\rope.py", line 139, in __call__
  File "D:\REFC\PRO\wirerope\callable.py", line 109, in __init__
  File "D:\REFC\PRO\wirerope\callable.py", line 49, in detect_function_attr_name
TypeError: cannot create 'compiled_function' instances
```

Is that easy to fix?

**Comment by kayhayen** [comment]
You are using Nuitka of distant past, that is not supported.
