### ISSUE TITLE
Alpine TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#900]
Hi! 

I'm trying to build a program in Alpine Linux docker container and get the error `TypeError: expected str, bytes or os.PathLike object, not NoneType`. 

The minimal example in docker on Ubuntu:
```bash
docker run --rm -it alpine

apk update && apk add --update musl-dev gcc python3-dev py3-pip chrpath git vim mc wget make openssh-client
pip3 install -U pip nuitka

nuitka3 --version
# 0.6.10
# Python: 3.8.2 (default, Jul 18 2020, 19:35:03) 
# Executable: /usr/bin/python3.8
# OS: Linux
# Arch: x86_64

echo 'import uuid' > /tst.py
nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports /tst.py
```
Output:
```
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:WARNING: You are not using ccache.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nuitka/__main__.py", line 196, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/nuitka/__main__.py", line 189, in main
    MainControl.main()
  File "/usr/lib/python3.8/site-packages/nuitka/MainControl.py", line 758, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "/usr/lib/python3.8/site-packages/nuitka/plugins/Plugins.py", line 218, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "/usr/lib/python3.8/site-packages/nuitka/plugins/standard/ImplicitImports.py", line 1434, in considerExtraDlls
    dist_dll_path = os.path.join(dist_dir, os.path.basename(uuid_dll_path))
  File "/usr/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

What I'm doing wrong?

I tried the similar commands on Ubuntu and it works perfect. Also I tried to remove ` --standalone` and run again on Alpine and it works too.

Thanks!

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kayhayen** [comment]
Can you fix `locateDLLFromFilesystem` in `nuitka.utils.SharedLibraries` to work with the `uuid` argument. I guess, it needs to check for filename with `.so` suffix, it was once contributed by an Alpine user. I don't have the system.

**Comment by anki-code** [comment]
The solution turned out to be simple:
```bash
apk add libuuid
```
Thanks!

**Comment by anki-code** [comment]
The cause of the error here:

https://github.com/Nuitka/Nuitka/blob/2a3471c060101f19c0388acaf5550199d3c73b03/nuitka/utils/SharedLibraries.py#L50-L52

This code returns `None` because there is no `uuid` library installed.

The solution turned out to be simple:
```bash
apk add libuuid
```
Thanks!

**Comment by kayhayen** [comment]
Duplicate of #1046 but the way you are reporting seems to suggest it worked in Python, but I now believe it never did due to lack of the library.

**Comment by kayhayen** [comment]
Removing for lack of feedback.
