### ISSUE TITLE
Import error for pocketsphinx running on AIY kit

### ISSUE THREAD

**Issue by Python-retropie-raspberry-pi-hobby** [Nuitka/Nuitka#905]
I am reprogramming a AIY voice kit to be independent of Google. The code I'm working on works fine on regular python3 , but I am not satisfied with speed.  Here is my code:

[speack.txt](https://github.com/Nuitka/Nuitka/files/5695873/speack.txt)

 Here is the command I use to run it:
```
python3 -m nuitka --run --follow-imports /home/pi/AIY-voice-kit-python/src/examples/voice/speack.py
```
It runs until it reaches 
```
from pocketsphinx import LiveSpeech, get_model_path
```
and then gives me this error message:
```
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 20 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (direct)': 20
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_pulse.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxbase._ad_pulse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/__init__.py", line 40, in <module sphinxbase>
    from .ad_pulse import *
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_pulse.py", line 32, in <module sphinxbase.ad_pulse>
    _ad_pulse = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_pulse.py", line 31, in swig_import_helper
    return importlib.import_module('_ad_pulse')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ad_pulse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_alsa.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxbase._ad_alsa'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/src/examples/voice/speack.py", line 11, in <module>
    from pocketsphinx import LiveSpeech, get_model_path
  File "/usr/local/lib/python3.7/dist-packages/pocketsphinx/__init__.py", line 35, in <module pocketsphinx>
    from sphinxbase import *
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/__init__.py", line 42, in <module sphinxbase>
    from .ad_alsa import *
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_alsa.py", line 32, in <module sphinxbase.ad_alsa>
    _ad_alsa = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/sphinxbase/ad_alsa.py", line 31, in swig_import_helper
    return importlib.import_module('_ad_alsa')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ad_alsa'
```
Can anyone help?

**Comment by kayhayen** [comment]
Filling out the issue template would be very necessary, but this seems to be a case of missing implicit dependencies. Can you provide the missing information?

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
My apologies:
I'm using linux 32x raspberry pi os (buster) on a raspberry pi 3b+
```
 0.6.9.6
Python: 3.7.3 (default, Jul 25 2020, 13:03:44) 
Executable: /usr/bin/python3
OS: Linux
Arch: armv7l
```

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
@kayhayen  I can't find evidence of missing dependencies for the python module, Is that what you meant?

**Comment by kayhayen** [comment]
I think this is roughly what I need, the missing dependency is the problem of Nuitka, it cannot see the call to `importlib.import_module('_ad_alsa')`, but that is subject to change now.

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
Actually I just updated the nuitka and It fixed the problem, you can close
this issue.

**Comment by kayhayen** [comment]
I am not quite conviced it could have fixed it. 

Definitely I want to use this to track the `importlib.import_module` static optimization that would be needed to handle this kind of thing. I added better support for hard module imports from standard library the other day, and mean to become able to optimize attribute lookups on these soon, and then their calls, to be able to convert this to a mere `__import__` usage.

**Comment by Python-retropie-raspberry-pi-hobby** [comment]
I haven't encountered any errors so far.
```
0.6.10.1
Python: 3.7.3 (default, Jul 25 2020, 13:03:44) 
Executable: /usr/bin/python3
OS: Linux
Arch: armv7l
```

**Comment by kayhayen** [comment]
Since you claim it went away, and this optimization that I am talking about is being implemented, I am closing this now.
