### ISSUE TITLE
Error using Nuitka for Python App that uses Numpy and Plotly

### ISSUE THREAD

**Issue by knadoor** [Nuitka/Nuitka#908]
**Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)**

0.6.10.2
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Users\user\PycharmProjects\PlotlyTest\venv\Scripts\python.exe
OS: Windows
Arch: x86_64

**How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source**
Python was installed using the 64-bit setup file in Windows and I installed Nuitka via the command:
pip install nuitka

This was done in the project directory within Pycharm.

**And the following command was used to run Nuitka:**
`python -m nuitka --standalone --show-progress --recurse-all --plugin-enable=numpy main.py`

The program itself is quite simple and was written to test out a few things, the following are the imports:
import plotly.graph_objects as go
import numpy as np
import os
from pptx import Presentation
from pptx.util import Inches
from PIL import Image

And this is the error I see when I run the generated executable:
```
C:\Users\user\PycharmProjects\PlotlyExample\main.dist>main
Traceback (most recent call last):
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ImportError: LoadLibraryExW 'C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\_multiarray_umath.pyd' failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\main.py", line 5, in <module>
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\__init__.py", line 140, in <module numpy>
  File "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\python.exe"
  * The NumPy version is: "1.19.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: LoadLibraryExW 'C:\Users\\user\PYCHAR~1\PLOTLY~1\MAIN~1.DIS\numpy\core\_multiarray_umath.pyd' failed: The specified module could not be found.
```
Thanks All!

Krishna

**Comment by Pro100rus32** [comment]
I asked the same question - https://github.com/Nuitka/Nuitka/issues/895

**Comment by kayhayen** [comment]
I failed to reproduce this on python3.9 and Linux just now. This is 1.19.3 of yours, I was using 1.19.4, but maybe it's a Windows only issue, probably again related to where DLLs are located, there seems to be some movement there all the time, or maybe even if a regression of Nuitka is at play.

**Comment by Pro100rus32** [comment]
> I failed to reproduce this on python3.9 and Linux just now. This is 1.19.3 of yours, I was using 1.19.4, but maybe it's a Windows only issue, probably again related to where DLLs are located, there seems to be some movement there all the time, or maybe even if a regression of Nuitka is at play.

Are you sure you checked on 64bit python?)
Since this doesn't work only on 64bit python.

**Comment by kayhayen** [comment]
I didn't check Windows yet, but I will. I prefer Linux for debugging, as it's often easier to find out what's going wrong due to me better knowing my tools there, but yeah, going to check it out. I am using 64 bit first usually.

**Comment by kayhayen** [comment]
My first attempt is with 1.18.5 which I think I know is working, then checking out, what changes in file system when I go to 1.19.3/4 which will likely reveal things.

**Comment by kayhayen** [comment]
The installation diff in term of whole file differences:

```
diff -r numpy-1.18.5/ numpy | grep "Only in"

# Manually removed tests and false matches, or pyx files that wouldn't matter.

Only in numpy/.libs: libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
Only in numpy-1.18.5/.libs: libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
Only in numpy-1.18.5/distutils: compat.py
Only in numpy/distutils/fcompiler: nv.py
Only in numpy-1.18.5/random: _bit_generator.cp38-win_amd64.pyd
Only in numpy/random: bit_generator.cp38-win_amd64.pyd
Only in numpy/random: lib
`````

The random/lib folder is suspicious, I don't know what the contained file is for, it appears to be an `ar` archive, nothing that ought to matter at runtime.

The other thing is the change in `bit_generator`, that is something that we do have implicit imports for, and it seems we managed at least some 1.19.x version at some point, because there is implicit dependency attempted for both names, and therefore it ought to work.

Ah, and I am affected by this: https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html

Seems I cannot even use Numpy on Windows currently.

**Comment by kayhayen** [comment]
@Pro100rus32 funnily that errors is Windows 64 bit only... maybe they are catching it, and yes indeed, check it out:

https://numpy.org/devdocs/release/1.19.4-notes.html

Are you on Windows 10 2004 already? @knadoor @Pro100rus32

**Comment by knadoor** [comment]
Thanks all, @kayhayen  yeah I'm on Windows 10 64-bit.

I previously use Numpy version 1.19.4 and received an error ( “runtimeError: package fails to pass a sanity check" - not Nuitka related) due to some known Numpy bug, then downgraded to 1.19.3.

**Comment by Pro100rus32** [comment]
> Are you on Windows 10 2004 already?

![image](https://user-images.githubusercontent.com/64806740/102959997-fb5e4b00-44f1-11eb-9c54-2aed805006ed.png)

**Comment by kayhayen** [comment]
@knadoor it is Nuitka related though, the DLL in question is a conflict, and Nuitka resolves these to use the latest ones, where 2 are used, and it does so by version information comparison. I think that may well be the issue then, and there is no way I am going to waste my time on a non-working configuration like that.

However 1.20.0rc1 seems available and the check is not present, so maybe that is supposed to work now. Trying it out, but I don't like rc versions really, as they might have other issues.

**Comment by Pro100rus32** [comment]
Something happened.
Now 32bit assembly does not work for me either...

Output:

```
Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\__init__.py", line 22, in <module numpy.core>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\multiarray.py", line 12, in <module numpy.core.multiarray>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\overrides.py", line 7, in <module numpy.core.overrides>
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\1NAIM\Build\Current_build\Main.dist\Main.py", line 2, in <module>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\__init__.py", line 140, in <module numpy>
  File "E:\1NAIM\Build\Current_build\Main.dist\numpy\core\__init__.py", line 48, in <module numpy.core>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "E:\1NAIM\Build\Current_build\Main.dist\python.exe"
  * The NumPy version is: "1.19.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was:


C:\Users\andre>nuitka --version
0.6.10.2
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38-32\python.exe
OS: Windows
Arch: x86
```

**Comment by kayhayen** [comment]
Trying myself @Pro100rus32 hoping you didn't just forget to enable the plugin. There really are plugins that are kind of mandatory, and numpy is maybe one of them, some versions won't work at all without the plugin, while some will. Not sure what to do about that, making plugins something that are to be disabled rather than enabled is a possible way out.

**Comment by kayhayen** [comment]
Happening to me too, @Pro100rus32 so I guess, that's something actionable then and it doesn't trigger the warning in 1.19.4 or 1.20.0rc1, so it ought to be workable, lets see what's the matter there.

**Comment by Pro100rus32** [comment]
> Trying myself @Pro100rus32 hoping you didn't just forget to enable the plugin. There really are plugins that are kind of mandatory, and numpy is maybe one of them, some versions won't work at all without the plugin, while some will. Not sure what to do about that, making plugins something that are to be disabled rather than enabled is a possible way out.

I am using plugins.

Here is:

python -m nuitka --mingw64 --windows-uac-admin --windows-icon-from-ico=E:\test\Other\Media\Sp7EYBpX_hY.ico --output-dir=E:\test\Build\Current_build --standalone --plugin-enable=multiprocessing  --plugin-enable=numpy --plugin-enable=pylint-warnings  "E:\test\test\Main.py"

**Comment by knadoor** [comment]
I happen to be using Plotly for some of my other activities.

**Comment by kayhayen** [comment]
Seems I broke numpy when adding macOS support blindly, i.e. without testing and apparently also without feedback, works on neither now, this must be a regression, that I sadly failed to catch. Hotfix and factory are coming once confirmed.

**Comment by kayhayen** [comment]
Ok, Windows and macOS are broken only, but still, sad to see this happen.

**Comment by NeuralAIM** [comment]
Thanks, now everything works :)

**Comment by noonchen** [comment]
I think issue #843 is related to this one.

**Comment by NeuralAIM** [comment]
> I think issue #843 is related to this one.

This already works as of 0.6.10.4

**Comment by kayhayen** [comment]
This has been released as 0.6.10.4 already.
