### ISSUE TITLE
Error import main

### ISSUE THREAD

**Issue by NeuralAIM** [Nuitka/Nuitka#918]
```
0.6.10.4
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```

`python -m nuitka --mingw64 --standalone "E:\TEST\TEST\main.py"`

**main.py**

```
from main2 import *
print(1)
```

**main2.py**

```
from main import *
print(2)
```

_**Out:**_

```
Traceback (most recent call last):
  File "E:\TEST\Build\Current_build\main.dist\main.py", line 1, in <module>
  File "E:\TEST\Build\Current_build\main.dist\main2.py", line 1, in <module main2>
ModuleNotFoundError: No module named 'main'
```

**Comment by kayhayen** [comment]
This works for me though. Notice this is not a circular import, this is `__main__` importing `main2` which then imports a duplicate `main`, and that's all supported.
