### ISSUE TITLE
Replacing rich comparison nodes with their inverted can lead to crashes during optimization

### ISSUE THREAD

**Issue by mantejemilence1** [Nuitka/Nuitka#919]
python -m nuitka newdesg.py --standalone --plugin-enable=qt-plugins --plugin-enable=numpy --plugin-enable=torch

i have used the command above for creating standalone package 
python:3.7
ubuntu :20.04

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:592:
->     def _pattern(self, pData):

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:592:
->     def _pattern(self, pData):

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:572:
-> class Trie():

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:572:
-> class Trie():

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:572:
-> class Trie():

Problem with statement at /home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py:572:
-> class Trie():

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': '/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py', 'module_name': <ModuleName torch.utils.hipify.hipify_python>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 196, in <module>
    main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 189, in main
    MainControl.main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 691, in main
    main_module = createNodeTree(filename=filename)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 149, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 631, in optimize
    finished = makeOptimizationPass()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 537, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 185, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 106, in optimizeCompiledPythonModule
    module.computeModule()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 509, in computeModule
    trace_collection=self.trace_collection
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/AssignNodes.py", line 278, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 488, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/OutlineNodes.py", line 227, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/LocalsDictNodes.py", line 397, in computeStatement
    trace_collection=trace_collection
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/NodeBases.py", line 849, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression=expression)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 488, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ExpressionBases.py", line 1060, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 488, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FunctionNodes.py", line 953, in computeExpressionRaw
    function_body.computeFunctionRaw(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FunctionNodes.py", line 433, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FunctionNodes.py", line 449, in computeFunction
    trace_collection=trace_collection
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/TryNodes.py", line 112, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ConditionalNodes.py", line 578, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 730, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 507, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ConditionalNodes.py", line 521, in computeStatement
    condition.computeExpressionBool(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ExpressionBases.py", line 611, in computeExpressionBool
    BaseException
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/VariableRefNodes.py", line 492, in mayRaiseExceptionBool
    or not self.variable_trace.getTypeShape().hasShapeSlotBool()
AttributeError: 'NoneType' object has no attribute 'hasShapeSlotBool'

**Comment by kayhayen** [comment]
The fix is on factory and should appear in a hotfix later https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
The issue was that during optimization, `not something < something2` was replaced to be `something >= something2` with it as a fresh node during the optimization of the `not` slot, however, the type shape information that is usually attached to expressions wasn't then there. Now it's copying it over to the new node, avoiding the crash. That kind of thing might be more common, but for now this fixes that kind of code.

**Comment by mantejemilence1** [comment]
@kayhayen 
Problem with statement at newdesg.py:1:
-> import sys

Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'newdesg.py', 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 199, in <module>
    main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 192, in main
    MainControl.main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 693, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 149, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 625, in optimize
    makeOptimizationPass()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 537, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 185, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 106, in optimizeCompiledPythonModule
    module.computeModule()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 505, in computeModule
    trace_collection=self.trace_collection
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 517, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 223, in computeStatement
    expression = trace_collection.onExpression(expression=self.subnode_expression)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 498, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ExpressionBases.py", line 1087, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 541, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 413, in _attemptRecursion
    module_package=module_package,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 333, in _consider
    module_kind=module_kind,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 143, in decideRecursion
    module_filename, module_name, module_kind
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 349, in onModuleEncounter
    module_filename, module_name, module_kind
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/standard/NumpyPlugin.py", line 375, in onModuleEncounter
    if module_name.startswith("matplotlib.backends.backend_qt"):
  File "<string>", line 11, in startswith
nuitka.Errors.NuitkaCodeDeficit: 
Do not use startswith on ModuleName objects, use e.g.
.hasNamespace(),
.getBasename(),
.getTopLevelPackageName()
.hasOneOfNamespaces

Check API documentation of nuitka.utils.ModuleNames.ModuleName

**Comment by kayhayen** [comment]
@mantejemilence1 thanks, that was even affecting develop, retry please this should work now

**Comment by mantejemilence1** [comment]
@kayhayen 

(yolact-env) elad@elad-Alienware-m15-R3:~/Downloads/yolact$ python -m nuitka newdesg.py --standalone --plugin-enable=qt-plugins --plugin-enable=numpy --plugin-enable=torch
Nuitka:INFO: Starting Python compilation.
Problem with statement at newdesg.py:4:
-> from PyQt5.QtCore import *

Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'newdesg.py', 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
Traceback (most recent call last):
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 199, in <module>
    main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 192, in main
    MainControl.main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 691, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 149, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 609, in optimize
    makeOptimizationPass()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 542, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 190, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 111, in optimizeCompiledPythonModule
    module.computeModule()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 505, in computeModule
    trace_collection=self.trace_collection
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 517, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 650, in computeStatement
    trace_collection.onExpression(self.subnode_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 498, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ExpressionBases.py", line 1087, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 539, in computeExpression
    trace_collection=trace_collection, module_name=imported_module_name
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 411, in _attemptRecursion
    module_package=module_package,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 342, in _consider
    reason=reason,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 130, in recurseTo
    reason=reason,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 110, in _recurseTo
    ImportCache.addImportedModule(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/ImportCache.py", line 48, in addImportedModule
    Plugins.onModuleDiscovered(imported_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 306, in onModuleDiscovered
    plugin.onModuleDiscovered(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 414, in onModuleDiscovered
    post_code, reason = self.createPostModuleLoadCode(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 429, in createPostModuleLoadCode
    qt_version = int(full_name.split(".")[0][-1])
  File "<string>", line 11, in split
nuitka.Errors.NuitkaCodeDeficit: 
Do not use split on ModuleName objects, use e.g.
.hasNamespace(),
.getBasename(),
.getTopLevelPackageName()
.hasOneOfNamespaces

Check API documentation of nuitka.utils.ModuleNames.ModuleName

still facing the same issue

**Comment by NeuralAIM** [comment]
> @kayhayen
> 
> (yolact-env) elad@elad-Alienware-m15-R3:~/Downloads/yolact$ python -m nuitka newdesg.py --standalone --plugin-enable=qt-plugins --plugin-enable=numpy --plugin-enable=torch
> Nuitka:INFO: Starting Python compilation.
> Problem with statement at newdesg.py:4:
> -> from PyQt5.QtCore import *
> 
> Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'newdesg.py', 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
> Traceback (most recent call last):
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/**main**.py", line 199, in
> main()
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/**main**.py", line 192, in main
> MainControl.main()
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 691, in main
> main_module = _createNodeTree(filename=filename)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 149, in _createNodeTree
> Optimization.optimize(main_module.getOutputFilename())
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 609, in optimize
> makeOptimizationPass()
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 542, in makeOptimizationPass
> changed = optimizeModule(current_module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 190, in optimizeModule
> changed = optimizeCompiledPythonModule(module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 111, in optimizeCompiledPythonModule
> module.computeModule()
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 505, in computeModule
> trace_collection=self.trace_collection
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
> new_statement = statement.computeStatementsSequence(trace_collection)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
> new_statement = trace_collection.onStatement(statement=statement)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 517, in onStatement
> new_statement, change_tags, change_desc = statement.computeStatement(self)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 650, in computeStatement
> trace_collection.onExpression(self.subnode_module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 498, in onExpression
> r = expression.computeExpressionRaw(trace_collection=self)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ExpressionBases.py", line 1087, in computeExpressionRaw
> return self.computeExpression(trace_collection=trace_collection)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 539, in computeExpression
> trace_collection=trace_collection, module_name=imported_module_name
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 411, in _attemptRecursion
> module_package=module_package,
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ImportNodes.py", line 342, in _consider
> reason=reason,
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 130, in recurseTo
> reason=reason,
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 110, in _recurseTo
> ImportCache.addImportedModule(module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/ImportCache.py", line 48, in addImportedModule
> Plugins.onModuleDiscovered(imported_module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/Plugins.py", line 306, in onModuleDiscovered
> plugin.onModuleDiscovered(module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/PluginBase.py", line 414, in onModuleDiscovered
> post_code, reason = self.createPostModuleLoadCode(module)
> File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 429, in createPostModuleLoadCode
> qt_version = int(full_name.split(".")[0][-1])
> File "", line 11, in split
> nuitka.Errors.NuitkaCodeDeficit:
> Do not use split on ModuleName objects, use e.g.
> .hasNamespace(),
> .getBasename(),
> .getTopLevelPackageName()
> .hasOneOfNamespaces
> 
> Check API documentation of nuitka.utils.ModuleNames.ModuleName
> 
> still facing the same issue

This is a factory bug, there is no such bug in the stable version.

**Comment by kayhayen** [comment]
Ok, please retry again @mantejemilence1 @NeuralAIM seems more than plugin is regressed on develop.

**Comment by mantejemilence1** [comment]
Traceback (most recent call last):
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 199, in <module>
    main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/__main__.py", line 192, in main
    MainControl.main()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 691, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/MainControl.py", line 149, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 609, in optimize
    makeOptimizationPass()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 542, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 187, in optimizeModule
    optimizeShlibModule(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 180, in optimizeShlibModule
    _attemptRecursion(module)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 56, in _attemptRecursion
    new_modules = module.attemptRecursion()
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 98, in attemptRecursion
    warn=python_version < 0x300,
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Importing.py", line 285, in findModule
    module_filename = _findModule(module_name=module_name)
  File "/home/elad/anaconda3/envs/yolact-env/lib/python3.7/site-packages/nuitka/importing/Importing.py", line 569, in _findModule
    assert module_name.getBasename(), module_name
AssertionError: PyQt5.

**Comment by kayhayen** [comment]
@mantejemilence1 that's not happening for me, I believe this might be `.pyi` files being parsed wrongly, but you to9ok great care to hide what module triggered it by shortening the output.

**Comment by kayhayen** [comment]
Release as part of 0.6.10.5 hotfix just now.
