### ISSUE TITLE
The dill plugin is not working, giving macro "MAKE_CODEOBJECT" requires 9 arguments, but only 8 given in C compile

### ISSUE THREAD

**Issue by chwba** [Nuitka/Nuitka#952]
Compile args: 
python -m nuitka --follow-imports^
                 --show-progress^
                 --show-scons^
                 --assume-yes-for-downloads^
                 --warn-unusual-code^
                 --windows-disable-console^
                 --windows-icon-from-ico="myicon.ico"^
                 --plugin-enable=numpy^
                 --plugin-enable=multiprocessing^
                 --plugin-enable=dill-compat^
                 --plugin-enable=pylint-warnings^
                 --windows-dependency-tool=pefile^
                 --experimental=use_pefile_recurse^
                 --experimental=use_pefile_fullrecurse^
                 --standalone^
                 --windows-company-name=mycompany^
                 --windows-product-name=myproduct^
                 --windows-product-version=123^
                 --mingw64^
                 --include-data-file=some_data.txt=some_data.txt^
                 --include-data-file=folder_with-files/*=folder_fith_files/^
                 app.py

Log: https://pastebin.com/raw/WpauBx7Z
Full-log: https://nextcloud.mnwd.in/s/aK6wfYFM6EEJ9NX

Used dependencies:
```
git+git://github.com/potocpav/python-concur
concur-imgui >= 1.3.9
Pillow
glfw
PyOpenGL
imageio
imageio-ffmpeg
pandas
ujson
emoji
requests
brotli
brotlipy
aiohttp
loguru
pycryptodomex
pywin32
wmi
git+git://github.com/chwba/pyshorteners@master
semantic_version
rich
multiprocess
psutil
pdoc3
git+git://github.com/Preston-Landers/pyuac
colorlog
colorama
pygments
cryptography
concur
validators
beautifulsoup4
numpy
```

**Comment by kayhayen** [comment]
The dill plugin was regressed when an additional field of code objects became supported, this is fixed on factory and will likely be in the next hotfix: https://nuitka.net/doc/factory.html

**Comment by chwba** [comment]
Tried again with factory, it failed with:

```
Nuitka:INFO: Finding dependencies for app.dist\pythoncom39.dll took 0.74 seconds
Nuitka:INFO: Finding dependencies for app.dist\pywintypes39.dll took 0.01 seconds
Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\nuitka\MainControl.py", line 739, in main
    copyUsedDLLs(
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\nuitka\freezer\Standalone.py", line 1530, in copyUsedDLLs
    shutil.copyfile(dll_filename, target_path)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'app.dist\\pythoncom39.dll'
```

**Comment by kayhayen** [comment]
You are using `--windows-disable-console` and then you wonder why it doesn't output anything?

**Comment by chwba** [comment]
> You are using `--windows-disable-console` and then you wonder why it doesn't output anything?

good point :D - I thought If run the app via CMD it would still print the stdout.

**Comment by chwba** [comment]
Alright recompiled it, first got an error from glfw `Failed to load shared library`, so I copied over the glfw.dll. Then started again and got:

```
before imports
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\app.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\src\base\State.py", line 5, in <module src.base.State>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\src\views\guild_joiner_gui.py", line 13, in <module src.views.guild_joiner_gui>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\src\features\online_stayer\OnlineStayer.py", line 6, in <module src.features.online_stayer.OnlineStayer>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\src\features\online_stayer\os_gateway.py", line 13, in <module src.features.online_stayer.os_gateway>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\aiohttp\__init__.py", line 6, in <module aiohttp>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\ADMINI~1\DOCUME~1\COMPIL~1\SOURCE~1\APP~1.DIS\aiohttp\client.py", line 1121, in <module aiohttp.client>
TypeError: GenericAlias expected 2 arguments, got 3
```
aiohttp is a library, the app needs  to function properly.

**Comment by kayhayen** [comment]
Manually copying stuff is not supported. Please file new issues with minimal reproducers of the first issues that happens.

**Comment by chwba** [comment]
Alright, I will try to create a reproduceable scenario for it, do not that aiohttp has no relation to glfw whatsoever - glfw is being used for the UI, aiohttp does network requests. I doubt its the cause.

**Comment by chwba** [comment]
Issue 1 regarding GLFW: https://github.com/Nuitka/Nuitka/issues/964

**Comment by chwba** [comment]
Issue 2 regarding aiohttp: https://github.com/Nuitka/Nuitka/issues/966

**Comment by kayhayen** [comment]
The dill plugin was repaired 0.6.11.4 already.
