### ISSUE TITLE
ImportError: C extension: LoadLibraryExW 'C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\_libs\interval.pyd' failed: The specified module could not be found. not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

### ISSUE THREAD

**Issue by gauravkhandelwal140** [Nuitka/Nuitka#957]
After convert my .py file in .exe using Nuitka Lib. its show this type of error
 
C:\Users\NETCOM\Desktop\project\BilltoJson.dist>BilltoJson.exe
Traceback (most recent call last):
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\__init__.py", line 30, in <module pandas>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\_libs\__init__.py", line 13, in <module pandas._libs>
    from pandas._libs.interval import Interval
ImportError: LoadLibraryExW 'C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\_libs\interval.pyd' failed: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\BilltoJson.py", line 1, in <module>
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\tabula\__init__.py", line 3, in <module tabula>
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\tabula\io.py", line 31, in <module tabula.io>
  File "C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\__init__.py", line 38, in <module pandas>
    ) from e
ImportError: C extension: LoadLibraryExW 'C:\Users\NETCOM\Desktop\project\BILLTO~1.DIS\pandas\_libs\interval.pyd' failed: The specified module could not be found. not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

<img width="960" alt="Error" src="https://user-images.githubusercontent.com/60732078/105976790-9a103580-60b6-11eb-931c-3f2805d931ba.png">

Can someone tell me how to solve this Error.

**Comment by kayhayen** [comment]
This issue didn't fill out the issue template, provided a screenshot rather than error messages, and didn't provide a script to reproduce. On top of that pandas is know to work, but we were not even informed which Nuitka was used.
