### ISSUE TITLE
ValueError: path is on mount 'C:', start on mount 'E:'

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#961]
```
0.6.11.2
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```

Output:
`python -m nuitka --clang --standalone --windows-uac-admin --windows-icon-from-ico=E:\Test\Test\Media\Sp7EYBpX_hY.ico --output-dir=E:\Test\Test\Test --plugin-enable=numpy "E:\Test\Test.py"`

```
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang-cl (clang-cl).
Nuitka-Scons:INFO: Compiled 127 C files using clcache with 7 cache hits and 120 cache misses.
Nuitka-Plugins:INFO: numpy: Copied 1 file from 'numpy' installation.
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\MainControl.py", line 768, in main
    copyDataFiles(dist_dir=dist_dir)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 1668, in copyDataFiles
    _handleDataFile(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 1608, in _handleDataFile
    assert isPathBelow(dist_dir, target_filename)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\utils\FileOperations.py", line 477, in isPathBelow
    return os.path.relpath(filename, path)[:3].split(os.path.sep) != ".."
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'E:'
```

**Comment by kayhayen** [comment]
That's something not considered so far, I will include it in the next hotfix.

**Comment by kayhayen** [comment]
This is currently on factory and in the next hotfix.

**Comment by Pro100rus32** [comment]
```
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
C Source Generation:  67%|█████████████████▎        | 78/117 [00:10<00:06,  5.84module/s, item=numpy.lib.function_base]
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang-cl (clang-cl).
Nuitka-Scons:INFO: Compiled 127 C files using clcache with 127 cache hits and 0 cache misses.
Nuitka-Plugins:INFO: numpy: Copied 1 file from 'numpy' installation.
C Source Generation: 100%|█████████████████████████| 117/117 [00:40<00:00, 10.65module/s, item=win32com.shell.shellcon]Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\__main__.py", line 195, in main
    MainControl.main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\MainControl.py", line 745, in main
    copyDataFiles(dist_dir=dist_dir)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 1663, in copyDataFiles
    _handleDataFile(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\freezer\Standalone.py", line 1608, in _handleDataFile
    if not isPathBelow(dist_dir, target_filename):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\nuitka\utils\FileOperations.py", line 477, in isPathBelow
    return os.path.relpath(filename, path).split(os.path.sep)[0] != ".."
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'E:'


C:\Users\andre>nuitka --version
0.6.12rc3
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```

**Comment by kayhayen** [comment]
The line numbers do not indicate current factory or even that of the other day, this is fixed in the last hotfix that is out as well, or so I strongly hope :)

**Comment by Pro100rus32** [comment]
Sorry, this is a PIP bug. Thanks)
