### ISSUE TITLE
Indicate tests are non-functional before skipping them due to missing deps

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#965]
I read the test logs looking for new tests that depend on missing deps.

I then enable add those deps to the build environment and re-run the tests, only to find a message like

> [ 3420s] Skipped, NumpyUsing.py (numpy.test not fully working yet).

I then need to edit my build scripts to remove those deps again because they are useless, and restart my builds.

It would be helpful if non-functional tests first say they are non-functional, and then maybe note they depend on missing deps, so I can see immediately that it is pointless trying to get them working.

**Comment by kayhayen** [comment]
That's actually just a laziness of mine, I think, I will make it work, or remove it. Numpy is actually covered by pretty much everything, just not on its own.

I was thinking of a default mode for standalone tests where coverage is the goal, and a mode, where relatively useless stuff is being done, e.g. to use Numpy or PyQt5 in isolation.

**Comment by jayvdb** [comment]
If we're going to get all of these working, BotoUsing is another one currently not enabled iirc.
I'd love the greater coverage.  If they are likely to work, I can probably easily do builds of them by using `sed` in the `.spec`, and report back any which fail.

**Comment by jayvdb** [comment]
NumpyUsing (which is just invoking its test suite) depends on pytest, and possibly other test deps (hypothesis?).

**Comment by jayvdb** [comment]
Forced-running Botousing:

```
[  520s] Comparing output of 'Boto3Using.py' using '/usr/bin/python3.8' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing ...
[ 1105s] --- /usr/bin/python3.8 (stdout)
[ 1105s] +++ nuitka (stdout)
[ 1105s] 
[ 1105s] @@ -1,2 +1 @@
[ 1105s] 
[ 1105s] -OK.
[ 1105s]  
[ 1105s] --- /usr/bin/python3.8 (stderr)
[ 1105s] +++ nuitka (stderr)
[ 1105s] 
[ 1105s] @@ -1 +1,9 @@
[ 1105s] 
[ 1105s] +Traceback (most recent call last):
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/Boto3Using.dist/Boto3Using.py", line 74, in <module>
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/Boto3Using.dist/moto/__init__.py", line 8, in f
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/importlib.py", line 127, in import_module
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/<frozen importlib._bootstrap>", line 1014, in _gcd_import
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/<frozen importlib._bootstrap>", line 991, in _find_and_load
[ 1105s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
[ 1105s] +ModuleNotFoundError: No module named 'moto.s3'
...
```

**Comment by jayvdb** [comment]
NumpyUsing

```
[  724s] Comparing output of 'NumpyUsing.py' using '/usr/bin/python3.8' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing ...
[ 2312s] --- /usr/bin/python3.8 (stdout)
[ 2312s] +++ nuitka (stdout)
[ 2312s] 
[ 2312s] @@ -1,163 +1 @@
[ 2312s] 
[ 2312s] -NumPy version 1.19.5
[ 2312s] -NumPy relaxed strides checking option: True
[ 2312s] -.............................................................x.......... [  0%]
[ 2312s] -......................................................ss................ [  1%]
[ 2312s] -........................................................................ [  1%]
[ 2312s] -.......................s................................................ [  2%]
[ 2312s] -...................................................x..........x..x...... [  3%]
[ 2312s] -....x................................................................... [  3%]
[ 2312s] -....................s................................................... [  4%]
[ 2312s] -..................................ssss................................x. [  5%]
[ 2312s] -........................................................................ [  5%]
[ 2312s] -........................................................................ [  6%]
[ 2312s] -........................................................................ [  7%]
[ 2312s] -........................................................................ [  7%]
[ 2312s] -........................................................................ [  8%]
[ 2312s] -........................................................................ [  9%]
[ 2312s] -........................................................................ [  9%]
[ 2312s] -........................................................................ [ 10%]
[ 2312s] -........................................................................ [ 11%]
[ 2312s] -........................................................................ [ 11%]
[ 2312s] -........................................................................ [ 12%]
[ 2312s] -........................................................................ [ 13%]
[ 2312s] -........................................................................ [ 13%]
[ 2312s] -........................sss............................................. [ 14%]
[ 2312s] -........................................................................ [ 15%]
[ 2312s] -.............................xx......................................... [ 15%]
[ 2312s] -........................................................................ [ 16%]
[ 2312s] -.............s.......................................................... [ 17%]
[ 2312s] -........................................................................ [ 17%]
[ 2312s] -........................................................................ [ 18%]
[ 2312s] -........................................................................ [ 18%]
[ 2312s] -........................................................................ [ 19%]
[ 2312s] -........................................................................ [ 20%]
[ 2312s] -........................................................................ [ 20%]
[ 2312s] -...............................................x...x.................... [ 21%]
[ 2312s] -........................................................................ [ 22%]
[ 2312s] -...............................................xx....................... [ 22%]
[ 2312s] -........................................................................ [ 23%]
[ 2312s] -........................................................................ [ 24%]
[ 2312s] -........................................................................ [ 24%]
[ 2312s] -........................................................................ [ 25%]
[ 2312s] -........................................................................ [ 26%]
[ 2312s] -........................................................................ [ 26%]
[ 2312s] -........................................................................ [ 27%]
[ 2312s] -..................................s..................................... [ 28%]
[ 2312s] -........................................................................ [ 28%]
[ 2312s] -...............s............................................s........... [ 29%]
[ 2312s] -........................................................................ [ 30%]
[ 2312s] -........................................................................ [ 30%]
[ 2312s] -........................................................................ [ 31%]
[ 2312s] -........................................................................ [ 32%]
[ 2312s] -........................................................................ [ 32%]
[ 2312s] -........................................................................ [ 33%]
[ 2312s] -........................................................................ [ 34%]
[ 2312s] -........................................................................ [ 34%]
[ 2312s] -................................................................s..s.... [ 35%]
[ 2312s] -........s............................................................... [ 36%]
[ 2312s] -........................................................................ [ 36%]
[ 2312s] -........................................................................ [ 37%]
[ 2312s] -........................................................................ [ 37%]
[ 2312s] -........................................................................ [ 38%]
[ 2312s] -......................................................s...........ssssss [ 39%]
[ 2312s] -sssssssss...............sssssssssssssss......................sssssssssss [ 39%]
[ 2312s] -ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 40%]
[ 2312s] -ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 41%]
[ 2312s] -ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 41%]
[ 2312s] -ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 42%]
[ 2312s] -ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 43%]
[ 2312s] -ss..ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 43%]
[ 2312s] -ssssssss................................................................ [ 44%]
[ 2312s] -........................................................................ [ 45%]
[ 2312s] -........................................................................ [ 45%]
[ 2312s] -...............x........................................................ [ 46%]
[ 2312s] -........................................................................ [ 47%]
[ 2312s] -........................................................................ [ 47%]
[ 2312s] -........................................................................ [ 48%]
[ 2312s] -........................................................................ [ 49%]
[ 2312s] -........................................................................ [ 49%]
[ 2312s] -........................................................................ [ 50%]
[ 2312s] -........................................................................ [ 51%]
[ 2312s] -........................................................................ [ 51%]
[ 2312s] -........................................................................ [ 52%]
[ 2312s] -.......................................x................................ [ 53%]
[ 2312s] -........................................................................ [ 53%]
[ 2312s] -........................................................................ [ 54%]
[ 2312s] -........................................................................ [ 55%]
[ 2312s] -........................................................................ [ 55%]
[ 2312s] -........................................................................ [ 56%]
[ 2312s] -........................................................................ [ 56%]
[ 2312s] -........................................................................ [ 57%]
[ 2312s] -........................................................................ [ 58%]
[ 2312s] -........................................................................ [ 58%]
[ 2312s] -........................................................................ [ 59%]
[ 2312s] -........................................................................ [ 60%]
[ 2312s] -....................................................x................... [ 60%]
[ 2312s] -........................................................................ [ 61%]
[ 2312s] -........................................................................ [ 62%]
[ 2312s] -........................................................................ [ 62%]
[ 2312s] -........................................................................ [ 63%]
[ 2312s] -........................................................................ [ 64%]
[ 2312s] -........................................................................ [ 64%]
[ 2312s] -....................................................................x... [ 65%]
[ 2312s] -........................................................................ [ 66%]
[ 2312s] -........................................................................ [ 66%]
[ 2312s] -........................................................................ [ 67%]
[ 2312s] -........................................................................ [ 68%]
[ 2312s] -........................................................................ [ 68%]
[ 2312s] -........................................................................ [ 69%]
[ 2312s] -........................................................................ [ 70%]
[ 2312s] -........................................................................ [ 70%]
[ 2312s] -........................................................................ [ 71%]
[ 2312s] -........................................................................ [ 72%]
[ 2312s] -........................................................................ [ 72%]
[ 2312s] -........................................................................ [ 73%]
[ 2312s] -........................................................................ [ 73%]
[ 2312s] -........................................................................ [ 74%]
[ 2312s] -........................................................................ [ 75%]
[ 2312s] -........................................................................ [ 75%]
[ 2312s] -........................................................................ [ 76%]
[ 2312s] -........................................................................ [ 77%]
[ 2312s] -........................................................................ [ 77%]
[ 2312s] -...................................................................xx... [ 78%]
[ 2312s] -........................................................................ [ 79%]
[ 2312s] -........................................................................ [ 79%]
[ 2312s] -........................................................................ [ 80%]
[ 2312s] -........................................................................ [ 81%]
[ 2312s] -........................................................................ [ 81%]
[ 2312s] -........................................................................ [ 82%]
[ 2312s] -........................................................................ [ 83%]
[ 2312s] -........................................................................ [ 83%]
[ 2312s] -........................................................................ [ 84%]
[ 2312s] -........................................................................ [ 85%]
[ 2312s] -........................................................................ [ 85%]
[ 2312s] -........................................................................ [ 86%]
[ 2312s] -........................................................................ [ 87%]
[ 2312s] -........................................................................ [ 87%]
[ 2312s] -........................................................................ [ 88%]
[ 2312s] -........s................s................s.................s....ss..... [ 89%]
[ 2312s] -........................................................................ [ 89%]
[ 2312s] -........................................................................ [ 90%]
[ 2312s] -........................................................................ [ 91%]
[ 2312s] -........................................................................ [ 91%]
[ 2312s] -........................................................................ [ 92%]
[ 2312s] -........................................................................ [ 92%]
[ 2312s] -........................................................................ [ 93%]
[ 2313s] -............................................................s........... [ 94%]
[ 2313s] -........................................................................ [ 94%]
[ 2313s] -........................................................................ [ 95%]
[ 2313s] -........................................................................ [ 96%]
[ 2313s] -....................................ss.................................. [ 96%]
[ 2313s] -........................................................................ [ 97%]
[ 2313s] -........................................................................ [ 98%]
[ 2313s] -............ssssssss.................................................... [ 98%]
[ 2313s] -..............................sss....................................... [ 99%]
[ 2313s] -................................................XXX.                     [100%]
[ 2313s] -=============================== warnings summary ===============================
[ 2313s] -../../../../../../../usr/lib/python3.8/site-packages/_pytest/config/__init__.py:1114
[ 2313s] -  /usr/lib/python3.8/site-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: hypothesis
[ 2313s] -    self._mark_plugins_for_rewrite(hook)
[ 2313s]  
[ 2313s] --- Docs: https://docs.pytest.org/en/stable/warnings.html-10457 passed, 518 skipped, 108 deselected, 18 xfailed, 3 xpassed, 1 warning in x.xx seconds (0:03:28)
[ 2313s] -
[ 2313s] --- /usr/bin/python3.8 (stderr)
[ 2313s] +++ nuitka (stderr)
[ 2313s] 
[ 2313s] @@ -1 +1,16 @@
[ 2313s] 
[ 2313s] +Nuitka-Plugins:WARNING: Use '--plugin-enable=numpy' for: Numpy support for at least 'numpy'.
[ 2313s] +Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
[ 2313s] +Traceback (most recent call last):
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/NumpyUsing.py", line 24, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/numpy/_pytesttester.py", line 125, in __call__
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/pytest/__init__.py", line 5, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/assertion/__init__.py", line 8, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/assertion/rewrite.py", line 31, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/assertion/util.py", line 14, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/_code/__init__.py", line 2, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/_code/code.py", line 45, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/_pytest/pathlib.py", line 445, in <module>
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/py/_vendored_packages/apipkg.py", line 148, in __makeattr
[ 2313s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.11.3/tests/standalone/NumpyUsing.dist/py/_vendored_packages/apipkg.py", line 69, in importobj
[ 2313s] +ModuleNotFoundError: No module named 'py._path'
[ 2313s]  
[ 2313s] Updating CPython cache by force due to non-matching comparison results.
```

**Comment by kayhayen** [comment]
We have a skip criterion in tests, that is used like this for a while now.
