### ISSUE TITLE
ImportError: import of scipy.optimize package is failing.

### ISSUE THREAD

**Issue by princethewinner** [Nuitka/Nuitka#971]
python -m nuitka --version

    0.6.11.5
    Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
    Executable: .............\AppData\Local\Programs\Python\Python36\python.exe
    OS: Windows
    Arch: x86_64

* Nuitka and Python Installation

    Python from microsoft installer.
    Nuitka using pip

* Reproducible using below example:

```
    from scipy.optimize import linear_sum_assignment

    def main():
        print(linear_sum_assignment)

    if __name__ == '__main__':
        main()

```
Compile Command:
`
python -m nuitka --follow-imports --plugin-enable=numpy --plugin-enable=qt-plugins --plugin-enable=pylint-warnings --show-progress --standalone test_compile.py
`

exe is building with the above command but the on execution it is failing with the error:

Traceback (most recent call last):
  File "D:\...\Test\compilation\nuitka_scipy_compile_test\test_compile.dist\test_compile.py", line 1, in <module>
  File "D:\...\Test\compilation\nuitka_scipy_compile_test\test_compile.dist\scipy\optimize\__init__.py", line 390, in <module scipy.optimize>
  File "D:\...\Test\compilation\nuitka_scipy_compile_test\test_compile.dist\scipy\optimize\optimize.py", line 37, in <module scipy.optimize.optimize>
  File "D:\...\Test\compilation\nuitka_scipy_compile_test\test_compile.dist\scipy\optimize\linesearch.py", line 18, in <module scipy.optimize.linesearch>
ImportError: LoadLibraryExW 'D:\...\Test\compilation\nuitka_scipy_compile_test\test_compile.dist\scipy\optimize\minpack2.pyd' failed: The specified module could not be found.

**Although minpack2.pyd exists on the specified path.**

Output of python -m pip freeze

   numpy==1.17.3
   scipy==1.1.0
   Nuitka==0.6.11.5

**Comment by Polokghosh53** [comment]
Can you redirect me to this code as I am not able to find it?

**Comment by kayhayen** [comment]
Using newer version of numpy and scipy, I cannot reproduce this. Downgrading my numpy seems to work, but scipy of that version  just won't be installable. But as newer one works, just use that.
