### ISSUE TITLE
modules not found when using --enable-plugin=multiprocessing

### ISSUE THREAD

**Issue by jgkeizer** [Nuitka/Nuitka#973]
modules are not found when using --enable-plugin=multiprocessing
everything is fine when --enable-plugin=multiprocessing is omitted.

versions:
------------------------------------------
windows 10cd te
python 3.8.5
nuitka 0.6.11.2 (tried develop version as well)

test1.py:
------------------------------------------
global text
text='hallo'
import test2

test2.py:
------------------------------------------
from test1 import text
print(text)

compiling and execution:
------------------------------------------
python -m nuitka --standalone test1.py
test1.exe:
hallo

python -m nuitka --standalone --enable-plugin=multiprocessing test1.py
test1.exe:
Traceback (most recent call last):
  File "C:\QUOKKA~1\test\TEST1~1.DIS\test1.py", line 3, in <module>
  File "C:\QUOKKA~1\test\TEST1~1.DIS\test2.py", line 1, in <module test2>
ModuleNotFoundError: No module named 'test1'

**Comment by kayhayen** [comment]
Works with recent Nuitka. The `__main__` module is duplicated if imported under a module name again.
