### ISSUE TITLE
Type Error on PyVisa

### ISSUE THREAD

**Issue by trapezoid677** [Nuitka/Nuitka#974]
python -m nuitka --version:

```
0.6.11.5
Python: 3.9.1 (default, Dec 13 2020, 11:55:53) 
Executable: /.../nuitka_test/venv/bin/python
OS: Linux
Arch: x86_64
```

Compile Command:

`python -m nuitka --follow-imports --plugin-enable=implicit-imports --standalone visa_test.py
`

Code to reproduce the problem:

```
import pyvisa as visa

rm_visa = visa.ResourceManager()
if rm_visa is not None:
    rm_visa.close()
```

The VISA libraries don't have to be installed, error is independent of that. The error happens as well under Windows 10, with the current development version 0.6.12.rc5 and with Python 3.8. Executable is building with the above command but the on execution it is failing (independent if --standalone or not) with the error :

```
Traceback (most recent call last):
  File ".../nuitka_test/visa_test.py", line 1, in <module>
    import pyvisa as visa
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../nuitka_test/venv/lib/python3.9/site-packages/pyvisa/__init__.py", line 22, in <module pyvisa>
    from .errors import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../nuitka_test/venv/lib/python3.9/site-packages/pyvisa/errors.py", line 13, in <module pyvisa.errors>
    from . import typing, util
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../nuitka_test/venv/lib/python3.9/site-packages/pyvisa/typing.py", line 12, in <module pyvisa.typing>
    from . import constants
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../nuitka_test/venv/lib/python3.9/site-packages/pyvisa/constants.py", line 19, in <module pyvisa.constants>
    from typing_extensions import Literal
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../nuitka_test/venv/lib/python3.9/site-packages/typing_extensions.py", line 2079, in <module typing_extensions>
    class _TypeAliasForm(typing._SpecialForm, _root=True):
TypeError: __mro_entries__() missing 1 required positional argument: 'bases

```

Output of python -m pip freeze

```
Nuitka==0.6.11.5
PyVISA==1.11.3
typing-extensions==3.7.4.3
```

**Comment by skabir8** [comment]
Did you find a solution for this?

**Comment by kayhayen** [comment]
This appears to be a commercial issue, please consider https://nuitka.net/pages/commercial.html if this is urgent, for now this won't be solved with any urgency yet.

**Comment by kayhayen** [comment]
So, I managed to reproduce this and get this fixed. I will keep you posted, once I have a test version of this available, right now there seem to be minor issues with that.

**Comment by kayhayen** [comment]
Your problem is solved here: https://nuitka.net/doc/factory.html (you can try this, but it's expected to work, I am getting the error that the VISA libraries are not installed for Python and Nuitka the same) and I expect to make a pre-release with this. I will keep you posted.

**Comment by trapezoid677** [comment]
I can confirm that the problem is solved with the files in factory.

**Comment by kayhayen** [comment]
Seems I forgot to add the tag, and close the issue at 0.6.13 release.
