### ISSUE TITLE
Nuitka Python 3.9 "FATAL: Error, expected output file hello.bin not created by AppImage."

### ISSUE THREAD

**Issue by projectintel-anon** [Nuitka/Nuitka#991]
I believe this is just a simple bug, but not entirely sure.

Ubuntu 20.10 Groovy Gorilla
0.6.12.2
Python: 3.9.0+ (default, Oct 19 2020, 09:51:18) 
Executable: /usr/bin/python3.9
OS: Linux
Arch: x86_64
When compiling any python file (this was done with --onefile and --linux-onefile-icon, even a simple print("Hello world"), it will give you an error saying **"FATAL: Error, expected output file hello.bin not created by AppImage."** despite the program output actually working. However, I did run into an instance where this did actually cause a fatal error.

Using Nuitka/Cython with Ursina (game engine), you will end up with an error:

```python3
Traceback (most recent call last):
  File "/home/enigmapr0ject/Desktop/Ursina/Dev1.dist/Dev1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/enigmapr0ject/Desktop/Ursina/Dev1.dist/ursina/__init__.py", line 10, in <module ursina>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/enigmapr0ject/Desktop/Ursina/Dev1.dist/ursina/window.py", line 309, in <module ursina.window>
  File "/home/enigmapr0ject/Desktop/Ursina/Dev1.dist/ursina/window.py", line 35, in __init__
  File "/home/enigmapr0ject/Desktop/Ursina/Dev1.dist/ursina/window.py", line 306, in __setattr__
TypeError: can't apply this __setattr__ to Window object
```
The command I ran to get this was:
```
python3.9 -m nuitka --onefile --linux-onefile-icon=/home/enigmapr0ject/Desktop/Ursina/icon.ico --plugin-enable=numpy --plugin-enable=pylint-warnings /home/enigmapr0ject/Desktop/Ursina/Dev1.py
```
Nuitka was installed with the https://nuitka.net/pages/download.html#debian-ubuntu-mint bash script and installed all dependencies with pip3.9 and APT.
The first fatal error message was a dud or just a bug, and the second was an actual fatal error.

**Comment by projectintel-anon** [comment]
Work around was Cython+GCC.
