### ISSUE TITLE
Issue with numpy/mkl

### ISSUE THREAD

**Issue by carlsc2** [Nuitka/Nuitka#994]
```
0.6.12.1
Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Executable: F:\miniconda3\envs\test\python.exe
OS: Windows
Arch: x86_64
```

With my conda environment, it seems that nuitka has trouble building numpy correctly.

I've managed to reproduce the issue with just this code:
```
import numpy as np
print(np.random.randint(0,20,(20,20)))
```

I used the following commands to compile:

```
python .\get-hints.py .\dumb_test.py
python .\nuitka-hints.py --mingw64 .\dumb_test.py
```

and also tried

```
python -m nuitka --standalone --mingw64 --plugin-enable=numpy .\dumb_test.py
```

and also

```
python -m nuitka --standalone --mingw64 .\dumb_test.py
```

However, for all of those different compile commands, I still always see the following output:

```
(test) PS F:\standalone_test> .\dumb_test.dist\dumb_test.exe
F:\standalone_test\dumb_test.dist\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
Traceback (most recent call last):
  File "F:\standalone_test\dumb_test.dist\dumb_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "F:\standalone_test\dumb_test.dist\numpy\__init__.py", line 231, in <module numpy>
AttributeError: module 'mkl' has no attribute 'get_version'
```

The relevant package versions are:
```
Nuitka==0.6.12.1
mkl-fft==1.2.1
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///C:/ci/numpy_and_numpy_base_1603466732592/work
```

Not sure what that numpy version is in the `pip freeze` output, but conda list says I have `numpy 1.19.2`

I'm sort of at a loss here, any help would be appreciated.

**Comment by kayhayen** [comment]
You were excluding the used command line though, that would be needed.

**Comment by carlsc2** [comment]
@kayhayen updated to include the various commands I tried

**Comment by carlsc2** [comment]
As another test, I just created a new conda environment and used pip to install my dependencies (as opposed to conda) and my nuitka compile did end up working. It seems that this is due to lack of mkl, as this is what I see:
```
>>> import numpy as np
>>> np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
```

in my previous environment, I see this:

```
>>> import numpy as np
>>> np.show_config()
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/miniconda3/envs/test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/miniconda3/envs/test\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/miniconda3/envs/test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/miniconda3/envs/test\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/miniconda3/envs/skurk\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/miniconda3/envs/test\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/miniconda3/envs/test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/miniconda3/envs/test\\Library\\include']
>>>
```

**Comment by kayhayen** [comment]
This is an interesting report, I will get to this once I get numpy debugged in #964 and it's interesting, because I wasn't aware of this config function. It surely points at things we need to check. Thanks for pointing this out.

**Comment by kayhayen** [comment]
This has long been solved and is no more reproducible.
