### ISSUE TITLE
python 3.9.2

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#996]
```
0.6.13rc3
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\andre\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

```
Nuitka-Plugins:INFO: numpy: Copied 1 file from 'numpy' installation.
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 185, in <module>
    main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\__main__.py", line 171, in main
    MainControl.main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 747, in main
    copyUsedDLLs(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nuitka\freezer\Standalone.py", line 1352, in copyUsedDLLs
    shutil.copyfile(dll_filename, target_path)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'E:\\TEST\\TEST\\TEST\\TEST.dist\\pythoncom39.dll'
```

**Comment by kayhayen** [comment]
@Pro100rus32 what happened?

**Comment by Pro100rus32** [comment]
> @Pro100rus32 what happened?

I don't know what happened, I updated Factory and I decided to use mingw. And the problem is gone.

**Comment by kayhayen** [comment]
ok, and please never open issues for using factory. You may use it, but don't send reports my way. Usually it's broken for extended times or brief periods and constantly changing. I don*t want to deal with reports not stemming from master or develop please.
