### ISSUE TITLE
TypeError using socketio and engineio

### ISSUE THREAD

**Issue by LeonardoRick** [Nuitka/Nuitka#999]
The `async` library `python-socketio` with it's dependency `python-engineio` are giving a type error after compilation with `nuitka`. This is the  complete `traceback`:

```
Traceback (most recent call last):
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\teste.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\socketio\__init__.py", line 3, in <module socketio>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\socketio\client.py", line 7, in <module socketio.client>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\engineio\__init__.py", line 8, in <module engineio>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\engineio\asyncio_client.py", line 7, in <module engineio.asyncio_client>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\aiohttp\__init__.py", line 6, in <module aiohttp>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\aiohttp\client.py", line 35, in <module aiohttp.client>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\aiohttp\http.py", line 7, in <module aiohttp.http>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\aiohttp\http_parser.py", line 15, in <module aiohttp.http_parser>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\aiohttp\helpers.py", line 48, in <module aiohttp.helpers>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\leona\iq\IQ-COP~1\TESTE~1.DIS\typing_extensions.py", line 1740, in <module typing_extensions>
TypeError: __mro_entries__() missing 1 required positional argument: 'bases'
```

This is my version of nuitka Installed via `pip`
```
$ python -m nuitka --version
0.6.12
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
```

* A minimal reproduceable example:
```python
import socketio
import asyncio
class AsyncSocketioTest:
    @classmethod
    async def create(cls):
        baseUrl = 'http://localhost:8070'
        self = AsyncSocketioTest()
        self.sio = socketio.AsyncClient()
        await self.sio.connect(baseUrl)

        @self.sio.event
        async def connect():
            print('im connected')

        @self.sio.event
        async def connect_error():
            print('error')

        @self.sio.event
        async def disconnect():
            print('Desconectado')

        return self

async def asleep():
    while True:
        await asyncio.sleep(1)

async def main():
    await AsyncSocketioTest.create()
    await asleep()

asyncio.get_event_loop().run_until_complete(main())
```

* Those are the packages related to the problem installed via `pip`
```
python-engineio==4.0.0
python-socketio==5.0.4
```

I can confirm that **the error  still happens in the `sync`  version of the library** too.

This is the comand use to generate the nuitka executable:
```
$ python -m nuitka --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package-data --mingw64 teste.py
./teste.dist/teste.exe
```

**Comment by kayhayen** [comment]
Use the latest hotfix, I am pretty sure you have an issue that got fixed there.

**Comment by LeonardoRick** [comment]
Could you please tell me how I do that?
Thanks a lot

**Comment by kayhayen** [comment]
Check out https://nuitka.net/pages/download.html
